### ISSUE TITLE
Disabling a slice value doesn't hide it's label

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#100]
The disabled value becomes hidden but the label is still visible.

```
slices.values[0].disabled = true;
```

https://codepen.io/team/amcharts/pen/2e41287a16d7d45f3c662a9bf049e4fa

![image](https://user-images.githubusercontent.com/174226/41805602-6aebf5e6-7662-11e8-8784-f1c57f3a6d3d.png)

**Comment by martynasma** [comment]
Two things:

1) It's not cool to access `series.slices` elements by its `values` property. It works in plain JS, but it will fail in languages that does type check because it's a private property.

Instead use `getIndex(1)`.

2) `PieSeries.slices` holds only the actual slice elements, not ticks or labels, hence they remaining visible.

You might want to visibility on the whole data item. Something like this:

```
pieSeries.events.on("shown", function (e) {
  e.target.dataItems.getIndex(1).visible = false;
});
```

Or, you can set it separately on `slices`, `labels`, and `ticks`, but the above seems easier.

Hope that makes sense.

**Comment by darlesson** [comment]
That makes sense. Thank you!
