### ISSUE TITLE
Hiding empty date values on dateAxis

### ISSUE THREAD

**Issue by themars** [amcharts/amcharts4#1000]
Hi! Is that a bug or I'm missing something? I have 2 series (with different date periods as you can see in the example), I want to hide one of them by clicking its name in legend, series disappears, but empty dates dont.

https://jsfiddle.net/7txgpkyo/

**Comment by martynasma** [comment]
Nope, it's by design.

DateAxis shows whole scope for all data. Regardless if the series is hidden or not - it's there.

I suppose you could implement your own logic. When series is hidden, you can zoom the chart to the remaining series. Or something like that.

I wish I had a demo for that, but we don't :(

**Comment by themars** [comment]
@martynasma Thank you, for your reply. I've found this way:
```
series1.events.on('visibilitychanged', (ev) => {
      ev.target.ignoreMinMax = !ev.visible;
      ev.target.chart.invalidateData();
    });
```
On large charts wouldn't be this code a problem?

**Comment by martynasma** [comment]
Re-validating data should be fine unless you have thousands of data points. The more data the longer it will take to re-validate it. I guess it depends on your particular data situation.
