### ISSUE TITLE
v4 Extreme Degradation of performance for XY Charts rendering (40 sec for 31 independant charts of less than 288 points (one day every 5 min points)

### ISSUE THREAD

**Issue by mdenoun** [amcharts/amcharts4#1004]
To render 31 charts only (not in a series but independently) each charts less than 288 points displayed in a table cell; took 41 sec while in v3 it took less than 2s.

**Comment by martynasma** [comment]
I don't think we're talking about performance degradation here.

In v3 all charts were building at once. Those 2 seconds were probably when whole browser was stalled.

In v4 there's a different approach in place. All build operations are queued and chunked, so that CPU load is manageable and browser remains responsive throughout the whole process. You probably see the first chart sooner than you see the first chart in similar setup on v3.

In any case, if you could provide a codepen for your setup, we'd surely take a look, if maybe there's some room for optimization.

**Comment by mdenoun** [comment]
Thank you very much Marty for your feedback, I will provide you with a small codepen by the end of this week. Thank you again for your help.

**Comment by mdenoun** [comment]
hello Marty,
Please find an angular example to reproduce this performance issue:
https://stackblitz.com/edit/angular-playground-fhgzzx?file=app%2Fcore%2Findex.ts
Let me know if I can help

**Comment by martynasma** [comment]
Thanks.

A few notes.

1) I have to admit that performance of `CategoryAxis` with many items (~300) in your case is not good in amCharts 4. We're looking for ways to speed it up.

That said, you are displaying date/time data, so why not use `DateAxis` instead? It will most certainly be faster.

2) Animations. Using animated theme with so many charts is not good.

While chart build itself is queued, the animations start playing immediately after chart is ready, so they are playing when another chart is building itself. Then the next, so we now have two charts trying to look fancy while the third one is building itself. Etc.

**Comment by mdenoun** [comment]
Great! Thank you very much I will try it soon.

________________________________
