### ISSUE TITLE
Chart with DateAxis and scrollbar freezes on zoom

### ISSUE THREAD

**Issue by FSJesseS** [amcharts/amcharts4#1006]
With the following configuration:

			chart.data = chartData;

			chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

			chart.maskBullets = false;

			let xAxis = chart.xAxes.push( new am4charts.DateAxis() );
			let yAxis = chart.yAxes.push( new am4charts.CategoryAxis() );

			yAxis.dataFields.category = "User_Id";
			xAxis.renderer.minGridDistance = 40;
			xAxis.dataFields.date = "Period";

			xAxis.renderer.grid.template.disabled = true;
			//yAxis.renderer.grid.template.disabled = true;
			xAxis.renderer.axisFills.template.disabled = true;
			yAxis.renderer.axisFills.template.disabled = true;
			yAxis.renderer.ticks.template.disabled = true;
			xAxis.renderer.ticks.template.disabled = true;

			yAxis.renderer.inversed = true;

			let series = chart.series.push(new am4charts.ColumnSeries());
			series.dataFields.categoryY = "User_Id";
			series.dataFields.dateX = "Period";
			series.dataFields.value = "Events";
			series.columns.template.disabled = true;
			series.sequencedInterpolation = true;
			//series.defaultState.transitionDuration = 3000;

			let bullet = series.bullets.push(new am4charts.CircleBullet());
			bullet.tooltipText = "{User_Id}, {Period.formatDate('yyyy-mm-dd')}: {Events}";
			bullet.strokeWidth = 3;
			bullet.stroke = am4core.color("#ffffff");
			bullet.strokeOpacity = 0;

			bullet.adapter.add("tooltipY", (tooltipY, target) => {
			  return -target.circle.radius + 1;
			})

			series.heatRules.push({property:"radius", target:bullet.circle, min:2, max:40});

			bullet.hiddenState.properties.scale = 0.01;
			bullet.hiddenState.properties.opacity = 1;

			let hoverState = bullet.states.create("hover");
			hoverState.properties.strokeOpacity = 1;

			chart.scrollbarY = new am4core.Scrollbar();
			chart.scrollbarX = new am4core.Scrollbar();

When I have more than 400 data items, the chart freezes on zoom.
If I change the DateAxis to a Category Axis the chart does not freeze.
[freeze_data_json.zip](https://github.com/amcharts/amcharts4/files/2903992/freeze_data_json.zip)

**Comment by martynasma** [comment]
I did try setting up your chart here:
https://codepen.io/team/amcharts/pen/9c708ccfd84984488f064bec6776a280?editors=0010

It does not freeze on zoom for me.

Am I missing something?

**Comment by FSJesseS** [comment]
Hi Marty,

The example you linked to does have the issue also.  If you zoom the X axis all the way in then drag the slider back and forth it will freeze.

**Comment by martynasma** [comment]
How long to I have to keep dragging slider back and forth for it to freeze? :) I did it for like a minute - no freeze.

![2019-02-27_17-25-01](https://user-images.githubusercontent.com/1458520/53501380-b8c5b600-3ab4-11e9-8bd0-a59342c24390.gif)

**Comment by FSJesseS** [comment]
It's actually when you pan across the data while zoomed in.  If you move the two end bits together and then drag the shortened scrollbar across the dateAxis it will definitely freeze.  The issue exists in Chrome, Firefox and Edge.  In Chrome once it freezes you can see chromes worker process for that tab chewing through memory until it hits about 2gb then stops.

**Comment by martynasma** [comment]
How close are we talking about?

I tried moving it as close as possible so the thumb part is still grabbable:

![image](https://user-images.githubusercontent.com/1458520/53679296-8cd44b80-3cd3-11e9-9a49-f24306a0f72c.png)

Dragged it back and forth like madman for a minute :) No freeze.

I'll ask the team to try that as well.

**Comment by FSJesseS** [comment]
Can you try a number of different OS's?  Everyone in my team is able to reproduce the issue on windows 10 in all browsers.  It is impossible to avoid actually 😬 I am amazed it is not happening for you.

**Comment by FSJesseS** [comment]
I tried to make a screen cap but the crash takes out the chrome capture thread also 💥

**Comment by FSJesseS** [comment]
Ahuh!  I've switched my locale settings from Australia/Sydney GMT+9 to Eastern US/Canada GMT-5 and it works!  Marty, if you switch time-zones to Sydney/Melbourne you should be able to recreate the issue 😁

**Comment by martynasma** [comment]
Oh boy, an Aussie-only problem :P

Alright, thanks. Now we'll have to do some digging, provided dev team can reproduce this.

Will keep you posted.

**Comment by martynasma** [comment]
Yup, was able to reproduce it with Sydney timezone.

**Comment by FSJesseS** [comment]
Mostly a Sydney & Melbourne problem I think.  Brisbane doesn't seam to be affected and they do not use daylight savings time.  DST will end here in Sydney on April 7th.  I would not be surprised if the bug magically disappeared on that day 😁

**Comment by martynasma** [comment]
Fixed in [4.2.2](https://github.com/amcharts/amcharts4/releases/tag/4.2.2).

## [4.2.2] - 2019-03-13

### Added
- `cursorHoverEnabled` added to `XYSeries`. Controls whether to trigger hover state on columns/bullets of the all series under hovered category/date.
- A new `plugins` property on all `Sprite`. [More info](https://www.amcharts.com/docs/v4/concepts/plugins/).
- New plugin: Regression. [More info](https://www.amcharts.com/docs/v4/tutorials/regression-trend-lines/).
- New `ExportMenu` setting: `closeOnClick` (default `true`). Will force export menu to close when export is initiated.

### Changed
- `DateFormat` will now parse even partial dates, e.g. format `"yyyy-MM-dd"` will parse `"2018"` correctly, and will assume Jan 1st.

### Fixed
- Export: `getImage()`/`getSVG()` will now correctly omit `exportable = false` elements.
- Export: Data export was not taking in additional columns after data updates.
- Some chart cloning issues fixed.
- Inccorrect behavior of Series' tooltip with `minBulletDistance` set fixed.
- Sometimes, when series had only one data item, chart used to zoom-in right after the init.
- In-line date formatting will now use `DateFormatter`'s parsing functions for string-based dates.
- `DateAxis` issues with certain timezones fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
