### ISSUE TITLE
Container with children fails with JSON config (the children are duplicated)

### ISSUE THREAD

**Issue by ismdiego** [amcharts/amcharts4#1010]
When creating a container with two basic children (two rectangles), the settings with JS work as expected:
https://jsfiddle.net/0tpcmgdh/

But when using a JSON config, the two rectangles specified in the children array (as seen in the documentation) are duplicated:
https://jsfiddle.net/m6ujxh7q/

Even the first simple example is failing with JSON:
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Assigning_elements_to_Container

(you can inspect the created elements and a 2 item array is created)

I have tested this with the latest released version (4.1.12), but it fails since 4.0.0, although from 4.0.8 onwards the array is created at least with the two rectangle children (4.0.0 - 4.0.7 created only one duplicated rectangle). This must be thanks to one fix for 4.0.8 "JSON: Adding elements to children via array syntax was not working properly." But anyway, they are still created duplicated.

**Comment by martynasma** [comment]
Thanks for the heads up! Bug confirmed.

Will ping you once the fix is available.

**Comment by martynasma** [comment]
Fixed in [4.1.14](https://github.com/amcharts/amcharts4/releases/tag/4.1.14).

## [4.1.14] - 2019-03-01

### Changed
- Hiding or showing an element will now automatically set its `readerHidden` attribute accordingly.

### Fixed
- JSON: Using `children` with an array value was duplicating elements.
- Working around a bug with Angular's dead code elimination in `--prod` mode.
- Fixed `ValueAxis` issue with animation when there's only single data item.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
