### ISSUE TITLE
Question : SankeyDiagram with drill down to child data

### ISSUE THREAD

**Issue by etranchi** [amcharts/amcharts4#104]
Hello,

I'm doing a SankeyDiagram with a tree map structure, what i wanted to do is a drill down into the children when we click on it (showing a new SankeyDiagram based on children data set).

It is possible to have the same feature that have the TreeMap Chart (NavigationBar and Level) in a SankeyDiagram ? 
How could i implement this myself ? Any advice ?

**Comment by martynasma** [comment]
Technically, no - there's no built-in drill-down capabilities in Sankey Diagram.

That said, give me a few days. I'll take a stab at implementing a demo that does that.

**Comment by martynasma** [comment]
OK, so drill-down itself is easy. However, using `NavigationBar` with Sankey chart is a bit trickier. We will need to make some changes to the charts to enable that. Might take a week or two. Hope it's not too late.

Will keep you posted.

**Comment by martynasma** [comment]
@etranchi thanks for holding your breath!

Since beta.32 (released yesterday) now allows much wider usage of `NavigationBar`, I whipped up this tutorial:

https://www.amcharts.com/docs/v4/tutorials/drill-down-sankey-diagram/

You'll find detailed explanation, as well as fully functioning demo of Sankey drilldown with breacrunb nav.

P.S. closing this (non)issue, but please feel free to ask your questions, should you have any.
