### ISSUE TITLE
Tick location is ignored on a vertical axis

### ISSUE THREAD

**Issue by bosiljkakostic** [amcharts/amcharts4#1052]
1. categoryAxis.renderer.ticks.template.location = 0.5 does not work
tick stay at start and end of the cell
2. y-axis is not showing when x-axis does not start from the beginning of the grid. How I can set that y-axis is always  visible
![problemDescription](https://user-images.githubusercontent.com/48427836/54111662-b7658900-43e4-11e9-865a-bbddbb84f7f4.jpg)

**Comment by martynasma** [comment]
Can you post a working chart code on CodePen? Thanks.

**Comment by bosiljkakostic** [comment]
The picture is from to complicate example,
we can use this example: https://jsfiddle.net/bosiljkakostic1/65echf0n/53/
also in that example, I wanted to set legend shape marker to custom bullets and,  I  put
bullet1.copyToLegendMarker = true;
bullet2.copyToLegendMarker = true;
but legend marker stay rectangles not triangle and circle

**Comment by bosiljkakostic** [comment]
https://jsfiddle.net/bosiljkakostic1/65echf0n/54/

**Comment by bosiljkakostic** [comment]
the last link is ok

**Comment by bosiljkakostic** [comment]
or this is more as first picture https://jsfiddle.net/bosiljkakostic1/65echf0n/59/ (sorry, jsfiddle saves under different name whenever I do save)

**Comment by martynasma** [comment]
Thanks!

Indeed, `location` seems to be ignored on ticks on a vertical axis. Will need to fix this.

**Comment by martynasma** [comment]
As for the axis line, it's disabled by default.

Use this to enable:

```
categoryAxis.renderer.line.strokeOpacity = 1;
```

**Comment by bosiljkakostic** [comment]
Thanks for categoryAxis.renderer.line.strokeOpacity = 1;, please look at how I can make legend markers
to have shape of bullets, 
bullet1.copyToLegendMarker = true;
bullet2.copyToLegendMarker = true;
do not work

**Comment by martynasma** [comment]
Please open separate issues for unrelated questions, or we'll have a mess on our hands.

**Comment by martynasma** [comment]
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by bosiljkakostic** [comment]
Thanks, it is corrected when I use directly
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
But, when I download amchats lib either from site or gihub, it do not work. When I manually replace contents of core.js and charts.js from https://www.amcharts.com/lib/4/ it work.
It is not important, thanks
