### ISSUE TITLE
Hidden stacked series affect column stacks after data update

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#1053]
Having an issue with Stacked Column XY Chart. 

I am trying to pre-configure a Stacked Column XY Chart's visible series before setting the chart data. See [this pen](https://codepen.io/cam-m/pen/ywXyrw).

The flow is:
1. Create the chart from config
2. Request Data from server (async, so below procedure continues)
2. Apply a user's stored filter to the chart (E..g hide one or more series)
3. When the data is returned set the chart data.

The issue is that I get gaps in the stacked columns. The size of the gap indicates that the chart is calculating a stacked column's position in the chart based on all series being visible, whereas it should calculate the position based only on what is visible.

![amcharts-stacked-column-bug](https://user-images.githubusercontent.com/629645/54120826-e0216900-444c-11e9-9094-e85e9c69aa09.jpg)

Interestingly if I immediately set the data after configuring series visibility the issue doesn't occur. It only occurs if I delay when the data is set. 

To simulate a delay before data is set, use the the button 'setData' after the chart is loaded.

The issue only started after upgrading from v4.0.8 to v4.1.14. Also looked similar to issue #198.

Also, an aside question - how can I programatically replicate clicking one of the legend markers to filter the series in the chart? My buttons don't animate the series, again leaving gaps in the chart - not sure what I'm doing wrong.

Let me know if you need further information and thanks in advance for you help,

Cam

**Comment by martynasma** [comment]
### Here's a summary of the issue for the dev team

In a stacked ColumnSeries scenario, if a chart has its data set and has a series pre-hidden (`hidden = true`), everything works fine. The remaining visible columns are shown in a stack from zero line.

![image](https://user-images.githubusercontent.com/1458520/54364397-7df77c80-4675-11e9-9794-eeade337263d.png)

Example:
https://codepen.io/team/amcharts/pen/2a4eb82e297839c5bbe0a4afa7ca42dc?editors=0010

Now, in the same scenario, where chart starts without data, but later receives it, e.g. after AJAX load, the stacks still are missing hidden series, but they are arranged as it was there:

![image](https://user-images.githubusercontent.com/1458520/54364522-b6975600-4675-11e9-9402-7b4a84f014e3.png)

Example:
https://codepen.io/team/amcharts/pen/8cbb74c203201a47f3dcb8ffcf01d7cf?editors=0010

**Comment by cam-m** [comment]
Any update guys?

**Comment by martynasma** [comment]
Working on it. Sorry for the wait.

**Comment by martynasma** [comment]
Fixed in [4.2.5](https://github.com/amcharts/amcharts4/releases/tag/4.2.5).

## [4.2.5] - 2019-03-21

### Added
- New property `minPolylinestep` added to global `am4core.options`. Setting to bigger value (default: `0.5`) allows simplification of multi-point lines.
- Export: new setting `useSimplifiedExport` (default: `true`). Setting to `false` will force use of external library (canvg) for all exports.

### Fixed
- `XYCursor` with pan behavior used to remain in "grabbing" mode after click on zoom out button.
- Export: Menu was not working properly on Mobile Safari.
- Export: Menu was not working properly on Android Chrome.
- Export: Exporting of PDF/XSLX is now supported on Mobile Safari.
- Export: Exporting images in IE9 was broken.
- Stacks with pre-hidden series were showing incorrectly.
- `DateAxis` no longer ignores `renderer.tooltipLocation`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by cam-m** [comment]
Fix worked great - thanks @martynasma!
