### ISSUE TITLE
CSV export not in sync with dynamic data

### ISSUE THREAD

**Issue by ciarancourtney** [amcharts/amcharts4#1054]
https://stackblitz.com/edit/amcharts4-bug-export-dynamic-series

#### Working
1. Add series1
2. Add series2
3. Export CSV

#### Not working
1. Add series1
2. Export CSV
3. Add series2
4. Export CSV **CSV will be same as step 2**

Also if removing a series from the `data` prop, the header will still be contained in the CSV (not implemented in stackblitz example)

FYI I'm still waiting on a response to my semi-related issue in https://github.com/amcharts/amcharts4/issues/926 Overall I still think there are large gaps to be filled with regards to dynamically adding/removing time-series to a chart. A fully working codepen tutorial in docs would be good.

**Comment by martynasma** [comment]
Thanks for the heads up. Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.2.2](https://github.com/amcharts/amcharts4/releases/tag/4.2.2).

## [4.2.2] - 2019-03-13

### Added
- `cursorHoverEnabled` added to `XYSeries`. Controls whether to trigger hover state on columns/bullets of the all series under hovered category/date.
- A new `plugins` property on all `Sprite`. [More info](https://www.amcharts.com/docs/v4/concepts/plugins/).
- New plugin: Regression. [More info](https://www.amcharts.com/docs/v4/tutorials/regression-trend-lines/).
- New `ExportMenu` setting: `closeOnClick` (default `true`). Will force export menu to close when export is initiated.

### Changed
- `DateFormat` will now parse even partial dates, e.g. format `"yyyy-MM-dd"` will parse `"2018"` correctly, and will assume Jan 1st.

### Fixed
- Export: `getImage()`/`getSVG()` will now correctly omit `exportable = false` elements.
- Export: Data export was not taking in additional columns after data updates.
- Some chart cloning issues fixed.
- Inccorrect behavior of Series' tooltip with `minBulletDistance` set fixed.
- Sometimes, when series had only one data item, chart used to zoom-in right after the init.
- In-line date formatting will now use `DateFormatter`'s parsing functions for string-based dates.
- `DateAxis` issues with certain timezones fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ciarancourtney** [comment]
Hi @martynasma I can conform that this is fixed alright, but whatever fixed https://github.com/amcharts/amcharts4/issues/979 is a show stopper for me (intermittent crash when adding new series)

**Comment by ciarancourtney** [comment]
Hi @martynasma just checking in on my crashing issue, you seem to be continuing to add new features to amcharts without focusing on stability/perf, I feel at this stage this should be your highest priority, based on issues others are raising. We are getting ready to release in the coming months and may have to revert our discussion on wither or not to purchase a license and switch to highcharts if these issues are not resolved soon.
