### ISSUE TITLE
Tooltips set directly on series objects (columns/bullets) flickering but not showing

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1066]
Tooltips that used to be shown are no longer visible. They only flicker is you move the mouse around the chart, but don't show on hover. See example here: https://codepen.io/npc42/pen/EGJEKB

This used to work up until one of the recent versions (I haven't updated for a while, so only see it in 4.2.0 and 4.2.1).

**Comment by martynasma** [comment]
Looks like a bug.

Here's a mini-version for the dev team:
https://codepen.io/team/amcharts/pen/a2ea63e4337a388cb8924bdfcb55c4c9

Funny, same chart with `CategoryAxis` works fine:
https://codepen.io/team/amcharts/pen/1cfde85b891cb896c6f035017dd456c4

**Comment by martynasma** [comment]
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by NPC** [comment]
@martynasma hmm, this version is not yet available on https://www.amcharts.com/download/, and my codepen still flickers, so CDN is not updated yet either? I'll try from git dist folder.

**Comment by NPC** [comment]
@martynasma looks fixed, thank you so much for such a quick response! You guys need to pace yourselves :)
