### ISSUE TITLE
Different format on Axes

### ISSUE THREAD

**Issue by Calandal95** [amcharts/amcharts4#107]
Hi all,

i have a bar chart created with AmCharts 4.
Both X and Y axes of the chart contains numeric labels, but i need a different format for each one.
I tried to set formats as follows: 

> chart.numberFormatter.formatNumber ='#,###.##'; 
> yAxis.numberFormatter.numberFormat = "#";

The expected behaviour should be that the Y Axis was formatted as a number without separators and X axis as a number separated by thousands and decimals with dot and comma (according to my locale).

The result is that the last instruction generally overrides all the other formats.
I guess there should be some kind of problems.

Regards
Alessio

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **37793**.
> (replying here will automatically notify amCharts support agent)

Hi Alessio,

This is happening because all child objects inherit `numberFormatter` from their ascendants. So if you access `numberFormatter` on an axis, it goes all the way and returns NumberFormatter from the chart. If you change the format on it, you change it for the whole chart.

The solution is to create an own instance of the `NumberFormatter` for the specific axis.

```
xAxis.numberFormatter = new am4core.NumberFormatter();
xAxis.numberFormatter.numberFormat = "#";
```

Yours sincerely,

Martynas Majeris
amCharts

P.S. have you seen upcoming amCharts 4 yet?
https://www.amcharts.com/v4

**Comment by Calandal95** [comment]
Thank you! This fixed my issue! Keep with the great work you're doing with amChart4!

**Comment by martynasma** [comment]
You're welcome!
