### ISSUE TITLE
error: Property 'target' in type 'Plugin' is not assignable to the same property in base type 'IPlugin'

### ISSUE THREAD

**Issue by develar** [amcharts/amcharts4#1079]
Since 4.2.2.

```
ERROR in <project path>/node_modules/@amcharts/amcharts4/.internal/core/utils/Plugin.d.ts
42:5 Property 'target' in type 'Plugin' is not assignable to the same property in base type 'IPlugin'.
  Type 'Optional<Sprite>' is not assignable to type 'Sprite'.
    Type 'undefined' is not assignable to type 'Sprite'.
    40 |      * A target object plugin is for.
    41 |      */
  > 42 |     target: Optional<Sprite>;
       |     ^
    43 |     /**
    44 |      * Is this object disposed?
    45 |      */
Version: typescript 3.3.3333
```

tsconfig:
```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "esnext",
    "strict": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "newLine": "LF",
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by martynasma** [comment]
Fixed in [4.2.4](https://github.com/amcharts/amcharts4/releases/tag/4.2.4).

## [4.2.4] - 2019-03-19

### Added
- `autoGapCount` added to `LineSeries`. If `connect = false` and distance between two data points is bigger than `baseInterval * autoGapCount`, a line will break automatically.

### Fixed
- `IPlugin` now accepts `Optional<Sprite>`.
- `XYCursor` will not longer obstruct page scroll if its `behavior` is set to `"none"`.
- JSON config: setting `geodata` by name (e.g. "worldLow") directly in `MapSeries` was not working.
- JSON config: Instantiating new `ColorSet` objects was not working properly.
- `DateFormatter` was not parsing dates like "20180101" (no separators) correctly.
- An issue with `DateAxis` and milliseconds fixed.
- `dataItem.locations.dateX` on `LineSeries` was not working properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
