### ISSUE TITLE
Q: What happens when someone clicks on the legend label? 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1080]
I would like to know what happens if one clicks on the legend label. 

- I want to know what axis are hidden or shown 
- I want to know how is a series shown/or hidden since `hide()` behaves differently from `.hidden` on a series
- I want to know how can one detect and override that behavior 

I want to achieve that once one clicks on a label the correct axis are shown, merging some axes, and overriding some default for grouping.

**Comment by martynasma** [comment]
Nothing happens when user clicks on a legend labels. It does not have any events attached.

Now, the whole "item container" (which holds marker, label, and value label elements) has a "hit" event attached, which triggers `hide()` or `show()` on relative Series.

Take a look at the code here:
https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/Legend.ts#L191

And here:
https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/Legend.ts#L750

What's to be done next, depends on what you are trying to achieve. Do you want to disable clicks on markers/value labels, and add custom events on label clicks?

**Comment by jimmykane** [comment]
What I have done so far: 
```
chart.legend.itemContainers.template.events.on("toggled", (ev) => {
        const series = <am4charts.LineSeries>ev.target.dataItem.dataContext;
        // Getting visible...
        if (!ev.target.readerChecked === true) {
          this.showSeriesYAxis(series)
        } else {
          this.hideSeriesYAxis(series)
        }
      });
```

The only boolean I can access is this `ev.target.readerChecked` 

Before I would hide the series as well thanks for letting me know how this works.

**Comment by martynasma** [comment]
You should probably use `ev.target.isActive` (`true` means item is toggled off; I know it's a bit counterintuitive)
