### ISSUE TITLE
WordCloud colors from createFromConfig not working

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1083]
We can't create WordCloud from config with custom colors

We have this errors : 

> this.component.colors.next is not a function

But here we have an exemple but it's not working : https://github.com/amcharts/amcharts4/blob/master/src/.internal/plugins/wordCloud/WordCloudSeries.ts#L751

`{
	data: [{
			word: "cervelo frameset closeout",
			value: 10
		},
		{
			word: "korean queen seon deok",
			value: 30
		},
		{
			word: "osseo maple grove hockey association",
			value: 10
		},
		{
			word: "closeout north face jackets",
			value: 40
		},
		{
			word: "jennifer lopez deseo perfume",
			value: 20
		},
		{
			word: "closeout soccer cleats",
			value: 10
		},
		{
			word: "nordstrom closeout",
			value: 20
		},
		{
			word: "closeout designer sunglasses",
			value: 50
		},
		{
			word: "ralph lauren closeout bedding",
			value: 10
		}
	],
	series: [{
		randomness: 0,
		angles: 45,
		dataFields: {
			value: "value",
			word: "word"
		},
		labels: {
			template: {
				text: "{word}"
			}
		},
		colors: {
			type: "ColorSet",
			list: [
				"#51a7fa",
				"#72bf4a",
				"#f5d428",
				"#f2902d",
				"#ea5e5b",
				"#b26edf",
				"#4591da",
				"#60a63d",
				"#d1b728",
				"#d07d19",
				"#c95250",
				"#995dc6",
				"#3e82c6",
				"#55943b",
				"#b9a328",
				"#b8701c",
				"#b24a4c",
				"#8854b4",
				"#3773b1",
				"#4b8339",
				"#a29129",
				"#a1641d",
				"#9c4347",
				"#774ca2"
			]
		}
	}]
}`

Thx

**Comment by martynasma** [comment]
Thanks! Looks like a bug. Let you know when a fix is available.

**Comment by martynasma** [comment]
https://codepen.io/team/amcharts/pen/b6c3dab48c85609cd21994415c5be3ac?editors=0010

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by Identity-labs** [comment]
Thx, 

We can't access to the dev version for testing ?
I have a commercial licence.

**Comment by martynasma** [comment]
No, I'm afraid. We should release it publicly within couple of days, though.

**Comment by martynasma** [comment]
Fixed in [4.2.4](https://github.com/amcharts/amcharts4/releases/tag/4.2.4).

## [4.2.4] - 2019-03-19

### Added
- `autoGapCount` added to `LineSeries`. If `connect = false` and distance between two data points is bigger than `baseInterval * autoGapCount`, a line will break automatically.

### Fixed
- `IPlugin` now accepts `Optional<Sprite>`.
- `XYCursor` will not longer obstruct page scroll if its `behavior` is set to `"none"`.
- JSON config: setting `geodata` by name (e.g. "worldLow") directly in `MapSeries` was not working.
- JSON config: Instantiating new `ColorSet` objects was not working properly.
- `DateFormatter` was not parsing dates like "20180101" (no separators) correctly.
- An issue with `DateAxis` and milliseconds fixed.
- `dataItem.locations.dateX` on `LineSeries` was not working properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
