### ISSUE TITLE
Date is incorrect when using like 'yyyymmdd' in inputDateFormat

### ISSUE THREAD

**Issue by jungti1234** [amcharts/amcharts4#1093]
'yyyy-MM-dd' is works fine in inputDateFormat.
but there is problem when I using like 'yyyyMMdd'.

if input value is '2012-07-27',
it shows '2012-07-27' when I using 'yyyy-MM-dd'.

but input value is '20120727',
it shows '201207-02-07' when I using 'yyyyMMdd'.

I think it seems may be there is problem....

**Comment by martynasma** [comment]
Thanks for the heads up. Bug confirmed.

Will let you know when the fix is available.

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.2.4](https://github.com/amcharts/amcharts4/releases/tag/4.2.4).

## [4.2.4] - 2019-03-19

### Added
- `autoGapCount` added to `LineSeries`. If `connect = false` and distance between two data points is bigger than `baseInterval * autoGapCount`, a line will break automatically.

### Fixed
- `IPlugin` now accepts `Optional<Sprite>`.
- `XYCursor` will not longer obstruct page scroll if its `behavior` is set to `"none"`.
- JSON config: setting `geodata` by name (e.g. "worldLow") directly in `MapSeries` was not working.
- JSON config: Instantiating new `ColorSet` objects was not working properly.
- `DateFormatter` was not parsing dates like "20180101" (no separators) correctly.
- An issue with `DateAxis` and milliseconds fixed.
- `dataItem.locations.dateX` on `LineSeries` was not working properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
