### ISSUE TITLE
Tooltips from series attached to different DateAxes overlap

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#1096]
I was showing a co-worker the [Multiple Date Axes demo](https://www.amcharts.com/demos/multiple-date-axes/?theme=dark) and noticed tooltip overlapping. I know this has been an issue in the past, but it looks like it needs to be reopened.

![image](https://user-images.githubusercontent.com/23387905/54615839-22dad680-4a35-11e9-8747-f615b15306e8.png)
Chrome 73.0.3683.75 (Official Build) (64-bit)

I also navigated to this demo on my iPhone (Chrome app) and noticed the same behavior.

![image](https://user-images.githubusercontent.com/23387905/54615916-4867e000-4a35-11e9-9d74-0e80c6a0d36e.png)

**Comment by martynasma** [comment]
This seems to be happening when series are attached to separate Date axes.

That issue you mentioned is still solved - same axis series do not overlap their tooltips.

**Comment by jungti1234** [comment]
in addition, there is one minor wrong thing in demo.

![제목 없음](https://user-images.githubusercontent.com/17401597/54666254-a0cdd900-4b2c-11e9-8b10-af944bd5a6cc.png)

**Comment by martynasma** [comment]
Thanks. Fixed the demo.

**Comment by martynasma** [comment]
Fixed in [4.3.15](https://github.com/amcharts/amcharts4/releases/tag/4.3.15).

## [4.3.15] - 2019-04-06

### Added
- `startendchanged` event added to `Component`. Fired when `start` or `end` is changed. Unlike `startchanged`/`endchanged` this event is fired not immediately but at the end of a cycle.

### Changed
- `Sunburst` chart's defaalt `radius` set to `95%`.

### Fixed
- `TreeMap` could produce a JS error if data was changed during interaction with the map.
- If `Component.addData()` called before chart was initialized, error happened.
- 3D columns with reversed base axis had wrong z-indexes.
- `DateAxis`-based chart with single data item got into infinite loop if `startLocation` and `endLocation` were set to `0.5` or `strictMinMax` was set to `true`.
- Tooltips of series could overlap if series used different `DateAxis` axes.
- Chart with multiple `DateAxis` and no animated theme was not properly zooming with scrollbar.
- Implemented a workaround for MSIE which was not updating series masks on chart resize.
- Disposing `XYCursor` will now remove series/axes tooltips that might be currently displayed because of it.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
