### ISSUE TITLE
First column does not show all points

### ISSUE THREAD

**Issue by rdibenedetto** [amcharts/amcharts4#1103]
In the following Pen I have a column serie based on openValueY, valueY and dateX. 
You can see the first column does not show correctly the point that it should to show. 
The first column is built in the same way of the other but as you can see it is a different result. 
In particular in the first column (10:00:00) we have only 1 float column that is the last declared one. The column with date 22:00:00 has  all 5 point declared.

This is the link of the Pen: https://codepen.io/roger710/pen/WmaxGB

It is a Bug?

**Comment by martynasma** [comment]
Looks like a bug. We'll need to take a look.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.3.3](https://github.com/amcharts/amcharts4/releases/tag/4.3.3).

## [4.3.3] - 2019-03-27

### Fixed
- `MapPolygonSeries.geodataSource` was not working.
- `MapChart` was not showing data if `geodata` was set later than data on series.
- When there were multiple data items with identical timestamps on `DateAxis`, the first ones could have been ignored.
- Even if `legend.itemContainer.template.togglable` was set to `false`, Legend item was stil togglable.
- Extra graticules (grid) was shown in `GraticuleSeries` unders some conditions.
- Tooltips on a logarithmic `ValueAxis` were showing wrong values.
- Value label for "0" could sometimes appear on top of logarithmic `ValueAxis`.
- `MapChart` position was not correct if padding was set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
