### ISSUE TITLE
"Lost label" of 0 on top of logarithmic Value Axis

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1105]
Please have a look at this demo: https://codepen.io/team/amcharts/pen/xBQwgR?editors=0011.

It's a simple Column Chart with a logarithmic value axis. Somehow the 0-label is outputted on top of the value axis; it should of course be at the bottom.

![Screenshot 2019-03-21 at 12 53 14](https://user-images.githubusercontent.com/13300227/54750835-56566600-4bd9-11e9-8cde-d88fc8a77211.png)

**Comment by martynasma** [comment]
Fixed in [4.3.3](https://github.com/amcharts/amcharts4/releases/tag/4.3.3).

## [4.3.3] - 2019-03-27

### Fixed
- `MapPolygonSeries.geodataSource` was not working.
- `MapChart` was not showing data if `geodata` was set later than data on series.
- When there were multiple data items with identical timestamps on `DateAxis`, the first ones could have been ignored.
- Even if `legend.itemContainer.template.togglable` was set to `false`, Legend item was stil togglable.
- Extra graticules (grid) was shown in `GraticuleSeries` unders some conditions.
- Tooltips on a logarithmic `ValueAxis` were showing wrong values.
- Value label for "0" could sometimes appear on top of logarithmic `ValueAxis`.
- `MapChart` position was not correct if padding was set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
