### ISSUE TITLE
Add support for stacked charts with logarithmic axes

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1106]
We're currently unable to use the stacked feature in conjunction with logarithmic axes since stacked charts always start their value axes at zero. Using the two together results in a `Logarithmic value axis can not have vales <= 0.` error. This can be worked around in v3 by using `treatZeroAs` but there doesn't seem to be an equivalent solution for v4.

[Codepen](https://codepen.io/team/amcharts/pen/cf07c493b45e171fb65c9b8ed703024a?editors=0010)

**Comment by sanshan** [comment]
I join this post. There is a problem with the logarithmic representation together with the "stacked" parameter.

What should I do if I have purchased a license and I need this particular feature?

**Comment by martynasma** [comment]
Fixed in [4.9.34](https://github.com/amcharts/amcharts4/releases/tag/4.9.34).

## [4.9.34] - 2020-07-31

### Added
- New bullet `ShapeBullet` in `Bullets` plugin. Please refer to [this documentation article](https://www.amcharts.com/docs/v4/tutorials/plugin-bullets/) for more info.
- `treatZeroAs` added to `ValueAxis`. Use it to work around zero-value restriction on a logarithmic scale.
- `stackToNegative` (default: `true`) added to `XYSeries`. Determines whether negative values in a stack will stack in relation to base (zero) line (`true`; default) or in relation to the previous value in the stack (`false`).

### Changed
- [xlsx](https://www.npmjs.com/package/xlsx) dependency was updated from `0.15.4` to `0.16.4`.
- Tooltip snapping on `DateAxis` now takes Series' location into account.

### Fixed
- Regression plugin: `reorder` option was not working properly.
- `snapToSeries` was not working properly if there was a hidden Series with exactly the same value as the other visible Series.
- `TreeMap` and `ForceDirectedTree` with a single data item and no children were not working properly with chart legend.
- Horizontal (X) Axis tooltip in a very small document was sometimes positioned with an offset.
- `zoomToRectangle()` method of `MapChart` with `deltaLongitude` was not working properly if a rectangle crossed the 180 meridian.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Pay attention to the new `ValueAxis` setting: `treatZeroAs`.
