### ISSUE TITLE
Legend itemContainers width

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1109]
Hi,

When we set the legend position as top, the itemContainers width 100% is not working, but it work's with legend position as bottom.

`{legend: {
itemContainers: {
template: {
width: "100%"
}
},
position: "top"
}}`

Thx

**Comment by martynasma** [comment]
OK, so this is because of the fuzzy logic.

When you set `position` of the legend, it also sets some properties to the template of the `itemContainers`. If position is "top" or "bottom", one of the things it resets is item container width.

The reason why it works for "bottom" is that "bottom" is default, so it does nothing, hence no reset.

To fix, simply move your `position: "top"` setting before `itemContainers` block.
