### ISSUE TITLE
Value Axis tooltips display non-logarithmic values when axis is logarithmic

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1111]
Please have a look at this demo: https://codepen.io/team/amcharts/pen/56af42b2d5e783377a23c4c3c41f1571?editors=0010

The chart in the demo has 2 logarithmic value axes. It also has a Chart Cursor enabled with tooltips on each axis.

Although the value axis tooltips display at the right location, they do not display the right value. They display a value as if the value axes were non-logarithmic.

![image](https://user-images.githubusercontent.com/13300227/54866043-9ea78c80-4d6f-11e9-9b45-bb672b94f8a0.png)

In the example from the screenshot, both value axis tooltips should display  ~1,760 instead of 6,338.

**Comment by martynasma** [comment]
Bug confirmed. Thanks!

**Comment by martynasma** [comment]
Fixed in [4.3.3](https://github.com/amcharts/amcharts4/releases/tag/4.3.3).

## [4.3.3] - 2019-03-27

### Fixed
- `MapPolygonSeries.geodataSource` was not working.
- `MapChart` was not showing data if `geodata` was set later than data on series.
- When there were multiple data items with identical timestamps on `DateAxis`, the first ones could have been ignored.
- Even if `legend.itemContainer.template.togglable` was set to `false`, Legend item was stil togglable.
- Extra graticules (grid) was shown in `GraticuleSeries` unders some conditions.
- Tooltips on a logarithmic `ValueAxis` were showing wrong values.
- Value label for "0" could sometimes appear on top of logarithmic `ValueAxis`.
- `MapChart` position was not correct if padding was set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
