### ISSUE TITLE
togglable for basic series is always true

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1117]
Hey amchats team,
I have upgrade my version from 4.2.0 to 4.2.6 and I have notice a strange behavior, when you define togglable of legend as false:
```
chart.legend.itemContainers.template.togglable = false
```
and then when I print togglable field for each legend item I got true value for each.
```
chart.legend.itemContainers.template.togglable = false
chart.legend.itemContainers.template.events.on("hit", function(ev) {
  console.log("Clicked on", ev.target.togglable);
});
```

Here I am reproducing the problem:
https://codepen.io/Barak/pen/xBNGdr

from my perspective it is a bug please correct me if I wrong.
If it is a bug please inform it by proper message and fix it.

**Comment by martynasma** [comment]
Fixed in [4.3.3](https://github.com/amcharts/amcharts4/releases/tag/4.3.3).

## [4.3.3] - 2019-03-27

### Fixed
- `MapPolygonSeries.geodataSource` was not working.
- `MapChart` was not showing data if `geodata` was set later than data on series.
- When there were multiple data items with identical timestamps on `DateAxis`, the first ones could have been ignored.
- Even if `legend.itemContainer.template.togglable` was set to `false`, Legend item was stil togglable.
- Extra graticules (grid) was shown in `GraticuleSeries` unders some conditions.
- Tooltips on a logarithmic `ValueAxis` were showing wrong values.
- Value label for "0" could sometimes appear on top of logarithmic `ValueAxis`.
- `MapChart` position was not correct if padding was set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
