### ISSUE TITLE
Not able to load external geoJson

### ISSUE THREAD

**Issue by francoisella** [amcharts/amcharts4#1119]
From today, after upgrading to 4.3.2 i'm not able to use MapPolygonSeries.geodataSource.url.
Data are loaded correctly but map is not shown. 

Another issue is that highlighting borders using this code doesn't work anymore:
`countryTemplate.zIndex = 0;
var hover_country = countryTemplate.states.create("hover");
hover_country.properties.stroke = strokeHighlightColor;
hover_country.properties.zIndex = 1;`

Downgrading to version 4.2.6 solved both issues

**Comment by martynasma** [comment]
For the second issue, use this instead:

```
hover_country.properties.zIndex = Number.MAX_VALUE;
```

**Comment by martynasma** [comment]
Fixed in [4.3.3](https://github.com/amcharts/amcharts4/releases/tag/4.3.3).

## [4.3.3] - 2019-03-27

### Fixed
- `MapPolygonSeries.geodataSource` was not working.
- `MapChart` was not showing data if `geodata` was set later than data on series.
- When there were multiple data items with identical timestamps on `DateAxis`, the first ones could have been ignored.
- Even if `legend.itemContainer.template.togglable` was set to `false`, Legend item was stil togglable.
- Extra graticules (grid) was shown in `GraticuleSeries` unders some conditions.
- Tooltips on a logarithmic `ValueAxis` were showing wrong values.
- Value label for "0" could sometimes appear on top of logarithmic `ValueAxis`.
- `MapChart` position was not correct if padding was set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
