### ISSUE TITLE
TreeMap chart memory leak

### ISSUE THREAD

**Issue by yvelianyk** [amcharts/amcharts4#1127]
I've created a [jsFiddle](http://jsfiddle.net/yvelianyk/ag6n7w92/15/) with dynamically setting the same whole data set into the TreeMap chart(new data set is applied every 5 seconds). I see that memory of the browser tab is constantly growing. After stopping setting data, memory is not free up.

**Comment by martynasma** [comment]
Fixed in [4.3.13](https://github.com/amcharts/amcharts4/releases/tag/4.3.13).

## [4.3.13] - 2019-04-10

### Fixed
- Using `propertyFields.url` was forcing pointer cursor on all objects from the same template, even if they did not have url set.
- Memory leak with dynamic changes of data on `TreeMap`.
- `getPoint()` method of `XYSeries` is now public.
- Setting `startAngle`/`endAngle` before adding `PieSeries` was causing it to not be drawn.
- Performance tweaks to 3D columns.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
