### ISSUE TITLE
TreeMap with none aminated theme

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1150]
If use use tree map with none animated theme you have this error

> Cannot read property 'isDisposed' of undefined

On this exemple : https://codepen.io/team/amcharts/pen/be2d6fefc7bab4214690ccfc76b4c5fa?editors=1010

comment `
am4core.useTheme(am4themes_animated);` line

**Comment by martynasma** [comment]
Fixed in [4.3.7](https://github.com/amcharts/amcharts4/releases/tag/4.3.7).

## [4.3.7] - 2019-04-04

### Fixed
- `TreeMap` was erroring out since `4.3.6` unless "animated" theme was enabled.
- On `TreeMap`'s legend with default markers `valueLabels` was not working on first load.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
