### ISSUE TITLE
Binding MapPolygon url changes pointer for all

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#1153]
E.g.

```javascript
countryTemplate = countriesSeries.mapPolygons.template;
countryTemplate.propertyFields.url = "url";
countriesSeries.data = [
  {
    title: "United States",
    id: "US",
    url: "https://www.google.com"
  }
];
```

### Expected behavior:

Only US should get a pointer on hover, while others should be as if no `url` is set. (I am pretty sure this is how it used to behave.)

### Actual behavior:

Presently (tested in v4.3.5 and v4.3.7), all the other countries get a pointer on hover, too.

If no data is passed at all, then none of them get a pointer on hover.

Demo:
https://codepen.io/team/amcharts/pen/3c642b944fb874c1899f9a6442f06fc7

**Comment by martynasma** [comment]
Fixed in [4.3.13](https://github.com/amcharts/amcharts4/releases/tag/4.3.13).

## [4.3.13] - 2019-04-10

### Fixed
- Using `propertyFields.url` was forcing pointer cursor on all objects from the same template, even if they did not have url set.
- Memory leak with dynamic changes of data on `TreeMap`.
- `getPoint()` method of `XYSeries` is now public.
- Setting `startAngle`/`endAngle` before adding `PieSeries` was causing it to not be drawn.
- Performance tweaks to 3D columns.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
