### ISSUE TITLE
Legend at position Right is truncated out of the chart

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1174]
Hi, 

When we set legend position at right, the legend area is out of the chart on every type of chart

Exemple here : https://codepen.io/anon/pen/ROoPop

Thx

**Comment by zeroin** [comment]
When position of a legend is set to Left or Right, it's width is set to 200px, that's why this happens. You should adjust the width to your needs (you can set it in pixels or percent). Note, with JSON you should set width after the position: https://codepen.io/anon/pen/GLNzBv

It's a bit more complicated to make the width to be calculated automatically and it's not yet possible to do it using JSON. Here is a demo you should follow: https://codepen.io/team/amcharts/pen/aXdbep?editors=0010
