### ISSUE TITLE
Crash in 4.1.9+ if quickly adding data in a loop

### ISSUE THREAD

**Issue by ciarancourtney** [amcharts/amcharts4#1184]
Posting new issue as I think my comments on https://github.com/amcharts/amcharts4/issues/1054 went into a black hole. By crash I mean the page will freeze and chrome will eventually offer to kill it.

Its difficult for my to construct a codepen for this, so I can offer a private screen share to exhibit reliable repro.

Related https://github.com/amcharts/amcharts4/issues/979

Issue is present up to current version; v4.3.12

**Comment by martynasma** [comment]
Sorry. It's extremely difficult to track all the comments, especially in closed issues. Sometimes they slip through the cracks.

Let me get this straight: a crash happens when you very frequently set `chart.data`? Or is it something else?

Unfortunately, we can't possible carve out time for live support sessions for screen sharing.
