### ISSUE TITLE
Enhancement: better item selection for TreeMap legend

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1194]
I have a treemap with 1 level and another with a lot of children
But with the same config the treemap with 1 level does't have legend rendered, and the multi level render only 1 root element in legend.

But in all case I want all root level data in legend (Unclassified / cuisine)

1 level : https://codepen.io/anon/pen/ZZKwMx
multi level : https://codepen.io/anon/pen/QPvYYM

The différence between both config is 
- maxLevels 1 / 2
- seriesTemplates index 0 / 1
- And data without / with children

**Comment by Identity-labs** [comment]
To have correctly all root elements in legend, all root elements must have a children.
So I put in all empty root elements him self in children.
But in tooltip I have the name repeat twice ...

I don't think it is the best way to do that

**Comment by martynasma** [comment]
Perhaps we should adopt fuzzy logic used for other hierarchical chart types: legend contains items for the first level that has more than one item.

I think it would make the most sense that way. What do you think?

**Comment by Identity-labs** [comment]
It's the same for LabelBullet, when we enter in Third level we don't have label.
But if we set label on all level, the treemap is unreadable ...
It's realy complicated to have dynamique treemap with differents levels to work.

**Comment by martynasma** [comment]
Fixed in [4.4.9](https://github.com/amcharts/amcharts4/releases/tag/4.4.9).

## [4.4.9] - 2019-05-28

### Added
- `startIndex` property added to `ColorSet`. This allows to specify from which color charts like `PieChart` should start when picking colors for slices.
- `excludeFromTotal` property added to `XYSeries` (default: `false`). Allows excluding values of particular series when caluclating totals.
- `includeRangesInMinMax` property added to `ValueAxis`.

### Changed
- The chart will now error out if trying to instantiate generic classes like  (`Chart`, `Axis`, `Series`).
- Legend in `TreeMap` was completely revamped. Previously it used series as data, but as series were not always created, it failed to render items in some cases. Now it uses `TreeMapDataItem` of `TreeMap`.
- `TreeMap` legend will now show items of first level which has more than one data item.
- `dataContext` of `ForceDirectedNodeDataItem` will now have the same object as target node's.

### Fixed
- `responsive.useDefault = false` was being ignored.
- `DateAxis` with hourly-based data could render some of the labels using date formatter of a changed period even if the period didn't actually change.
- In some cases `MapChart` could interfere with event objects of other charts on the same page, even when not directly interacting with it.
- If `baseInterval` of `DateAxis` didn't have `count` set, the chart failed to render.
- Setting data on hidden Series resulted tooltips on invisible bullets to be shown.
- `WordCloudSeries` with single label or several labels with the same values was displaying labels using `minFontSize`.
- `axis.createSeriesRange()` was not working with `RadarColumnSeries`.
- When data was added to a chart, series could flicker at incorrect position before rendering properly. Also the same could happen when zooming chart (it was only visible if animated theme was not in use).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Identity-labs** [comment]
Hi, 
With this change, when we have only 1 element in treemap, the legend disappear.
It's not possible to choose data level for the legends, display next childrens over root items ?
Thx
