### ISSUE TITLE
Zooming / scrolling with two dateAxis (question or maybe a bug?)

### ISSUE THREAD

**Issue by onx2** [amcharts/amcharts4#1197]
**Bug / question**
It seems that the handles don't affect the chart zooming on a `XYChart` that has two xAxes and two series. I may be missing a piece of the configuration, please let me know if I am and any documentation I can read up on.

Using the cursor to highlight a section will only zoom in the right-hand size of the graph and the left stays locked into place.

**How to reproduce**
Create a `XYChart` with multiple dateAxes and multiple series.
Add a `XYChartScrollbar` -- *optional* push both series in.
Grab the left or right handle on the scroll bar and see the graph not correspond to the changes.

**See fiddle**: https://jsfiddle.net/oLsdfzp3/3/

![image](https://user-images.githubusercontent.com/23039725/56066423-b4441c80-5d45-11e9-86c8-61e4e5cd7530.png)

**Comment by onx2** [comment]
Okay I think I found out what it going on.

It seems that this functionality only works with the `am4themes_animated` installed. I'm not sure if that is intentional or not though because it works with one series without the theme installed.

With two series and no animation (_previous not working ex_): https://jsfiddle.net/oLsdfzp3/3/
With one series and no animation (_working_): https://jsfiddle.net/418ghwyr/1/
With two series and animation (_working_): https://jsfiddle.net/418ghwyr/

**Comment by zeroin** [comment]
This will be fixed in next release - thanks for the heads up!
By the way, in case you were wondering why at some zoom levels the grid is out of sync - this happens because at some point "week" interval is chosen and when this interval is used, the grid is placed on first day of the week. So if you don't want this to happen, you must remove "week" interval drom <code>dateAxis.gridIntervals</code>. In JSON what would mean setting all the intervals you need in the settings:

<code>
          gridIntervals:[
         { timeUnit: "day", count: 1 },
         { timeUnit: "day", count: 2 },
         { timeUnit: "day", count: 3 },
         { timeUnit: "day", count: 4 },
         { timeUnit: "day", count: 5 },
         { timeUnit: "month", count: 1 },
         { timeUnit: "month", count: 2 },
         { timeUnit: "month", count: 3 },
         { timeUnit: "month", count: 6 },
         { timeUnit: "year", count: 1 },
         { timeUnit: "year", count: 2 }]
</code>

**Comment by onx2** [comment]
Awesome!! Thanks for the quick response / fix. 

> By the way, in case you were wondering why at some zoom levels the grid is out of sync - this happens because at some point "week" interval is chosen and when this interval is used, the grid is placed on first day of the week.

Oh okay cool, very good to know. So, these settings will never try to align weeks, but rather days? 

Is this the issue you're talking about?
![image](https://user-images.githubusercontent.com/23039725/56139225-770aa500-5f66-11e9-9045-7b21b79bc3e0.png)

**Comment by martynasma** [comment]
Fixed in [4.3.15](https://github.com/amcharts/amcharts4/releases/tag/4.3.15).

## [4.3.15] - 2019-04-06

### Added
- `startendchanged` event added to `Component`. Fired when `start` or `end` is changed. Unlike `startchanged`/`endchanged` this event is fired not immediately but at the end of a cycle.

### Changed
- `Sunburst` chart's defaalt `radius` set to `95%`.

### Fixed
- `TreeMap` could produce a JS error if data was changed during interaction with the map.
- If `Component.addData()` called before chart was initialized, error happened.
- 3D columns with reversed base axis had wrong z-indexes.
- `DateAxis`-based chart with single data item got into infinite loop if `startLocation` and `endLocation` were set to `0.5` or `strictMinMax` was set to `true`.
- Tooltips of series could overlap if series used different `DateAxis` axes.
- Chart with multiple `DateAxis` and no animated theme was not properly zooming with scrollbar.
- Implemented a workaround for MSIE which was not updating series masks on chart resize.
- Disposing `XYCursor` will now remove series/axes tooltips that might be currently displayed because of it.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
