### ISSUE TITLE
"Grabbing" cursor not shown in Firefox with chart cursor set to "panX"

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1198]
Default cursor shown instead of "grabbing" cursor with [this chart](https://jsfiddle.net/eb05rvu3/1/). Latest version of Firefox on Windows 10.  Works fine on Chrome and Edge on the same computer.

**Comment by martynasma** [comment]
Fixed in [4.4.1](https://github.com/amcharts/amcharts4/releases/tag/4.4.1).

## [4.4.1] - 2019-04-22

### Changed
- Now when using `CSVParsing` for parsing external data, `skipRows` will kick in first, removing X rows from the beginning of data, then `useColumnNames` will use the first row of what's left.

### Fixed
- JSON: Specifying language locale as string (i.e. "fr_FR") now works in JS setups, provided appropriate language file is loaded.
- Grab/Grabbing cursor was not appearing on Scrollbars on Firefox.
- `MapChart` used to pan itself when it was zoomed in, `tapToActivate` enabled, and was tapped.
- Hovering mouse cursor over an `XYChart` while it was initializing could sometimes result in a JS error.
- Issue with `DateAxis` and `Series` not having dates at certain data items fixed. It was cousing problems with multiple date axes mostly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
