### ISSUE TITLE
Eliminate automatic panning with "panX" 

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1204]
As shown in [pen here](https://codepen.io/anon/pen/ZZXjrr), the chart will automatically pan after manual panning with the cursor (by clicking and dragging in the chart) is completed so that the candlestick on the left of the chart is brought fully in view.  You have to zoom in a bit to see this.  More often than not, we care about the more recent data (i.e. the data on the far right of the chart not the data on the far left).  This is especially true when we pan to the right to view the most recent candlestick.  This behavior hides some or all of the candlestick so that viewing the most recent candlestick requires resizing the browser window or changing the zoom (very annoying).

Is there a way to turn off this automatic panning or alternatively make it automatically pan based on the candlestick on the right instead of the left?

**Comment by martynasma** [comment]
I'm afraid I'm not quite sure what you mean by "automatic panning".

When I open your chart it shows all possible candlesticks, including most recent. Nothing is hidden.

![image](https://user-images.githubusercontent.com/1458520/56136354-4a24b500-5f9b-11e9-9825-a9049e455f59.png)

**Comment by bfailing** [comment]
Panning is inherently disabled when all candlesticks are viewable (i.e. nothing to pan to).  That's why I said you have to zoom in to see this.

Steps to reproduce:
1. Grab left zoom handle and bring it in (e.g., about half of the zoom range to make the candlesticks bigger and make it easier to see the effect) so that the left-most candlestick is hardly showing.  The amount that it is hidden doesn't really matter, but the effect is more noticeable if less is showing.

2. Grab the zoom bar (should be on the far right now) and move it away from the right side (at least far enough so that the last few candlesticks on the right are not viewable).

3. Manually pan toward the most recent candlesticks on the right (by clicking and dragging on the chart) so that the right-most candlestick is at least partially in view.  This can include panning past the most recent candlestick to enable the rubber-band effect.  In other words, try to view the entire right-most candlestick by manually panning.  You cannot without changing the zoom level or resizing the browser window.

**Comment by martynasma** [comment]
Gotcha. Was able to reproduce this. Thanks!

Will see what we can do to fix.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.4.0](https://github.com/amcharts/amcharts4/releases/tag/4.4.0).

## [4.4.0] - 2019-04-17

### Added
- Charts now have new property - `tapToActivate` (default: `false`). If set to `true` it will not react to touch drag gestures until user taps on the chart. [More info](https://www.amcharts.com/docs/v4/concepts/touch/).
- New element on charts: `dragGrip`. It's a grip that, when enabled, will allow scrolling the page even if the chart functionality does not permit it, e.g. with chart cursor or `MapChart`. [More info](https://www.amcharts.com/docs/v4/concepts/touch/).

### Fixed
- `NumberFormatter` in charts was ignoring locale settings.
- `TreeMap` could crash across data update.
- In some situations `XYCursor` with `"panX"` behavior would not allow panning the chart completely to the edge of data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
