### ISSUE TITLE
Disabling last legend item raises error: Cannot set property 'invalid' of undefined at t.update...

### ISSUE THREAD

**Issue by RobbertBreij** [amcharts/amcharts4#122]
In a Pie Chart with an external legend, disable (toggle off) every legend item. Disabling the last legend item (until no more slices are left in the chart) raises the following error:

```
core.js:1 Uncaught TypeError: Cannot set property 'invalid' of undefined
    at t.update (core.js:1)
    at core.js:1
```

Once the error appears, it's only possible to re-show a single legend item, but no more than that. Also the error keeps appearing every time a legend item is clicked.

Find a Codepen example here: https://codepen.io/team/amcharts/pen/YvMepP?editors=0010.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
