### ISSUE TITLE
RadarChart axis.createSeriesRange() doesn't seem to do anything

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#1224]
If you're looking to color segments of `RadarColumn`, I feel an axis range via `createSeriesRange` could be a good option. According to documentation it's not an unreasonable expectation:

> ...whatever you can do with those axes on an XY chart, you can do here as well. That includes adding Axis Ranges.
 [source](https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-on-radar-chart/)

Regular `axis.axisRanges.create()` seem to work just fine as expected. However, whether it's x/y, category, or value, `createSeriesRange` doesn't seem to do anything, e.g.

```javascript
var range2 = categoryAxis.createSeriesRange(series);
range2.contents.fill = am4core.color("#0066CC");
range2.contents.fillOpacity = 0.3;
range2.category = "N";
range2.endCategory = "N";

var valueRange2 = valueAxis.createSeriesRange(series)
valueRange2.value = 0;
valueRange2.endValue = 6;
valueRange2.contents.fill = "red";
valueRange2.contents.fillOpacity = 1;
```

Demo (value/category axes `createSeriesRange` examples on the bottom):
https://codepen.io/team/amcharts/pen/b272a4220dad433d84b39c8f82c581c3

**Comment by martynasma** [comment]
Fixed in [4.4.9](https://github.com/amcharts/amcharts4/releases/tag/4.4.9).

## [4.4.9] - 2019-05-28

### Added
- `startIndex` property added to `ColorSet`. This allows to specify from which color charts like `PieChart` should start when picking colors for slices.
- `excludeFromTotal` property added to `XYSeries` (default: `false`). Allows excluding values of particular series when caluclating totals.
- `includeRangesInMinMax` property added to `ValueAxis`.

### Changed
- The chart will now error out if trying to instantiate generic classes like  (`Chart`, `Axis`, `Series`).
- Legend in `TreeMap` was completely revamped. Previously it used series as data, but as series were not always created, it failed to render items in some cases. Now it uses `TreeMapDataItem` of `TreeMap`.
- `TreeMap` legend will now show items of first level which has more than one data item.
- `dataContext` of `ForceDirectedNodeDataItem` will now have the same object as target node's.

### Fixed
- `responsive.useDefault = false` was being ignored.
- `DateAxis` with hourly-based data could render some of the labels using date formatter of a changed period even if the period didn't actually change.
- In some cases `MapChart` could interfere with event objects of other charts on the same page, even when not directly interacting with it.
- If `baseInterval` of `DateAxis` didn't have `count` set, the chart failed to render.
- Setting data on hidden Series resulted tooltips on invisible bullets to be shown.
- `WordCloudSeries` with single label or several labels with the same values was displaying labels using `minFontSize`.
- `axis.createSeriesRange()` was not working with `RadarColumnSeries`.
- When data was added to a chart, series could flicker at incorrect position before rendering properly. Also the same could happen when zooming chart (it was only visible if animated theme was not in use).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
