### ISSUE TITLE
pre-pulled slice on sunburst?

### ISSUE THREAD

**Issue by stevedw** [amcharts/amcharts4#1256]
Is there anyway to set an outer slice on a sunburst to be pre-puilled?

I have tried both config and property approach on the data and set the series object relevant to the level (and the other levels) returned by the create call.
`var level3 = chart.seriesTemplates.create("3");`

`level3.slices.template.propertyFields.isActive = "pulled";`
`level3.slices.template.configField` = "config"`

I feel I am missing something here but I can't figure it out.

**Comment by martynasma** [comment]
Fixed in [4.4.4](https://github.com/amcharts/amcharts4/releases/tag/4.4.4).

## [4.4.4] - 2019-05-08

### Fixed
- When data for `ForceDirecctedSeries` was changed the old links remained visible.
- Legend with custom data was causing a JS error.
- Changing data during `rangechangeended` with `skipEmptyPeriods` enabled was triggering "Cannot read property 'getTime[ of undefined" exception.
- Slices of `SunburstSeries`, and columns of `TreeMapSeries` were not taking `propertyFields`/`configField` from data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
