### ISSUE TITLE
axisRange.label.bent not working with Firefox but works fine with Chrome/IE11/Edge  

### ISSUE THREAD

**Issue by naveenhirebeel** [amcharts/amcharts4#1258]
Hi,

axisRange.label.bent = true is working fine with IS 11/Edge / Chrome browsers but not working with Firefox.

**Comment by martynasma** [comment]
Do you have an example?

**Comment by naveenhirebeel** [comment]
https://jsfiddle.net/pgcwakm6/5/

Check out this

**Comment by naveenhirebeel** [comment]
without bent, outer range text is displayed at correct position but with bent position will get changed. 

https://jsfiddle.net/pgcwakm6/6/

**Comment by martynasma** [comment]
Thanks!

This will be fixed in the next release.

**Comment by martynasma** [comment]
Fixed in [4.4.3](https://github.com/amcharts/amcharts4/releases/tag/4.4.3).

## [4.4.3] - 2019-05-06

### Added
- `Regression` plugin: two new settings - `simplify` (simplifies output data for faster performance) and `reorder` (orders data in a horizontal linear fashion for scatter plots).
- `arrangestarted`, `arrangeended`, and `arrangeprogress` events added to `WordCloudSeries`. Allows showing preloader while building the chart.

### Changed
- `keepSelection` behavior extended. Now it will keep `ValueAxis` selection while scrolling a perpendicular `DateAxis` or `CategoryAxis`.

### Fixed
- `Regression` plugin: fixed issue with gaps in data.
- Panning chart with `CategoryAxis` out of range, the axis could pan back with one less category in the range when released.
- In some cases labels with `bent = true` on `AxisLabelCircular` were positioned incorrectly on `RadarChart`'s Axis ranges.
- Safari was not displaying base grid of Y axis in some cases.
- Chart could freeze if there was a very small difference between minimum and maximum values of `ValueAxis` (less than 0.00000001).
- If `WordCloud` was hidden while arranging words, and then unhidden, the words would overlap in some cases. Arranging of words now stops if container is hidden during the process and resumes when it is unhidden.
- 3D columns were cut off on IE if the size of Chart container changed after the chart was already build.
- In some setups with `<base href>` some elements were being drawn incorrectly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by naveenhirebeel** [comment]
Hi @martynasma ,

The fix is not working if we run with Angular 7 Application. 

Steps to reproduce:
1. Open the below link in Firefox browser
2. Landing page has Chart(component) which renders properly and Outer Range names are visible.
3. click on hyper link "link to Same Radar Component" and same Chart renders via route. 
4. Observe outer Range Names are not visible now.

Application Link : https://mychart.cfapps.io/

Git Hub : https://github.com/naveenhirebeel/test_chart
