### ISSUE TITLE
Y CategoryAxis Basegrid Disappears in Safari

### ISSUE THREAD

**Issue by mariadoesmath** [amcharts/amcharts4#1263]
In an XYChart with a y category axis, and an x value axis, the category axis basegrid disappears on Safari.

Open [this codepen](https://codepen.io/meskro7/pen/zXVpVz) in Chrome and Safari to observe the difference.

Screenshots

Chrome:
<img width="1675" alt="Screen Shot 2019-05-02 at 8 51 27 AM" src="https://user-images.githubusercontent.com/22682031/57080124-83596680-6cb7-11e9-82b1-da9ad551f9c1.png">

Safari:
<img width="1666" alt="Screen Shot 2019-05-02 at 8 50 37 AM" src="https://user-images.githubusercontent.com/22682031/57080081-67ee5b80-6cb7-11e9-9959-2aed5014b306.png">

**Comment by amcharts** [comment]
> New comment from Zendesk by **Antanas Marcelionis** on ticket **44997**.
> (replying here will automatically notify amCharts support agent)

fixed

Yours sincerely,

Antanas Marcelionis
amCharts

P.S. have you seen amCharts 4 yet?
https://www.amcharts.com/

**Comment by martynasma** [comment]
Fixed in [4.4.3](https://github.com/amcharts/amcharts4/releases/tag/4.4.3).

## [4.4.3] - 2019-05-06

### Added
- `Regression` plugin: two new settings - `simplify` (simplifies output data for faster performance) and `reorder` (orders data in a horizontal linear fashion for scatter plots).
- `arrangestarted`, `arrangeended`, and `arrangeprogress` events added to `WordCloudSeries`. Allows showing preloader while building the chart.

### Changed
- `keepSelection` behavior extended. Now it will keep `ValueAxis` selection while scrolling a perpendicular `DateAxis` or `CategoryAxis`.

### Fixed
- `Regression` plugin: fixed issue with gaps in data.
- Panning chart with `CategoryAxis` out of range, the axis could pan back with one less category in the range when released.
- In some cases labels with `bent = true` on `AxisLabelCircular` were positioned incorrectly on `RadarChart`'s Axis ranges.
- Safari was not displaying base grid of Y axis in some cases.
- Chart could freeze if there was a very small difference between minimum and maximum values of `ValueAxis` (less than 0.00000001).
- If `WordCloud` was hidden while arranging words, and then unhidden, the words would overlap in some cases. Arranging of words now stops if container is hidden during the process and resumes when it is unhidden.
- 3D columns were cut off on IE if the size of Chart container changed after the chart was already build.
- In some setups with `<base href>` some elements were being drawn incorrectly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
