### ISSUE TITLE
Calling chart.dispose() on a chart with an external legend triggers "EventDispatcher is disposed" exception message

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1266]
When you call `dispose` on a chart with an external legend container after creating it, the `"EventDispatcher is disposed"` exception is triggered. This doesn't happen you use a regular legend. This may be related to #324 as adding a timeout prevents this from happening.

[Codepen](https://codepen.io/team/amcharts/pen/83369beb848d32ae62943b46d3720e34?editors=0010)

**Comment by amcharts** [comment]
> New comment from Zendesk by **Antanas Marcelionis** on ticket **45023**.
> (replying here will automatically notify amCharts support agent)

fixed

Yours sincerely,

Antanas Marcelionis
amCharts

P.S. have you seen amCharts 4 yet?
https://www.amcharts.com/

**Comment by martynasma** [comment]
Fixed in [4.4.3](https://github.com/amcharts/amcharts4/releases/tag/4.4.3).

## [4.4.3] - 2019-05-06

### Added
- `Regression` plugin: two new settings - `simplify` (simplifies output data for faster performance) and `reorder` (orders data in a horizontal linear fashion for scatter plots).
- `arrangestarted`, `arrangeended`, and `arrangeprogress` events added to `WordCloudSeries`. Allows showing preloader while building the chart.

### Changed
- `keepSelection` behavior extended. Now it will keep `ValueAxis` selection while scrolling a perpendicular `DateAxis` or `CategoryAxis`.

### Fixed
- `Regression` plugin: fixed issue with gaps in data.
- Panning chart with `CategoryAxis` out of range, the axis could pan back with one less category in the range when released.
- In some cases labels with `bent = true` on `AxisLabelCircular` were positioned incorrectly on `RadarChart`'s Axis ranges.
- Safari was not displaying base grid of Y axis in some cases.
- Chart could freeze if there was a very small difference between minimum and maximum values of `ValueAxis` (less than 0.00000001).
- If `WordCloud` was hidden while arranging words, and then unhidden, the words would overlap in some cases. Arranging of words now stops if container is hidden during the process and resumes when it is unhidden.
- 3D columns were cut off on IE if the size of Chart container changed after the chart was already build.
- In some setups with `<base href>` some elements were being drawn incorrectly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
