### ISSUE TITLE
Changing data during rangechangeended w/skipEmptyPeriods enabled triggers "Cannot read property 'getTime[ of undefined" exception

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1277]
When changing the chart's data array during a rangechangeended event in the date axis with `skipEmptyPeriods` enabled, the chart raises the `Cannot read property 'getTime' of undefined` exception.

[Codepen](https://codepen.io/team/amcharts/pen/65e2d045f3ac714f2a0899ed32d8aa90?editors=0010)

**Comment by martynasma** [comment]
Fixed in [4.4.4](https://github.com/amcharts/amcharts4/releases/tag/4.4.4).

## [4.4.4] - 2019-05-08

### Fixed
- When data for `ForceDirecctedSeries` was changed the old links remained visible.
- Legend with custom data was causing a JS error.
- Changing data during `rangechangeended` with `skipEmptyPeriods` enabled was triggering "Cannot read property 'getTime[ of undefined" exception.
- Slices of `SunburstSeries`, and columns of `TreeMapSeries` were not taking `propertyFields`/`configField` from data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
