### ISSUE TITLE
Object doesn't support property or method 'isDisposed'  of demo:[ Angular Gauge With Two Axes ]

### ISSUE THREAD

**Issue by dangenius** [amcharts/amcharts4#1278]

**Comment by martynasma** [comment]
Fixed in [4.4.4](https://github.com/amcharts/amcharts4/releases/tag/4.4.4).

## [4.4.4] - 2019-05-08

### Fixed
- When data for `ForceDirecctedSeries` was changed the old links remained visible.
- Legend with custom data was causing a JS error.
- Changing data during `rangechangeended` with `skipEmptyPeriods` enabled was triggering "Cannot read property 'getTime[ of undefined" exception.
- Slices of `SunburstSeries`, and columns of `TreeMapSeries` were not taking `propertyFields`/`configField` from data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
