### ISSUE TITLE
Setting datapoint value to null is not reactive

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#1281]
When setting a datapoint value to `null`, the chart does not update. Setting the value to `0` instead works.
Currently I'm setting the value and calling chart.invalidateRawData afterwards. Is this intentional behavior or a reactivity issue?

Thanks in advance for looking into it!

**Comment by martynasma** [comment]
`invalidateRawData()` is meant for updating values.

`null` is not a value, it's "lack of value" which would mean that there's no data point in that place.

This is by design.

If you need to selectively remove data points, you will need to re-evaluate whole of the data, using `invalidateData()`.

Hope that makes sense.
