### ISSUE TITLE
Date axis cursor tooltip displays wrong value

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1283]
In [this fiddle](http://jsfiddle.net/vmattu9/61vn9apy/), the date axis tooltips are not lining up with the timestamp in the chart's data. For example, the point at 299 says May even though the data's date value is set to 2018-06-30. Manually setting the `baseInterval` to one month ([fiddle](http://jsfiddle.net/x8nsb4o6/)) makes the tooltip report correct values, but the chart should be able to do this without manual intervention.

**Comment by zeroin** [comment]
Well, it's always better to set baseInterval manually, especially when the data is at intervals like these. In this particular case DateAxis decides that data is every two months and this causes problems. However I agree that the cursor behaves strangely even anyway, I will take a look at it.

**Comment by Achilles1515** [comment]
@zeroin @martynasma 

Here is another example I created:

http://jsfiddle.net/amyd4sgb

The tooltip for every point shows an incorrect time.

**Comment by martynasma** [comment]
@Achilles1515 That's because you don't have `baseInterval` set:

```
      dateAxis.baseInterval = {
      	timeUnit: "second",
        count: 1
      }
```

**Comment by Achilles1515** [comment]
@martynasma Interesting. Thanks for letting me know.

For baseInterval, the [docs](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity) state:

> In fact, if you know the granularity of your data beforehand, it is encouraged to set baseInterval so that Date axis does not have to waste precious resources in trying to figure it our from your data.

Regarding "trying to figure it our from your data", is the example I posted then a bug in this "trying to figure it out" algorithm?...because it does not figure it out correctly in that example and the chart shows the user incorrect information.

Also, "trying to figure it our from your data" contains a typo --> "our" should be "out".

**Comment by martynasma** [comment]
Thanks for the heads up about typo. Fixed.

No, it's not a bug, it works correctly. Your data points come at minute intervals, so it determines the granularity is in minutes, hence it "rounding up" the seconds.

If you want to keep precision down to level of seconds, you manually set `baseInterval`.

Hope that makes sense.
