### ISSUE TITLE
Map is dragged: ZoomIn: Error: "Cannot read property '0' of null" error on zoomIn

### ISSUE THREAD

**Issue by rdalfonso** [amcharts/amcharts4#1286]
When I execute this.chart.zoomIn() on a map that's dragged to the left, there's an error in the javascript console. "Cannot read property '0' of null"

This issue always happens when I use the wheel of my mouse and it triggers errors with zoomIn and zoomOut

> Projection.js:250 Uncaught TypeError: Cannot read property '0' of null
>     at AlbersUsa.push../node_modules/@amcharts/amcharts4/.internal/charts/map/projections/Projection.js.Projection.convert (Projection.js:250)
>     at MapChart.push../node_modules/@amcharts/amcharts4/.internal/charts/types/MapChart.js.MapChart.zoomToGeoPoint (MapChart.js:772)
>     at MapChart.push../node_modules/@amcharts/amcharts4/.internal/charts/types/MapChart.js.MapChart.zoomOut (MapChart.js:887)
>     at MapChart.push../node_modules/@amcharts/amcharts4/.internal/charts/types/MapChart.js.MapChart.handleWheel (MapChart.js:422)
> 

My setup has custom zoom button which trigger the this.chart.zoomIn and this.chart.zoomOut functions. Everything works correctly unless I scroll to the far left.

This issue also happens on the map demo:
https://www.amcharts.com/demos/us-heat-map/
1. Click inside the map
2. Click outside the map. near the amCharts branding, and use mouse wheel.
3. Error also occurs randomly when clicking outside the map.

Anyone else have this issue?

**Comment by martynasma** [comment]
Fixed in [4.4.5](https://github.com/amcharts/amcharts4/releases/tag/4.4.5).

## [4.4.5] - 2019-05-13

### Changed
- Exporting chart data to JSON format now respects `dataFields` setting.

### Fixed
- Setting `showSystemTooltip = false` on a `Scrollbar` now correctly disables tooltips on its thumb and grips.
- When data for `ForceDirectedSeries` was changed for the second time, the old links remained visible.
- Initial scatter of `ForceDirectedSeries` nodes reduced. Results in a better initial animation.
- Adding data using `addData()` method to a chart with `XYChartScrollbar` was resulting data to be added twice.
- With some special combination of axes config `XYChart` sometimes could fall into infinite loop.
- Some JS error when converting coordinates out of bounds of AlbersUSA projection fixed.
- Tooltip bounds were not being copied when cloning a `Tooltip`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
