### ISSUE TITLE
Horizontal axis missing in Safari

### ISSUE THREAD

**Issue by georgezernet** [amcharts/amcharts4#1293]
[This example](https://codepen.io/geocourgen/pen/vwXYbg) works fine in FF and Chrome but doesn't work in Safari.

Firefox (OK):
![amchart_ff](https://user-images.githubusercontent.com/33207452/57599413-be9c4500-7595-11e9-9a2e-035709286c03.png)

Safari (not OK):
![amchart_saf](https://user-images.githubusercontent.com/33207452/57599447-d673c900-7595-11e9-8df5-8004960add63.png)

**Comment by martynasma** [comment]
Does this happen on a standalone chart? Seems like an error caused by iframe settings of CodePen itself.

Check browser console.

**Comment by georgezernet** [comment]
Yes, the same happens on standalone chart. I simply extracted JS and JSON from it and put into CodePen.

**Comment by martynasma** [comment]
Thanks. We'll have to do some more digging.

Will keep you posted.

**Comment by martynasma** [comment]
OK, so here's the deal. You have dates as strings in your source data ("2019-04-16 00:00").

You use custom function to convert them to real dates by passing them into constructor of `new Date()`.

This works in normal browsers like Chrome and FireFox. Safari, does not know how to convert string dates like that, hence it ending up with data with `Invalid date` instead of valid `Date` objects.

I suggest you don't parse your dates, but rather let amCharts do that by specifying `inputDateFormat`:

```
chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mm";
```

**Comment by georgezernet** [comment]
Thank you @martynasma. This did the trick!
