### ISSUE TITLE
removeData does not remove points on scrollbarX if it is called after an addData

### ISSUE THREAD

**Issue by kimlukas3** [amcharts/amcharts4#1294]
Example: https://codepen.io/kimlukas3/pen/JqRXdO

I have a function which are triggered each second, this function adds 2 items with addData and removes 2 items with removeData.

The items will not be removed from scrollbarX.

**Comment by martynasma** [comment]
Duplicate: #1292

**Comment by martynasma** [comment]
Fixed in [4.4.5](https://github.com/amcharts/amcharts4/releases/tag/4.4.5).

## [4.4.5] - 2019-05-13

### Changed
- Exporting chart data to JSON format now respects `dataFields` setting.

### Fixed
- Setting `showSystemTooltip = false` on a `Scrollbar` now correctly disables tooltips on its thumb and grips.
- When data for `ForceDirectedSeries` was changed for the second time, the old links remained visible.
- Initial scatter of `ForceDirectedSeries` nodes reduced. Results in a better initial animation.
- Adding data using `addData()` method to a chart with `XYChartScrollbar` was resulting data to be added twice.
- With some special combination of axes config `XYChart` sometimes could fall into infinite loop.
- Some JS error when converting coordinates out of bounds of AlbersUSA projection fixed.
- Tooltip bounds were not being copied when cloning a `Tooltip`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
