### ISSUE TITLE
If Slider width is Percent, it's always 100%

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#1296]
Our text on a curved path example uses a standalone slider:
https://codepen.io/team/amcharts/pen/mvzgaz

If you set `slider.width` to a `Number` value, it's fine:
![image](https://user-images.githubusercontent.com/2334143/57654150-826ee180-75a1-11e9-9a90-296c3c48dd9b.png)

However, given:

```javascript
slider.width = am4core.percent(50);
```

The Slider is always fully expanded:

![image](https://user-images.githubusercontent.com/2334143/57654187-96b2de80-75a1-11e9-95cf-0a4b3df80453.png)

Fork/example:
https://codepen.io/team/amcharts/pen/bc6545ac3881496b1df99ffaabde248f

**Comment by martynasma** [comment]
Fixed in [4.4.7](https://github.com/amcharts/amcharts4/releases/tag/4.4.7).

## [4.4.7] - 2019-05-21

### Changed
- Export: Children columns on hierarchical charts (`TreeMap`, `Sunburst`, `ForceDirectedTree`) are no longer exported to "flat" formats (CSV, XLSX).

### Fixed
- `keepTargetHover` was hiding tooltip when transiting hover from one `Sprite` to another.
- Firefox was not displaying texts along paths on a page with `base href` set, due to Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=455986).
- `SunburstSeries` with 0 values were producing a JS error.
- Width (or height if vertical) of `Scrollbar`/`Slider` was always 100%, even if it was set to less than 100%.
- `WordCloud` with long labels that did not fit into container could get into infinite loop and never get drawn.
- If a lot of `GaugeChart` instances with axis bands were rendered on a single page, stack owerflow error could happen.
- Adding data to a chart with `XYChartScrollbar` and series in the scrollbar forced full-redraw of scrollbar chart which was making it blink.
- Z-indexing of `ColumnSeries3D` columns was incorrect in some cases.
- Tooltip of a 3D slice was not in the center of a slice.
- Changing of Series' name was not propagating to legend.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
