### ISSUE TITLE
(Firefox Browser) - axisRange.label.bent = true is not working properly when integrated with Angular 7.

### ISSUE THREAD

**Issue by naveenhirebeel** [amcharts/amcharts4#1298]
Hi Team,

bent = true functionality is not working properly when integrated with Angular7 Application.  It works fine with All other Major Browsers. 

Application Link : https://mychart.cfapps.io/
Git Hub : https://github.com/naveenhirebeel/test_chart

Steps to reproduce:

1. Open the below link in Firefox browser
2. Landing page has Chart(component) which renders properly and Outer Range names are visible.
3. click on hyper link "link to Same Radar Component" and same Chart renders via route.
4. Observe outer Range Names are not visible now.

@martynasma @zeroin Appreciate your response ASAP.

**Comment by naveenhirebeel** [comment]
Hi @martynasma,

I think it is bug as it works fine with Edge/Chrome browser. Kindly let me know will this be addressed in next release.

**Comment by martynasma** [comment]
Checking.

**Comment by Pauan** [comment]
@naveenhirebeel [It is a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=455986). We have found a workaround which fixes it, and the workaround will be in the next release.

**Comment by martynasma** [comment]
Fixed in [4.4.7](https://github.com/amcharts/amcharts4/releases/tag/4.4.7).

## [4.4.7] - 2019-05-21

### Changed
- Export: Children columns on hierarchical charts (`TreeMap`, `Sunburst`, `ForceDirectedTree`) are no longer exported to "flat" formats (CSV, XLSX).

### Fixed
- `keepTargetHover` was hiding tooltip when transiting hover from one `Sprite` to another.
- Firefox was not displaying texts along paths on a page with `base href` set, due to Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=455986).
- `SunburstSeries` with 0 values were producing a JS error.
- Width (or height if vertical) of `Scrollbar`/`Slider` was always 100%, even if it was set to less than 100%.
- `WordCloud` with long labels that did not fit into container could get into infinite loop and never get drawn.
- If a lot of `GaugeChart` instances with axis bands were rendered on a single page, stack owerflow error could happen.
- Adding data to a chart with `XYChartScrollbar` and series in the scrollbar forced full-redraw of scrollbar chart which was making it blink.
- Z-indexing of `ColumnSeries3D` columns was incorrect in some cases.
- Tooltip of a 3D slice was not in the center of a slice.
- Changing of Series' name was not propagating to legend.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by naveenhirebeel** [comment]
> @naveenhirebeel [It is a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=455986). We have found a workaround which fixes it, and the workaround will be in the next release.

Hi @Pauan , 
It is not working after work around fix also. Kindly look into it. 

> @naveenhirebeel [It is a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=455986). We have found a workaround which fixes it, and the workaround will be in the next release.

**Comment by naveenhirebeel** [comment]
@Pauan & @martynasma , 

This is working fine in latest Firefox version. Thanks for the help.
