### ISSUE TITLE
scrollbarX blink when adding or removing points on a chart with around 3000 points.

### ISSUE THREAD

**Issue by kimlukas3** [amcharts/amcharts4#1301]
Example: https://codepen.io/kimlukas3/pen/OYbgOX

How to reproduce it:
A timer trigger's each two seconds, this adds 1 item and remove one with addData.
The Xscrollbar does blink when it refresh. 
This happens when more than a few points are on the chart. In this example around 3000.

If you have more items on the cart, it could happens that a loading indicator is showed.

**Comment by martynasma** [comment]
Fixed in [4.4.7](https://github.com/amcharts/amcharts4/releases/tag/4.4.7).

## [4.4.7] - 2019-05-21

### Changed
- Export: Children columns on hierarchical charts (`TreeMap`, `Sunburst`, `ForceDirectedTree`) are no longer exported to "flat" formats (CSV, XLSX).

### Fixed
- `keepTargetHover` was hiding tooltip when transiting hover from one `Sprite` to another.
- Firefox was not displaying texts along paths on a page with `base href` set, due to Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=455986).
- `SunburstSeries` with 0 values were producing a JS error.
- Width (or height if vertical) of `Scrollbar`/`Slider` was always 100%, even if it was set to less than 100%.
- `WordCloud` with long labels that did not fit into container could get into infinite loop and never get drawn.
- If a lot of `GaugeChart` instances with axis bands were rendered on a single page, stack owerflow error could happen.
- Adding data to a chart with `XYChartScrollbar` and series in the scrollbar forced full-redraw of scrollbar chart which was making it blink.
- Z-indexing of `ColumnSeries3D` columns was incorrect in some cases.
- Tooltip of a 3D slice was not in the center of a slice.
- Changing of Series' name was not propagating to legend.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
