### ISSUE TITLE
zIndex not working on 3D bar chart serie

### ISSUE THREAD

**Issue by puyt** [amcharts/amcharts4#1315]
Hi,

When making a 3D bar chart with more than 1 serie, the series are overlapped in the wrong order. Using `zIndex` doesn't change anything. 

As seen in the screenshot below I think the serie without a red border should be displayed on top for a 3D bar chart.

Live example: https://codepen.io/anon/pen/eaRJxK

![image](https://user-images.githubusercontent.com/3668615/57935947-31bdf800-78c3-11e9-8751-a5c7720f8ed0.png)

**Comment by zeroin** [comment]
`zIndex` is not working here because columns are placed in the same container as there might be cases when  it's not enough to simply place one series above another to have a correct view. To fix this issue in a current version you can not use `categoryAxis.renderer.inversed = true;` but of course, we will fix it in next release.

**Comment by martynasma** [comment]
Fixed in [4.4.7](https://github.com/amcharts/amcharts4/releases/tag/4.4.7).

## [4.4.7] - 2019-05-21

### Changed
- Export: Children columns on hierarchical charts (`TreeMap`, `Sunburst`, `ForceDirectedTree`) are no longer exported to "flat" formats (CSV, XLSX).

### Fixed
- `keepTargetHover` was hiding tooltip when transiting hover from one `Sprite` to another.
- Firefox was not displaying texts along paths on a page with `base href` set, due to Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=455986).
- `SunburstSeries` with 0 values were producing a JS error.
- Width (or height if vertical) of `Scrollbar`/`Slider` was always 100%, even if it was set to less than 100%.
- `WordCloud` with long labels that did not fit into container could get into infinite loop and never get drawn.
- If a lot of `GaugeChart` instances with axis bands were rendered on a single page, stack owerflow error could happen.
- Adding data to a chart with `XYChartScrollbar` and series in the scrollbar forced full-redraw of scrollbar chart which was making it blink.
- Z-indexing of `ColumnSeries3D` columns was incorrect in some cases.
- Tooltip of a 3D slice was not in the center of a slice.
- Changing of Series' name was not propagating to legend.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
