### ISSUE TITLE
Chart Jump/Compress on addData when Zoomed

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1319]
At least on candlestick charts, the chart jumps when new data is added via the `addData()` function.

See [this pen](https://codepen.io/anon/pen/MdbeBX). Move the right zoom grip in about halfway, then click the "Add Chart Data" button to see the displayed candles jump/compress. If you don't see it, keep zooming in with the right zoom grip and clicking the "Add Chart Data" button. If you still don't see it, try refreshing to get new data then repeat the above steps.

This seems to happen when the right zoom grip is moved in and also when both zoom grips are moved in. However, it does not seem to occur when only the left zoom grip is moved in (i.e. the most recent candlestick is in view).

I'm guessing it has to do with zooming the valueAxis to fit data off-screen as the effect is more pronounced if the data has a larger vertical spread when zoomed all the way out. However, it's not repeatable/predictable, so it's tough to tell without knowing what's going on under the hood.

How can this be avoided?

**Comment by martynasma** [comment]
Fixed in [4.4.9](https://github.com/amcharts/amcharts4/releases/tag/4.4.9).

## [4.4.9] - 2019-05-28

### Added
- `startIndex` property added to `ColorSet`. This allows to specify from which color charts like `PieChart` should start when picking colors for slices.
- `excludeFromTotal` property added to `XYSeries` (default: `false`). Allows excluding values of particular series when caluclating totals.
- `includeRangesInMinMax` property added to `ValueAxis`.

### Changed
- The chart will now error out if trying to instantiate generic classes like  (`Chart`, `Axis`, `Series`).
- Legend in `TreeMap` was completely revamped. Previously it used series as data, but as series were not always created, it failed to render items in some cases. Now it uses `TreeMapDataItem` of `TreeMap`.
- `TreeMap` legend will now show items of first level which has more than one data item.
- `dataContext` of `ForceDirectedNodeDataItem` will now have the same object as target node's.

### Fixed
- `responsive.useDefault = false` was being ignored.
- `DateAxis` with hourly-based data could render some of the labels using date formatter of a changed period even if the period didn't actually change.
- In some cases `MapChart` could interfere with event objects of other charts on the same page, even when not directly interacting with it.
- If `baseInterval` of `DateAxis` didn't have `count` set, the chart failed to render.
- Setting data on hidden Series resulted tooltips on invisible bullets to be shown.
- `WordCloudSeries` with single label or several labels with the same values was displaying labels using `minFontSize`.
- `axis.createSeriesRange()` was not working with `RadarColumnSeries`.
- When data was added to a chart, series could flicker at incorrect position before rendering properly. Also the same could happen when zooming chart (it was only visible if animated theme was not in use).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
