### ISSUE TITLE
DateAxis: Setting baseInterval with no "count" property fails to render series

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#1325]
Regarding the `baseInterval` member of the `DateAxis` class, the [docs ](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Manually_specifying_data_granularity)state:

> A "count" specifies how many "timeUnit" each data item comes at. Count parameter can be skipped, in which case Date axis will assume 1.

I am assuming the count parameter being "skipped" means it is omitted from the `baseInterval` object.

In [this JSFiddle](http://jsfiddle.net/r5px8oeg/), I specify:

`dateAxis.baseInterval = {
      	timeUnit: "second",
      }`

with no `count` property, which according to the docs means the DateAxis should use a value of 1 here, and the chart fails to render the series line. Tooltips still show up but the series line just doesn't show.

![image](https://user-images.githubusercontent.com/23387905/58258124-285be200-7d40-11e9-94b3-52e52369e9f4.png)

**Comment by martynasma** [comment]
Fixed in [4.4.9](https://github.com/amcharts/amcharts4/releases/tag/4.4.9).

## [4.4.9] - 2019-05-28

### Added
- `startIndex` property added to `ColorSet`. This allows to specify from which color charts like `PieChart` should start when picking colors for slices.
- `excludeFromTotal` property added to `XYSeries` (default: `false`). Allows excluding values of particular series when caluclating totals.
- `includeRangesInMinMax` property added to `ValueAxis`.

### Changed
- The chart will now error out if trying to instantiate generic classes like  (`Chart`, `Axis`, `Series`).
- Legend in `TreeMap` was completely revamped. Previously it used series as data, but as series were not always created, it failed to render items in some cases. Now it uses `TreeMapDataItem` of `TreeMap`.
- `TreeMap` legend will now show items of first level which has more than one data item.
- `dataContext` of `ForceDirectedNodeDataItem` will now have the same object as target node's.

### Fixed
- `responsive.useDefault = false` was being ignored.
- `DateAxis` with hourly-based data could render some of the labels using date formatter of a changed period even if the period didn't actually change.
- In some cases `MapChart` could interfere with event objects of other charts on the same page, even when not directly interacting with it.
- If `baseInterval` of `DateAxis` didn't have `count` set, the chart failed to render.
- Setting data on hidden Series resulted tooltips on invisible bullets to be shown.
- `WordCloudSeries` with single label or several labels with the same values was displaying labels using `minFontSize`.
- `axis.createSeriesRange()` was not working with `RadarColumnSeries`.
- When data was added to a chart, series could flicker at incorrect position before rendering properly. Also the same could happen when zooming chart (it was only visible if animated theme was not in use).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
