### ISSUE TITLE
ForceDirectedTree node and link templates not working with configField or propertyFields

### ISSUE THREAD

**Issue by Aterops** [amcharts/amcharts4#1331]
I am possibly missing something, however I am unable to get the node or link to work with the configField or propertyFields. Particularly in relation to changing the stroke and strokeWidth of the link.

I am able to change the strokeWidth in the template of the link, but i would like to be able to set both the stroke and the strokeWidth in the data.

I was even unable to change the stroke in the template, unless i used an adapter,

    let linkTemplate = networkSeries.links.template
    // linkTemplate.strokeWidth = 10
    linkTemplate.propertyFields.strokeWidth = 'strokeWidth'
    linkTemplate.configField = 'config'
    // linkTemplate.stroke = am4core.color('#B0B')
    linkTemplate.adapter.add('stroke', function (stroke, target) {
      return am4core.color('#B0B')
      })

    networkSeries.data = [
      {
        'name': 'Phoebe',
        'value': 60,
        'children': [
          {
            'name': 'test1',
            'value': 50,
            'strokeWidth': 30,
            'config': {
              'strokeWidth': 50
            },
            'children': [
              {
                'name': '1A',
                'value': 10
              }
            ]
          },
          {
            'name': 'test2',
            'value': 50
          },
          {
            'name': 'test3',
            'value': 50
          },
          {
            'name': 'test4',
            'value': 50
          }
        ]
      }
    ]

**Comment by martynasma** [comment]
The link's data item currently does not have any data context, hence `propertyFields` not working.

We'll see if we can populate link with its target node's data context.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.4.9](https://github.com/amcharts/amcharts4/releases/tag/4.4.9).

## [4.4.9] - 2019-05-28

### Added
- `startIndex` property added to `ColorSet`. This allows to specify from which color charts like `PieChart` should start when picking colors for slices.
- `excludeFromTotal` property added to `XYSeries` (default: `false`). Allows excluding values of particular series when caluclating totals.
- `includeRangesInMinMax` property added to `ValueAxis`.

### Changed
- The chart will now error out if trying to instantiate generic classes like  (`Chart`, `Axis`, `Series`).
- Legend in `TreeMap` was completely revamped. Previously it used series as data, but as series were not always created, it failed to render items in some cases. Now it uses `TreeMapDataItem` of `TreeMap`.
- `TreeMap` legend will now show items of first level which has more than one data item.
- `dataContext` of `ForceDirectedNodeDataItem` will now have the same object as target node's.

### Fixed
- `responsive.useDefault = false` was being ignored.
- `DateAxis` with hourly-based data could render some of the labels using date formatter of a changed period even if the period didn't actually change.
- In some cases `MapChart` could interfere with event objects of other charts on the same page, even when not directly interacting with it.
- If `baseInterval` of `DateAxis` didn't have `count` set, the chart failed to render.
- Setting data on hidden Series resulted tooltips on invisible bullets to be shown.
- `WordCloudSeries` with single label or several labels with the same values was displaying labels using `minFontSize`.
- `axis.createSeriesRange()` was not working with `RadarColumnSeries`.
- When data was added to a chart, series could flicker at incorrect position before rendering properly. Also the same could happen when zooming chart (it was only visible if animated theme was not in use).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by brecriffs** [comment]
@Aterops  We're you able to change the link's color without using the adapter function?

Here, I can get the distance to apply to links with children, but the stroke color doesn't apply.
`
"configLink":{
          "distance":4,
          "stroke": "#F00"
        },
`
