### ISSUE TITLE
ForceDirectedTree - offset dataContext of ForceDirectedNodeDataItem

### ISSUE THREAD

**Issue by Aterops** [amcharts/amcharts4#1340]
After the 4.4.9 release I can now use the configField and propertyField in the force directed tree. However the dataContexts appears to be offset by 1 node for the propertyFields, the configField is acting on the correct node.

In this test case the node Child1 should have a strokeWidth = 10 but this is acting on Child2.

Also I dont appear to be able to use the configField to set the stroke color of the link. I can set the node element colors like "configNode": { "circle": "red" }. Is there something similar for the link? Or possible the color inheritance needs to be overriden somehow?

var nodeTemplate = networkSeries.nodes.template;
nodeTemplate.configField = "configNode";
nodeTemplate.tooltipText = "{name}";
nodeTemplate.fillOpacity = 1;
nodeTemplate.label.hideOversized = true;
nodeTemplate.expandAll = false;
nodeTemplate.label.text = "{name}"
nodeTemplate.label.truncate = false;
nodeTemplate.label.wrap = true;
nodeTemplate.tooltipPosition = "pointer";
nodeTemplate.propertyFields.stroke = "test2";

var linkTemplate = networkSeries.links.template;
linkTemplate.configField = "configLink";
linkTemplate.strokeOpacity = 0.5;
linkTemplate.distance = 1.3;
linkTemplate.propertyFields.strokeWidth = "test";
linkTemplate.propertyFields.fill = "test1";

networkSeries.data = [{
"name": "Parent",
"value": 30,
"color": "red",
"children":[  
	{
		"name": "Child1",
		"value": 5,
		"color": "green",
		"test": 10,
		"test1": "black"
	},
	{
		"name": "Child2",
		"value": 10,
		"color": "blue",
		"test": 20,
		"test2": "black",
		"test1": "black",
		"configLink": {
			"stroke": "black"
		},
		"configNode": {
			"circle": {
				"stroke": "red"
			},
			"strokeWidth": 5
		}
	},
	{
		"name": "Child3",
		"value": 15,
		"color": "yellow",
		"test": 30,
		"test1": "black"
	},
	{
		"name": "Child4",
		"value": 20,
		"color": "pink",
		"test": 40,
		"test1": "black"
	}]
}]

**Comment by Aterops** [comment]
Sorry a slight correction, the configField also seems to be offset like the propertyFields. This is only for the link, the node configField is being applied to the correct node.

var nodeTemplate = networkSeries.nodes.template;
nodeTemplate.configField = "configNode";

var linkTemplate = networkSeries.links.template;
linkTemplate.configField = "configLink";

networkSeries.data = [{
"name": "Parent",
"value": 30,
"color": "red",
"children":[  
	{
		"name": "Child1",
		"value": 5,
		"color": "green",
		"configNode": {
			"strokeWidth": 30
		},
		"configLink": {
			"strokeWidth": 50
		}
	},
	{
		"name": "Child2",
		"value": 10,
		"color": "blue",
		"configLink": {
			"strokeWidth": 15
		}
	},
	{
		"name": "Child3",
		"value": 15,
		"color": "yellow",
		"configLink": {
			"strokeWidth": 25
		}
	},
	{
		"name": "Child4",
		"value": 20,
		"color": "pink",
		"configLink": {
			"strokeWidth": 35
		}
	}]
}]

**Comment by martynasma** [comment]
Yes, something's off. We're gonna need to fix this.

Will let you know.

**Comment by Aterops** [comment]
Ok thanks, please let me know if you need any help testing.

**Comment by martynasma** [comment]
Fixed in [4.5.0](https://github.com/amcharts/amcharts4/releases/tag/4.5.0).

## [4.5.0] - 2019-06-14

### Added
- Support of queued chart initialization. If enabled (`am4core.options.queue = true`) the chart will not start initializing until previous chart finishes.
- Support for delayed rendering. If enabled (`am4core.options.onlyShowOnViewport = true`) the chart will start rendering itself only when scrolled into view.

### Changed
- Default CSS for a `Popup` now has text color set to ensure it is visible on default background.

### Fixed
- `dataContext` of `ForceDirectedNodeDataItem` was not being populated correctly.
- `MapPolygonSeries` was not being displayed properly if GeoJSON contained a single very small polygon.
- Tooltips now work correctly when a chart is contained within the shadow DOM.
- `rtl` inheritance was not working properly on some elements, e.g. axis tooltips.
- None of the `Responsive` events were being triggered.
- JSON: It was not possible to set `XYSeries.baseAxis` using axis' `id`.
- `LineSeries` was being cut off if div of a chart was more than 20K pixels width/height.
- When axis was disabled (`axis.disabled = true`) its ticks and grid remained visible.
- If a chart had series with bullets and `minBulletDistance` set and the chart was resized so that bullets had to be hidden, some of the bullets remained visible.
- `openCategoryX` and `openCategoryY` data fields were not working properly on `XYSeries`.
- If `XYChart` had stacked series and series had both possitive and negative numbers, series were stacked incorrectly if some of the series were hidden.
- `MapChart` was not adjusting its size to the container in some specific cases.
- Some performance improvements with `series.connect = false` and a lot of missing values.
- `Rectangle3D` was not copying side's properties when cloning.
- `ForceDirectedLink`'s data item was not properly set. It is set to target's data item now.
- `MapChart` was not displaying maps of very small countries properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
