### ISSUE TITLE
Use amchart in sortable div with different width

### ISSUE THREAD

**Issue by primemb** [amcharts/amcharts4#1341]
I have a page which made with bootstrap and I have 2 different sections in this page first one use "col-lg-12" and second one use "col-lg-6" both of them are draggable. I want to put some amcharts in them everything works fine and my charts are responsive but when I moved a div in big section to small section chart responsive feature stop working and not resize automatically.
this is my full code: https://jsfiddle.net/primemb/va0n4xs3/6/

**Comment by Aterops** [comment]
Hi, I've only just started using these charts, however you might want to look at adding a chart maxsizechanged event. Something like:

`chart.events.on("maxsizechanged", resizeChart);

function resizeChart(ev) {
  document.getElementById("kt_chart1").style.height = chart.contentHeight + "px";
}`

**Comment by primemb** [comment]
thank you for the answer but I don't want to change my div style I want to resize chart somehow I tried using 'chart.reinit();' in update function but nothing happened

**Comment by Aterops** [comment]
I just had another quick look, if you dont mind redrawing the chart when you move it, you could dispose and recreate the chart. In the update function you could add the following:

chart.dispose();
chart = am4core.create("kt_chart1", am4charts.XYChart);
drawChart();

**Comment by notacouch** [comment]
It's really not clear what is causing the chart to stop resizing. Is it because of flexbox? Because of something jQuery UI Slider is doing? This is something we'll have to keep an eye on if we can't find anything in cursory investigation.

With your demo I can't really get the big div to move into the small div, but I did try manually resizing `#kt_chart1`.

To replicate the chart no longer resizing: Drag the big div just a little, stop dragging, now if you tinker with `#kt_chart1`'s width, the chart won't resize. 

What I have found is resetting the display of either of the chart div's parents (`.kt-portlet__body` or its parent `.kt-portlet`) in a timed fashion allows for the chart to resize again (manually at least).

We can achieve this programmatically via jQuery UI Sortable's [`stop` event](http://api.jqueryui.com/sortable/#event-stop) and timing via `setTimeout`:

```javascript
                stop: function(event, ui) {
                	console.log('stop');
                  window.stopthing = ui;
                  //ui.item.style.display = 'block';
                  //ui.item.style.display = '';
                  //ui.item.css('display', 'block');
                  //ui.item.css('display', '');
                  setTimeout(function() {
                  	ui.item.css('display', 'block');
                  }, 10);
                  setTimeout(function() {
                  	ui.item.css('display', '');
                  }, 20);
                  
                },
```

Fork:
https://jsfiddle.net/notacouch/w5qjpcs1/3/

Now if you drag/drop and manually resize `#kt_chart1`, the chart should automatically resize again.

But we'll have to look into why it stops auto resizing in the first place.
