### ISSUE TITLE
Treemap: Missing "zoom out" button when only one first level element

### ISSUE THREAD

**Issue by Daniel-Prescience** [amcharts/amcharts4#1342]
Treemap zoom out button is missing when first level only contains one element - see [CodePen](https://codepen.io/anon/pen/wbEXJJ#anon-login)

**Comment by martynasma** [comment]
Fixed in [4.4.10](https://github.com/amcharts/amcharts4/releases/tag/4.4.10).

## [4.4.10] - 2019-05-28

### Fixed
- Disposing top-most stacked series was causing a JS error.
- If `TreeMap` top level had one node only, zoom-out button was not shown after drill-down.
- Bullets were not shown on series on initial render if no animated theme was used (since last release only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
