### ISSUE TITLE
Non-animated bullets do not render on initial load

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#1343]
[This JSFiddle](http://jsfiddle.net/r5px8oeg/) shows a simple animated chart with a single series with bullets. In the beginning of the JavaScript code, if you comment out `am4core.useTheme(am4themes_animated);` then the series will load with no bullets shown. After doing something like zooming in on the plot, the bullets will show.

This may be a Chrome only issue, as I tried in Edge and FireFox and the bullets rendered on load as expected.

Chrome Version 74.0.3729.169 (Official Build) (64-bit)

![GIF](https://user-images.githubusercontent.com/23387905/58559190-8bda8980-81f0-11e9-8477-a0abc4eaaa95.gif)

(the JSFiddle is re-ran after commenting the code line)

**Comment by Achilles1515** [comment]
@martynasma 
There may be some larger issue going on here with Chrome.
Here is a gif of me running a CodePen from the [amCharts docs](https://www.amcharts.com/docs/v4/concepts/bullets/#Multi_element_bullets).

![GIF](https://user-images.githubusercontent.com/23387905/58560171-8e3de300-81f2-11e9-8e79-b51161c0c2d0.gif)

**Comment by martynasma** [comment]
Fixed in [4.4.10](https://github.com/amcharts/amcharts4/releases/tag/4.4.10).

## [4.4.10] - 2019-05-28

### Fixed
- Disposing top-most stacked series was causing a JS error.
- If `TreeMap` top level had one node only, zoom-out button was not shown after drill-down.
- Bullets were not shown on series on initial render if no animated theme was used (since last release only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
