### ISSUE TITLE
picking up some errors

### ISSUE THREAD

**Issue by dvodvo** [amcharts/amcharts4#1345]
These errors all relate to map files in js format - Low resolution.

azerbaijanLow=properties:{name:"Gegark'unik'",id:"AM-GR",TYPE:"City",CNTRY_NAME:"Azerbaijan"},id:"AM-GR"}
id AM should be AZ

Channel islands Low has an odd empty array hanging around:
[]},"properties name | Saint Berlade

Giunea Low  suffered  coding conversion problems where names with question marks
properties:{name:"Nz?r?kor?"

Seychelles region 'SC-00' has no type; I am not certian if this is allowed...

Then, there are a bunch of low res js files that do not render.  They all have one thing in common: a small area.  Only 1 generates zoom control buttons:

Vatican,  Aruba,  Bonaire,  Curacao,  Channel Islands,  Dominica, HongKong,  Saint Helena,  Saint Lucia,  Saint Vincent,  San Marino,   Seychelles (here, controls appear, but no points),  Singapore,  Saint Kitts, Saint Pierre et Miquelon,  Svalbard.    Antigua, Anguilla, Bermuda, Fiji and (gasp) the Maldives can be added to the list.

Additional note: using JSON raw data source also does not render the maps.  My **assumption** at this point is that the surface area of these nations is too small and something gets zeroed out in handling and thus the processing fails to complete; Seychelles was an interesting smoking gun.

**Comment by martynasma** [comment]
Thanks for the heads up. We're going to look into it.

**Comment by martynasma** [comment]
We've released an updated geodata package which fixes most of the errors.

The last error with small maps is rather in the engine. We are going to be releasing a fix for it this week as well.

Will let you know when that happens.

**Comment by martynasma** [comment]
Fixed in [4.5.0](https://github.com/amcharts/amcharts4/releases/tag/4.5.0).

## [4.5.0] - 2019-06-14

### Added
- Support of queued chart initialization. If enabled (`am4core.options.queue = true`) the chart will not start initializing until previous chart finishes.
- Support for delayed rendering. If enabled (`am4core.options.onlyShowOnViewport = true`) the chart will start rendering itself only when scrolled into view.

### Changed
- Default CSS for a `Popup` now has text color set to ensure it is visible on default background.

### Fixed
- `dataContext` of `ForceDirectedNodeDataItem` was not being populated correctly.
- `MapPolygonSeries` was not being displayed properly if GeoJSON contained a single very small polygon.
- Tooltips now work correctly when a chart is contained within the shadow DOM.
- `rtl` inheritance was not working properly on some elements, e.g. axis tooltips.
- None of the `Responsive` events were being triggered.
- JSON: It was not possible to set `XYSeries.baseAxis` using axis' `id`.
- `LineSeries` was being cut off if div of a chart was more than 20K pixels width/height.
- When axis was disabled (`axis.disabled = true`) its ticks and grid remained visible.
- If a chart had series with bullets and `minBulletDistance` set and the chart was resized so that bullets had to be hidden, some of the bullets remained visible.
- `openCategoryX` and `openCategoryY` data fields were not working properly on `XYSeries`.
- If `XYChart` had stacked series and series had both possitive and negative numbers, series were stacked incorrectly if some of the series were hidden.
- `MapChart` was not adjusting its size to the container in some specific cases.
- Some performance improvements with `series.connect = false` and a lot of missing values.
- `Rectangle3D` was not copying side's properties when cloning.
- `ForceDirectedLink`'s data item was not properly set. It is set to target's data item now.
- `MapChart` was not displaying maps of very small countries properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
