### ISSUE TITLE
series doesn't get stacked properly

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1348]
Hey I have an example of 2 series: wind_UP & PV_UP.
I am creating these series dynamically with typescript.
When I toggle off all the other series instances(NB_DOWN & NB_UP), then I got a strange phenomena, the series PV_UP overlay the black series WIND_UP and not stacked it.
all the series instances have stacked property set to true.
I would like to know if this phenomena is:
1.bug in my implementation?
2.bug in the library?
3. desired behavior?
Here is the example:
https://stackblitz.com/edit/angular-ksxwh1

Thanks in advance,
Barak Inbal

**Comment by georgybu** [comment]
Probably stack order is matter? Please, check this version:
https://stackblitz.com/edit/angular-zo7jjp

**Comment by BrkCoder** [comment]
> Probably stack order is matter? Please, check this version:
> https://stackblitz.com/edit/angular-zo7jjp
I think this is a pretty nice workaround but not full solution,still waiting for official answer!

**Comment by martynasma** [comment]
Hm, must be a bug. We're looking into it. Will keep you posted.

This happens in a weird data setup where negative-value column series in a stack is in the middle of positive-value series.

Nevertheless, we should probably handle such contingency.

Thanks for the heads up!

**Comment by BrkCoder** [comment]
thanks martynasma for the quick respond!

**Comment by martynasma** [comment]
Fixed in [4.5.0](https://github.com/amcharts/amcharts4/releases/tag/4.5.0).

## [4.5.0] - 2019-06-14

### Added
- Support of queued chart initialization. If enabled (`am4core.options.queue = true`) the chart will not start initializing until previous chart finishes.
- Support for delayed rendering. If enabled (`am4core.options.onlyShowOnViewport = true`) the chart will start rendering itself only when scrolled into view.

### Changed
- Default CSS for a `Popup` now has text color set to ensure it is visible on default background.

### Fixed
- `dataContext` of `ForceDirectedNodeDataItem` was not being populated correctly.
- `MapPolygonSeries` was not being displayed properly if GeoJSON contained a single very small polygon.
- Tooltips now work correctly when a chart is contained within the shadow DOM.
- `rtl` inheritance was not working properly on some elements, e.g. axis tooltips.
- None of the `Responsive` events were being triggered.
- JSON: It was not possible to set `XYSeries.baseAxis` using axis' `id`.
- `LineSeries` was being cut off if div of a chart was more than 20K pixels width/height.
- When axis was disabled (`axis.disabled = true`) its ticks and grid remained visible.
- If a chart had series with bullets and `minBulletDistance` set and the chart was resized so that bullets had to be hidden, some of the bullets remained visible.
- `openCategoryX` and `openCategoryY` data fields were not working properly on `XYSeries`.
- If `XYChart` had stacked series and series had both possitive and negative numbers, series were stacked incorrectly if some of the series were hidden.
- `MapChart` was not adjusting its size to the container in some specific cases.
- Some performance improvements with `series.connect = false` and a lot of missing values.
- `Rectangle3D` was not copying side's properties when cloning.
- `ForceDirectedLink`'s data item was not properly set. It is set to target's data item now.
- `MapChart` was not displaying maps of very small countries properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
