### ISSUE TITLE
Pattern not rendering sometimes after zooming on var radar chart

### ISSUE THREAD

**Issue by matix931** [amcharts/amcharts4#1355]
![2019-06-06 13_24_49-Variable-radius radar - JSFiddle](https://user-images.githubusercontent.com/1347171/59029525-cb434e80-885e-11e9-9121-c8f2ad93393e.png)

JSFiddle: http://jsfiddle.net/pvzcyfb2/

How to reproduce: Run jsfiddle, if bug does not appear, run it again.

OS: Windows 10 64bit
Firefox 67.0: bug exists
Chrome 74.0.3729.169 64bit: bug exists
Chrome 75.0.3770.80 64bit: bug exists + performance problems
Microsoft Edge 44.17763.1.0: bug exists

Anyway, great library!

**Comment by martynasma** [comment]
Seems issue is related to your setup of changing data while the chart is animating zoom, waiting 10ms then changing data again and zooming.

Is this legit setup?

**Comment by matix931** [comment]
Not really, because 10ms is a fixed value, i don't know when rendering is done so 10ms could not be enough, also this bug can appear even not changing data, above example shows almost 100% reproductable case. I am using this chart to show around 40 stacked bars and even i set timeout to 1000ms, bug is appearing sometimes. It is really important for me, because pattern shows critical information and viewer can quickly find relevant information.

If there would be an option to disable animation on zooming or setting initial zoom before data is set.
Another option could be event something like: afterdatarendered or afterdatachangedandrendered.
Best option is to find the cause of not rendering pattern and i am aware that can be browser job.

**Comment by martynasma** [comment]
Fixed in [4.5.3](https://github.com/amcharts/amcharts4/releases/tag/4.5.3).

## [4.5.3] - 2019-06-18

### Added
- `"up"`, `"down"`, `"left"` and `"right"` options added to `Tooltip.pointerOrientation`. Allows forcing constant position/orientation of the Tooltip. Note, the tooltip might go out of div/screen boundaries when using these new orientations.
- New property added to `SliceGrouper`: `groupProperties`. It's an object comprising by key/value pairs to apply to a "group slice", e.g. `grouper.groupProperties.fill = am4core.color("red")`.
- It was impossible to reuse single pattern for multiple `Sprite` elements, as disposing one was resulting in pattern to be disposed as well.

### Fixed
- `hideOversized` was being ignored for HTML-based labels.
- `PieChart` series' `legendSettings` were shared across all series; it was impossible to set different `valueText`.
- `CategoryAxis` with HTML labels could in result excessive white space at the bottom of the chart.
- In some cases patterns set as `Sprite`'s fills using `fill` adapter were not displayed.
- When calculating totals on a Series with all zero values, `percent` was not being calculated. It will now have a zero.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
