### ISSUE TITLE
Popup/Modal: Default CSS should specify foreground color

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#1357]
The default popup CSS prescribes a white background for the popup content. Since a default background color is defined, a default foreground color should also be defined to make the text readable.

See [this codepen](https://codepen.io/anon/pen/Gaaedz?&editable=true), which is a fork of an amCharts demo with two changes:
1) CSS body color changed to white
2) Added a popup

As you can see, the white background and foreground color of the body make the popup content totally illegible.

![image](https://user-images.githubusercontent.com/23387905/59034824-f798a400-8839-11e9-91d4-e49b966d7860.png)

Adding `"color": "#000"`, to the PopupCSS.ts `StyleRule(`.${prefix}-content`, ...)` will now give a proper default text color to match the default white popup background.

![image](https://user-images.githubusercontent.com/23387905/59034866-14cd7280-883a-11e9-913a-72b32f38fb56.png)

And as a side note, I feel the addition of some type of box-shadow/stroke around the popup would be nice to ensure it is distinguished from background elements.

![image](https://user-images.githubusercontent.com/23387905/59035275-ec924380-883a-11e9-9c9a-cde6c350bd56.png)
( `box-shadow: 7px 10px 20px 0px rgba(0, 0, 0, 0.5);` )

I know all of this can be modified by user-defined CSS, but I am strictly speaking of the default values.

**Comment by martynasma** [comment]
Good catch. This will be implemented in the next release.

**Comment by martynasma** [comment]
Fixed in [4.5.0](https://github.com/amcharts/amcharts4/releases/tag/4.5.0).

## [4.5.0] - 2019-06-14

### Added
- Support of queued chart initialization. If enabled (`am4core.options.queue = true`) the chart will not start initializing until previous chart finishes.
- Support for delayed rendering. If enabled (`am4core.options.onlyShowOnViewport = true`) the chart will start rendering itself only when scrolled into view.

### Changed
- Default CSS for a `Popup` now has text color set to ensure it is visible on default background.

### Fixed
- `dataContext` of `ForceDirectedNodeDataItem` was not being populated correctly.
- `MapPolygonSeries` was not being displayed properly if GeoJSON contained a single very small polygon.
- Tooltips now work correctly when a chart is contained within the shadow DOM.
- `rtl` inheritance was not working properly on some elements, e.g. axis tooltips.
- None of the `Responsive` events were being triggered.
- JSON: It was not possible to set `XYSeries.baseAxis` using axis' `id`.
- `LineSeries` was being cut off if div of a chart was more than 20K pixels width/height.
- When axis was disabled (`axis.disabled = true`) its ticks and grid remained visible.
- If a chart had series with bullets and `minBulletDistance` set and the chart was resized so that bullets had to be hidden, some of the bullets remained visible.
- `openCategoryX` and `openCategoryY` data fields were not working properly on `XYSeries`.
- If `XYChart` had stacked series and series had both possitive and negative numbers, series were stacked incorrectly if some of the series were hidden.
- `MapChart` was not adjusting its size to the container in some specific cases.
- Some performance improvements with `series.connect = false` and a lot of missing values.
- `Rectangle3D` was not copying side's properties when cloning.
- `ForceDirectedLink`'s data item was not properly set. It is set to target's data item now.
- `MapChart` was not displaying maps of very small countries properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
