### ISSUE TITLE
Question: How to wrap category axis labels 

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#136]
Hi,

 How to wrap category axis labels into multiple lines and provide ellipses.

**Comment by martynasma** [comment]
Excellent question!

I went ahead and put together this tutorial for ya:
https://www.amcharts.com/docs/v4/tutorials/wrapping-and-truncating-axis-labels/

Hope you find this useful.

**Comment by Varshamathukumalli** [comment]
Hi, 

Thanks  for the response, if we want to use both truncate and wrapping. so is it possible by any means?
If we set maxHeight, that is not respecting when wrapping is set to true. Is there any way to limit the number of lines to display?

**Comment by martynasma** [comment]
No, I'm afraid using both `wrap` and `truncate` is currently not supported. (turning on `truncate` disables `wrap`)

There's currently no way to limit wrapped Label by number of lines. We might add this in the future, though.

**Comment by Varshamathukumalli** [comment]
That's unfortunate for us.
I have created a sample where i have provided max-width as 100 and truncate as true. 
But the last label is displaying only one character and ellipses which occupies around 30px. 
Is there any issue with max-width and truncate?
And the tooltip is also not available completely, its ripped off because of long text. Can we provide some wrapping for tooltip also?

**Comment by martynasma** [comment]
Yes:

```
categoryAxis.renderer.tooltip.label.maxWidth = 150;
categoryAxis.renderer.tooltip.label.wrap = true;
```

I don't think there's any issue with label. It's just "Lithuania" does not fit into 100px you have set. So label tries to reduce the text so it fits together with ellipsis.

There's actually a complex algorithm behind the truncation. Due to performance optimization we can't just go ahead and measure each symbol, so truncation mechanism approximates places where to cut off. Technically it might not cut off in the most optimal way. But that's a trade off we have to live with.

**Comment by Varshamathukumalli** [comment]
Thanks for the solution.

**Comment by sajidAzeem** [comment]
Hi @martynasma 
Can you please tell me how to wrap valueLabels in pieChart?
