### ISSUE TITLE
Missing data on a very wide chart

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#1362]
Please see the codepen here: https://codepen.io/npc42/pen/WBVNvY?editors=0110

If you scroll all the way to the right, you'll (hopefully) also see, that the yellow serie is missing for the last 6 days — and the tooltip is positioned on the 27th of October for later entries (28th to the 2nd of November). 

Yet I can see no difference in the last data items. Also, if I set the chart width (in the CSS) to a smaller value (even 20,000px) it starts showing correctly. At 20,300px last two days are lost, 20,400px — three(ish), and at 20,859px, which is an actual value from my application, last 6 days are not shown correctly.

The reason I have such a wide chart is that it is synced to another large scrollable div.

**Comment by NPC** [comment]
Hmmm, and if you open the codepen in Firefox and try moving your mouse above the chart, it dissapears and reappears randomly. Only seems to happen on the later dates (around October). Not sure if it's related, but it doesn't seem happen on a narrower version.

Here's what I'm seeing:
![2019-06-07_11-09-04](https://user-images.githubusercontent.com/564364/59124517-baedab00-8914-11e9-842c-a3fb12343602.gif)

**Comment by martynasma** [comment]
Fixed in [4.5.0](https://github.com/amcharts/amcharts4/releases/tag/4.5.0).

## [4.5.0] - 2019-06-14

### Added
- Support of queued chart initialization. If enabled (`am4core.options.queue = true`) the chart will not start initializing until previous chart finishes.
- Support for delayed rendering. If enabled (`am4core.options.onlyShowOnViewport = true`) the chart will start rendering itself only when scrolled into view.

### Changed
- Default CSS for a `Popup` now has text color set to ensure it is visible on default background.

### Fixed
- `dataContext` of `ForceDirectedNodeDataItem` was not being populated correctly.
- `MapPolygonSeries` was not being displayed properly if GeoJSON contained a single very small polygon.
- Tooltips now work correctly when a chart is contained within the shadow DOM.
- `rtl` inheritance was not working properly on some elements, e.g. axis tooltips.
- None of the `Responsive` events were being triggered.
- JSON: It was not possible to set `XYSeries.baseAxis` using axis' `id`.
- `LineSeries` was being cut off if div of a chart was more than 20K pixels width/height.
- When axis was disabled (`axis.disabled = true`) its ticks and grid remained visible.
- If a chart had series with bullets and `minBulletDistance` set and the chart was resized so that bullets had to be hidden, some of the bullets remained visible.
- `openCategoryX` and `openCategoryY` data fields were not working properly on `XYSeries`.
- If `XYChart` had stacked series and series had both possitive and negative numbers, series were stacked incorrectly if some of the series were hidden.
- `MapChart` was not adjusting its size to the container in some specific cases.
- Some performance improvements with `series.connect = false` and a lot of missing values.
- `Rectangle3D` was not copying side's properties when cloning.
- `ForceDirectedLink`'s data item was not properly set. It is set to target's data item now.
- `MapChart` was not displaying maps of very small countries properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
