### ISSUE TITLE
On PieChart series' legendSettings is shared across all series; it's impossible to set different valueText

### ISSUE THREAD

**Issue by Eldair** [amcharts/amcharts4#1380]
Hello,

When instantiating Pie chart I have a special item in dataset where the value is formatted the way I need it to be. That item's key is used for tooltips where it works as before:

`series.slices.template.tooltipText = '{category}: [bold]{special_item} / {value.percent.formatNumber('#.0')}%[/]'`

In the same way I referenced it for leggendSettings.valueTest

`series.legendSettings.valueText = '{special_item}';`

It worked correctly up until few versions ago (not sure which one). Bug with how it works now is that it displays values only from 1st series for all series, no matter how many there are.

Reporoduction:
https://codepen.io/Eldair/pen/rExVde

**Comment by Eldair** [comment]
UPDATE: I've now tested this with all *.4.* version and it doesn't work, perhaps it never did, but still, it works for tooltips, why not for legend as well?

**Comment by martynasma** [comment]
I'm looking at the codepen. It seems like it does work:

![image](https://user-images.githubusercontent.com/1458520/59547304-7cc03f00-8f45-11e9-9fb4-03f0670aa30c.png)

Am I missing something?

**Comment by Eldair** [comment]
It shows the same value for both instances of Czech republic in the legend and they are not the same (400 and 500)

**Comment by martynasma** [comment]
Gotcha.

It seems like `legendSettings` object is shared across series. So the last `valueText` overrides the rest of them.

We'll need to fix that. Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.5.3](https://github.com/amcharts/amcharts4/releases/tag/4.5.3).

## [4.5.3] - 2019-06-18

### Added
- `"up"`, `"down"`, `"left"` and `"right"` options added to `Tooltip.pointerOrientation`. Allows forcing constant position/orientation of the Tooltip. Note, the tooltip might go out of div/screen boundaries when using these new orientations.
- New property added to `SliceGrouper`: `groupProperties`. It's an object comprising by key/value pairs to apply to a "group slice", e.g. `grouper.groupProperties.fill = am4core.color("red")`.
- It was impossible to reuse single pattern for multiple `Sprite` elements, as disposing one was resulting in pattern to be disposed as well.

### Fixed
- `hideOversized` was being ignored for HTML-based labels.
- `PieChart` series' `legendSettings` were shared across all series; it was impossible to set different `valueText`.
- `CategoryAxis` with HTML labels could in result excessive white space at the bottom of the chart.
- In some cases patterns set as `Sprite`'s fills using `fill` adapter were not displayed.
- When calculating totals on a Series with all zero values, `percent` was not being calculated. It will now have a zero.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
