### ISSUE TITLE
AxisRange toggle visibility

### ISSUE THREAD

**Issue by KevinFernandes** [amcharts/amcharts4#1397]
If I have an AxisRange on a date axis and call setVisibility(false), it correctly hides the AxisRange, but if I later setVisibility(true), the range is not displayed.  I tried also calling validate() as high up the chain as I could (including the chart itself) with not success at getting it to show.

Is this the correct way to toggle the visibility of an AxisRange or is there an other technique to use or can it be done at all?

**Comment by KevinFernandes** [comment]
If instead of calling setVisibility(), I call show()/hide() it works as expected.
Is this how it is supposed to work?

**Comment by zeroin** [comment]
We will fix this issue, thank you. Meanwhile you can use show/hide or axisRange.contents.show/hide/setVisibility methods.

**Comment by martynasma** [comment]
Fixed in [4.5.4](https://github.com/amcharts/amcharts4/releases/tag/4.5.4).

## [4.5.4] - 2019-07-08

### Added
- `allwaysShowTooltip` property added to `Sprite`. Allows tooltip to be shown without the need for hovering/selecting an element.
- `NumberFormatter` now supports `"!"` modifier which works in conjunction with `"a"` and `"b"` modifiers. If used, formatter will force application of a prefix/suffix for values that do not fit into any of the defined prefix lists. This is useful in cases you want to format all of the values using same prefix, e.g. "B" and want even small values to be formatted as such (`500,000` formatted as `"0.5B"`).

### Fixed
- `CategoryAxis` tooltip could show incorrect category if its `renderer.tooltipLocation` was set to `0`.
- Memory leak which happened when disposing a chart with `XYChartScrollbar` with series added to it fixed.
- Some series stacking issues fixed.
- Issue with `baseDuration.timeUnit = "yyyy"` and `StepLineSeries` fixed.
- In some cases `DateAxis` tooltips would show empty near edge of the plot area.
- `CategoryAxis.indexToPosition` adjusted to work better with no default `startLocation` and `endLocation` values.
- `WordCloud` could go into stackoverflow if `minWordLenght` was set to a number which resulted in no words to appear at all.
- `ForceDirectedSeries` were resulting in JS error if inited in a hidden container.
- If an axis range was made invisible by setting its `visible = false`, and then visibility was set back to `true` again, axis range was not shown.
- JSON: entries of type `OrderedListTemplate` or `SortedListTemplate` was not being processed correctly as templated lists.
- Legend items were still focusable/togglable via keyboard even if `clickable`/`focusable` on their respective containers were set to to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by cowwoc** [comment]
@martynasma I'm seeing this exact same issue in version 4.10.16. Should I open a separate bug report? Are you able to reproduce the problem on your end?
