### ISSUE TITLE
Axis margin/label width not adjusted after label text adapter is executed

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1398]
A user noticed that when an adapter is used to shorten an axis label, the axis seems to preserve the width of the original label rather than adjusting the label/margin to accommodate the new label.

Demo illustrating the same chart with and without the adapter applied: https://codepen.io/team/amcharts/pen/1a54e2d24f9769c4e9a602bfde8e784d

Note: The custom formatter is necessary due to user requirements, so switching to numberFormat + prefixesOfBig/SmallNubers is not an option.

**Comment by zeroin** [comment]
We will fix this issue in next release. Meanwhile a solution would be to add this:

`  valueAxis.ghostLabel.adapter.add("text", (text)=>{
  	return "";
  })`

**Comment by martynasma** [comment]
Fixed in [4.5.4](https://github.com/amcharts/amcharts4/releases/tag/4.5.4).

## [4.5.4] - 2019-07-08

### Added
- `allwaysShowTooltip` property added to `Sprite`. Allows tooltip to be shown without the need for hovering/selecting an element.
- `NumberFormatter` now supports `"!"` modifier which works in conjunction with `"a"` and `"b"` modifiers. If used, formatter will force application of a prefix/suffix for values that do not fit into any of the defined prefix lists. This is useful in cases you want to format all of the values using same prefix, e.g. "B" and want even small values to be formatted as such (`500,000` formatted as `"0.5B"`).

### Fixed
- `CategoryAxis` tooltip could show incorrect category if its `renderer.tooltipLocation` was set to `0`.
- Memory leak which happened when disposing a chart with `XYChartScrollbar` with series added to it fixed.
- Some series stacking issues fixed.
- Issue with `baseDuration.timeUnit = "yyyy"` and `StepLineSeries` fixed.
- In some cases `DateAxis` tooltips would show empty near edge of the plot area.
- `CategoryAxis.indexToPosition` adjusted to work better with no default `startLocation` and `endLocation` values.
- `WordCloud` could go into stackoverflow if `minWordLenght` was set to a number which resulted in no words to appear at all.
- `ForceDirectedSeries` were resulting in JS error if inited in a hidden container.
- If an axis range was made invisible by setting its `visible = false`, and then visibility was set back to `true` again, axis range was not shown.
- JSON: entries of type `OrderedListTemplate` or `SortedListTemplate` was not being processed correctly as templated lists.
- Legend items were still focusable/togglable via keyboard even if `clickable`/`focusable` on their respective containers were set to to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
