### ISSUE TITLE
Exporting external containers through extraSprites doesn't export correctly when different positions are used

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#1399]
A user noticed that when he set his external containers into the exporting object's extraSprites array that the second sprite added with a different `position` value set doesn't get exported properly; the space for the sprite is included in the output but the contents are missing. If you set both extraSprites to the same position , such as "bottom", then both containers are exported correctly.

Demo: https://codepen.io/BankofCanada/pen/qzRoxO?editors=0010. Note that the legend is missing in this case but the space is in the image/pdf output. If you set the sprite containing the title container to "bottom" both will get exported.

**Comment by martynasma** [comment]
Fixed in [4.5.5](https://github.com/amcharts/amcharts4/releases/tag/4.5.9).

## [4.5.9] - 2019-07-24

### Added
- `above` property added to `AxisTick`, `Grid`, and `AxisFill`. Allows putting individual elements on top of the series even if all the other grids/ticks/axis fills are below them.
- `bullet` property added to `AxisDataItem`. Allows adding bullets to the axes. You can have both `AxisBullet` (new class) or a simple `Sprite` there.
- New element class `AxisBullet`. Use `AxisBullet` which is a container with a `location` property in case you want to adjust bullet location within cell.

### Fixed
- JSON: Series-bound axis ranges were breaking whole chart in JSON-based setups.
- In some rare cases `NumberFormatter` was suffering from floating point number precision issue when calculating big number prefixes.
- Updating data was causing Annotation menu item to duplicate.
- Exporting `extraSprites` with different positions didn't work.
- Responsive rules were not always kicking in on first load if there were multiple charts on the same page.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
