### ISSUE TITLE
FunnelSeries' labels & ticks `disabled` option doesn't work correctly

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1404]
Example:
https://codepen.io/dmsmaxim/pen/qzPNzJ?editors=1010

When you set `series.labels.template.disabled = series.ticks.template.disabled = false;` after 5s, only space for labels becomes available but labels themself stay invisible.

**Comment by zeroin** [comment]
This happens because initially labels and ticks are hidden and they are shown when series is inited. As you disable labels and ticks initially, they are not show. So to solve this you either need to loop through all labels/ticks and call `show()` for each of them or set opacity to 1 for label/tick template:

```
series.labels.template.opacity = 1;
series.ticks.template.opacity = 1;
```

**Comment by dmsmaxim** [comment]
But this works well for Pie chart
