### ISSUE TITLE
XYChart Cursor Tooltip CategoryAxis Tooltip Empty

### ISSUE THREAD

**Issue by Infineon12** [amcharts/amcharts4#1405]
Example present on Demo Page:
https://www.amcharts.com/demos/smoothed-line-chart/

The cursor category tooltip on the right edge does not show any textual value.
See screenshot.
![2019-06-26 13_39_40-Smoothed Line Chart - amCharts](https://user-images.githubusercontent.com/2978137/60177012-22ae5c00-9818-11e9-8153-268baf314d28.png)

If i copy the code to a fiddle:
http://jsfiddle.net/jkcht5vm/

And edit the 
categoryAxis.endLocation = 0.5;
to a value >= 0.6 it does work.

This i not so nice due to the fact that i really want to end at 0.5.

Thanks for your support.

Marco

**Comment by martynasma** [comment]
Fixed in [4.5.4](https://github.com/amcharts/amcharts4/releases/tag/4.5.4).

## [4.5.4] - 2019-07-08

### Added
- `allwaysShowTooltip` property added to `Sprite`. Allows tooltip to be shown without the need for hovering/selecting an element.
- `NumberFormatter` now supports `"!"` modifier which works in conjunction with `"a"` and `"b"` modifiers. If used, formatter will force application of a prefix/suffix for values that do not fit into any of the defined prefix lists. This is useful in cases you want to format all of the values using same prefix, e.g. "B" and want even small values to be formatted as such (`500,000` formatted as `"0.5B"`).

### Fixed
- `CategoryAxis` tooltip could show incorrect category if its `renderer.tooltipLocation` was set to `0`.
- Memory leak which happened when disposing a chart with `XYChartScrollbar` with series added to it fixed.
- Some series stacking issues fixed.
- Issue with `baseDuration.timeUnit = "yyyy"` and `StepLineSeries` fixed.
- In some cases `DateAxis` tooltips would show empty near edge of the plot area.
- `CategoryAxis.indexToPosition` adjusted to work better with no default `startLocation` and `endLocation` values.
- `WordCloud` could go into stackoverflow if `minWordLenght` was set to a number which resulted in no words to appear at all.
- `ForceDirectedSeries` were resulting in JS error if inited in a hidden container.
- If an axis range was made invisible by setting its `visible = false`, and then visibility was set back to `true` again, axis range was not shown.
- JSON: entries of type `OrderedListTemplate` or `SortedListTemplate` was not being processed correctly as templated lists.
- Legend items were still focusable/togglable via keyboard even if `clickable`/`focusable` on their respective containers were set to to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
