### ISSUE TITLE
strange behavior of 2 stacked series in different scales

### ISSUE THREAD

**Issue by BrkCoder** [amcharts/amcharts4#1434]
Hey I have occurred strange behavior when creating 2 series of columns:
The first series has values between 10,000 - 100,000,
The second series has values between 10 - 100 .
Two of this series are stacked! , when I am toggling with the legend,
When I toggle the first series(10,000 - 100,000), the 2 series are disappeared from the chart,
When I  toggle the second series(10 - 100), only the desired series is disappeared from the chart.
Here is the example:
[https://stackblitz.com/edit/amcharts-bug-20448-abypw4](https://stackblitz.com/edit/amcharts-bug-20448-abypw4)
I am suspect that this is a bug because  this phenomena doesn't occurred when:
1. I cancel the stacked property(set it to false)
2. I switch the 2 series order of creation.

Please provide a clarification regrading this issue asap.

Thanks in advance,
Barak Inbal

**Comment by zeroin** [comment]
I confirm it's a bug, trying to fix it now.

**Comment by martynasma** [comment]
Fixed in [4.5.4](https://github.com/amcharts/amcharts4/releases/tag/4.5.4).

## [4.5.4] - 2019-07-08

### Added
- `allwaysShowTooltip` property added to `Sprite`. Allows tooltip to be shown without the need for hovering/selecting an element.
- `NumberFormatter` now supports `"!"` modifier which works in conjunction with `"a"` and `"b"` modifiers. If used, formatter will force application of a prefix/suffix for values that do not fit into any of the defined prefix lists. This is useful in cases you want to format all of the values using same prefix, e.g. "B" and want even small values to be formatted as such (`500,000` formatted as `"0.5B"`).

### Fixed
- `CategoryAxis` tooltip could show incorrect category if its `renderer.tooltipLocation` was set to `0`.
- Memory leak which happened when disposing a chart with `XYChartScrollbar` with series added to it fixed.
- Some series stacking issues fixed.
- Issue with `baseDuration.timeUnit = "yyyy"` and `StepLineSeries` fixed.
- In some cases `DateAxis` tooltips would show empty near edge of the plot area.
- `CategoryAxis.indexToPosition` adjusted to work better with no default `startLocation` and `endLocation` values.
- `WordCloud` could go into stackoverflow if `minWordLenght` was set to a number which resulted in no words to appear at all.
- `ForceDirectedSeries` were resulting in JS error if inited in a hidden container.
- If an axis range was made invisible by setting its `visible = false`, and then visibility was set back to `true` again, axis range was not shown.
- JSON: entries of type `OrderedListTemplate` or `SortedListTemplate` was not being processed correctly as templated lists.
- Legend items were still focusable/togglable via keyboard even if `clickable`/`focusable` on their respective containers were set to to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
