### ISSUE TITLE
Maps with custom GeoJson data only show one feature (geographical region) out of many

### ISSUE THREAD

**Issue by chesnutcase** [amcharts/amcharts4#1438]
I'm following the [Amcharts Map tutorial](https://www.amcharts.com/docs/v4/chart-types/map/#Loading_external_maps) to create a visualisation using other open sourced geodata.

I'm trying to display a map of Indonesia with different provinces shown, using the `indonesia-province.json` file from the [superpika/indonesia-geojson](https://github.com/superpikar/indonesia-geojson) repository. I followed the tutorial step by step but this is what I get when I'm at the section [Loading Series Data](https://www.amcharts.com/docs/v4/chart-types/map/#Loading_series_data) of the tutorial:

![photo_2019-07-05_22-27-25](https://user-images.githubusercontent.com/32205524/60728939-222e6780-9f74-11e9-8bc4-3d20acf150cd.jpg)

It only shows one province, the province of Papua.

Thinking that there was something wrong with the GeoJson file, I opened it up in the [HERE XYZ GeoJson Visualizer](http://geojson.tools/), and got this:

![photo_2019-07-05_22-30-31](https://user-images.githubusercontent.com/32205524/60729107-82bda480-9f74-11e9-86c3-b6718aaa4389.jpg)

The viewer shows all provinces. The province of Papua is the easternmost province in blue.

I tried the other geojson files in the [superpika/indonesia-geojson](https://github.com/superpikar/indonesia-geojson) repository, but all yielded me the same result showing only one province (one geographical feature in the GeoJson file).

I then tried to try Amcharts using another country's GeoJson data, so i grabbed a map of Japan from [dataofjapan/land](https://github.com/dataofjapan/land)'s `japan.geojson` file, and it works correctly without changing other lines of code (i.e. only change was the `map.geodataSource.url` property):

![photo_2019-07-05_22-41-18](https://user-images.githubusercontent.com/32205524/60729788-193e9580-9f76-11e9-8788-fafb22fc5f79.jpg)

The full map is clipped, but I could still click and drag to pan around to see the rest of the map. With the Indonesia GeoJson, panning doesn't show me anything else.

I've tried other GeoJson files of indonesia such as [this repository](https://github.com/ans-4175/peta-indonesia-geojson) too and several other sites, but they all yield the same result of showing only *one* province out of many.

Is there something wrong with the Indonesia GeoJson files that Amcharts can't handle? Why could the Japan GeoJson file load but not Indonesia's?

[CodePen Demo here](https://codepen.io/chesnutcase/pen/ZdMBmW)

**Comment by zeroin** [comment]
Each feature of geoJSON must have an unique id - your geoJSON does not have them.  id should go as feature property, not in the properties object.

**Comment by rogobgobs** [comment]
have it works?

**Comment by sankhaKarunasekara** [comment]
I had the same issue & it took me three days to figure everything out with some [StackOverflow ](url)help.  When I use http://mapshaper.org/ to simplify my custom map, as explained in [this turorial](https://www.amcharts.com/docs/v4/tutorials/creating-custom-maps/) it failed to render the map with all the features. It only shows me the last feature of a geojson feature collection. If you have the same issue, check these things,

1. Check whether you have an id as a property of Feature. 
`[{
    "type": "Feature",
    "id": "MON",
    "properties": {
        "electoralDistrictCode": "MON",
        "electoralDistrict": "Monaragala",
        // ...
    },
    "geometry": {/* ... */}
},{...`

2. The direction of coordinates. 
-  Your coordinates inside geometry should be in the clockwise direction otherwise Amchart failed to render the custom map correctly.

I find that http://mapshaper.org/ was rearranging your maps coordinates in the anti-clockwise direction when you download your map as a geojson. I couldn't yet find a way to reverse it inside the mapshaper but I get my map working by using 
https://github.com/mapbox/geojson-rewind to rewind the coordinates. 

hope it helps.

**Comment by clintharris** [comment]
geojson-rewind didn't work for me, but reversing the coordinates array after loading the geojson as described in #2810 did the trick

**Comment by achillesp** [comment]
If there's anyone still having similar issues, using geojson-rewind --clockwise solved the issue on my case.
