### ISSUE TITLE
RadarChart: Randomly zooms in when series appear

### ISSUE THREAD

**Issue by klmntoth** [amcharts/amcharts4#1441]
Sometimes when the series appear, the chart zooms in randomly, then it stays zoomed in or jumps back to normal.

https://codepen.io/anon/pen/bPmgeP
(press the create series button, might not work first try)

![stuck](https://user-images.githubusercontent.com/47834753/60771336-ce905b00-a0e6-11e9-8669-40e3cb16fb52.gif)
![jumping](https://user-images.githubusercontent.com/47834753/60771337-d0f2b500-a0e6-11e9-8ffa-4b2bd9820b95.gif)

**Comment by martynasma** [comment]
Indeed, something funky going on. We're looking into it.

**Comment by martynasma** [comment]
Fixed in [4.5.5](https://github.com/amcharts/amcharts4/releases/tag/4.5.5).

## [4.5.5] - 2019-07-12

### Added
- New property `updateCurrentData` added to `DataSource`. If set to `true` it will try to overwrite values (resulting in smooth animations) in current data rather than overwriting whole data set.
- Feature added back: Support of queued chart initialization. If enabled (`am4core.options.queue = true`) the chart will not start initializing until previous chart finishes.
- Feature added back: Support for delayed rendering. If enabled (`am4core.options.onlyShowOnViewport = true`) the chart will start rendering itself only when scrolled into view.

### Fixed
- Accessibility: The screen reader description for column/bullet/slice was not being added properly every time.
- On `RadarChart` data updates sometimes `ValueAxis` scale was not being calculated corrently.
- `alwaysShowTooltip` was not working properly in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
