### ISSUE TITLE
Wrong values in tooltips and labels for dates (even with baseInterval)

### ISSUE THREAD

**Issue by anton-paskanny** [amcharts/amcharts4#1450]
I have an array with dates, each date is ISOstring, then I transform it into a standard js Date object. The interval for dateAxis is configured to 7 days (that's according to the dates in source array). And in tooltip after 7/28 goes 7/31, but in the array after 7/28 goes 8/04. And labels on dateAxis don't correspond with values from a source array. I can't image what's going wrong with the library or my actions to configure it. Any ideas on how to fix that? Thanks a lot in advance!

Here is the link to the demo: https://codepen.io/anon/pen/bPjWbQ?editors=0010

P.S. am4chart version I use is 4.5.3.

**Comment by martynasma** [comment]
That is correct. Since your data points come in weekly intervals the DateAxis switches itself into weekly mode, where it displays a grid line/label for each week.

The date representing a week is not the one for actual data item, but rather first day of the week.

So when you have Sep 8 date, you get label Sep 2, since that is the date for Monday of Sep 8's week.

If you need labels to be in exactly the same day as the data item itself, you need the chart in daily mode:

```
dateAxis.baseInterval = {
  "timeUnit": "day",
  "count": 1
};
```

**Comment by anton-paskanny** [comment]
@martynasma Thanks a lot for your explanation. It's really helpful!
