### ISSUE TITLE
Brackets escaping problem in the multiline tooltip label

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1452]
Example:
https://codepen.io/dmsmaxim/pen/rEPMxW
As you can see here starting from the second line brackets are not escaped properly and value simply isn't shown as on the first line.
![image](https://user-images.githubusercontent.com/15041200/60968260-4fd53100-a325-11e9-95bf-f3730601306a.png)

To escape brackets I follow this instruction: 
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-strings/#Escaping

**Comment by martynasma** [comment]
I suppose this is happening because auto-wrap is splitting mid-brackets somewhere.

If you would add a line break after each iteration it would be fine.

Nevertheless it's a bug. We're going to look into it. Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.5.6](https://github.com/amcharts/amcharts4/releases/tag/4.5.6).

## [4.5.6] - 2019-07-16

### Added
- New property on `Annotation` plugin: `data`. Allows getting serialized annotation data object, as well as setting it back to load annotations.

### Changed
- Annotation plugin will not create full Export menu if it wasn't explicitly created before.
- Tweaked CSS for `ExportMenu` to protect from icons getting small becuase of the page-wide CSS.
- When exporting data on chart with `exporting.dateFormat` set, the date/time fields in data will be formatted according to the set format.

### Fixed
- `XYChartScrollbar` with series attached to different `ValueAxis` were using same axis scale in the scrollbar.
- Using `wrap = true` on horizontal axis labels was resulting weird behavior when zooming in some cases.
- Export was not prioritizing menu item's specific options over generic format options.
- Auto-wrapped text was not retaining square bracket escaping (double bracket) for each subsequent line.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
