### ISSUE TITLE
RadarChart: without data xAxes.push causes console error

### ISSUE THREAD

**Issue by klmntoth** [amcharts/amcharts4#1455]
```
ngAfterViewInit(): void {
    this.zone.runOutsideAngular(() => {
      const chart = am4core.create('chartdiv', am4charts.RadarChart);
      
      const categoryAxis = chart.xAxes.push(
        new am4charts.CategoryAxis<am4charts.AxisRendererCircular>()
      );
      
      this.chart = chart;
    });
  }
```
pushing to xAxes gives this error on the console:
Error: <path> attribute d: Expected number, " MNaN,NaN  LNaN,Na…".  AMElement.ts:631 

code and package versions here:
https://stackblitz.com/edit/angular-ikce7e

open this to see the error on the console:
https://angular-ikce7e.stackblitz.io/

**Comment by martynasma** [comment]
Fixed in [4.5.6](https://github.com/amcharts/amcharts4/releases/tag/4.5.6).

## [4.5.6] - 2019-07-16

### Added
- New property on `Annotation` plugin: `data`. Allows getting serialized annotation data object, as well as setting it back to load annotations.

### Changed
- Annotation plugin will not create full Export menu if it wasn't explicitly created before.
- Tweaked CSS for `ExportMenu` to protect from icons getting small becuase of the page-wide CSS.
- When exporting data on chart with `exporting.dateFormat` set, the date/time fields in data will be formatted according to the set format.

### Fixed
- `XYChartScrollbar` with series attached to different `ValueAxis` were using same axis scale in the scrollbar.
- Using `wrap = true` on horizontal axis labels was resulting weird behavior when zooming in some cases.
- Export was not prioritizing menu item's specific options over generic format options.
- Auto-wrapped text was not retaining square bracket escaping (double bracket) for each subsequent line.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
