### ISSUE TITLE
Scrollbar chart with multiple Axes displays series using wrong ValueAxis

### ISSUE THREAD

**Issue by thunderbolt10** [amcharts/amcharts4#1457]
I have a chart with 2 vertical value Axes and one of the series is always displayed in the scrollbar with the wrong scale, like it is using the scale from the secondary axis instead.

Here is a codepen [example](https://codepen.io/thunderbolt10/pen/WWpXwK) where series S1 is not drawn correctly in the scrollbar because it is scaled to use the larger right hand axis scale. Series S1 and S2 uses the left hand ValueAxis whilst series S3 should be the only series drawn against the right hand axis.
 
The affect is switched by reversing the order of the 2 lines (89 and 90) so that series S2 is then drawn incorrectly in the scrollbar:

with:
```
scrollbarX.series.push(series2);
scrollbarX.series.push(series1);
```
![image](https://user-images.githubusercontent.com/30114322/61125264-525c9580-a4a1-11e9-92b9-f945b2877d64.png)

with:
```
scrollbarX.series.push(series1);
scrollbarX.series.push(series2);
```
![image](https://user-images.githubusercontent.com/30114322/61125395-9b144e80-a4a1-11e9-854f-eb45dc3e0a68.png)

**Comment by martynasma** [comment]
Fixed in [4.5.6](https://github.com/amcharts/amcharts4/releases/tag/4.5.6).

## [4.5.6] - 2019-07-16

### Added
- New property on `Annotation` plugin: `data`. Allows getting serialized annotation data object, as well as setting it back to load annotations.

### Changed
- Annotation plugin will not create full Export menu if it wasn't explicitly created before.
- Tweaked CSS for `ExportMenu` to protect from icons getting small becuase of the page-wide CSS.
- When exporting data on chart with `exporting.dateFormat` set, the date/time fields in data will be formatted according to the set format.

### Fixed
- `XYChartScrollbar` with series attached to different `ValueAxis` were using same axis scale in the scrollbar.
- Using `wrap = true` on horizontal axis labels was resulting weird behavior when zooming in some cases.
- Export was not prioritizing menu item's specific options over generic format options.
- Auto-wrapped text was not retaining square bracket escaping (double bracket) for each subsequent line.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
