### ISSUE TITLE
How to read/use the reference documentation?

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1459]
I'm trying to start with my serie hidden, so searching the reference:   
https://www.amcharts.com/docs/v4/reference/columnseries/   
I've found there is a "visible" property   
But when I set:   
[var series = chart.series.push(new am4charts.ColumnSeries());
series.visible = false;](url)
It does not start hidden.   
But I'm not sure if that's the correct way to set it, the documentation is very confusing because there are properties that are called like this in the example:   
`series.slices.template.cursorDownStyle = am4core.MouseCursorStyle.grabbing;   `
Why is not directly series.cursorDownStyle? I mean how can we know the "full path" to call the property?

**Comment by zeroin** [comment]
To have series initially hidden, you should set `series.hidden = true` visibility doesn't work here, as initially series are hidden and then shown for the animation to happen. 

Your slices are clickable, that's why you set the cursorDownStyle on slices.template. In case your whole series would be clickable (you might need to add some event for that) then you could add cursorDownStyle on series as well.

**Comment by enriquepiatti** [comment]
OK, the hidden property works fine. But I'm still confused about when to use series.PROPERTY or for example series.columns.template.PROPERTY etc

**Comment by martynasma** [comment]
@enriquepiatti 

`series.slices.template` applies properties to slices. There are no actual slice objects available when chart is created because data is not yet parsed, so you cannot set them directly, hence you set them on a "template", and they are propagated to all slices on that series when they are being created.

`series.***` is the series itself. So you set series-related properties, such as `hidden`.

Hope that makes sense.

**Comment by enriquepiatti** [comment]
Yes it makes sense, the problem is not with the code, but with the documentation.    
The slices is just one example, what I mean is that for (for example) if you go here:   
https://www.amcharts.com/docs/v4/reference/columnseries/   
You will see a property: "cursorDownStyle" just as that, without anything else.    
But we cannot use "cursorDownStyle" directly on the series (series.cursorDownStyle) neither the template of the serie (series.template.cursorDownStyle) the correct way to use that property is:   
series.slices.template.cursorDownStyle   
In that particular case we can know that because there is an example showing it, but how can we guess that only from documentation?     
The docs are showing all the properties at the same level, how can we know which inner object those properties belong?

**Comment by martynasma** [comment]
It's called inheritance :)

Jokes aside, I agree that class reference is somewhat overwhelming with the sheer amount of properties available. Sometimes it helps turning off inherited properties to get a better look at class'es native ones.

**Comment by enriquepiatti** [comment]
it's not inheritance with inheritance we can use the property on the same object, in any case is some type of composition, but then we need to know the inner object and that's not present in the docs, or at least I don't know how to read, let's take this example:   
https://www.amcharts.com/docs/v4/reference/columnseries/
"cursorDownStyle" property
it says:    
"Type Array < IStyleProperty >  Inherited from Sprite"    
and it is used as:    
series.slices.template.cursorDownStyle   
How can we guess that "cursorDownStyle" must be called inside "slices.template"?

**Comment by martynasma** [comment]
Well, I agree that concept of "list templates" gets some getting used to it. But once you figure it our, it's quite straightforward.

https://www.amcharts.com/docs/v4/concepts/list-templates/

**Comment by enriquepiatti** [comment]
That page says: 

> Many of the properties, in amCharts 4's classes, that require this piece of functionality, are already list templates. These properties are indicated with type ListTemplate in Class reference. 

but searching "listtemplate" in https://www.amcharts.com/docs/v4/reference/columnseries/ gives 0 results.   
The thing with the docs is that for example you have exactly at the same level the property "name" and "alwaysShowTooltip", but name is used with series.name and alwaysShowTooltip with series.columns.template.alwaysShowTooltip, what I'm asking is how can we know that? if must be used inside a "series.columns.template." or inside "series.columns." or just inside "series."

**Comment by martynasma** [comment]
I don't think you're looking close enough.

![image](https://user-images.githubusercontent.com/1458520/61574132-4ab17800-aac3-11e9-81da-6fc543e43d4d.png)

I guess you know it by experience.

Everything in amCharts 4 is a `Sprite`. Including Series and it's child Columns. Hence they both having similar properties.

Does it make it a bit harder to master? Yes. Does it also make it super flexible and able to do a lot of things even we haven't imagined? Also, yes.

Documentation cannot account for every possible scenario. So it's down to you to employ sense and combine it with knowledge of key concepts in amCharts, such as "list templates", "property fields", etc.

Ask yourself, does setting `alwaysShowTooltip` directly on a series make sense? What tooltip would you show on a series? The answer is: no it does not make sense.

Does `alwaysShowTooltop` make sense in the scope of a column? Yes it does. A column has specific data, location, and can display a meaningful tooltip.

Since I learned about key concepts, I know that the way to configure a column in a `ColumnSeries` is via `columns.template`. It holds a "template" object of `Column` which is used as a model to sculpt all actual columns in the series when they are created. Whatever we set on a "template" will end up on actual column objects.

Do I want to display tooltips on all of the columns? No, I don't.

In this case I use `propertyFields` on a `column.template` to dynamically set value of this particular property for each column via data.

Hope that sounds reasonable.

---

I suppose that additional level of confusion might come from the fact that seemingly some settings are inherited by children object and some are not.

Actually, none of the settings are inherited. So if you set `alwaysShotTooltip` on a Series, it won't be `true` on its child columns.

However, due to the nature of SVG, visual properties ARE inherited by children.

So if you set `fill` on Series, it affects columns, because `fill` property gets inherited by column elements from its parent series group.

Hope that all makes sense.

**Comment by enriquepiatti** [comment]
I'm not complaining about the design in Amcharts, I really like the library, but I find the docs very confusing, beucase https://www.amcharts.com/docs/v4/reference/columnseries/ is for one class "ColumnSeries" and then it shows the properties of that class, but they are not!       
I mean, "name" for example is a property of that clase, but not alwaysShotTooltip:    
var series = new am4charts.ColumnSeries();   // series is an object of ColumnSeries
series.name = 'something';   // name is a property of ColumnSeries object, this is OK
series.columns.template.alwaysShowTooltip;  // alwaysShowTooltip is a property of "template" not ColumnSeries, and also we need to know the full path ".columns.template." both things are not in the documentation, I mean you need to "know" that, the poit of having a reference of the properties is to learn what we can do right?     
Maybe could be solved just adding an extra note to every property, to know if is a property of "series" object, or "columns" object, or "columns.template" object etc.
The thing is that is not inheritance, those properties are in different objects and they are all mixed.

**Comment by martynasma** [comment]
`alwaysShowTooltip` IS a property of ColumnSeries. It's also a property of Column, Scrollbar, Button, and several hundred of other classes. Whether it makes sense to actually use them on all of those, is another matter, and down to developer to decide.
