### ISSUE TITLE
Label adapter "textOutput" is not receiving all the labels

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1461]
I want to filter some lables because there are too many to show them all, so I'm using this adapter:

```
                            categoryAxis.renderer.labels.template.adapter.add("textOutput", function(text) {
                                const price = +text;
                                if((price % 100) <= groupPrice) return text;
                                return '';
                            });
```
But that function is not only receiving duplicate values but also is not receiving some labels! not sure based on what. Is this normal?

**Comment by martynasma** [comment]
A better way to control density of axis labels is via `minGridDistance`:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

That said, all labels should go through this adapter. If you say some don't, can you post it as a working example?

As for the "duplicate values", the axis creates extra labels that are not visible at this moment but might be necessary when situation changes, such as chart is zoomed. Those might come across as excessive labels.

It's by design.

**Comment by enriquepiatti** [comment]
minGridDistance works much better thanks !   
just to answer, is not that there are some labels I don't want to show, the problem was there are too many and they were overlapping

**Comment by martynasma** [comment]
So... all set? :)

**Comment by enriquepiatti** [comment]
Yes thanks !! :)
