### ISSUE TITLE
Series legend disappears unless mouse is over chart

### ISSUE THREAD

**Issue by vdurante** [amcharts/amcharts4#1472]
I don't know if this is related to Angular, but whenever my mouse is not over the chart, the legend becomes invisible.

Apparently this happens since I am creating a separate LineSeries for each line instead of a single series with different attributes containing the value of each line.

https://codepen.io/anon/pen/RXwwoB?editors=0010

## Mousover
![image](https://user-images.githubusercontent.com/5401232/61422937-3b280880-a8e4-11e9-8db5-b8d69d7afc33.png)

## Normal
![image](https://user-images.githubusercontent.com/5401232/61422946-3fecbc80-a8e4-11e9-80e8-8b4265850ade.png)

**Comment by martynasma** [comment]
OK, couple of things. One normal, the other a bit weird :)

1) Let's start with the obvious one. None of your series have their `name` set, which is what is shown in legend by default when it's not hovered, hence it being empty.

2) Why is it shown when hovered is a result of a fuzzy logic employed by legend. Default text for legend is like this `"{name}"`.

It means that replace `{name}` with:

a) "name" key from data
b) if there's no such key, replace it with series name

Since your data actually has "name" items, they do get displayed when hovered.

Hope that makes sense.

So if you want something shown when nothing is hovered, you can set series `name`:

```
series.name = "Series #" + i;
```

If you'd like to change what is shown when hover happens, you can use `legendSettings` for series, e.g.:

```
series.legendSettings.itemLabelText = "{name}: {valueY}";
```

**Comment by vdurante** [comment]
@martynasma I used series.name ="whatever" and now it works! Thank you very much!

Sorry to bother with such useless questions, but I couldn't find the answer online. Do you also know if it is possible to use a Moment (moment.js) object on DateAxis? Thank you!

**Comment by martynasma** [comment]
No problem.

Not sure about Moment. Probably not :)

**Comment by vdurante** [comment]
@martynasma ty <3
