### ISSUE TITLE
axisRange error, when used in JSON config

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts4#1475]
Hi, I have following config:
```
yAxes      => [
    {   type            => 'ValueAxis',
        id              => 'axis-revenue',
        title           => { text => 'Revenue' },
        numberFormatter => { type => 'NumberFormatter', numberFormat => q['$' #,###.] },
        axisRanges      => [
            {   series   => 'series-revenue',
                endValue => 0,
                contents => { stroke => '#ff0000', },
            },
        ],
    },
]

series => [
    {   type            => 'LineSeries',
        id              => 'series-revenue',
        name            => 'Revenue',
        yAxis           => 'axis-revenue',
        dataFields      => { dateX => 'time', valueY => 'revenue', },
        tooltipText     => '{name}: $ {valueY.value}',
        numberFormatter => { numberFormat => '#,###.00', },
        tensionX        => 0.8,
        connect         => \0,
        strokeWidth     => 2,
    },
]
```

When chart is creating it throws an error ```TypeError: this.raiseCriticalError is not a function``` and don't rendering.
If I remove axisRange config - everything works.

**Comment by martynasma** [comment]
Fixed in [4.5.5](https://github.com/amcharts/amcharts4/releases/tag/4.5.9).

## [4.5.9] - 2019-07-24

### Added
- `above` property added to `AxisTick`, `Grid`, and `AxisFill`. Allows putting individual elements on top of the series even if all the other grids/ticks/axis fills are below them.
- `bullet` property added to `AxisDataItem`. Allows adding bullets to the axes. You can have both `AxisBullet` (new class) or a simple `Sprite` there.
- New element class `AxisBullet`. Use `AxisBullet` which is a container with a `location` property in case you want to adjust bullet location within cell.

### Fixed
- JSON: Series-bound axis ranges were breaking whole chart in JSON-based setups.
- In some rare cases `NumberFormatter` was suffering from floating point number precision issue when calculating big number prefixes.
- Updating data was causing Annotation menu item to duplicate.
- Exporting `extraSprites` with different positions didn't work.
- Responsive rules were not always kicking in on first load if there were multiple charts on the same page.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
