### ISSUE TITLE
Bad XYChartScrollbar rendering if min/max set on dateAxis 2nd

### ISSUE THREAD

**Issue by Christian-Adler** [amcharts/amcharts4#1487]
A reopen of #357

The problem exists still in actual version 4.5.8 if min/max is set later (after chart creation) to the dateAxis.

This pen is forked from the pen mentioned in #357 . Only change ist to set min/max not in config but later.
https://codepen.io/chrisadler/pen/PMNpxd

**Comment by martynasma** [comment]
Fixed in [4.5.13](https://github.com/amcharts/amcharts4/releases/tag/4.5.13).

## [4.5.13] - 2019-08-06

### Fixed
- Sometimes `requestAnimationFrame` was being invoked even if all charts were disposed.
- Base grid was not displayed if `axis.renderer.inside = true`.
- Last tooltip might not be shown on `DateAxis` if it had multiple series and some of the series did not have data at the last date.
- Legend values were showing value of the pervious hovered data item on the dates which did not have any data.
- Changing base value of `ValueAxis` was not making the series to be redrawn.
- Sometimes `ValueAxis` was not adjusting `min`/`max` when a part of the `DateAxis` with series having no data at the selected period was selected.
- Sometimes columns or step line series could overlap if `baseInterval.unit = "day"` and `baseInterval.count > 1`.
- `XYChartScrollbar` axes were not handling changes of `min`/`max` of chart axes.
- Panning of `CategoryAxis` could result incorrect zoom in some cases.
- FireFox issue with multiple `PictorialStackedSeries` on the same chart solved.
- Cursor selection was disappearing when mouse was released (with `selectX`/`selectY`/`selectXY` cursor behavior).
- Tooltip of clustered columns was positioned incorrectly (always showing in the middle of a cell).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
