### ISSUE TITLE
setting alwaysShowTooltip to true creates a tooltip on legend items, how to hide them? 

### ISSUE THREAD

**Issue by thinkingparticle** [amcharts/amcharts4#1494]
check this fiddle: 
I want to show and hide tooltips. it works on columns but it creates a tooltip on legend item which I didnt wanted and I can't even hide it after it has been shown.

http://jsfiddle.net/fxezu79o/1/

![image](https://user-images.githubusercontent.com/17741554/61875209-5eb00c00-aeff-11e9-8ec6-49227dbff545.png)

I appreciate if someone could give me a hint.

**Comment by thinkingparticle** [comment]
I do not know why. but setting `chart.legend.useDefaultMarker = true;` fixed it. 😄

**Comment by martynasma** [comment]
`useDefaultMarker` fixes it because causes Legend to create its own square elements as markers, that have no connection to the actual columns series.

Whereas default behavior is to led series itself create a marker that resembles its look. So I suppose some `tooltipText` and `alwaysShowTooltip` get propagated somehow.

However, I can't seem to be able to reproduce it in a simpler chart. We'll keep looking into it.

https://codepen.io/team/amcharts/pen/5623237902e1f8bcb9c770a1d9fb0d51?editors=0010

**Comment by zeroin** [comment]
An alternatve solution would be setting:
`input_series.legendDataItem.marker.children.getIndex(0).tooltip = undefined;`
in the `show_tooltip` method, although useDefaultMarker is also a good approach.
