### ISSUE TITLE
SlicedChart cant hold 2 PictorialStackedSeries

### ISSUE THREAD

**Issue by cengler** [amcharts/amcharts4#1496]
Im trying to extend this example with 2 PictorialStackedSeries.
https://www.amcharts.com/docs/v4/chart-types/sliced-chart/

When I add the second **PictorialStackedSeries**, the first hides.

I also try add 2 FunnelSeries and PyramidSeries, but they work correctly

Issue example
https://codepen.io/caeycae/pen/XvjgOY

**Comment by martynasma** [comment]
I'm seeing two of PictorialStackedSeries, PyramidSeries, and FunnelSeries in your CodePen example:

![image](https://user-images.githubusercontent.com/1458520/61926417-23522380-af79-11e9-8375-ad12b8e68913.png)

Am I missing something, or you were able to resolve it after posting this?

**Comment by cengler** [comment]
it seems that the error occurs only in firefox

<img width="1383" alt="imagen" src="https://user-images.githubusercontent.com/1243214/61926571-6eebd980-af47-11e9-9458-c51d271fa98e.png">

**Comment by martynasma** [comment]
Indeed. Thanks for the tip.

Will let you know when we're able to resolve this.

**Comment by amcharts-support** [comment]
> New comment from Zendesk by **Antanas Marcelionis** on ticket **48019**.
> (replying here will automatically notify amCharts support agent)

fixed

Yours sincerely,

Antanas Marcelionis
amCharts

P.S. have you seen amCharts 4 yet?
https://www.amcharts.com/

**Comment by martynasma** [comment]
Fixed in [4.5.13](https://github.com/amcharts/amcharts4/releases/tag/4.5.13).

## [4.5.13] - 2019-08-06

### Fixed
- Sometimes `requestAnimationFrame` was being invoked even if all charts were disposed.
- Base grid was not displayed if `axis.renderer.inside = true`.
- Last tooltip might not be shown on `DateAxis` if it had multiple series and some of the series did not have data at the last date.
- Legend values were showing value of the pervious hovered data item on the dates which did not have any data.
- Changing base value of `ValueAxis` was not making the series to be redrawn.
- Sometimes `ValueAxis` was not adjusting `min`/`max` when a part of the `DateAxis` with series having no data at the selected period was selected.
- Sometimes columns or step line series could overlap if `baseInterval.unit = "day"` and `baseInterval.count > 1`.
- `XYChartScrollbar` axes were not handling changes of `min`/`max` of chart axes.
- Panning of `CategoryAxis` could result incorrect zoom in some cases.
- FireFox issue with multiple `PictorialStackedSeries` on the same chart solved.
- Cursor selection was disappearing when mouse was released (with `selectX`/`selectY`/`selectXY` cursor behavior).
- Tooltip of clustered columns was positioned incorrectly (always showing in the middle of a cell).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
