### ISSUE TITLE
GaugeChart Ticks Missing

### ISSUE THREAD

**Issue by Infineon12** [amcharts/amcharts4#1498]
Hello,

within the small preview Images it is visible that ticks are included.
Also on closer look at the sourcecode ticks are configured.

![2019-07-26 13_08_39-Demos Archive - amCharts](https://user-images.githubusercontent.com/2978137/61947948-cd947000-afa6-11e9-8a98-724b27973fa2.png)

But if you look at the chart displayed there are no ticks available.

![2019-07-26 13_08_54-Angular Gauge With Two Axes - amCharts](https://user-images.githubusercontent.com/2978137/61947947-cd947000-afa6-11e9-9894-a8012bdc7749.png)

I do think this is a new issue because i remind myself that this worked before.

Greetings Marco

**Comment by martynasma** [comment]
I can't remember precise version when it happened, but at some point we started setting `disabled = true` on all ticks by default. This is for performance, so that items that are not needed would not generated.

To enabled them, simply set:

```
axis.renderer.ticks.template.disabled = false
```

Sorry for the inconvenience.

P.S. we'll update demos accordingly
