### ISSUE TITLE
Accessible theme

### ISSUE THREAD

**Issue by manavs19** [amcharts/amcharts4#1504]
Hi,

I am using amcharts4 default theme. The chart labels disappear in high contrast mode on IE11. 

This page suggests that amcharts comes with accessible themes for high contrast.
https://www.amcharts.com/javascript-charts/

However I did not find any docs on what those themes are exactly. It would be great if someone could tell me the names of those themes.

Regards,
Manav

**Comment by martynasma** [comment]
In this mode IE/Edge shows web pages with default black background. Since labels in amCharts are black by default, they are not visible.

We're not able to detect Windows HC mode, and therefore cannot change the color of labels adaptively.

One workaround that I can offer is to use CSS `@media` rule to override the color of all text on charts:

```
@media screen and (-ms-high-contrast: active) {
  #chartdiv text {
  	fill: #fff!important;
  }
}
```

You may need to adjust your CSS selectors if you don't use id `chartdiv` for your chart container.

Hope this helps.

**Comment by martynasma** [comment]
Above in the tutorial form:
https://www.amcharts.com/docs/v4/tutorials/windows-high-contrast-mode/
