### ISSUE TITLE
exporting force directed graph as JSON or CSV

### ISSUE THREAD

**Issue by hichd** [amcharts/amcharts4#1510]
Hello,

I added the export menu to a force directed graph but it doesn't seem to have the option to export the chart as a CSV or JSON file.

I followed the documentation and customized the export menu as follows :
```
chart.exporting.menu.items = [{
  "label": "...",
  "menu": [
    { "type": "png", "label": "PNG" },
    { "type": "json", "label": "JSON" },
    { "label": "Print", "type": "print" }
  ]
}];
```
however the json option did not appear. Then I used the export API
```
    function exportJSON() {
      chart.export.toJSON({}, function(data) {
        this.download(data, this.defaults.formats.JSON.mimeType, "amCharts.json");
      });
    }
```
and I got the error : Property 'export' does not exist on type 'ForceDirectedTree'.

So my question is, how can I get the option to export my directed graph as a CSV or JSON file?

**Comment by martynasma** [comment]
Export to JSON works fine on ForceDirected chart:

https://codepen.io/team/amcharts/pen/bb574b863479c13a3583dcfdb3e4828e?editors=0010

Exporting to CSV does not make sense in hierarchical scenarios, though. Especially in those that top nodes' value is auto-calculated from child nodes. But still, it appears in export menu and works.

If you have a demo which does not work, can you post it online so that we can take a look?
