### ISSUE TITLE
requestAnimationFrame events are sent in infinite loop after dispose()

### ISSUE THREAD

**Issue by adamturski** [amcharts/amcharts4#1524]
I've found that requestAnimationFrame events are sent after disposing all charts in my Angular app which uses Amcharts in version 4.5.11. With such infinite events my application performance is worse. Similar issue was reported here https://github.com/amcharts/amcharts4/issues/106

The reason for that issue is that "ghostPaper" element added to body is hidden and it is processed by ResizeSensor.js in attachResizeEvent method in some infinite loop, even after disposing all charts - ghostPaper is not removed.

```
var invisible = element.offsetWidth === 0 && element.offsetHeight === 0;
                    if (invisible) {
                        // Check in next frame
                        if (!lastAnimationFrame){
                            lastAnimationFrame = requestAnimationFrame(function(){
                                lastAnimationFrame = 0;

                                reset();
                            });
                        }

                        return;
```

```
export function getGhostPaper() {
    if (ghostPaper === null) {
        // ghost is used to draw elements while real paper is not yet created or Sprite doesn't know parent yet
        var ghostDiv = document.createElement("div");
        ghostDiv.hidden = true;
        document.body.appendChild(ghostDiv);
        var ghostSvgContainer = new SVGContainer(ghostDiv);
        ghostPaper = new Paper(ghostSvgContainer.SVGContainer, "ghost");
    }
    return ghostPaper;
}
```

As a workaround in my view with chart I've added below code to ngOnDestroy lifecycle method which stopped this infinite loop as I made ghostPaper 1px height and removed hidden attribute. I couldn't find better solution for that.
```
const amchartsPapers = document.getElementsByClassName("resize-sensor");
    for(let i = 0; i < amchartsPapers.length; i++)
    {
      const paperParent = amchartsPapers.item(i).parentElement;
      if(document.body === paperParent.parentElement) {
        paperParent.hidden = false;
        paperParent.style.height= '1px';
      }
    }
```

**Comment by martynasma** [comment]
Fixed in [4.5.13](https://github.com/amcharts/amcharts4/releases/tag/4.5.13).

## [4.5.13] - 2019-08-06

### Fixed
- Sometimes `requestAnimationFrame` was being invoked even if all charts were disposed.
- Base grid was not displayed if `axis.renderer.inside = true`.
- Last tooltip might not be shown on `DateAxis` if it had multiple series and some of the series did not have data at the last date.
- Legend values were showing value of the pervious hovered data item on the dates which did not have any data.
- Changing base value of `ValueAxis` was not making the series to be redrawn.
- Sometimes `ValueAxis` was not adjusting `min`/`max` when a part of the `DateAxis` with series having no data at the selected period was selected.
- Sometimes columns or step line series could overlap if `baseInterval.unit = "day"` and `baseInterval.count > 1`.
- `XYChartScrollbar` axes were not handling changes of `min`/`max` of chart axes.
- Panning of `CategoryAxis` could result incorrect zoom in some cases.
- FireFox issue with multiple `PictorialStackedSeries` on the same chart solved.
- Cursor selection was disappearing when mouse was released (with `selectX`/`selectY`/`selectXY` cursor behavior).
- Tooltip of clustered columns was positioned incorrectly (always showing in the middle of a cell).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
