### ISSUE TITLE
Tooltips jump around erratically during pinch zoom

### ISSUE THREAD

**Issue by mjohnstone357** [amcharts/amcharts4#1525]
Hello,

We're trying to use amCharts to display a line chart (specifically, am4charts.XYChart) in a web application that needs to work nicely on mobile devices.

We're finding that when we do pinch zoom on mobile browsers, such as Safari on an iPad, the chart's tooltips jump around erratically. It seems to be jumping between the positions of the two fingers that are in contact with the screen.

This behaviour can be seen on the demo at https://www.amcharts.com/demos/reversed-value-axis/, though we are using a non-inverted line chart for our application.

I've made a video of the behaviour, which you can view here: https://drive.google.com/file/d/1HRjTcmOC1R8EeLEMsh1L19_gqVRIe55m/view?usp=sharing

Is this something that we can address through configuration, or is it a bug?

**Comment by martynasma** [comment]
We're working on a fix. Stay tuned.

**Comment by martynasma** [comment]
Fixed in [4.5.15](https://github.com/amcharts/amcharts4/releases/tag/4.5.15).

## [4.5.15] - 2019-08-23

### Added
- `hideSeriesTooltipsOnSelection` added to `XYCursor`. If set to `true` it will automatically hide cursor-initiated series tooltips when selecting with cursor (e.g. for a zoom).
- Properties `numberFields`, `numberFormatter`, and `numberFormat` properties to `Export`. Allows forcing certain number format for values listed in `numberFields` effectively converting them into strings.
- `snapToSeries` now supports `XYChart` setups where both X and Y axes are `ValueAxis`.

### Changed
- `ZoomControl`'s plus and minus button will not be exported to images anymore.

### Fixed
- When the chart with external data source and reload frequency set was disposed, the data source kept reloading the data.
- When Tooltip's `keepTargetHover` was enabled and hover moved from an element with tooltip content to an element without one, an empty tooltip was being shown.
- `SankeySiagram` with a lot of nodes was performing poorly on initial load.
- `TreeMap` could show bullets of multiple levels which could result overapping of bullets/labels.
- `MapLineSeries` with `imagesToConnect` were not updating if images changed their positions.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Quick tip. Set `hideSeriesTooltipsOnSelection = true` on your cursor.

**Comment by Rich43** [comment]
We have done some testing on this and we can still hide the tooltip when zooming in and out. It is definitely improved though, could you have another look at this and test on an iPhone using Safari?

The flickering that was there before is better too.
