### ISSUE TITLE
4.5.11-4.5.12 regression on multiple axes different numberFormatter

### ISSUE THREAD

**Issue by nurettin** [amcharts/amcharts4#1526]
AMCharts version 4.5.11 allows us to specify different number formatters for different y axes, 4.5.12 doesn't. See fiddles:
4.5.11: http://jsfiddle.net/6nqmzwjh/
4.5.12: http://jsfiddle.net/6nqmzwjh/1/

(I only changed amcharts cdn version url)

#993

**Comment by martynasma** [comment]
This is not a bug/regression but rather correction of behavior to a more intuitive behavior.

In JSON config, in 4.5.11 and down if there was an object specification with `type` set in it, the config was forcefully creating a new instance of the object.

So when you had this:

```
  "numberFormatter": {
        "id": "format1",
        "type": "NumberFormatter",
        "numberFormat": "x#.##"
   }
```

In some axis definition it meant that it was creating a separate instance of `NumberFormatter` for that axis, as well as setting the `numberFormat` for that specific formatter.

4.5.12 changed that. If now checks if existing object (and `numberFormatter` exists everywhere because it's inheritable all the way up to the chart) is of the same `type` and new object is being created only if the object types differ.

If they don't, properties of the current object are being overwritten.

In your setups it ends up overwriting `numberFormat` a number of times, with the last one taking effect, hence the issue you are seeing.

To work around that simply use `forceCreate`:

```
      "numberFormatter": {
        "id": "format1",
        "type": "NumberFormatter",
        "forceCreate": true,
        "numberFormat": "x#.##"
      }
```

P.S. yes, I now notice we haven;t updated our JSON docs to reflect this change. Our bad. We're going to make those changes soon. Sorry for the inconvenience.

**Comment by nurettin** [comment]
I confirm this works, thanks! looking forward to doc update.

**Comment by martynasma** [comment]
Heads up, docs updated.

Thanks again!

> p.s. instead of looking for numberFormatter - or any other instance - /everywhere/, may I suggest you only look for it up the hierarchy? That way, your inheritance model will be more intuitive.

That's already how it is. If object itself does not have own `NumberFormatter` it requests one from its immediate parent, and so on. Since axes are children of chart, that means they inherit formatter from chart object.
