### ISSUE TITLE
Why is ngZone needed for Angular?

### ISSUE THREAD

**Issue by andii1997** [amcharts/amcharts4#1531]
In the angular code in your [docs](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) you create the chart in an `ngZone.runOutsideAngular`-block. Why is this needed? What is not working, if it isn't run outside angular?

**Comment by l1b3r** [comment]
The code that runs outside Angular zone would not trigger an automatic change detection from Angular. If you e.g. set timeouts or subscribe to DOM events (mouseover, clicks etc.) within the `runOutsideAngular` callback, Angular would not run the change detection upon the timeout completion or the occurrence of the dom event. This is often used to improve the performance of the application, especially with charting libraries when you are sure the library will handle the mouseover and over events by itself. Change detection provided by Angular would sometimes introduce a very noticeable yet unnececcary overhead.

Running everything within Angular zone should still work though.

**Comment by Pauan** [comment]
@l1b3r is correct: because amCharts uses many event listeners (and things like `requestAnimationFrame`), that causes a lot of performance problems in Angular.

If you do not use `runOutsideAngular` then Angular will update hundreds of times every second, even though nothing has changed.

So by using `runOutsideAngular`, it fixes that performance problem.

(Note: the performance problem is caused by the Angular / Zones system, not amCharts. Other frameworks like React do not have this performance problem)
