### ISSUE TITLE
Step line series with large autoGapCount shows incorrectly

### ISSUE THREAD

**Issue by rcslaney** [amcharts/amcharts4#1532]
I have a chart with two y axes, on the top I want to display data with a granularity of a second, so I have set base interval to 1 second so that the points show in the right places and aren't grouped to the closest minute, hour etc.

On the bottom axis however I have data that has granularity of an hour, which I can display fine with a column chart by setting column width to 36000 percent, but this did not perform very well for a large amount of data. So as on the Wiki I changed it to a StepLineSeries and because my chart has a base interval of 1 second I set the autoGapCount so the series would display.

![image](https://user-images.githubusercontent.com/784148/62611456-85a60f00-b8fd-11e9-919d-8a77bb3e0f04.png)
Before setting series.connect = false and series.autoGapCount = 3600 chart is fine, but gaps in my data (which would be too intensive to fill) are misrepresented when they should be 0.

![image](https://user-images.githubusercontent.com/784148/62611285-319b2a80-b8fd-11e9-8c8f-8e5f4b303202.png)
After settings as you can see this no longer looks like a stepped line chart.

Is there a solution to this? I understand I am maybe using the chart in an unusual way, so if there is anyway to set the baseInterval per series or something like that that would be great.

**Comment by rcslaney** [comment]
I have replicated the problem here if that is helpful https://codepen.io/rcslaney/pen/aeYeKR

**Comment by martynasma** [comment]
Thanks for the codepen. It helps.

We're looking into it why StepLineSeries reverts to regular LineSeries like this.

**Comment by martynasma** [comment]
Fixed in [4.5.14](https://github.com/amcharts/amcharts4/releases/tag/4.5.14).

## [4.5.14] - 2019-08-11

### Added
- `mouseOptions` added to `Interactions`. For now it contains only wheel sensitivity setting, e.g. `mapChart.interactions.mouseOptions.sensitivity = 0.4`.
- `getPositionX()` and `getPositionY()` methods added to all axes. Returns relative position of a series data item on axis.

### Changed
- Series with `DateAxis` not as a base axis of a series (like gantt) will now animate similar to other charts.
- `SlicedChart` hidden labels arrangements adjusted.

### Fixed
- `ValueAxis` was incorrectly choosing min/max values for the data with very small values.
- `StepLineSeries` with `connect = false` and `autoGapCount > 1` was showing regular line series, not a step series.
- Chart with `DateAxis` which was not a base axis of a series and dates older than Unix Epoch (January 1st, 1970 at UTC) was incorrectly showing base of a series.
- `DateAxis` was not animating smoothly when adding more data.
- `ValueAxis` pre-zoom (on `ready` event) was not working properly.
- `fullWidth` cursor line was not reverting back if set to `true` and then back to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
