### ISSUE TITLE
Pre-zoom is zooming out immediately

### ISSUE THREAD

**Issue by anastasia-adv** [amcharts/amcharts4#1535]
Hello, 
I'm trying to pre-zoom a Waterfall Chart using zoomToValues(). However, at first, the chart is zoomed and it immediately zooms out . 
As the documentation suggested I also added showOnInit = false for the series. I still get the same result. 
I tried it on different browsers and it still zooms out. Even on the tutorial page (https://www.amcharts.com/docs/v4/tutorials/pre-zooming-an-axis/) in the section dealing with category and value axis I see the chart immediately zooming out. 

Is there a way to still use zoomToValues to make it work ? 

Thank you for your time.

**Comment by martynasma** [comment]
Indeed. Something has changed recently that broke pre-zooming.

We'll get to the bottom of it and will keep you posted.

Thanks for the heads up!

**Comment by zeroin** [comment]
While we are solving this with events, you can use a different approach which should work fine and doesn't include events. Simply set relative start/end values for the axes and set keepSelection to true, for example:

`yAxis.start = 0.5;
yAxis.end = 1;
yAxis.keepSelection = true;`

**Comment by martynasma** [comment]
Fixed in [4.5.14](https://github.com/amcharts/amcharts4/releases/tag/4.5.14).

## [4.5.14] - 2019-08-11

### Added
- `mouseOptions` added to `Interactions`. For now it contains only wheel sensitivity setting, e.g. `mapChart.interactions.mouseOptions.sensitivity = 0.4`.
- `getPositionX()` and `getPositionY()` methods added to all axes. Returns relative position of a series data item on axis.

### Changed
- Series with `DateAxis` not as a base axis of a series (like gantt) will now animate similar to other charts.
- `SlicedChart` hidden labels arrangements adjusted.

### Fixed
- `ValueAxis` was incorrectly choosing min/max values for the data with very small values.
- `StepLineSeries` with `connect = false` and `autoGapCount > 1` was showing regular line series, not a step series.
- Chart with `DateAxis` which was not a base axis of a series and dates older than Unix Epoch (January 1st, 1970 at UTC) was incorrectly showing base of a series.
- `DateAxis` was not animating smoothly when adding more data.
- `ValueAxis` pre-zoom (on `ready` event) was not working properly.
- `fullWidth` cursor line was not reverting back if set to `true` and then back to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
