### ISSUE TITLE
selectended does not trigger when the selected area is very small

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1546]
Use a linechart 

Perform a selection like on the example https://www.amcharts.com/docs/v4/concepts/chart-cursor/ 

<img width="733" alt="Screenshot 2019-08-08 at 16 41 27" src="https://user-images.githubusercontent.com/1268723/62712589-6ab9c480-b9fb-11e9-939d-644ffaddea7f.png">

For example on the above the alert did not trigger

**Comment by martynasma** [comment]
Thanks!

Direct link to demo in question:
https://codepen.io/team/amcharts/pen/gKYmEL

**Comment by zeroin** [comment]
This is actually not a bug. There is a setting, hitTolerance which can be configured:

`chart.cursor.interactions.hitOptions.hitTolerance = 0;`

Now, the event will always be fired. This is added in order to avoid events to be fired when user simply clicks/touches the plot area.

You can listen to `behaviorcanceled` event of ChartCursor to find when user selects a very small section and use this event to hide selection.

**Comment by jimmykane** [comment]
@zeroin  yeah you are most right. Make sense 100% and works great as a feature. Was about to close that one btw good timing. Closing now and thanks!
