### ISSUE TITLE
The Title alignment not right for treemap

### ISSUE THREAD

**Issue by renjiie** [amcharts/amcharts4#1548]
![treemap](https://user-images.githubusercontent.com/37571081/62755084-32b09100-ba90-11e9-8e78-ebeac36430ed.PNG)
In the treemap . after going into 2 levels or more the text merges or the alignment is not good . Ho w can I only input the text of the current level

**Comment by zeroin** [comment]
Could you create a codepen with your chart? It would be easier to help.

**Comment by renjiie** [comment]
In the demo it is upto 1 level drill . How can I add multiple levels .

**Comment by renjiie** [comment]
`chart.data = [{
		  "name": "Frequent",
		  "children": [
		    { "name": "A1", "value": 100 },
		    { "name": "A2", "value": 60 },
		    { "name": "A3", "value": 30 }
		  ]
		}, {
		  "name": "Weekend",
		  "children": [
		    { "name": "B1", "value": 135 },
		    { "name": "B2", "value": 98 },
		    { "name": "B3", "value": 56 }
		  ]
		}, {
		  "name": "Bargain",
		  "children": [
		    { "name": "C1", "value": 335 },
		    { "name": "C2", "value": 148 },
		    { "name": "C3", "value": 126 },
		    { "name": "C4", "value": 26 }
		  ]
		}, {
		  "name": "Ordinary",
		  "children": [
		    { "name": "D1", "value": 415 },
		    { "name": "D2", "value": 148 },
		    { "name": "D3", "value": 89 },
		    { "name": "D4", "value": 64 },
		    { "name": "D5", "value": 16 }
		  ]
		}, 
		{
		  "name": "Holiday",
		  "children": [
		    { 
		    	"name": "Holiday1", "value":1000,
		    	"children":[
		    		{
		    			"name": "Holiday1a", "value":1000,
		    			"children":[
		    				{
		    					"name": "Holiday1b", "value":1000,
		    					"children":[
				    				{
				    					"name": "Holiday1c", "value":1000,
				    					"children":[
						    				{
						    					"name": "Holiday1d", "value":1000,
						    				}
						    			]
				    				}
				    			]
		    				}
		    			]
		    		}
		    	]
		    }
		  ]
		}];
		/* Set color step */
		chart.colors.step = 0;
		chart.colors.list = [am4core.color("#e17e39")];
		chart.dataFields.value = "value";
		chart.dataFields.name = "name";
		chart.dataFields.children = "children";
		chart.homeText = "Home";
		/* Create top-level series */
		var level1 = chart.seriesTemplates.create("0");
		level1.columns.template.fillOpacity = 0;

		/* Create second-level series */
		var level2 = chart.seriesTemplates.create("1");
	
		var level2_bullet = level2.bullets.push(new am4charts.LabelBullet());
		level2_bullet.locationY = 0.5;
		level2_bullet.locationX = 0.5;
		level2_bullet.label.text = "{name}";
		level2_bullet.label.fill = am4core.color("#fff");
		level1.columns.template.fillOpacity = 0;
		level2.columns.template.fillOpacity = 0;
		var level3 = chart.seriesTemplates.create("2");
		var level3_bullet = level3.bullets.push(new am4charts.LabelBullet());
		level3_bullet.locationY = 0.5;
		level3_bullet.locationX = 0.5;
		level3_bullet.label.text = "{name}";
		level3_bullet.label.fill = am4core.color("#fff");
		level1.columns.template.fillOpacity = 0;
		level2.columns.template.fillOpacity = 0;
		level3.columns.template.fillOpacity = 0;
		var level4 = chart.seriesTemplates.create("3");
		var level4_bullet = level4.bullets.push(new am4charts.LabelBullet());
		level4_bullet.locationY = 0.5;
		level4_bullet.locationX = 0.5;
		level4_bullet.label.text = "{name}";
		level4_bullet.label.fill = am4core.color("#fff");
		level4.columns.template.fillOpacity = 0;
		var level5 = chart.seriesTemplates.create("4");
		var level5_bullet = level5.bullets.push(new am4charts.LabelBullet());
		level5_bullet.locationY = 0.5;
		level5_bullet.locationX = 0.5;
		level5_bullet.label.text = "{name}";
		level5_bullet.label.fill = am4core.color("#fff");
		level5.columns.template.fillOpacity = 0;

		/* Add a navigation bar */
		chart.navigationBar = new am4charts.NavigationBar();
		chart.navigationBar.links.template.fill = am4core.color("#fff");
		chart.navigationBar.activeLink.fill = am4core.color("#fff");
	}`

**Comment by martynasma** [comment]
I'm afraid TreeMap does not currently support auto-hiding bullets from previous step in the drill-down scenario.

We'll need to consider a solution.

Meanwhile I don't have a workaround :(

**Comment by renjiie** [comment]
> I'm afraid TreeMap does not currently support auto-hiding bullets from previous step in the drill-down scenario.
> 
> We'll need to consider a solution.
> 
> Meanwhile I don't have a workaround :(

any alternative way of showing the titles

**Comment by martynasma** [comment]
Not, I'm afraid. We're figuring out a solution, though.

Will keep you posted.

**Comment by renjiie** [comment]
How can we log the values in console on click of a value in treemap ? 
chart.data = [{
  name: "First",
  children: [
    {
      name: "A1",
      value: 100
    },
    {
      name: "A2",
      value: 60
    },
    {
      name: "A3",
      value: 30
    }
  ]
}]
onclick of "A1" . How can i log A1 and its values in the console .

**Comment by martynasma** [comment]
Fixed in [4.5.15](https://github.com/amcharts/amcharts4/releases/tag/4.5.15).

## [4.5.15] - 2019-08-23

### Added
- `hideSeriesTooltipsOnSelection` added to `XYCursor`. If set to `true` it will automatically hide cursor-initiated series tooltips when selecting with cursor (e.g. for a zoom).
- Properties `numberFields`, `numberFormatter`, and `numberFormat` properties to `Export`. Allows forcing certain number format for values listed in `numberFields` effectively converting them into strings.
- `snapToSeries` now supports `XYChart` setups where both X and Y axes are `ValueAxis`.

### Changed
- `ZoomControl`'s plus and minus button will not be exported to images anymore.

### Fixed
- When the chart with external data source and reload frequency set was disposed, the data source kept reloading the data.
- When Tooltip's `keepTargetHover` was enabled and hover moved from an element with tooltip content to an element without one, an empty tooltip was being shown.
- `SankeySiagram` with a lot of nodes was performing poorly on initial load.
- `TreeMap` could show bullets of multiple levels which could result overapping of bullets/labels.
- `MapLineSeries` with `imagesToConnect` were not updating if images changed their positions.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
