### ISSUE TITLE
minBulletDistance for ValueAxis

### ISSUE THREAD

**Issue by ElAngularo** [amcharts/amcharts4#1555]
Hello, 

I have problem with series.minBulletDistance for ValueAxis.
in my case: https://codepen.io/elangularo/pen/zgmQWd
Bullets are:
- visible all the time,
- not visible when I have ~500 data points on X axis (zoom doesn't change anything).

Every example of minBulletDistance using DateAxis or CategoryAxis. Is there any possibility to use it with ValueAxis?

**Comment by martynasma** [comment]
Looks like a bug. We're going to need to look into it.

Will keep you posted.

Thank you for reporting it!

**Comment by martynasma** [comment]
Turns out we can't have this implemented.

This setting will work only when Series' base axis is `CategoryAxis` or `DateAxis`. If base axis is `ValueAxis` the setting will be ignored, because it would be a huge overhead to measure distance between each and every bullet.

We'll update documentation accordingly soon.
