### ISSUE TITLE
Limit the "min zoom" (opposite to minZoomCount)

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts4#1563]
Is there any property to set the min zoom for CategoryAxis? will be the opposite to minZoomCount.   
I have a long X Axis and I don't want to allow to view it all, the zoom should be "2" as min (half of the axis as max).

**Comment by martynasma** [comment]
Maybe I'm reading wrong your description, but I don't quite understand :)

Do you need to set a limit on how many categories there are displayed at any given time? E.g. `maxZoomCount`?

**Comment by enriquepiatti** [comment]
Exactly, minZoomCount seems to affect the maxZoom we can get, I'm looking for the opposite, the min zoom we can get (so the max count in categories to show).     
Suppose I have 100 categories in my axis, I want to show max 50: this will show the scrollbar at 50% size as max length (end-start = 0.5 as max)

**Comment by martynasma** [comment]
Gotcha. We'll consider this. But can't promise anything, yet.

**Comment by martynasma** [comment]
Fixed in [4.6.2](https://github.com/amcharts/amcharts4/releases/tag/4.6.2).

## [4.6.2] - 2019-09-25

### Added
- New plugin: [OverlapBuster](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/). Allows automatically "exploding" overlapping items such as bullets or markers for easier access to them.
- New property: `maxZoomCount` on `Component`. Use it to limit how many items such as categories or base intervals on axes can be shown at the same time.
- Added `riseFromOpenState`, `riseFromPreviousState`, `dropFromOpenState`, and `dropFromPreviousState` setters to `ColumnSeries`. You can use them to set states to `undefined` if you don't want them to be used.
- A possibility to make "fixed" `ForceDirectedTree` nodes added (via `dataFields.fixed`). Also it is possible to set `x` and `y` of such nodes using `series.nodes.template.propertyField.x` and `y`. [More info](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes).

### Changed
- Removed "GIF" option from the Export menu. Browsers don't know how to convert canvas to GIF, so it was falling back to exporting as PNG, making GIF option redundant.

### Fixed
- If chart's data source was initialized (which would happen by only accessing chart's `dataSource` property) and its `url` was not set, it was still trying to load and resulting in error.
- Formatting number with "b" modifier, was causing all numbers up to 1024 become zero.
- `ColorSet` with default (no) theme was generating colors from second in the list from `4.6.1`.
- Bullet positions were incorrect on `ValueAxis` with `baseValue` set to other than zero.
- Bullet positions with `DateAxis` could be incorrect in some cases.
- Title position of a cloned Axis was nor being positioned properly.
- Cursor was flickering if axis of a cursor had some padding set.
- Tooltip position of `MapImage` elements with `nonScaling = true` could be incorrect in some specific cases.
- Vertical axis break's fill might get out of sync with break lines if the width of a break was small.
- `RadarCursor` could show incorrect label if the chart had `CategoryAxis` with only 3 categories.
- Series was not redrawing properly if its axis range value changed.
- `PieChart` could show some labels out of chart area in some specific cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
