### ISSUE TITLE
Tooltip with fixed position and KeepTargetHover causes empty tooltips

### ISSUE THREAD

**Issue by carmoreira** [amcharts/amcharts4#1564]
In the following example:
https://codepen.io/carmoreira/pen/GRKoyja

When we hover Russia and then move the cursor to the countries on the south, empty tooltips will display. This behavior disappears if I disable KeepTargetHover but causes the tooltip to flicker and makes it harder to click. 

Is this a bug? Or is there a different way to make sure that entries without custom data do not show a tooltip?

**Comment by martynasma** [comment]
Most definitely a bug. Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.5.15](https://github.com/amcharts/amcharts4/releases/tag/4.5.15).

## [4.5.15] - 2019-08-23

### Added
- `hideSeriesTooltipsOnSelection` added to `XYCursor`. If set to `true` it will automatically hide cursor-initiated series tooltips when selecting with cursor (e.g. for a zoom).
- Properties `numberFields`, `numberFormatter`, and `numberFormat` properties to `Export`. Allows forcing certain number format for values listed in `numberFields` effectively converting them into strings.
- `snapToSeries` now supports `XYChart` setups where both X and Y axes are `ValueAxis`.

### Changed
- `ZoomControl`'s plus and minus button will not be exported to images anymore.

### Fixed
- When the chart with external data source and reload frequency set was disposed, the data source kept reloading the data.
- When Tooltip's `keepTargetHover` was enabled and hover moved from an element with tooltip content to an element without one, an empty tooltip was being shown.
- `SankeySiagram` with a lot of nodes was performing poorly on initial load.
- `TreeMap` could show bullets of multiple levels which could result overapping of bullets/labels.
- `MapLineSeries` with `imagesToConnect` were not updating if images changed their positions.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
