### ISSUE TITLE
Chart cursor with disabled axis tooltip also disables cursor line

### ISSUE THREAD

**Issue by madnivek** [amcharts/amcharts4#1566]
Hello,

I noticed a potential issue today with the latest 4.5.14 patch update. When using a chart cursor, you may disable axis tooltips using something like `dateAxis.cursorTooltipEnabled = false`, and this would disable the tooltip, but the cursor line would still be visible. However, if cursor snapping is enabled using `chart.cursor.xAxis = dateAxis`, the line no longer appears. Is this a bug or a change in how the cursor works? Before the last update, you were able to have snapping cursor lines without their corresponding tooltips. This is causing problems for custom tooltip behavior that we have implemented on top of the cursor line.

Here is an example CodePen forked from one of your documentation examples: https://codepen.io/madnivek/pen/bGbEKxv

See lines 42-45. Notice that the vertical cursor line seems to be "stuck" on the left side of the chart.

Thanks for your help!

Best,

-Kevin

**Comment by martynasma** [comment]
Seems like a bug. We'll need to fix it.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.5.15](https://github.com/amcharts/amcharts4/releases/tag/4.5.15).

## [4.5.15] - 2019-08-23

### Added
- `hideSeriesTooltipsOnSelection` added to `XYCursor`. If set to `true` it will automatically hide cursor-initiated series tooltips when selecting with cursor (e.g. for a zoom).
- Properties `numberFields`, `numberFormatter`, and `numberFormat` properties to `Export`. Allows forcing certain number format for values listed in `numberFields` effectively converting them into strings.
- `snapToSeries` now supports `XYChart` setups where both X and Y axes are `ValueAxis`.

### Changed
- `ZoomControl`'s plus and minus button will not be exported to images anymore.

### Fixed
- When the chart with external data source and reload frequency set was disposed, the data source kept reloading the data.
- When Tooltip's `keepTargetHover` was enabled and hover moved from an element with tooltip content to an element without one, an empty tooltip was being shown.
- `SankeySiagram` with a lot of nodes was performing poorly on initial load.
- `TreeMap` could show bullets of multiple levels which could result overapping of bullets/labels.
- `MapLineSeries` with `imagesToConnect` were not updating if images changed their positions.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
