### ISSUE TITLE
Sankey Performance

### ISSUE THREAD

**Issue by ct5845** [amcharts/amcharts4#1570]
The Sankey seems to struggle, to the point of crashing the browser when the number of nodes gets large;

https://codepen.io/ct5845/pen/XWrdeVo

This pen is just before it's limit, anymore nodes than this and it hangs my browser and is unrecoverable. 

Using Chrome peformance tools, it seems a long time is spent in "SankeyDiagram.prototype.getNodeLevel = function (node, level) {" in SankeDiagram.js

**Comment by martynasma** [comment]
Fixed in [4.5.15](https://github.com/amcharts/amcharts4/releases/tag/4.5.15).

## [4.5.15] - 2019-08-23

### Added
- `hideSeriesTooltipsOnSelection` added to `XYCursor`. If set to `true` it will automatically hide cursor-initiated series tooltips when selecting with cursor (e.g. for a zoom).
- Properties `numberFields`, `numberFormatter`, and `numberFormat` properties to `Export`. Allows forcing certain number format for values listed in `numberFields` effectively converting them into strings.
- `snapToSeries` now supports `XYChart` setups where both X and Y axes are `ValueAxis`.

### Changed
- `ZoomControl`'s plus and minus button will not be exported to images anymore.

### Fixed
- When the chart with external data source and reload frequency set was disposed, the data source kept reloading the data.
- When Tooltip's `keepTargetHover` was enabled and hover moved from an element with tooltip content to an element without one, an empty tooltip was being shown.
- `SankeySiagram` with a lot of nodes was performing poorly on initial load.
- `TreeMap` could show bullets of multiple levels which could result overapping of bullets/labels.
- `MapLineSeries` with `imagesToConnect` were not updating if images changed their positions.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
