### ISSUE TITLE
Hide/show labels as items are disabled in legend?

### ISSUE THREAD

**Issue by ClaytonAstrom** [amcharts/amcharts4#1575]
I'm trying to hide labels when they're too small, but if the data is toggled in the legend, then the item labels also should change?

Here's my example:
https://codepen.io/claytonastrom/pen/PoYGpJy

If `Fourth` is disabled, so too should its label be?  And also, if enough items are disabled so that `Fifth` is now >= 5%, it should then have a visible label?

I'm assuming the adapter function for the label needs to be invoked at some point, I tried:

```ts
chart.events.on("transitionended", () => {
      level0_bullet.label.hardInvalidate();
    });
```
to no real success.  If there's any guidance anyone can offer it's more than possible I'm just not understanding these docs correctly

**Comment by martynasma** [comment]
I agree that labels/bullets for the hidden node should be hidden as well. If it's not happening it must be a bug. We'll need to investigate.

As for labels for small nodes, they are actually hidden on a basis of whether they fit into actual node, not whether node has certain amount of percent. However, in this case, even if all of the other nodes are hidden, the label/bullet does not appear. So it must be another bug.

Thanks for the heads up. Will keep you posted about the progress.

**Comment by ClaytonAstrom** [comment]
Ahh I thought I had to put a condition in on whether or not to show the label.  If it should be hiding be default based on fit, I don't think that's happening either

Here's what it looks like without the hideSmall function:
https://codepen.io/claytonastrom/pen/MWgjdJp

**Comment by martynasma** [comment]
OK, I took another look. It seems like it might not be a bug after all.

When something is hidden, it's "hidden" state is applied. And yours explicitly says that the bullet should be visible, hence it remaining visible after node is toggled off by legend.

To disable that, get rid of the code:

```
level0.bulletsContainer.hiddenState.properties.opacity = 1;
level0.bulletsContainer.hiddenState.properties.visible = true;
```

Now, what's going on for the "Fifth" label is that bullets that are initially "hidden" (which is the case because of your adapter) are not rendered at all, hence it not re-appearing when it should.

Probably a better solution is to get rid of that adapter, and just enable auto-hiding of items that do not fit:

```
level0_bullet.label.hideOversized = true;
```

**Comment by ClaytonAstrom** [comment]
Ahhh fantastic!  I figured I was reading something wrong, thanks!
