### ISSUE TITLE
Chart was not disposed - Angular & Material

### ISSUE THREAD

**Issue by ilueckel** [amcharts/amcharts4#1587]
Hi,
in version 4.5.12 you introduced the warning 
`Now prints a warning if you do not dispose of the chart properly.`
Since then we get the warnings on charts inside of Angular Material Material Tabs. 
Here is a stackblitz: https://stackblitz.com/edit/angular-7v9wzx

Am I missing something here? I do not intend to recreate or dispose the chart at all.

Edit: Before 4.5.12 we get an error instead of the warning. The last "working" version known to us was 4.4.10

**Comment by Pauan** [comment]
@ilueckel Thanks for providing a demo! There's five issues with your code:

1. Since you're using `ViewChild`, you don't need to use an `id`.

2. You need to use `ngAfterViewInit` instead of `ngOnInit`.

3. You need to implement `ngOnDestroy`. Even if you don't intend to recreate the chart, a parent component might recreate it. For example, if you add in routing then the router will load/unload components automatically.

4. You need to run the amCharts code inside of `this.zone.runOutsideAngular`, like [our tutorial shows](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/). This is needed because if you don't then you will have major performance issues with Angular.

5. The `mat-tab-group` component loads all of the tabs at once, including the tabs which aren't visible. This is why you're getting the "not disposed" warning, because the chart is created but not actually attached to the DOM.

   To fix this, you should [lazy load the tabs](https://material.angular.io/components/tabs/overview#lazy-loading), which is recommended for tabs which manipulate the DOM (which is what amCharts does).

Here is the fixed demo: https://stackblitz.com/edit/angular-d4zhjw

**Comment by MilindOO7** [comment]
I have the similar issue but I'm not getting the exact solution for it. Here is my code in stackoverflow
https://stackoverflow.com/questions/59043840/chart-was-not-disposed-in-amchart-in-live-data-when-using-socket

Kindly guide.
Thanks
