### ISSUE TITLE
Consider making DataItem.dataContest generic

### ISSUE THREAD

**Issue by CaselIT** [amcharts/amcharts4#1589]
The current type definition of `DataItem.dataContext` is `Object`
https://github.com/amcharts/amcharts4/blob/7e80e871d51617870752b8f8eb54906932bbe14c/src/.internal/core/DataItem.ts#L1150-L1152

It would be nice to make it generic in the DataItem and all the classes that derive from it, so that an user can specify its type.
Typescript supports the default type for a generic, so the change would be backward compatible.

Something like:
```ts
class DataItem<DataContextType = Object> {
  //...
  public get dataContext(): DataContextType { 
 	return this._dataContext; 
 } 
 //...
}
// and on every child class
class SeriesDataItem<DataContextType = Object>  extends DataItem<DataContextType> {
  // ...
}
```

This would avoid the error on sample callback like:
```ts
interface MyInterface {
  value: number;
}
onClick(cell: DataItem<MyInterface>){
  cell.dataContext.value  // this does not error
}
```

Thanks

**Comment by Pauan** [comment]
This is a good idea, but it's a huge amount of work, because we would have to change thousands of lines of code, and we would run into a lot of type issues (because `DataItem` is deeply embedded into everything).

So instead I recommend doing type casts, like this:

```js
onClick(cell: DataItem){
  (cell.dataContext as MyInterface).value
}
```

**Comment by CaselIT** [comment]
Thanks for considering it.

The snipped you provided is similar to what I do: 
```ts
onClick(cell: DataItem & {dataContext: MyInterface})
```

> but it's a huge amount of work

it should be quite painless by setting default type. But I understand that a lot of other changes may be required.

**Comment by Pauan** [comment]
Unfortunately, it isn't as painless as you think.

Changing `class DataItem` is easy, but we would also have to change the thousands of places where `DataItem` is *used*, and those places where it's used now need a new `DataContextType` generic as well.

So we would essentially need to change the entire system, because `DataItem` is used everywhere.

And things also get really complicated because a `Series` can contain many `DataItem`, but they're contained within a `Dictionary`, like this:

```ts
dataItemsByAxis = new Dictionary<string, Dictionary<string, DataItem>>();
```

The problem is that it can have many `DataItem`, and each `DataItem` can have a different `dataContext`, but we can only pass in 1 generic, so there's no way to make this type safe.

**Comment by CaselIT** [comment]
I was only referring to implementing the generic type in the definition, then leave everything else as is, so your snipped remains unchanged, with the default generic type `Object`

I agree that making every declaration generic is a lot of work, and I don't think it's worth it in the library code.

One thing you may consider is replace `Object` with `object` as suggested in the documentation. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types
