### ISSUE TITLE
AxisRange Label valign = 'middle' doesn't work

### ISSUE THREAD

**Issue by tzann** [amcharts/amcharts4#1611]
Positioning a label on an AxisRange with `valign = "middle"` positions it the same as if it were `valign = "bottom"`.

The label is positioned with:
`range.label.inside = true;`
`range.label.valign = "middle";`

Expected result: The label is positioned vertically in the middle of the chart.
Actual result: The label is positioned at the bottom of the chart.

Example: https://codepen.io/ssc-hrep3/pen/ExYvVaK
![image](https://user-images.githubusercontent.com/24497035/64016093-5e221b00-cb26-11e9-8e33-f57ac800be7b.png)

**Comment by martynasma** [comment]
Fixed in [4.5.16](https://github.com/amcharts/amcharts4/releases/tag/4.5.16).

## [4.5.16] - 2019-09-04

### Fixed
- Data sources were not being disposed properly when chart was disposed.
- Adding series to an already inited chart was not showing the series.
- Fixed `StepLineSeries` glitch where base axis was not `CategoryAxis`/`DateAxis`.
- Title of a cloned X axis was being drawn above the axis labels.
- If all values of a `ValueAxis` data wehere the same and negative, the chart zoomed in incorrectly after init.
- Center-alignment of axis labels was not working.
- `maxWidth`/`maxHeight` set on column template of a `ColumnSeries` was not working properly if the size of a cell was less than `maxWidth`/`maxHeight`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
