### ISSUE TITLE
CategoryAxis with StepLineSeries

### ISSUE THREAD

**Issue by towsie84** [amcharts/amcharts4#1613]
Hi,

Is it possible to have categoryAxis as the Y-Axis along with a StepLineSeries?

Thanks

Iain

**Comment by martynasma** [comment]
Do you mean that **both** X and Y axes are `CateoryAxis`?

**Comment by towsie84** [comment]
The X-Axis would be either a CategoryAxis or a DateAxis.

Thanks

**Comment by martynasma** [comment]
OK, so Step Line with be going horizontally or vertically?

**Comment by towsie84** [comment]
It will be going horizontally.

**Comment by martynasma** [comment]
Hm, it kinda works but not quite :)

https://codepen.io/team/amcharts/pen/8571ff9af42561ad3392216c6a9b07e5?editors=0010

I'm setting this up as a bug. It's a quite unusual setup, though. So I'm not sure if we can give this a priority, but we'll get to the fix, eventually.

**Comment by martynasma** [comment]
Fixed in [4.5.16](https://github.com/amcharts/amcharts4/releases/tag/4.5.16).

## [4.5.16] - 2019-09-04

### Fixed
- Data sources were not being disposed properly when chart was disposed.
- Adding series to an already inited chart was not showing the series.
- Fixed `StepLineSeries` glitch where base axis was not `CategoryAxis`/`DateAxis`.
- Title of a cloned X axis was being drawn above the axis labels.
- If all values of a `ValueAxis` data wehere the same and negative, the chart zoomed in incorrectly after init.
- Center-alignment of axis labels was not working.
- `maxWidth`/`maxHeight` set on column template of a `ColumnSeries` was not working properly if the size of a cell was less than `maxWidth`/`maxHeight`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
