### ISSUE TITLE
Animations don’t work with external data 

### ISSUE THREAD

**Issue by abdfahim** [amcharts/amcharts4#1621]
Hi,

Not sure if this is a bug or as designed, but animation doesn't work if I use external data.

For example, the following is the official example for animate a column chart
https://codepen.io/team/amcharts/pen/ERxpwg

But, if I just change this to load external data, animation cease to exist as shown in the fork below
https://codepen.io/abdfahim/pen/JjPreGY

Can you please check?

Thanks,

**Comment by martynasma** [comment]
Data loader just updates the data, meaning that data for already existing series is replaced, hence no initial animation.

I'm not sure if it would be OK for us to trigger those automatically. We'll consider this.

In the interim you can trigger them like this:

```
chart.events.on("datavalidated", function(ev) {
  chart.series.each(function(series) {
    series.appear();
  });
});
```

**Comment by martynasma** [comment]
Since data source can be used in a very wide selection of places, not just chart, we are not going to implement this as a built-in feature.

Please use the suggested workaround.

Documentation has been [updated accordingly](https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Animating_series).
