### ISSUE TITLE
Map with multiple layers doesn't update position on drag

### ISSUE THREAD

**Issue by guiscaranse** [amcharts/amcharts4#1628]
When overlaying multiple maps using Orthographic Projection, and `rotateLongLat` as pan behavior dragging leads to a delay to update other layers position.

You can see a demo in this codepen:
https://codepen.io/guiscaranse/pen/wvwgRwe

**Comment by zeroin** [comment]
Rotating a map with so many polygons is an expensive operation, and amCharts is made so that if rendering of a frame takes more than 45ms, it delays rendering of some sprites for next frame. To avoid this, you update `updateStepDuration` to some bigger number, like:

`am4core.system.updateStepDuration = 500;`

This might however result a higher CPU usage.

**Comment by guiscaranse** [comment]
I see. I think that the use of `updateStepDuration` should be documented in the maps rotation area of amCharts documentation, a higher number of polygons whould be expected if you are building a world wide scale map (which are very common). But I am right now closing this since the above solution works
