### ISSUE TITLE
Capitalizing axis labels?

### ISSUE THREAD

**Issue by nikola1970** [amcharts/amcharts4#1635]
Hello, is it possible to alter the category axis labels somehow but with using the current value? I know that using adapter we can append or prepend something, bold, change color, but can I use that value and alter it? I cannot make that work. 
For example I would like to take the current label and capitalize the first letter ("female" -> "Female").

**Comment by martynasma** [comment]
An adapter is a custom function to modify any value.

You're not limited to just appending stuff to labels, you can completely alter them.

E.g.:

```
categoryAxis.renderer.labels.template.adapter.add("textOutput", function(text) {
  return text.charAt(0).toUpperCase() + text.slice(1)
});
```

P.S. we're using "textOutput" instead of "text", since the former will already contain final label content, whereas the latter will contain a generic placeholder, like "{category}".

**Comment by nikola1970** [comment]
Awesome, thanks! @martynasma  :)
