### ISSUE TITLE
Map is never centered on screen when Russia is rendered

### ISSUE THREAD

**Issue by sergiocastrovale** [amcharts/amcharts4#164]
A simple test like including `polygonSeries.include = ["RU"]` in one of your examples can show what I mean:

![screenshot_1](https://user-images.githubusercontent.com/8822036/43030630-bfa54842-8c8a-11e8-85fa-240c727dead8.png)

No matter what we do, whenever Russia is rendered there's no way to center the map. Any idea why?

**Comment by martynasma** [comment]
See that piece of land all the way to the left? That's a piece of Russia that wraps around 180/-180 latitude threshold. From engine's point of view that's two pieces of land, and they both have to be shown, hence it seeming off-center.

At this point I can't offer another solution, than updating your code to apply manual zoom settings for Russia.

**Comment by martynasma** [comment]
Hey, we just a thought. Maybe you can use `deltaLongitude` to adjust the center so that Russia is whole.

Here's more info about setting map center:
https://www.amcharts.com/docs/v4/chart-types/map/#Setting_map_center

And here's a cool demo about it ;)
https://codepen.io/team/amcharts/pen/BPWMxq?editors=0010

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
