### ISSUE TITLE
Number formatting does not work on TreeMap

### ISSUE THREAD

**Issue by hassankhan** [amcharts/amcharts4#1642]
Hi there,

Using [the fiddle](https://jsfiddle.net/api/post/library/pure/) for the TreeMap chart, I tried to format the numbers using the `chart.numberFormatter.numberFormat` property. However, this does not seem to have any effect, as illustrated in [this fiddle](https://jsfiddle.net/rbandqcy/1/).

It seems like #118 may be related, but I can't seem to figure out what lines specifically fixed the issue from the commit diffs.

**Comment by martynasma** [comment]
At first glance it looks like a bug. Thanks for the heads up.

We'll be looking into this.

**Comment by martynasma** [comment]
Fixed in [4.6.1](https://github.com/amcharts/amcharts4/releases/tag/4.6.1).

## [4.6.1] - 2019-09-18

### Added
- New property `unselectedOverlay` added to `XYChartScrollbar`. It contains a reference to `Sprite` element used as a "curtain" on unselected areas of the scrollbar. Use it to control dimming effect by using its `fill` and `fillOpacity` properties.
- Export: New option `crop` (default: `false`) added to `extraSprices` interface `IExportCanvas`. If set to `true`, it will crop extra elements to match height/width of the main chart being exported.
- Wherever "date format" can be set it now accepts in [Intl.DateTimeFormatOptions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) format. E.g. `chart.dateFormatter.dateFormat = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }`.
- New property `intlLocales` on `DateFormatter`. Specifies list of locales to use if date formates are specified as `IntlDateTimeFormatOptions`.
- JSON: You can now set `parent` property of the elements by their `id` in JSON configs. E.g.: `scrollbarX: { parent: "aa1" }`.
- JSON: You can now set easing functions as strings in JSON config, e.g. `transitionEasing: "ease.cubicInOut"`.

### Fixed
- `TreeMapSeries` and `SunburstSeries` were not inheriting `numberFormatter` propertly from the chart.
- Removed a leftover `console.log()` call.
- Exporting no longer temporarily modifies the site's styles.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by hassankhan** [comment]
Thank you so much @martynasma 🎉
