### ISSUE TITLE
Sankey chart links value 0 

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#1644]
Hello there !

I've to to generate a sankey graph dynamically. The default rendering should look like this

https://codepen.io/ptorrent/pen/dybmROL (link with data value = 0)

What we see:
![image](https://user-images.githubusercontent.com/6083644/64592210-c933e300-d3ab-11e9-9685-1dfb4d9844e0.png)

What I want:
![image](https://user-images.githubusercontent.com/6083644/64592255-e799de80-d3ab-11e9-9fb8-77aef126a6c8.png)

Is there a way to have a better rendering of nodes ?

Thanks for your help !

**Comment by martynasma** [comment]
What is "better rendering of nodes"?

You have a bunch of nodes with zero value, how would you like to depict those?

**Comment by martynasma** [comment]
Fixed in [4.9.35](https://github.com/amcharts/amcharts4/releases/tag/4.9.35).

## [4.9.35] - 2020-08-12

### Added
- New adapter on `XYSeries`: `groupValue`. It's now possible to apply custom aggregate value calculation functions for grouped data items. [More info](https://www.amcharts.com/docs/v4/tutorials/using-custom-functions-for-data-item-grouping/).
- New adapter on `Cursor`: `cursorPoint`. Use it to custom-position chart cursor using your own logic.

### Changed
- Accessibility: Now if ENTER is pressed when object with an enabled `"hit"` event is focused, that event will be triggered automatically.
- Clicking anywhere on the plot area with `XYCursor` will now trigger blur on any focused element on the page (consistent to clicking anywhere else on the document).

### Fixed
- RangeSelector plugin was not properly inheriting chart's locale.
- `"x"` (timestamp) in `inputDateFormat` was not working properly.
- If all values of `SankeyDiagram` were `0` (zero), nodes were not being arranged and their rectangles were not being displayed.
- First `CategoryAxis` label was not visible if `minGridDistance` was set to `0` (zero).
- Old series bullets of an `XYSeries` remained visible when data was updated and data grouping was enabled on related `DateAxis`.
- `Utils.random()` function was not returning value in proper from/to range.
- Stacking now works only between series of the same type. Previously a `LineSeries` between two stacked `ColumnSeries` could mess up stacking for the latter.
- Zooming in on a part of `LineSeries` which had `strokeDashArray` enabled via `propertyFields` was making the whole line dashed.
- On a chart with `XYCursor` hovering on category with a null value for some series, used to display a tooltip for a different category in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
