### ISSUE TITLE
Bug: object (array) assigned to `MapPolygonSeries.data` is mutated

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#165]
Specifically for `MapPolygonSeries`, haven't tested others.

E.g.
```
// Assign clone to data
polygonSeries.data = countriesDataClone;
```

one would expect countriesDataClone to be left alone. But it gets mutated.

View example & console logs here:
https://codepen.io/notacouch/pen/f5f9a5819eb044fc6d37021dc7461470?editors=0011

**Comment by martynasma** [comment]
OK, so here's the deal. Map data would not get mutated if `useGeodata` is not used. Since we use that, the source data (both set on charts and on series directly) gets filled with complimentary data from the GeoJSON.

Working around that would involve complex mechanisms of keeping dual data. That is not efficient, with not a lot benefits.

At this time, unless we hit some sort of deal-breaking scenario, we're going to leave it as it is.

**Comment by martynasma** [comment]
Makes sense!

https://www.amcharts.com/docs/v4/chart-types/map/#Note_about_data_mutation
