### ISSUE TITLE
Problem with tooltip position with PointedCircle on map

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1664]
The tooltips associated with a PointedCircle on a map seem to stay "attached" to their position. When zooming, instead of following the position of the PointedCircle, they stay on the same spot (it doesn't appear to be the same for the PinBullets, for which tooltips stay attached to the base).

Here is a [codepen](https://codepen.io/segolene-albouy/pen/MWgBdMg) of the same bug

![tooltip](https://user-images.githubusercontent.com/44207487/65051075-b64f7e80-d968-11e9-888b-a1686954c9c7.png)
![tooltip-problem](https://user-images.githubusercontent.com/44207487/65051079-b780ab80-d968-11e9-8060-e3d13ed00829.png)

Edit: the same problem happens when you attach the tooltip to the "circle element" of a pinBullet

**Comment by martynasma** [comment]
Fixed in [4.6.2](https://github.com/amcharts/amcharts4/releases/tag/4.6.2).

## [4.6.2] - 2019-09-25

### Added
- New plugin: [OverlapBuster](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/). Allows automatically "exploding" overlapping items such as bullets or markers for easier access to them.
- New property: `maxZoomCount` on `Component`. Use it to limit how many items such as categories or base intervals on axes can be shown at the same time.
- Added `riseFromOpenState`, `riseFromPreviousState`, `dropFromOpenState`, and `dropFromPreviousState` setters to `ColumnSeries`. You can use them to set states to `undefined` if you don't want them to be used.
- A possibility to make "fixed" `ForceDirectedTree` nodes added (via `dataFields.fixed`). Also it is possible to set `x` and `y` of such nodes using `series.nodes.template.propertyField.x` and `y`. [More info](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes).

### Changed
- Removed "GIF" option from the Export menu. Browsers don't know how to convert canvas to GIF, so it was falling back to exporting as PNG, making GIF option redundant.

### Fixed
- If chart's data source was initialized (which would happen by only accessing chart's `dataSource` property) and its `url` was not set, it was still trying to load and resulting in error.
- Formatting number with "b" modifier, was causing all numbers up to 1024 become zero.
- `ColorSet` with default (no) theme was generating colors from second in the list from `4.6.1`.
- Bullet positions were incorrect on `ValueAxis` with `baseValue` set to other than zero.
- Bullet positions with `DateAxis` could be incorrect in some cases.
- Title position of a cloned Axis was nor being positioned properly.
- Cursor was flickering if axis of a cursor had some padding set.
- Tooltip position of `MapImage` elements with `nonScaling = true` could be incorrect in some specific cases.
- Vertical axis break's fill might get out of sync with break lines if the width of a break was small.
- `RadarCursor` could show incorrect label if the chart had `CategoryAxis` with only 3 categories.
- Series was not redrawing properly if its axis range value changed.
- `PieChart` could show some labels out of chart area in some specific cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
