### ISSUE TITLE
When change chart event from "ready" to "datavalidated", the function of pre-zoom is not work?

### ISSUE THREAD

**Issue by yuxuejiao** [amcharts/amcharts4#1671]
[https://codesandbox.io/s/vue-template-udvli](url)
From the link, you can see the function of pre-zoom of top chart is not work , the chart below does not has this problem. 
the distinction of the two chart is the event they listen to.
`chart.events.on("datavalidated", function() {
       dateAxis.zoomToDates(new Date(startDate), new Date(endDate));
});`

**Comment by martynasma** [comment]
I'm not entirely sure why it does not work for your particular setup. It should. I wasn't able to reproduce it in a simpler chart.

That said, delaying zoom seems to be working:

```
        chart.events.on("datavalidated", function() {
          console.log(startDate)
          setTimeout(function() {
          dateAxis.zoomToDates(new Date(startDate), new Date(endDate));
          }, 100)
        });
```

Also, if you need to use "datavalidated" instead of "ready", I'm assuming you are going to be updating data and want to retain zoom position.

For such task axis' [`keepSelection`](https://www.amcharts.com/docs/v4/reference/dateaxis/#keepSelection_property) property might be a better solution.

**Comment by yuxuejiao** [comment]
It works! The reason I use "datavalidated" instead of "ready is when the chart's data is a lot, If i use "ready",  there will  appear a scene that all data are shown on the limited axes, then the pre-zoom works.  But I use "datavalidated", the scene that all data are shown on the limited axes will not appear.
