### ISSUE TITLE
Any offset applied to x-axis breaks cursor somehow

### ISSUE THREAD

**Issue by potrata** [amcharts/amcharts4#1676]
Greetings! 
In my case I need to add some space between x-axis and plot area (to show some custom ranges with subtotal values). I'm doing that by adding non-zero `marginTop` value directly on xAxis. Chart renders pretty well generally, but cursor starts to disappear at some "boundary" points, which leads to tooltip flickering, etc. 
_I've also tried to set `paddingTop` and `dy` both on the axis itself and on the `bottomAxesContainer`, but ran into the same problem._

Here is the recording, illustrating cursor behaviour:
![Cursor](https://media.giphy.com/media/fqc2QeLs7i3EMl1V9w/giphy.gif)

And here is an example of broken chart:
https://codesandbox.io/s/amcharts-4-broken-cursor-w86ux

**Comment by martynasma** [comment]
How about using `startLocation` and `endLocation`?

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

**Comment by potrata** [comment]
> How about using `startLocation` and `endLocation`?
> 
> https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_where_axis_starts_and_ends

Tweaking these settings did not help, problem still here.
I'd like to sort it out how changing **vertical** axis indentation can affect **horizontal** chart layout.

**Comment by potrata** [comment]
https://github.com/amcharts/amcharts4/blob/master/src/.internal/charts/cursors/XYCursor.ts#L733

That's the place in code, where cursor becomes hidden. And it's happening because of x-axis tooltip doesn't fit to cursor bounds anymore 😕

Any workarounds?

**Comment by martynasma** [comment]
Fixed in [4.6.2](https://github.com/amcharts/amcharts4/releases/tag/4.6.2).

## [4.6.2] - 2019-09-25

### Added
- New plugin: [OverlapBuster](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/). Allows automatically "exploding" overlapping items such as bullets or markers for easier access to them.
- New property: `maxZoomCount` on `Component`. Use it to limit how many items such as categories or base intervals on axes can be shown at the same time.
- Added `riseFromOpenState`, `riseFromPreviousState`, `dropFromOpenState`, and `dropFromPreviousState` setters to `ColumnSeries`. You can use them to set states to `undefined` if you don't want them to be used.
- A possibility to make "fixed" `ForceDirectedTree` nodes added (via `dataFields.fixed`). Also it is possible to set `x` and `y` of such nodes using `series.nodes.template.propertyField.x` and `y`. [More info](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes).

### Changed
- Removed "GIF" option from the Export menu. Browsers don't know how to convert canvas to GIF, so it was falling back to exporting as PNG, making GIF option redundant.

### Fixed
- If chart's data source was initialized (which would happen by only accessing chart's `dataSource` property) and its `url` was not set, it was still trying to load and resulting in error.
- Formatting number with "b" modifier, was causing all numbers up to 1024 become zero.
- `ColorSet` with default (no) theme was generating colors from second in the list from `4.6.1`.
- Bullet positions were incorrect on `ValueAxis` with `baseValue` set to other than zero.
- Bullet positions with `DateAxis` could be incorrect in some cases.
- Title position of a cloned Axis was nor being positioned properly.
- Cursor was flickering if axis of a cursor had some padding set.
- Tooltip position of `MapImage` elements with `nonScaling = true` could be incorrect in some specific cases.
- Vertical axis break's fill might get out of sync with break lines if the width of a break was small.
- `RadarCursor` could show incorrect label if the chart had `CategoryAxis` with only 3 categories.
- Series was not redrawing properly if its axis range value changed.
- `PieChart` could show some labels out of chart area in some specific cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
