### ISSUE TITLE
xlsx exporting.dateFormat header

### ISSUE THREAD

**Issue by isama92** [amcharts/amcharts4#1698]
Hello,
I noticed that when I export a xlsx of a LineSeries with the exporting.dateFields option the header is getting formatted along with the rest of the column resulting in a 'incorrect date' string instead of the label I set.

This happen even in the jsfiddle this user posted few months ago.
https://github.com/amcharts/amcharts4/issues/1372#issue-455007739

(JSFiddle here: https://jsfiddle.net/57jvL1a4/)

**Comment by martynasma** [comment]
Fixed in [4.6.4](https://github.com/amcharts/amcharts4/releases/tag/4.6.4).

## [4.6.4] - 2019-09-29

### Added
- Ukrainian translation (uk_UA).
- `DataSource` now supports binary loading using `responseType = "blob"`.

### Fixed
- Setting `exporting.dateFormat` resulted in "Invalid date" as a column name for date/time columns when exporting to XLSX.
- Performance improved, especially data-parsing.
- When panning `XYChart`, the chart will round selections respecting `startLocation` and `endLocation` values of the Axis.
- First bullet of a series with `CategoryAxis` could be positioned incorrectly.
- Conflict between Annotation plugin and amCharts 3 Export plugin fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
