### ISSUE TITLE
Line-Chart Date Axis. Unsorted Data displaying wrong

### ISSUE THREAD

**Issue by tobiasbeck** [amcharts/amcharts4#170]
When using a Line-Chart and a Date-Axis, the data is not rendered correctly. only when they are sorted by data before pushed to the chart, they are rendered correctly.
My data looks as following: (unsorted)
```
[
 {
    value: 8,
    _id: '2018-07-18T12:39:08.000Z'
  },
  {
    value: 4,
    _id: '2018-07-17T17:01:13.000Z'
  },
 
  {
    value: 8,
    _id: '2018-07-19T15:47:31.000Z'
  },
{
    value: 128,
    _id: '2018-07-23T11:16:22.000Z'
  },
  {
    value: 4,
    _id: '2018-07-20T12:50:56.000Z'
  },
  {
    value: 8,
    _id: '2018-07-21T22:11:43.000Z'
  },
 {
    value: 424,
    _id: '2018-07-16T07:28:13.000Z'
  },
  
  {
    value: 16,
    _id: '2018-07-24T07:12:02.000Z'
  }
]
```

**Comment by martynasma** [comment]
If you are using `DateAxis` the chart will show all data points in correct places.

Here's a demo using your (unsorted) data:
https://codepen.io/team/amcharts/pen/03fa8cd02f75dceaf00e18942b1bf59c?editors=0010

This works well for `ColumnSeries`, but won't work for connected series, like `LineSeries`, because the line will follow the order of your data items creating a mess of a chart.

If you are using `LineSeries` I can only recommend pre-sorting your data using [`Array.sort()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

**Comment by martynasma** [comment]
I closed this, but please feel free to post any follow up questions you may have.

**Comment by tobiasbeck** [comment]
Thank you for your response. 
You should point this out in the documentation, as this is not really a expected behavior, and costed me about 4 hours of debugging.

**Comment by martynasma** [comment]
Dully noted. Sorry for the inconvenience!

**Comment by martynasma** [comment]
There you go:
https://www.amcharts.com/docs/v4/concepts/data/#Order_of_data_items

**Comment by tianmarin** [comment]
> There you go:
> https://www.amcharts.com/docs/v4/concepts/data/#Order_of_data_items
Thank you!!

In my case i was a couple of days :(

´´´javascript
        var self = this;
        this.chart.events.on("beforedatavalidated", function(ev) {
          self.chart.data.sort(function(a, b) {
            return (a.date) - (b.date);
          });
        });
```
