### ISSUE TITLE
Background format not updating when changing projection

### ISSUE THREAD

**Issue by guiscaranse** [amcharts/amcharts4#1715]
When changing a projection on the fly, the background format is not updated.

Example:
https://codepen.io/guiscaranse/pen/oNvKbEO

**Comment by martynasma** [comment]
Fixed in [4.6.7](https://github.com/amcharts/amcharts4/releases/tag/4.6.7).

## [4.6.7] - 2019-10-05

### Added
- `paddingRadius` added to `ForceDirectedNode`. Allows having some extra free space around bubbles.
- New event on all `Sprite` elements: `parentset`. Triggers whenever element's `parent` is set.

### Fixed
- `MapChart` background was not being updated if map projection was changed after init.
- Axis' tooltip was not changed if user rolled over the axis, rolled out and then rolled over it again on the same axis item.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
