### ISSUE TITLE
Category Axis Tooltips not appearing

### ISSUE THREAD

**Issue by klmntoth** [amcharts/amcharts4#1717]
The same tooltip wont appear until you trigger another one.

https://codepen.io/team/amcharts/pen/vrBerZ
for example:
trigger the first category axis tooltip (1994)
move out your cursor without triggering another
try triggering the first again

**Comment by martynasma** [comment]
Yup, looks like a bug. Thanks for letting us know.

Will let you know when a fix is available.

**Comment by martynasma** [comment]
Fixed in [4.6.7](https://github.com/amcharts/amcharts4/releases/tag/4.6.7).

## [4.6.7] - 2019-10-05

### Added
- `paddingRadius` added to `ForceDirectedNode`. Allows having some extra free space around bubbles.
- New event on all `Sprite` elements: `parentset`. Triggers whenever element's `parent` is set.

### Fixed
- `MapChart` background was not being updated if map projection was changed after init.
- Axis' tooltip was not changed if user rolled over the axis, rolled out and then rolled over it again on the same axis item.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
