### ISSUE TITLE
Can AmCharts set the 'SameSite' cookie to silence the Chrome warning?

### ISSUE THREAD

**Issue by afarley-tangent** [amcharts/amcharts4#1722]
When I load AmCharts javascript in my page in Chrome, I see a warning:

`A cookie associated with a cross-site resource at http://amcharts.com/ was set without the `SameSite` attribute.`

As far as I can tell, this is something that can only be addressed on the server-side where the Javascript is hosted. Am I correct? Or is this my responsibility as the user to fix this?

**Comment by martynasma** [comment]
Yes. As we provide a CDN use of our libs, we can't enforce any restrictive headers, because our users use our libs in a million of different ways.

If you need some specific headers, you are welcome to put amCharts file son your own web server and decorate them with response headers you require.

Ways to get amCharts files are listed on this page:
https://www.amcharts.com/download/
