### ISSUE TITLE
Broken localization in 4.6.5

### ISSUE THREAD

**Issue by NemoDima** [amcharts/amcharts4#1728]
Broken localization in 4.6.5
4.6.5
https://codepen.io/vovaltus/pen/jOONJOv?editors=1000
![изображение](https://user-images.githubusercontent.com/43349820/66209940-427bd880-e6c1-11e9-94d7-6e33701d112c.png)

4.6.0
https://codepen.io/vovaltus/pen/rNNBRmN 
![изображение](https://user-images.githubusercontent.com/43349820/66209981-5e7f7a00-e6c1-11e9-9a76-12053b385315.png)

**Comment by martynasma** [comment]
Fixed in [4.6.6](https://github.com/amcharts/amcharts4/releases/tag/4.6.6).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
