### ISSUE TITLE
ForceDirectedTree bug

### ISSUE THREAD

**Issue by genryd** [amcharts/amcharts4#1729]
I'm using this example: https://www.amcharts.com/demos/force-directed-network/

I set:

`am4core.options.onlyShowOnViewport = true;`

If you add div before the chart (to make it out of viewport ), then scroll up, reload page and scroll down. Now the force and distance settings is not working.

**Comment by martynasma** [comment]
Thanks. Looks like a bug.

Codepen for dev team:
https://cdpn.io/team/amcharts/debug/d3e66c78f47910e182efc21c54385efd

What I get when chat scrolls into view and is revealed:
![image](https://user-images.githubusercontent.com/1458520/66264941-6b61b200-e816-11e9-9997-1af422d70600.png)

This is how it should normally look:
![image](https://user-images.githubusercontent.com/1458520/66264949-9815c980-e816-11e9-8967-dfc72bd69789.png)

**Comment by martynasma** [comment]
Fixed in [4.6.8](https://github.com/amcharts/amcharts4/releases/tag/4.6.8).

## [4.6.8] - 2019-10-07

### Added
- New `Export` property: [`validateSprites`](https://www.amcharts.com/docs/v4/reference/export/#validateSprites_property). It's an array you can push any `Sprite` to it. When export starts, it will check if those elements are not invalid and will await for them to be ready. This is useful if you need to do any modifications to your chart for export.
- New option for CSV and XSLX export options: `pivot`. If set to `true`, will "pivot" the data so that firsst column is field names with values lined up horizontally in rows.
- New property on `NumberFormatter`: `smallNumberThreshold` (default `1`). You can now set what is considered a "small number" when applying small number prefixes if `"a"` format modifier is used.

### Fixed
- If `ForceDirectedTree` was used with `am4core.options.onlyShowOnViewport = true`, the forces on links were not being calculated properly, resulting in incorrect layout.
- JSON: String dates will now be correctly parsed using `DateFormatter` in axis ranges' `date` and `endDate` properties.
- `WordCloud` was not properly parsing Korean text.
- If `MapChart` was zoomed in while still playing pan inertia animation, it produced a jerky effect.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by genryd** [comment]
Thanks for the prompt help! I appreciate it so much!

Now if ForceDirectedTree is used with `am4core.options.onlyShowOnViewport = true`, the chart looks more disordered and nodes go beyond the borders. The latter issue can be fixed by increasing the area, but not the first one.

**Comment by martynasma** [comment]
I don't get any significant differences in layouts between using and not using this feature.

Do you have an example?

**Comment by genryd** [comment]
Most likely these are random differences. Never mind, everything is fine.

Many thanks!

**Comment by martynasma** [comment]
Yeah, ForceDirectedTree is influenced by a number of factors, including a bit of randomness. That's how it works.

**Comment by genryd** [comment]
Example: https://cmi.to/r2/

I conducted a survey and most people agreed that loading in viewport looks more ordered than loading after scroll down. As if lacking repulsive power.

**Comment by martynasma** [comment]
Alright. We'll give it another look. Thanks!

**Comment by genryd** [comment]
Greetings! Any updates on this issue?

**Comment by martynasma** [comment]
Not yet. We'll post any developments here when there are any.

**Comment by martynasma** [comment]
Hi again. Sorry for the wait. We have decided not to implement this fix due to complexity of third party algo. Sorry.
