### ISSUE TITLE
What is the name of the element animation that happens when updating the range of the  y axis scale?

### ISSUE THREAD

**Issue by algebrathefish** [amcharts/amcharts4#1734]
Hi:

I am working on a series with live updating , so much like this one https://codepen.io/team/amcharts/pen/MGVbNV

I would like to have a smooth animation, without the bouncing effect for the change of scale

I was reading here https://www.amcharts.com/docs/v4/concepts/animations/#Using_easing_functions but I really don't know to which element to change the .transitionEase

Thank you

**Comment by zeroin** [comment]
I found out that `rangeChangeEasing` was not passed to animation which was happening when min/max values changed, so it used default `linear` easing while values were animating using `cubicOut` easing. So this will be fixed in next release. I tested it and it is much better now, however some bounciness might still happen, not because of the easing function but because all the processes are not 100% synced. We will let you know when new version is released.

**Comment by martynasma** [comment]
Fixed in [4.7.2](https://github.com/amcharts/amcharts4/releases/tag/4.7.2).

## [4.7.2] - 2019-10-18

### Added
- `RadarColumn` now supports `width` adapter (the adapter should return `Percent` object).

### Changed
- `minWidth`/`minHeight` set on Axis to 0.0001 to avoid ready event to be not called on super small divs.

### Fixed
- A link between two fixed `ForcedDirectedTree` nodes was not visible.
- If `maxZoomCount` was set on a series which was used for `XYChartScrollbar`, scrollbar series was zoomed-in.
- `PercentChart`'s legend, if placed to an external div could loose text formatting after data update.
- `gridType = "polygons"` of `RadialAxis` was not working.
- Label of `PinBullet` was not being cloned.
- `rangeChangeEasing` function was not being passed to `ValueAxis` min/max animation which resulted in some unwanted animation effects when min/max of the axis changed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
