### ISSUE TITLE
Cannot change Radar Chart grid to linear

### ISSUE THREAD

**Issue by rickygordon** [amcharts/amcharts4#1736]
From release 4.6.4 on wards setting the gridType property on the AxisRendererRadial class to "polygons" has no effect the graphs look.

example using latest amcharts: https://jsfiddle.net/s34q9nwr/

**Comment by martynasma** [comment]
Looks like a bug. Thank you for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.7.2](https://github.com/amcharts/amcharts4/releases/tag/4.7.2).

## [4.7.2] - 2019-10-18

### Added
- `RadarColumn` now supports `width` adapter (the adapter should return `Percent` object).

### Changed
- `minWidth`/`minHeight` set on Axis to 0.0001 to avoid ready event to be not called on super small divs.

### Fixed
- A link between two fixed `ForcedDirectedTree` nodes was not visible.
- If `maxZoomCount` was set on a series which was used for `XYChartScrollbar`, scrollbar series was zoomed-in.
- `PercentChart`'s legend, if placed to an external div could loose text formatting after data update.
- `gridType = "polygons"` of `RadialAxis` was not working.
- Label of `PinBullet` was not being cloned.
- `rangeChangeEasing` function was not being passed to `ValueAxis` min/max animation which resulted in some unwanted animation effects when min/max of the axis changed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
