### ISSUE TITLE
Label of a PinBullet is not being cloned

### ISSUE THREAD

**Issue by enxt** [amcharts/amcharts4#1739]
Hi,
I´m trying setting and view text inside the **PinBullets** assigned to a LineSerie, , but it seems to fail.

Hi have a demo in:  [https://codepen.io/enxt/pen/qBBEwgV](https://codepen.io/enxt/pen/qBBEwgV)

I also modified the **Plugin Bullets demo** to show that here the text is being displayed correctly [https://codepen.io/enxt/pen/MWWwvM](https://codepen.io/enxt/pen/MWWwvMK)

**Comment by martynasma** [comment]
Looks like text is not being cloned when PinBullet is cloned.

You can fix that using:

```
bullet.label.shouldClone = true;
```

We should probably enable that by default as well.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.7.2](https://github.com/amcharts/amcharts4/releases/tag/4.7.2).

## [4.7.2] - 2019-10-18

### Added
- `RadarColumn` now supports `width` adapter (the adapter should return `Percent` object).

### Changed
- `minWidth`/`minHeight` set on Axis to 0.0001 to avoid ready event to be not called on super small divs.

### Fixed
- A link between two fixed `ForcedDirectedTree` nodes was not visible.
- If `maxZoomCount` was set on a series which was used for `XYChartScrollbar`, scrollbar series was zoomed-in.
- `PercentChart`'s legend, if placed to an external div could loose text formatting after data update.
- `gridType = "polygons"` of `RadialAxis` was not working.
- Label of `PinBullet` was not being cloned.
- `rangeChangeEasing` function was not being passed to `ValueAxis` min/max animation which resulted in some unwanted animation effects when min/max of the axis changed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
