### ISSUE TITLE
zoomControl issues for zooms < 1

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#174]
[pen](https://codepen.io/notacouch/pen/7b7bbee45ad000190f3bac54eb14dbc0?editors=0010), [live version](https://codepen.io/notacouch/live/7b7bbee45ad000190f3bac54eb14dbc0)

When `chart.minZoomLevel` is < 1, and `chart.maxZoomLevel` is around 1 more/less, the `chart.zoomControl.thumb` is way too tall:
![image](https://user-images.githubusercontent.com/2334143/43293868-76ca21d6-910a-11e8-97ae-d5dd477a38a5.png)

Though the height improves with larger values for `chart.maxZoomLevel`, the support for zooming out to `zoomLevel`s of < 1 seems a little off.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.41](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.41).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
