### ISSUE TITLE
Super thick MapPolygon and Line strokes on quick zoom

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#175]
[pen](https://codepen.io/notacouch/pen/e02dbf097c8cce0f8ddfe9eea01627f8?editors=0010), [live version](https://codepen.io/notacouch/live/e02dbf097c8cce0f8ddfe9eea01627f8)

Use the zoomControl slider to zoom in/out really fast, at some point the polygon strokes and the lines become super thick:
![image](https://user-images.githubusercontent.com/2334143/43294381-ef87c7b6-910c-11e8-9c5f-4dad53c7676c.png)

How they normally appear:
![image](https://user-images.githubusercontent.com/2334143/43294406-0b2680ca-910d-11e8-995f-0bd35cd920de.png)

Same behavior in another project I'm working on (effects were way more exaggerated, FF on left, Chrome on right):
![image](https://user-images.githubusercontent.com/2334143/43294208-20d91cb2-910c-11e8-8174-4b65388dbb5a.png)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.50](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.50).

## [4.0.0-beta.50] - 2018-09-10

### Added
- `am4core.unuseAllThemes()` method added. Any chart created after this method call will not have any theme applied to it.
- New property `am4core.registry.baseSprites` will now hold all active (non-disposed) instances of top-level elements, such as charts.
- `startLocation`/`endLocation` properties added to `CategoryAxis` (previously available on `DateAxis` only). Allows to specify location the first and last cells of the axis should start on respectively.
- `innerRadius` of a Slice can now be set as `Percent` (e.g. `am4core.percent(50)`).
- You can now set custom radii (`radius` property) on Pie series (if you have more than one, you might want one to be larger and another smaller).

### Changed
- [`MapLine.imagesToConnect`](https://www.amcharts.com/docs/v4/reference/mapline/#imagesToConnect_property) now accepts an array of string IDs that can reference images by their `id` property.
- Changed `tooltip` inheritance so that it checks for `virtualParent` rather than direct `parent`. E.g. series' bullets use series' tooltip and not chart tooltip as it was before.

### Fixed
- Map polygon stroke thickness could be rendered incorrectly when zooming quickly. (Issue #175)
- Calling `addData()` more than once before data was validated resulted only last data item to be added. (Issue #222)
- `DateAxis.baseInterval` was ignored if data was set directly on series.
- `MapLine` was not paying attention to the properties set on template.
- `HeatLegend` was not updating its label count after its size changed. This could have been resulting in very few labels if initial container (div) size was small.
- The map portion of `MapChart` was incorrectly positioned after container (div) resize.
- Object properties, like `"name"` in GeoJSON were overriding same properties in `MapSeries` data. Now, the values specified in data are used over ones in GeoJSON. (Issue #307)
- Axis ranges used to reset `axisRange.label.text`. (Issue #308)
- Fixed issues with disposing series and charts.
- Updated to [canvg 1.5.3](https://github.com/canvg/canvg/releases/tag/v1.5.3) to fix em/rem text issue for epoxrt fallbacks.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
