### ISSUE TITLE
With grouping on data chart is sometimes not visible, depending on the width of the chart

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1756]
When using the new data groups I am experiencing some weird behaviour

<img width="856" alt="Screenshot 2019-10-15 at 11 07 35" src="https://user-images.githubusercontent.com/1268723/66817544-2804f300-ef3c-11e9-82a1-02d5ee7b623e.png">

As you can see the tooltip works but the lines are not drawn? 

I have no error messages or so, however, a screen resize will fix it

**Comment by martynasma** [comment]
Yes. We've noticed this behavior, too. Fixing as we speak. Hold tight ;)

**Comment by martynasma** [comment]
Fixed in [4.7.1](https://github.com/amcharts/amcharts4/releases/tag/4.7.1).

## [4.7.1] - 2019-10-16

### Added
- Two additional auto-calculated values (used in `valueXShow` and `valueYShow` data fields) added: `startChange` and `startChangePercent`. Shows change from starting value of the first data item in series.

### Changed
- Animated theme: Default values for `rangeChangeDuration` and `interpolationDuration` changed to `500` (was `700`). Makes zooming animations more snappy.

### Fixed
- Data item grouping was sometimes producing visual anomalies when multiple data sets were being loaded /set to chart/series asynchronously.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
