### ISSUE TITLE
Question: How to group data (confused)

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1760]
Hi there great am4Charts team, 

My data are based on **hourly**  values.

Eg monday 30km , tuesday 50km etc 

They can span up to years if the user selects so as seen below (see the month, year etc selection)

Here is an example of ungroupped data 
<img width="975" alt="Screenshot 2019-10-16 at 09 58 52" src="https://user-images.githubusercontent.com/1268723/66899619-96f55100-effb-11e9-8f2e-761d63990c28.png">

When I enable grouping it looks like this: 
<img width="979" alt="Screenshot 2019-10-16 at 10 01 22" src="https://user-images.githubusercontent.com/1268723/66899846-ee93bc80-effb-11e9-9249-7f0d9202a9e1.png">

I read the documentation but I am a bit confused on how to tackle this. 

Idealy if the data range that the user selects is : 

Range 30 days -> He should see a daily breakdown 
Range 12 months -> He should see monthly breakdown 
Range >=1 years -> He should see yearly breakdown 

Currently its not like this as you can see 

Do I need to change the groupIntervals and do that dynamically or is it something more simple that I am missing or even some bug perhaps?

**Comment by martynasma** [comment]
Well, you can change `groupIntervals` as well as `groupCount` to set what and how is grouped.

Also, you should probably change series' `groupFields` to "sum" Y value instead of show close value when grouping occurs.

That said this:

> Range 30 days -> He should see a daily breakdown
Range 12 months -> He should see monthly breakdown
Range >=1 years -> He should see yearly breakdown

I don't think it's possible because `groupCount` is one number for all periods, so you can't specify numbers.

It basically means that if there are more data points than `groupCount`, it will group to a bigger period.

E.g. if you set it to 30, then it show days if there are less period selected than 30 days.

Once you select bigger period, say 45 days, it will switch to months (actually it will switch to weeks unless you modify `groupIntervals`).

Then when you zoom out further, say to 2 years, it will still be showing months, because 2 years is just 24 months or less than 30. Only when you select to more than 2.5 years it will switch to years.

Hope that makes sense.

**Comment by THEaustinlopez** [comment]
This is a SERIOUS oversight by the library honestly. I have had to dynamically update groupCounts based on ranges in view by listening to the scrollEvent. It "kinda" works but it is highly unstable and clearly not deigned to work this way. Who would want dateTime data at the minute/second level and not be able to zoom out and see what the OG post suggested. Group from minutes, to hours, to days, weeks, months, years? For those who might want to have this "basic" functionality here is a small sample of the code that sort of makes its work:

This is a little out of context but basically just get the diff in milliseconds  and then check them between the ranges you want and set the groupCount from there. It's a bit barbaric but it's all we got right now.

`
function getDateDiff(dateA: number, dateB: number) {
      const diffMilliseconds = Math.abs(dateA - dateB);
      return diffMilliseconds;
    } 

xAxis.adapters.add('groupCount', function (value: any, target: any, key: any) {
            let updatedGroupCount = value;
            if (diffTime >= (1000 * 60 * 60 * 24 * 365)) {
              updatedGroupCount = 1;
            } else if (diffTime < (1000 * 60 * 60 * 24 * 365) && diffTime >= (1000 * 60 * 60 * 24 * 31)) {
              updatedGroupCount = 12;
            } else if (diffTime <= (1000 * 60 * 60 * 24 * 31) && diffTime > (1000 * 60 * 60 * 24 * 7)) {
              updatedGroupCount = 7;
            } else if (diffTime <= (1000 * 60 * 60 * 24 * 7) && diffTime > (1000 * 60 * 60 * 24)) {
              updatedGroupCount = 1;
            } else if (diffTime < (1000 * 60 * 60 * 24) && diffTime > 3600000) {
              updatedGroupCount = 24;
            } else if (diffTime < 3600000 && diffTime > 60000) {
              updatedGroupCount = 60;
            } else if (diffTime < 10000) {
              updatedGroupCount = 10;
            }
            console.log(key + ' is ' + updatedGroupCount);
            return updatedGroupCount;
          });`
