### ISSUE TITLE
In Group Bar Chart, Value-Axis value in negative, Column Bar show in middle of the chart

### ISSUE THREAD

**Issue by erhspatel** [amcharts/amcharts4#1761]
In Group Bar Chart, Value-Axis value in negative, Column Bar show in middle of the chart. (Previously, I had created issue. #1750 )

https://codepen.io/erhspatel/pen/PooZGBE

**Comment by zeroin** [comment]
It happens because you have a separate y value axis for each series. And for the series which values is negative, the minimum value is at the top. Unfortunately there is no way to sync grid so that 0 value of all axes would be at the same position. But maybe you don't need a separate y axis for each of the series? The same chart with a single axis looks fine: https://codepen.io/team/amcharts/pen/a954c0a58e241c19cdf663d802841699
