### ISSUE TITLE
Fetaure requests: Increasing maxPrecision and adding minPrecision 

### ISSUE THREAD

**Issue by WavescapTorben** [amcharts/amcharts4#1765]
When im using ValueAxis like this:

valueAxis = chart.yAxes.push( new am4charts.ValueAxis() );				
valueAxis.maxPrecision = 8;

it had no effect setting maxPrecision higher then 5, it shows maximal 5 digits after the point on the axis, but my data has up to 8 digits. 

Would be very nice to increase the possible digits for that.
And maybe add a minDigitsForScientificNotation as well :)

Other idea I had was to introduce a minPrecision option..

Or maybe there is an other way around this?

Big thanks for your work here!

**Comment by martynasma** [comment]
Well, `ValueAxis` does not show exact values in your data. It shows grid at intervals with appropriate precision for the axis scale. So `maxPrecision` is not for increasing precision, it's for limiting it.

I don't see how `minPrecision` could work in this case.

Say you have a series that range values from 0.000025 to 0.000085. The ValueAxis chooses "rounded" scale and produces 0 to 0.0001, with 5 grid lines displayed at values 0, 0.00001, 0.00002, etc. You can set `maxPrecision` to 8 but that does will have no effect on those labels since they have only decimal 5.

I hope that makes sense.

**Comment by WavescapTorben** [comment]
So there is no way to increase the decimals? This would be bad for for some scenarios. For example some times i have data between 0 and 0.000001, so that the valueAxis shows 0, 0.00001, 0.00001, 0.00001, 0.00001..

**Comment by martynasma** [comment]
Ah, OK, I know what's going on.

NumberFormatter (which is used to format all numbers on the chart), has this number format set by default: `"#,###.#####"`

This means 5 decimal places.

So, all you need to do is to modify it:

```
chart.numberFormatter.numberFormat = "#,###.#########";
```

Or eliminate rounding completely:

```
chart.numberFormatter.numberFormat = "#";
```

No need to use `maxPrecision` at all.

Sorry for not catching this before.

**Comment by WavescapTorben** [comment]
Thank you:)
