### ISSUE TITLE
maxZoomCount on axis limit the section on chart, and scrollbar series interval break

### ISSUE THREAD

**Issue by yingyinghu** [amcharts/amcharts4#1769]
When I set the maxZoomCount to two days, and I have an XYChartScrollbar with Series (so I can see the x axis dateValues), the interval is show only of two days, so the scroll is dislocate.
![maxzoomcount](https://user-images.githubusercontent.com/11941866/67026523-30aa2480-f108-11e9-9f72-579efb5391f1.png)

**Comment by martynasma** [comment]
Thanks for bringing this to our attention.

Example:
https://codepen.io/team/amcharts/pen/e3029f440a2e042ec0d4c6b291a19b3b?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.7.2](https://github.com/amcharts/amcharts4/releases/tag/4.7.2).

## [4.7.2] - 2019-10-18

### Added
- `RadarColumn` now supports `width` adapter (the adapter should return `Percent` object).

### Changed
- `minWidth`/`minHeight` set on Axis to 0.0001 to avoid ready event to be not called on super small divs.

### Fixed
- A link between two fixed `ForcedDirectedTree` nodes was not visible.
- If `maxZoomCount` was set on a series which was used for `XYChartScrollbar`, scrollbar series was zoomed-in.
- `PercentChart`'s legend, if placed to an external div could loose text formatting after data update.
- `gridType = "polygons"` of `RadialAxis` was not working.
- Label of `PinBullet` was not being cloned.
- `rangeChangeEasing` function was not being passed to `ValueAxis` min/max animation which resulted in some unwanted animation effects when min/max of the axis changed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by yingyinghu** [comment]
Thanks!
