### ISSUE TITLE
Force display to show in days - totals not being calculated properly

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#1770]
Need some help figuring out what I am doing wrong here.  I have data coming in each with a timestamp (this happens to be stats reported back from Amazon's SES service).  I want to always display the chart as days instead of seconds, minutes, etc.  When I do that the chart totals are never calculated properly.

I created a fiddle here to show what is happening - [https://jsfiddle.net/8d4whgmc/1/](https://jsfiddle.net/8d4whgmc/1/)

Is there a setting I am missing here or maybe using the wrong way?

**Comment by xorspark** [comment]
Forcing the `baseInterval` to a day doesn't make the chart sum up your data.

As of 4.7, [dynamic data grouping](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Dynamic_data_item_grouping) was introduced for date x axis and value y axis setups, which would do the automatic summing that you're looking for, after tweaking the settings accordingly. This won't work with your setup, however, since you're referencing properties directly by name for your single grouped tooltip per data point. Unless I'm missing something, settings-wise, you'll need to manually pre-process and group/sum up your data by days and pass it into your chart for your use case.

[Here's an updated fiddle that demonstrates this](https://jsfiddle.net/4vw6nf1x/). Also note that date-based data [must be in ascending order](https://www.amcharts.com/docs/v4/concepts/data/#Order_of_data_items); your data set was in descending order.

**Comment by morrow95** [comment]
@xorspark  - it's not just the tooltips... it is the data itself on the chart.  The column totals are wrong and not summed which I thought was supposed to be automatic.

**Comment by xorspark** [comment]
@morrow95 - It was never automatic. The totals only get summed up if you enabled data grouping, which was recently introduced. The only limitation of data grouping is your tooltip setup, which is why you need to manually sum it up yourself.
