### ISSUE TITLE
Distinguish various legend events (reopen #7, version 4.6.9)

### ISSUE THREAD

**Issue by Christian-Adler** [amcharts/amcharts4#1778]
How to detect if a legend click is on the marker or the label?

Event fired but on **both**.
`    chart.legend.itemContainers.template.events.on('hit', (ev) => {`
`      console.log('Clicked on', ev.target);`
`    })`;

--------------------------

Using the code of issue #7 a type **error** is thrown:
Uncaught TypeError: chart.legend.markers.template.on is not a function
`    chart.legend.markers.template.on("hit", function (ev) {`
`      console.log("clicked", ev.target);`
`    });`
`    chart.legend.labels.template.on("hit", function (ev) {`
`      console.log("clicked", ev.target);`
`    });`

--------------------------

With **template.events** nothing is fired.
`    chart.legend.markers.template.events.on("hit", function (ev) {`
`      console.log("clicked", ev.target);`
`    });`
`    chart.legend.labels.template.events.on("hit", function (ev) {`
`      console.log("clicked", ev.target);`
`    });`

**Comment by xorspark** [comment]
You have to set `interactionsEnabled` on the marker and label template in order to capture events on them individually (they are set to false by default, as explained in the [change logs](https://github.com/amcharts/amcharts4/blob/master/dist/ember/CHANGELOG.md#400-beta65---2018-10-28)).

```
chart.legend.markers.template.interactionsEnabled = true;
chart.legend.markers.template.events.on("hit", function (ev) {
  console.log("clicked", ev.target);
});
chart.legend.labels.template.interactionsEnabled = true; 
chart.legend.labels.template.events.on("hit", function (ev) {
  console.log("clicked", ev.target);
});
```

[Demo](https://codepen.io/team/amcharts/pen/2e40b00b6343cd36c2280c26f0aa8712?editors=0010)

**Comment by Christian-Adler** [comment]
It works - thanks :)
