### ISSUE TITLE
How to disable animations?

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#178]
Hello,

In version 3 there was a flag 'startDuration' and on setting it to 0, we could disable animations in a chart. Is there any similar property provided in v4?

**Comment by martynasma** [comment]
Simply do not use animated theme. Remove this line:

```
am4core.useTheme(am4themes_animated);
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by VaishnaviAppannagari** [comment]
Thank you. It's working.

**Comment by bhaskerchari** [comment]
Hi @martynasma ,

As you suggested I am not using am4core.useTheme(am4themes_animated); so that it will disable all animations of all charts. 

Not including am4core.useTheme(am4themes_animated);  can I consider AmCharts will never request or make a call for request animation frame? But as I have tested its not the case with me as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/5499784/50740342-16efbe80-1213-11e9-90a8-ef6b573cd570.png)

![image](https://user-images.githubusercontent.com/5499784/50740284-3cc89380-1212-11e9-8f27-27cb0cdfeb9e.png)

Hi even though the animations are turned off I still see a request being made from AmCharts in Container.js as shown in the above attachments because of which AmChart is spending more time in request animation frame as per the google chrome performance tab stats. It is taking almost 13 seconds for request animation frame. I have no clue why is it requesting eventhough animations are disabled.

![image](https://user-images.githubusercontent.com/5499784/50740367-57e7d300-1213-11e9-96d1-e51849b32a3e.png)

Thanks,
Bhasker

**Comment by martynasma** [comment]
@bhaskerchari raf is used not only for animations. Since amCharts 4 is completely asynchronous and also distributed (large updates are chunked out so that they do not bog down the browser), we rely on raf to do updates in increments.

It also assures that all changes to the configuration are processed together, for example if you change both color and opacity of an object, it won't redraw twice but rather once starting with the next frame.

13 seconds for a chart sounds a lot. If you would like to look into particular chart, please open a separate issue or email us at contact@amcharts.com.

**Comment by bhaskerchari** [comment]
@martynasma , Sure thanks for the information and I will try to create a new one once I am ready with any sample.

Thanks,
Bhasker

**Comment by CalvinNunes** [comment]
Is it possible to disable animations during runtime? 
For example, I want to have the animation at the beggining when the chart is created, but at some point I need to call `invalidateData()` and this time I don't want to use any of animations, (because just some colors are changed in data, so no need to make all animation again).

 How can I do it?

**Comment by russeljo** [comment]
> Is it possible to disable animations during runtime?
> For example, I want to have the animation at the beggining when the chart is created, but at some point I need to call `invalidateData()` and this time I don't want to use any of animations, (because just some colors are changed in data, so no need to make all animation again).
> 
> How can I do it?

This helped me
https://www.amcharts.com/docs/v4/concepts/animations/
