### ISSUE TITLE
Error Duplicate id on changing scrollbar series

### ISSUE THREAD

**Issue by Christian-Adler** [amcharts/amcharts4#1799]
Removing and adding the same series again to the scrollbar results in an duplicate id error.

The remove is from issue #461

Example in this pen:
https://codepen.io/chrisadler/pen/MWWmqxa

**Comment by Christian-Adler** [comment]
By coincidence i got the problem solved.
You also have to remove the labels of the scollbar chart xAxis.

`while (chart.scrollbarX.scrollbarChart.xAxes.length > 1)`
`      chart.scrollbarX.scrollbarChart.xAxes.removeIndex(0);`

**Comment by martynasma** [comment]
Thanks for additional info! We probably need to fix this anyway.

**Comment by martynasma** [comment]
Fixed in [4.7.7](https://github.com/amcharts/amcharts4/releases/tag/4.7.7).

## [4.7.7] - 2019-11-02

### Added
- `NumberFormatter` now supports `numberFormat` in [Intl.DateTimeFormatOptions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) objects. E.g. `chart.numberFormatter.numberFormat = { style: "decimal", minimumFractionDigits: 3 }`. [More info](https://www.amcharts.com/docs/v4/tutorials/formatting-date-time-and-numbers-using-intl-object/).
- New built-in pattern: `CirclePattern`.
- `PictorialStackedSeries` now supports `align`/`valign` settings, allowing controlling its position inside chart container.

### Changed
- Default pattern list in `PatternSet` is expanded and revamped for better look and increased contrast.
- Pattern elements are now centered, so they work better with `rotation`.
- `MapChart` now will shift zoom towards center gradually when zooming out.

### Fixed
- `getIndex()` method of `PatternSet` was always returning current pattern, not particular index.
- Sometimes Export's user-added `"data"` adapter was kicking in before amCharts built-in adapter, causing data edits to be overwritten.
- Built-in adapters (e.g. for export `"data"`) sometimes were being added multiple times.
- Export no longer errors out on pages with missing external CSS files.
- Using `addData()` on `PercentChart` was reusing colors from the beginning for the newly added slices.
- `SliceGrouped` on `PercentSeries` when used on a chart with responsive fetures enabled, could display labels of the hidden slices after chart resize.
- Issue with zooming `DateAxis` with single data item fixed (the single item used to disappear in certain cases).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
