### ISSUE TITLE
XY Cursor with zoomXY: Zooms to the wrong vertical end (inverted target)

### ISSUE THREAD

**Issue by PabloMizzle** [amcharts/amcharts4#1802]
Hi Guys,

the XYCursor with behavior zoomXY targets the wrong side of the chart (vertically).

You can observe that in your own demos, e. g.:
https://www.amcharts.com/demos/xy-error-chart/

For example, try to zoom into the upper right corner. You will end up in the lower right corner and vice versa.

Best,
Pablo

**Comment by martynasma** [comment]
Thank you for bringing this to our attention!

We'll let you know when this is fixed.

**Comment by martynasma** [comment]
Fixed in [4.7.5](https://github.com/amcharts/amcharts4/releases/tag/4.7.5).

## [4.7.5] - 2019-10-26

### Added
- New theme: `microchart`. Automatically adapts all charts for very small containers.
- New theme: `patterns`. Automatically fills `ColumnSeries` and `PercentSeries` with distinctive patterns.
- New object `PatternSet` used in conjunction with `XYChart` or `PercentSeries` to auto-assign distinctive pattern fills.
- New property `patterns` on `XYChart` and `PercentSeries`.

### Changed
- `tooltipX` and `tooltipY` properties now can be set in `Percent` for relative positioning.

### Fixed
- Cursor on all-`ValueAxis` setups and behavior set to "zoomXY" was not working properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by PabloMizzle** [comment]
> Fixed in [4.7.5](https://github.com/amcharts/amcharts4/releases/tag/4.7.5).
> 
> ## [4.7.5] - 2019-10-26
> ### Added
> * New theme: `microchart`. Automatically adapts all charts for very small containers.
> * New theme: `patterns`. Automatically fills `ColumnSeries` and `PercentSeries` with distinctive patterns.
> * New object `PatternSet` used in conjunction with `XYChart` or `PercentSeries` to auto-assign distinctive pattern fills.
> * New property `patterns` on `XYChart` and `PercentSeries`.
> 
> ### Changed
> * `tooltipX` and `tooltipY` properties now can be set in `Percent` for relative positioning.
> 
> ### Fixed
> * Cursor on all-`ValueAxis` setups and behavior set to "zoomXY" was not working properly.
> 
> [Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).
> 
> Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

Thanks @martynasma
