### ISSUE TITLE
Problem with "]" escaping when there is "/" symbol 

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1803]
Example:
https://codepen.io/dmsmaxim/pen/poowypb
![image](https://user-images.githubusercontent.com/15041200/67608082-6d70be00-f78f-11e9-802c-f88d9eed5161.png)
So, as you can see the combination of "]]" and "/" is not processed very well.

**Comment by martynasma** [comment]
Fixed in [4.7.6](https://github.com/amcharts/amcharts4/releases/tag/4.7.6).

## [4.7.6] - 2019-10-29

### Added
- Added more pre-set patterns to `PatternSet`, including one with circles.

### Changed
- Using `patterns` theme will no longer reset Series' colors.
- Using `patterns` theme now respects series' `fillOpacity` setting to set pattern background transparency.

### Fixed
- Formatted strings were being cut off at specific `\]]` character combination.
- `LineSeries` with `RectPattern` for a fill was failing on chart with a legend.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
