### ISSUE TITLE
Click on MapChart background event doesn't fire

### ISSUE THREAD

**Issue by AndTessitore** [amcharts/amcharts4#1805]
I found that hit events on background of a MapChart doesn't work. It doesn't work even on [Countries morphing to pie charts](https://www.amcharts.com/demos/countries-morphing-to-pie-charts/) demo stored on your site. The code used in demo is:

`chart.chartContainer.background.events.on("hit", function () { zoomOut() });`

I'm able to change background color, but when trying to add hit event it doesn't fire at all:

`chart.background.fill = am4core.color("#000000");     chart.background.events.on("hit", function (e) {console.log(e);});
`

**Comment by zeroin** [comment]
Hi,

This happens because Map Chart adds some events to chart.chartContainer background and it's over the main chart background, even it is not visible. So instead of adding events to `chart.background` add them to `chart.chartContainer.background`. Also, as the map has another invisible by default `backgroundSeries` you should also add event listener on this series, as the chartBackground listener will only fire if the user clicks outside the map. Here is a demo:

https://codepen.io/team/amcharts/pen/13fc4668fd38cd073a5f20da2c35269c
