### ISSUE TITLE
SankeyDiagram cuts off top and bottom

### ISSUE THREAD

**Issue by PersonThing** [amcharts/amcharts4#1833]
SankeyDiagram charts seem to cut off vertically on top and bottom.  In minor cases, it just makes it look like labels aren't centered within a link, but in extreme cases, it can hide entire links.

Examples:
https://codepen.io/PersonThingTim/pen/rNNJByo?editors=1000
![image](https://user-images.githubusercontent.com/900715/68090260-28a3f180-fe37-11e9-8531-c0f17815d335.png)

https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Creating_a_Sankey_diagram
![image](https://user-images.githubusercontent.com/900715/68090394-df54a180-fe38-11e9-96d4-25b1d3843b96.png)

If you inspect DOM, you can see the `<g>` tags within the svg are drawn outside the `<div>` and cut off.

I noticed that if I flip the from/to of the data, it doesn't cut things off.  Seems like if the right side is taller, it doesn't cut things off.  But if left side is taller, it does.

**Comment by zeroin** [comment]
It seems this happens when there are links with 0 values, which doesn't make a lot of sense. But of course, it shouldn't happen. We will investigate and fix this in next release.

**Comment by zeroin** [comment]
It's actually not zeroes, it's something else.

**Comment by zeroin** [comment]
Found a bug, will be fixed in next release.

**Comment by PersonThing** [comment]
> It seems this happens when there are links with 0 values, which doesn't make a lot of sense. But of course, it shouldn't happen. We will investigate and fix this in next release.

For what it's worth, I'm using SankeyDiagram to draw relationships between 2 types of orgs.  It's meaningful to show if an org has no connections to orgs of the opposing type.  ChordDiagram works as well, but there's more complexity involved that makes SankeyDiagram make more sense.

**Comment by martynasma** [comment]
Fixed in [4.7.8](https://github.com/amcharts/amcharts4/releases/tag/4.7.8).

## [4.7.8] - 2019-11-05

### Added
- `itemIndex` added to `AxisDataItem`. Shows current index of data item on the axis.

### Changed
- `extremeschanged` is now dispatched by `DateAxis` when the `min`/`max` are animating.

### Fixed
- Setting `maskBullets` on an `XYChart` will toggle on or off bullet masking dynamically.
- In some particular cases some Sankey nodes were drawn out of bounds.
- `behaviorcanceled` event of `ChartCursor` was not being fired.
- Regression plugin was failing when added to Series object that was not yet attached to a Chart.
- JSON config was failing where Label's `text` or `html` properties were being set to percent value.
- Toggling of `DateAxis.skipEmptyPeriods` was not working after the chart was already inited.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
