### ISSUE TITLE
XYChart: Animation missing on update (DateAxis, multiple series with separate data)

### ISSUE THREAD

**Issue by th3ragex** [amcharts/amcharts4#1834]
I have two series in an XYChart and each series has its own data. Both share the same date axis. Updating one series results in a smooth animation moving the line to the left together with the dateaxis. The seconds line doesn't animate, just "jumps" to match the moved date.

Fiddle for testing: http://jsfiddle.net/uv1jc4fd/3/

Adding new data to both series results in the correct behavior of both moving simultaneous.

Is there something i can do to get both series animations?

**Comment by martynasma** [comment]
Fixed in [4.7.8](https://github.com/amcharts/amcharts4/releases/tag/4.7.8).

## [4.7.8] - 2019-11-05

### Added
- `itemIndex` added to `AxisDataItem`. Shows current index of data item on the axis.

### Changed
- `extremeschanged` is now dispatched by `DateAxis` when the `min`/`max` are animating.

### Fixed
- Setting `maskBullets` on an `XYChart` will toggle on or off bullet masking dynamically.
- In some particular cases some Sankey nodes were drawn out of bounds.
- `behaviorcanceled` event of `ChartCursor` was not being fired.
- Regression plugin was failing when added to Series object that was not yet attached to a Chart.
- JSON config was failing where Label's `text` or `html` properties were being set to percent value.
- Toggling of `DateAxis.skipEmptyPeriods` was not working after the chart was already inited.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
