### ISSUE TITLE
Percent value cannot be set as label text/html

### ISSUE THREAD

**Issue by andykno** [amcharts/amcharts4#1836]
A percent value (e.g. "100%") cannot be set as text or html of a label. 

An error occurs: 
> Expected a string or number but got [object Object]

Example:
```
var chart = am4core.createFromConfig(
  { 
    "text":"100%",       //Error!
    //"html":"100%",     //Error!
    //"text":"100 %",    //Ok
    "fontSize":30,
    "type":"Label"
  }
 , "chartdiv" );
```
https://codepen.io/AndYpsilon0/pen/KKKQqyj

**Comment by martynasma** [comment]
Fixed in [4.7.8](https://github.com/amcharts/amcharts4/releases/tag/4.7.8).

## [4.7.8] - 2019-11-05

### Added
- `itemIndex` added to `AxisDataItem`. Shows current index of data item on the axis.

### Changed
- `extremeschanged` is now dispatched by `DateAxis` when the `min`/`max` are animating.

### Fixed
- Setting `maskBullets` on an `XYChart` will toggle on or off bullet masking dynamically.
- In some particular cases some Sankey nodes were drawn out of bounds.
- `behaviorcanceled` event of `ChartCursor` was not being fired.
- Regression plugin was failing when added to Series object that was not yet attached to a Chart.
- JSON config was failing where Label's `text` or `html` properties were being set to percent value.
- Toggling of `DateAxis.skipEmptyPeriods` was not working after the chart was already inited.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
