### ISSUE TITLE
Stacked radar chart will not auto scale if the series is pre-hided

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#184]
![image](https://user-images.githubusercontent.com/33080381/43433595-12b6be72-9446-11e8-9453-dee55166cf31.png)
![image](https://user-images.githubusercontent.com/33080381/43433616-23c98366-9446-11e8-8c28-8dc39acc1df8.png)
there are 3 series, the pre-hided series will not auto-scale after showing by selecting legend. Also, have some issue with the first one, will only auto-scale after hide/show action.
the code is here
http://jsfiddle.net/shichenglu/4jfbzua1/

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.40](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.40).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
