### ISSUE TITLE
Do not display an empty tooltip on XYChart with no cursor and tooltipText set on series

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#185]
When creating an `XYChart` with a category axis and adding a non-default `tooltipText` to the series, the chart will display an empty cursor centered in the chart when hovering over any element. As soon as an `XYCursor` is created, the behavior is as expected.
The issue also doesn't affect a chart with a date axis instead of a category axis.

You can see the issue here: https://codepen.io/chnoch/pen/xJYbqZ

**Comment by martynasma** [comment]
OK, so with series tooltips there are these rules of thumb:

1) If you have a cursor, set `tooltipText` directly on series.
2) If you don't have a cursor, set `tooltipText` on some element of the series.

For the latter, it depends on the type of series. For `ColumnSeries` like in your pen, `series.columns.template` seems perfect.

That said, I agree that displaying an awkward empty tooltip if there's no cursor and `tooltipText` is set directly on series is not cool. So we'll need to give it some thought, how maybe we can avoid that.

Thanks!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.41](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.41).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
