### ISSUE TITLE
Align namelabels to left or right Sankey diagram

### ISSUE THREAD

**Issue by marjukas** [amcharts/amcharts4#1869]
Hello,

we would need to align the namelabels of Sankey nodes on the rightmost nodes so that they would be positioned left of the node, but aligned right.

We have tried horizontalCenter and label.textAlign, but neither of them is giving the needed effect.

Please see picture below - the labes should be aligned to the red line. 

![Alignment issue](https://user-images.githubusercontent.com/35274613/68577546-fcacef80-0478-11ea-8b13-398bd1cee50d.jpeg)

**Comment by zeroin** [comment]
It's a bit complicated, you must set:
```
nodeTemplate.nameLabel.horizontalCenter = "right";
nodeTemplate.nameLabel.label.horizontalCenter = "right";
nodeTemplate.nameLabel.label.textAlign = "end";
nodeTemplate.nameLabel.label.truncate = false;
nodeTemplate.nameLabel.width = undefined;
```
https://codepen.io/team/amcharts/pen/8f456c206bf68a9866dc8c3c3ac57626

**Comment by marjukas** [comment]
Hello,

Thanks for the answer! It works to make all labels on all levels like this. 

But there is another complexity - our chart has 3 levels of nodes and it should be aligned differently on levels 1 and 3 to make it look symmetrical.. 

The third level should be aligned as described above. The first one should have labels to the right of the node and aligned left. So they would be "same but the other way around".

Is this possible?

**Comment by martynasma** [comment]
You may need to create adapters for those labels:

```
nodeTemplate.nameLabel.width = undefined;
nodeTemplate.nameLabel.adapter.add("horizontalCenter", function(center, target) {
  if (target.parent.level == 3) {
    target.horizontalCenter = "right";
    target.label.horizontalCenter = "right";
    target.label.textAlign = "end";
    target.label.truncate = false;
    return "right";
  }
  return center;
});
```

https://codepen.io/team/amcharts/pen/ZEEqXMQ

**Comment by marjukas** [comment]
Thank you, this works!

**Comment by OGudkov-TechHub** [comment]
Hi,

I know, this issue is closed already, but it looks like the proposed [solution](https://github.com/amcharts/amcharts4/issues/1869#issuecomment-553805963) has got some flaws. I don't want to produce duplicates so let me write my questions here.

First of all, the string `target.label.truncate = false;` has to be written outside of `if`. Otherwise, any label longer than a single character on any level except 3rd will be truncated. For example if the 1st item (from the above codepen sample) has got label "Another label" - it will be rendered as "A...".

Next thing is that the positioning of any label for 3rd level will be changed (or reset to default) if a corresponding node, or a parent node will be switched OFF. It also won't be restored after switching it ON again.

Are they any solutions for these things? Thanks in advance!

**Comment by OGudkov-TechHub** [comment]
> Hi,
> 
> First of all, the string `target.label.truncate = false;` has to be written outside of `if`. Otherwise, any label longer than a single character on any level except 3rd will be truncated. For example if the 1st item (from the above codepen sample) has got label "Another label" - it will be rendered as "A...".

[Here](https://www.amcharts.com/docs/v4/tutorials/handling-long-sankey-labels/#Wrapping_labels) I found the proper solution, as I think.
