### ISSUE TITLE
Replacing the whole dataset with less elements than before gives an error

### ISSUE THREAD

**Issue by jochenjonc** [amcharts/amcharts4#187]
Hi,

When replacing the data of a chart with a dataset that has the same or more elements the charts is updated as it should be, including an animation.
But when I update the data of a chart with less elements than before it get the following error: Cannot read property 'values' of undefined.

I made a [StackBlitz](https://stackblitz.com/edit/angular-amcharts-remove-bug) that demonstrates the issue. Click on Add first and then on Remove.

Hope it can be fixed, because my only solution for now is to re-initialize the chart completely.

Regards,

Jochen

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.40](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.40).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
