### ISSUE TITLE
Label.text = null causes "Cannot read property 'toString' of null" error

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1870]
Example:
https://codepen.io/dmsmaxim/pen/jOOpaxY
![image](https://user-images.githubusercontent.com/15041200/68586086-887c4700-048c-11ea-85f1-9a78ef16ee76.png)
I think it's wrong behavior. `null` shouldn't cause such a problem...

**Comment by martynasma** [comment]
I disagree. `Label.text` expects a string, and `null` is not a string.

You can set it to `undefined` or an empty string to indicated there's no text, but `null` is something else.

**Comment by balaji9124** [comment]
Hi @martynasma 

As per JavaScript, programmatically  `null == undefined`, which returns true, but `"" == undefined` returns false which shows that null and undefined both representing the value is empty or unavailable . As AMCharts is also a JavaScript library, It is expected to perform a universal value validation rather than restricting it to a type. 

Thanks
