### ISSUE TITLE
Sankey diagram link stroke and controlPointDistance appearance

### ISSUE THREAD

**Issue by marjukas** [amcharts/amcharts4#1898]
Hello,

when we set stroke on Sankey diagram links the strokes go over the end of links and are visible there. 
This seems to be connected to controlPointDistance property - if we set controlPointDistance smaller (then the shape of links is better), the length of strokes gets longer and they get more visible.
Is there any way to avoid the strokes going longer, but the shape of the links stays like with small controlPointDistance value?

![image](https://user-images.githubusercontent.com/35274613/69139561-6ce6f100-0ac9-11ea-88bb-4c653ac13729.png)

**Comment by martynasma** [comment]
Indeed, smaller `controlPointDistance` generates overflowing strokes.

We'll see if it is possible to fix.

Here's a working test subject:
https://codepen.io/team/amcharts/pen/ef32374c46bdae913c282ec431b6116f?editors=0010

**Comment by martynasma** [comment]
This seems to not be a bug. Small `controlPointDistance` values do not because of the `tensionX` setting.

If you need to use small control point distance, you also need to reduce `tensionX`.

The following will produce perfectly straight lines with correct strokes:

```JavaScript
chart.links.template.controlPointDistance = 0;
chart.links.template.tension = 1;
```

This is mentioned in the docs BTW:
https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Basic_configuration
