### ISSUE TITLE
Unexpected colour behaviour for pie charts

### ISSUE THREAD

**Issue by Venlious** [amcharts/amcharts4#1916]
I recently updated to the latest amCharts version and stumbled upon some unexpected behaviour when it comes to setting a colour list for PieCharts.

I have looked into the documentation for the [ColorSet here](https://www.amcharts.com/docs/v4/reference/colorset/), but have been unsuccessful in resolving this issue. It worked perfectly fine in the older version, but has since stopped functioning as expected.

Please see Codepen showcasing this issue: [https://codepen.io/venlious/pen/abbraWN](https://codepen.io/venlious/pen/abbraWN)

You can repeat the issue by changing the imported amCharts version. You'll see that the colours do not show up as expected.

**Comment by martynasma** [comment]
Fixed in [4.7.11](https://github.com/amcharts/amcharts4/releases/tag/4.7.11).

## [4.7.11] - 2019-11-26

### Fixed
- Visual glitch with `ColumnSeries3D` used in a stacked axis scenario fixed.
- `PercentSeries` was sometimes jumping over 2 colors in `ColorSet`.
- Fixed possible compilation issues with some configurations.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
