### ISSUE TITLE
Zoom/Panning for Force Directed Graph

### ISSUE THREAD

**Issue by JGoodwin-DS** [amcharts/amcharts4#1919]
Is there a way to get this to work or is there an enhancement in place for implementing these features?  Being able to zoom into a subsection of a large FDG or out to see more relations would be extremely useful.

**Comment by martynasma** [comment]
We actually do have this feature under consideration. If something happens, we'll let you know.

**Comment by mcverticchio** [comment]
Do you have any updates on whether this feature will be added?

**Comment by martynasma** [comment]
> Do you have any updates on whether this feature will be added?

No at this time, I'm afraid. No development or additional decision have been made from the time this issue was created. Sorry.

**Comment by lancegliser** [comment]
I might be able to set a developer into this task. Could you give me a rough outline of the steps you expect it requires and a time line if you were doing it?

I know there is map zoom already. Hoping this might be a port level of effort.

**Comment by zeroin** [comment]
I am sorry but proper guidance on how to implement this would take us even more time than to make it by ourselves. I am afraid we can not provide it at the moment. I've already spend quite a time trying to implement it and faced some problems so postponed it for some time. We will be coming to it, most likely during next month.

**Comment by martynasma** [comment]
Fixed in [4.10.0](https://github.com/amcharts/amcharts4/releases/tag/4.10.0).

## [4.10.0] - 2020-09-01

### Added
- New `LineSeries` property: `smoothing` (`"bezier"` (default), `"monotoneX"`, and `"monotoneY"`) - indicates algorithm to use for smoothing the lines. Monotone algos are better suited for irregularly-spaced data. [More info](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Alternate_smoothing_algorithm).
- `ForcedDirectedTree`: new property `zoomable` (default: `false`). If set to `true`, the chart will be zoomable/draggable using mouse, touch, or API. [More information](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming).
- `ForcedDirectedTree`: zoom related properties added. `mouseWheelBehavior` (`"zoom"`, `"none"`) - controls what happens when mouse wheel is used over chart; `zoomStep` (default: `2`) - step to increase zoom level my each zoom in; `zoomOutButton` - an instance of button which is shown when chart is zoomed in.
- `ForcedDirectedTree`: new zoom-related methods: `zoomToPoint(point, level, center)` and `zoomToDataItem(dataItem, level, center)`;
- New global function: `am4core.createDeferred(callback, scope, ...parameters)`. Can be used to create multiple charts in a truly safe daisy-chain (next chart starts to be instantiated only when previous triggers a `ready` event). Returns a `Promise` with chart instance. [More information](https://www.amcharts.com/docs/v4/concepts/performance/#Deferred_daisy_chained_instantiation);
- New global option: `am4core.options.deferredDelay` (default `100`). Specifies time-gap in milliseconds between deferred chart instantiations.

### Changed
- Added date ordinal translations for Chinese locales.

### Fixed
- Accessibility: `readerTitle` was not being properly populated with data on `Label`.
- Accessibility: `readerDescription` was not being populated with data.
- Now works with Angular Universal SSR. Please refer to our [Angular doc](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) for instructions on how to structure your app for SSR to work properly.
- When `MapChart` was panned with inertia and a polygon with `zoomToObject()` hit event was clicked when the map was still moving, the map was zooming into a wrong position.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
