### ISSUE TITLE
¿Popups on Links?

### ISSUE THREAD

**Issue by JFLopez7** [amcharts/amcharts4#1933]
Hi,

I have a question about popups in forced-directed trees, i'm trying to put unique popus for the links between nodes but it seems that you can only put popups on nodes... is there a way to do this? or is it really limited to the nodes?

Thanks in advance!

**Comment by zeroin** [comment]
I confirm this is a bug, it will be fixed in next update.

**Comment by martynasma** [comment]
Fixed in [4.7.15](https://github.com/amcharts/amcharts4/releases/tag/4.7.15).

## [4.7.15] - 2019-12-16

### Added
- `notAllowed` added to [`MouseCursorStyle`](https://www.amcharts.com/docs/v4/reference/mousecursorstyle/).
- `PieSeries`, `FunnelSerries`, `PyramidSeries`, and `PictorialStackedSeries` will now use absolute values for their slices (good if you have negative values).
- [`positionToCoordinate()`](https://www.amcharts.com/docs/v4/reference/axis/#positionToCoordinate_method) method added to `Axis`.
- Added `index` as second parameter to [`List.each()`](https://www.amcharts.com/docs/v4/reference/list/#each_method) method.
- `min` and `max` adapters added to `ValueAxis`.

### Changed
- Icons in `ExportMenu` now have `box-sizing: border-box` set in default CSS to make icons play nice(er) with external CSS.
- Popup now has a tiny strip on top of it which can be used to drag it (much like regular windows in your OS), instead of the whole body of popup being draggable.
- Popup will now use theme colors for backgrounds/text.

### Fixed
- The `List.each` method was missing an `index` argument for the callback.
- Links and other interactive elements in popups are now clickable.
- Labels in `PieSeries` could sometimes overlap if animated theme was not used.
- `DateAxis` with `groupData = true` and `"average"` as group field was now shown properly if data had gaps.
- `AxisRendererRadial` (`RadarChart` uses it) was not paying attention to `tick.location` property.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
