### ISSUE TITLE
keep XYChartScrollbar  chart unchanged when valueAxis changes

### ISSUE THREAD

**Issue by Muzzamil1** [amcharts/amcharts4#1935]
Hi! 
If I change min and max values in valueAxis the chart in XYChartScrollbar also changes.
Here is what I mean
**Before setting the` valueAxis.min` and `valueAxis.max`**

![before](https://user-images.githubusercontent.com/53085438/69897294-edc8a700-136b-11ea-97de-9d19a4630e70.PNG)

**After**
![After](https://user-images.githubusercontent.com/53085438/69897298-033dd100-136c-11ea-9960-6c099e08973a.PNG)

Is it possible to keep the XYChartScrollbar chart unchanged? 
What I did is that I created a new series with new value Axis and, pass it to the XYChartScrollbar and then I have to hide the 2nd series's chart, legend, and valueAxis.

```
                let valueAxis2 = chart.yAxes.push(new am4charts.ValueAxis());
                let series2 = char.series.push(new am4charts.LineSeries());
                series2.dataFields.valueY = "value";
                series2.dataFields.categoryX = "dateTime";
                series2.yAxis = valueAxis2;

                chart.scrollbarX.series.push(series2);               
                series2.hidden = true;
                series2.hiddenInLegend = true;
                valueAxis2.disabled = true;
```
Is there any shortcut?

**Comment by zeroin** [comment]
I am afraid there is no a straightforward way to do that, only with some workaround:
https://codepen.io/team/amcharts/pen/3200312c55714e6f5b22c00310ae93f2?editors=0010

Scrollbar value axis listens for the extremeschanged event and if min and max values are defined by user, updates it's own axis to use the same min/max. So I save old values and when set them again, but do that on exitframe, otherwise it won't work.

Another option would be not to use defined min/max but zoom your original value axis to the desired values, but I am not sure if this solution is ok for you.

**Comment by Muzzamil1** [comment]
Thanks for the reply 👍.
I will try your solutions.

**Comment by Muzzamil1** [comment]
Thanks, The codepen solution worked 👍
