### ISSUE TITLE
Improve Documentation: Indicate full syntaxis/Class

### ISSUE THREAD

**Issue by tomasts248** [amcharts/amcharts4#1937]
For example instead of only listing the name of the property, why not indicating the full line? Instead of "fill" for example for a tooltip, indicate display series.tooltip.background.fill = am4core.color("white");
since classes are different and are not obvious, I have had to google most of them using previous questions and then trying them blindly. Another example: "shiftRadius" is listed but how I'm supposed to know how to apply it? Maybe I'm overlooking something?
Regards!

**Comment by steve3d** [comment]
well, same for me here. The doc are really confusing.

**Comment by martynasma** [comment]
While it makes sense to have as much usage examples as possible, it would be a bit overwhelming to have those for each possible property, if not outright misleading.

A lot of properties are being inherited, like for example `maxWidth` which is available on both `Sprite` (basic element) and inherited down to `ValueAxis`. Which example should it show?

While I agree that more examples would be good, I suggest to look up specific topic in documentation, for possible commentary and guidance, as well as tutorials, rather than relying solely on classref.

I'm going to go ahead and close this, since there's little I can add to the topic.
