### ISSUE TITLE
Issue with Gradient fill 

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#194]
Hello,

I am trying to fill the columns of a chart with customized gradient using linear gradient's element property.

I want to fill the gradient in such a way that it demonstrates the column value i.e. if value is lower it should be filled with red and if higher then the fill should be green.
I am able to achieve this requirement for horizontal chart successfully, but not in case of vertical chart.

Following is the code pen demonstrating the same:

https://codepen.io/team/amcharts/pen/oMqvOP?editors=0010

**Comment by martynasma** [comment]
Something like this?

https://codepen.io/team/amcharts/pen/OwZyLY?editors=0010

We are using an adapter on `series.column.template` to dynamically create an appropriate `LinearGradient` instance based on actual data:

```
series.columns.template.adapter.add("fill", function(fill, target) {
  var data = target.dataItem.dataContext;
  var gradient = new am4core.LinearGradient();
  gradient.addColor(am4core.color("#000"));
  if (data.value >= data.target) {
    gradient.addColor(am4core.color("#2EC4B6"));
  }
  else {
    gradient.addColor(am4core.color("#DA3E52"));
  }
  return gradient;
});
```

Hope it helps.

**Comment by VaishnaviAppannagari** [comment]
I am actually trying to achieve something like the following pen:

https://codepen.io/anon/pen/NBMxGg?editors=0010

**Comment by martynasma** [comment]
I'm not entirely sure what's going on here in your code?

```
var group = new am4core.Group('gradient');
var verticalGradient = new am4core.LinearGradient();
verticalGradient.element = group;
verticalGradient.id = 'gradient';

var group1 = new am4core.Group('gradient2');
var horizontalGradient = new am4core.LinearGradient();
horizontalGradient.element = group;
horizontalGradient.id = 'gradient2';
```

Proper way to create gradients is this:

```
var verticalGradient = new am4core.LinearGradient();
verticalGradient.addColor(am4core.color("#f00"));
verticalGradient.addColor(am4core.color("#0f0"));
verticalGradient.rotation = 90;

var horizontalGradient = new am4core.LinearGradient();
horizontalGradient.addColor(am4core.color("#f00"));
horizontalGradient.addColor(am4core.color("#0f0"));
```

https://codepen.io/team/amcharts/pen/713a1ea20cfc348c1eecace3c38521ca/

**Comment by Varshamathukumalli** [comment]
@martynasma ,

Probably what she has mentioned in this url: https://codepen.io/varshamathukumalli/pen/QBrEBd?editors=1000 
is she wanted to use a gradient which they have created using svg as:

 <linearGradient id="gradient" x1="0" x2="0" y2="100%"  y1="0"  gradientUnits="userSpaceOnUse" width="100%" height="100%"> 
    <stop offset="0.1" stop-color="rgb(100, 188, 97)"></stop>
    <stop offset="0.4" stop-color="rgb(252, 172, 99)"></stop>
    <stop offset="0.7" stop-color="rgb(212, 50, 44)"></stop>
</linearGradient>

Now she is using this gradient's id in her code to amcharts gradient object.
And from the sample, what i understood is the gradient is working fine in horizontal case where it is plotting  from red to orange in the second horizontal graph.
But in the vertical case instead of plotting from red to green, in the 2nd vertical graph it is displaying green color which is misinterpreted.

Regards,
Varsha

**Comment by martynasma** [comment]
Sooooo, are we all set, or is there something not working?

P.S. I still have no idea what that code does, or why it's even working at all :)

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
