### ISSUE TITLE
AMChartsV4 slower seems 100% slower to initialise than V3

### ISSUE THREAD

**Issue by ptimson** [amcharts/amcharts4#1965]
Hey,

Am trying to use V4 but seems a lot slower to initialise than V3. I tried to put an example here:
https://codepen.io/ptimson/pen/QWwNZRp

But it seems to take double the amount of time to render.

Basically we are trying to show a graph for different country values for the last 3 years. Is there anyway to improve the performance to bring down the initial render time for V4 to make it more inline with V3? I tried a bunch of things suggested in https://www.amcharts.com/docs/v4/concepts/performance/ with little difference noticed.

Thanks

**Comment by zeroin** [comment]
Well yes, version 4 is a lot more complex because of all the possibilities. So I agree, the initial rendering is slower. In your case I would suggest considering data grouping, it should make things faster. Here is a chart with 50K data points: https://www.amcharts.com/demos/data-grouping-50k-points/ and grouping enabled.
