### ISSUE TITLE
GroupData and multiple series problem

### ISSUE THREAD

**Issue by borodiliz** [amcharts/amcharts4#1967]
Hi!

I am having problems trying to use `groupData` + `groupFields.valueY = "average"` + multiple series.

It seems that if a series has no data on a given interval, the average value is `NaN` (and a 0 is represented)

In the following example, one serie has 5k points and another only 500 points

Setting `dateAxis.groupData = true;`

<img width="990" alt="Captura de pantalla 2019-12-11 a las 21 35 59" src="https://user-images.githubusercontent.com/2467193/70658495-65e17780-1c5e-11ea-97d7-7f02f6b2921a.png">

Setting `dateAxis.groupData = false;`

<img width="987" alt="Captura de pantalla 2019-12-11 a las 21 36 20" src="https://user-images.githubusercontent.com/2467193/70658487-611cc380-1c5e-11ea-8a0c-00fd9815dc84.png">

https://codepen.io/borodiliz/pen/WNbxewN

Thanks in advance!

**Comment by zeroin** [comment]
I confirm it's a bug on our side. I fixed it on dev and will soon release an update with a fix. Thank you for helping to find this bug.

**Comment by martynasma** [comment]
Fixed in [4.7.15](https://github.com/amcharts/amcharts4/releases/tag/4.7.15).

## [4.7.15] - 2019-12-16

### Added
- `notAllowed` added to [`MouseCursorStyle`](https://www.amcharts.com/docs/v4/reference/mousecursorstyle/).
- `PieSeries`, `FunnelSerries`, `PyramidSeries`, and `PictorialStackedSeries` will now use absolute values for their slices (good if you have negative values).
- [`positionToCoordinate()`](https://www.amcharts.com/docs/v4/reference/axis/#positionToCoordinate_method) method added to `Axis`.
- Added `index` as second parameter to [`List.each()`](https://www.amcharts.com/docs/v4/reference/list/#each_method) method.
- `min` and `max` adapters added to `ValueAxis`.

### Changed
- Icons in `ExportMenu` now have `box-sizing: border-box` set in default CSS to make icons play nice(er) with external CSS.
- Popup now has a tiny strip on top of it which can be used to drag it (much like regular windows in your OS), instead of the whole body of popup being draggable.
- Popup will now use theme colors for backgrounds/text.

### Fixed
- The `List.each` method was missing an `index` argument for the callback.
- Links and other interactive elements in popups are now clickable.
- Labels in `PieSeries` could sometimes overlap if animated theme was not used.
- `DateAxis` with `groupData = true` and `"average"` as group field was now shown properly if data had gaps.
- `AxisRendererRadial` (`RadarChart` uses it) was not paying attention to `tick.location` property.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
