### ISSUE TITLE
Question: How to trigger cursor move without triggering also `cursorpositionchanged`

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#1977]
Hi I am trying to programmticaly share the cursor position via more than on component. 

When the cursor position changes from another component I trigger the cursor move like this 

```
              this.chart.cursor.triggerMove((<am4charts.DateAxis>xAxis).dateToPoint(new Date(cursor.time)), 'soft');

```

I also want to listen to the chart cursor position changing to update the other component. 

For that I listen to 

```
   chart.cursor.events.on('cursorpositionchanged', (event) => {
```

But as you can imagine when the programmtical change happens from another component with triggerMove it also triggers the cursorpositionchanged event. 

How can one avoid this?

**Comment by zeroin** [comment]
Well, I could recommend to turn off these events by calling
`chart.cursor.events.off("cursorpositionchanged");`
and then reenable them
`chart.cursor.events.on("cursorpositionchanged");`

But as we use it internally, this most likely will cause the tooltips not to appear on the chart.
So I believe you should use some your own custom flags in order to solve this.
