### ISSUE TITLE
Language in multi-panel-chart does not work for scrollbar

### ISSUE THREAD

**Issue by WeeSKee** [amcharts/amcharts4#1980]
Hi,
setting the language for a multi-panel-chart work in the bottom legend but not in the scrollbar.
You can see my example, with french language : https://jsfiddle.net/ya03tqkh/
In the bottom legend, we have the month 'Mai' but in the scrollbar we have 'May'.
Did i miss something or a bug ?

Thanks everyone

**Comment by martynasma** [comment]
Seems like `XYChartScrollbar` is not inheriting chart's locale. It's a bug.

Will let you know when it's fixed.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.7.16](https://github.com/amcharts/amcharts4/releases/tag/4.7.16).

## [4.7.16] - 2019-12-18

### Added
- `hideTooltipWhileZooming` (default `true`) property added to `XYSeries` and `Axis`. It will hide respective tooltips while chart zoom animation is playing.
- `customValue` data field added to `XYSeries`. Useful if you want to show (in a tooltip for example) some custom value when data is grouped and you need an aggregated numeric value that is not other than one of the Series' data fields.
- All the custom fields from chart's raw data are copied into grouped data item's `dataContext`. This allows referencing to custom fields via text placeholders even in aggregate data items when data grouping is enabled.

### Changed
- Accessibility: Default `role` for chart changed to `region`.

### Fixed
- Accessibility: `Scrollbar` and its elements now set required attributes like `aria-orientation`, `aria-controls`, `aria-valuenow`, `aria-valuetext`, `aria-valuemin`, and `aria-valuemax`.
- Annotation plugin: The elements that went outside of the chart area were not being properly clipped.
- `XYChartScrollbar` was not inheriting locale from parent chart.
- Sometimes grid lines (and some other lines) were blurry.
- Tooltips of an `XYChart` with stacked axes could be positioned incorrectly.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
