### ISSUE TITLE
Map chart's zoom out of Zoom control function won't follow the current map center

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#1982]
while the zoom in function works just fine, they both worked fine several versions before, not sure since which version the zoom out function doesn't work well.

**Comment by zeroin** [comment]
Could you try to set:
`chart.centerMapOnZoomOut = false;`
We added this auto-center thing because a lot of people were complaining the map wen out of bounds when zooming out.

**Comment by shichenglu** [comment]
it does work. this auto center function is great for zomLevel<2 or 4, but if the map is zoomed in by 8 or 16, auto center will make user lost position easily.

**Comment by zeroin** [comment]
I agree, I think I will adjust code to center map only when zoom-level is low. Thanks!

**Comment by martynasma** [comment]
Fixed in [4.7.17](https://github.com/amcharts/amcharts4/releases/tag/4.7.17).

## [4.7.17] - 2019-12-22

### Added
- `maskBullets` added to `XYSeries` for a possibility to set it on individual series rather on all chart.

### Changed
- Changed `am4core.type.is` to `am4core.is`. This fixes a circular dependency issue.
- `centerMapOnZoomOut` of `MapChart` will kick in on `zoomLevel < 1.5` for a better UX.

### Fixed
- Mouse wheel behavior on `XYChart` improved.
- Stacked series of a chart with multiple `ValueAxis` were not properly sorted.
- Some issues with hiding tooltips while chart is zooming fixed.
- Chart with rotated axis labels of Y axis could go into SO in some rare cases.
- `SankeyDiagram` with a single level and animated theme was not displaying links.
- Some min/max issues with grouped data on `DateAxis` fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
