### ISSUE TITLE
Bug with label display on treemap

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#1986]
I noticed there is a bug when deselecting a legend item associated with a treemap: the labels are displaced instead of disappearing.

![treemap-whole](https://user-images.githubusercontent.com/44207487/71102634-1bf61580-21b9-11ea-9452-bf15fa95f943.png)
![bug-treemap](https://user-images.githubusercontent.com/44207487/71102638-1e586f80-21b9-11ea-80da-1a172a9af4a4.png)

Here's a [codepen](https://codepen.io/segolene-albouy/pen/mdyRxEz)

thank you!

**Comment by martynasma** [comment]
Fixed in [4.7.17](https://github.com/amcharts/amcharts4/releases/tag/4.7.17).

## [4.7.17] - 2019-12-22

### Added
- `maskBullets` added to `XYSeries` for a possibility to set it on individual series rather on all chart.

### Changed
- Changed `am4core.type.is` to `am4core.is`. This fixes a circular dependency issue.
- `centerMapOnZoomOut` of `MapChart` will kick in on `zoomLevel < 1.5` for a better UX.

### Fixed
- Mouse wheel behavior on `XYChart` improved.
- Stacked series of a chart with multiple `ValueAxis` were not properly sorted.
- Some issues with hiding tooltips while chart is zooming fixed.
- Chart with rotated axis labels of Y axis could go into SO in some rare cases.
- `SankeyDiagram` with a single level and animated theme was not displaying links.
- Some min/max issues with grouped data on `DateAxis` fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
