### ISSUE TITLE
Wrong one-ended links appearance when the animated theme is applied

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#1993]
Example:
https://codepen.io/dmsmaxim/pen/OJPpqwq?editors=1010
![image](https://user-images.githubusercontent.com/15041200/71296667-151dfd00-2389-11ea-8541-4f200af3e6ea.png)
Disable animated theme:
![image](https://user-images.githubusercontent.com/15041200/71296718-44cd0500-2389-11ea-90bc-7d50b63c082f.png)

**Comment by martynasma** [comment]
Fixed in [4.7.17](https://github.com/amcharts/amcharts4/releases/tag/4.7.17).

## [4.7.17] - 2019-12-22

### Added
- `maskBullets` added to `XYSeries` for a possibility to set it on individual series rather on all chart.

### Changed
- Changed `am4core.type.is` to `am4core.is`. This fixes a circular dependency issue.
- `centerMapOnZoomOut` of `MapChart` will kick in on `zoomLevel < 1.5` for a better UX.

### Fixed
- Mouse wheel behavior on `XYChart` improved.
- Stacked series of a chart with multiple `ValueAxis` were not properly sorted.
- Some issues with hiding tooltips while chart is zooming fixed.
- Chart with rotated axis labels of Y axis could go into SO in some rare cases.
- `SankeyDiagram` with a single level and animated theme was not displaying links.
- Some min/max issues with grouped data on `DateAxis` fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
