### ISSUE TITLE
multiple ValueAxis with strictMinMax will effect hover tooltip show up

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#200]
The hover tooltip won't show up on the entire bar (only part of the bar can active the hover tooltip) after I create multiple ValueAxis, even those valueAxis are not assigned to any data. Remove those valueAxis or remove the strictMinMax setting can solve this issue, somehow different valueAxis with different strictMinMax value get conflict. Here is the code:
https://jsfiddle.net/shichenglu/eLgdqo50/

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.43](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.43).

## [4.0.0-beta.43] - 2018-08-12

### Changed
- `$net.load()` options parameter now supports `responseType`. If set to `"blob"` will return response as `Blob` object in `result.blob`.

### Fixed
- Value axis min/max calculation algorithm adjusted. Fixed an issue with `strictMinMax = true` and issue with min/max when axis size was very small.
- Export now correctly uses external fonts included via `@import`, such as Google Fonts.
- Non-clickable columns in `ColumnSeries` will no longer gain focus on click/tap, unless its `hitOptions.noFocus` is set to `false`.
- Noon was incorrectly formatted as "AM", instead of "PM".
- `TextFormatter` was producing invalid `style` value on empty formatting blocks (`"[]"`).
- `parent` was not being set for a `Sprite` that was pushed directly to `Container.children`.
- If axis labels were disabled, ranges labels were not visible.
- Axis used to reset some of the user-set values when initing renderer, e.g. `dateAxis.renderer.grid.template.location = 0.5` was not working.
- `XYChart` with category axis + date axis was not working properly.
- Stacked chart with logarithmic axis was not working properly.
- JSON: local formatter instances were not being instantiated properly, so all children objects were reusing chart's main formatters.
- JSON: Patterns are now supported.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
