### ISSUE TITLE
Example folder inside node_modules

### ISSUE THREAD

**Issue by supoved** [amcharts/amcharts4#2004]
1. I would not expect it too be there in the first place, it should be in the source code but excluded from packaging into a node module
2. We are using react-scripts that have webpack with it's config built in. I can see that it does compiled  the whole examples folder into production code. 

So anyone who will use am_charts 4.7.10 with default react will have all the examples in production.

**Comment by Pauan** [comment]
We intentionally put the examples into the npm package so that way they are easily accessible for our users. This has no impact on your code, since the examples are not included in the final bundle.

I just now followed [our React tutorial](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/) with React version 16.12.0 and amCharts version 4.7.18. When doing a release build, it does ***not*** include the examples in the `build` folder.

If the examples are being included in your `build` folder, then there is something wrong with your setup. Could you please show your `webpack.config.js` file?
