### ISSUE TITLE
Grouping discarded if dataset is updated

### ISSUE THREAD

**Issue by pyr0hu** [amcharts/amcharts4#2006]
Hello!

I used the grouping feature to reduce the visible points in my chart, which is working correctly. The data set as `chart.data = [...]`. If I update the data with another assignment `chart.data = newData;` the group is discarded and all points are visible. Tried to call `invalidateData` or `invalidateRawData`, neither regrouped the new array. Interestingly, if in the initial setup, I set the data on the series as `series.data = [...]` it is not grouped by default.

**Comment by martynasma** [comment]
Do you have an example?

I tried replacing `chart.data` on a simple chart with `groupData` enabled and the new data is grouped properly.

https://codepen.io/team/amcharts/pen/372352b282fa45b4a012260dd25ae639?editors=0010

**Comment by pyr0hu** [comment]
Sure. I used Vue as in my project. If you click "regenerate", the grouping is discarded, and it feels like Vue is regenerating the whole chart, not sure why.

https://codepen.io/pyr0hu/pen/bGNYKXp

**Comment by pyr0hu** [comment]
UPDATE: found out, that if I comment out the baseInterval stuff when initializing the chart, the reload works correctly

**Comment by martynasma** [comment]
Fixed in [4.7.20](https://github.com/amcharts/amcharts4/releases/tag/4.7.20).

## [4.7.20] - 2020-01-08

### Fixed
- Changing data for a chart with `DateAxis` and `groupData = true` and custom `baseInterval` was resulting the grouping not to working.
- Changing colors and some other visual properties of a series after the chart was inited was not affecting `LineSeries` and `ColumnSeries`, as well as their legend markers.
- Sometimes the active tooltip of the chart was hidden even though it should remain visible (if some other sprite was hidden at the moment).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by pyr0hu** [comment]
awesome! works properly. thank you
