### ISSUE TITLE
tensionX/tensionY is ignored whenever opacity property is applied via propertyFields

### ISSUE THREAD

**Issue by ZakTreister** [amcharts/amcharts4#2014]
Hi,

I'm having this issue

![image](https://user-images.githubusercontent.com/43063428/71640402-04775c00-2c92-11ea-8f01-2dca7dafb072.png)

As you can see once the propertyFields kick in, I lose my tensionX.

I'm loading amcharts 4 with the CDN. Is this why I'm not getting the fix?

_Originally posted by @ZakTreister in https://github.com/amcharts/amcharts4/issues/341#issuecomment-570040919_

**Comment by zeroin** [comment]
No, it's not because of CDN. When some property is changed, the new line is started and with two points you can not smooth it. The possible workaround would be to use axis ranges in this case: https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/ 
As with axis ranges a full line is drawn for each range.
