### ISSUE TITLE
When setting the hitTolerance we cannot specify X or Y and that limits us to fixing mobile scrolling

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2048]
When setting the hitTolerance we cannot specify X or Y and that limits us to fixing mobile scrolling false positives. 

Lets set hit tolerance to 40 

```
chart.cursor.interactions.hitOptions.hitTolerance = 40;
```

In order then to zoom on X axis (That is the only Zoom supported) then I have to select a portion of 40px and that is ok

<img width="1440" alt="Screenshot 2020-01-18 at 20 44 13" src="https://user-images.githubusercontent.com/1268723/72669564-98d41380-3a33-11ea-942c-e89bfded9434.png">

However, If I move the cursor vertically while selecting , the zoom triggers. 

Can we ask for different tolerances on X and Y ?

**Comment by martynasma** [comment]
Hm, I'm not too thrilled about introducing a second hitTolerance option.

Let us experiment a bit if we maybe can introduce some fuzzy logic that takes cursor's `behavior` into account as well.

**Comment by martynasma** [comment]
Fixed in [4.8.1](https://github.com/amcharts/amcharts4/releases/tag/4.8.1).

## [4.8.1] - 2020-01-22

### Added
- New setting `syncWithAxis` added to `ValueAxis`. Use it to sync grid between two or more axes. Set it to a reference of another `ValueAxis`, the one you need to sync grid with. [More info](https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Synchronizing_grid).

### Changed
- When default state is restored it will not set properties with `undefined` values as well. It used to ignore those.
- `XYCursor` will now take its `behavior` logic into account when calculating if it has moved or not. For example, if `behavior == "zoomX"` it will only measure horizontal distance when determining if cursor has moved or not.

### Fixed
- `Annotation` plugin: setting `currentTool` property was not working for `"line"` and `"arrow"`.
- Sometimes element properties were not being restored to their original values when responsive rules were applied.
- Sometimes some bullets on a `TreeMap` were not being shown back on after drilling bacup to top level.
- Setting `fontSize` on a `ValueAxis` was resulting in an error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
