### ISSUE TITLE
Drill-down Treemap : images disappearing when zooming without the animated theme

### ISSUE THREAD

**Issue by Segolene-Albouy** [amcharts/amcharts4#2052]
(Relatively insignificant bug)

When zooming in a drill-down treemap then zooming out, some of the icons associated with the treemap "squares" disappear. This doesn't happen when the animated theme is used.

![missing](https://user-images.githubusercontent.com/44207487/72723412-e6aa6200-3b80-11ea-9ce8-0bc5f813d9fe.png)

https://codepen.io/segolene-albouy/pen/OJPajda?editors=1010

**Comment by martynasma** [comment]
Fixed in [4.8.1](https://github.com/amcharts/amcharts4/releases/tag/4.8.1).

## [4.8.1] - 2020-01-22

### Added
- New setting `syncWithAxis` added to `ValueAxis`. Use it to sync grid between two or more axes. Set it to a reference of another `ValueAxis`, the one you need to sync grid with. [More info](https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Synchronizing_grid).

### Changed
- When default state is restored it will not set properties with `undefined` values as well. It used to ignore those.
- `XYCursor` will now take its `behavior` logic into account when calculating if it has moved or not. For example, if `behavior == "zoomX"` it will only measure horizontal distance when determining if cursor has moved or not.

### Fixed
- `Annotation` plugin: setting `currentTool` property was not working for `"line"` and `"arrow"`.
- Sometimes element properties were not being restored to their original values when responsive rules were applied.
- Sometimes some bullets on a `TreeMap` were not being shown back on after drilling bacup to top level.
- Setting `fontSize` on a `ValueAxis` was resulting in an error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
