### ISSUE TITLE
Tooltip text overflowing the tooltip border

### ISSUE THREAD

**Issue by sscots** [amcharts/amcharts4#2082]
I've found a bug where text will overflow the borders of the tooltip.
It happens whenever you drag over multiple tooltips, where each tooltip has a different number of lines, and text from the previous tooltip shows up at the bottom of the next tooltip.
I've determined the **bug is caused by adding newline characters to the end** of the tooltip.

Here is an example of the issue:
https://codepen.io/sscots/pen/BayeqwZ
If you drag over the 2nd bar to see the tooltip and then drag over the 3rd bar to see it's tooltip, you'll see text still appearing from the 2nd bar's tooltip within the 3rd bar's tooltip.

I don't consider this a big issue, because I just modified my code to prevent trailing newline characters on a tooltip (unless someone needs them for a reason), but am filing this issue in case someone else is trying to figure this bug out.

**Comment by sscots** [comment]
I also noticed a similar issue is occurring even if a newline is inside/between text.
Say if I do "\n\n" in the middle of a paragraph, the text from my previous tooltip will show inside of the blank line.

**Comment by sscots** [comment]
I found that if I just use html with the "tooltipHTML" instead of "tooltipText", then I can get it to work better.

**Comment by martynasma** [comment]
Fixed in [4.8.7](https://github.com/amcharts/amcharts4/releases/tag/4.8.7).

## [4.8.7] - 2020-02-05

### Added
- `sortBySeries` property added to `CategoryAxis`. If you set it to an instance of a `ColumnSeries`, the axis will automatically sort its categories by actual series' values.

### Fixed
- Labels with extra line breaks at the end could sometimes inherit content from previous version of multi-text, e.g. in dynamically updated tooltips.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
