### ISSUE TITLE
Stacked Series with different valueAxis do not stack after release 4.7.17

### ISSUE THREAD

**Issue by alcart** [amcharts/amcharts4#2089]
After I updated the am4charts version to 4.7.17 when series are in different yAxis, they are not stacked anymore.
In this [pen](https://codepen.io/alcartdelg/pen/xxbomMz) (a modified version of this demo [Stacked and Clustered Column Chart](https://www.amcharts.com/demos/stacked-column-chart/)) You can see the behavior I am referring to. This doesn't happen in version 4.7.16 is there a specific reason for that change?

**Comment by xorspark** [comment]
I'm not sure what the problem is. It seems to be stacking correctly in the latest release (4.8.6 as of today).

Current version:
![Screen Shot 2020-01-31 at 10 49 09 PM](https://user-images.githubusercontent.com/2679427/73586522-75ba5280-447c-11ea-8ce2-a649e9165cb6.png)

4.7.16:
![Screen Shot 2020-01-31 at 10 51 08 PM](https://user-images.githubusercontent.com/2679427/73586524-7d79f700-447c-11ea-9917-6dd421e721cb.png)

The older version has everything stacked into the same column space whereas the current version makes it a clustered stacked setup. The current version makes more sense since they're stacked according to their associated axis, which looks like the `Stacked series of a chart with multiple ValueAxis were not properly sorted.` fix in [the 4.17.7 changelong addresses](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#4717---2019-12-22). Or am I misunderstanding the problem?

>

**Comment by alcart** [comment]
Oh, I get it now. That was the desired behavior. Is there a way to make the Stacked series of a chart with multiple ValueAxis sorted on an optional basis? For instance, having a `series.sortedStack` option? Because for one of my charts I would like to have them stacked even if they are on different ValueAxis.

**Comment by zeroin** [comment]
If you set `series.clustered = false;` it should do like it was, although from my point of view this view doesn't make a lot of sense, as the columns are not stacked, they are just drawn one behind each other (that's how it was before).

**Comment by alcart** [comment]
Oh well, that's what I needed. Thank you very much. I will go ahead and close this issue.
