### ISSUE TITLE
Showing percentage in Force Directed Tree

### ISSUE THREAD

**Issue by qasimalbaqali** [amcharts/amcharts4#2104]
I am trying to show the percentage of the values in my Force Direct Tree chart. The idea is to show the percentage in the tooltip as well as the legend. 

I have set the attribute `calculatePercent` to `true` using the `ForceDirectedSeries` but that isn't working. 

```
const chart = create("circle-packing-chart", am4plugins.ForceDirectedTree);
chart.numberFormatter.numberFormat = "#,###";

const series = new am4plugins.ForceDirectedSeries();
series.calculatePercent = true;

// trying to enable the calculation percent in another way
const networkSeries = chart.series.push(series);
networkSeries.calculatePercent = true;
```

And trying to show the percentage in the legend, but I get an empty string.
```
chart.legend.labels.template.text = "{name}: {percent}%";
```

I am currently using two other amChart components the drill down Treemap and the Sunburst with the `calculatePercent` enabled and it's working just fine.

Does the Force Directed Tree chart doesn't have this functionality, or the way I am implementing it is wrong?

**Comment by martynasma** [comment]
Fixed in [4.9.0](https://github.com/amcharts/amcharts4/releases/tag/4.9.0).

## [4.9.0] - 2020-02-09

- New plugin: [Venn Diagram](https://www.amcharts.com/docs/v4/chart-types/venn/).
- `ForceDirectedSeries.dragFixedNodes` property added (default `false`).
- `ForceDirectedSeriesDataItem.percent` getter added.

### Fixed
- Mouse interactions were not working properly in very old (pre-59) FireFox.
- Dynamically changing `ForceDirectedSeriesDataItem.fixed` was not working.
- `CirclePattern` was not being globally exported.
- Setting `expoirtable = false` on some elements that are invisible sometimes caused them to become visible after export.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
