### ISSUE TITLE
How I can contribute to the project by making CSS animations like.

### ISSUE THREAD

**Issue by DevilDipan** [amcharts/amcharts4#2117]
I am trying to make CSS animations that I can attach with amcharts
![Animatedmultiforpreview2](https://user-images.githubusercontent.com/43346471/74211384-bf454180-4cb5-11ea-9275-a818ee454d2f.gif)
![Animatedmultiforpreview3](https://user-images.githubusercontent.com/43346471/74211393-c4a28c00-4cb5-11ea-99ce-2633f51b961b.gif)

Also I need help with animation lags.

**Comment by DevilDipan** [comment]
Also each series has to be denoted different element ids which could be made to work for each having a single id

**Comment by martynasma** [comment]
I'm not entirely sure what to suggest. We're not going to add CSS animation as a built-in feature. And we already have similar demo here:
https://www.amcharts.com/demos/css-animations/

Maybe you can post your code here or on CodePen so that everyone looking for it can find it?

As for IDs, I'm afraid there's no way to have two same IDs. It's by design. That said, chart adds all kinds of class names, including by object type, so you should be able to target multiple line series by their respective class names.
