### ISSUE TITLE
XYScrollbar grip drag issues when mouse goes outside of iframe. Webkit browsers only.

### ISSUE THREAD

**Issue by juan-jd-2** [amcharts/amcharts4#2123]
Hello,

My setup is an XY chart with an XYScrollbar inside an iframe. If you are dragging the scroll grip and you move your mouse outside the iframe and release the mouse, when you move back inside the iframe, the scrollbar will continue to drag and will at times behave erratically.

It seems that this kind of behavior was brought up [here](https://github.com/amcharts/amcharts4/issues/316), but there was no solution or workaround if you are using an iframe. Is there anything that can be done? 

This issue only occurs on webkit browsers (Chrome, Safari, etc.). It does not occur on Firefox. 

Thank you.

**Comment by martynasma** [comment]
No, I'm afraid.

Those browsers do not generate any kind of events when mouse cursor goes out of the iframe. Meaning that if mouse pointer was pushed down, then dragged outside iframe and released, no mouse up event would be fired and the chart would still think that the mouse button is pressed.

This gives me some ideas actually for a workaround. I'm going to mark this as a bug, so that we can give it another thought and get back to it.

Will keep you posted here.

**Comment by juan-jd-2** [comment]
Thank you very much.

**Comment by martynasma** [comment]
Fixed in [4.9.2](https://github.com/amcharts/amcharts4/releases/tag/4.9.2).

## [4.9.2] - 2020-02-25

### Added
- Accessibility: New method for chart's `svgContainer`: `readereAlert(text)`. When called, will force screen reader to read out certain text.
- `velocityDecay` added to `ForceDirectedSeries`. Increase the number to slow down node dynamics.

### Changed
- Accessibility: If screen reader is enabled, it will notify user when a) legend item is triggered; b) `MapChart` zoom level changes.
- `XYCursor.snapToSeries` now accepts an array of series and will snap to most close data point from any series present in the array.

### Fixed
- Now charts will properly disengage dragged elements when mouse cursor leaves iframe.
- Fixed a typos in French, Portuguese translations.
- Added more translated prompts to Korean translation.
- When series which was being used in an `XYChartScrollbar` local data was being updated, the clone used in Scrollbar was not being updated.
- `Series.autoDispose` setting was being ignored.
- Fixed "The precision is out of range" errors on some browsers (Safari, IE) when very small numbers are used.
- Accessibility: Setting of `tabindex` value was basically not working.
- Funnel slice with `null` values showed small black rectangle at the top/left corner and legend item was not showing a marker.
- Syncing between multiple `ValueAxis` improved.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
