### ISSUE TITLE
"over" events on Columns don't work if Cursor is enabled

### ISSUE THREAD

**Issue by lgerndt** [amcharts/amcharts4#2125]
I discovered that "over" events don't work (my event listener is never fired) on Columns if a chart's Cursor is enabled.  Interestingly, "out" events *do* work.

Background if interested:  we want to highlight the label text when user hovers over a column, that's why we're trying to setup "over" and "out" events.

**Comment by zeroin** [comment]
Hi,

I tried to reproduce it: https://codepen.io/team/amcharts/pen/RwPWmap?editable=true
The events do fire for me (check console). So I am afraid I need to see your chart live in order to understand why this happens in your setup.

**Comment by lgerndt** [comment]
Hi Zeroin, thanks for replying!  Here's a variation of your chart that displays the bug.  You'll notice I'm using a CategoryAxis for the X-axis.

**Comment by martynasma** [comment]
Thanks for additional info. This will be fixed in the next version.

**Comment by martynasma** [comment]
Fixed in [4.9.1](https://github.com/amcharts/amcharts4/releases/tag/4.9.1).

## [4.9.1] - 2020-02-14

### Added
- `precision` added to `MapLine` (default `0.1`). If line has `shortestDistance = true` set, it will be bent according to to projection. If `precision` is larger than the distance (degrees) between line's end points, no such bending will occur. Set it to large number for perfectly straight lines.
- `precision` added to `MapPolygon` (default `0.5`). Polygon's side lines are bent according to to projection. If `precision` is larger than the distance (degrees) between side's end points, no such bending will occur. Set it to large number for perfectly straight lines.

### Fixed
- JSON config: referring to a `parent` by id is now not dependent on order of elements.
- Series elements (e.g. columns) were not dispatching "over" event when `XYCursor` was being used.
- When `Legend` was triggering hover over `PieSeries` slice (or other `PercentSeries`), the slice did not dispatch `"over"` event.
- Hidden `ForceDirectedNode` (if hidden using API) was not showing if legend item was clicked to show it again.
- `path` adapter was not working on `Sprite`.
- Adding `data` to a `XYChart` with an `XYChartScrollbar` with a series was sometimes resulting JS error (if some data was missing).
- Adding `AxisBreak` to `CategoryAxis` could result JS error.
- `groupFields` were not copied to series in `XYChartScrollbar`, or any other cloned series.
- If a bullet was already disabled when `disabled` property field was set, that bullet did not update correctly after data change.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
