### ISSUE TITLE
ScrollbarX disconnected from chart series if using series.data instead of chart.data

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2136]
If data is provided per series instead of per chart the scrollbar is no longer connected to the series in the chart.

Sometimes (maybe a timing problem) the scrollbar is initially empty.
But reproducible the scrollbar is not updated if the series has new data by the series.addData method.

Simple Pen:
https://codepen.io/chrisadler/pen/PoqzNgJ

**Comment by martynasma** [comment]
Fixed in [4.9.2](https://github.com/amcharts/amcharts4/releases/tag/4.9.2).

## [4.9.2] - 2020-02-25

### Added
- Accessibility: New method for chart's `svgContainer`: `readereAlert(text)`. When called, will force screen reader to read out certain text.
- `velocityDecay` added to `ForceDirectedSeries`. Increase the number to slow down node dynamics.

### Changed
- Accessibility: If screen reader is enabled, it will notify user when a) legend item is triggered; b) `MapChart` zoom level changes.
- `XYCursor.snapToSeries` now accepts an array of series and will snap to most close data point from any series present in the array.

### Fixed
- Now charts will properly disengage dragged elements when mouse cursor leaves iframe.
- Fixed a typos in French, Portuguese translations.
- Added more translated prompts to Korean translation.
- When series which was being used in an `XYChartScrollbar` local data was being updated, the clone used in Scrollbar was not being updated.
- `Series.autoDispose` setting was being ignored.
- Fixed "The precision is out of range" errors on some browsers (Safari, IE) when very small numbers are used.
- Accessibility: Setting of `tabindex` value was basically not working.
- Funnel slice with `null` values showed small black rectangle at the top/left corner and legend item was not showing a marker.
- Syncing between multiple `ValueAxis` improved.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
