### ISSUE TITLE
Tooltip on DateAxis

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#214]
Hello!

I'm trying to build a chart with a DateAxis, yet it seems tooltips are not shown unless I point the cursor precisely on the point (which is very hard and bullets seem no good for that either, specially with a large dataset).

I have checked the issue [#22](https://github.com/amcharts/amcharts4/issues/22) for a fix (although my intervals are regular), and its' [CodePen](https://codepen.io/arm1n/pen/gzzmVQ) report example has the same issue (I assume the scripts imported are the latest, right?).

Moreover, the issue appears to be present only with Timestamps or Date objects. If the date value is something like 0, 1, 2, 3... or 0, 2, 4, 6..., the tooltips are correctly displayed.

**Comment by dswitzer** [comment]
@VictorJuliani,

Here's an example that uses the hit event on the series segments to allow you to click within the line area of the chart:

https://codepen.io/anon/pen/rrMVBy

**Comment by VictorJuliani** [comment]
Hi @dswitzer!

I am not trying to listen to click on the chart. What I meant is that I have to move the cursor precisely on the chart line point to see the tooltip ballon, but this is very hard and works badly.

What I've figured out is that the problem seems to be with the actual interval between the datapoints. It works normally for 1 min interval between each point, but if this value is smaller, the tooltips don't show.

Here is a simple repro: https://codepen.io/victorjuliani/pen/rroVVw?editors=0010
Just update the 'interval' variable to something >= 60 and tooltips will be nice, while for < 60, they don't show up.

**Comment by martynasma** [comment]
@VictorJuliani 

Yes, there currently are some issues with the code that finds nearest available data item to display tooltip on.

This happens on data sets that have data items at irregular intervals, like in your codepen.

We're working on a fix for it.

There's currently no known workaround, I'm afraid.

**Comment by VictorJuliani** [comment]
@martynasma Thanks for your feedback!

Just a note, on my second codepen [here, if you need it](https://codepen.io/victorjuliani/pen/rroVVw?editors=0010) , the issue also happens, but the data have REGULAR intervals. It fails when this interval is smaller than 1 minute.

**Comment by martynasma** [comment]
This seems to be related to #126

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.45](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.45).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

## [4.0.0-beta.45] - 2018-08-17

### Added
- New hardcoded `Sprite` state name added `"hoverActive"` which (if defined) is applied on active elements on hover. This state is applied last in the chain.
- New property on `DataSource`: `keepCount`. If set to `true` incremental updates will remove data items from the beginning of the current dataset, when adding the newly-loaded ones.
- New property on `DataSource`: `incrementalParams`. It's an object whose key/value pairs will be added to URL as parameters when DataSource is making an incremental load request.
- `Popup` (and `Modal`) now have an event dispatcher (`events`) with two events: `"opened"` and `"closed"`. ([more info](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Event_handlers))

### Changed
- Legend now respects `itemContainers.template.togglable = false`, which disables default functionality of toggling items when clicked in legend, allowing users to attach their own funcitonality to legend item clicks.
- Toggling of items in Legend can now be disabled by setting `chart.legend.itemContainers.template.togglable = false`.
- In `XYChart` with a `DateAxis`, cursor and data at irregular intervals will now display a Tooltip for nearest available series' data item.
- `zoomToCategories` method of `CategoryAxis` now zooms to the end of the "to" category.
- Default `urlTarget` of amCharts logo is now `"_blank"`.

### Fixed
- In `DataSource` the formatters `inputDateFormat` was ignored.
- Incremental data load via `DataSource` was not working.
- Tooltip used to flicker ar 0,0 position in some cases when hovering over elements.
- Fixed issue which caused chart to gradually shrink to invisibility under some conditions.
- Fixed rendering errors for charts that were initialized in hidden containers.
- `XYCursor` lines and axis tooltips were not shown if chart did not have any data (data was set directly on axis/series).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

**Comment by develar** [comment]
If anyone tries to implement custom tooltip — It is not documented yet (no even reference), but if data grouping enabled for date axis, you need to check also property `groupDataItems` in `event.target.dataItem` (`dataContext` will be undefined).
