### ISSUE TITLE
Updated dynamic tooltip is not showing on 'cursorpositionchanged' event

### ISSUE THREAD

**Issue by squareloop1** [amcharts/amcharts4#2188]
I want to show a tooltip on the cursor position with some calculated value based on the current cursor position on the chart.

It seems like the tooltip is only showing for static values. As soon as I add an updated calculated value (e.g. `Math.random()`), the tooltip is not showing up anymore.

I created a reproduction from the range area chart demo:
https://codepen.io/squareloop1/pen/XWbRZxp

See especially this part:

```
chart.cursor.events.on('cursorpositionchanged', (e) => {
  const random = Math.random();
  console.log(random); // showing updated random values correctly. Eventhandler is firing.
  //chart.plotContainer.tooltipText = 'Test'; // this tooltip is showing correctly
  chart.plotContainer.tooltipText = `Test: ${random}`; // this is not showing the tooltip at all
});
```

**Comment by martynasma** [comment]
Fixed in [4.9.5](https://github.com/amcharts/amcharts4/releases/tag/4.9.5).

## [4.9.5] - 2020-03-03

### Added
- Third paramterer - `force` - added to `ChartCursor.triggerMove`. If set to `true` it will trigger all actions associated with the move even if the cursor is already at the same coordinates.

### Fixed
- Exporting from ExportMenu will now prevent cursor (and releated tooltips) from appearing just before export so they are not included in exported image.
- Panning on a `MapChart` with `panBehavior = "rotateLongLat"` was not working properly since `4.9.3`.
- Disposed series was not being properly removed from `XYChartScrollbar` if it was used there.
- Sprites with `dx`/`dy` set and `rotation != 0` were not displaying fixed-position tooltip in correct position.
- Changing `tooltipText` was causing the tooltip to hide if it was already visible and `tooltipPosition` was set to `"pointer"`.
- `XYChart` with legend positioned to right/left was not positioning `valueLabels` properly (if aligned to right).
- `TreeMap` legend was not functioning properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
