### ISSUE TITLE
Tooltips appearing in exports even if disabled

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2195]
Hi, on my chart, the export menu appears over the series, which means when I export the chart, the cursor finds itself over the series, thus showing tooltips. The issue is that the exported picture shows tooltips which hide some data.

I read there ([Export Tutorial](https://www.amcharts.com/docs/v4/concepts/exporting/#Excluding_elements_from_export)) that it was possible to disable tooltip exports, but it doesn't seem to work.

Here is a stackblitz reproducing the issue : [StackBlitz](https://stackblitz.com/edit/typescript-dy7ew7).

Try to export as an image then lower your cursor quickly on the chart to see what I mean.

This might be similar to [#2212](https://github.com/amcharts/amcharts4/issues/2112).

**Comment by martynasma** [comment]
Fixed in [4.9.5](https://github.com/amcharts/amcharts4/releases/tag/4.9.5).

## [4.9.5] - 2020-03-03

### Added
- Third paramterer - `force` - added to `ChartCursor.triggerMove`. If set to `true` it will trigger all actions associated with the move even if the cursor is already at the same coordinates.

### Fixed
- Exporting from ExportMenu will now prevent cursor (and releated tooltips) from appearing just before export so they are not included in exported image.
- Panning on a `MapChart` with `panBehavior = "rotateLongLat"` was not working properly since `4.9.3`.
- Disposed series was not being properly removed from `XYChartScrollbar` if it was used there.
- Sprites with `dx`/`dy` set and `rotation != 0` were not displaying fixed-position tooltip in correct position.
- Changing `tooltipText` was causing the tooltip to hide if it was already visible and `tooltipPosition` was set to `"pointer"`.
- `XYChart` with legend positioned to right/left was not positioning `valueLabels` properly (if aligned to right).
- `TreeMap` legend was not functioning properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by IkamThorek** [comment]
The delay fixed it for me. Thanks
