### ISSUE TITLE
Legend marker colours do not match series fill colours 

### ISSUE THREAD

**Issue by trevorhawes** [amcharts/amcharts4#2196]
If I set my series fill colours from data:
series.columns.template.propertyFields.fill = "fill"
series.columns.template.propertyFields.stroke = "fill"
etc then I would expect the legend to use that fill colour, but it doesnt.
If I try to override that:
chart.series.each(function(series) {
                series.columns.template.adapter.add("fill", function(fill, target) {
                    chart.legend.markers.each(function(marker) {
                        if (marker.dataItem.dataContext === target.dataItem.component) {
                            marker.children.getIndex(0).fill = fill;
                        }
                    });
                    return fill;
                })
            })
Then I can force the markers to pick up the colour, but ... if I click on the markers (to turn on/off the series) when it is turned on again it has the original colour and not the fill colour I just set it to.

**Comment by martynasma** [comment]
`propertyFields` is designed to override properties for each individual data item, whereas legend marker is just one. Suppose data would contain different colors for each of the column. Which color should marker use?

This is the logic behind it not working by default. Not a bug.

That said, if you have the same color for all of the series columns, why not set that color directly on series, rather than on columns?
