### ISSUE TITLE
Question: my tooltips sometimes appear weirdly

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2198]
Hi, some of my tooltips appear in a weird way. 

![tooltip_fcked_up](https://user-images.githubusercontent.com/60658002/75699225-69f6c180-5cb0-11ea-9eee-d3c9ade6fcf7.png)

Do you have any idea what might cause it ?

**Comment by martynasma** [comment]
No. Can you post your chart online where we can test? CodePen perhaps.

**Comment by DavidAuger** [comment]
I have the same overlapping problem.
We observe that firstly, tooltip's elements are rendered well but their arrow are sometimes overlapping other cards. After 0.5-1 sec a small blink render cards other again (as expected).
In some cases (and more often in live data charts) we observed the overlapping shown on the screenshot and that tooltip stays in that state.

**Comment by IkamThorek** [comment]
Here is the bug : [stackblitz](https://stackblitz.com/edit/typescript-puhord) , add a lot of series for maximum effect.



**### Long story short :**
When I use adapters to show tooltips over a range, the tooltips appear one over another.



**### Full explication of my situation :**

In my code I have 2 sets of series. Most of the time, I only build the first set, it appears just fine.

When I activate the second set, I have a vertical guide bar separating left (first set) from right (second set). I hide the first set and its tooltips on the right side of the chart, and I hide the second and its tooltips on the left side.

In order to do that, I use 2 lists of ranges : **leftRanges**, which contains ranges that hide content on the left side, and **rightRanges**, which similarly contains ranges that hide content on the right side. I use **range.contents.disabled** to hide contents. 

However, it doesn't hide tooltips (I tried **range.contents.tooltip.disabled** but to no effect). So I used an adapter **x** :
![image](https://user-images.githubusercontent.com/60658002/75784953-4771b080-5d63-11ea-84bb-83bfd97c48d6.png)

I then enable/disable the **x** key, depending on if I want to show only the first set full screen, or if I want to show both sets.

![image](https://user-images.githubusercontent.com/60658002/75785227-afc09200-5d63-11ea-8751-1bcbf515dec7.png)

If I comment the code about adapters, the tooltips appear fine, but the tooltips of both series appear on both sides off the chart, which is not what I want.

**Comment by martynasma** [comment]
Thanks for the details.

I must say I'm not thrilled toggling `disabled` in the adapter of `x`.

The tooltip might be hidden but there's no guarantee that it is disabled **before** other tooltips are positioned, hence the original issue.

If you need to switch between sets of displayed tooltips, I suggest you implement some kind of control that would iterate through series and set each of those tooltips' `disabled` directly, not via adapter.

Another option is to consolidate data into a single tooltip. A few ideas to consider:

https://www.amcharts.com/docs/v4/tutorials/multi-series-shared-tooltip-with-colored-bullets/
https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
https://www.amcharts.com/docs/v4/tutorials/custom-static-multi-value-tooltip/

**Comment by IkamThorek** [comment]
Please note that the issue comes from disabling tooltips within the adapter, not from the fact that I enable/disable the adapters.

**Comment by martynasma** [comment]
> Please note that the issue comes from disabling tooltips within the adapter, not from the fact that I enable/disable the adapters.

Yes, that's exactly what I meant. You disable a tooltip in its adapter, but it does not mean that some other tooltip wasn't positioned taking into account the former tooltip.

**Comment by Julienh** [comment]
Hello,
I have the same problem, you can reproduce on this demo (Chrome) : https://www.amcharts.com/demos/stacked-area/

The motorbike tooltip is under the bicycle.
![Untitled-2](https://user-images.githubusercontent.com/148217/76524925-36aff180-646b-11ea-8dc0-77379a1826aa.png)

I also have the problem when of one of the tooltip disappear temporary.

**Comment by martynasma** [comment]
@Julienh How do you reproduce this? Section of bikes series is completely off screen.

**Comment by Julienh** [comment]
@martynasma I just move my cursor from the left to the right ?

I also reproduced the bug when the tooltip disappear temporary on this demo : https://www.amcharts.com/demos/pareto-diagram/
![Untitled-2](https://user-images.githubusercontent.com/148217/76603766-d9b94780-650d-11ea-8ae3-adde0a11efec.png)

**Comment by IkamThorek** [comment]
I saw the bug on the [link](https://www.amcharts.com/demos/stacked-area/) @Julienh provided, I just had to over the horizontal value 1999. However, it doesn't occur anymore. because there's more space over the chart now.

**Comment by martynasma** [comment]
Steps to reproduce:

1) Go here: https://codepen.io/team/amcharts/pen/3fac1af4e84bdc671cc3198276483239
2) Zoom vertically so that data points are out of the plot area.
3) Hover plot area.

![image](https://user-images.githubusercontent.com/1458520/76625623-5238fc00-6540-11ea-9ed8-70bbb9eee88c.png)

**Comment by Julienh** [comment]
I don't need to zoom in to reproduce the bug (cf my screenshot)
Chrome 80.0.3987.132
Firefox 73.0.1 (64 bits)

**Comment by martynasma** [comment]
Gotcha. Starting from next version, the chart will not show tooltips for data items that are outside plot area.

**Comment by martynasma** [comment]
Fixed in [4.9.7](https://github.com/amcharts/amcharts4/releases/tag/4.9.7).

## [4.9.7] - 2020-03-14

### Added
- Export has now additional setting `dataFieldsOrder`. It's an array. Push field names into it and exported data will try to maintain field order like this.
- A read-only property `tooltipDate` added to `DateAxis`. Will holde `Date` object of the last shown axis tooltip.

### Fixed
- In charts with series loading their own external data with responsive features enabled, they were starting as pre-hidden.
- Axes in `XYChartScrollbar` (both value and date) were not reseting min/max if series of the chart changed. This could result scrollbar's series incorrectly displayed.
- `PyramidSeries` and `FunnelSeries` with very small values were not animating properly on chart init.
- `PyramidSeries` and `FunnelSeries` with data items with `value = 0` could show small rectangle at top/left corner.
- `PyramidSeries` with data items with `value = 0` was not rendered properly.
- Tooltip on a horizontal axis was "shaking" when cursor was very near plot area.
- Performance improved of adding series to an already build `XYChart`.
- Map was not drawn with certain initial `deltaLongitude` values (e.g. 30, 60, etc).
- Removing series with a lot of data, `DateAxis` with grouping enabled, and zoomed-in chart could cause a stack overflow.
- Removing series could cause error (if removed while initial animation was still playing out).
- Sometimes, if a series was added after chart was inited and data grouping of `DateAxis` was enabled, the `ValueAxis` was not fully zoomed out.
- A newly added series after the chart was inited was not showing initial animation.
- Violating logarithmic axis scale no longer results in critical / chart-stopping error. The modal can be closed and chart recovered.
- If chart had stacked axes and series with bullets, the bullets were not masked properly. Now you can set `series.maskBullets = true` to solve this.
- Series tooltip is no longer shown if data item is outside plot area.
- Perfectly straight line series in `XYChartScrollbar` were not displayed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
