### ISSUE TITLE
Setting cursor.maxTooltipDistance to 0 doesn't work when series have identical data.

### ISSUE THREAD

**Issue by IkamThorek** [amcharts/amcharts4#2203]
It shows tooltips for series that have identical values even if you set : 

`chart.cursor.maxTooltipDistance = 0;`

![image](https://user-images.githubusercontent.com/60658002/75873688-a3ded980-5e10-11ea-8754-24bd9b875d2f.png)

**Comment by martynasma** [comment]
Thanks for bringing it to our attention!

Live example for the team:
https://codepen.io/team/amcharts/pen/3938cd39a36d3f7b08002b449e58b523?editors=0010

**Comment by martynasma** [comment]
Starting with the next release, you will be able to set `maxTooltipDistance` to `-1`. It will mean that only one tooltip will be shown at any given time, even if there are points in exact same coordinates.

We'll notify here once again when it is released.

**Comment by martynasma** [comment]
Fixed in [4.9.6](https://github.com/amcharts/amcharts4/releases/tag/4.9.6).

## [4.9.6] - 2020-03-05

### Changed
- Setting `maxTooltipDistance` to `-1` on `XYCursor` will force only one tooltip to always be displayed, even if there are multiple data items in exact same spot.

### Fixed
- Responsive: changing data on a chart with active responsive rules was causing for those rules not to be re-applied when chart was updated.
- If Legend item was clicked or tapped, subsequently pressing ENTER anywhere on the page was toggling it.
- Series of `MapChart` and their children were inherinting main locale.
- `ExportMenu` was freezing the whole chart is hovered (since `4.9.5`).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
