### ISSUE TITLE
Responsive bug?

### ISSUE THREAD

**Issue by maksabuzyarov** [amcharts/amcharts4#2204]
Hi, i make responsive chart using this instruction: [https://www.amcharts.com/docs/v4/concepts/responsive/](https://www.amcharts.com/docs/v4/concepts/responsive/).

Then, after 3 seconds, I updated the chart data and got unexpected behavior. The current responsive rules did not work right away, but only when I changed the screen size to the declared condition and back.

I taked example from instruction and added data update after 3 seconds.
[https://codepen.io/maksabuzyarov/pen/ZEGJNbm](https://codepen.io/maksabuzyarov/pen/ZEGJNbm)

To reproduce: 
1. Open link.
2. Change viewport to < 600px
3. Restart example
4. Wait 3 seconds

Data updated and ticks now enabled, but according to the responsive rules, it should be disabled

**Comment by martynasma** [comment]
Fixed in [4.9.6](https://github.com/amcharts/amcharts4/releases/tag/4.9.6).

## [4.9.6] - 2020-03-05

### Changed
- Setting `maxTooltipDistance` to `-1` on `XYCursor` will force only one tooltip to always be displayed, even if there are multiple data items in exact same spot.

### Fixed
- Responsive: changing data on a chart with active responsive rules was causing for those rules not to be re-applied when chart was updated.
- If Legend item was clicked or tapped, subsequently pressing ENTER anywhere on the page was toggling it.
- Series of `MapChart` and their children were inherinting main locale.
- `ExportMenu` was freezing the whole chart is hovered (since `4.9.5`).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by maksabuzyarov** [comment]
It works now. Thanks!
