### ISSUE TITLE
Date Axis labels inaccurate when reducing number of labels

### ISSUE THREAD

**Issue by MikamB** [amcharts/amcharts4#2207]
I have a lot of data to display on a chart, but when the chart reduces the number of labels it also offsets them from their correct positioning

See here: https://stackblitz.com/edit/typescript-tt1g7p

**Comment by martynasma** [comment]
Do you mean that when there are less labels to be displayed than for each hour, they are moved from the center of the cell to the start of the multi-hour period?

It's by design:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis

TL;DR: set:

```
axis.renderer.labels.template.location = 0.5;
axis.renderer.minGridDistance.template.location = 0.5;
```

**Comment by MikamB** [comment]
That's certainly part of it. It's part of a zoomable chart, so we see these labels moving as users zoom in and out and pan around, making it look like the data is offset.

I'm confused by the decision to have these labels labelling an area rather than a specific point seems counter to the design of having axis labels. At least for this use of trying to label data points on a line.

Even with the day labels it's marking the middle of the day.

Considering we're trying to do precise time plotting if ValueAxis don't do this it seems we might be better off using a unix timestamp with a ValueAxis and changing the labels?

**Comment by martynasma** [comment]
Again, this is by design. It follows axis and data granularity.

Suppose you have hourly data. If we display grid/label for every hour, it makes sense to display the label in the middle of that hour, since the data point is displayed there.

Now, if there are too many labels to cram into available width, we start displaying labels/graid every X hours, say every 3 hours. If labels would be displayed in the middle of such 3-hour cell, it would be incorrect from the time scale, since, say 6:00 would be display immediate below the data point for 7:00.

This is the reason for default behavior of labels being reset to the beginning of the cell when it contains more base time units than 1.

Does that make sense?

That said, you have full control of where labels are placed (using the `location`) properties, as well as when such "grouping" of grid/labels occurs using `minGridDistance`:

https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels

**Comment by MikamB** [comment]
> Now, if there are too many labels to cram into available width, we start displaying labels/graid every X hours, say every 3 hours. If labels would be displayed in the middle of such 3-hour cell, it would be incorrect from the time scale, since, say 6:00 would be display immediate below the data point for 7:00.

True, but instead what we're seeing is that, using your example of 3 hour groups the line denoting the start of the 6, 7, 8 group would be aligned roughly to 5:30. It's neither denoting the start of 6, nor the centre of the grouping.

**Comment by martynasma** [comment]
No, the line is in correct place :) It's just the data item is moved into the middle of the hour.

Position for it can also be controlled:
https://www.amcharts.com/docs/v4/concepts/series/#Data_item_locations

**Comment by MikamB** [comment]
Thank you very much for your help, I think this is the issue that's been eluding me. It just never occurred to me that you'd plot data at a different position than the one provided :/
