### ISSUE TITLE
Map polygon tooltip number formatter doesn’t respect locale settings

### ISSUE THREAD

**Issue by kubajaburek** [amcharts/amcharts4#2208]
Hello,
I’m building a map chart with numeric values and displaying the values in polygon tooltips. The chart has the `cs_CZ` locale set, but map tooltips in particular don’t respect that setting. The thousands separator in Czech is a space, but thousands in tooltips are still separated by a comma. I’ve created a simple example:

[http://kod.djpw.cz/fbvc-](http://kod.djpw.cz/fbvc-)

While debugging, I’ve found out that the number formatter of map polygons does not correctly inherit the locale setting from the chart, but even if I set it manually, numbers are still not formatted correctly. Number formatting using the same locale work correctly in tooltips in an XY chart.

I’m using the free hosted version of amCharts 4 and I couldn’t find anything specific about map tooltip number formatting, so I believe this is a bug in the library.

**Comment by martynasma** [comment]
Thanks for the heads up!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.9.6](https://github.com/amcharts/amcharts4/releases/tag/4.9.6).

## [4.9.6] - 2020-03-05

### Changed
- Setting `maxTooltipDistance` to `-1` on `XYCursor` will force only one tooltip to always be displayed, even if there are multiple data items in exact same spot.

### Fixed
- Responsive: changing data on a chart with active responsive rules was causing for those rules not to be re-applied when chart was updated.
- If Legend item was clicked or tapped, subsequently pressing ENTER anywhere on the page was toggling it.
- Series of `MapChart` and their children were inherinting main locale.
- `ExportMenu` was freezing the whole chart is hovered (since `4.9.5`).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by sureshhallyali** [comment]
Is it fixed this issue ?? if its fixed please let us know solution.
