### ISSUE TITLE
Last number formatter is used for all chart values

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#221]
Hello!

Currently the individual formatters presented in the tutorial [here](https://www.amcharts.com/docs/v4/concepts/formatters/#Individual_formatters) do not work properly. The chart picks the last formatter declared and uses it everywhere.

For instance, if I declare (in JSON) a global formatter with $ symbol and an X axis formatter with % symbol, both axis will have the % symbol. However, if I declare the X axis formatter and THEN then global formatter, both axis have the $ symbol. The same applies if I have only yAxis & xAxis individual formatters.

Here is a CodePen reproducing the issue: https://codepen.io/victorjuliani/pen/VBgeVr?editors=0010

**Comment by martynasma** [comment]
OK, let me explain why it is happening first.

`numberFormatter` is an "inheritable" property. This means that if some item in chart does not have it explicitly set, it will try to look for it in its parent, until found, all the way to the chart itself. Same goes for other formatters as well.

So if you request `.numberFormatter` on an Axis and on a chart, it will actually return the very same `NumberFormatter` object.

This is intentional, so that you don't have to go around and create formatters for every single object that uses numbers.

For Object-based setups, that's not a problem. You can just assign a `axis.numberFormatter = new NumberFormatter()` so that you have a separate copy of the formatter which won't affect anything else - just this particular axis and its children.

In JSON it works differently. A new object is created only if current property does not return nothing. Since it now returns an inherited formatter object (which is our global chart formatter) it just sets `numberFormat` which affects the whole chart.

Obviously, not cool.

I'm thinking about modifying this so that if you have `type` explicitly set (like you do in your config), JSON parser would not try to extract current value of the property, but rather go ahead and create a new instance.

This would solve the issue.

Make sure you're subscribed to this ticket so you're notified when it's available.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.43](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.43).

## [4.0.0-beta.43] - 2018-08-12

### Changed
- `$net.load()` options parameter now supports `responseType`. If set to `"blob"` will return response as `Blob` object in `result.blob`.

### Fixed
- Value axis min/max calculation algorithm adjusted. Fixed an issue with `strictMinMax = true` and issue with min/max when axis size was very small.
- Export now correctly uses external fonts included via `@import`, such as Google Fonts.
- Non-clickable columns in `ColumnSeries` will no longer gain focus on click/tap, unless its `hitOptions.noFocus` is set to `false`.
- Noon was incorrectly formatted as "AM", instead of "PM".
- `TextFormatter` was producing invalid `style` value on empty formatting blocks (`"[]"`).
- `parent` was not being set for a `Sprite` that was pushed directly to `Container.children`.
- If axis labels were disabled, ranges labels were not visible.
- Axis used to reset some of the user-set values when initing renderer, e.g. `dateAxis.renderer.grid.template.location = 0.5` was not working.
- `XYChart` with category axis + date axis was not working properly.
- Stacked chart with logarithmic axis was not working properly.
- JSON: local formatter instances were not being instantiated properly, so all children objects were reusing chart's main formatters.
- JSON: Patterns are now supported.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
