### ISSUE TITLE
Adding data asynchronously misses some data points

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#222]
Hello,

Values are not correctly displayed if you execute addData synchronously, as we can see here:

![image](https://user-images.githubusercontent.com/6083644/44002075-72d4c726-9e3d-11e8-8fd5-18684c1ddbfb.png)

https://codepen.io/ptorrent/pen/MBLMjE

If timeout variable is set to 0 or 100, it dosen't work . If I set this variable to 1000, it's look ok

From my point of view, it is complicated to manage data (many differents cases depending on the chart type (serie / column, date , category, data on xAxis in some case, XYScrollbar not displayed, cursor not displayed if data are set to serie)).

**Comment by martynasma** [comment]
This looks closely related to #206.

Please take a look at the @zeroin reply there if the solution fixes this issue as well.

**Comment by ptorrent** [comment]
Hello,

I don't think there is a link between #206 and this post. There is no data before12:00 ( it's not the same rendering problem (no matter the zoom)).

![image](https://user-images.githubusercontent.com/6083644/44004540-36beecae-9e64-11e8-9239-337092efc67f.png)

**Comment by ptorrent** [comment]
You can reproduce de bug here : (play with timeout and you will see)

https://codepen.io/ptorrent/pen/jvWabW

![image](https://user-images.githubusercontent.com/6083644/44619237-790edf00-a883-11e8-8659-8c74f9a07da2.png)

![image](https://user-images.githubusercontent.com/6083644/44619250-ae1b3180-a883-11e8-9451-f61d22dd3f31.png)

**Comment by ptorrent** [comment]
any news about this issue ?

**Comment by martynasma** [comment]
I just checked your codepen. I can't seem to be able to reproduce this.

Does this happen in some particular browser?

**Comment by ptorrent** [comment]
happening on chrome and opera 

This is the chrome result : 

![image](https://user-images.githubusercontent.com/6083644/44959661-579c9b80-aef2-11e8-9f20-f7217889e37e.png)

**Comment by EtienneHelfer** [comment]
Hello amcharts, 

I have the same issue : 

![image](https://user-images.githubusercontent.com/35633370/44985417-95e09c00-af80-11e8-9e96-fc131134e2e6.png)

issue with firefox and others web browsers.

**Comment by martynasma** [comment]
@ptorrent Thanks. That last demo sheds some light. We're going to be looking into it.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.50](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.50).

## [4.0.0-beta.50] - 2018-09-10

### Added
- `am4core.unuseAllThemes()` method added. Any chart created after this method call will not have any theme applied to it.
- New property `am4core.registry.baseSprites` will now hold all active (non-disposed) instances of top-level elements, such as charts.
- `startLocation`/`endLocation` properties added to `CategoryAxis` (previously available on `DateAxis` only). Allows to specify location the first and last cells of the axis should start on respectively.
- `innerRadius` of a Slice can now be set as `Percent` (e.g. `am4core.percent(50)`).
- You can now set custom radii (`radius` property) on Pie series (if you have more than one, you might want one to be larger and another smaller).

### Changed
- [`MapLine.imagesToConnect`](https://www.amcharts.com/docs/v4/reference/mapline/#imagesToConnect_property) now accepts an array of string IDs that can reference images by their `id` property.
- Changed `tooltip` inheritance so that it checks for `virtualParent` rather than direct `parent`. E.g. series' bullets use series' tooltip and not chart tooltip as it was before.

### Fixed
- Map polygon stroke thickness could be rendered incorrectly when zooming quickly. (Issue #175)
- Calling `addData()` more than once before data was validated resulted only last data item to be added. (Issue #222)
- `DateAxis.baseInterval` was ignored if data was set directly on series.
- `MapLine` was not paying attention to the properties set on template.
- `HeatLegend` was not updating its label count after its size changed. This could have been resulting in very few labels if initial container (div) size was small.
- The map portion of `MapChart` was incorrectly positioned after container (div) resize.
- Object properties, like `"name"` in GeoJSON were overriding same properties in `MapSeries` data. Now, the values specified in data are used over ones in GeoJSON. (Issue #307)
- Axis ranges used to reset `axisRange.label.text`. (Issue #308)
- Fixed issues with disposing series and charts.
- Updated to [canvg 1.5.3](https://github.com/canvg/canvg/releases/tag/v1.5.3) to fix em/rem text issue for epoxrt fallbacks.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
