### ISSUE TITLE
Question or Bug RadarChart

### ISSUE THREAD

**Issue by tom2966** [amcharts/amcharts4#2251]
Hi,

I belive that I found a bug with the RadarSeries SeriesTooltip. As you also can see here: https://www.amcharts.com/demos/radial-line-graph/ the Tooltip from Series 1 and 2 is displayed only in the right- bottom quarter oft he chart. I belive this is a bug- isn‘t it? Otherwise it would be great if anybody can explain to me how to configurate the chart that the Tooltips will diplayed for all values.
Thanks a lot and best regards

Thomas

**Comment by martynasma** [comment]
Thank you for bringing it to our attention. It's most definitely a bug.

**Comment by martynasma** [comment]
Fixed in [4.9.9](https://github.com/amcharts/amcharts4/releases/tag/4.9.9).

## [4.9.9] - 2020-03-16

### Fixed
- Fixed again: if chart had stacked axes and series with bullets, the bullets were not masked properly. Now you can set `series.maskBullets = true` to solve this.
- `TimeLine` series bullets were not updating position when Y axis was zoomed.
- Tooltips of `TimeLine`/`RadarChart` series were hidden on some parts of the chart (sice 4.9.7).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by tom2966** [comment]
Solved! Thans for the fast & agile Support!
BR
Thomas
