### ISSUE TITLE
Bullets are very slow

### ISSUE THREAD

**Issue by floklein** [amcharts/amcharts4#2259]
Hi!

Even when not displayed, bullets are very slow. I only need them displayed on "true" points (not grouped ones). Do you have a workaround please?

Here is a CodePen: https://codepen.io/floklein/pen/YzXvyXB
- Add a series: fast
- Add a series with bullets: very slow (several seconds with 10k points)

**Comment by zeroin** [comment]
With this setup, bullets are still created, that's why it is slow. For an easy solution I could recommend using `minBulletDistance` property of series. If you set it to 30, the bullets will only be shown if the distance between data points is >30. And the chart will create bullets only when it needs them. 

If you want to show bullets only when data is not grouped, you can create adapter for `minBulletDistance` and make it big if data is grouped:
https://codepen.io/team/amcharts/pen/32de033e75919b4a47cce6ced9303618

**Comment by floklein** [comment]
Thanks a lot, works wonderfully!
