### ISSUE TITLE
Creating multiple bullets

### ISSUE THREAD

**Issue by mrAndyss** [amcharts/amcharts4#2271]
I ask for advice.

I have dataset like this:
`chart.data = [
{"GroupUsers": "Group 1","Value1": 11700000, "users": [{"name": "Mary", "href": "/user1foto.png"}, {"name": "Andy", "href": "/user2foto.png"}, {"name": "Mihkael", "href": "/user3foto.png"}]},
{"GroupUsers": "Group 2","Value1": 8300000,  "users": [{"name": "John", "href": "/user4foto.png"}, {"name": "Emma", "href": "/user5foto.png"}]}
];`

I have chart like this (shows the amounts by users group):
![image](https://user-images.githubusercontent.com/62033545/77227784-c6544f00-6b93-11ea-84bc-a913d502e19d.png)

I need to create bullets for each group with user photos. A set of bullets should be located in the center of the group. The number of groups and users in them can be arbitrary.
![image](https://user-images.githubusercontent.com/62033545/77227817-f56ac080-6b93-11ea-82f6-adf824dde3de.png)

**Comment by martynasma** [comment]
This is theoretically possible following this workflow:

1. Add generic `Bullet` to series.
2. Add `ready` event to series.
3. Event handler iterates through series' `bullets` and pushes `Image` instances as per data.

`Bullet` template may need to be manipulated in order to accommodate clustered layout of its children elements, width and position.

I'm sorry, but I don't have a ready-made example, and unfortunately can't carve out sufficient time to produce one.

If you'd like to take a stab at it yourself, let us know how it goes.

**Comment by mrAndyss** [comment]
Thanks for the advice! But I still need a little help.
How can I push images separately for each value in a series?
I'm trying to do it here: https://codepen.io/mrAndyss/pen/QWbZWyR, but images are not drawn.
Which object should I use to push images?

**Comment by martynasma** [comment]
More like this:

```
series.events.on("ready", function (ev) {
  series.bullets.each(function(bullet) {
    bullet.clones.each(function(nbullet) {
      var i = 0;
      while (i < nbullet.dataItem.dataContext.users.length) {
        var image = nbullet.createChild(am4core.Image);
        image.width = 100;
        image.height = 100;			
        image.verticalCenter = "middle";
        image.dx = i*110;
        image.href = nbullet.dataItem.dataContext.users[i].href;
        i++;
      }
    });
  });

});
```

https://codepen.io/team/amcharts/pen/6624d696d1cce782727c5101ce3deb26?editors=0010

**Comment by mrAndyss** [comment]
"bullet.clones" - this is a list of bullet instances for each series value. This is what I needed to know. Thanks!
