### ISSUE TITLE
Firefox Rendering Issues 

### ISSUE THREAD

**Issue by Infineon12** [amcharts/amcharts4#2283]
Hello,

i realized an issue with displaying labels, buttons within Firefox.
It feels like this is resulted by not getting the correct dimensions.

This happens on my own site for legend entries.
Should be:
![image](https://user-images.githubusercontent.com/2978137/77513616-9e0b6f80-6e75-11ea-94e9-55e8a03cb067.png)
Sometimes is in Firefox:
![image](https://user-images.githubusercontent.com/2978137/77513645-af547c00-6e75-11ea-97ce-7b6917fb1e68.png)

Firefox Browser Version 74

Example Page i used for showing the issue: 
https://codepen.io/team/amcharts/pen/NZGoVK

E.g. the map zoom control.
If i put the Map Chart Div to the top of the code it will be rendered by default and looks like expected.
![image](https://user-images.githubusercontent.com/2978137/77513995-47eafc00-6e76-11ea-8b67-2db768140f3f.png)
Result:
![image](https://user-images.githubusercontent.com/2978137/77513750-e2970b00-6e75-11ea-9dc9-f79ffa215ec7.png)

---

If the map chart keeps beeing the second div it will only be rendered when scrolling down.
Then the issue results in following display:
![image](https://user-images.githubusercontent.com/2978137/77514109-81236c00-6e76-11ea-98fd-0b061af1aa21.png)

---

Interesting is that if i set onlyShowOnViewport to false.
am4core.options.onlyShowOnViewport = false;

Then also if the map chart is the first div it always is rendered wrong too.

------
Second example:
Legend of graph

Should look like:
![image](https://user-images.githubusercontent.com/2978137/77515335-a6b17500-6e78-11ea-8b32-a11106a2739c.png)

Looks like if rendered second in Firefox:
![image](https://user-images.githubusercontent.com/2978137/77515375-b7fa8180-6e78-11ea-9795-36baec77e026.png)

Pen: https://codepen.io/Infineon12/pen/dyogajM

Thanks in advance for helping out.

Greetings Marco

**Comment by Infineon12** [comment]
Just checked to downgrade.
This happens since version 4.8.0

**Comment by martynasma** [comment]
Thanks for bringing it to our attention. We'll be looking into it, and keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.9.12](https://github.com/amcharts/amcharts4/releases/tag/4.9.12).

## [4.9.12] - 2020-03-26

### Added
- New mouse cursor style added: `am4core.MouseCursorStyle.text`.
- Export `formatOptions` now accessible via public property, e.g. `chart.exporting.formatOptions.getKey("csv").disabled = true`.

### Changed
- Using date format `"i"` to parse ISO dates now supports unlimited number of milliseconds. It was failing before if more than three digits were used for milliseconds.

### Fixed
- If `Label` had its interactions disabled then re-enabled, its `selectable` property was being ignored.
- `Modal` with `closable = false` could still be closed via curtain click.
- `openModal()` ignored title (second parameter).
- Pushing child elements in `Label` which has `textValign` set was resulting in error.
- `cursor.snapToSeries` was not working properly with `CategoryAxis`.
- Firefox was not measuring labels properly if a chart was lazy-loaded using `onlyShowOnViewport`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
