### ISSUE TITLE
XYSeries disappears from chart when zooming in with scrollbar

### ISSUE THREAD

**Issue by MikamB** [amcharts/amcharts4#2284]
This has only been happening with the 15 secondly subset of my data, so I think it might be data related, but I can't see anything strange about the data in question when comparing it to the sets that don't suffer this issue.

I've notice that this is at the point where display="none" disappears from one of the <g> components in the raw svg, but I'm struggling to determine the true cause.

I've checked for ordering issues which appear to be common issues, but haven't found anything that looks like it might be an issue.

You can see a stackblitz [here](https://stackblitz.com/edit/amcharts4-disappearing-data)

**Comment by zeroin** [comment]
The line disappears because you have `series.connect = false` and the gaps between your data are bigger than baseInterval duration of the date axis. So you either do not set connect = false, or set some baseInterval for your date axis (because automatically calculated can be wrong) or increase `series.autoGapCount` value which is 1.1 by default.

**Comment by MikamB** [comment]
That seems to have solved my issue, thanks.
