### ISSUE TITLE
Images as ValueAxis labels throws an error

### ISSUE THREAD

**Issue by simvol** [amcharts/amcharts4#2285]
When trying to add image to ValueAxis I'm getting an error `Cannot read property 'toString' of null` and the chart is not rendered. I couldn't find exact example on the official documentation, but I tried to follow the same approach as for adding images to bullets.

_Here is my code_
`const valueAxis = chart.yAxes.push(new am4charts.ValueAxis());`
`const label = valueAxis.renderer.labels.template;`
`const image = label.createChild(am4core.Image); // Error is thrown at this point, regardless of what comes next`
`image.href = 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-160/star.svg';`
`image.width = 30;`
`image.height = 30;`
`image.horizontalCenter = 'middle';`
`image.verticalCenter = 'middle';`

_What I see on the screen_
![image](https://user-images.githubusercontent.com/10889961/77556896-4f120a00-6e76-11ea-9d4d-5ba16af63858.png)

_What error looks like in the console_
TypeError: Cannot read property 'toString' of null
    at AxisLabel.Label.alignSVGText (Label.js?028d:770)
    at AxisLabel.Label.draw (Label.js?028d:614)
    at AxisLabel.Sprite.validate (Sprite.js?5d2f:530)
    at ValueAxis.validateAxisElements (ValueAxis.js?364d:421)
    at ValueAxis.validate (ValueAxis.js?364d:334)
    at eval (Container.js?be33:604)
    at Module.each (Array.js?6e0f:74)
    at Container.validateLayout (Container.js?be33:592)
    at System.validateLayouts (System.js?72b5:400)
    at eval (System.js?72b5:209)

**Comment by simvol** [comment]
I tried to use label adapter and add image with html, but something else weird is happening - html tags make labels gigantic and translate them 10k+ pixels out of the view.

Can someone explain what is going on please?
![image](https://user-images.githubusercontent.com/10889961/77587843-ec386700-6ea5-11ea-8896-9b41394e96e3.png)

**Comment by simvol** [comment]
I discovered that I should be using 'htmlOutput' adapter instead of 'html'. I don't know what is the difference but the first one works as expected.

I'm not closing the ticket because I would like to hear if there is a solution for the original issue.

**Comment by martynasma** [comment]
Your first attempt was correct, albeit failed due to a bug :)

We'll fix this in a new version due to be released before end of this week.

Will ping you here once more when the fix is available.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.9.12](https://github.com/amcharts/amcharts4/releases/tag/4.9.12).

## [4.9.12] - 2020-03-26

### Added
- New mouse cursor style added: `am4core.MouseCursorStyle.text`.
- Export `formatOptions` now accessible via public property, e.g. `chart.exporting.formatOptions.getKey("csv").disabled = true`.

### Changed
- Using date format `"i"` to parse ISO dates now supports unlimited number of milliseconds. It was failing before if more than three digits were used for milliseconds.

### Fixed
- If `Label` had its interactions disabled then re-enabled, its `selectable` property was being ignored.
- `Modal` with `closable = false` could still be closed via curtain click.
- `openModal()` ignored title (second parameter).
- Pushing child elements in `Label` which has `textValign` set was resulting in error.
- `cursor.snapToSeries` was not working properly with `CategoryAxis`.
- Firefox was not measuring labels properly if a chart was lazy-loaded using `onlyShowOnViewport`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by simvol** [comment]
Confirming works. Thanks a lot, it was crazy fast :)
