### ISSUE TITLE
Please use VALID ES6 import statements => file extensions

### ISSUE THREAD

**Issue by tobiu** [amcharts/amcharts4#2294]
Looking at the docs:
https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/
> import * as am4core from "@amcharts/amcharts4/core";

This syntax will work in case you are using a BUILD process like webpack, but in case you want to import your lib directly into the browser, it will break.

So, how to fix it: Of course you need to adjust the path first to match the folder, e.g.:
> import * as am4core from "../node_modules/@amcharts/amcharts4/core";

But even this will break, because a brower based import statement requires a ***filename-extension***:
> import * as am4core from "../node_modules/@amcharts/amcharts4/core.js";

This import does work fine. Then you get:
![Screenshot 2020-03-27 at 11 13 04](https://user-images.githubusercontent.com/1177434/77745658-f7150800-701b-11ea-912c-d726d7b5a8f6.png)

=> none of your import statements is using a filename extension, so they all break.

This is a bummer, since I am creating an ES8 framework which runs without any JS related builds:

https://github.com/neomjs/neo

Adding a showcase on how to use your ES6 version of the lib with neo.mjs is impossible until you adjust your imports to be valid in a browser based env. So please fix this!

(I can create a showcase including your lib via script tags, but this is not the same.)

**Comment by tobiu** [comment]
https://github.com/microsoft/TypeScript/issues/16577

**Comment by Pauan** [comment]
@tobiu We aren't against making amCharts work natively in the browser, but it's a lot more complicated than you think, because our *dependencies* don't work natively in the browser. So those will need to change first.

In general *very* few npm packages work natively in the browser, It will take years before you can expect npm packages to work natively.

Instead you need to use [import maps](https://github.com/WICG/import-maps) in order to use them. There are [multiple tools](https://github.com/WICG/import-maps#community-polyfills-and-tooling) you can use to automatically generate the import maps, including [@import-maps/generate](https://www.npmjs.com/package/@import-maps/generate) and [@jsenv/node-module-import-map](https://www.npmjs.com/package/@jsenv/node-module-import-map).
