### ISSUE TITLE
Incremental loading from external data source seems to be replacing the existing data

### ISSUE THREAD

**Issue by jaischeema** [amcharts/amcharts4#230]
We tried using the `incremental` feature with `reloadingFrequency` and added a custom adapter to append the last timestamp parameter to the request but the graph goes to some weird values after the request returns empty array because there are no new readings.

```javascript
  chart.dataSource.url = dataSourceUrl;
  chart.dataSource.reloadFrequency = 5000;
  chart.dataSource.incremental = true;
  chart.dataSource.adapter.add("url", function(url, target) {
    if (target.lastLoad) {
      url += "&last_timestamp=" + Math.trunc(target.lastLoad.getTime() / 1000);
    }
    return url;
  });
```

Is this feature working in the latest beta and does that configuration look right?

The format of the data we get back from the server is as following
```javascript
[{ timestamp: "2018-07-20T10:37:00.000+10:00", value: 100.20 }]
```

**Comment by martynasma** [comment]
Now that I'm looking at the code, it seems that incremental loading was not fully implemented, hence the issue.

We'll keep you posted here when it is implemented.

Thanks for the heads up!

**Comment by jaischeema** [comment]
Awesome, thank you!

**Comment by martynasma** [comment]
OK, so incremental loads are fixed, and there will be a few additional goodies thrown in in the next release.

I'll post more details when we release the update. Stay tuned.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.45](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.45).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

## [4.0.0-beta.45] - 2018-08-17

### Added
- New hardcoded `Sprite` state name added `"hoverActive"` which (if defined) is applied on active elements on hover. This state is applied last in the chain.
- New property on `DataSource`: `keepCount`. If set to `true` incremental updates will remove data items from the beginning of the current dataset, when adding the newly-loaded ones.
- New property on `DataSource`: `incrementalParams`. It's an object whose key/value pairs will be added to URL as parameters when DataSource is making an incremental load request.
- `Popup` (and `Modal`) now have an event dispatcher (`events`) with two events: `"opened"` and `"closed"`. ([more info](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Event_handlers))

### Changed
- Legend now respects `itemContainers.template.togglable = false`, which disables default functionality of toggling items when clicked in legend, allowing users to attach their own funcitonality to legend item clicks.
- Toggling of items in Legend can now be disabled by setting `chart.legend.itemContainers.template.togglable = false`.
- In `XYChart` with a `DateAxis`, cursor and data at irregular intervals will now display a Tooltip for nearest available series' data item.
- `zoomToCategories` method of `CategoryAxis` now zooms to the end of the "to" category.
- Default `urlTarget` of amCharts logo is now `"_blank"`.

### Fixed
- In `DataSource` the formatters `inputDateFormat` was ignored.
- Incremental data load via `DataSource` was not working.
- Tooltip used to flicker ar 0,0 position in some cases when hovering over elements.
- Fixed issue which caused chart to gradually shrink to invisibility under some conditions.
- Fixed rendering errors for charts that were initialized in hidden containers.
- `XYCursor` lines and axis tooltips were not shown if chart did not have any data (data was set directly on axis/series).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

**Comment by martynasma** [comment]
FYI, [Incremental data loading](https://www.amcharts.com/docs/v4/concepts/data/loading-external-data/#Incremental_data_loading) section in docs was updated with a lot of new info.

**Comment by jaischeema** [comment]
Thank you @martynasma for a very prompt solution, will try it out today.
