### ISSUE TITLE
Options do not apply when using Data Item Grouping

### ISSUE THREAD

**Issue by uckhj** [amcharts/amcharts4#2303]
hello.

I want to use the data item grouping option because I have a lot of data.
However, using that option does not apply to the location option applied to the series.
I leave a message because I don't know if my usage is wrong or an issue.

leave codepen url :
https://codepen.io/uckhj/pen/vYOPRvX

**Comment by amcharts** [comment]
It's a bug on our side, we will fix it in next release. Will let you know. Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.9.13](https://github.com/amcharts/amcharts4/releases/tag/4.9.13).

## [4.9.13] - 2020-04-05

### Added
- Global options setting added `am4core.options.suppressErrors` (default `false`). Set it to `true` to disable error-invoked modal display.

### Fixed
- Setting `locale` as string (e.g. `locale: "fr_FR"`) in JSON config was not working.
- `ValueAxis.min` and `ValueAxis.max` now accept `undefined`.
- `NumberFormatter` and `DateFormatter` will not longer critically fail if invalid `Intl` data is passed to them. Instead they will return `"Invalid"` string.
- Responsive: Sometimes objects were being revealed after coming back from responsive mode when thet shouldn't.
- `locations` setting of the `SeriesDataItem` were not being copied to grouped data items (when `DateAxis.groupData = true`).
- Shadow DOM: Made some changes to eliminate errors in IE11.
- Shadow DOM: `ExportMenu` and `Popup`/`Modal` CSS was not being properly applied causing those elements to lose styling and positioning.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
