### ISSUE TITLE
Legend labels and formatting broken when hovering columns

### ISSUE THREAD

**Issue by matoilic** [amcharts/amcharts4#2307]
I have created a column chart using amCharts 4.9.12 and came across an issue with dynamic/placeholder values in legend labels. When hovering one of the elements the labels in the legend all change to the name of the currently hovered element. Also, the adapter for the formatting seems to be ignored. 

While debugging I noticed that on hover, the `dataItem` property for all items in the legend gets set to the currently hovered one. This causes the placeholder `'{name}'` to be the same for all series elements.

I have created an example on Codepend to illustrate the issue. Am I doing something wrong here or is this really a bug in amCharts itself?

https://codepen.io/matoilic/pen/LYVvBvP?editable=true

**Comment by martynasma** [comment]
Might be a bug. Here's a significantly reduced version of your CodePen, still exhibiting the behavior.

https://codepen.io/team/amcharts/pen/4e113460b1caa5b9385d4e68db1c50ba?editors=0010

We'll keep you posted.

**Comment by zeroin** [comment]
No, it's not a bug but a outcome of a uncommon setup. Each series creates 4 data items (because category field is the same), even though the value field is present only in one data object in your data. And then you hover some category, the series sets these invisible data items as a tooltipDataItem and retrieves {name} from it. 

So I see couple solutions here:

1) create only one series. If you need to have a legend entry for each column, use this approach:
https://www.amcharts.com/docs/v4/tutorials/individual-legend-item-for-each-column/

2) set data for individual series:
https://codepen.io/team/amcharts/pen/e1a00127b32513ae41e9b5b2d4f54b3d?editors=0010
