### ISSUE TITLE
pie chart labes show 0.0% after resize when legend is disabled

### ISSUE THREAD

**Issue by Skindrat** [amcharts/amcharts4#2308]
Step to reproduce
1. use this code https://codepen.io/team/amcharts/pen/yLyNYdJ (example of responsive feature)
2. resize window to hide labels and ticks(<=600px)
![image](https://user-images.githubusercontent.com/52242367/78271901-6ce60b80-7515-11ea-9819-6a8f002ec77a.png)
3. disable one or mere legend
4. resize back to make labels and ticks visible (>600px)

Expected result:
![image](https://user-images.githubusercontent.com/52242367/78272086-b46c9780-7515-11ea-8311-7acc67df09dd.png)
Actual result:
![image](https://user-images.githubusercontent.com/52242367/78272125-c6e6d100-7515-11ea-888b-ccbdea4603e2.png)

**Comment by martynasma** [comment]
This is due how Responsive works, via application of states.

We have some ideas on how to resolve this, though.

Stay tuned.

**Comment by martynasma** [comment]
Fixed in [4.9.13](https://github.com/amcharts/amcharts4/releases/tag/4.9.13).

## [4.9.13] - 2020-04-05

### Added
- Global options setting added `am4core.options.suppressErrors` (default `false`). Set it to `true` to disable error-invoked modal display.

### Fixed
- Setting `locale` as string (e.g. `locale: "fr_FR"`) in JSON config was not working.
- `ValueAxis.min` and `ValueAxis.max` now accept `undefined`.
- `NumberFormatter` and `DateFormatter` will not longer critically fail if invalid `Intl` data is passed to them. Instead they will return `"Invalid"` string.
- Responsive: Sometimes objects were being revealed after coming back from responsive mode when thet shouldn't.
- `locations` setting of the `SeriesDataItem` were not being copied to grouped data items (when `DateAxis.groupData = true`).
- Shadow DOM: Made some changes to eliminate errors in IE11.
- Shadow DOM: `ExportMenu` and `Popup`/`Modal` CSS was not being properly applied causing those elements to lose styling and positioning.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
