### ISSUE TITLE
Enhancement: Allow innerRadius of Slice to be defined in percentage

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#231]
The `radius` and `innerRadius` of a `PieChart` have a type `number | Percent`. However a single `Slice` has the properties `radius` and `innerRadius` as either `number` or `number | string`. 
In case we define a percentage value on the `innerRadius` of the chart and want to change the `innerRadius` of a `Slice` based on a certain state (e.g. `active`), I'd just want to change the percentage value and not have to specify the actual pixel value, as this might be quite hard to figure out (since the charts may be responsive). 
Could you add the option to also specify a percentage on the `innerRadius` and `radius` of a `Slice`, or do you have another way to fulfill this requirement?

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.50](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.50).

## [4.0.0-beta.50] - 2018-09-10

### Added
- `am4core.unuseAllThemes()` method added. Any chart created after this method call will not have any theme applied to it.
- New property `am4core.registry.baseSprites` will now hold all active (non-disposed) instances of top-level elements, such as charts.
- `startLocation`/`endLocation` properties added to `CategoryAxis` (previously available on `DateAxis` only). Allows to specify location the first and last cells of the axis should start on respectively.
- `innerRadius` of a Slice can now be set as `Percent` (e.g. `am4core.percent(50)`).
- You can now set custom radii (`radius` property) on Pie series (if you have more than one, you might want one to be larger and another smaller).

### Changed
- [`MapLine.imagesToConnect`](https://www.amcharts.com/docs/v4/reference/mapline/#imagesToConnect_property) now accepts an array of string IDs that can reference images by their `id` property.
- Changed `tooltip` inheritance so that it checks for `virtualParent` rather than direct `parent`. E.g. series' bullets use series' tooltip and not chart tooltip as it was before.

### Fixed
- Map polygon stroke thickness could be rendered incorrectly when zooming quickly. (Issue #175)
- Calling `addData()` more than once before data was validated resulted only last data item to be added. (Issue #222)
- `DateAxis.baseInterval` was ignored if data was set directly on series.
- `MapLine` was not paying attention to the properties set on template.
- `HeatLegend` was not updating its label count after its size changed. This could have been resulting in very few labels if initial container (div) size was small.
- The map portion of `MapChart` was incorrectly positioned after container (div) resize.
- Object properties, like `"name"` in GeoJSON were overriding same properties in `MapSeries` data. Now, the values specified in data are used over ones in GeoJSON. (Issue #307)
- Axis ranges used to reset `axisRange.label.text`. (Issue #308)
- Fixed issues with disposing series and charts.
- Updated to [canvg 1.5.3](https://github.com/canvg/canvg/releases/tag/v1.5.3) to fix em/rem text issue for epoxrt fallbacks.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Chnoch** [comment]
Thanks for the update!

As far as I can tell from the typings of the newest version (beta.50), only the `innerRadius` property now allows to specify a percentage value, but not the `radius` property. Could this be aligned and enhanced as well?

**Comment by martynasma** [comment]
You can use `radius` as `Percent` for `PieSeries`. Or do you need to set relative sizing for each individual slice as well?

https://www.amcharts.com/docs/v4/reference/pieseries/#radius_property

**Comment by Chnoch** [comment]
Yeah since when changing the `radius` for the active or hover state we need to be able to set the property on the slice (same as was implemented for `innerRadius`).

**Comment by Chnoch** [comment]
Sure thing. Referenced in #339. Thanks
