### ISSUE TITLE
Uncaught TypeError: t.resizeSensor.resetSensor is not a function

### ISSUE THREAD

**Issue by Achara** [amcharts/amcharts4#2334]
When using amchart4 with other ember addons that also have css-element-queries as dependency, this JS error occurs. (Please see the screenshot) In my case, I use amcharts 4 and ember-table libraries in my ember application The JS error refers to t.resizeSensor.resetSensor is not a function in amchart4 core.js. t.resizeSensor.resetSensor seems to be undefined when it is invoked.

`Uncaught TypeError: t.resizeSensor.resetSensor is not a function`

<img width="1320" alt="amchart4_error" src="https://user-images.githubusercontent.com/5659090/78991695-897ed680-7b07-11ea-9595-05bec2cf12fa.png">

**Comment by martynasma** [comment]
Hey, which version of [css-element-queries](https://github.com/marcj/css-element-queries) are you using?

**Comment by Achara** [comment]
I have @amcharts/amcharts4-ember@4.9.16 and css-element-queries@1.2.3 packages installed.

**Comment by Pauan** [comment]
@Achara Why do you have the `css-element-queries` package installed? It is not installed or used by `@amcharts/amcharts4-ember`.

You can use `npm ls css-element-queries` or `yarn why css-element-queries` to find which package is importing `css-element-queries`.

**Comment by Achara** [comment]
@Pauan, Thank you for your help. The error I got in core.js which lead me to look into amchart4 core.js file and I found a reference of css-element-queries.
https://raw.githubusercontent.com/amcharts/amcharts4/master/dist/script/core.js.map

The css-element-queries package installed is used by ember-table library which amcharts4 seems to have some conflicts with ember-table. Please advise. Thank you so much!

**Comment by martynasma** [comment]
We're getting rid of the `css-element-queries` dependency altogether in the next version. That should fix the issue for you.

We'll let you know when the new version is released.

**Comment by martynasma** [comment]
Fixed in [4.9.19](https://github.com/amcharts/amcharts4/releases/tag/4.9.19).

## [4.9.19] - 2020-04-30

### Added
- Export: Two new PDF export options added: `font` and `extraFonts` which enable specifying non-default font to use when exporting PDF. [More info](https://www.amcharts.com/docs/v4/concepts/exporting/#PDF_and_non_Latin_languages).

### Changed
- Third party resize sensor replaced with a home-brewed, which is faster and more reliable.
- `svgContainer.resizeSensor` replaced with a dummy object. Make sure you remove all references to it in your code. Calling it's `reset()` method will now generate a warning in console.

### Fixed
- Inline text formatting blocks now accept quote-enclosed values, e.g. `[font-family: 'Segoe UI']`.
- Fills for columns in `RadarColumnSeries` were black (since last release).
- With Chrome 81 disposing the chart in with DevTools open was very slow.
- Performance optimizations when showing/hiding series with a lot of data.
- Tooltip was flickering at 0,0 position if animated theme was not enabled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
