### ISSUE TITLE
Export map with Pattern

### ISSUE THREAD

**Issue by rronaldr** [amcharts/amcharts4#2337]
Hello is there any way to export a map with MapPolygon Pattern that also has an Image element?

It seems that even the official demo doesn't support this feature: https://codepen.io/rronaldr/pen/zYvGveG.

My problem described here: https://stackoverflow.com/questions/61169228/export-doesnt-include-pattern

Thanks

**Comment by martynasma** [comment]
Including another SVG image into an SVG when exporting automatically makes the canvas "tainted", so they are removed or the export would fail altogether.

The only way around it would be to use a native `Sprite` element with it's `path` property set to the pattern, so that it becomes part of the SVG itself, not an external image. Or, just use `Pattern` element as a `fill`.

I updated the demo here to use built-in `PatternSet`:
https://www.amcharts.com/demos/map-with-patterns/

Those patterns will export just fine.

Hope this helps.
