### ISSUE TITLE
Bug: Togglable on itemContainers.template doesn't toggle active state

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#234]
As far as I can tell from the documentation (https://www.amcharts.com/docs/v4/reference/sprite/#togglable_property) the `togglable` property should allow setting an element to active. 
However when adding `toggleable=true` on the `itemContainers.template` for the chart legend and then clicking on any legend item, the respective chart slice disappears (and is not marked as `active` as when clicking on the chart slice).

In addition the state on the legend indicates that the element is still visible after the first click and is only toggled on subsequent clicks. Due to this behavior the legend is out of sync with the chart.

To reproduce: 
https://codepen.io/chnoch/pen/LBvzKQ
- Click on any item in the legend
--> Instead of the respective slice being active, it gets hidden
--> The clicked element in the chart is still marked active
- Click on the same item in the legend
--> The slice is being displayed again, but the legend now shows as disabled.

Is `togglable` generally the wrong attribute to set an element as `active`? And why is the legend and chart state out of sync?

**Comment by martynasma** [comment]
Before classifying this as a bug, help me understand what you are trying to achieve by setting `togglable` to item containers?

Setting `togglable = true` activates this behavior:
1) Clicking for the first time it sets `isActive = true` + applies "active" state (if it is defined);
2) Clicking second time it resets `isActive` to `false + applies "default" state.

This is why you see the behavior you are seeing.

Maybe if I understand what you are trying to achieve, I can suggest some other way to do it.

**Comment by Chnoch** [comment]
Thanks for taking it up.
The behavior I'm looking for is for the chart to behave the same when I click either on a slice or on the respective legend item. So that when I click on the legend item (e.g. on "Lithuania" in the above Codepen) the slice gets marked as "active". 
Default behavior (as far as I can tell) when clicking in the chart is to select it as active and when clicking on the legend is to hide it. 
When using `togglable=true` on the `itemContainers.template` I'd expect the legend to behave the same as the chart and to set the slice of the chart as "active" and not to hide it. 

What happens now is the following behavior:
1. Click on "Lithuania" in the legend: Slice of Lithuania gets hidden and is not set as active, Legend item stays the same
2. Click on "Lithuania" again: Slice is displayed in its default state, however the legend item is now displayed as hidden.

As far as I can tell the "active" state in the chart is never triggered when clicking on an element in the legend, it only switches between "default" and "hidden" state.

Hope you understand what I mean.

**Comment by Chnoch** [comment]
For our use case the simplest enhancement would be to allow the legend to toggle an item between "active" and "default" instead of between "hidden" and "default". If this could be configured with a simple property that would be optimal. 
However if we can otherwise just attach our own "hit" event that'll also work for us.

**Comment by martynasma** [comment]
We decided to simply make legend respect the `legend.itemContainers.template.togglable = false`.

This will be in the next version we are going to release.

Since we can't think of all the possible scenarios that users might need on legend item click, it would not make sense to have many presets, especially it is quite easy to attach own "hit" events to do that.

Hope you agree.

**Comment by Chnoch** [comment]
Sounds good to me! Thanks!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.45](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.45).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

## [4.0.0-beta.45] - 2018-08-17

### Added
- New hardcoded `Sprite` state name added `"hoverActive"` which (if defined) is applied on active elements on hover. This state is applied last in the chain.
- New property on `DataSource`: `keepCount`. If set to `true` incremental updates will remove data items from the beginning of the current dataset, when adding the newly-loaded ones.
- New property on `DataSource`: `incrementalParams`. It's an object whose key/value pairs will be added to URL as parameters when DataSource is making an incremental load request.
- `Popup` (and `Modal`) now have an event dispatcher (`events`) with two events: `"opened"` and `"closed"`. ([more info](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Event_handlers))

### Changed
- Legend now respects `itemContainers.template.togglable = false`, which disables default functionality of toggling items when clicked in legend, allowing users to attach their own funcitonality to legend item clicks.
- Toggling of items in Legend can now be disabled by setting `chart.legend.itemContainers.template.togglable = false`.
- In `XYChart` with a `DateAxis`, cursor and data at irregular intervals will now display a Tooltip for nearest available series' data item.
- `zoomToCategories` method of `CategoryAxis` now zooms to the end of the "to" category.
- Default `urlTarget` of amCharts logo is now `"_blank"`.

### Fixed
- In `DataSource` the formatters `inputDateFormat` was ignored.
- Incremental data load via `DataSource` was not working.
- Tooltip used to flicker ar 0,0 position in some cases when hovering over elements.
- Fixed issue which caused chart to gradually shrink to invisibility under some conditions.
- Fixed rendering errors for charts that were initialized in hidden containers.
- `XYCursor` lines and axis tooltips were not shown if chart did not have any data (data was set directly on axis/series).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).
