### ISSUE TITLE
Sankey links not re-drawing after navigating up a level once encountering zero value

### ISSUE THREAD

**Issue by littleberry** [amcharts/amcharts4#2346]
I encountered an issue (bug?) drawing a Sankey diagram with AmCharts 4. When encountering a zero value on a node, the link doesn't draw (expected). However, when navigating back up a level after encountering this, none of the links draw, even though all nodes at that level have values.

Example of behavior on Codepen: https://codepen.io/littleberry/pen/vYNOQxG

This example is contrived in that at the top level, Node B has a value of 30. At sub-level (click the link to B), Node G (only node at level) has a value of zero. I have run into this scenario with data returned from a database query.

To view described behavior: 
1. Click the link to node B to navigate to the sub-level (the link between B and G does not appear as expected).
2. Click the link to 'Home' in breadcrumb nav (links present before navigating to sub-level no longer appear)

[Edit: added screenshots from pen linked above and code]
When Sanky chart first loads:
![sankey-zeros-issue-example-a](https://user-images.githubusercontent.com/5406637/79495546-c14bb980-7ff2-11ea-99fc-33dc78d4e8a3.png)

Click on B and this is the result:
![sankey-zeros-issue-example-b](https://user-images.githubusercontent.com/5406637/79495575-cc064e80-7ff2-11ea-8c78-64a7d3c62424.png)

Then click Home in the breadcrumbs nav to go back to the beginning:
![sankey-zeros-issue-example-c](https://user-images.githubusercontent.com/5406637/79495714-04a62800-7ff3-11ea-9250-3bf982bfb039.png)

Clicking the A branch works as expected:
![sankey-zeros-issue-example-d](https://user-images.githubusercontent.com/5406637/79495985-7bdbbc00-7ff3-11ea-8628-50250640d37a.png)

The code I used is largely from the tutorials for creating a Sankey chart and breadcrumb navigation.:
`let chartData = [
	{"from": "All", "to": "A", "value": 57, "sub": [{ "from": "A", "to": "F", "value": 35}, { "from": "A", "to": "G", "value": 20}, { "from": "A", "to": "P", "value": 2 }]},
	{"from": "All", "to": "B", "value": 30,
		"sub": [{"from": "B", "to": "G", "value": 0}]}
];

let chart = am4core.create("sankey", am4charts.SankeyDiagram);
chart.dataFields.fromName = "from";
chart.dataFields.toName = "to";
chart.dataFields.value = "value";

let nav = chart.createChild(am4charts.NavigationBar);
nav.data = [{ name: "Home" }];
nav.toBack();

let nodeTemplate = chart.nodes.template;
nodeTemplate.width = 30;
nodeTemplate.stroke = am4core.color("#fff");
nodeTemplate.strokeWidth = 2;
nodeTemplate.nameLabel.locationX = 0.2;
nodeTemplate.nameLabel.label.fill = am4core.color("#000");
nodeTemplate.clickable = false;
nodeTemplate.draggable = false;

chart.links.template.cursorOverStyle = am4core.MouseCursorStyle.pointer;
chart.links.template.events.on("hit", function(ev) {
  chart.colors.reset();
	var nav = chart.children.getIndex(0);
	var linkData = ev.target.dataItem.dataContext;
  if (linkData.sub) {
    chart.data = linkData.sub;
    nav.data.push({
      name: ev.target.populateString("{fromName}→{toName}"),
      step: ev.target.dataItem.dataContext
    });
    nav.invalidateData();
		chart.invalidateData();
	}
});
nav.links.template.events.on("hit", function(ev) {
  var target = ev.target.dataItem.dataContext;
  var nav = ev.target.parent;
	chart.colors.reset();
  if (target.step) {
    chart.data = target.step.sub;
    nav.data.splice(nav.data.indexOf(target) + 1);
    nav.invalidateData();
  } else {
    chart.data = chartData;
    nav.data = [{ name: "Home" }];
  }
	chart.invalidateRawData();
});

chart.data = chartData;
`

**Comment by martynasma** [comment]
Fixed in [4.9.18](https://github.com/amcharts/amcharts4/releases/tag/4.9.18).

## [4.9.18] - 2020-04-28

### Added
- Heatmaps can now be logarithmic (set `logarithmic = true` in the heat rule config).

### Fixed
- Preloader label was misaligned when RTL was enabled.
- Double "hit" event invocation on `MapPolygon` fixed.
- Regression plugin: "processed" event was triggered twice on initial chart load.
- SliceGrouper plugin: if slice templats had any "hit" events set, `clickBehavior = "break"` was not working.
- IE was not displaying series in `XYChartScrollbar`. On IE now gray fill/stroke is used instead of desaturate filter.
- IE was not displaying series with filters. Remnoved filters if IE.
- Fixed issue with zero-value nodes drill-down `SankeyDiagram`.
- When animations were disabled through options, showing `XYSeries` and `FunnelSeries` after it was hidden was not working.
- It was not possible to add `MapImages` to `MapImageSeries` directly from the GeoJSON geodata.
- `maxWidth` set on Legend's label was being ignored.
- Layout was not being redrawn when `minGridDistance` was set after chart initialization.
- If `sprite.showTooltipOn = "hit"` and no animated theme was used, tooltip used to flicker at old position before shown in the correct one.
- EDGE was not showing `ColumnSeries` gradients if gradient was set on series, not on directly on column template.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
