### ISSUE TITLE
CalendarWeek Wrong (Summertime issue?)

### ISSUE THREAD

**Issue by AlexKa** [amcharts/amcharts4#2357]
Hi folks,

when having date displayed on a calendar week basis, starting with 03-30 the week calculation seems to go wrong:

- 2020-03-30 is the monday of calendar week 14
- 2020-04-06 is the monday of calendar week 15
....

03-29 was beginning of summertime. Maybe this has sth. to do with it?

![image](https://user-images.githubusercontent.com/361999/79266987-b0873080-7e98-11ea-8da9-c8d1df3d1eab.png)

I also created a Codepen sample for that:
https://codepen.io/akmuc/pen/WNQQLzP

Best Alex

**Comment by martynasma** [comment]
Thanks for the heads up!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.9.17](https://github.com/amcharts/amcharts4/releases/tag/4.9.17).

## [4.9.17] - 2020-04-20

### Added
- Global option `am4core.options.nonce` added. If set, amCharts will use this as a nonce-parameter for all dynamically created stylesheets, so it can be addressed in `Content-Security-Policy` headers.
- New `Popup` property: `dynamicResize`. If set to `true` (default) and contents contains unloaded images it will resize itself when those finish loading.
- `gradientUnits` added to `LinearGradient`. If you're setting gradient on a perfectly straight line, set it to `userSpaceOnUse`.
- `filterUnits` added to `Filter`. If you're setting gradient on a perfectly straight line, set it to `userSpaceOnUse`.
- `startLocation` and `endLocation` added to `CategoryAxisBreak`. Can use to indicate where exactly within category break should start and end.

### Changed
- `Popup` now will size itself to accommodate images inside it as they are being loaded. To disable, set `Popup`'s `dynamicResize = false`. Also make sure you enable `maxWidth`/`maxHeight` in your CSS to avoid unreasonably large popups for unsized images.

### Fixed
- Week number in date format (`"ww"`) was not accounting for daylight saving.
- Pressing ENTER on a focused Legend item will no longer toggle related series if legend's item containers are sett to be not togglable.
- Exporting to SVG no longer breaks if chart contains `foreignObject` elements with SVG's in them.
- Line smoothing (`tensionX` / `tensionY`) now drops out duplicate points to avoid weird loops on overlapping data items.
- Chart was zooming incorrectly, when data was added directly to stacked series and one of the series was hidden.
- Some performance issues with `XYCursor` and a lot of series fixed.
- `LinearGradient` fill was not working on `LineSeries` under EDGE.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
