### ISSUE TITLE
How can use LinearGradient for AxisLine stroke ?

### ISSUE THREAD

**Issue by saleemshenlin** [amcharts/amcharts4#2361]
i see it in docs.
![image](https://user-images.githubusercontent.com/3690320/79338852-8dbd5080-7f5a-11ea-8529-309ea59dce8e.png)

``` javascrip
    const gradient = new am4core.LinearGradient();
    gradient.addColor(am4core.color('red'));
    gradient.addColor(am4core.color('blue'));
    gradient.addColor(am4core.color('green'));
    gradient.addColor(am4core.color('yellow'));
    gradient.addColor(am4core.color('red'));

    valueAxis.renderer.line.strokeOpacity = 1;
    valueAxis.renderer.line.strokeWidth = 5;
    valueAxis.renderer.line.stroke = gradient;
```

**Comment by zeroin** [comment]
SVG has issues with gradients and filters on straight lines, because they return height or width 0 when measuring the size: https://stackoverflow.com/questions/21638169/svg-line-with-gradient-stroke-wont-display-straight

So the solution here could be setting:
`gradient.element.attr({gradientUnits:"userSpaceOnUse"});`

However, the gradient will be drawn through all the area of your chart, so it might start and end not at exactly the colors you specified. But we do not have alternative solution.

**Comment by zeroin** [comment]
Since 4.9.17 you can do:

`gradient.gradientUnits = "userSpaceOnUse";`
