### ISSUE TITLE
Keyboard return press on legend item still invokes "toggle" with "togglable" set to false

### ISSUE THREAD

**Issue by PabloMizzle** [amcharts/amcharts4#2364]
Hi Guys,

I love your software. However, here's a small issue:
- Our goal is to "(un)highlight" a series when selecting the respective legend item instead of "show/hide"
- We set legend.itemContainers.togglable to "false"
- We add an event handler function to legend.itemContainers.hit which highlights the series
- Works for mouse/touch, but will still "show/hide" the respective series when tab selected and the "return" key is pressed

Try it in this [Pen](https://codepen.io/team/amcharts/pen/BGVYwq) from an [article on your website](https://www.amcharts.com/docs/v4/tutorials/highlighting-column-series-on-legend-click/).

Could you please make it behave the same way and maybe suggest a workaround?

Thank you and Kind Regards
Pablo

**Comment by martynasma** [comment]
Thanks for the heads up!

This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.9.17](https://github.com/amcharts/amcharts4/releases/tag/4.9.17).

## [4.9.17] - 2020-04-20

### Added
- Global option `am4core.options.nonce` added. If set, amCharts will use this as a nonce-parameter for all dynamically created stylesheets, so it can be addressed in `Content-Security-Policy` headers.
- New `Popup` property: `dynamicResize`. If set to `true` (default) and contents contains unloaded images it will resize itself when those finish loading.
- `gradientUnits` added to `LinearGradient`. If you're setting gradient on a perfectly straight line, set it to `userSpaceOnUse`.
- `filterUnits` added to `Filter`. If you're setting gradient on a perfectly straight line, set it to `userSpaceOnUse`.
- `startLocation` and `endLocation` added to `CategoryAxisBreak`. Can use to indicate where exactly within category break should start and end.

### Changed
- `Popup` now will size itself to accommodate images inside it as they are being loaded. To disable, set `Popup`'s `dynamicResize = false`. Also make sure you enable `maxWidth`/`maxHeight` in your CSS to avoid unreasonably large popups for unsized images.

### Fixed
- Week number in date format (`"ww"`) was not accounting for daylight saving.
- Pressing ENTER on a focused Legend item will no longer toggle related series if legend's item containers are sett to be not togglable.
- Exporting to SVG no longer breaks if chart contains `foreignObject` elements with SVG's in them.
- Line smoothing (`tensionX` / `tensionY`) now drops out duplicate points to avoid weird loops on overlapping data items.
- Chart was zooming incorrectly, when data was added directly to stacked series and one of the series was hidden.
- Some performance issues with `XYCursor` and a lot of series fixed.
- `LinearGradient` fill was not working on `LineSeries` under EDGE.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
