### ISSUE TITLE
 Why does the round world bootstrap move so hard

### ISSUE THREAD

**Issue by byCihat** [amcharts/amcharts4#2369]
hi
Why does the round world bootstrap move so hard

it hardly moves when you enter with a cell phone

http://www.tahmin.co/dunyam/

**Comment by martynasma** [comment]
Drawing maps in globe projection is a resource intensive operation. Since mobile phoens has usually lesser processor than computers, it might seem slower. I suggest disabling auto-rotation animation on mobiles.

Not using semi-transparencies on MapPolygonSeries objects might also improve performance.
