### ISSUE TITLE
Chart does not render when data is passed to Series instead of Chart in Firefox & Safari

### ISSUE THREAD

**Issue by gaurav-mehta** [amcharts/amcharts4#2371]
I'm trying to render a line chart from multiple data sources. For this reason, I have to provide data to the Series instead of the Chart. However, When I provide data to the Series instead of the Chart object, the chart does not render in Firefox (version 75.0) & Safari (version 13.1 (14609.1.20.111.8)).

Here is the link to my CodePen https://codepen.io/mehtag/pen/bGVpLmX?editors=1000.

Could someone help figure out the issue? I need to resolve this real fast.

**Comment by martynasma** [comment]
The issue is not with where data is set. The issue is that FF/Safari do not understand string dates like `"05-10-2020"`. Chrome is much more forgiving in that regard.

You just need to instruct the chart's DateFormatter what format your dates are in:

```
chart.dateFormatter.inputDateFormat = "MM-dd-yyyy";
```

Docs:
https://www.amcharts.com/docs/v4/concepts/data/#Parsing_dates_in_data

**Comment by gaurav-mehta** [comment]
Thanks for the quick reply. It did solve the problem. There is another issue I'm unable to figure out if you look at my data and the Dates that are getting plotted they don't match. Could you help me with that as well?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
