### ISSUE TITLE
ColumnSeries tooltip flickering

### ISSUE THREAD

**Issue by Stepik42** [amcharts/amcharts4#2384]
This issue can be reporoduced by following these steps:
1) Open the demo example in CodePen: https://www.amcharts.com/demos/simple-column-chart/
2)  add: series.columns.template.showTooltipOn = "hit";
3) disable animations
 
After that, if you want to show a tooltip by clicking on columns, then you will see that the tooltip will be shown at the old position for a short time and after that the tooltip is correctly displayed on the clicked column.  Tested by clicking between USA and BRAZIL columns.

**Comment by martynasma** [comment]
OK, so it seems that orientation of the tooltip is changed before relocating it.

We'll need to see if we can reverse it.

Will let you know when workaround or fix is available.

**Comment by martynasma** [comment]
Live demo for dev team:
https://codepen.io/team/amcharts/pen/edd53f151eb597256d2023fa93afcb27?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.9.18](https://github.com/amcharts/amcharts4/releases/tag/4.9.18).

## [4.9.18] - 2020-04-28

### Added
- Heatmaps can now be logarithmic (set `logarithmic = true` in the heat rule config).

### Fixed
- Preloader label was misaligned when RTL was enabled.
- Double "hit" event invocation on `MapPolygon` fixed.
- Regression plugin: "processed" event was triggered twice on initial chart load.
- SliceGrouper plugin: if slice templats had any "hit" events set, `clickBehavior = "break"` was not working.
- IE was not displaying series in `XYChartScrollbar`. On IE now gray fill/stroke is used instead of desaturate filter.
- IE was not displaying series with filters. Remnoved filters if IE.
- Fixed issue with zero-value nodes drill-down `SankeyDiagram`.
- When animations were disabled through options, showing `XYSeries` and `FunnelSeries` after it was hidden was not working.
- It was not possible to add `MapImages` to `MapImageSeries` directly from the GeoJSON geodata.
- `maxWidth` set on Legend's label was being ignored.
- Layout was not being redrawn when `minGridDistance` was set after chart initialization.
- If `sprite.showTooltipOn = "hit"` and no animated theme was used, tooltip used to flicker at old position before shown in the correct one.
- EDGE was not showing `ColumnSeries` gradients if gradient was set on series, not on directly on column template.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
