### ISSUE TITLE
Weird value axis for all data points with 0

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#2419]
**Bug description**
Example:
https://codepen.io/dmsmaxim/pen/ExVXoOZ

I'm trying to plot data points with `0` on all of them here and I think it's a bit weird that there is `-1` and `+1` values on the value axis. Ok, maybe `+1` is fine. I understand that there should be something on the axis. But why there is `-1`?

I know about `min` settings for `ValueAxis`.
But what if there is no opportunity to know what data will be on the chart...

![image](https://user-images.githubusercontent.com/15041200/80481474-2ab8ba00-895b-11ea-941b-a9727c8d6411.png)

**Environment**
amcharts v 4.9.17;
Google Chrome
Version 81.0.4044.122

**Additional context**

no additional context

**Comment by martynasma** [comment]
This is by design. When the line is absolutely straight, the axis scale adjusts so that the line is in the middle.

So it happens yours is all zeroes. But what would happen if all values were, say 5? You probably would not want your straight line at the bottom with scale going pointlessly to the 20.

So, yeah, setting `min` to zero is the only way to ensure that your Y axis scale starts at zero.

Hope that sounds reasonable.
