### ISSUE TITLE
Radar chart is black color

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2423]
default radar chart is black color.
https://www.amcharts.com/demos/zoomable-radar/

**Comment by martynasma** [comment]
Thank you for bringing this to our attention.

Will keep you posted about the progress of the fix.

**Comment by martynasma** [comment]
Fixed in [4.9.19](https://github.com/amcharts/amcharts4/releases/tag/4.9.19).

## [4.9.19] - 2020-04-30

### Added
- Export: Two new PDF export options added: `font` and `extraFonts` which enable specifying non-default font to use when exporting PDF. [More info](https://www.amcharts.com/docs/v4/concepts/exporting/#PDF_and_non_Latin_languages).

### Changed
- Third party resize sensor replaced with a home-brewed, which is faster and more reliable.
- `svgContainer.resizeSensor` replaced with a dummy object. Make sure you remove all references to it in your code. Calling it's `reset()` method will now generate a warning in console.

### Fixed
- Inline text formatting blocks now accept quote-enclosed values, e.g. `[font-family: 'Segoe UI']`.
- Fills for columns in `RadarColumnSeries` were black (since last release).
- With Chrome 81 disposing the chart in with DevTools open was very slow.
- Performance optimizations when showing/hiding series with a lot of data.
- Tooltip was flickering at 0,0 position if animated theme was not enabled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
