### ISSUE TITLE
PDF export broken due to missing Roboto fonts

### ISSUE THREAD

**Issue by fermevc** [amcharts/amcharts4#2430]
Simple PDF export worked like a charm for past two weeks.
Today I was trying to follow a tutorial for Multiple charts export, and found out that there is a problem regarding Roboto fonts...

![roboto error amcharts](https://user-images.githubusercontent.com/10687702/80871066-d723d480-8caa-11ea-985a-6e1e84aab082.png)

Even in the final Codepen that follows your tutorial there's the same error -  https://codepen.io/team/amcharts/pen/qvRMQj

Can I solve this on my own, or I need to wait for new library update.
I've googled about this issue on pdfmake, but proposed solutions either doesn't solve my problem, or I don't know how to implement some of them...
I'm using Laravel 6.x, and my Charts are in "blade" files.
This is just a question, If you need more details, I'll provide anything you want.
Thanks in advance!

**Comment by martynasma** [comment]
Fixed in [4.9.20](https://github.com/amcharts/amcharts4/releases/tag/4.9.20).

## [4.9.20] - 2020-05-11

### Changed
- `hit` and `up` events on nested objects will now respect correct bubbling up order.
- If `rtl` is not set directly on the `Label`, it will now take `rtl` value not from its parent but from `baseSprite` (performance enhancement).
- `<desc>` element with amCharts attribution removed from generated SVG.

### Fixed
- Export: PDF export will now fallback to regular fonts if bold fonts don't exist.
- Export: Advanced PDF exports with extra content were broken since last release.
- Export: Image export was essentially broken in IEs.
- `options.nonce` was not working properly on EDGE.
- Event `selectedned` was not dispatched by `Cursor` if released outside the chart div and behavior was set to `select*`.
- If all series were removed and then added quickly to the chart with a legend it could result a JS error.
- Setting `data` directly on a series not right after it was created could result `series.data` array to be shown as empty.
- It was impossible to set `SwitchButton` as active initially.
- Fixed snapping cursor to series when data was missing: if series had gaps in data and `cursor.snapToSeries` was set, the snapping was not working properly.
- When adding data to `XYSeries` which was `XYCharScrollbar`'s series, the raw data was incorrectly modified.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
