### ISSUE TITLE
Adding data to series used in XYChartScrollbar, updates it twice

### ISSUE THREAD

**Issue by janbols** [amcharts/amcharts4#2439]
**Bug description**
When adding a series to an XYChartScrollbar, adding data using `series.addData`, will add the same object twice.
For example after executing `series.addData({date: new Date(), value: 5}, 1);`, a `console.log(series.data)` will show the last item being added twice. In addition, the first 2 items are removed instead of just the first one. 

You can see an example in http://jsfiddle.net/ate89u6L/ using the console view.

**Environment (if applicable)**
AMCharts 4.9.19

**Additional context**
Might be related to https://github.com/amcharts/amcharts4/issues/356

**Comment by martynasma** [comment]
Fixed in [4.9.20](https://github.com/amcharts/amcharts4/releases/tag/4.9.20).

## [4.9.20] - 2020-05-11

### Changed
- `hit` and `up` events on nested objects will now respect correct bubbling up order.
- If `rtl` is not set directly on the `Label`, it will now take `rtl` value not from its parent but from `baseSprite` (performance enhancement).
- `<desc>` element with amCharts attribution removed from generated SVG.

### Fixed
- Export: PDF export will now fallback to regular fonts if bold fonts don't exist.
- Export: Advanced PDF exports with extra content were broken since last release.
- Export: Image export was essentially broken in IEs.
- `options.nonce` was not working properly on EDGE.
- Event `selectedned` was not dispatched by `Cursor` if released outside the chart div and behavior was set to `select*`.
- If all series were removed and then added quickly to the chart with a legend it could result a JS error.
- Setting `data` directly on a series not right after it was created could result `series.data` array to be shown as empty.
- It was impossible to set `SwitchButton` as active initially.
- Fixed snapping cursor to series when data was missing: if series had gaps in data and `cursor.snapToSeries` was set, the snapping was not working properly.
- When adding data to `XYSeries` which was `XYCharScrollbar`'s series, the raw data was incorrectly modified.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
