### ISSUE TITLE
Adding an active state for a column series breaks legend markers

### ISSUE THREAD

**Issue by jyrimatti** [amcharts/amcharts4#2444]
See codepen: https://codepen.io/jyri-matti/pen/BaoJMeq

Normally the legend shows a marker greyed out when the series is hidden. But if an active state is created for the series, the marker isn't grey anymore.

I wasn't able to find a workaround, is there some?

**Comment by martynasma** [comment]
"active" is a special state that gets applied to the legend item when it's "turned off". (I know a bit counter-intuitive but it's there for historical reasons)

If you create "active" state for the series, it gets propagated to the marker and knocks off legend's default active state.

Solutions:

1) Since "active" sate is not used anywhere natively for series, I imagine you are using it for your own app logic. Could you just use some other state name instead?

2) Disable copying of series to markers: `legend.defaultMarkers = true`

https://www.amcharts.com/docs/v4/concepts/legend/#Default_markers

**Comment by jyrimatti** [comment]
Thanks, `useDefaultMarker=true;` fixed the problem.

I'm using active state for "selecting" or "highlighting" columns by clicking them, since I though that's what it is meant for: https://www.amcharts.com/docs/v4/concepts/states/#Reserved_named_states

I guess I could also use a custom state instead. It just didn't occur to me that active state had some intended behavior for legends. I can see now (https://www.amcharts.com/docs/v4/concepts/legend/#Styling_disabled_state) that it's actually documented, so my bad, sorry. Although both the name and propagation from the series is a bit confusing.

I'm closing this since, if I understood correctly, it's not a bug.
