### ISSUE TITLE
Venn Diagram Label

### ISSUE THREAD

**Issue by sabba88** [amcharts/amcharts4#2448]
**Question**
Hi,
I have a problem with labels in Venn Diagram.
I have the data that is an array of object, each object has the following property:
- category
- value
- set (only for intersections)
- label

When I try to assign label property to serie label, the value of the property is not showed.
`series.labels.template.text = '{label}';`

Here is a demo [https://codepen.io/sabba88/pen/qBOxdpb?editable=true%3Dhttps%3A%2F%2Fwww.amcharts.com%2Fdemos%2Fvenn-diagram%2F](url)

I already use this pattern in some other charts and it works without any problem.
What I'm missing in this case?

Thanks in advance,
Samuele

**Comment by martynasma** [comment]
The issue is with how label is looking up values for the text placeholders.

It first looks up for a key in a dataItem. Since Venn's data item has label property it stops there, thinking it should be used, and does not get to the actual data.

There are a couple of solutions:

1) Use different key, e.g. "labeltext" instead of "label".
2) Use full reference: `'{dataItem.dataContext.label}'`.

**Comment by sabba88** [comment]
Thank you @martynasma, It works.
