### ISSUE TITLE
SwitchButton set active

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#2455]
Hy,

How can set a SwitchButton to active ?
I want to control his active state at least at first page load.

here is a pen if u can help.
https://codepen.io/aniov/pen/ZEbxjdW?editors=0010
(it seems that switchButton - labels see the correct active state)

Thank you in advance.

**Comment by zeroin** [comment]
Indeed, it's quite a stupid mistake from our side. We forgot to create acive state on whole button so the states are not passed to the children. This will solve it:

`chartSwitchButton.states.create("active");`

And we will fix this problem in next release. Thanks for the heads up.

**Comment by zeroin** [comment]
Update: this line is also required:

`chartSwitchButton.setStateOnChildren = true;`

**Comment by aniov** [comment]
Thank you for your response but i think we need something more for this to work.

Here is a pen with added code lines:
https://codepen.io/aniov/pen/VwvxZWw?editors=0010

It seems that on first toggle the switch (visual representation) doesn't change to his new state, but labels do, and it ends up being unsync.

![SwitchButton](https://user-images.githubusercontent.com/21243081/81470191-2e1d3280-91f2-11ea-9643-127b69e53584.gif)

**Comment by zeroin** [comment]
OK< I see that this will have to wait until we release an update, probably on Monday-Tuesday.

**Comment by martynasma** [comment]
Fixed in [4.9.20](https://github.com/amcharts/amcharts4/releases/tag/4.9.20).

## [4.9.20] - 2020-05-11

### Changed
- `hit` and `up` events on nested objects will now respect correct bubbling up order.
- If `rtl` is not set directly on the `Label`, it will now take `rtl` value not from its parent but from `baseSprite` (performance enhancement).
- `<desc>` element with amCharts attribution removed from generated SVG.

### Fixed
- Export: PDF export will now fallback to regular fonts if bold fonts don't exist.
- Export: Advanced PDF exports with extra content were broken since last release.
- Export: Image export was essentially broken in IEs.
- `options.nonce` was not working properly on EDGE.
- Event `selectedned` was not dispatched by `Cursor` if released outside the chart div and behavior was set to `select*`.
- If all series were removed and then added quickly to the chart with a legend it could result a JS error.
- Setting `data` directly on a series not right after it was created could result `series.data` array to be shown as empty.
- It was impossible to set `SwitchButton` as active initially.
- Fixed snapping cursor to series when data was missing: if series had gaps in data and `cursor.snapToSeries` was set, the snapping was not working properly.
- When adding data to `XYSeries` which was `XYCharScrollbar`'s series, the raw data was incorrectly modified.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
