### ISSUE TITLE
How axisY cursor show only point value not all value

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts4#2464]
How axisY cursor show only point value not all value (same magnet behaviour)?

**Comment by martynasma** [comment]
I'm afraid there's no way to turn on grid snapping of cursor on a `ValueAxis`. Sorry.

**Comment by ezze** [comment]
@martynasma, could tell us why it's not possible?

**Comment by martynasma** [comment]
Because `ValueAxis` is a linear scale, there are no concrete "anchor points" like, say, days on a `DateAxis` or categories on `CategoryAxis`.

That said, you can turn on snapping to actual data points of particular series:
https://www.amcharts.com/docs/v4/reference/xycursor/#snapToSeries_property

Example:
https://www.amcharts.com/demos/date-based-data/

**Comment by HASSANDL** [comment]
in json mode config snapToSeries array of id series not work.

**Comment by martynasma** [comment]
@HASSANDL Posted a separate issue: #2480. Make sure you subscribe to it for progress updates.
