### ISSUE TITLE
CircleBullet misaligned in legend

### ISSUE THREAD

**Issue by mustajarvi** [amcharts/amcharts4#2465]
**Bug description**

A linechart with default CircleBullets shows misaligned bullets in legend. I inspected the SVG and it looks like it's slightly off center. See CodePen here: https://codepen.io/rikard/pen/WNQyaRx

![image](https://user-images.githubusercontent.com/1049525/81666686-a2e6ab80-9442-11ea-8437-a5e72a6e0214.png)

**Comment by martynasma** [comment]
Fixed in [4.9.21](https://github.com/amcharts/amcharts4/releases/tag/4.9.21).

## [4.9.21] - 2020-05-13

### Fixed
- Latest version of `canvg` was causing issues in some Angular setups. Downgraded to `3.0.0`.
- The legend marker for `LineSeries` with circle bullet was not properly centered.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by mustajarvi** [comment]
Thank you @martynasma !
