### ISSUE TITLE
Map:  tooltips (showTooltipOn) that were on 'always' and now on 'hover' appear when zooming the map

### ISSUE THREAD

**Issue by Avivhdr** [amcharts/amcharts4#2468]
I created a map that shows tooltips on both situation:
1. hover 
2. last country that had an 'hit' event.

every hit event set the selected country's '_showTooltipOn_' to '_always_' and sets the previous selected country's '_showTooltipOn_' to '_hover_' (see code below).

For some reason once i zoom in the map all the tooltips that at one point were on 'always' suddenly appear.

Is this a bug or am i doing something wrong?

Code + CodeSandBox below.

Thanks.

```
let selected;
polygonTemplate.events.on("hit", function hitEvent(ev) {
  if (!selected) { // first hit
    selected = ev.target;
    selected.isHover = true;
    selected.showTooltipOn = 'always';
  } else { // there is a selected country
    if (selected !== ev.target) {
      // Remove selected properties
      selected.isHover = false;
      selected.showTooltipOn = 'hover';
      selected.hideTooltip(200);
      // select new country
      selected = ev.target;
      selected.isHover = true;
      selected.showTooltipOn = 'always';        
    }
  }
});
```

CodeSandbox - https://codepen.io/AvivHDR/pen/ZEbRdNd

Steps to repreduce:
1. click on  a few countries (see the the tooltip will stay on the last hited country on the)
2. zoom in (make sure that the countries that you previously clicked are in view)

**Comment by martynasma** [comment]
Fixed in [4.9.22](https://github.com/amcharts/amcharts4/releases/tag/4.9.22).

## [4.9.22] - 2020-05-14

### Changed
- Export: Now using forked version of `canvg` until underlying issues are fixed in source library.

### Fixed
- `queue` and `onlyShowOnViewport` were not working properly on regular `Container` instances.
- Export: Garbled IE image exports fixed.
- Some tooltips were reappearing on `MapChart` after their `showToolipOn` was reset back to `"hover"` from `"always"`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
