### ISSUE TITLE
homeText doesn't work on Treemap navigationBar

### ISSUE THREAD

**Issue by rinatio** [amcharts/amcharts4#247]
There's a `homeText` property defined on this example: https://codepen.io/team/amcharts/pen/paXGJj and chart doesn't take it into account.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.46](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.46).

## [4.0.0-beta.46] - 2018-08-19

### Fixed
- `TreeMap.homeText` was not working.
- `TreeMap` used to display upper level bullets/labels when drilled-down.
- `TreeMap` had issues with hiding items using legend (when not using animated state).
- Chart cursor was not visible if data was set directly on axis/series but not on chart.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
