### ISSUE TITLE
Cannot read property 'innerRadius' of undefined since version 4.9.14

### ISSUE THREAD

**Issue by alan-1066** [amcharts/amcharts4#2472]
Hi, Since update 4.9.14 I'm having issues trying to get a radarChart to work as a child. 

Example:
https://codepen.io/alan1066/pen/bGVxwox

This example code works as expected with 4.9.13 but with 4.9.14 and above I get the message "Cannot read property 'innerRadius' of undefined"

Can you help me with this?

Thanks!

**Comment by martynasma** [comment]
Fixed in [4.9.23](https://github.com/amcharts/amcharts4/releases/tag/4.9.23).

## [4.9.23] - 2020-05-19

### Added
- `removedfromqueue` event added to `Sprite`. It is invoked when `am4core.options.queue = true` or `am4core.options.onlyShowOnViewport = true` and the Sprite (chart) is removed from queue (appears on the screen).
- `groupperiodchanged` event added to `DateAxis`. It is invoked when data grouping is on and grouping period is changed.

### Fixed
- JSON: Array value in `snapToSeries` on `XYCursor` was resulting in error.
- `RadarChart` was resulting in an error if used as a column or bullet template in some other chart.
- `AxisRendererRadial.innerRadius` was ignored if set in percent and `RadarChart.innerRadius` was not set.
- Wide charts were being cut off in the middle when printing.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by alan-1066** [comment]
Hi, 

Thanks, The column chart now loads without error but `innerRadius` doesn't appear to work on the radarChart when used in a column chart. 

https://codepen.io/alan1066/pen/bGVxwox

Thanks
