### ISSUE TITLE
Chart cut-out when printing (or puppeteer.pdf)

### ISSUE THREAD

**Issue by Eldair** [amcharts/amcharts4#2482]
**Bug description**

When printing a page the chart is not resized properly causing to be outside of the box or cut out. This started happening with version 4.9.19 (it was all good before that).

I tested it with both puppeteer (print to pdf) and with regular print (ctrl + p) in chrome and new MS edge.

4.9.18 (this is how it should look)
![image](https://user-images.githubusercontent.com/470003/82219793-10507b80-991e-11ea-949c-17da797c7081.png)

4.9.19+
![image](https://user-images.githubusercontent.com/470003/82219539-b2239880-991d-11ea-84c4-2ec6318cd6de.png)

**Environment (if applicable)**

 - amCharts version 4.9.19
 - Browser and its version Chrome/Edge 81

**Comment by martynasma** [comment]
Can you post your chart online where we can reproduce and test it?

**Comment by Eldair** [comment]
Here you go: https://codepen.io/Eldair/full/NWGEvOY
I'm not sure if you'll be able to test it that way. It is much easier to reproduce the issue using puppeeter and it's to pdf function.
If you want I can send you code for that script as well.

**Comment by martynasma** [comment]
Thanks. I'm able to reproduce this with simple Ctrl-P in Chrome:

![image](https://user-images.githubusercontent.com/1458520/82291918-869ebd80-99b2-11ea-9b18-ba63936dcf96.png)

Not sure what's going on here, but will look into it.

**Comment by martynasma** [comment]
Fixed in [4.9.23](https://github.com/amcharts/amcharts4/releases/tag/4.9.23).

## [4.9.23] - 2020-05-19

### Added
- `removedfromqueue` event added to `Sprite`. It is invoked when `am4core.options.queue = true` or `am4core.options.onlyShowOnViewport = true` and the Sprite (chart) is removed from queue (appears on the screen).
- `groupperiodchanged` event added to `DateAxis`. It is invoked when data grouping is on and grouping period is changed.

### Fixed
- JSON: Array value in `snapToSeries` on `XYCursor` was resulting in error.
- `RadarChart` was resulting in an error if used as a column or bullet template in some other chart.
- `AxisRendererRadial.innerRadius` was ignored if set in percent and `RadarChart.innerRadius` was not set.
- Wide charts were being cut off in the middle when printing.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Eldair** [comment]
Confirming it is fixed in the latest release! Thanks a lot
