### ISSUE TITLE
How show numbers as float in cursor info?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#2495]
I have some float parameters in my XY line series.  When cursor over chart info is in integers.
But i need float values. How can i resolve it?

screen
https://monosnap.com/file/4dY5gGvhmO4wvhas5qAMdbUVV25fX7

**Comment by martynasma** [comment]
You can use `ValueAxis` setting [`extraTooltipPrecision`](https://www.amcharts.com/docs/v4/reference/valueaxis/#extraTooltipPrecision_property) for that.

**Comment by CristianoYL** [comment]
I had a similar issue. I noticed that the cursor's xy values are not displayed correctly, and not just because of rounding. I tried setting the extraTooltipPrecision, and although the labels are not displaying extra digits, there are still off by a small margin. My guess is that when hovering over a bullet, the actual coordinate of the cursor is used, instead of the bullet.

The issue exists in the official demo: [https://www.amcharts.com/demos/zoomable-bubble-chart](https://www.amcharts.com/demos/zoomable-bubble-chart/)
 
e.g.: if you hover over the first bullet on the bottom left, Sierra Leone has an avg income of 1072.95788, while the label on XAinx shows 1065. If I update the code and add 
```
valueAxisX.extraTooltipPrecision = 0.0001;
```
The label becomes 1089.74905. The issue is reproducible on both axises and in other charts.

If anyone has any idea on how to fix it, please let me know. Thanks in advance!
