### ISSUE TITLE
Hiding or showing the legend doesn't adjust the chart to the available dimensions

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#25]
[hide](https://www.amcharts.com/docs/v4/reference/legend/#hide_method), [show](https://www.amcharts.com/docs/v4/reference/legend/#show_method) and [setVisibility](https://www.amcharts.com/docs/v4/reference/legend/#setVisibility_method) methods don't re-position or resize the chart.

https://codepen.io/team/amcharts/pen/e2b0557b22dd819159a5ff5dc82d255d/

**Comment by dswitzer** [comment]
Also, the documentation for the legend.disabled property states:

> Controls if element is disabled.
> 
> A disabled element is hidden, and is removed from any processing, layout calculations, and generally treated like if it does not existed.
> 
> The element itself is not destroyed, though. Setting this back to false, will "resurrect" the element.

I read this as that setting `disabled=true` should be like setting the CSS `display:none` on an HTML element, in that the element should be treated as it does not exist.

However, I'm not finding this behavior is true. None of the items that I've tried setting `disabled=true` to that inherit from a Sprite actually cause the canvas to re-layout the element. It's acting more like CSS `visibility: hidden` and `visibility: visible`.

**Comment by martynasma** [comment]
Solved in [4.0.0-beta.28](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.28) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta28---2018-06-05)).

**Comment by dswitzer** [comment]
Should hiding and showing a legend cause the chart to reposition to occupy the space the legend was using?

If so, it's not working properly.

It does work if I use `chart.legend.disabled` to toggle the legend, but using `show()` or `hide()` just toggle visibility without the chart reclaiming the space.

**Comment by martynasma** [comment]
Hm, that's a functional question. Should toggling item visibility also remove it from the layout tree? I tend to think it should not. Sort of like `visibility: hidden` equivalent.

While, `disabled = true` is `display: none`.

**Comment by dswitzer** [comment]
For me, I would expect `show()` and `hide()` to work like `display: none`, but that might just be because that's  the behavior of the common JS frameworks (e.g. jQuery). That doesn't mean I'm right, it was just my expectation. Usually showing or hiding an object removes it from the layout.

I certainly would expect `setVisibility()` to just be the equivalent of the CSS `visibility` property.

I would recommend that the documentation makes it very clear that the `show()` and `hide()` methods don't effect layout and point the user to using `disabled` if they require it be removed from layout.

Anyway, based on expectation, things seem to be working correctly now.

**Comment by martynasma** [comment]
Gotcha. Makes sense.

However, in SVG CSS works a lot differently than in HTML. And we - being SVG charts - are operating under SVG defaults.

In any case, we will discuss if this one more time.

Thanks!
