### ISSUE TITLE
TreeMap chart doesn't hide parent name on drill-down

### ISSUE THREAD

**Issue by rinatio** [amcharts/amcharts4#250]
Given drill-down example: https://codepen.io/rinatio/pen/rrXdMa if you click on the "Other" -> "Tesla" you can still see the "Tesla" title even though following lines removed:
```
// by default only current level series bullets are visible, but as we need brand bullets to be visible all the time, we modify it's hidden state
//level0SeriesTemplate.bulletsContainer.hiddenState.properties.opacity = 1;
//level0SeriesTemplate.bulletsContainer.hiddenState.properties.visible = true;
```
Those are related to the `0` level anyway though.

<img width="1680" alt="screen shot 2018-08-17 at 19 18 34" src="https://user-images.githubusercontent.com/426879/44279867-5d885080-a253-11e8-8a19-49e701473f9f.png">

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.46](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.46).

## [4.0.0-beta.46] - 2018-08-19

### Fixed
- `TreeMap.homeText` was not working.
- `TreeMap` used to display upper level bullets/labels when drilled-down.
- `TreeMap` had issues with hiding items using legend (when not using animated state).
- Chart cursor was not visible if data was set directly on axis/series but not on chart.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
