### ISSUE TITLE
Chart Overlay

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#252]
Hello,

Is it possible to prevent event capture (mousemove) if an item is in front of the chart?

I created an example here:

https://codepen.io/ptorrent/pen/QVWwNe

**Comment by martynasma** [comment]
You can disable all interactions with the chart using this setting:

```
chart.interactionsEnabled = false;
```

Hope it helps.

**Comment by martynasma** [comment]
Not sure if we can reliably know if cursor is over the chart.

Besides your overlay can have move events attached that cancel bubbling up as well.

That said, we will give it some thought. Maybe it's possible to figure out if there's something between cursor and the chart. Or maybe we can make it configurable.

Will keep you posted.

**Comment by ptorrent** [comment]
Thanks !

I tried the amChart modal. It seems that an error appears when I move the mouse on the modal overlay.

https://codepen.io/ptorrent/pen/xaxGEa

![image](https://user-images.githubusercontent.com/6083644/44339151-a3762c00-a480-11e8-9d47-d8913df77587.png)

**Comment by martynasma** [comment]
@ptorrent This last error is now fixed (not released yet). Will let you know when we get the mouse moving thing.

**Comment by ptorrent** [comment]
Thanks !

**Comment by martynasma** [comment]
OK, not moving cursor if something is obstructing plot area is also looking good. Will be in the next version!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.47](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.47).

## [4.0.0-beta.47] - 2018-08-24

### Added
- New series type: `OHLCSeries`.
- `goHome()` method added to `MapChart`. Calling it will reset map to `homeZoomLevel` and `homeGeoPoint`.
- `homeGeoPoint` added to `MapChart`. Allows setting initial `geoPoint` at which map will be centered.
- `homeZoomLevel` added to `MapChart`. Allows setting initial `zoomLevel`.
- `maxPanOut` property added to `MapChart`, with default value `0.7`. It prevents map to be dragged out of the chart area.
- `noRisers` property added to `StepLineSeries`. It allows step line chart without vertical (or horizontal, depending on orientation) lines.
- Step line without risers now allows making Waterfall chart. Example added.
- `startLocation` and `endLocation` added to `StepLineSeries`, that allow controling locations at which step should start/end.
- `maxPrecision` added for `ValueAxis`. Use it to restrict Value axis to show value labels with less than desired precision (set 0 if you only want integers).
- Portugese (Portugal) translation added.

### Changed
- `Cursor` will now not move if there's some element obstructing the chart's plot area, e.g. a popup or some other element outside the chart.

### Fixed
- Series' and axes' tooltips will now correctly inherit formatters.
- Errors when hovering mouse cursor over open Modal.
- JSON: `children` property of `Container`-type objects was not being processed correctly.
- Popup/Modal now sets `aria-label` automatically if title is set.
- Removing bullet template from series or disposing it will remove/dispose all the bullets created from it.
- Tooltips were overlapping each other, fixed for the most part, but might still be some situations where they overlap.
- Changing data for `MapImageSeries` and `MapLineSeries` used to result runtime error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
