### ISSUE TITLE
Label Positioning in Gauge Charts

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#253]
Hello,

I am trying to render a gauge chart with only 3 labels. Hence, I used ranges with labels to achieve that. 
But I am unable to position those labels properly as setting only horizontal and vertical centers are not enough.

I tried setting various properties like dx,dy,location but still I am not able to achieve proper result.

Can you suggest something?

And is there anyway to control the frequency of ticks. I want to render them only with range labels.

https://codepen.io/anon/pen/VGwLEw?editors=0010

**Comment by martynasma** [comment]
You can control position of the Ranges' labels using their [`radius`](https://www.amcharts.com/docs/v4/reference/axislabelcircular/#radius_property) property:

```
labelRange1.label.radius = 30;
```

The radius means distance of label from the axis. (default 15px)

For right-side label you may also need to set its `horizontalCenter = "righ"` so that the `radius` is calculated to its right edge, rather than left one.

---

To show ticks only on Ranges' position, simply set their length at zero on the axis, while at some length for each ranges' ticks:

```
axis.renderer.ticks.template.length = 0;

// ...

labelRange1.tick.length = 10;
```

---

Here's the updated pen:
https://codepen.io/team/amcharts/pen/62b6c1dfe8c06ae6ee9c2fe50c6fb80c/?editors=0010

**Comment by VaishnaviAppannagari** [comment]
Thanks. It's working.

**Comment by martynasma** [comment]
Great!

I'm closing this, but please feel free to post any follow up questions you may have.
