### ISSUE TITLE
disableKey method does not seem to work for adapters

### ISSUE THREAD

**Issue by Scylanth** [amcharts/amcharts4#2530]
Hello,

I have been trying to modify the label text on a Yaxis through a button. Depending on the button's toggle state, the label should appear or disappear. I figured out adapters could do the trick.

But before implementing the button, I wanted to test that disabling/re-enabling the adapter would work. I tried the following code.

https://codepen.io/Scylanth/pen/JjGPwgK

I can't manage to make the enableKey/disableKey work. I could only manage to make it work with the add/remove action. Is this intended?

Thanks in advance.

**Comment by martynasma** [comment]
You seem to be disabling the adapter on the label template. However, disabled status is not being propagated to actual label elements.

We will investigate if we can make disable status to be propagated as well.

**Comment by Scylanth** [comment]
Thank you, in the meantime I will use the add/remove methods (unless if there is a cleaner way of doing it).

**Comment by martynasma** [comment]
OK, so this will be implemented in the next version. I'll ping you here when it's released.

That said, while disabled keys will carry over to the actual labels, you won't be able toggle adapters via template adapter. If at some point you'll need to re-enable those adapters, you'll need to enable them on each individual label instance in `axis.renderer.labels`.

**Comment by Scylanth** [comment]
Great news.

In the meantime I have been trying to force re-evaluating the labels only after clicking on the button. I tried something like this :
chart.yAxes.each((yAxis) => yAxis.renderer.invalidateLabels())
But it does not seem to rewrite the labels

**Comment by martynasma** [comment]
As I mentioned before, modifying adapter status on a template **after** actual label are already created will not propagate the status, even if you invalidate those labels.

**Comment by Scylanth** [comment]
I changed the method in the codepen to use **remove** instead of **disableKey**, I thought this one was working.  Is this method impacted by the bug as well ?

**Comment by martynasma** [comment]
If you remove the adapter before actual labels are created, they should not propagate.

**Comment by Scylanth** [comment]
Indeed, I needed to modify the actuals labels instead. Thank you.

**Comment by martynasma** [comment]
Fixed in [4.9.25](https://github.com/amcharts/amcharts4/releases/tag/4.9.25).

## [4.9.25] - 2020-06-06

### Added
- Global option `am4core.options.autoDispose` added (default `false`). If set to `true`, when chart is being created in a container that has already existing chart, instead of "Chart was not disposed" warning in console, the chart being overwritten will be disposed.
- New plugin: [Range Selector](https://www.amcharts.com/docs/v4/tutorials/plugin-range-selector/). Collection of controls for adding alternative zoom controls for axes.

### Changed
- Disabled callbacks will now carry over to a clone when cloning an Adapter.

### Fixed
- Export: Sometimes background was improperly clipped when upscaling exported image.
- Export: If chart's `data` was updated open `ExportMenu` was forcibly being closed.
- `"Z"` and `"ZZ"` indicators in `inputDateFormat` were being ignored.
- If series had `sequencedInterpolation = true` set and it was hidden via legend, its legend item lost disabled color when chart was resized.
- `bullet.locationX` and `bullet.locationY` was being ignored on a `ColumnSeries` with `CategoryAxis`.
- If a chart's Legend was disposed, it could result in JS errors if chart had an `XYCursor` enabled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
