### ISSUE TITLE
block zoom out on mobile when minzoomlevel set

### ISSUE THREAD

**Issue by jparasha** [amcharts/amcharts4#2536]
[demos/flight-routes-map/](https://www.amcharts.com/demos/flight-routes-map/)
Hi,

on non touch devices I am able to block zoom beyond **minZoomLevel** but on touch devices **pinch to zoom** out goes well beyond minZoomLevel limit. see image below :

![image](https://user-images.githubusercontent.com/18441721/83614385-c238aa80-a5a2-11ea-8682-98e739f26113.png)
Do we have a solution for the same?

Thanks

**Comment by smaheshkumar** [comment]
I am also facing the same issue, when i try to set "minZoomLevel" which is working fine in non-touch devices. Is there any way to apply "minZoomLevel" for touch devices.

**Comment by martynasma** [comment]
It seems that pinch-zoom does not have the `minZoomLevel` check implemented.

We'll need to fix that. Thanks for the heads up!

Will keep you posted about the fix progress.

**Comment by martynasma** [comment]
Fixed in [4.9.29](https://github.com/amcharts/amcharts4/releases/tag/4.9.29).

## [4.9.29] - 2020-07-09

### Changed
- Export: data exported as HTML will now have `<thead>` and `<tbody>` tags.
- `XYChart.getClosest()` method is now public.
- Accessibility: Now pressing ENTER while there's a `MapChart` element focused (using TAB key) will invoke its `hit` event, if set.

### Fixed
- JSON: heat rules referring to series' bullets were not working, e.g. `target: "bullet[0].circle"`.
- IE: More fixes to polyfill overriding.
- `ColorSet` method `next()` would fail if `currentStep` was bigger than `minColors`, affecting `SliceGrouper` plugin setups with a lot of slices in particular.
- On `MapChart` settings `minZoomLevel` and `maxZoomLevel` were being ignored when pinch-zooming.
- Syncing of axes improved, especially when series of one axis were hidden/shown.
- If a `MapSeries` had its geodata loaded via `geodataSource`, the map used to disappear after div size changed.
- Legend had a `maxWidth` set to `200` and this could result labels to be truncated even if there was enough space for them to fit in.
- Ticks/grid could disappear if `ValueAxis` had `min`/`max` set and data of a chart changed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
