### ISSUE TITLE
Cursor movement after disposing of a legend triggers errors

### ISSUE THREAD

**Issue by smcassar** [amcharts/amcharts4#2540]
Receiving the following error after disposing of a legend and moving my cursor over the chart:

![image](https://user-images.githubusercontent.com/25423886/83710171-3cc70000-a65f-11ea-96bd-253dd9f289aa.png)

Appears to happen when a chart has an `XYCursor` and a disposed `Legend`

```ts
  chart.cursor = new XYCursor()
  chart.legend = new Legend()

  // ... series setup, etc

  // call dispose on the legend (eg: due to click event)
  chart.legend.dispose()
```
After disposing of the legend any cursor movement on the chart causes the above error

[CodePen](https://codepen.io/scassar/pen/dyGyBYe)

projects amCharts version: 4.9.19 (replicated in pen using latest version)

**Comment by martynasma** [comment]
Fixed in [4.9.25](https://github.com/amcharts/amcharts4/releases/tag/4.9.25).

## [4.9.25] - 2020-06-06

### Added
- Global option `am4core.options.autoDispose` added (default `false`). If set to `true`, when chart is being created in a container that has already existing chart, instead of "Chart was not disposed" warning in console, the chart being overwritten will be disposed.
- New plugin: [Range Selector](https://www.amcharts.com/docs/v4/tutorials/plugin-range-selector/). Collection of controls for adding alternative zoom controls for axes.

### Changed
- Disabled callbacks will now carry over to a clone when cloning an Adapter.

### Fixed
- Export: Sometimes background was improperly clipped when upscaling exported image.
- Export: If chart's `data` was updated open `ExportMenu` was forcibly being closed.
- `"Z"` and `"ZZ"` indicators in `inputDateFormat` were being ignored.
- If series had `sequencedInterpolation = true` set and it was hidden via legend, its legend item lost disabled color when chart was resized.
- `bullet.locationX` and `bullet.locationY` was being ignored on a `ColumnSeries` with `CategoryAxis`.
- If a chart's Legend was disposed, it could result in JS errors if chart had an `XYCursor` enabled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
