### ISSUE TITLE
Data set with small timeout after setting series isn't rendered

### ISSUE THREAD

**Issue by krystian-wolarek** [amcharts/amcharts4#2547]
**Bug description**

Chart got some initial data. I fetch info about new stats and data for it. If that data comes after stats in few milliseconds (~10) it's not getting rendered.

Reproduced issue with comments in code:
https://codepen.io/codeapi/pen/dyGPYNK

**Additional context**

In above example default values should be form 10 to 20 and after succesful fetch it should be 90-100.
After clicking fetch button, chart sometimes will get updated sometimes not. If in first run u will see correct result use reset btn and fetch once again.

Only solution that works ( commented in example) is to clear yAxes and series, then create them once again but i'm not sure its best way. I tried invalidation, deepInvalidation without success.

**Comment by krystian-wolarek** [comment]
I use Chrome 83.0.4103.97 on Mac Catalina.
![issue](https://user-images.githubusercontent.com/39270768/83779336-18cde380-a68c-11ea-9a14-a34038a9dc6c.gif)

**Comment by krystian-wolarek** [comment]
I can also see this issue on Opera, FF, Safari and Edge on Browserstack. In FF mostly it occurs only after first "fetch" but not alway. In other browsers it's almost always repetitive

**Comment by martynasma** [comment]
OK, yeah, I finally managed to reproduce this after a lot of tries.

My guess is that data update occurs while chart is still updating. Thought that should not be a problem.

We will need to investigate this.

Will keep you posted.

**Comment by zeroin** [comment]
I am investigating this and as a temp solution I could suggest clearing chart data before you add new axes and series to the chart:

`chart.data = [];`

This would be a lot better for performance and would solve the problem. However I imagine scenario where you might not want this and it shouldn't be like this anyway, so I am still looking into it.

**Comment by zeroin** [comment]
OK so here is what happens here:

When you add new series to the chart, it still has old data. In this case we temporary set chart's data to series, so it would process it and after processing we reset series data to empty array. We do this because otherwise each time a new series is added, they would all invalidate and that would be really slow. So the bug you described happens in the middle of the series processing data. As at that moment it has it's own data, setting data on the chart does not affect this series, so it processes old data and is happy about it. And I could not find a proper way to fix it without causing other issues or making it bad for performance. However it's really easy to fix it from outside, by either reseting chart's data to [] before you add series (this would be good for performance) or, if you can not do this, you could reset each series data to [] before setting new chart data:

```
            chart.series.each(function(series){
              series.data = [];
            })
```

**Comment by krystian-wolarek** [comment]
Thanks for fix i will try it out in the upcoming iteration. I will come be back with feedback

**Comment by krystian-wolarek** [comment]
Finally i implemented your suggested solution and it works ok for me. Thank you for investigating it
