### ISSUE TITLE
Export Menu closes after new Data

### ISSUE THREAD

**Issue by JacobDeuchert** [amcharts/amcharts4#2548]
Hi, 
I have a live chart where the data gets updated every second. The chart has an export menu but the export menu automatically closes after new data gets pushed into the chart. I didn't found a property in the docs to prevent this behaviour. 

Reproduced here: [CodePen](https://codepen.io/jacobdeuchert/pen/zYrxqjr)

Thanks!

**Comment by martynasma** [comment]
Fixed in [4.9.25](https://github.com/amcharts/amcharts4/releases/tag/4.9.25).

## [4.9.25] - 2020-06-06

### Added
- Global option `am4core.options.autoDispose` added (default `false`). If set to `true`, when chart is being created in a container that has already existing chart, instead of "Chart was not disposed" warning in console, the chart being overwritten will be disposed.
- New plugin: [Range Selector](https://www.amcharts.com/docs/v4/tutorials/plugin-range-selector/). Collection of controls for adding alternative zoom controls for axes.

### Changed
- Disabled callbacks will now carry over to a clone when cloning an Adapter.

### Fixed
- Export: Sometimes background was improperly clipped when upscaling exported image.
- Export: If chart's `data` was updated open `ExportMenu` was forcibly being closed.
- `"Z"` and `"ZZ"` indicators in `inputDateFormat` were being ignored.
- If series had `sequencedInterpolation = true` set and it was hidden via legend, its legend item lost disabled color when chart was resized.
- `bullet.locationX` and `bullet.locationY` was being ignored on a `ColumnSeries` with `CategoryAxis`.
- If a chart's Legend was disposed, it could result in JS errors if chart had an `XYCursor` enabled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
