### ISSUE TITLE
MapLineSeries does not draw the line to the end

### ISSUE THREAD

**Issue by bcronje** [amcharts/amcharts4#255]
Using version 4.0.0-beta.46

When using `MapLineSeries` with only two points in the line, then then line is not drawn up to the end, it stops before the point. This happens when I use either `multiGeoLine` or `imagesToConnect`. This is very noticeable if zoomed in. To illustrate:

![image](https://user-images.githubusercontent.com/462097/44377517-6dc35880-a4fd-11e8-9c60-fc88e505d7b5.png)

However if I change to either `MapSplineSeries` or `MapArcSeries` the line is drawn perfectly.
With `MapSplineSeries`:
![image](https://user-images.githubusercontent.com/462097/44377570-baa72f00-a4fd-11e8-884a-59582b78e607.png)

With `MapArcSeries`
![image](https://user-images.githubusercontent.com/462097/44377603-d6aad080-a4fd-11e8-9089-feefda3ef7f8.png)

**Comment by martynasma** [comment]
I confirm it is the case.

Here's a working example using `imagesToConnect`:
https://codepen.io/team/amcharts/pen/9a35ac4ec65490972a6ddab2f6f3a69f?editors=0010

![image](https://user-images.githubusercontent.com/1458520/44389474-a0884380-a533-11e8-8277-ba1d730ec75f.png)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.47](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.47).

## [4.0.0-beta.47] - 2018-08-24

### Added
- New series type: `OHLCSeries`.
- `goHome()` method added to `MapChart`. Calling it will reset map to `homeZoomLevel` and `homeGeoPoint`.
- `homeGeoPoint` added to `MapChart`. Allows setting initial `geoPoint` at which map will be centered.
- `homeZoomLevel` added to `MapChart`. Allows setting initial `zoomLevel`.
- `maxPanOut` property added to `MapChart`, with default value `0.7`. It prevents map to be dragged out of the chart area.
- `noRisers` property added to `StepLineSeries`. It allows step line chart without vertical (or horizontal, depending on orientation) lines.
- Step line without risers now allows making Waterfall chart. Example added.
- `startLocation` and `endLocation` added to `StepLineSeries`, that allow controling locations at which step should start/end.
- `maxPrecision` added for `ValueAxis`. Use it to restrict Value axis to show value labels with less than desired precision (set 0 if you only want integers).
- Portugese (Portugal) translation added.

### Changed
- `Cursor` will now not move if there's some element obstructing the chart's plot area, e.g. a popup or some other element outside the chart.

### Fixed
- Series' and axes' tooltips will now correctly inherit formatters.
- Errors when hovering mouse cursor over open Modal.
- JSON: `children` property of `Container`-type objects was not being processed correctly.
- Popup/Modal now sets `aria-label` automatically if title is set.
- Removing bullet template from series or disposing it will remove/dispose all the bullets created from it.
- Tooltips were overlapping each other, fixed for the most part, but might still be some situations where they overlap.
- Changing data for `MapImageSeries` and `MapLineSeries` used to result runtime error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
