### ISSUE TITLE
Transparent color json

### ISSUE THREAD

**Issue by imtrobin** [amcharts/amcharts4#2550]
Hi, how do I set transparent colors in json? They turn out black, either using #ARGB or #RGBA e.g

` "colors":     { "list": [ "#80ec407a", "#1976d280", "#e0e0e080" ] },`

**Comment by martynasma** [comment]
How about using `rgba()` notation?

```
"rgba(128, 236, 40, 0.5)"
```

**Comment by imtrobin** [comment]
It would work but not in my case, because I'm using theme to set the color , and my variable color is #rgba format

**Comment by martynasma** [comment]
Sorry, we don't support RGBA format yet.

I'm chalking it up as an `enhancement`.

Might implement it in one of the upcoming versions.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.9.27](https://github.com/amcharts/amcharts4/releases/tag/4.9.27).

## [4.9.27] - 2020-06-18

### Added
- `ExportMenu` item definition can now have `title` property. If set, it will be added to item's `title` property, which should show a system tooltip on hover.

### Changed
- Hex color parser now supports RGBA format which includes alpha value, e.g. `"#FF000080"` will produce a 50% transparent red.

### Fixed
- Fixed performance issue with a logarithmic `ValueAxis` with `strictMinMax` set to `true`.
- Calculated value of `sum` in the selection of an `XYChart` could include one extra data item, not visible in the selection.
- Pie slices with 0 values were sorted incorrectly in FF.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
