### ISSUE TITLE
"propertyFields" colors in states and legend

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#2563]
I have charts that use `propertyFields` to retrieve colors out of the data. On series interaction, I'm applying a custom state that should also change the colors of the series. The state does get applied but the colors don't take effect. If I don't use `propertyFields` and assign the colors directly to the series, it works fine.

This example Codepen [here](https://codepen.io/sassomedia/pen/KKVVNYB?editors=0010) shows the issue: on rollover of one series' bullets, the other series should hide its bullets and turn grey. On click of the chart background, the states get restored. As the issue shows, only the bullets hide but the color doesn't turn grey. If line 98 & 105 get uncommented and the `propertyFields` commented out, it works as expected for the second series.

A similar issue shows there in the chart legend. When using `propertyFields` for the series, the legend markers don't color properly. And I'm not even able to manually override the marker colors.

What I'm I missing here? Any insight would be great, thanks!

**Comment by sassomedia** [comment]
Forgot to add, if I inspect a series that uses `propertyFields`, the series' color properties are still the default ones, not the ones that were supposed to be assigned with the `propertyFields`. This would explain why the legend shows the wrong colors. It seems like the series carries two different color sets. Not sure if this is by design, I just can't imagine a scenario where this would be useful.

**Comment by pemberdom** [comment]
If I may, I am currently working on a project also using the `propertyFields`, and got a look at the CodePen. It might not solve entirely your issue, but the `color` property in the CodePen dataset does not actually carry a color information. 
If you replace `seriesColor1` and `seriesColor2` by "red", "#00FF00"... any color format accepted by AmCharts, the colors get properly applied:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/45367780/84343317-af9f1200-ab5c-11ea-88c6-96a14aa92e73.png">

<img width="629" alt="image" src="https://user-images.githubusercontent.com/45367780/84343327-b6c62000-ab5c-11ea-9eb6-427e0394336c.png">

About the legend markers, they won't display the colors coming from the `propertyFields` by design, given you can apply multiple colors to a same series (see [this discussion](https://github.com/amcharts/amcharts4/issues/2196) or [that discussion](https://github.com/amcharts/amcharts4/issues/1051) for instance).

On our project we authorize only 1 color per series while using the `propertyFields`, so we override the legend markers `fill` and `stroke` by using adapters that read the dataset and apply the proper styles.

Hope it helps a bit!

**Comment by pemberdom** [comment]
A precision:
replacing `const seriesColor1 = am4core.color("#BD407F");` by `const seriesColor1 = "#BD407F";` should also work

**Comment by sassomedia** [comment]
@pemberdom Thanks for your reply, although I think you misunderstood my use case there. I'm not trying to color sections of the series. It's only one color per series and the ones specified are applied correctly. However, I do need the color to change when the state changes and that is not working. It only works when the data is directly applied to the series but not when I use `propertyFields`.

Expected on dots rollover on Series 1:
<img width="1253" alt="Expected" src="https://user-images.githubusercontent.com/5614099/84346708-8d080a00-abeb-11ea-92e3-46aebe2ef4ab.png">

Actual:
<img width="1246" alt="Actual" src="https://user-images.githubusercontent.com/5614099/84346732-9beebc80-abeb-11ea-9572-e9a1355e4206.png">

`const seriesColor1 = am4core.color("#BD407F");` is actually perfectly valid and is supposedly the recommended way of specifying colors for amCharts according to the documentation. In fact, using `const seriesColor1 = "#BD407F";` breaks the `series1.tensionX = 0.8;` as you can see in your screenshot.

The note about the different colors per series and the legend makes sense I guess. Completely missed those discussions, my bad. It seems a bit wasteful though if it's all the same color. I think I tried overriding this with an adapter at some point but I could not get it to work. I give this another try knowing that it does work. Thanks for that confirmation!

**Comment by martynasma** [comment]
`propertyFields` overrides state. I'm afraid we won't be changing that behavior.

You already are iterating through bullets and hiding them. I suppose you could iterate through segments and set color manually.

Another option would be to apply desaturate filter to the whole series. However, filters are slow. If you have a chart with a lot data points/segments that is not the best option.

As for the legend, `propertyFields` does not make a lot of sense, since those are to tie specific data item to specific value, whereas legend represents series, not specific data items.

Hope this makes sense.

**Comment by sassomedia** [comment]
Alright, that is unfortunate. I can make it work without the `propertyFields`, it just takes a bit away from consistency. I'm basically building a set of preconfigured charts that the rest of the team can merely just drop in, without having to understand how amcharts work. `propertyFields` would have made that much easier.

I get the legend part although, since I'm not going to be using `propertyFields`, this won't be an issue anyway. The colors work fine when directly assigned to the series.

Thanks!
