### ISSUE TITLE
Scrollbar `start` and `end` update

### ISSUE THREAD

**Issue by ilueckel** [amcharts/amcharts4#2583]
**Bug description**

Updating the `end` or `start` value of a `Scrollbar` via javscript code does update the chart only the first time. After the scrollbar visuals update, but not the data on chart (until you grab the scrollbar handles with the mouse).

I expect the chart to update the data each time I update the `end` or `start` value.

Here is a fiddle reproducing the problem: https://jsfiddle.net/ay170jq2/2/

I'm using:

* the latest amcharts version 
* Chrome and Firefox

**Comment by martynasma** [comment]
It's a known issue, but not fixable right now, I'm afraid.

There are two workarounds:

1) Set `start` end `end` on your axis instead of scrollbar.

2) Set private property `_skipRangeEvents` to `false` on your scrollbar just after setting `start` or `end`.

The latter is not pretty, but it will preserve the zoom animation :)

**Comment by ilueckel** [comment]
Alright, workaround 1 works fine for my use case.
