### ISSUE TITLE
Pie chart slices may flicker when hovering the "inside" border

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#26]
Slices may flicker when it's selected and the cursor stays over the border facing the center of the pie.

![flickering](https://user-images.githubusercontent.com/174226/40038116-5121f87e-57c5-11e8-9895-da563e35b5d7.gif)

**Comment by martynasma** [comment]
This is tricky. Slide out happens on hover. If cursor is close to the edge, it may become not above the slice, which in turn triggers out event and sliding in :)

Fixing this would require a lot of fuzzy logic, and we're trying to avoid that.

The issue is not as prominent when using Animated theme.

At this point I'm going to shelve this as a non-issue, until we figure a logical way to avoid it, such as using better defaults, or something similar.

**Comment by JeanPerriault** [comment]
Hi, @martynasma you stated you may figure a "logical way to avoid it", are there any progress on this? I've seen that using animated theme kind of reduce the flickering, but this is still there, especially when using thin slices (see https://codepen.io/jeanperriault/pen/wvgqgGr). Could you point me to the code handling this hover mechanism? Couldn't some debounce help?
