### ISSUE TITLE
Changing active and hover state colors for the zoom button

### ISSUE THREAD

**Issue by jaischeema** [amcharts/amcharts4#263]
Hi,

I am trying to customize the active and hover state colors for the zoom out button but haven't found anything that could help. I have been able to change the background color by changing the fill color on the background rectangle, not sure if this is correct way either:
```js
chart.zoomOutButton.background.fill = am4core.color("red");
```

I am not even sure if this is the right place to ask this question. If it is not, can you please redirect me to general QA forum that you recommend for these sort of questions?

Cheers

**Comment by notacouch** [comment]
No worries, you're in the right place and you're on the right track.

The `background` property is the correct place to style things for a `Button` as they extend `Container`s. Check out the tutorial on `Container`s:
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Styling_containers

To style the button on certain user interactions, you would style the relevant `SpriteState` property of its background. See our tutorial on States:
https://www.amcharts.com/docs/v4/concepts/states/

The three relevant states in this case are `default`, `hover`, and instead of "active" it would be `down`.

Here's an example:
https://codepen.io/team/amcharts/pen/a8c408622eabc3c75f2291886a7eea78/?editors=0010

**Comment by jaischeema** [comment]
Awesome, that is exactly what I was looking for. Thank you!
