### ISSUE TITLE
The overlay test applied to a label always returns true

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2652]
Hello! I want to display along with the city-label a rectangle marking the city location, but I want this rectangle to stay always visible so I can see where a potential location is even if the rectangles are overlapping themselfs (on a large view of the map).
I also want to hide labels if they are overlapping, for this I am using the `hitTest()` function but here I face problems.

![image](https://user-images.githubusercontent.com/37619567/86104092-43159400-bac6-11ea-9e4b-eff56891805c.png)

https://codepen.io/directcuteo/pen/rNxmjdj
As you  can see in the codePen, a `Sprite` has 2 children: `Rectangle` and `Label`.
I am checking the Label of the Sprite for overlapping with the other Labels of the other Sprites, but the `hitTest()` function is returning `true` for every single one of the Labels and they are all hidden in the end.
I am not sure why this happens. Can you check it out? Thank you!

**Comment by zeroin** [comment]
As I mentioned in a previous question about hitTest, the hitTest will work only for the sprites in the same level (added to the same parent). Each label is in some MapImage, so their coordinates are quite the same, that's why you get true all the time. I could suggest to create your custom hitTest method where coordinates are corrected using `am4core.utils.spritePointToSprite` method: https://www.amcharts.com/docs/v4/reference/utils_module/#spritePointToSprite_method

**Comment by directcuteo** [comment]
I understand. Didn't know having same parent matters also. Thanks for the suggestion.
