### ISSUE TITLE
syncWithAxis breaks when toggling series

### ISSUE THREAD

**Issue by thefat32** [amcharts/amcharts4#2669]
**Bug description**

When using syncWithAxis option for multiple value axes, sometimes toggling a series breaks the axes sync (so different grid lines would appear in the chart for every axes. I could reproduce this in official demo located at:

https://www.amcharts.com/demos/multiple-value-axes/

Result after playing around with first and second series toggle about 3 times:

https://imgur.com/a/EGxAowk

**Environment (if applicable)**

Every Browser
amCharts 4.9.16

**Additional context**

I could give any other example of this if necessary

**Comment by martynasma** [comment]
Fixed in [4.9.29](https://github.com/amcharts/amcharts4/releases/tag/4.9.29).

## [4.9.29] - 2020-07-09

### Changed
- Export: data exported as HTML will now have `<thead>` and `<tbody>` tags.
- `XYChart.getClosest()` method is now public.
- Accessibility: Now pressing ENTER while there's a `MapChart` element focused (using TAB key) will invoke its `hit` event, if set.

### Fixed
- JSON: heat rules referring to series' bullets were not working, e.g. `target: "bullet[0].circle"`.
- IE: More fixes to polyfill overriding.
- `ColorSet` method `next()` would fail if `currentStep` was bigger than `minColors`, affecting `SliceGrouper` plugin setups with a lot of slices in particular.
- On `MapChart` settings `minZoomLevel` and `maxZoomLevel` were being ignored when pinch-zooming.
- Syncing of axes improved, especially when series of one axis were hidden/shown.
- If a `MapSeries` had its geodata loaded via `geodataSource`, the map used to disappear after div size changed.
- Legend had a `maxWidth` set to `200` and this could result labels to be truncated even if there was enough space for them to fit in.
- Ticks/grid could disappear if `ValueAxis` had `min`/`max` set and data of a chart changed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
