### ISSUE TITLE
Disable 'Chart was not disposed' warning at chart level

### ISSUE THREAD

**Issue by RichardCosta10** [amcharts/amcharts4#2688]
Amcharts doesn't cater for cacheing charts due to [always showing a warning](https://github.com/amcharts/amcharts4/blob/16820e250b3cd887b1e891917d48ee7846fb43b1/src/.internal/core/utils/Instance.ts#L133) when a chart is removed from the DOM however there are some instances where this may be desired such as using Vue's [keep-alive functionality](https://vuejs.org/v2/api/#keep-alive)  to cache views of a SPA and avoid rendering charts again. The cacheing works but the warnings are irrelevant as the intention is not to dispose the charts. 

The warnings are useful but in the case above it becomes harder to know which ones to pay attention to and the tendency is to ignore them instead.

It would be useful to be able to disable this warning for individual charts to fix the incompatibility with keep-alive and that way we know the warnings we are seeing are relevant.

**Comment by martynasma** [comment]
We're adding a new global option `am4core.options.suppressWarnings` in the new version about to be released.

Sorry, we decided against chart-level warning suppression setting. Currently all error/warning/dispose check settings are global. It would be inconsistent to have it on chart-level, as well as would add additional weight to all objects.

**Comment by martynasma** [comment]
Fixed in [4.9.30](https://github.com/amcharts/amcharts4/releases/tag/4.9.30).

## [4.9.30] - 2020-07-10

### Added
- `am4core.options.suppressWarnings` global option added (default: `false`). If set to `true`, the charts won't output any warnings into console (e.g. "Chart was not disposed").

### Fixed
- Drill-down map with `geodataSource` problem fixed (since last release only).
- Issues with cursor/tooltip and other element positioning fixed, when chart was being initialized outside of DOM (no container on init).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by RichardCosta10** [comment]
@martynasma, thanks for the prompt response! Disabling all warnings is not ideal since the warnings are still useful for the non-long lived charts. It might hide other potential problems and any future amcharts warnings. Ideally it should be possible to disable the actual check in order to avoid the incorrect warning and the overhead associated with it. Should I open an enhancement for this?

**Comment by martynasma** [comment]
I understand. However, we have made the decision of not implementing this on a per-chart basis.

The main reason for the decision is that we have a hierarchy of classes. Most of those can be a standalone instance of an amCharts - not necessarily a chart.

Adding this setting to a base class would mean that every single element on the chart has it. With hundreds, even thounsands of elements, that is a considerable additional (and quite unnecessary) additional burden on memory footprint, which we are not willing to do.

Hence the one global variable.

Hope you find it reasonable.
