### ISSUE TITLE
Rendering speed performance

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#2720]
Hi,

We upgraded v3 -> v4 this year and are trying to roll it out, but there's been a lot of push back due to performance issues. When we did the upgrade, we kept nearly all of our configurations the same for charts and the only differences were to get things like paddings and such to match between both versions. We do include adapters and such for rendering things like certain number formats and colors, but even the majority of that setup was carried over almost verbatim from our v3 setup.

With that said, on an example page, we render 48 charts - half are a very simple gauge chart and the other half are column/line charts with no more than about 16 columns. When we render these, both render sequentially - meaning when one chart has rendered and the ready function is called, the next chart renders, and so on.

For v3, we use `chart.addListener('rendered', onChartReady);` to determine when a chart is done rendering.
For v4, we use `chart.events.on('ready', onChartReady, this);` to determine the same end event.

So, the setup is nearly identical on chart params and data setup, the way each chart renders is identical, and we basically can flip a flag to say if v3 or v4 can render.

In this 48 chart page, v3 loads on average about 13 seconds. v4 always loads about 3x that time at 35 seconds on average. I'm trying to get people to upgrade because v3 is no longer in support, but when there is a 3x increase in load times, nobody wants to do it.

We've gone through all the suggestions here https://www.amcharts.com/docs/v4/concepts/performance/ as well. To clarify on the points in there:
- we don't use animations
- we don't use transparency
- data is common between v3 and v4 and we use all labels as strings (e.g. no date axis or anything)
- in this example, data points are quite minimal per chart, so all the recommendations on "lots of data" don't apply
- we don't do any custom complex shapes or added elements to the graphs
- we don't do the built-in queue or viewport settings, as we have our own queue management, as outlined above.

Do you have some suggestions on how we might be able to speed this up?

Also, this is all tested on latest chrome with the dev tools closed (due to the disposer issue that is still not resolved in chrome: https://github.com/amcharts/amcharts4/issues/2429)

Another afterthought - could this be related to how charts are told to render to the page? In v4, we write the chart to the page element, then set all of the various chart configs. In v3 it is the opposite, where we create the chart configs, then call `chart.write(element);`. Seems like the latter would be much more performant, since it can create all the configs without running through all the mutating that v4 seems to be doing.

**Comment by martynasma** [comment]
This is due to fundamental differences how the two versions treat rendering.

V3 did not have any queuing whatsoever. If there were 50 charts on the page, they were just building all at the same time. Naturally that was resulting in faster speed to screen, but it also meant that CPU was fully hogged and browser/tab completely frozen until charts were there.

V4 employs chunked rendering approach. Meaning that we build stuff in chunks, giving CPU some breathing space, so that there's no freezing. The gradual render/data parsing is applied even within a single chart instance. It results in slower time to screen.

V4 is also much much more complex and thus flexible than its predecessor, so there's also more elements to paint and consider, which adds up when you have a lot of charts.

These are the two conceptual approaches, and I don't think we can do anything at this point to make V4 multi-chart performance match V3's.

**Comment by runfaj** [comment]
@martynasma That's good to know. So, in theory, if I were to rotate in a new set of charts every couple minutes on a loop, we'd expect v4 to be more performant in general, even though it takes longer to render each time? I ask this scenario because we also have seen v4 crashing lately on some of our lower memory devices (like a chromebit) under this scenario whereas v3 never had this issue with the same staggered loading approach.

> These are the two conceptual approaches, and I don't think we can do anything at this point to make V4 multi-chart performance match V3's.

I wonder if it would be possible to build in some sort of flag that allows the same scenario I mentioned at the end of the original question - namely, maybe it would be possible to skip all the observing that v4 does and do calculations and rendering separately. If we could have the calculations happen before we actually render things to the page, I'm confident that would drastically speed things up.

**Comment by martynasma** [comment]
> So, in theory, if I were to rotate in a new set of charts every couple minutes on a loop, we'd expect v4 to be more performant in general, even though it takes longer to render each time?

Yes. I suppose it would.

> I wonder if it would be possible to build in some sort of flag that allows the same scenario I mentioned at the end of the original question - namely, maybe it would be possible to skip all the observing that v4 does and do calculations and rendering separately.

I'm afraid that would be complicated. Would require an overhaul of the core rendering system which relies on queuing operations and reusing browser's `requestAnimationFrame()` for processing. V3 was very "brutal" in that regard, just going at it in a linear fashion. I suppose it could get away with it because it was much more simpler than V4.

> If we could have the calculations happen before we actually render things to the page, I'm confident that would drastically speed things up.

I don't think that's possible. Chart is creating a lot of work when parsing data. Theoretically it's probably possible to emulate that work, but I don't want to go there :)

**Comment by runfaj** [comment]
Thanks for clarifying! This helps give some insight we can help explain things as questions arise.
