### ISSUE TITLE
Wrong tooltip position in small browser/charts

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2742]
**Bug description**

If browser size is very small (from the beginning) the x axis tooltip position is not always correct.
(Usecase: small charts shown in IFrames - so limited size available)

Screenshots from pen https://codepen.io/chrisadler/pen/GRoLYwd
(Place editors left so preview frame could easily resized)

Tooltip cut off
![image](https://user-images.githubusercontent.com/58069494/88534332-23f81c80-d008-11ea-9d0b-5c5c9c892f63.png)

Tooltip not connected to the cursor.
![image](https://user-images.githubusercontent.com/58069494/88534495-7f2a0f00-d008-11ea-8bb2-d59536095014.png)

**Environment (if applicable)**

 - amCharts version: 4.9.31 (and earlier)
 - Browser and its version: all Browsers

**Comment by martynasma** [comment]
Fixed in [4.9.34](https://github.com/amcharts/amcharts4/releases/tag/4.9.34).

## [4.9.34] - 2020-07-31

### Added
- New bullet `ShapeBullet` in `Bullets` plugin. Please refer to [this documentation article](https://www.amcharts.com/docs/v4/tutorials/plugin-bullets/) for more info.
- `treatZeroAs` added to `ValueAxis`. Use it to work around zero-value restriction on a logarithmic scale.
- `stackToNegative` (default: `true`) added to `XYSeries`. Determines whether negative values in a stack will stack in relation to base (zero) line (`true`; default) or in relation to the previous value in the stack (`false`).

### Changed
- [xlsx](https://www.npmjs.com/package/xlsx) dependency was updated from `0.15.4` to `0.16.4`.
- Tooltip snapping on `DateAxis` now takes Series' location into account.

### Fixed
- Regression plugin: `reorder` option was not working properly.
- `snapToSeries` was not working properly if there was a hidden Series with exactly the same value as the other visible Series.
- `TreeMap` and `ForceDirectedTree` with a single data item and no children were not working properly with chart legend.
- Horizontal (X) Axis tooltip in a very small document was sometimes positioned with an offset.
- `zoomToRectangle()` method of `MapChart` with `deltaLongitude` was not working properly if a rectangle crossed the 180 meridian.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
