### ISSUE TITLE
Security: Issue with xlsx < 0.16.0

### ISSUE THREAD

**Issue by c-frater** [amcharts/amcharts4#2743]
**Bug description**
We're using `@amcharts/amcharts4` and our Snyk testing shows an error for the version of `xlsx` that you have

See here for more details on the issue in particular: https://snyk.io/vuln/SNYK-JS-XLSX-585898

The resolution is to update xlsx to a `0.16.0` version

**Environment (if applicable)**
 - amCharts version: 4.9.33 [paid licence]

**Comment by martynasma** [comment]
Thank you for bringing this to our attention. We're investing this.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.9.34](https://github.com/amcharts/amcharts4/releases/tag/4.9.34).

## [4.9.34] - 2020-07-31

### Added
- New bullet `ShapeBullet` in `Bullets` plugin. Please refer to [this documentation article](https://www.amcharts.com/docs/v4/tutorials/plugin-bullets/) for more info.
- `treatZeroAs` added to `ValueAxis`. Use it to work around zero-value restriction on a logarithmic scale.
- `stackToNegative` (default: `true`) added to `XYSeries`. Determines whether negative values in a stack will stack in relation to base (zero) line (`true`; default) or in relation to the previous value in the stack (`false`).

### Changed
- [xlsx](https://www.npmjs.com/package/xlsx) dependency was updated from `0.15.4` to `0.16.4`.
- Tooltip snapping on `DateAxis` now takes Series' location into account.

### Fixed
- Regression plugin: `reorder` option was not working properly.
- `snapToSeries` was not working properly if there was a hidden Series with exactly the same value as the other visible Series.
- `TreeMap` and `ForceDirectedTree` with a single data item and no children were not working properly with chart legend.
- Horizontal (X) Axis tooltip in a very small document was sometimes positioned with an offset.
- `zoomToRectangle()` method of `MapChart` with `deltaLongitude` was not working properly if a rectangle crossed the 180 meridian.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
