### ISSUE TITLE
Modal / element obstructing chart's plot area - mouse events are still interpreted

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#277]
Events like mouseClick, mouseDown... are still catch and interpreted by chart when are under another element.
If we have 
`chart.cursor = new am4charts.XYCursor();
chart.cursor.behavior = 'zoomXY';` 
we can still zoom the chart from the element over the chart.

![modal-zoom](https://user-images.githubusercontent.com/21243081/44618370-1fa3b180-a87d-11e8-8f2e-40ee60a64c35.gif)

PS: In my case I have some sliders on the modal element on top of chart, and trying to move them will zoom the chart under and also lock the sliders - cannot move them.
![amcharts-overlay](https://user-images.githubusercontent.com/21243081/44618132-d94c5380-a878-11e8-9f7c-0afb47a0cd7a.PNG)

**Comment by martynasma** [comment]
Yup, thanks for the heads up.

We did make cursor numb to moves when those are happening on an obstructing element, but it seems the zoom is still happening.

We'll fix that.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.48](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.48).

## [4.0.0-beta.48] - 2018-08-31

### Added
- `useWebFonts` setting in `Export`. Allows disabling of download of web fonts when exporting.
- `useRetina` setting in `Export`. Images are now exported scaled up on retina displays by default. Set `useRetina = false` to disable.

### Changed
- Export fallback mechanism for older browsers changed from FabricJS to canvg, which is much lighter and has better text formatting support.
- On retina displays images will now export supersized in order not to lose quality. Set `useRetina = false` to disable.
- amCharts logo will now auto-hide on supersmall chart sizes.

### Fixed
- Cursor was zooming the chart even if drag motion was performed on an external element positioned over the chart.
- Cursor was not hidden when it was no longer hovering the chart area if chart had no padding.
- `urlTarget` was not carried over from `ListTemplate` template to new items.
- Cursor could cause chart to freeze up on a DateAxis with empty cells in the axis' beginning or end.
- Export will now correctly handle web fonts, such as Google Fonts. Please note that FontAwesome is not supported, since they forbid any kind of usage, except inclusion via CSS.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
