### ISSUE TITLE
DateAxis.timezoneOffset is not working

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2774]
When the data is using my [local timezone +10:00](https://codepen.io/aglalexfan/pen/poyJxqb?editors=0010), it is working fine:
![image](https://user-images.githubusercontent.com/46702190/89857825-73317600-dbe0-11ea-9788-e5a607356cc0.png)

When the data is using [different timezone like +06:30](https://codepen.io/aglalexfan/pen/qBZdJxV?editors=0010), it breaks the graph with the line being cut off and the X axis labels all wrong:
![image](https://user-images.githubusercontent.com/46702190/89858131-2c904b80-dbe1-11ea-9a75-4c1ef60ca6d5.png)

Is there any way to make the second demo look exactly the same as first?

**Comment by martynasma** [comment]
This is already being handled via amCharts helpdesk. If you don't mind, I'm going to post the same solution provided in our response, just in case anyone else might be running into the same.

The issue is with that min and max does not take timezone offset into account.

The solution is to recalculate your min/max accordingly:

```JavaScript
// date createt to find out users timezone
var date = new Date();

// this is required, as if we set min/max before dada is parsed, a wrong base interval might be chosen
dateAxis.baseInterval = {timeUnit:"minute", count:1};

// adjust min/max
dateAxis.min = Date.parse("2020-05-05T00:00:00+10:00") + (date.getTimezoneOffset() - dateAxis.timezoneOffset) * 60000;
dateAxis.max = Date.parse("2020-05-05T20:00:00+10:00") + (date.getTimezoneOffset() - dateAxis.timezoneOffset) * 60000;
```

Setting `baseInterval` is also important because automatic interval detection is not reliable, especially with offset data.

Here's live version:
https://codepen.io/team/amcharts/pen/1cb60d5dc145599d1df8b94ee8af6f20
