### ISSUE TITLE
Hidden series on stacked column series still occupy space

### ISSUE THREAD

**Issue by mihaela-kokoon** [amcharts/amcharts4#2791]
**I'm missing something or possible bug: on a chart with stacked series, when hiding one series, it still occupies space when zooming out**

So I have a chart with grouped data (by months and days) and stacked column series and a custom legend where I toggle the series visibility like in the docs https://www.amcharts.com/docs/v4/tutorials/toggling-series-via-api/
Something at least weird happens, but I'm not sure if it's a bug or I'm missing something.
If I zoom in the chart (the series will be grouped by days) and hide one series, then I zoom out, the stacked series are not repositioned. Meaning the stacked columns on the one which was hidden are hanging in the air. It looks like although the series is hidden, it still occupies the space. Would it be possible to prevent this or have the grouping happen only on visible ones?
In the attached GIF, you may see that when I zoom out the darker-blue columns are still positioned where they were when the lighter blue ones were visible. I would have expected the dark ones to be at the bottom.
Thank you!

![ezgif com-optimize](https://user-images.githubusercontent.com/64415990/90154103-6785b100-dd92-11ea-9b22-7bd8069cab7d.gif)

**Comment by zeroin** [comment]
Could you prepare a codepen of this situation? It would help a lot.

**Comment by mihaela-kokoon** [comment]
Yes, I will try to make a codepen tomorrow. Btw, do you have some basic React + amchart4 Sandbox/Codepen that I could fork? I noticed that in the issue template there is no link to a template. Take care! And thanks for answering so quick! 😉

**Comment by mihaela-kokoon** [comment]
Or I'll fork one of the codepen demos from the docs site 😉

**Comment by mihaela-kokoon** [comment]
Hi again. Here is the CodePen reproducing the issue. Thank you!

https://codepen.io/ella301/pen/QWNyXXK

**Comment by mihaela-kokoon** [comment]
I added steps to reproduce in the CodePen, but here's also a GIF. 💙 
![ezgif com-optimize](https://user-images.githubusercontent.com/64415990/90240682-64da9880-de32-11ea-8bfb-b76f1bfd1658.gif)

**Comment by zeroin** [comment]
Thanks a lot for a codepen, I am investingating this issue and will let you know when it's solved..

**Comment by mihaela-kokoon** [comment]
Thank you! Much appreciated!

**Comment by martynasma** [comment]
Fixed in [4.9.36](https://github.com/amcharts/amcharts4/releases/tag/4.9.36).

## [4.9.36] - 2020-08-20

### Added
- New adapter on `XYSeries`: `groupDataitem`. When data grouping occurs, each aggregate data item will be passed through this adapter, where you can modify its aggregate value. [More info](https://www.amcharts.com/docs/v4/tutorials/using-custom-functions-for-data-item-grouping/).
- Two new `MapPolygonSeries` properties: `sortPolygonsBy` ( `"area"` (default), `"name"`, `"longitude"`, `"latitude"`, `"id"`, and `"none"`) and `sortPolygonsReversed` (default `false`).

### Fixed
- Export: `fontSize` option was being ignored when exporting data in PDF.
- Better format object type checks in `DateFormatter` and `NumberFormatter`.
- Older (non-Chromium) EDGE browser was not showing patterns in the legend markers.
- If a stacked series was hidden with data item grouping enabled and then axis zoomed in or zoomed out so that group perdiod changes, series were stacked on the wrong position.
- `CircularAxis` line was flickering while start/end angle was animating.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
