### ISSUE TITLE
Angular ssr build not working, addEventListener is not defined

### ISSUE THREAD

**Issue by Paru9445** [amcharts/amcharts4#2802]
While creating an angular ssr build, the code compiled successfully but got an error while running the project.
I am using the following 2 libraries:-
    "@amcharts/amcharts4": "^4.9.35",
    "@amcharts/amcharts4-geodata": "^4.1.16",

The error seems like this:-

Compiled successfully.
/home/praveen/Desktop/cmt/dist/cmt/server/main.js:57886
        addEventListener("beforeprint", function () {
        ^

ReferenceError: addEventListener is not defined
    at new Registry (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:57886:9)
    at Module../node_modules/@amcharts/amcharts4/.internal/core/Registry.js (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:58100:16)
    at __webpack_require__ (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:26:30)
    at Module../node_modules/@amcharts/amcharts4/.internal/core/System.js (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:67413:67)
    at __webpack_require__ (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:26:30)
    at Module../node_modules/@amcharts/amcharts4/core.js (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:111639:79)
    at __webpack_require__ (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:26:30)
    at Object../src/app/dashboard/dashboard.component.ts (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:362688:17)
    at __webpack_require__ (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:26:30)
    at Object../src/app/app-routing.module.ts (/home/praveen/Desktop/cmt/dist/cmt/server/main.js:361736:31)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:36587
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cmt@0.0.0 dev:ssr: `ng run cmt:serve-ssr`
npm ERR! Exit status 1

Thanks in advance

**Comment by martynasma** [comment]
Which version of TS and Angular are you running?

**Comment by Paru9445** [comment]
"ts-node": "~8.3.0",
"tslint": "~6.1.0",
"typescript": "~3.8.3"

"@angular/cli": "~9.1.6",
"@angular/compiler-cli": "~9.1.7"

in case you need it :- "@types/express": "^4.17.0",

**Comment by Paru9445** [comment]
Hey everone,
Please try to resolve this issue 

https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/
The given link has issues, cause the above example is also not working in ssr build, please help me out with this

**Comment by martynasma** [comment]
We'll provide a solution to run amCharts 4 with SSR with the next version.

Will let you know details when the new version is out. Possibly by the end of this week.

**Comment by Paru9445** [comment]
Okay thank you so much for the reply, my client is behind for this only, WIll wait for the updated version, thank you so much

**Comment by Paru9445** [comment]
Hey is this sorted???

**Comment by martynasma** [comment]
Not yet. As I mentioned, we'll notify you here when new version is out.

**Comment by martynasma** [comment]
Fixed in [4.10.0](https://github.com/amcharts/amcharts4/releases/tag/4.10.0).

## [4.10.0] - 2020-09-01

### Added
- New `LineSeries` property: `smoothing` (`"bezier"` (default), `"monotoneX"`, and `"monotoneY"`) - indicates algorithm to use for smoothing the lines. Monotone algos are better suited for irregularly-spaced data. [More info](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Alternate_smoothing_algorithm).
- `ForcedDirectedTree`: new property `zoomable` (default: `false`). If set to `true`, the chart will be zoomable/draggable using mouse, touch, or API. [More information](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming).
- `ForcedDirectedTree`: zoom related properties added. `mouseWheelBehavior` (`"zoom"`, `"none"`) - controls what happens when mouse wheel is used over chart; `zoomStep` (default: `2`) - step to increase zoom level my each zoom in; `zoomOutButton` - an instance of button which is shown when chart is zoomed in.
- `ForcedDirectedTree`: new zoom-related methods: `zoomToPoint(point, level, center)` and `zoomToDataItem(dataItem, level, center)`;
- New global function: `am4core.createDeferred(callback, scope, ...parameters)`. Can be used to create multiple charts in a truly safe daisy-chain (next chart starts to be instantiated only when previous triggers a `ready` event). Returns a `Promise` with chart instance. [More information](https://www.amcharts.com/docs/v4/concepts/performance/#Deferred_daisy_chained_instantiation);
- New global option: `am4core.options.deferredDelay` (default `100`). Specifies time-gap in milliseconds between deferred chart instantiations.

### Changed
- Added date ordinal translations for Chinese locales.

### Fixed
- Accessibility: `readerTitle` was not being properly populated with data on `Label`.
- Accessibility: `readerDescription` was not being populated with data.
- Now works with Angular Universal SSR. Please refer to our [Angular doc](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) for instructions on how to structure your app for SSR to work properly.
- When `MapChart` was panned with inertia and a polygon with `zoomToObject()` hit event was clicked when the map was still moving, the map was zooming into a wrong position.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
