### ISSUE TITLE
Legend markers showing up black in 4.9.36

### ISSUE THREAD

**Issue by mccahan** [amcharts/amcharts4#2815]
**Bug description**

Legend markers are showing up as black in the latest version, e.g. in this this official example from the documentation:

![image](https://user-images.githubusercontent.com/2308923/90835171-1aad5780-e309-11ea-9145-0498f0b83c82.png)
https://codepen.io/team/amcharts/pen/XqPbYd

Example works correctly if I substitute in https://cdn.amcharts.com/lib/version/4.9.35/core.js

**Environment (if applicable)**

Confirmed in Chrome (84.0.4147.125), Safari (13.1.2), and Firefox (79.0) on macOS Catalina 10.15.6

**Additional context**

**Comment by martynasma** [comment]
Fixed in [4.9.37](https://github.com/amcharts/amcharts4/releases/tag/4.9.37).

## [4.9.37] - 2020-08-21

### Fixed
- Colors for markers in Legend with `useDefaultMarkers = true` were broken since last release.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
