### ISSUE TITLE
Unable to access data item of a legend on hit event

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#284]
Hello,

I want to access the value attached to the legend on its hit event. At present event.target.dataItem is undefined.

Should I set any properties to enable that?

Example:
https://codepen.io/anon/pen/vzGxBo?editors=0010

**Comment by notacouch** [comment]
Hi,

It's not clear to me what you're trying to achieve.

If you're looking to check the `dataItem`s of the Legend's items (e.g. when clicking "Research", "Marketing", or "Sales" in the example provided), you can handle the legend's `itemsContainer` template hit event instead of the legend itself:

```
chart.legend.itemContainers.template.events.on("hit", function(event) {
 console.log(event.target.dataItem);
});
```

Here's the legend documentation:
https://www.amcharts.com/docs/v4/concepts/legend/#Handling_events

Example:
https://codepen.io/team/amcharts/pen/4541dfbda389ca5e76b91569ae606a62/

Let me know if that works.

Otherwise can you clarify what you were trying to do with data directly on the legend? The documentation link above also has a section on custom data items, if that's what you were looking to do:
https://www.amcharts.com/docs/v4/concepts/legend/#Adding_custom_items

**Comment by kimhe5623** [comment]
It doesn't work for my computer :(
