### ISSUE TITLE
Mobile hover

### ISSUE THREAD

**Issue by adamalexandru4** [amcharts/amcharts4#2856]
Hello, is there any way to disable hover on mobile ? 
When the user try to zoom in the MapChart, obviously he uses 2 fingers but those 2 countries becomes hovered (activated) and sometimes they still remains activated even after stopping the action.

So, I would like to disable hover on width < 992px but keeping hit/click action available.

**Comment by martynasma** [comment]
Thank you for bringing up a good topic.

We are going to implement a new global option in the next version, to be released this week.

I'll notify when new version is out, and will also provide more details.

**Comment by martynasma** [comment]
Fixed in [4.10.1](https://github.com/amcharts/amcharts4/releases/tag/4.10.1).

## [4.10.1] - 2020-09-07

### Added
- New `DateAxis` property: `timezone`. Allows setting timezone to recalculate data in, e.g. `"Australia/Sydney"`. Make sure not to set this on both axis and date formatter.
- New `DateFormatter` property: `timezone`. Allows setting timezone to recalculate date objects to before applying the format, e.g. `"Australia/Sydney"`.
- New global option: `am4core.options.disableHoverOnTransform` (`"never"` (default), `"touch"`, `always`)). Allows disabling all hover activity when some element is being dragged or resized. [More info](https://www.amcharts.com/docs/v4/concepts/touch/#Hover_functionality).

### Changed
- Now `SankeyLink` that points "backwards" will be applied `"backwards"` state (if created) so you can style it differently than regular links.

### Fixed
- Accessibility: data placeholder population was not working on bullets if Animated theme was not enabled.
- Tapping on a chart with `Cursor` was triggering an on-screen keyboard on some mobiles devices.
- Some TypeScript warnings were fixed.
- A chart with `DateAxis` and `groupData = true` could result a JS error if a series had bullets and a lots of data points.
- In a chart with `DateAxis` and `groupData = true`, if a series was hidden when zoomed-in, then zoomed-out, and then unhidden, the related  `ValueAxis` was not updating it's min/max to available value range.
- In some cases a heat rule could result in infinity value which would lead to drawing errors.
- Errors when cloning a `RadarChart` from a template fixed.
- `SankeyDiagram` used to produce stack owerflow error if data contained backward links. Now it will correctly draw a link.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Please read here for more details:
https://www.amcharts.com/docs/v4/concepts/touch/#Hover_functionality
