### ISSUE TITLE
Circle Line Series chart with heat rules throws console error on scrollbar move or zoom

### ISSUE THREAD

**Issue by mihaela-kokoon** [amcharts/amcharts4#2858]
**Circle Line Series chart with heat rules throws console error on scrollbar move or zoom**

Hello,

I noticed that with a LineSeries chart with circle bullets that have heatRules applied, when zooming in and moving the scrollbar, there are 2 console errors for the circle r radius and the circle translate with invalid values Infinity/-Infinity and NaN.
I'll also mention that the chart DateAxis has groupData enabled, if it helps.

This looks like a bug to me, but please advise if I have to change something in my code. From what I saw in the docs, the heatRules should be well defined.

Here is the Codepen https://codepen.io/mihaela-kokoon/pen/XWdzJLy
I'll attach a GIF showing the issue.

Thank you! Take care!

![bullets-error](https://user-images.githubusercontent.com/64415990/92135794-e0b57880-ee13-11ea-9069-a7ef0fc424e1.gif)

**Comment by martynasma** [comment]
Fixed in [4.10.1](https://github.com/amcharts/amcharts4/releases/tag/4.10.1).

## [4.10.1] - 2020-09-07

### Added
- New `DateAxis` property: `timezone`. Allows setting timezone to recalculate data in, e.g. `"Australia/Sydney"`. Make sure not to set this on both axis and date formatter.
- New `DateFormatter` property: `timezone`. Allows setting timezone to recalculate date objects to before applying the format, e.g. `"Australia/Sydney"`.
- New global option: `am4core.options.disableHoverOnTransform` (`"never"` (default), `"touch"`, `always`)). Allows disabling all hover activity when some element is being dragged or resized. [More info](https://www.amcharts.com/docs/v4/concepts/touch/#Hover_functionality).

### Changed
- Now `SankeyLink` that points "backwards" will be applied `"backwards"` state (if created) so you can style it differently than regular links.

### Fixed
- Accessibility: data placeholder population was not working on bullets if Animated theme was not enabled.
- Tapping on a chart with `Cursor` was triggering an on-screen keyboard on some mobiles devices.
- Some TypeScript warnings were fixed.
- A chart with `DateAxis` and `groupData = true` could result a JS error if a series had bullets and a lots of data points.
- In a chart with `DateAxis` and `groupData = true`, if a series was hidden when zoomed-in, then zoomed-out, and then unhidden, the related  `ValueAxis` was not updating it's min/max to available value range.
- In some cases a heat rule could result in infinity value which would lead to drawing errors.
- Errors when cloning a `RadarChart` from a template fixed.
- `SankeyDiagram` used to produce stack owerflow error if data contained backward links. Now it will correctly draw a link.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
