### ISSUE TITLE
A rest parameter must be of an array type

### ISSUE THREAD

**Issue by brieucp** [amcharts/amcharts4#2867]
Hello,

After updating to last version 4.10.0, I have an error while building my project with typescript (2.7.2) : 

```
ERROR in node_modules/@amcharts/amcharts4/.internal/core/Registry.d.ts(173,20): error TS2370: A rest parameter must be of an array type.
node_modules/@amcharts/amcharts4/.internal/core/utils/Instance.d.ts(172,51): error TS2370: A rest parameter must be of an array type.
```

Everything's fine when I rollback to 4.9.37

**Comment by martynasma** [comment]
Fixed in [4.10.1](https://github.com/amcharts/amcharts4/releases/tag/4.10.1).

## [4.10.1] - 2020-09-07

### Added
- New `DateAxis` property: `timezone`. Allows setting timezone to recalculate data in, e.g. `"Australia/Sydney"`. Make sure not to set this on both axis and date formatter.
- New `DateFormatter` property: `timezone`. Allows setting timezone to recalculate date objects to before applying the format, e.g. `"Australia/Sydney"`.
- New global option: `am4core.options.disableHoverOnTransform` (`"never"` (default), `"touch"`, `always`)). Allows disabling all hover activity when some element is being dragged or resized. [More info](https://www.amcharts.com/docs/v4/concepts/touch/#Hover_functionality).

### Changed
- Now `SankeyLink` that points "backwards" will be applied `"backwards"` state (if created) so you can style it differently than regular links.

### Fixed
- Accessibility: data placeholder population was not working on bullets if Animated theme was not enabled.
- Tapping on a chart with `Cursor` was triggering an on-screen keyboard on some mobiles devices.
- Some TypeScript warnings were fixed.
- A chart with `DateAxis` and `groupData = true` could result a JS error if a series had bullets and a lots of data points.
- In a chart with `DateAxis` and `groupData = true`, if a series was hidden when zoomed-in, then zoomed-out, and then unhidden, the related  `ValueAxis` was not updating it's min/max to available value range.
- In some cases a heat rule could result in infinity value which would lead to drawing errors.
- Errors when cloning a `RadarChart` from a template fixed.
- `SankeyDiagram` used to produce stack owerflow error if data contained backward links. Now it will correctly draw a link.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
