### ISSUE TITLE
LineSeries Tooltip function

### ISSUE THREAD

**Issue by samuel-p** [amcharts/amcharts4#287]
Is there anything simmilar to the old graph balloonFunction? I like to disable the tooltip for null values. 

In version 3 I used the following graph config:
```
{
  ... ,
  "balloonFunction": function (graphDataItem, graph) {
    let value = graphDataItem.values.value;
    let title = graph.title;
    if (value > 0) {
      return title + ": <strong>" + value + "</strong>";
    } else {
      return "";
    }
  },
  ...
}
```

**Comment by martynasma** [comment]
Yes, it's called "adapters":
https://www.amcharts.com/docs/v4/concepts/adapters/

In your case, you'd use `"tooltipText"` adapter.

**Comment by samuel-p** [comment]
Thanks for your response. I already noticed the adapters, but was unable to find the property which holds the current value. 

I tried it with the following code, but the property `target.dataItem.value` is always undefined. 

```
series.tooltipText = "{name}: {valueY}";
series.adapter.add("tooltipText", (text, target, key) => {
  const value = target.dataItem.value;
  if (value > 0) {
    return text;
  }
  return '';
});
```

**Comment by martynasma** [comment]
Try `target.tooltipDataItem` instead.

**Comment by samuel-p** [comment]
Thanks for your help, but `target.tooltipDataItem.value` is also undefined and `target.tooltipDataItem.values` is the same for every y-value:
```
{
  "value": {},
  "valueX": {
    "stack": 0
  },
  "valueY": {
    "stack": 0,
    "sum": 1800,
    "average": 127.71428171423572,
    "open": 73,
    "close": 1,
    "low": 1,
    "high": 300,
    "count": 14
  },
  "openValueX": {},
  "openValueY": {},
  "dateX": {
    "sum": 21486628800000,
    "average": 1534759200000,
    "open": 1534197600000,
    "close": 1535320800000,
    "low": 1534197600000,
    "high": 1535320800000,
    "count": 14
  },
  "dateY": {},
  "openDateX": {},
  "openDateY": {}
}
```

Any other ideas?

**Comment by martynasma** [comment]
Can you post your whole chart config and data so I can play a little with it?

Would eliminate a lot of guesswork about your setup.

**Comment by samuel-p** [comment]
I'm using amcharts with Angular and here is my chart component:

chart-example.component.html
```
<div #chart class="chart chart-animate-draw"></div>
```

chart-example.component.ts
```
import {AfterViewInit, Component, ElementRef, NgZone, OnDestroy, ViewChild} from '@angular/core';
import {of} from "rxjs";
import * as am4charts from "@amcharts/amcharts4/charts";
import * as am4core from "@amcharts/amcharts4/core";

@Component({
  selector: 'app-chart-example',
  templateUrl: './chart-example.component.html'
})
export class ChartExampleComponent implements AfterViewInit, OnDestroy {
  @ViewChild('chart') div: ElementRef;
  private chart: am4charts.XYChart;

  constructor(private zone: NgZone) {}

  ngAfterViewInit(): void {
    this.zone.runOutsideAngular(() => {
      let chart = am4core.create(this.div.nativeElement, am4charts.XYChart);

      let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
      dateAxis.renderer.grid.template.location = 0;
      let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
      valueAxis.tooltip.disabled = true;

      let items = chart.series.push(new am4charts.LineSeries());
      items.name = "Items";
      items.dataFields.dateX = "time";
      items.dataFields.valueY = "items";
      items.strokeWidth = 2;
      items.tooltipText = "{valueY.value}";
      items.adapter.add("tooltipText", (text, target, key) => {
        const value = target.dataItem.value; // is always undefined
        if (value > 0) {
          return text;
        }
        return '';
      });

      chart.cursor = new am4charts.XYCursor();
      chart.cursor.lineY.disabled = true;
      chart.cursor.xAxis = dateAxis;
      chart.legend = new am4charts.Legend();

      this.chart = chart;
    });
    this.loadData();
  }

  ngOnDestroy(): void {
    this.zone.runOutsideAngular(() => {
      if (this.chart) {
        this.chart.dispose();
      }
    });
  }

  private loadData() {
    // load data from server
    of([
      {"time": "2018-08-14", "items": 102}, {"time": "2018-08-15", "items": 241},
      {"time": "2018-08-16", "items": 135}, {"time": "2018-08-17", "items": 76},
      {"time": "2018-08-18", "items": 0}, {"time": "2018-08-19", "items": 0},
      {"time": "2018-08-20", "items": 47}, {"time": "2018-08-21", "items": 147},
      {"time": "2018-08-22", "items": 261}, {"time": "2018-08-23", "items": 121},
      {"time": "2018-08-24", "items": 54}, {"time": "2018-08-25", "items": 0},
      {"time": "2018-08-26", "items": 230}, {"time": "2018-08-27", "items": 207}
    ]).delay(2000).subscribe(data => {
      this.chart.data = data;
    });
  }
}
```

**Comment by martynasma** [comment]
Thanks.

I still see the `const value = target.dataItem.value;` is this an old code, or have you tried changing to `const value = target.tooltipDataItem.value;` and it didn't help?

**Comment by samuel-p** [comment]
Yes, `const value = target.tooltipDataItem.value;` also undefined.

**Comment by martynasma** [comment]
OK, so it looks like `tooltipDataitem` for series is being set **after** adapter of `tooltipText` adapter kicks in.

We're going to try figure out if it can be somehow worked around.

Meanwhile checking if passed in "text" to the adapter is `"0"` would do the trick.

I know it's not a reliable solution because you might want to change what goes into tooltip, but might work as a temporary workaround.

**Comment by martynasma** [comment]
codepen for our reference:
https://codepen.io/team/amcharts/pen/ac838776c126355124e64624ac406cb0?editors=0010

**Comment by samuel-p** [comment]
Thanks for your reply. The passed in "text" is always "{valueY.value}" and never "0".

**Comment by martynasma** [comment]
Right. My bad.

I believe we can work around that by using adapter on `series.tooltip.label` directly, as it does receive correct `dataItem`:

```
items.tooltip.label.adapter.add("textOutput", (text, target, key) => {
  if (target.dataItem) {
    if (target.dataItem.values.valueY.value == 0) {
      return "";
    }
  }
  return text;
});
```

The above is verified to work as expected.

**Comment by lfhenrl** [comment]
I am trying V4 but the adapter seems not to handle to return HTML

**Comment by martynasma** [comment]
@lfhenrl Please open a separate issue, or email us directly at contact@amcharts.com.

**Comment by samuel-p** [comment]
Thanks @martynasma your example works perfectly.

@lfhenrl to handle HTML you have to use the key "htmlOutput".

```
items.tooltipHTML = "{name}: <strong>{valueY.value}</strong>";
items.tooltip.label.adapter.add("htmlOutput", (text, target, key) => {
  if (target.dataItem) {
    if (target.dataItem.values.valueY.value == 0) {
      return '';
    }
  }
  return text;
});
```

The example above works for me.

**Comment by martynasma** [comment]
Great!

I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by martynasma** [comment]
Well, maybe not, since we're going to look into feeding proper dataItem into series :)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.50](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.50).

## [4.0.0-beta.50] - 2018-09-10

### Added
- `am4core.unuseAllThemes()` method added. Any chart created after this method call will not have any theme applied to it.
- New property `am4core.registry.baseSprites` will now hold all active (non-disposed) instances of top-level elements, such as charts.
- `startLocation`/`endLocation` properties added to `CategoryAxis` (previously available on `DateAxis` only). Allows to specify location the first and last cells of the axis should start on respectively.
- `innerRadius` of a Slice can now be set as `Percent` (e.g. `am4core.percent(50)`).
- You can now set custom radii (`radius` property) on Pie series (if you have more than one, you might want one to be larger and another smaller).

### Changed
- [`MapLine.imagesToConnect`](https://www.amcharts.com/docs/v4/reference/mapline/#imagesToConnect_property) now accepts an array of string IDs that can reference images by their `id` property.
- Changed `tooltip` inheritance so that it checks for `virtualParent` rather than direct `parent`. E.g. series' bullets use series' tooltip and not chart tooltip as it was before.

### Fixed
- Map polygon stroke thickness could be rendered incorrectly when zooming quickly. (Issue #175)
- Calling `addData()` more than once before data was validated resulted only last data item to be added. (Issue #222)
- `DateAxis.baseInterval` was ignored if data was set directly on series.
- `MapLine` was not paying attention to the properties set on template.
- `HeatLegend` was not updating its label count after its size changed. This could have been resulting in very few labels if initial container (div) size was small.
- The map portion of `MapChart` was incorrectly positioned after container (div) resize.
- Object properties, like `"name"` in GeoJSON were overriding same properties in `MapSeries` data. Now, the values specified in data are used over ones in GeoJSON. (Issue #307)
- Axis ranges used to reset `axisRange.label.text`. (Issue #308)
- Fixed issues with disposing series and charts.
- Updated to [canvg 1.5.3](https://github.com/canvg/canvg/releases/tag/v1.5.3) to fix em/rem text issue for epoxrt fallbacks.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by samuel-p** [comment]
It seems, that the fix has a bug: 

https://codepen.io/anon/pen/yxvGoJ

If the tooltip is empty at one value it does not show again after hover that value.

**Comment by martynasma** [comment]
OK, so issue is that once series receives first empty `tooltipText` it stops trying to resolve which data item it is, because it's a costly operation - the logic goes like this: if we don't display tooltip there's no point in wasting CPU on finding out tooltip position.

I'm not sure if there's a good way around it, so let me put another solution on the table:

```
items.adapter.add("tooltipText", (text, target, key) => {
    target.tooltip.disabled = 
      target.tooltipDataItem && target.tooltipDataItem.values.valueY.value == 0;
  return text;
});
```

This works nicely.

It disables or enables series' tooltip based on the current data item, without affecting `tooltipText`.

Hope you like this.

**Comment by samuel-p** [comment]
Thank you, that also works perfectly.

**Comment by djamadeus** [comment]
That last solution leads to tooltips displaying on wrong Y-Positions for me (in linecharts with many series). I suppose the not displayed tooltips from 0-Series still go into the offset-calculation for the displayed ones, to preventing hitting the undisplayed shapes.

Changing the adapter  to the following solved that problem for me:

series.adapter.add("tooltipText", (text, target, key) => {
            if(target.tooltipDataItem.values.valueY.value == 0){
                text = "";
            }
        return text;
        });

**Comment by setiawans** [comment]
@djamadeus I'd like to ask how to styling tooltipAdapter? maybe for some changes size, border-radius or anymore. thanks
