### ISSUE TITLE
label adapter trouble

### ISSUE THREAD

**Issue by mrAndyss** [amcharts/amcharts4#2872]
Hi. I have been using an adapter for label text format for a long time. But recently I get the error: "Cannot read property 'valueY' of undefined". What changed?

`
var series2 = chart.series.push(new am4charts.ColumnSeries3D());
.......
var valueLabel2 = series2.bullets.push(new am4charts.LabelBullet());
valueLabel2.label.text = "{Fakt}";

valueLabel2.label.adapter.add("text", function(text, target) {
  return new Intl.NumberFormat('ru-RU',{maximumFractionDigits: 0}).format(**target.dataItem.valueY**);
});

`

**Comment by mrAndyss** [comment]
if (!target.dataItem) {
    return text;
  }

**Comment by martynasma** [comment]
Fixed in [4.10.2](https://github.com/amcharts/amcharts4/releases/tag/4.10.2).

## [4.10.2] - 2020-09-08

### Fixed
- Some `SankeyDiagram` charts were broken after last release.
- `4.10.0` caused some bullet adapters to kick in earlier which in turn was resulting in critical errors if those adapters relied on `dataItem` to be present without checking.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
