### ISSUE TITLE
Gap in live data chart with multiple series

### ISSUE THREAD

**Issue by VimalkumarNair** [amcharts/amcharts4#2876]
I am working with live data in which old data should get deleted after some amount of data is rendered on the chart but facing some issues in it.
I am using the live data chart example and added an additional series(series2) to it. The data for series2 is generated when the xAxis DateTime is at 1 second. As the old data gets deleted the datapoint for series2 moves out of the chart.
Here, a gap is created in series1 data as you can see in the below link.
https://codepen.io/vimalkumarnair/pen/xxVYqvz

When there is no data for series2, I have tried with not setting the value at all and also with setting it to null.

I have also tried calling each of the below functions after data is added to chart.
chart.validate()
chart.resetProcessedRange()
chart.validateRawData()
chart.validateData()
chart.validateDataElement()
chart.validateDataItems()
chart.validateDataRange()
chart.validateLayout()
chart.validatePosition()

Is there a way to fix this?

Thank you in advance.

![image](https://user-images.githubusercontent.com/9985799/92476775-1cc65000-f1fd-11ea-8fde-fafda2cf439d.png)

![image](https://user-images.githubusercontent.com/9985799/92476733-0ddf9d80-f1fd-11ea-87b8-18352d8840ff.png)

**Comment by martynasma** [comment]
This seems to be happening when you use `addData()` with removal of data items when there is series without any data items, which is unusual situation.

I suggest you try the following: instead of using `chart.data` set your data (and update with `addData()` directly on series. This way the series with distinctive granularity would not step on each others toes.
