### ISSUE TITLE
am4plugins_sliceGrouper.SliceGrouper uses a global istance for data and breaks on multiple charts 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#2901]
**Bug description**

This breaks with am4core.options.queue = true; 

0. am4core.options.queue = true;
1. Create a pie chart 
2. Bind some data to it 
3. add am4plugins_sliceGrouper.SliceGrouper to group low values 
4. Create another pie with the same dataset but a new object eg `[...data]`
5. add am4plugins_sliceGrouper.SliceGrouper to group low values 

Expected 

<img width="419" alt="Screenshot 2020-09-12 at 16 13 36" src="https://user-images.githubusercontent.com/1268723/92997358-f3663680-f512-11ea-923c-63dd41f49f2e.png">

Broken 

<img width="425" alt="Screenshot 2020-09-12 at 16 13 10" src="https://user-images.githubusercontent.com/1268723/92997361-f7925400-f512-11ea-88f1-41a845e0fdf1.png">

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this:
https://codepen.io/team/amcharts/pen/b23b916ce5945f3009270abe5b323f5f?editors=0010

Can you post your repro case we can test?

**Comment by jimmykane** [comment]
Well just remove the queue from there.

**Comment by martynasma** [comment]
You mean the `am4core.options.queue = true;` line?

It works identically for me with and without that line.

What am I missing? :)

**Comment by jimmykane** [comment]
The above code pen :-) 

Not touched 

A Chart
<img width="1440" alt="Screenshot 2020-09-13 at 16 29 00" src="https://user-images.githubusercontent.com/1268723/93020618-583a9300-f5de-11ea-96d6-fae360cc50db.png">
B Chart 
<img width="1440" alt="Screenshot 2020-09-13 at 16 29 14" src="https://user-images.githubusercontent.com/1268723/93020626-5ffa3780-f5de-11ea-9793-36f9e2c1f311.png">

Putting queue = false 

Chart A
<img width="1439" alt="Screenshot 2020-09-13 at 16 30 28" src="https://user-images.githubusercontent.com/1268723/93020651-815b2380-f5de-11ea-8327-074a4333eefb.png">
Chart B 
<img width="1439" alt="Screenshot 2020-09-13 at 16 30 36" src="https://user-images.githubusercontent.com/1268723/93020658-8ae48b80-f5de-11ea-949d-e70de28d032a.png">


Or am I misunderstanding something

**Comment by jimmykane** [comment]
To my understanding with queue = false it looks ok, while with queue on it produces some side effects

**Comment by martynasma** [comment]
Hm, that's not what I'm seeing.

Which browser are you using?

**Comment by jimmykane** [comment]
Breaks with brave latest (mobile + desktop) 

![Screenshot_20200913-164935](https://user-images.githubusercontent.com/1268723/93021101-2f67cd00-f5e1-11ea-8247-f68864f77c54.jpg)

**Comment by jimmykane** [comment]
Also chrome mobile latest (I don't have chrome on desktop due to company policy + Google ) 

![Screenshot_20200913-165138](https://user-images.githubusercontent.com/1268723/93021127-6938d380-f5e1-11ea-8cc9-48eed8327796.jpg)

**Comment by jimmykane** [comment]
Firefox Desktop + Osx
<img width="1439" alt="Screenshot 2020-09-13 at 16 54 23" src="https://user-images.githubusercontent.com/1268723/93021221-d6e4ff80-f5e1-11ea-9a14-f9d1e82c45f0.png">

**Comment by jimmykane** [comment]
Safari aslo + OSX 
<img width="1436" alt="Screenshot 2020-09-13 at 16 55 19" src="https://user-images.githubusercontent.com/1268723/93021235-efedb080-f5e1-11ea-93c3-5490875c53a2.png">

**Comment by jimmykane** [comment]
Ok this is super weird. 

Now on Brave it's ok for Desktop. Perhaps some timing issue ?

**Comment by jimmykane** [comment]
Definitely a timing issue / event order 
https://www.loom.com/share/74de38ef3c7944dbb53fa97db2eb3dc0

**Comment by martynasma** [comment]
OK, I was able to reproduce it with Brave on desktop.

I'll see if this can be fixed.

**Comment by jimmykane** [comment]
Not a showstopper for sure 😂 

But yeah. Notice. The video above is with brave.

Have a great rest of the Sunday @martynasma  and as always thanks a lot. My best regards.

**Comment by martynasma** [comment]
I think we have a fix in place for the next release. I'll ping you here when the new version is out. Thanks!

**Comment by martynasma** [comment]
Fixed in [4.10.3](https://github.com/amcharts/amcharts4/releases/tag/4.10.3).

## [4.10.3] - 2020-09-19

### Added
- RangeSelector plugin: a new event `periodselected` added to `DateAxisRangeSelector`.
- `DateFormatter` now supports quarter format (code: `"q"`).

### Changed
- More prompt translations to Indonesian locale (`id_ID`).

### Fixed
- JSON config: Some axis' `title` property was being overwritten if it wasn't last option in the properties list.
- SliceGrouper plugin was sometimes not functioning properly when used with `options.queue = true`.
- Scrollable legend was not resetting back to top if its height changed.
- `TreeMap` with `binaryTree` algorithm was producing a JS error if no initial data was set on chart.
- If data grouping on `DateAxis` was enabled and there were more than one series in the chart, the second and other series were rendered with data ungrouped in the background before rendering them correctly and thiswas causing performance issues.
- Vertical `CurvedColumnSeries` with non-inversed `CategoryAxi`s were not positioned properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
