### ISSUE TITLE
Quarter as dateFormat

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#2920]
I can change axis format using `dateFormats`. https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/
But I want to use `quarter` (like Q1, Q2, Q3, Q4).
I cannot see such option. How to make it?

**Comment by martynasma** [comment]
It's currently not available, but we'll add `q` code in the next version.

I'll let you know when the new version is out.

**Comment by piernik** [comment]
Great!

**Comment by martynasma** [comment]
Fixed in [4.10.3](https://github.com/amcharts/amcharts4/releases/tag/4.10.3).

## [4.10.3] - 2020-09-19

### Added
- RangeSelector plugin: a new event `periodselected` added to `DateAxisRangeSelector`.
- `DateFormatter` now supports quarter format (code: `"q"`).

### Changed
- More prompt translations to Indonesian locale (`id_ID`).

### Fixed
- JSON config: Some axis' `title` property was being overwritten if it wasn't last option in the properties list.
- SliceGrouper plugin was sometimes not functioning properly when used with `options.queue = true`.
- Scrollable legend was not resetting back to top if its height changed.
- `TreeMap` with `binaryTree` algorithm was producing a JS error if no initial data was set on chart.
- If data grouping on `DateAxis` was enabled and there were more than one series in the chart, the second and other series were rendered with data ungrouped in the background before rendering them correctly and thiswas causing performance issues.
- Vertical `CurvedColumnSeries` with non-inversed `CategoryAxi`s were not positioned properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
