### ISSUE TITLE
When is the 'Event Dispatcher is disposed' error message supposed to happen?

### ISSUE THREAD

**Issue by jeremypanelli1** [amcharts/amcharts4#2967]
I am working on a project that involves several different charts, and we have a bug reporting system in place called bugsnag that files reports whenever a bug occurs. Event dispatcher is disposed appears to be happening only on Safari (inconsistently) and only on 'out' events. It might be the way we are changing data, it might be the event itself. It does crash our app though, which is a problem. I'm wondering when it is supposed to be called and what the most common reasons for it being called that you guys have seen. Thanks!

**Comment by martynasma** [comment]
It's not supposed to happen. If you could post a repro case somewhere where we can see it in action, we'd take a look.

Thanks.

**Comment by fu1996** [comment]
@jeremypanelli1 I have encountered similar problems before. What I found out is the execution order of the program. Check the execution order of the program to see if the related events of the chart are called when the chart is disposed. I hope it can help you

**Comment by jeremypanelli1** [comment]
Hi! This seems to be exclusively happening on ipad and ios when the user attempts to click a column within a bar chart and data is updated. We are able to reproduce, but only on an ios simulator. It appears to be the handleGlobalPointerDown function that calls a processDelayed function and forces an 'out' event and within the 'enabled' check throws the error. This happens when clicking and selecting a bar within a bar graph I'm curious on the need to throw an error here. What are you attempting to warn the developer from doing? 

Error EventDispatcher is disposed 
    node_modules/@amcharts/amcharts4/.internal/core/utils/EventDispatcher.js:180:28 
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:1176:36 
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:1206:27 
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:730:13 
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:292:143

**Comment by martynasma** [comment]
Thank you for additional details. Just wanted to let you know, we're looking into it.

Will keep you posted.

**Comment by martynasma** [comment]
Hm, I can't seem to be able to reproduce those warnings on neither MacOS Safari nor Mobile Safari.

I did try those in various charts.

Would you be able to produce some sort of demo that we can use for testing, that exhibits this issue, or at least provide some guidance on how to reproduce it?

**Comment by lgerndt** [comment]
> @jeremypanelli1 I have encountered similar problems before. What I found out is the execution order of the program. Check the execution order of the program to see if the related events of the chart are called when the chart is disposed. I hope it can help you

fu1996, can you please elaborate a bit more?  I'm not exactly sure what you're saying.  It sounds like you're saying that events should NOT be called when chart is disposed, is that what you're saying?

**Comment by jeremypanelli1** [comment]
@martynasma Yea - I'll send you one in a little bit

**Comment by fu1996** [comment]
> > @jeremypanelli1 I have encountered similar problems before. What I found out is the execution order of the program. Check the execution order of the program to see if the related events of the chart are called when the chart is disposed. I hope it can help you
> 
> fu1996, can you please elaborate a bit more? I'm not exactly sure what you're saying. It sounds like you're saying that events should NOT be called when chart is disposed, is that what you're saying?

[https://codepen.io/fu1996/pen/KKzJMJj?editors=1111](https://codepen.io/fu1996/pen/KKzJMJj?editors=1111)
Click the dispose button to see the corresponding error

**Comment by martynasma** [comment]
Thanks for the link.

In your dispose function you dispose one of the axis. At this point there are actual series attached to the axis.

By this time the error is not yet happening.

The error kicks in when you update the chart data.

Updating chart data triggers a redrawing of series, which cannot function without both X and Y axis.

Since series that is being updated is still tied to an axis that has been disposed, the said error is triggered.

For this set up to work, you need to:

1) Create a new X axis.
2) Assign it to series `xAxis` property.
3) Then update chart data.

Hope this makes sense.

**Comment by prasanna-sasne** [comment]
Hello @martynasma
I'm currently displaying data in a reduced format because using the full dataset freezes the amCharts library due to its inability to handle billions of data points (though the data isn't live). To manage this, I've been condensing the data, and during Zoom events, I dynamically adjust the displayed data by adding or removing points.

However, I'm not entirely satisfied with your approach. I find it less than ideal to create a new X-axis, assign it to the xAxis property, and update the entire chart for every zoom-in or zoom-out action. I'm looking for a more efficient solution that doesn't require these repeated steps with each Zoom event. Can you please suggest best way to deal with this use case?
