### ISSUE TITLE
DateAxis.baseInterval is ignored if data is set directly to Series

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#298]
Hello,

I've some trouble to set baseInterval to month or minute (day work find)

https://codepen.io/ptorrent/pen/gdMdBP

What am I doing wrong?

**Comment by martynasma** [comment]
OK, so it looks like `baseInterval` on axis is ignored when you have data set directly to series' `data` which is the case with your chart.

I'm going to chalk it up as bug in case this unusual setup is fixable, however, you can easily fix it by assigning your data directly to chart rather than series.

Here's a simplified demo for our own usage:
https://codepen.io/team/amcharts/pen/6a1a6d0a139596ed5c49d9f9acdf71be/

**Comment by ptorrent** [comment]
Thank you !

I have to link the data to the series because I receive the data in asynchronous ways from several different server. As I build the graph as I receive the data, I do not link the data to the graph but to the series because of the dates not necessarily in order. Sorting all data by date is relatively heavy because of the amount of data I have.

**Comment by martynasma** [comment]
Gotcha.

However, I'm not entirely sure how setting unordered data directly to series would solve the situation. We don't sort the data in series in any way, so if it works that way it's incidental, and might seize working at some point.

That said, sorting an array in JavaScript should not be a huge operation, even with a few thousands of items. I strongly recommend considering it, if server-side sorting is not possible.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.50](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.50).

## [4.0.0-beta.50] - 2018-09-10

### Added
- `am4core.unuseAllThemes()` method added. Any chart created after this method call will not have any theme applied to it.
- New property `am4core.registry.baseSprites` will now hold all active (non-disposed) instances of top-level elements, such as charts.
- `startLocation`/`endLocation` properties added to `CategoryAxis` (previously available on `DateAxis` only). Allows to specify location the first and last cells of the axis should start on respectively.
- `innerRadius` of a Slice can now be set as `Percent` (e.g. `am4core.percent(50)`).
- You can now set custom radii (`radius` property) on Pie series (if you have more than one, you might want one to be larger and another smaller).

### Changed
- [`MapLine.imagesToConnect`](https://www.amcharts.com/docs/v4/reference/mapline/#imagesToConnect_property) now accepts an array of string IDs that can reference images by their `id` property.
- Changed `tooltip` inheritance so that it checks for `virtualParent` rather than direct `parent`. E.g. series' bullets use series' tooltip and not chart tooltip as it was before.

### Fixed
- Map polygon stroke thickness could be rendered incorrectly when zooming quickly. (Issue #175)
- Calling `addData()` more than once before data was validated resulted only last data item to be added. (Issue #222)
- `DateAxis.baseInterval` was ignored if data was set directly on series.
- `MapLine` was not paying attention to the properties set on template.
- `HeatLegend` was not updating its label count after its size changed. This could have been resulting in very few labels if initial container (div) size was small.
- The map portion of `MapChart` was incorrectly positioned after container (div) resize.
- Object properties, like `"name"` in GeoJSON were overriding same properties in `MapSeries` data. Now, the values specified in data are used over ones in GeoJSON. (Issue #307)
- Axis ranges used to reset `axisRange.label.text`. (Issue #308)
- Fixed issues with disposing series and charts.
- Updated to [canvg 1.5.3](https://github.com/canvg/canvg/releases/tag/v1.5.3) to fix em/rem text issue for epoxrt fallbacks.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ptorrent** [comment]
Hello,

Are you sure it's ok ?

(I removed browser cache) 

https://codepen.io/ptorrent/pen/gdMdBP

**Comment by martynasma** [comment]
Looks, like `baseInterval` is ignored in JSON-based setup altogether. It works fine now in object-bsaed setups.

Since it's a separate issue, I posted a separate GitHub issue for it: #337

Make sure you subscribe to it to stay up-to-date.
