### ISSUE TITLE
Printing wide charts via IFrame in IE11 leads to distorted images

### ISSUE THREAD

**Issue by c-goetz** [amcharts/amcharts4#2981]
**Bug description**

Printing a wide chart via IFrame in IE11 leads to distortion.

*Steps to reproduce:*

* open https://codepen.io/carlo_g/pen/oNLvxqZ in IE11(you may need to embed the codepen and serve it locally since codepen doesn't like IE11)
* click print in the export menu
* print with 'Microsoft print to pdf'
* open pdf

*Actual result:*
![image](https://user-images.githubusercontent.com/6413073/95096061-1a87e080-072c-11eb-81fb-e00692854cbf.png)

*Expected result:*
Same thing done in Chromium:
![image](https://user-images.githubusercontent.com/6413073/95096230-4d31d900-072c-11eb-8c61-f57f582cd1fd.png)

As you can see everything is distorted. I suspect that this only happens when the image in the iframe actually has to be resized to fit. Printing the smaller CodePen from https://www.amcharts.com/docs/v4/concepts/exporting in IE11 looks fine.

*Possible fix*
Adding a line with `height = 'auto'` in `Export.printViaIframe` seems to fix this.
```
    Export.prototype.printViaIframe = function (data, options, title) {
        return __awaiter(this, void 0, void 0, function () {
            var iframe, img, isIOS;
            return __generator(this, function (_a) {
                iframe = document.createElement("iframe");
                iframe.style.visibility = "hidden";
                document.body.appendChild(iframe);
                // This is needed for FireFox
                iframe.contentWindow.document.open();
                iframe.contentWindow.document.close();
                img = new Image();
                img.src = data;
                img.style.maxWidth = "100%";
                // added this line
                img.style.height = 'auto';
```

**Environment (if applicable)**

 - amCharts version: 4.10.5
 - IE11

**Additional context**

**Comment by martynasma** [comment]
Fixed in [4.10.6](https://github.com/amcharts/amcharts4/releases/tag/4.10.6).

## [4.10.6] - 2020-10-09

### Added
- SVG export options now support `scale`, `minWidth`, `minHeight`, `maxWidth`, and `maxHeight`.
- New `ExportMenu` property: `element` (a reference to menu's top element).

### Fixed
- `readerTitle` and `readerDescription` were not being properly populated with data on Map objects.
- Setting `includeRangesInMinMax = true` on `ValueAxis` in some cases was messing up the chart.
- Export: Printing via iframe in IE11 was distorting the chart aspect ratio.
- Export: Exporting in IE11 was leaving behind a stray `<canvas>` element afterwards.
- Auto-zoom on `ValueAxis` was not working properly with multiple series with incomplete data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
