### ISSUE TITLE
Printing a chart via IFrame in IE11 litters the dom with canvas elements

### ISSUE THREAD

**Issue by c-goetz** [amcharts/amcharts4#2982]
**Bug description**

*Steps to reproduce:*
- open in IE11
- use the first codepen
- print the chart multiple times
- open dev tools and inspect dom of embedded codepen

*Actual result:*
- dom contains a canvas element per print
![image](https://user-images.githubusercontent.com/6413073/95100831-caac1800-0731-11eb-8dec-fc578af78bc0.png)

*Expected result:*
- dom contains no canvas element

**Environment (if applicable)**

 - amCharts version: 4.10.5
 - Browser and its version: IE11

**Additional context**

**Comment by martynasma** [comment]
Fixed in [4.10.6](https://github.com/amcharts/amcharts4/releases/tag/4.10.6).

## [4.10.6] - 2020-10-09

### Added
- SVG export options now support `scale`, `minWidth`, `minHeight`, `maxWidth`, and `maxHeight`.
- New `ExportMenu` property: `element` (a reference to menu's top element).

### Fixed
- `readerTitle` and `readerDescription` were not being properly populated with data on Map objects.
- Setting `includeRangesInMinMax = true` on `ValueAxis` in some cases was messing up the chart.
- Export: Printing via iframe in IE11 was distorting the chart aspect ratio.
- Export: Exporting in IE11 was leaving behind a stray `<canvas>` element afterwards.
- Auto-zoom on `ValueAxis` was not working properly with multiple series with incomplete data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
