### ISSUE TITLE
Line chart displays wrong chart on zoom

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2988]
**Bug description**

Line chart is vertically inverted if zoomed and series ranges are used and valueAxis.includeRangesInMinMax = true;

Details at #2883 

Codepen:
https://codepen.io/chrisadler/pen/bGpowgB?editors=1010

Sorry for creating a new bug issue - maybe the previous one got lost.
But this is a serious error which has no acceptance at the customers and the issue mentioned above I created a month ago and has no feedback or even a label. 

Please take a look at it.

**Comment by martynasma** [comment]
Looking into it. Will keep you posted. Not sure how the original ticket got lost. Sorry about that.

**Comment by martynasma** [comment]
Fixed in [4.10.6](https://github.com/amcharts/amcharts4/releases/tag/4.10.6).

## [4.10.6] - 2020-10-09

### Added
- SVG export options now support `scale`, `minWidth`, `minHeight`, `maxWidth`, and `maxHeight`.
- New `ExportMenu` property: `element` (a reference to menu's top element).

### Fixed
- `readerTitle` and `readerDescription` were not being properly populated with data on Map objects.
- Setting `includeRangesInMinMax = true` on `ValueAxis` in some cases was messing up the chart.
- Export: Printing via iframe in IE11 was distorting the chart aspect ratio.
- Export: Exporting in IE11 was leaving behind a stray `<canvas>` element afterwards.
- Auto-zoom on `ValueAxis` was not working properly with multiple series with incomplete data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
