### ISSUE TITLE
XYCursor: "Uncaught TypeError: t.replace is not a function"

### ISSUE THREAD

**Issue by lnicastro** [amcharts/amcharts4#2997]
**Bug description**

Not sure exactly since when, but I am receiving this type of error message in the console log window:

```
Uncaught TypeError: t.replace is not a function
    plainText core.js:46985
    get core.js:43313
    applyAccessibility core.js:30340
    setDataItem core.js:30281
    setDataItem core.js:9803
    setDataItem core.js:43284
    set core.js:30256
    setDataItem core.js:9801
    each core.js:33017
...
```
which is not happening when using my local version 4.9.33.

Looking into the code I see that this happens when creating a cursor in a chart where the X axis is created via `CategoryAxis`, but not via `ValueAxis`, e.g.:
```
var xAxis = chart.xAxes.push(new am4charts.CategoryAxis());
var mydata = chart.series.push(new am4charts.LineSeries());
...
chart.cursor = new am4charts.XYCursor();
```
To be short, I found that if the series `dataFields.categoryX` is "not" a string I get those errors. So at some stage this became a (at least partial) requirement. I would be happy to use `ValueAxis`, but, as I already reported, that has other drawbacks.

 - amCharts 4.10.6 (core.js)
 - In any Browser

Can check using the code I used for my previous issue: [https://qsfit.inaf.it/xy_vText.html](https://qsfit.inaf.it/xy_vText.html)

**Comment by martynasma** [comment]
Fixed in [4.10.7](https://github.com/amcharts/amcharts4/releases/tag/4.10.7).

## [4.10.7] - 2020-10-10

### Fixed
- `numberFormatter` inheritance was broken for `XYSeries` elements like bullets since last version.
- Chart with a `CategoryAxis` and `XYCursor` was erroring when number-based categories were used in data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
