### ISSUE TITLE
Date axis automatic detection of granularity is not working

### ISSUE THREAD

**Issue by AhmedSayed77** [amcharts/amcharts4#2998]
**Bug description**

An array of data with seconds between them, are all displayed in a single day. When I tried to set `dateAxis.gridIntervals`, the chart always picked the largest interval, or ignores them and displays them in a single day. Setting `baseInterval` is not applicable, because I don't know the granularity of the data before hand, and I presumed that automatic detection will handle it.

[reproduction link](https://codesandbox.io/s/charming-boyd-5pcix?file=/src/index.ts)

**Environment (if applicable)**

 - amCharts version: 4.10.5
 - Browser and its version: latest firefox and chrome

**Comment by xorspark** [comment]
You need to specify a [inputDateFormat](https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/#Parsing_dates) so that the chart knows how to parse your timestamps. By default, the chart assumes daily data (`'yyyy-MM-dd'`). In your case, `'i'` is sufficient.

```
chart.dateFormatter.inputDateFormat = 'i';
```

Also note that your timestamps [need to be in ascending order](https://www.amcharts.com/docs/v4/concepts/data/#Date_based_data).

**Comment by AhmedSayed77** [comment]
hmmm. It worked like a charm. and 'x' for if the `time` property is a unix timestamps, am I right?

**Comment by xorspark** [comment]
Correct.

**Comment by AhmedSayed77** [comment]
Thanks a lot. I'm gonna suggest something here. If you highlight the important keywords in the documentation, it can help prevent falling in mistakes like this. I've read the linked page about 3 times, but not thoroughly, because the documentation is huge, and I just wanted to get things working. Of course this is not your fault, but it would save you the time and effort consumed by answering questions like mine, when the answer was right on front of me from the beginning. Thanks again for your time, you're an amazing team
