### ISSUE TITLE
Label format not respecting format settings in 4.10.6

### ISSUE THREAD

**Issue by Steve-OH** [amcharts/amcharts4#3000]
**Bug description**

Labels in divergent stacked bar charts (and perhaps elsewhere) are not respecting the `chart.numberFormatter.numberFormat` settings. This is new in 4.10.6.

JSFiddle: https://jsfiddle.net/Steve_OH/752L0qkx/latest/

**Environment (if applicable)**

 - amCharts version - 4.10.6
 - Browser and its version - any
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - n/a

**Additional context**

Before (4.10.5) and after (4.10.6) images here: https://imgur.com/a/CgcTAEZ

**Comment by martynasma** [comment]
Thanks for the heads up! Looking into it.

**Comment by martynasma** [comment]
Fixed in [4.10.7](https://github.com/amcharts/amcharts4/releases/tag/4.10.7).

## [4.10.7] - 2020-10-10

### Fixed
- `numberFormatter` inheritance was broken for `XYSeries` elements like bullets since last version.
- Chart with a `CategoryAxis` and `XYCursor` was erroring when number-based categories were used in data.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
