### ISSUE TITLE
â€¦ appearing in truncated labels

### ISSUE THREAD

**Issue by Josh10101010** [amcharts/amcharts4#3017]
I've created a treemap and some of the labels are too wide for the container so I have set truncate to true.

However, I am getting the characters "â€¦" in the label, I image this is instead of "..." or something similar? 

Could this be an issue with encoding etc? I've looked through the documentation and on here, can't see any similar issues.

![image](https://user-images.githubusercontent.com/66729900/96561770-e679f700-12b7-11eb-86ac-07ac71006f3d.png)

**Comment by xorspark** [comment]
It might be an encoding issue. Make sure your page is UTF-8 encoded. Otherwise, it might be an issue with the font not having the `...` unicode character. Worst case, you can also configure the object's associated label's [`ellipsis`](https://www.amcharts.com/docs/v4/reference/label/#ellipsis_property) if you want to use something else to represent truncated text (such as three individual period characters).

**Comment by Josh10101010** [comment]
Setting the [ellipsis](https://www.amcharts.com/docs/v4/reference/label/#ellipsis_property) worked, thanks.
