### ISSUE TITLE
Timeline chart is moved up when queue is turned on

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#3019]
**Bug description**

As in topic. Timeline chart is moved up when queue is turned on

`this.am4core.options.queue = true;`
<img width="693" alt="timeline-chart" src="https://user-images.githubusercontent.com/420691/96718469-5b2c5e80-13a8-11eb-8726-35f6d6d68979.png">

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Thank you for bringing this to our attention.

We'll fix it in the next version, and will let you know.

In the interim, the following workaround fixes the issue:

```JavaScript
dateAxis.renderer.line.isMeasured = false;
```

**Comment by martynasma** [comment]
Fixed in [4.10.9](https://github.com/amcharts/amcharts4/releases/tag/4.10.9).

## [4.10.9] - 2020-10-23

### Changed
- Export: API functions like `getCSV`, `getSVG`, `getJSON`, `getExcel` will not error out if no opeionts or format identifier is passed in.

### Fixed
- Better invalidation of charts with `am4core.options.queue = true` enabled.
- A slice in `PieSeries` remained enlarged (as hovered) after subsequent taps on it on a touch device.
- In some rare cases, on mobile devices a JS error could be invoked when disposing series/axes.
- Vertical `ValueAxis` was not auto-zooming in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
