### ISSUE TITLE
Simulate mouse move on chart

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#303]
Hello,

I've a table. Each rows in this table is a datapoint on the chart. If I move hover a row, I would like to move the chart cursor to the specific date of the row.

I found this : 

```javascript 
 chart.cursor.moveTo(dateAxis.anyToPoint(ts))
```

But it's move only cursor, not bullets.

Is there a better way to do that ?

Thanks for your support !

**Comment by RobbiesCode** [comment]
Hi,

Yes, ChartCursor has a similar event named `triggerMove` which simulates the actual mouse/touch action of moving the chart cursor to a certain category/date.

In this case, any **hover** states are triggered as well.

```
  chart.cursor.triggerMove(dateAxis.anyToPoint(ts));
```

Here's a simple Codepen example that does this: https://codepen.io/team/amcharts/pen/rZjjPa?editors=1010. Click the button to see the Chart Cursor jump to a new category (and see how the bullets grow). Please note that the example uses a Category Axis instead of a Date Axis, but it should work the same.

Docs: https://www.amcharts.com/docs/v4/reference/cursor/#triggerMove_method.

I hope this helps!

**Comment by ptorrent** [comment]
Perfect ! thanks

**Comment by NPC** [comment]
@RobbiesCode can you please clarify how it's supposed to work? The CodePen example highlights a category on click, but it disappears with the first mouse motion — and then doesn't work anymore, until you hover the chart. Is there additional condition on hiding/showing the cursor for this to work reliably?
