### ISSUE TITLE
Maximum call stack size exceeded with version 4.10.8

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#3031]
**Bug description**

Angular 
<img width="840" alt="Screenshot 2020-10-26 at 09 47 26" src="https://user-images.githubusercontent.com/1268723/97151795-4c5ef680-1770-11eb-9776-672fc3ecc63d.png">

<img width="559" alt="Screenshot 2020-10-26 at 09 41 24" src="https://user-images.githubusercontent.com/1268723/97151290-9b585c00-176f-11eb-9ed9-23b1f6df968e.png">
<img width="476" alt="Screenshot 2020-10-26 at 09 41 34" src="https://user-images.githubusercontent.com/1268723/97151299-9eebe300-176f-11eb-8131-b6946c6cffd7.png">

**Comment by jimmykane** [comment]
This affects all versions after 4.10.8

**Comment by martynasma** [comment]
I know you're probably tired of hearing this, but can you post a repro case on CodePen or somewhere else? :)

**Comment by jimmykane** [comment]
Maybe this helps ? 

https://beta.quantified-self.io/user/u2rQqTs1tYNrwKXo2go1XLqoOl23/event/dd2d14e790154c142df47ade9ccc821fdc6ca6a01f0fc5681ff0de67c026b8a2 


On the beta domain you have all sourcemaps and non minified code. 

Open the link, scroll quickly down to the chart and you will see the issue. The console should have the stack , adding a debug point should work

**Comment by martynasma** [comment]
Thanks, this helps. Will let you know when we figure it out.

**Comment by jimmykane** [comment]
Great. I can also try to debug this. As mentioned (did some bisect with GIT) it breaks at 4.10.8 and after. Others work :-D

**Comment by martynasma** [comment]
Thanks. This should be GTG from next version. Will ping you once it's out. Probably by the end of this week.

**Comment by jimmykane** [comment]
Great to hear so. 

Just a little thing I wanted to add when I just saw the message, I though it was some es6 array creates. I had issues with those on my projects as well as array spreads. To me it looks like array spreads are so slow vs concats.

**Comment by martynasma** [comment]
Fixed in [4.10.10](https://github.com/amcharts/amcharts4/releases/tag/4.10.10).

## [4.10.10] - 2020-11-03

### Changed
- License check for `MapChart` was not working. If you are using commercial `MapChart`, make sure you use `addLicense()` for both Charts and Maps products.

### Fixed
- Better dispose check for delayed `"out"` event.
- Applying accessibility to some labels with only numeric information was resulting in error.
- Chart could result in an SO in some rare cases.
- Using `strictMinMax` with `includeRangesInMinMax` sometimes could caulse wrong zooms.
- In some cases Legend's item labels were being truncated when cahrt container was shrinking, but were not being restored to their full width once it was enlarged back.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
