### ISSUE TITLE
Wrong initial zoom with series range and includeRangesInMinMax=true

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3050]
**Bug description**

Chart zooms y axis initial to wrong values if series range is used with includeRangesInMinMax=true and series has negative values.
Seems like only the series range is used for min y calculation.

https://codepen.io/chrisadler/pen/VwjxBXM?editors=0010

![image](https://user-images.githubusercontent.com/58069494/97869245-6de05500-1d11-11eb-9d4f-ba4f4e6fb70a.png)

**Environment (if applicable)**

 - amCharts version: 4.10.9 (and earlier)
 - Browser and its version: all browsers

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.10.10](https://github.com/amcharts/amcharts4/releases/tag/4.10.10).

## [4.10.10] - 2020-11-03

### Changed
- License check for `MapChart` was not working. If you are using commercial `MapChart`, make sure you use `addLicense()` for both Charts and Maps products.

### Fixed
- Better dispose check for delayed `"out"` event.
- Applying accessibility to some labels with only numeric information was resulting in error.
- Chart could result in an SO in some rare cases.
- Using `strictMinMax` with `includeRangesInMinMax` sometimes could caulse wrong zooms.
- In some cases Legend's item labels were being truncated when cahrt container was shrinking, but were not being restored to their full width once it was enlarged back.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
