### ISSUE TITLE
MapChart country name translation

### ISSUE THREAD

**Issue by samuel-p** [amcharts/amcharts4#306]
Is there an option to translate the country names in a MapChart? 
The name attribute and the title attribute (like in v3) in the values does not work. Is there an other attribute I can use?

Here is an example:
https://codepen.io/anon/pen/XPNVEa

**Comment by martynasma** [comment]
Well, technically, the "name" works in the data. However, since you also have `useGeodata = true`, the names get copied over from GeoJSON overwriting what you have.

The solution is to add it to some other field, like "title" as you currently have. Then set up map serie's data fields to get their names from "title":

```
polygonSeries.dataFields.name = "title";
```

**Comment by martynasma** [comment]
That said, I guess we could not overwrite "name" if it's already set.

I opened a separate issue for that: #307

You can subscribe to it so you are up to date if there are any developments.

**Comment by samuel-p** [comment]
Thanks, the option `polygonSeries.dataFields.name = "title";` works perfectly for me.
