### ISSUE TITLE
Tooltip: showTooltipOn = hit not triggered by keyboard

### ISSUE THREAD

**Issue by bryanbuchs** [amcharts/amcharts4#3087]
I've got a map with a polygonSeries. Each mapPolygons element has an associated tooltip. I can show that on `hit` using `template.showTooltipOn`. But the `hit` event isn't catching keyboard events, only the mouse click.

My map objects are focusable, and if I attach an event listener with `mapPolygons.template.events.on('hit')`, I can trigger them by mouse or keyboard.  But then I guess I'm needing to manage tooltip visibility manually?

Shouldn't the `showTooltipOn: 'hit'` take into account keyboard actions? Or am I missing something?

**Comment by martynasma** [comment]
Fixed in [4.10.11](https://github.com/amcharts/amcharts4/releases/tag/4.10.11).

## [4.10.11] - 2020-11-13

### Added
- New setting `reverseGeodata` (default: `false`) on `MapChart` and `MapSeries`. amCharts requires polygon coordinates to be in clockwise order. Some map data have them in counter-clockwise. If your custom map appears garbled, try setting this to `true`.
- New global option: `am4core.options.pixelPerfectPrecision` (default: `0`). Precision (number of decimal points) to be used when rounding point x/y for elements that have `pixelPerfect = true` set.

### Fixed
- `XYChartScrollbar` was not inheriting `inputDateFormat` from the chart properly.
- Clicking on a chart on mobile devices could sometimes make them document scroll a bit.
- Accessibility: pressing ENTER while there is a focused element with `showTooltipOn = "hit"` will not display its tooltip.
- RangeSelector (plugin) was not properly removing its elements after `dispose()` it will now auto-dispose when related axis is disposed.
- In some cases a console error could be displayed when using `XYCursor` over chart when data was being updated.
- Very long labels with `wrap = true` may have been wrapping incorrectly in some cases.
- JSON config: `rgb(...)` and `rgba(...)` syntax was not recongnised in `ColorSet`'s `baseColor`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
