### ISSUE TITLE
Multiple axes - sometimes zoom on oY axes is on

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#310]
Having the pen below: https://codepen.io/aniov/pen/eLvNzE?editors=0010

Sometimes when chart is generated or you are toggling between legends, there is an auto zoom on oY axes. Pressing zoom out button will not work but manually using slider to zoom-in-out will bring it to normal state.

![multiaxes-auto-y-zoom](https://user-images.githubusercontent.com/21243081/44944655-3305ce00-ade3-11e8-862e-4e9b3acc1397.gif)

**Comment by zeroin** [comment]
Well, this particular chart has more problems, not only this one - zooming x scrollbar will result line to disappear. This happens because your data is very messy. If you set a data directly on series, then at lease you should use separate data providers which would contain only the data they need:

https://codepen.io/team/amcharts/pen/gdzaXR?editors=0010

With your data structure things get so complicated that I am even afraid to look at it (although I honestly tried) :) Like both of your series get data provider which has 120+12 data points, however category axes only get 12 or 120 data points.
