### ISSUE TITLE
Radar Chart with Multiple Years Data

### ISSUE THREAD

**Issue by SrinivasKothapalli** [amcharts/amcharts4#3105]
**Would like to display Multiple Year Data in Radar Chart**

Trying to Display multiple Years in radar chart , say data from 
Jan 2019 to Dec 2020 which 2 years of data but when it comes to displaying months only 2019 (Jan to Dec) getting plotted
but for 2020 no months getting plotted 

 Code Pen:
https://codepen.io/srinivaskothapalli/pen/jOrRZZx

![image](https://user-images.githubusercontent.com/22912906/99507466-683d6d00-29a9-11eb-978f-ce525599e27c.png)

Want to Display 2 Years Months, in the above example Months for 2019 is not plotted

**Comment by xorspark** [comment]
Your month range loop's end condition needs to be adjusted to draw the additional ranges from the subsequent year(s). In your case, you have 17 months worth of data, so you should loop while i < 17. Since your index will go beyond 11, you need to calculate the correct index using modulo 12 so you can wrap around the dateFormatter's months array once i > 11:

```
// add month ranges
for (var i = 0; i < 17; i++) {
  // ...
  range.label.text = chart.dateFormatter.language.translate(chart.dateFormatter.months[i%12])
  // ...
}
```
