### ISSUE TITLE
Drill-down Treemap Legend Refreshing ?

### ISSUE THREAD

**Issue by KunyuHe** [amcharts/amcharts4#3120]
**Question**

Hi, I've been trying to implement a multilevel treemap following [this example](https://www.amcharts.com/docs/v4/chart-types/treemap/#Multi_level_drill_down). In my use case, some of the squares can be quite small relatively, hence hard for the user to see and interact with.

I tried to simply add a legend but found that each time when you hit a square, it only appends the `TreemapSeries` of that square to the legend data. I would like to add a legend to the chart so that it refreshes to reflect `TreemapDataItem`s on the current level only when the user hit the square, zoom out, or hit the navigation bar. I'm wondering if there's a way to do that?

Please see the pen linked below:

https://codepen.io/kunyuhe/pen/gOMVMxm

Thanks a lot!

**Environment (if applicable)**

 - amCharts version: amCharts 4

**Comment by martynasma** [comment]
The second-level item appearing in the legend is a bug.

Normal behavior of a legend in TreeMap is to show all items for the level that has more than one node. In your case that's the top-most level.

We will fix dynamic adding of a clicked node in the next version.

Unfortunately, there's no such option to add sub-nodes of a currently selected node to the legend. Sorry.

It could be possible by dynamically manipulating legend's data items, but unfortunately, we do not have a demo like that.

**Comment by martynasma** [comment]
Fixed in [4.10.12](https://github.com/amcharts/amcharts4/releases/tag/4.10.12).

## [4.10.12] - 2020-11-26

### Changed
- `DateAxis` setting `timezone` is being deprecated. Please consider setting `timezone` on chart or axis `dateFormatter`. `DateAxis` will now properly place grid in time zones that use non-whole hour fractions, e.g. ("Australia/Adelaide").
- Accessibility: Roles and tabindexes in `ExportMenu` elements has been altered to better comply with ARIA standards.

### Fixed
- Scrollbar could act funky when repeatedly clicking on its grips.
- A minor conflict with Google Charts lib on IE fixed.
- Improved performance of `ValueAxis` scale calculation.
- Setting `min` and `max` on a `DateAxis` could result in excessive overzoom and an empty grid in some cases.
- Overzooming `DateAxis` coul dresult in some extra space shown on it.
- Legend was dynamically adding items on a Treemap chart when drilling-down.
- When Legend's labels' `width` were set in percent, they were not being properly sized.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
