### ISSUE TITLE
JSON configuration for gauge with label 

### ISSUE THREAD

**Issue by fredmef** [amcharts/amcharts4#3123]
**Question**
Hi,
I'm looking for a JSON configuration for a gauge with a label displaying the value.
I've tried the following configuration without any success (label is not displayed):
```
'#config' => [
        'innerRadius' => '85%',
        'xAxes' => [
          [
            'type' => 'ValueAxis',
            'min' => 0,
            'max' => 10000,
            'strictMinMax' => TRUE,
            'axisRanges' => [
              [
                'value' => 0,
                'endValue' => 6000,
                'axisFill' => [
                  'fillOpacity' => 1,
                  'fill' => 'green',
                ],
              ],
              [
                'value' => 6000,
                'endValue' => 9000,
                'axisFill' => [
                  'fillOpacity' => 1,
                  'fill' => 'orange',
                ],
              ],
              [
                'value' => 9000,
                'endValue' => 10000,
                'axisFill' => [
                  'fillOpacity' => 1,
                  'fill' => 'red',
                ],
              ],
            ],
          ],
        ],
        'hands' => [
          [
            'type' => 'ClockHand',
            'value' => $duration,
            'innerRadius' => '50%',
            'radius' => '80%',
            'startWidth' => 15,
          ],
        ],
        'children' => [
          [
            'type' => 'Label',
            'text' => $duration,
          ],
        ],
      ]
```

Here is the result. As you can see no label is displayed.
<img width="864" alt="Capture d’écran 2020-11-24 à 17 17 23" src="https://user-images.githubusercontent.com/41957018/100122384-99baaa80-2e79-11eb-82fc-0a97be5f2eb6.png">

Thanks for your help,
Regards.

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
Depending on where in the hierarchy you're attaching your objects, you may need to set `forceCreate` to `true` so that the creation process doesn't ignore it due to existing objects in that level. In your case, you're adding directly onto the chartContainer, which will already have children created from your other properties (hands, ranges, axes, etc), so adding a label requires `forceCreate`:

```
config = {
  // ...
  children: [{
    forceCreate: true,
    type: "Label",
    text: "some text",
    // ...
  }],
  // ...
}
```

If you're adding to a different pre-defined container, such as `radarContainer`, you need to set `forceCreate` on it as well:

```
  "radarContainer": {
    "forceCreate": true,
    "children": [{
      "type": "Label",
      "forceCreate": true,
      "isMeasured": false,
      "x": "50%",
      "fontSize": "2em",
      "paddingBottom": 15,
      "verticalCenter": "bottom",
      "horizontalCenter": "middle",
      "text": "Test"
    }] 
  },
```

[This section in the JSON config documentation](https://www.amcharts.com/docs/v4/concepts/json-config/#Creating_or_reusing_) explains this scenario in more detail.
