### ISSUE TITLE
Date Axis shows incorrect labels for timezone 'Australia/Adelaide'

### ISSUE THREAD

**Issue by frank-fajardo-a142179** [amcharts/amcharts4#3135]
**Bug description**

XYChart with DateFormatter set to have 'Australia/Adelaide' for timezone shows incorrect labels.

For example, this weekly chart has data starting at 23 Nov, and the date axis set as follows:
```
chart.dateFormatter.inputDateFormat = 'i';
chart.dateFormatter.timezone = 'Australia/Adelaide';
...
dateAxis.strictMinMax = true;
dateAxis.min = new Date('2020-11-23T00:00:00+10:30').getTime();
dateAxis.max = new Date('2020-11-30T00:00:00+10:30').getTime();
dateAxis.baseInterval = {
  timeUnit: 'day',
  count: 1
};
```

However, the chart's date axis starts on 22 Nov, instead of 23 Nov:
![image](https://user-images.githubusercontent.com/35437382/100557874-ce0deb00-32ff-11eb-85b1-11d344a48283.png)

Link to this example on CodePen: https://codepen.io/frankfajardo/pen/qBaEQeg

**Environment (if applicable)**

 - amCharts version 4.10.12

**Additional context**

N/A

**Comment by martynasma** [comment]
Fixed in [4.10.13](https://github.com/amcharts/amcharts4/releases/tag/4.10.13).

## [4.10.13] - 2020-12-18

### Added
- Export: PDF export options now support `scale`, `minWidth`, `minHeight`, `maxWidth`, and `maxHeight` options.

### Changed
- Setting `ignoreZeroValues = true` on `PieSeries`/`PyramidSeries` will now hide `null`-value slices, too.

### Fixed
- Inserting a new bullet into an initialized Series will now invalidate it cause the new bullet to appear immediately.
- Using `timezone` might shift axis label values by one day in some cases.
- `"i"` input date format was not properly parsing formats with no milliseconds and with timezone offset, e.g. (`"...+10:30"`).
- Export: `normalizeSVG()` method was producing wrong SVG width/height in output if scale parameter was not being passed in.
- RangeSelector plugin: "YTD" pre-defined period was not working properly with some data-grouping setups.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
