### ISSUE TITLE
Removing (or adjusting) the space between 2 (or more) column series.

### ISSUE THREAD

**Issue by MashRoofa** [amcharts/amcharts4#3148]
Im working on this example taken from this tutorial [Managing width and spacing of Column Series](https://www.amcharts.com/docs/v4/tutorials/managing-width-and-spacing-of-column-series/).

[My Example](https://codepen.io/ChrisMash/pen/wvzMQVb)

The example is slightly modified to allow for full cell width availability and also the columns are set to a fixed value of 50px. What Im trying to achieve is to make the two column series on each category touch each without changing their width or the cell start and end locations.

**Comment by martynasma** [comment]
I don't think there's an easy way to do that.

It would involve calculating `cellStartLocation`/`cellEndLocation` based of actual width of the `chart.plotContainer` as well as number of data items.

So that actual width of the columns (set in config to 100%) would end up in precise fixed with, e.g. 50px.

It's possible, but I don't think I have a ready-made example like that.

**Comment by MashRoofa** [comment]
Thank you, i will just use the cellStartLocation and cellEndLocation with bars being 100% width. Then, by changing the cellLocations i will manually adjust to the desirable space.
