### ISSUE TITLE
Pdf export, landscape, full width - how to?

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3153]
When export chart to landscape pdf, chart take only part of page width.
I'm trying this settings, but no result:
`
    Chart.main.chart.exporting.title = '';
    Chart.main.chart.exporting.filePrefix = 'StandartCatalogCurve';
    Chart.main.chart.exporting.formatOptions.getKey("pdf").addURL = false;
    Chart.main.chart.exporting.formatOptions.getKey("pdf").pageOrientation = 'landscape';
    Chart.main.chart.exporting.formatOptions.getKey("pdf").minWidth = 1920*2;
    Chart.main.chart.exporting.formatOptions.getKey("pdf").minHeight = 1080*2;
    Chart.main.chart.exporting.formatOptions.getKey("pdf").pageSize = "A4";
`

![image](https://user-images.githubusercontent.com/11944160/101295579-ed44d500-3837-11eb-8e11-47a3eac4a408.png)

**Comment by martynasma** [comment]
Currently, PDF export option does not support those options. We'll add it in the next version to be released this week.

I'll let you know here when it happens.

**Comment by martynasma** [comment]
Fixed in [4.10.13](https://github.com/amcharts/amcharts4/releases/tag/4.10.13).

## [4.10.13] - 2020-12-18

### Added
- Export: PDF export options now support `scale`, `minWidth`, `minHeight`, `maxWidth`, and `maxHeight` options.

### Changed
- Setting `ignoreZeroValues = true` on `PieSeries`/`PyramidSeries` will now hide `null`-value slices, too.

### Fixed
- Inserting a new bullet into an initialized Series will now invalidate it cause the new bullet to appear immediately.
- Using `timezone` might shift axis label values by one day in some cases.
- `"i"` input date format was not properly parsing formats with no milliseconds and with timezone offset, e.g. (`"...+10:30"`).
- Export: `normalizeSVG()` method was producing wrong SVG width/height in output if scale parameter was not being passed in.
- RangeSelector plugin: "YTD" pre-defined period was not working properly with some data-grouping setups.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by russeljo** [comment]
Hi, after update to this release, my landscape pdf still take only part of page width.
Maybe, I miss something? Cache was cleared.

**Comment by dhiren-eng** [comment]
Hi @martynasma , facing the same issue in landscape orientation. Looks like minWidth and scale are not working
