### ISSUE TITLE
The mouse cursor position can be lost when swiping a column chart

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#316]
Try swipe the chart below left and right. The final position sometimes stays before or after where the mouse cursor stopped.

https://codepen.io/team/amcharts/pen/mGmQQE?editors=0010

**Comment by martynasma** [comment]
This might happen if mouse cursor goes outside chart iframe when still dragging.

This should be happening on CodePen only. For some obscure reason browsers to not generate out or even up events if mouse is moved or released outside codepen iframe, hence chart not knowing that we have released the mouse.

It should not be happening if you open CodePen in a full window mode.

Let me know if you can reproduce this without moving mouse outside iframe.

**Comment by martynasma** [comment]
Indeed, it's a bug. Thanks.

**Comment by martynasma** [comment]
Fixed in dev. Will be in the next release.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.49](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.49).

## [4.0.0-beta.49] - 2018-09-05

### Added
- JSON config: added `callback` property, which if it holds a reference to function will call it within the scope of the object being prepared.
- Adapters for `url` and `urlTarget` properties.
- Chart can now be panned or zoomed using mouse wheel. To set what it does use `mouseWheelBehavior` on `XYChart` (see next point)
- [`mouseWheelBehavior`](https://www.amcharts.com/docs/v4/reference/xychart/#mouseWheelBehavior_property) added to `XYChart`. Options: `"zoomX"` (default), `"zoomY"`, `"zoomXY"`, `"panX"`, `"panY"`, `"panXY"`, `"none"`.
- [`mouseWheelBehavior`](https://www.amcharts.com/docs/v4/reference/mapchart/#mouseWheelBehavior_property) added to `MapChart`. Options: `"zoom"` (default), `"none"`.

### Changed
- Second parameter to `Cursor`'s [`triggerMove()`](https://www.amcharts.com/docs/v4/reference/cursor/#triggerMove_method) method was changed from boolean to enumeration of "stickiness" level: `"hard"`, `"soft"`, `"none"` (default).

### Fixed
- Error fixed when `Popup` object was being disposed.
- Over-panning of an `XYChart` did not disappear after mouse button was released outside chart.
- Multiple memory leaks fixed.
- `MapChart` was rounding lat/long coordinates too much which was resulting in pixelated maps for small-area maps.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
