### ISSUE TITLE
Question: Chart Map Zoom

### ISSUE THREAD

**Issue by kothve** [amcharts/amcharts4#3160]
**Question**

Hi,

This question relates to map charts.

Is there an option to remove all data points outside of zoom scope when clicking on country/state?

Pictures illustrate the issue when pressing on "Brazil". Datapoints not part of brazil are still being shown. Is there a built in option to remove those data points?

If the option is available, is it also available in V3 of amcharts?

Thank you for your time.
![Screen Shot 2020-12-10 at 3 10 49 PM](https://user-images.githubusercontent.com/7607272/101825741-0d0c1f80-3afc-11eb-9594-c5e5d1d627e9.png)

![Screen Shot 2020-12-10 at 3 10 02 PM](https://user-images.githubusercontent.com/7607272/101825773-19907800-3afc-11eb-9ce7-54fdec74af48.png)

**Comment by martynasma** [comment]
No, I'm afraid there's no such option. Sorry.

**Comment by plsoucy-tapclicks** [comment]
Thanks for the information. We're looking at possibly using a "point in polygon" algorithm to filter out the points based on the area the user has zoomed in, given that there is no such option in amCharts. 

We have the lat/long for our data points, so we would need the polygons for the area we are zooming in, with vertices in lat/long format. Is there an easy way to get that from amCharts directly or convert that from files like https://www.amcharts.com/lib/3/maps/js/usaHigh.js (which do not seem to be in lat/long format)?

Thanks!

**Comment by martynasma** [comment]
I'm sorry, but we do not have such built-in function which would check if lat/long point is within certain polygon :(

**Comment by plsoucy-tapclicks** [comment]
Thanks - we should be able to take care of the point-in-polygon logic if we have the polygon definitions with lat/long for each vertex for each state. In this map definition from amCharts for example - https://www.amcharts.com/lib/3/maps/js/usaHigh.js - I see  polygons defined, but the vertices are not in a direct lat/long format. Is there any way/documentation on how we can get them in lat/long format, or documentation on how to convert them to lat/long format otherwise (which I assume amCharts does internally)?

Thank you!

**Comment by martynasma** [comment]
These are in SVG, from the old version.

You should refer to the V4 maps, that are in GeoJSON format:

https://github.com/amcharts/amcharts4-geodata/tree/master/dist/script/json
