### ISSUE TITLE
Range Selector shows only 5 days after clicking MAX then YTD

### ISSUE THREAD

**Issue by dnewkerk** [amcharts/amcharts4#3169]
**Bug description**

I've run into a bug with the [Stock Chart](https://www.amcharts.com/demos/stock-chart/), using the Range Selector plugin.  If you click the MAX range selector button, and next click the YTD button, instead of showing the actual YTD, it shows only the most recent 5 days.

To reproduce the issue I forked a copy of the official stock chart demo, and only modified it by replacing the CSV data with a JavaScript object of my data, and adjusted the dataFields to match my object keys (in my use case, the data comes from an API response, not from a CSV file):
https://codepen.io/dnewkerk/pen/QWKpprx

I've included a screenshot below of what happens as well.

If you click a different range selector button such as 1M and then click YTD, it works correctly. The issue only occurs when you first click MAX and then next click YTD.

I've tested with date formatted as a string, Date object, and timestamp, but the effect was the same in each case. All string dates in the series converted to Date objects/timestamps without error, so it doesn't appear to be a faulty date somewhere in the data.

I've tested converting my data to a CSV file and loading it in place of the sample CSV, and the issue still is present. I'm attaching my CSV in case you'd like to try it (I was unable to get the remote file to load in the codepen).

I've also tested reducing the number of objects down to a lower number (e.g. 1500 objects) and the issue does not seem to occur at this point.

It doesn't seem to be specifically due to the large number of objects, since my series contains 3262 objects, and the stock chart demo has more, at 3674 objects. The main difference I can see is that my data has values for the current year, rather than stopping at a point further than a year in the past, so the demo stock chart is not actually loading YTD but the most recent year it has (2013-2014). However this might not be the key either since if I load only the first 1500 or so objects from my data (with earlier dates), the issue does not occur there either.

Please let me know if there's anything further I can provide to help troubleshoot the bug. Thanks in advance!

![amcharts-ytd-bug](https://user-images.githubusercontent.com/1725553/102181800-dc681500-3e70-11eb-9ca8-d027cd8fcf77.png)

[MSFT.csv.txt](https://github.com/amcharts/amcharts4/files/5693879/MSFT.csv.txt)

**Comment by martynasma** [comment]
Fixed in [4.10.13](https://github.com/amcharts/amcharts4/releases/tag/4.10.13).

## [4.10.13] - 2020-12-18

### Added
- Export: PDF export options now support `scale`, `minWidth`, `minHeight`, `maxWidth`, and `maxHeight` options.

### Changed
- Setting `ignoreZeroValues = true` on `PieSeries`/`PyramidSeries` will now hide `null`-value slices, too.

### Fixed
- Inserting a new bullet into an initialized Series will now invalidate it cause the new bullet to appear immediately.
- Using `timezone` might shift axis label values by one day in some cases.
- `"i"` input date format was not properly parsing formats with no milliseconds and with timezone offset, e.g. (`"...+10:30"`).
- Export: `normalizeSVG()` method was producing wrong SVG width/height in output if scale parameter was not being passed in.
- RangeSelector plugin: "YTD" pre-defined period was not working properly with some data-grouping setups.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
