### ISSUE TITLE
Map displays generated local geoData imprecise

### ISSUE THREAD

**Issue by freinold** [amcharts/amcharts4#318]
I generated a local Geojson Map of Munich and simplified it further before using it in geoDataSource.
Ideally, it should look like this:

![maplow1](https://user-images.githubusercontent.com/32450519/45030104-153aa200-b04b-11e8-9b25-7aed48d56142.png)

But when it was displayed by amcharts4, there were huge imprecisions:

![maplow2](https://user-images.githubusercontent.com/32450519/45030116-1bc91980-b04b-11e8-8641-d0af6275ef69.png)

Is there something i can do to resolve this problem?

**Comment by martynasma** [comment]
Have you tried setting less aggressive simplification setting?

**Comment by freinold** [comment]
Yeah, also did it with the raw map, same output. Actually the upper map is drawn with the same .geojson file as the bottom one in amcharts4

**Comment by freinold** [comment]
Thanks for your help so far!
I didnt use any shapefile, but the [OSM overpass turbo API](http://overpass-turbo.eu/#) to directly create a .geojson file. Here's the one I got (only used .txt to upload it):
[munichDistrictsHigh.geo.json.txt](https://github.com/amcharts/amcharts4/files/2351629/munichDistrictsHigh.geo.json.txt)

**Comment by martynasma** [comment]
OK, we traced this back to how we round coordinates. This is now fixed in dev and will be released shortly.

Thanks for bringing it to our attention!

**Comment by freinold** [comment]
Thanks for responding so quickly!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.49](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.49).

## [4.0.0-beta.49] - 2018-09-05

### Added
- JSON config: added `callback` property, which if it holds a reference to function will call it within the scope of the object being prepared.
- Adapters for `url` and `urlTarget` properties.
- Chart can now be panned or zoomed using mouse wheel. To set what it does use `mouseWheelBehavior` on `XYChart` (see next point)
- [`mouseWheelBehavior`](https://www.amcharts.com/docs/v4/reference/xychart/#mouseWheelBehavior_property) added to `XYChart`. Options: `"zoomX"` (default), `"zoomY"`, `"zoomXY"`, `"panX"`, `"panY"`, `"panXY"`, `"none"`.
- [`mouseWheelBehavior`](https://www.amcharts.com/docs/v4/reference/mapchart/#mouseWheelBehavior_property) added to `MapChart`. Options: `"zoom"` (default), `"none"`.

### Changed
- Second parameter to `Cursor`'s [`triggerMove()`](https://www.amcharts.com/docs/v4/reference/cursor/#triggerMove_method) method was changed from boolean to enumeration of "stickiness" level: `"hard"`, `"soft"`, `"none"` (default).

### Fixed
- Error fixed when `Popup` object was being disposed.
- Over-panning of an `XYChart` did not disappear after mouse button was released outside chart.
- Multiple memory leaks fixed.
- `MapChart` was rounding lat/long coordinates too much which was resulting in pixelated maps for small-area maps.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
