### ISSUE TITLE
Solid gouge watermark is drawn over graph rather then under graph

### ISSUE THREAD

**Issue by sdapkus** [amcharts/amcharts4#3184]
**Bug description**
Using solid gauge (RadarChart) and adding water mark to it, water mark is drawn over graph, because of this few issues appears:
* When hovering mouse over graph where water mark is, no tool tip is shown
* On other graph types, water mark isn't covering graph itself, because water mark is on top, some parts of graph is hidden

CodePen (https://codepen.io/sdapkus/pen/xxEYEvr)
I've copied Solid gauge example from docs and just add water mark.

**Environment (if applicable)**

 - amCharts: Tried on 4.7.0 and 4.10.13
 - Chrome 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

I have used water mark in XYChart at there it works as expected, but on this chart type it works different

**Comment by xorspark** [comment]
You need to add the watermark to the chart container like the original demo does, not the `plotContainer`

```
chart.children.push(watermark);
```

**Comment by sdapkus** [comment]
When not using `plotContainer` water mark is drawn below graph.
https://www.amcharts.com/docs/v4/tutorials/adding-watermarks-to-charts/#Positioning
Here it says it can be added to `plotContainer` and even screenshot shows where it is drawn then.

**Comment by xorspark** [comment]
Right. The documentation also mentions tweaking the alignment to position it. Note that the plotContainer's layout is set to absolute ([docs](https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/#Pre_defined_chart_containers)), so your positioning has it set to draw in the center - this is expected. If you want the watermark placed at the bottom right, set the alignment accordingly if you're adding to the plotContainer.

```
watermark.align = "right";
watermark.valign = "bottom";
```

The tooltip issue you're describing is also expected since the label is drawn on top of the other elements so it intercepts the events. You have to set `interactionsEnabled` to false on the label so that it doesn't capture the mouseover event (`watermark.interactionsEnabled = false;`), allowing the tooltips to appear.

**Comment by sdapkus** [comment]
Yes, position where watermark appears is correct.
I understand that because watermark is drawn on top of series it is intercepting events. But it is strange, that in `XYChart` by default watermark is drawn under series ([example](https://codepen.io/sdapkus/pen/qBaxrgj)), but on RadarChart watermark is drawn over series by default.

I tried setting `zIndex` for water mark to `-1` then it appears under series and it starts working as I'm expecting (same as XYChart). So it is not a bug then, but it is inconsistency between different chart types.

Also please note these examples [docs](https://www.amcharts.com/docs/v4/tutorials/adding-watermarks-to-charts/#Setting_container_s_fill), [docs](https://www.amcharts.com/docs/v4/tutorials/adding-watermarks-to-charts/#Image_patterns) in both of these, watermark is drawn under series and there is no `zIndex` needed to achieve that.

**Comment by xorspark** [comment]
Each chart type draws its elements in different orders for a variety of reasons; it just so happens that XYChart is set up in such a way that you don't need to use `zIndex` to keep the label underneath everything. I'll let the team know to add a note about this to call this out more clearly.
