### ISSUE TITLE
Artefacts when zooming StepLine charts

### ISSUE THREAD

**Issue by ngerasimoff** [amcharts/amcharts4#3201]
Hello everyone! 
Could you please explain me how to get rid of zooming artefacts in **StepLine** charts.
For example, I can observe these glitches when using scrollbar handlers..moving them from left to right, especially when I do it relatively fast. One important note is that I need to set property **`connect`** equal to **`false`**.

![artefacts](https://user-images.githubusercontent.com/53784088/104276563-2ff07180-54b6-11eb-9816-1805d25059c2.jpg)

[**Basic example based on your demo chart**](https://codepen.io/defoox/pen/RwGewNg)

1. Latest version of Amcharts
2. Checked in Chrome/Opera/Mozilla
3. with the latest version of React

**Comment by martynasma** [comment]
Fixed in [4.10.14](https://github.com/amcharts/amcharts4/releases/tag/4.10.14).

## [4.10.14] - 2021-02-02

### Added
- Exporting: all adapters related to XLSX export, will now have `xslx` property holding reference to processor, that needs to be used in order to modify actual workbooks for export.

### Fixed
- `StepLineSeries` might get "stuck" during zoom/data updates in some cases.
- `ColumnSeries3D` was not staying hidden across data updates.
- Columns on `DateAxis` were not being positioned properly when changing `firstDayOfWeek`.
- RangeSelector plugin: YTD was not working properly when data was being grouped to years.
- Disposing chart on a click of a custom `ExportMenu` item was resulting in JS errors.
- In some setups "ghost paper" (invisible div) was influencing document layout.
- In charts where Series had very small amplitude of values, related `ValueAxis` could get end up in a dead loop.
- HTML tooltips were not being sized properly in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
