### ISSUE TITLE
Column3D series no longer hidden after data update

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3216]
**Bug description**

In a **XYChart3D** a hidden **ColumnSeries3D** is no longer hidden after data update.
If you hide both series by clicking on the legend markers, after a chart update only the line series is still hidden.

![image](https://user-images.githubusercontent.com/58069494/104590177-3c69fb00-566b-11eb-97f5-ee0276e09842.png)

https://codepen.io/chrisadler/pen/ZEpmLbV

**Environment (if applicable)**

 - amCharts version: 4.10.3
 - Browser and its version: all browsers

**Comment by martynasma** [comment]
Fixed in [4.10.14](https://github.com/amcharts/amcharts4/releases/tag/4.10.14).

## [4.10.14] - 2021-02-02

### Added
- Exporting: all adapters related to XLSX export, will now have `xslx` property holding reference to processor, that needs to be used in order to modify actual workbooks for export.

### Fixed
- `StepLineSeries` might get "stuck" during zoom/data updates in some cases.
- `ColumnSeries3D` was not staying hidden across data updates.
- Columns on `DateAxis` were not being positioned properly when changing `firstDayOfWeek`.
- RangeSelector plugin: YTD was not working properly when data was being grouped to years.
- Disposing chart on a click of a custom `ExportMenu` item was resulting in JS errors.
- In some setups "ghost paper" (invisible div) was influencing document layout.
- In charts where Series had very small amplitude of values, related `ValueAxis` could get end up in a dead loop.
- HTML tooltips were not being sized properly in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
