### ISSUE TITLE
Makes hidden 200px by 200px container in the corner

### ISSUE THREAD

**Issue by njfix6** [amcharts/amcharts4#3245]
**Bug description**
Our AM Chart is affecting out CSS by making this hidden 200px by 200px container in the bottom left corner. It is affecting our footer but it probably should not be there at all. 

I know if is the amchart becuase when I comment out the component, it goes away. I is also only on a chart that is completely empty. Only this line is present: `am4core.create('chartdiv', am4charts.XYChart),`

<img width="734" alt="Screen Shot 2021-01-22 at 8 51 10 AM" src="https://user-images.githubusercontent.com/6845581/105505885-15c14b00-5c8f-11eb-9cfd-3aa9aed30671.png">

**Environment (if applicable)**
 - amCharts version - 4.10.13
 - Browser and its version - Chrome Version 87.0.4280.141
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - Typescript.

**Additional context**

**Comment by martynasma** [comment]
Fixed in [4.10.14](https://github.com/amcharts/amcharts4/releases/tag/4.10.14).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
