### ISSUE TITLE
Issue with ytd preselection and notion of ytd

### ISSUE THREAD

**Issue by ranell** [amcharts/amcharts4#3249]
Hi,

This code preselect YTD (year to date) instead of max. Year to date, begins from the last day of the the last year, until the last date.

Therefore, the preselection  should begin the 2153-12-31 to 2154-11-23. Instead, it displays date from 2153-11-23 to 2154-11-23. This seems to be the 1Y Period ?

Anyway the preselection and first displaying is different when you click again on YTD (and here YTD begins from 2154-01-01, instead of 2153-12-31)

https://codepen.io/Lenny186/pen/VwKOBRg

**Comment by martynasma** [comment]
Indeed, it's a bug. We'll fix it in the next version.

Just to make sure YTD will mean a period from the Jan 1st of the last year in data to the end of the data.

**Comment by ranell** [comment]
Hi
Thanks a lot. Is there anyway to redefine, in my code,  YTD as from the last day of 2020 until now ?

**Comment by martynasma** [comment]
No, at least not with RangeSelector.

**Comment by martynasma** [comment]
Fixed in [4.10.14](https://github.com/amcharts/amcharts4/releases/tag/4.10.14).

## [4.10.14] - 2021-02-02

### Added
- Exporting: all adapters related to XLSX export, will now have `xslx` property holding reference to processor, that needs to be used in order to modify actual workbooks for export.

### Fixed
- `StepLineSeries` might get "stuck" during zoom/data updates in some cases.
- `ColumnSeries3D` was not staying hidden across data updates.
- Columns on `DateAxis` were not being positioned properly when changing `firstDayOfWeek`.
- RangeSelector plugin: YTD was not working properly when data was being grouped to years.
- Disposing chart on a click of a custom `ExportMenu` item was resulting in JS errors.
- In some setups "ghost paper" (invisible div) was influencing document layout.
- In charts where Series had very small amplitude of values, related `ValueAxis` could get end up in a dead loop.
- HTML tooltips were not being sized properly in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by ranell** [comment]
Hi and Thanks for this reply
as i'm calling script in this way
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
	<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
	<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
	<script src="https://cdn.amcharts.com/lib/4/plugins/rangeSelector.js"></script>
	<script src="https://cdn.amcharts.com/lib/4/lang/fr_FR.js"></script>
your fixes should appears ? because i'm still having the same issue.
