### ISSUE TITLE
Donut and Pie Charts are not working properly 

### ISSUE THREAD

**Issue by AnjelikaVolotka** [amcharts/amcharts4#3250]
**Right blue section for Lithuania is not in line**

1. Go to https://www.amcharts.com/demos/#pie
2. Try to work with Pie Chart With Legend
<img width="1429" alt="Screenshot 2021-01-25 at 16 48 15" src="https://user-images.githubusercontent.com/77978150/105723280-47584180-5f2f-11eb-9840-65db59d9b924.png">
<img width="1427" alt="Screenshot 2021-01-25 at 16 48 44" src="https://user-images.githubusercontent.com/77978150/105723288-49220500-5f2f-11eb-9cb3-d0444126354e.png">

**Environment (if applicable)**

**Additional context**

**Comment by amcharts** [comment]
When you click on a slice, all we do is move it along the vector of the middle of a slice by the same distance. And this is the result, all the slices are moved by the same distance. The side effect which you see happens because the slices are not equal. If you take this picture open it in photoshop, select the bigger slice and try to move it, you will see that you won't find any position which would be "correct". Unless you scale the slice, and also adjust inner radius. But we really are not going to do this, sorry.
