### ISSUE TITLE
Some HTML tooltip contents truncated when wrap = true

### ISSUE THREAD

**Issue by redc2** [amcharts/amcharts4#3255]
**Bug description**

When using series HTML tooltips with `series.tooltip.label.wrap = true`, some tooltip contents appear to be truncated at the end.

See [this pen](https://codepen.io/redc22/pen/rNMXgmQ) for example. The values for dates 2020-01-02 and 2020-01-05 are cut off in the series tooltips. With longer tooltip contents (such as the one commented out in the pen), the wrapping seems to work fine. It seems with `series.tooltipText` there are also no issues displaying the full text.

Is this a bug or am I just missing something?

**Environment**

Latest stable Chrome and FF.

**Comment by martynasma** [comment]
Fixed in [4.10.14](https://github.com/amcharts/amcharts4/releases/tag/4.10.14).

## [4.10.14] - 2021-02-02

### Added
- Exporting: all adapters related to XLSX export, will now have `xslx` property holding reference to processor, that needs to be used in order to modify actual workbooks for export.

### Fixed
- `StepLineSeries` might get "stuck" during zoom/data updates in some cases.
- `ColumnSeries3D` was not staying hidden across data updates.
- Columns on `DateAxis` were not being positioned properly when changing `firstDayOfWeek`.
- RangeSelector plugin: YTD was not working properly when data was being grouped to years.
- Disposing chart on a click of a custom `ExportMenu` item was resulting in JS errors.
- In some setups "ghost paper" (invisible div) was influencing document layout.
- In charts where Series had very small amplitude of values, related `ValueAxis` could get end up in a dead loop.
- HTML tooltips were not being sized properly in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
