### ISSUE TITLE
Reverse-chronological order for Serpentine Timeline

### ISSUE THREAD

**Issue by sebgentei** [amcharts/amcharts4#3273]
Hi,

I would like to use the serpentine timeline to represent the career of an employee.
I'd like to have the timeline to start from the most recent event and finish the older one.
To test, I've modified the js script of the example below:
https://www.amcharts.com/demos/serpentine-timeline/

I tried to use the **_inversed_** property on the **_dateAxis.renderer_** which doesn't work.

This property seems to only work when the **dateAxis** is used on other charts like the XY Chart.

I may have missed something but is there a way to have the timeline in reverse-chronological order?

Thanks for your help and advice in advance.

**Comment by xorspark** [comment]
Taking a quick look at the plugin's source, it looks like `inversed` is not supported in curved charts like timeline/serpentine.

**Comment by sebgentei** [comment]
> Taking a quick look at the plugin's source, it looks like `inversed` is not supported for the X axis in curved charts like timeline/serpentine.

Hi @xorspark, Thanks for the reply.

I understand, since I couldn't find the information in the documentation, I thought that maybe I was doing something wrong...
That would be great if there was another way for doing that.

If not, I'll have to use the XY Chart but it would be a bit more complicated and time-consuming since I want to use dynamic data to generate a timeline per employee.

Anyway, thanks for your help.

**Comment by kavi87** [comment]
I too would like this option to be supported.

For now I can think of two solutions:
1. Use a category axis and pre-ordered data, but lose the gap scaling between events
2. Use a scrollbar and set the xAxis "end" to 1 and "start" to something like 0.8 so that user understand they can move the thumb from right to left to go back in time.

If there's no plan of supporting it, are there better solutions for a reverse timeline display ?

Thanks.
