### ISSUE TITLE
Issues when panning inverted graph

### ISSUE THREAD

**Issue by Vaidot** [amcharts/amcharts4#3288]
**Bug description**
If you try to pan graph with inverted axis, it first jumps to either right or left side. 
As the an example just add to https://www.amcharts.com/demos/line-graph/ these lines:
`dateAxis.renderer.inversed = true;`
`chart.cursor.behavior = "panX";`
Then try to pan zoomed in graph.

**Comment by martynasma** [comment]
Fixed in [4.10.16](https://github.com/amcharts/amcharts4/releases/tag/4.10.16).

## [4.10.16] - 2021-03-03

### Fixed
- In some rare cases an critical error could happen on hoverable objects on touch-only displays.
- Zooming and drag-rotating a resized `MapChart` could throw off the map position.
- It was possible to continue zooming the chart using mouse wheel even when max zoom was reached.
- Zooming "inverted" horizontal axis was incorrect.
- Updating data on `SankeyDiagram` in some cases could result in an SO.
- `TreeMap` was showing incorrectly sized nodes with empty children array.
- Sometimes wrapping long strings were causing punctuation at the end of the word to wrap into the next line.
- Dynamically switching `logarithmic` setting for a `ValueAxis` was not updating its scale properly in some cases.
- `SliceGrouper` plugin was not updating properly when manipulating data and/or series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
