### ISSUE TITLE
rotateLong shifts the map on window resize

### ISSUE THREAD

**Issue by kirilcvetkov** [amcharts/amcharts4#3292]
**Bug description**

When the width of the window changes and then I move the map, the whole rectangle of the map would shift left or right depending on if I've increased or decreased the window size. The map goes off-center and sometimes outside of the window, until I resize the window to the original dimensions. It seems like this is some kind of a responsive feature but instead of centering the map, it overshoots.

Steps to reproduce:

1. Codepen - https://codepen.io/kiril-cvetkov/pen/ExNNYbJ
2. Resize browser window
3. Drag the map left or right
4. The map shifts

**Environment (if applicable)**
Tested on:
- Safari - Version 14.0.3 (16610.4.3.1.4)
- Brave - Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)
- Google Chrome - Version 88.0.4324.150 (Official Build) (x86_64)

**Comment by martynasma** [comment]
Fixed in [4.10.16](https://github.com/amcharts/amcharts4/releases/tag/4.10.16).

## [4.10.16] - 2021-03-03

### Fixed
- In some rare cases an critical error could happen on hoverable objects on touch-only displays.
- Zooming and drag-rotating a resized `MapChart` could throw off the map position.
- It was possible to continue zooming the chart using mouse wheel even when max zoom was reached.
- Zooming "inverted" horizontal axis was incorrect.
- Updating data on `SankeyDiagram` in some cases could result in an SO.
- `TreeMap` was showing incorrectly sized nodes with empty children array.
- Sometimes wrapping long strings were causing punctuation at the end of the word to wrap into the next line.
- Dynamically switching `logarithmic` setting for a `ValueAxis` was not updating its scale properly in some cases.
- `SliceGrouper` plugin was not updating properly when manipulating data and/or series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
