### ISSUE TITLE
Removing scrollbar from legend in exported image and adding it back after export (Unable to add it back)

### ISSUE THREAD

**Issue by dhiren-eng** [amcharts/amcharts4#3298]
Hi,

The actual requirement is to show all the legend items in the Legend in exported image.. I was able to do that in this codepen [https://codepen.io/dhiren530/pen/KKNNoQL?editors=0010](https://codepen.io/dhiren530/pen/KKNNoQL?editors=0010) by setting chart.legend.height = chart.legend.contentHeight ; So in exported image, all the legends items were shown successfully.

In exportfinished I had set chart.legend.height back to old maxHeight.  As a result, the scrollbar was hidden and only top few markers were visible after export finished.. 

Before export : 
![image](https://user-images.githubusercontent.com/59474883/107702696-a0222b00-6ce0-11eb-91e3-58b6aadfe2f7.png)

After export scrollbar lost : 
![image](https://user-images.githubusercontent.com/59474883/107702780-c051ea00-6ce0-11eb-8751-c33200c57f7a.png)

Unable to find out what's wrong in my approach. What is the right way to do it ?

@martynasma

**Comment by martynasma** [comment]
I don't think legend scroll can be toggled like that.

Besides, this does not work good either, since legend will still be capped by chart height.

To do this, I suggest putting legend in a completely external container:

https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/
