### ISSUE TITLE
Turn on build-optimizer for Angular builds

### ISSUE THREAD

**Issue by gp187** [amcharts/amcharts4#3319]
**Question**

AmCharts requires `--build-optimizer=false` in production. That is unacceptable. 
Build size with --build-optimizer=false is 8 MB
Build size with --build-optimizer=true is 2.4MB

When will this be fixed?

**Environment (if applicable)**
Angular 11.0.4
OR
Angular 9+

**Comment by martynasma** [comment]
Unfortunately, it's not our bug to fix :(

Please refer to this discussion here: https://github.com/amcharts/amcharts4/issues/1146#issuecomment-526386236

Also possible workaround: https://github.com/amcharts/amcharts4/issues/2961#issuecomment-703291438

**Comment by gp187** [comment]
Angular 11 works perfectly with --build-optimizer=true but the maps don't show. As far as I can see, everything else works perfectly.

**Comment by martynasma** [comment]
Angular 11 might work with its own optimizer. However it is implemented in a really intrusive way, that "optimizes" not only own code, but also code of the dependencies, taking a very liberal approach to what needs to be in the dependency and what can be removed. Sometimes it works sometimes it leads into anomalies.

It's really not a bug in Angular or amCharts. It's just a really drastic optimization technique that breaks a lot of valid libraries, not just amCharts.

Angular team's approach is sort of "take it or leave it". That's why it's not enabled by default, and that's why they do not consider fixing or changing it, and just recommend on not using it at all if it does not work.

amCharts works with a lot of other optimizers like Webpack, Rollup, and Terser just fine. That's what we recommend on using for trimming down the fat of your applications.
