### ISSUE TITLE
MapArcSeries curvature and lineObject alignment

### ISSUE THREAD

**Issue by 14327319** [amcharts/amcharts4#3330]
I am using `am4maps.MapChart` and drawing a graph on geographical map with `am4maps.MapImageSeries` and `am4maps.MapArcSeries`. When I add a new line using `mapLines.create()` method of `MapArcSeries` object and zoom enough, I get an unaligned result. (AmCharts 4.9.12)

You can see my results here:

Straight line, aligned line object:

![1](https://user-images.githubusercontent.com/40094627/109281075-e624d600-782c-11eb-90b7-82ca2c8b4804.png)

MapArcSeries curved line, unaligned line object:
![2](https://user-images.githubusercontent.com/40094627/109281078-e6bd6c80-782c-11eb-995c-17d880a2c846.png)

I set my chart zoom level to 1024:

`chart.maxZoomLevel = 1024;`

I also set alignment properties but it seems the object still does not follow the curve.

```
		bullet.horizontalCenter = "middle";
		bullet.verticalCenter = "middle";
		bullet.align = "center";
```

I suspect this is a bug? Could you please check and inform me if I should set a different parameter?

Thank you.

**Comment by martynasma** [comment]
Two questions.

1) Does this happen with current version? (4.10.15)
2) Can you post your actual MapChart on CodePen/jsFiddle?

**Comment by 14327319** [comment]
> Two questions.
> 
>     1. Does this happen with current version? (4.10.15)

Yes, it happens.

>     2. Can you post your actual MapChart on CodePen/jsFiddle?

Please refer to this: [jsfiddle](https://jsfiddle.net/vyt2gmx1/2/) (You may need to zoom in several times.)

**Comment by martynasma** [comment]
Gotcha, thanks. And sorry for not catching this earlier.

MapArcSeries does not support putting objects on it. Only MapLineSeries does.

**Comment by 14327319** [comment]
Actually demo [plane example](https://www.amcharts.com/demos/animations-along-lines/) contains that kind of feature. A plane image moves along arcs and it seems it is aligned with the line moving over. I mean, conceptually that seems possible. Is there any workaround to achieve it?

**Comment by martynasma** [comment]
Well, on that demo MapArcSeries lines are in fact straight in projection sense, hence it seeming that plane follows the arc, whereas it follows the straight ground line. It just seems curved because of the map distortions due to projections.

In your setup the the actual distance is super small, so the distortion of a "straight" line is negligible, making it actually look straight by default.

However, you add the visual curvature by setting `controlPointDistance`, which is not supported by image placement algo.

Hope that makes sense.
