### ISSUE TITLE
Clarify group intervals

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3332]
Please update https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Group_intervals to explain the meaning of time intervals having multiple entries. For example, what is the meaning of milliseconds having multiple counts associated with it?

```
{ timeUnit: "millisecond", count: 1 },
{ timeUnit: "millisecond", count: 10 },
{ timeUnit: "millisecond", count: 100 },
```

Does this mean that when the current time interval is "milliseconds" then the chart will display a maximum of 100 items before grouping? When are the "1" and "10" values used?

**Comment by martynasma** [comment]
Let's say your `groupCount = 500`. If there are less than 500 milliseconds in current scope, it will display a data item for each milliseconds.

Now let's say there are 1000 milliseconds in the current scope. Since it's more than 500, the next grouping interval will kick in (`{ timeUnit: "millisecond", count: 10 }`) which means that chart will group data items in 10-millisecond aggregate data items, resulting in 100 data items.

Does that make sense?

**Comment by cowwoc** [comment]
@martynasma Yes. That makes sense. Is it possible to update the documentation with this explanation?

**Comment by martynasma** [comment]
I think it already has that:

> As you can see the intervals can be not just a single whole time unit like minute or month, but also numbered increments.

> E.g. if we have half an hour worth of data items each second (1800 data items) the grouping will kick in and will group our data items in 10-second blocks resulting in aggregate 180 data items.

**Comment by cowwoc** [comment]
@martynasma Yes, I read that paragraph. It wasn't cleared to me that:

* The intervals are only used once the data items surpass `groupCount` (I thought they allow one to specify different `groupCounts` per time interval).
* That `timeUnit: "millisecond", count: 10` means "group data items in 10 millisecond aggregates" and if that doesn't reduce the number of data items to under `groupCount` then `timeUnit: "millisecond", count: 10` means "group data items in 100 millisecond aggregates` and compare to `groupCount` and so on.
