### ISSUE TITLE
Exporting dataFields option is ignored when creating chart from json config

### ISSUE THREAD

**Issue by samuelpucat** [amcharts/amcharts4#3361]
**Bug description**

I'm creating amchart from config (am4core.createFromConfig function) and I'm trying to change names of exported columns with help of [this documentation](https://www.amcharts.com/docs/v4/concepts/exporting/#Changing_order_and_names_of_columns), but I just can't achieve expected result.

repro:
[codepen](https://codepen.io/samuelpucat/pen/abBRBxW?editors=0010)

**Environment (if applicable)**

amCharts version: 4

**Comment by martynasma** [comment]
Fixed in [4.10.17](https://github.com/amcharts/amcharts4/releases/tag/4.10.17).

## [4.10.17] - 2021-03-19

### Added
- New setting for `Export`: `webFontFilter`. Allows it to set to a regular expression. If set only those external fonts that their URL match regular exporession will be loaded.
- New setting for `ForceDirectedSeries`: `showOnTick` (default `10`). Render series hidden until Xth tick.
- New setting for `XYCursor`: `snapOnPan` (default `true`). Indicates whether to "snap" zoom selection to equal periods when panning by cursor ends.

### Fixed
- Zooming of chart with multiple vertical axes of which one was inverted was incorrect.
- `minZoomCount` was not being taken into account when zooming with mouse wheel.
- JSON config: `exporting.dataFields` setting was being ignored.
- Creating chart before its container is ready, was resulting in extra element in DOM in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
