### ISSUE TITLE
SliceGrouper broken when using queue option

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#3396]
**Bug description**

I spent hours upon hours trying to figure out why this fix was working in the fiddles: https://github.com/amcharts/amcharts4/issues/3297 but my local environment wasn't. I ended up re-creating nearly the whole local environment setup as a subset of code and ultimately found the issue.

The issue I was seeing is that the SliceGrouper plugin does not reset properly on my pie chart and the entire legend will show, completely ignoring any limit/threshold settings.

Here's two different examples that show the issue:

Complex example: https://codesandbox.io/s/pie-grouper-thing-8hzrt?file=/src/index.js:339-368
  - click the "set limit to something new" in the preview and observe that the legend doesn't change at all
  - now change the `am4core.options.queue = true;` to be `false`, manually refresh the preview, and observe that it now works

Simple example: https://codepen.io/runfaj/pen/JjEjEOM
  - click the "set value to something new" button in the preview and observe the legend just displays the full values every time
  - comment out or change the queue option to `false`, and observe the grouping now works

So there is definitely a bug with resetting when the queuing option is enabled. I unfortunately must have this `true` in our environment, so reporting a bug here.

**Environment**

amcharts 4.10.17
browser: any, mostly testing in chrome
framework: any, replicated in react, vanilla js

**Comment by martynasma** [comment]
Fixed in [4.10.18](https://github.com/amcharts/amcharts4/releases/tag/4.10.18).

## [4.10.18] - 2021-04-21

### Fixed
- `SliceGrouper` was not working when chart was a child of another `Container`.
- `SliceGrouper` was not updating properly when `am4core.options.queue = true` was set.
- `DateAxis` labels were showing zeros instead of proper milliseconds in IE.
- In some cases hidden link in `SankeyDiagram` could cause rollover tooltip to appear.
- Stroke of the slices in a `FunnelChart` was not being drawn complete.
- JSON config: value list of the `List` element was not being properly truncated to supplied lenght.
- JSON config: event list as array was not working properly.
- Using `timezone` setting in some timezones could offset Series' bullets.
- Absolute pixel `width` in `RadarColumn` was being ignored.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
