### ISSUE TITLE
Zoomed out chart does not retain shape of data

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3400]
Testcase: https://codepen.io/cowwoc/pen/ZEBNKPv

We generate data with a specific shape, as seen in this image:

![image](https://user-images.githubusercontent.com/633348/111507875-79ad4080-8721-11eb-96a6-51e33ba3bd73.png)

However, when we zoom out the chart shows a different slope that does not reflect the real slope of the data:

![image](https://user-images.githubusercontent.com/633348/111507153-b9275d00-8720-11eb-97ff-b9467ecbe890.png)

![image](https://user-images.githubusercontent.com/633348/111507598-3357e180-8721-11eb-93ae-5bc8c2ffefda.png)

![image](https://user-images.githubusercontent.com/633348/111507752-5e423580-8721-11eb-8b9a-203ae9939d3e.png)

Oddly, when I zoom in I also get a different slope:
 
![image](https://user-images.githubusercontent.com/633348/111508070-aa8d7580-8721-11eb-90eb-c544f121760b.png)

I am expecting the slope of the data to be retained when zooming out and when zooming in I expect to see a slope that represents a sub-section of a single "hill". Put another way, I expect the chart to decrease the level of detail (number of points) as I zoom out, but the overall shape of the chart should remain the same.

**Comment by MarkoB19** [comment]
Got the same problem.

**Comment by martynasma** [comment]
It would be unrealistic to expect the same shape to be carried across data grouping.

Let's look at the data.

You currently have data points every 10 minutes.

Start and end of each tooth does not coincide with start and end of the hour.

So what happens when chart starts grouping data points into hours? It grabs data points that fall exactly into that hour, not the tooth, which means that one data point gets middle of the "upslope", the other gets "peak", the other "bottom".

Since you have it configured to use average value as an aggregate value, it does exactly data: calculates value out of whatever data points there are in the specific hour range.

Exactly the same happens when grouping to bigger time periods.

There's no way around it.

I hope this makes sense.

**Comment by cowwoc** [comment]
@martynasma Yes, your explanation makes sense. There is just one more thing that doesn't line up.

Take a look at https://codepen.io/cowwoc/pen/mdRVeRR

* The value rises once per minute, from 0 to 59.
* The value is drops to zero every hour.
* The maximum value we are expecting to see is 59.
* I've simplified the grouping rules to:
```
{
	timeUnit: "minute",
	count: 1
},
{
	timeUnit: "minute",
	count: 10
},
{
	timeUnit: "hour",
	count: 1
}
```

* Navigate to the first tooth.
* Zoom into 1-point-per-minute grouping.
* As expected, in the last 10 minutes of the hour we see the values 49 to 59 followed by a drop.
* Unzoom to 10-minutes-per-point grouping.
* Why are the above values (49 through 59 inclusive) converted into a single point with value 55? Shouldn't the value be 59.4 since we have `series.groupFields.valueY = "average"`?

**Comment by cowwoc** [comment]
@martynasma Makes sense. Thank you.

**Comment by samkristoff** [comment]
On an XY chart with ***maxPanOut** > 0 you can pan beyond the first or last point in the series, but when you release left click (ie stop panning) the chart is snapped back to the time range of the series.  **snapOnPan** does not seem to change this behavior.

One potential work around is to add a null point to the start and end of the series and then programmatically zoom the x axis to desired data range on data load.  This way you can pan beyond the edge of the data and won't get snapped back when you release.
