### ISSUE TITLE
Milliseconds are displayed as 0 on DateAxis in IE11

### ISSUE THREAD

**Issue by jbate** [amcharts/amcharts4#3403]
I have a simple chart with date/time values. The DateAxis label displays the millisecond value in Chrome but in IE11 it is 0.

The `dateFormat` I am using is: 'dd-MMM-yyyy HH:mm:ss.nnn'

See screenshots and test case below:

**Chrome**
![image](https://user-images.githubusercontent.com/2857604/112450307-2ef87d80-8d4c-11eb-80dd-02531eeca0d2.png)

**IE11**
![image](https://user-images.githubusercontent.com/2857604/112450413-4a638880-8d4c-11eb-9707-3d1018ebebf3.png)

**Test case**
https://jsbin.com/muzivel/edit?js,output

**Comment by martynasma** [comment]
Fixed in [4.10.18](https://github.com/amcharts/amcharts4/releases/tag/4.10.18).

## [4.10.18] - 2021-04-21

### Fixed
- `SliceGrouper` was not working when chart was a child of another `Container`.
- `SliceGrouper` was not updating properly when `am4core.options.queue = true` was set.
- `DateAxis` labels were showing zeros instead of proper milliseconds in IE.
- In some cases hidden link in `SankeyDiagram` could cause rollover tooltip to appear.
- Stroke of the slices in a `FunnelChart` was not being drawn complete.
- JSON config: value list of the `List` element was not being properly truncated to supplied lenght.
- JSON config: event list as array was not working properly.
- Using `timezone` setting in some timezones could offset Series' bullets.
- Absolute pixel `width` in `RadarColumn` was being ignored.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
