### ISSUE TITLE
Sankey Tooltip appears for disabled groups

### ISSUE THREAD

**Issue by harshini4kav** [amcharts/amcharts4#3406]
**Bug description**

Even after disabling the nodes, tooltips for links between disabled appears on hover.

**Environment (if applicable)**

https://codepen.io/team/amcharts/details/RBVgEO

**Additional context**

![image](https://user-images.githubusercontent.com/81306175/112643181-17171b80-8e6a-11eb-9940-90cc29e2f5c5.png)

As you could see the "smartphone" node is disabled. Yet I could see tooltip for the link between "Smartphone" and "Samsung"

**Comment by martynasma** [comment]
Fixed in [4.10.18](https://github.com/amcharts/amcharts4/releases/tag/4.10.18).

## [4.10.18] - 2021-04-21

### Fixed
- `SliceGrouper` was not working when chart was a child of another `Container`.
- `SliceGrouper` was not updating properly when `am4core.options.queue = true` was set.
- `DateAxis` labels were showing zeros instead of proper milliseconds in IE.
- In some cases hidden link in `SankeyDiagram` could cause rollover tooltip to appear.
- Stroke of the slices in a `FunnelChart` was not being drawn complete.
- JSON config: value list of the `List` element was not being properly truncated to supplied lenght.
- JSON config: event list as array was not working properly.
- Using `timezone` setting in some timezones could offset Series' bullets.
- Absolute pixel `width` in `RadarColumn` was being ignored.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
