### ISSUE TITLE
SliceGrouper doesn't work with container

### ISSUE THREAD

**Issue by feliperfpereira** [amcharts/amcharts4#3410]
I've tried use sliceGrouper with in a chart inside a container and doesn'twork, looking in erro on console I saw this error:
![image](https://user-images.githubusercontent.com/39968564/112842677-3388a300-9078-11eb-82b9-fdc34920391e.png)

I reproduce the bug but in this scenario the error doesn't appear  BUT you will be able to see sliceGrouper doesn't working

link to code 
https://jsfiddle.net/8yg4a62f/

in my code I solve(just for testing) change the raw SliceGrouper code doing this:
![image](https://user-images.githubusercontent.com/39968564/112843091-9bd78480-9078-11eb-9a37-181478967935.png)

this commented line is the original and the live above then is where i select the correct chart in this container to add the data

but if you run my jsfiddle you'll see sliceGrouper doesn't working as well

**Comment by martynasma** [comment]
Fixed in [4.10.18](https://github.com/amcharts/amcharts4/releases/tag/4.10.18).

## [4.10.18] - 2021-04-21

### Fixed
- `SliceGrouper` was not working when chart was a child of another `Container`.
- `SliceGrouper` was not updating properly when `am4core.options.queue = true` was set.
- `DateAxis` labels were showing zeros instead of proper milliseconds in IE.
- In some cases hidden link in `SankeyDiagram` could cause rollover tooltip to appear.
- Stroke of the slices in a `FunnelChart` was not being drawn complete.
- JSON config: value list of the `List` element was not being properly truncated to supplied lenght.
- JSON config: event list as array was not working properly.
- Using `timezone` setting in some timezones could offset Series' bullets.
- Absolute pixel `width` in `RadarColumn` was being ignored.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
