### ISSUE TITLE
Dynamic fontSize and re-centering AxisLabel

### ISSUE THREAD

**Issue by notacouch** [amcharts/amcharts4#343]
If we dynamically set the `fontSize` of an `AxisLabel`, how do we re-center it?

See [following demo](https://codepen.io/team/amcharts/pen/5ada17273c698657ccbf06eca4919482/). 

```javascript
series.events.on("inited", () => {
  // dynamically resize "Research and Development"
  categoryAxis.renderer.labels.getIndex(1).fontSize = 30;
  // now off-center, how to re-center?
})
```

![image](https://user-images.githubusercontent.com/2334143/45394968-b0121e00-b601-11e8-87e2-47cbc10e9c9f.png)

I've tried `invalidate` and `invalidateLayout` methods on the label, the renderer, the chart, and others to no avail.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.51](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.51).

## [4.0.0-beta.51] - 2018-09-13

### Changed
- Changed `Label.renderingFrequency` to `2`, for better performance.

### Fixed
- Performance tweaking.
- `DateAxis.baseInterval` was ignored in JSON-based configs.
- `"hoverActive"` state was not always being correctly applied.
- Better handling of cursor zoom and pan when outside chart area.
- Fixed occasional error when formatting dates or numbers.
- Line chart starts new segement only if properties (like `stroke`, `fill`, `strokeDashArray`, etc.) in data have changed. It used to start new segment if properties in data were defined resulting in reduced performance and disabled smoothed lines.
- Labels were not updating their position if their `fontSize` changed.
- `Sprite.nonScalingStroke = true` was ignored if set after `Sprite.strokeWidth`.
- `LineSeries` could leave some garbage lines while zooming.
- `ColumnSeries` could leave some garbage columns while zooming.
- `DateAxis` with one date only in chart data was not rendered properly.
- The chart was not zooming out after data validation.
- Added `ghostLabel` to `Axis` which is an invisible label and it helps to avoid unwanted changes of axis widht/height when the scale changes, e.g. on zoom.
- `zoomToMapObject`, if used with `MapPolygon` and custom `zoomLevel` was not working properly.
- `"hidden"` event of Series was called on initial chart initialization.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
