### ISSUE TITLE
LineSeries with single point on DateAxis raises <path> errors + tooltip does not show

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#344]
When plotting Line Series on a Date Axis X & Value Axis Y, things go wrong when the Line Series only has a **single data item**.

1) The console displays errors like:
`core.js:1 Error: <path> attribute d: Expected number, " MNaN,185  LNaN,18…".` (possibly coming from AMElement.js)

2) The tooltip does not show when the XYCursor hovers over it.

3) The Date Axis labels look wrong. If you look at the Codepen demo, you'll see that there is only one label "spot" on the Date Axis, but there seem to be multiple date labels overlapping. The date axis label becomes unreadable.

4) The Date Axis tooltip is at a wrong position and it is displaying "Invalid Date".

Codepen: https://codepen.io/team/amcharts/pen/36bc219809f128fe865b041bfcac5692?editors=1010

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.51](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.51).

## [4.0.0-beta.51] - 2018-09-13

### Changed
- Changed `Label.renderingFrequency` to `2`, for better performance.

### Fixed
- Performance tweaking.
- `DateAxis.baseInterval` was ignored in JSON-based configs.
- `"hoverActive"` state was not always being correctly applied.
- Better handling of cursor zoom and pan when outside chart area.
- Fixed occasional error when formatting dates or numbers.
- Line chart starts new segement only if properties (like `stroke`, `fill`, `strokeDashArray`, etc.) in data have changed. It used to start new segment if properties in data were defined resulting in reduced performance and disabled smoothed lines.
- Labels were not updating their position if their `fontSize` changed.
- `Sprite.nonScalingStroke = true` was ignored if set after `Sprite.strokeWidth`.
- `LineSeries` could leave some garbage lines while zooming.
- `ColumnSeries` could leave some garbage columns while zooming.
- `DateAxis` with one date only in chart data was not rendered properly.
- The chart was not zooming out after data validation.
- Added `ghostLabel` to `Axis` which is an invisible label and it helps to avoid unwanted changes of axis widht/height when the scale changes, e.g. on zoom.
- `zoomToMapObject`, if used with `MapPolygon` and custom `zoomLevel` was not working properly.
- `"hidden"` event of Series was called on initial chart initialization.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
