### ISSUE TITLE
Straight line series doesn't show up in the XYChartScrollbar

### ISSUE THREAD

**Issue by manoj016** [amcharts/amcharts4#346]
<img width="1198" alt="screen shot 2018-09-13 at 9 29 46 am" src="https://user-images.githubusercontent.com/41284266/45466481-b7d3de80-b737-11e8-96ef-3514a71a686a.png">

The above is a single line XY chart Series which is not shown in the XYChartScrollbar.

But if the line series is in a zigzag manner, it shows up.

<img width="1035" alt="screen shot 2018-09-13 at 9 33 00 am" src="https://user-images.githubusercontent.com/41284266/45466536-0d0ff000-b738-11e8-8f8d-07688249c911.png">

**Comment by martynasma** [comment]
Thanks for the heads up! A bug.

Live example:
https://codepen.io/team/amcharts/pen/ca91163c6797479ebff3da9b5616ced2/

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.52](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.52).

## [4.0.0-beta.52] - 2018-09-21

### Added
- `CurvedColumnSeries` added. Allows having columns as curves or as triangles. Check `curved-column-chart` and `triangle-column-chart` in examples folder.
- `RadialGradientModifier` class added. Allows building more donut-like pie charts. Check `semi-circle-donut-chart` in examples.
- New chart type: `FunnelChart`, which can show regular FunnelSeries and PyramidSeries.
- New axis type: `DurationAxis`. Values on it are treated and formatted like time durations.
- `extraMin` and `extraMax` properties added to `ValueAxis`. Can be used to relatively adjust calculated minimum and maximum scale values.
- Two new read-only properties added to `Container`: `contentWidth` and `contentHeight`. Will hold width/height in pixels of the actual dimensions of elements in Container.

### Changed
- `DurationFormatter` now uses `TimeUnit` for its `baseUnit`, rather than arbitrary codes.
- `durationFormat` property was removed from `DurationFormatter`. Use [`getFormat()`](https://www.amcharts.com/docs/v4/reference/durationformatter/#getFormat_method) method to get correct format instead, then pass in to `format()`.
- Series will not show a tooltip (if one axis is `CategoryAxis`) if there is no value for this category (used to show tooltip if it had some extra text).

### Fixed
- Legend `valueLabel` values were not shown on chart initial render.
- 3D pie slices were not showing full stroke, only on the upper part of a slice.
- Sometimes `XYChart` did some additional animation even after all series finished animating, causing zoom-out flashing briefly.
- `XYChartScrollbar` was not showing series if data to the original series was added later (or changed).
- Chrome was not showing line series in `XYChartScrollbar` if all values were equal.
- Creating an empty line (without `multiGeoLine` set) was resulting in critical error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
