### ISSUE TITLE
JSON Parser not loading event array correctly

### ISSUE THREAD

**Issue by GhostKilllaX** [amcharts/amcharts4#3472]
**Bug description**
when loading events as an array via JSON the events won't work.

**Additional context**
example can be found here: https://jsfiddle.net/9432fz8x/6/

**Comment by martynasma** [comment]
Thanks for the heads up! It's a bug.

Will be fixed in the next version. I'll ping you here once it's out.

**Comment by martynasma** [comment]
Fixed in [4.10.18](https://github.com/amcharts/amcharts4/releases/tag/4.10.18).

## [4.10.18] - 2021-04-21

### Fixed
- `SliceGrouper` was not working when chart was a child of another `Container`.
- `SliceGrouper` was not updating properly when `am4core.options.queue = true` was set.
- `DateAxis` labels were showing zeros instead of proper milliseconds in IE.
- In some cases hidden link in `SankeyDiagram` could cause rollover tooltip to appear.
- Stroke of the slices in a `FunnelChart` was not being drawn complete.
- JSON config: value list of the `List` element was not being properly truncated to supplied lenght.
- JSON config: event list as array was not working properly.
- Using `timezone` setting in some timezones could offset Series' bullets.
- Absolute pixel `width` in `RadarColumn` was being ignored.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by GhostKilllaX** [comment]
thanks for the quick fix! great work :)
