### ISSUE TITLE
DateAxis last item different date interval result in no LineSeries visible

### ISSUE THREAD

**Issue by NudeFox** [amcharts/amcharts4#3475]
Not sure it's a bug or not. I believe i can miss some internal chart logic.
The test case is simple and i prepared a codepen for representation:
https://codepen.io/NudeFox/pen/JjEwGKj 

(Changing the last point to next hour fix everything but that is not possible in real project)

As you could see the primary time interval is one hour but the last item is different (in real case it is always the time this chart data was asked).
As i understand chart has really hard times if this happens cause the performance drop significantly when such case loads. Also it results in not visible line series even if the data points are present on the chart and that could be checked by hovering over the chart. 
Except that the last datapoint that is different also is not shown on the correct date (usually something rounded like 14:56 -> 14:30).
Grouping the data doesn't helps, setting `strictMinMax` also.
How can i solve that issue? Or if you think that could be counted as bug, when it could be fixed?

**Comment by martynasma** [comment]
OK, so this is happening because of the `series.connect = false`.

The logic for how auto-break works is described here:
https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Gaps_over_missing_data_points

What happens is when you have data points every hour, chart calculates data granularity as hourly, so gap displays only when there is a gap bigger than an hour.

When you add a dapaoint in minutes, chart starts to think you have data granularity in minutes, so now data points that are more than a minute apart are not connected, hence no line at all.

There are a couple of options:

1) Force hourly granularity (only if you have only one data point per hour):

```JavaScript
dateAxis.baseInterval = { timeUnit: "hour" }
```

2) Force granularity to minutes and set `autoGapCount` to more than 60 minutes:

```JavaScript
dateAxis.baseInterval = { timeUnit: "minute" }
series.autoGapCount = 60;
```

**Comment by NudeFox** [comment]
@martynasma Second solution seems to work. And thanks for explanation how the `series.connect` works. 
One more thing. Are there any chance that we could restrict zoom to a certain point with that configuration? Something like `dateAxis.minZoom = 'hour'` ?

**Comment by martynasma** [comment]
Yes, you can use [`minZoomCount`](https://www.amcharts.com/docs/v4/reference/dateaxis/#minZoomCount_property) for that.

The count is for `baseInterval`.

**Comment by NudeFox** [comment]
Find out that `minZoomCount` will restrict the totalNumber of items on chart. So if i want only hours then it's 12 hours on page at the same time and each hour is 60 minutes. So the value of zoom count should be `60*12=720`. It's not really a clear way to set that. Could it be possible to add a new feature, where we could just say the `minZoomInterval` ? 
For ex: `dateAxis.minZoomInterval = {timeUnit: 'hour'}` or smth like that?

**Comment by martynasma** [comment]
No, I'm afraid we will not consider a setting like that. I think it's not that big of a calculation to make that would warrant a fairly duplicate setting ;)
