### ISSUE TITLE
Grid decimal issue on value axis

### ISSUE THREAD

**Issue by jorenmeynen** [amcharts/amcharts4#3529]
It seems that on smaller charts, the grid lines/labels don't have the correct values

From tutorial: https://www.amcharts.com/docs/v4/tutorials/hiding-non-integer-labels-on-value-axis/
![image](https://user-images.githubusercontent.com/37269796/119241033-0b875e80-bb54-11eb-96a4-28ca393f2a48.png)

Expected:
![image](https://user-images.githubusercontent.com/37269796/119241118-78025d80-bb54-11eb-86aa-1db27aff8be7.png)

**Comment by jorenmeynen** [comment]
Also, looks like it might be similar to this:
https://github.com/amcharts/amcharts4/issues/1255

**Comment by martynasma** [comment]
Fixed in [4.10.19](https://github.com/amcharts/amcharts4/releases/tag/4.10.19).

## [4.10.19] - 2021-06-08

### Fixed
- Export: dynamic CSS `<style>` added by `Export` was not applying global `nonce` option.
- `RangeSelector` plugin: some pre-set period buttons were behaving incorrectly when there was no animated theme enabled.
- In some cases labels for `ValueAxis` were prone to a floating-point issue.
- `OverlapBuster` plugin. Was not always working properly without animated theme.
- Minor tweak to multiple series tooltip arrangements.
- JSON config: sometimes items pushed to `children` were not being created.
- Truncation of Legend's labels sometimes were being knocked off by the `XYCursor` activities.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
