### ISSUE TITLE
Comparison issue in "isInRectangle" math function 

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#3532]
The `isInRectangle` function in `Math.js` seems to have an incorrect comparison:
https://github.com/amcharts/amcharts4/blob/5fa08412c4424b178eb9c9531a047f8aa7a6c4b8/dist/es2015/.internal/core/utils/Math.js#L691

`point.x` does get correctly compared with `>=` and `<=`, however, `point.y` only gets compared with `>` and `<`. This fails if `point.y` and `rectangle.y` have the same values.

**Comment by martynasma** [comment]
Fixed in [4.10.19](https://github.com/amcharts/amcharts4/releases/tag/4.10.19).

## [4.10.19] - 2021-06-08

### Fixed
- Export: dynamic CSS `<style>` added by `Export` was not applying global `nonce` option.
- `RangeSelector` plugin: some pre-set period buttons were behaving incorrectly when there was no animated theme enabled.
- In some cases labels for `ValueAxis` were prone to a floating-point issue.
- `OverlapBuster` plugin. Was not always working properly without animated theme.
- Minor tweak to multiple series tooltip arrangements.
- JSON config: sometimes items pushed to `children` were not being created.
- Truncation of Legend's labels sometimes were being knocked off by the `XYCursor` activities.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
