### ISSUE TITLE
Bug with Pie Charts as Bullets demo

### ISSUE THREAD

**Issue by fxbit** [amcharts/amcharts4#3539]
Hi,
We are using amCharts4 from JSON Config in most of our charts without any problem up to "4.10.15"
After that version the PieChart as Bullets stop working. We can't see any exception from the library or the rendering of PieChart in SVG tree.

We have tested the pure example of :
https://www.amcharts.com/demos/pie-charts-as-bullets/#code
And is working with JavaScript example but not with JSON example.
If we revert the version from 4.10.8 to 4.10.5 is working just fine.

**Comment by martynasma** [comment]
Fixed in [4.10.19](https://github.com/amcharts/amcharts4/releases/tag/4.10.19).

## [4.10.19] - 2021-06-08

### Fixed
- Export: dynamic CSS `<style>` added by `Export` was not applying global `nonce` option.
- `RangeSelector` plugin: some pre-set period buttons were behaving incorrectly when there was no animated theme enabled.
- In some cases labels for `ValueAxis` were prone to a floating-point issue.
- `OverlapBuster` plugin. Was not always working properly without animated theme.
- Minor tweak to multiple series tooltip arrangements.
- JSON config: sometimes items pushed to `children` were not being created.
- Truncation of Legend's labels sometimes were being knocked off by the `XYCursor` activities.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
