### ISSUE TITLE
Maintain zoom position on ValueAxis after validateData

### ISSUE THREAD

**Issue by smartb-pair** [amcharts/amcharts4#354]
I notice that a DateAxis will maintain the zoom position after changing the data and calling validateData, which is great, but when trying this with a ValueAxis the chart will always zoom back out to the whole data set. Is there some way I can get the ValueAxis to also behave like this?

**Comment by martynasma** [comment]
No, I'm afraid it's currently not possible to force ValueAxis to maintain the same zoom across data updates.

We're going to investigate possibilities to implement this feature, at which point we'll inform you here.

Thanks for the suggestion!

**Comment by smartb-pair** [comment]
Thanks @martynasma, this would be a super useful feature for me.

Also I just noticed that this feature is broken in version 4.0.0-beta.51 - when zooming with a DateAxis it always jumps instantly back to the whole data set. I have locked it to version 4.0.0-beta.50 and it works there.

**Comment by martynasma** [comment]
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by kozga** [comment]
I would like to use this feature but I have not found an example of how to do it. Updating data by default results in a zoom out. I tested XYchart with valueAxis.

example: https://codepen.io/anon/pen/LqBdGZ

**Comment by kozga** [comment]
I found keepSelection option but it does not seem to work. Regardless of how it is set, the graph is always zoomed out. Is this issue fixed for sure?

**Comment by dFelinger** [comment]
> I found keepSelection option but it does not seem to work. Regardless of how it is set, the graph is always zoomed out. Is this issue fixed for sure?

You should add it to the axis instance like this:
``` javascript
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
dateAxis.keepSelection = true;
```
