### ISSUE TITLE
how to disable labels and ticks on SliceGrouper plugin

### ISSUE THREAD

**Issue by m7x333** [amcharts/amcharts4#3551]
**Question**

https://codepen.io/max333-echo/pen/JjWOrRx

1. is any way to disable labels and ticks for SliceGrouper plugin? for our case in the inner series 
2. seem like a bug SliceGrouper plugin show percentile for tooltip but not for label on inner series 

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
I'm not seeing labels or ticks in inner series on your example. Did you manage to remove them already on your own?

![image](https://user-images.githubusercontent.com/1458520/120146690-24e07880-c1ee-11eb-8eff-573fe0007fbc.png)

**Comment by m7x333** [comment]
i mean SliceGrouper plugin label and tick,  other_inner in example above, created by:
```
const innerPieSeriesGrouper = pieSeries.plugins.push(
  new am4plugins_sliceGrouper.SliceGrouper()
);
innerPieSeriesGrouper.limit = 5;
innerPieSeriesGrouper.groupName = "other_inner";
innerPieSeriesGrouper.clickBehavior = "none";
```

**Comment by martynasma** [comment]
Gotcha.

OK, so the issue is that SliceGrouper modifies data provider data in order to manipulate slices for the chart.

Since both of the series use the same data provider - chart - the first series messes up things for the second series as well.

The only way around this is to set data directly to each series:

```
pieSeries.data = [....];
pieSeries2.data = [....];
```

https://codepen.io/team/amcharts/pen/f15ed44af87658bf34ffffd7e7bb5982?editors=0010

**Comment by m7x333** [comment]
thank you
