### ISSUE TITLE
Swapping of label and value in different environment?

### ISSUE THREAD

**Issue by meghanaNanuvala** [amcharts/amcharts4#3564]
Hi 
I'm working on amcharts4 where i reproduced the pie-charts. In local environment the pie-chart is working fine as expected, but in QA where i deployed the local code in that environment the pie-chart  is not working fine where labels and values were swapped.

Pie-Chart in local environment
![Screenshot from 2021-06-03 13-49-53](https://user-images.githubusercontent.com/71019344/120612251-a47e7980-c472-11eb-902a-6f62ad1ddc71.png)
here, the label and values were as expected.

Pie-Chart in QA environment
![Screenshot from 2021-06-03 13-51-11](https://user-images.githubusercontent.com/71019344/120612399-caa41980-c472-11eb-8191-0c050edf6f45.png)
Here, swapping does.
Can you tell me that why does the behaviour changes in different environment. Any solution to resolve this behaviour change of pie-chart in different environments.

Thank you.

**Comment by xorspark** [comment]
This is likely because you have the build optimizer enabled (a similar issue was reported here: https://github.com/amcharts/amcharts4/issues/2929). You need to disable it to make the legend render correctly. If the app size is an issue, one alternative solution is to lazy load and use webpack, mentioned at https://github.com/amcharts/amcharts4/issues/1146#issuecomment-693607250 and https://github.com/amcharts/amcharts4/issues/1146#issuecomment-850324057

**Comment by meghanaNanuvala** [comment]
Thanks, now it's working fine
