### ISSUE TITLE
"Chart was not disposed" console warning logged incorrectly

### ISSUE THREAD

**Issue by bradzab0623** [amcharts/amcharts4#3570]
I am using amcharts with angular routing. I am correctly disposing of my chart in the angular 'ngOnDestroy' lifecycle hook.

However, when using angular routing but configuring it so the route component can be reused and not destroyed (implementing a custom RouteReuseStrategy), the "Chart was not disposed <id>" console warning is logged, even though my application can then route back and reuse the component that contains the chart. When routing back, the chart is correctly displayed and everything works, just the console warning is displayed. 

It is 'just' a console warning, but I can see accidentally not disposing of a chart in the future, but ignoring the warning because of this bug and not realizing it actually being a problem.

**Comment by martynasma** [comment]
In this case, you should probably just use autodispose:

https://www.amcharts.com/docs/v4/tutorials/chart-was-not-disposed/#Auto_disposing_charts

**Comment by bradzab0623** [comment]
When setting autoDispose = true, the chart is disposed of when routing away, but that's not the behavior I want. I'm having angular cache the state of my component and re-render it when routing back. I do not want the chart to be destroyed.

The problem is when routing away, the chart is no longer included in the DOM which is triggering the warning. When I route back, the chart is correctly re-displayed (but with the warning). I'm not sure if there is a good solution for the warning to not be displayed in this particular case. Maybe add a config option on a per-chart basis to not warn?

**Comment by martynasma** [comment]
Luckily, there already is such [setting](https://www.amcharts.com/docs/v4/reference/options/#suppressWarnings_property) :)

```JavaScript
am4core.options.suppressWarnings = true;
```

**Comment by bradzab0623** [comment]
is there by chance a way to suppress warnings on a per chart basis? it seems like that would only do it for the entire application.

And I still don't love this solution. Not sure if there's someone smarter than me that has a better idea

**Comment by Andy1605** [comment]
I know the issue has been closed, but is there some news within the last two years, on how to handle this?
We have the same issue here. Entirely disabling the warnings is no option for us, but the "not disposed" warnings make our software look a bit unprofessional.
I would like to disable the dispose check per chart instance individually. e.g. chart.disableDisposeCheck or anything like that. Since there are charts bound in angular components which get detached/reatached at will. e.g. Tabs, Expandable containers, ...

Thank you, and pls keep up your good work! The framework is awesome.
