### ISSUE TITLE
amCharts3 vs amCharts4 when all valueAxis values are NULLS

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#3574]
Hi,

Don't know if it is a bug or it can be simply solved, so...

amCharts4 XY chart shows nothing, when all dataProvider's values (Y axes values) are null.

Eg:

I have DATE based data, where X - Date, Y - Number (eg. electricity meters hourly data)

amCharts4 show this:
![image](https://user-images.githubusercontent.com/37294916/121195523-586b7480-c878-11eb-8b86-510d903c0d5a.png)

amCharts3 shows this:
![image](https://user-images.githubusercontent.com/37294916/121195687-7d5fe780-c878-11eb-9fda-e151d6079f6e.png)

Question:

Is it possible to fill date axis, show grid lines and etc (to get similar view to amCharts3) with new version?

**Comment by igoriok1994** [comment]
amCharts4 example: 
https://codepen.io/igoriok1994/pen/QWpByjg

**Comment by martynasma** [comment]
amCharts 4 treats data differently. DateAxis displays a scale for the scope of actual series data. In your example all data points have no value, so from the viewpoint of DateAxis there is no data, hence no scale.

To work around it, you can use axis' `min` and `max` to fix the scale, e.g.:

```
categoryAxis.min = new Date(chart.data[0]["DATE"]).getTime();
categoryAxis.max = new Date(chart.data[chart.data.length - 1]["DATE"]).getTime();
categoryAxis.baseInterval = {
  timeUnit: "hour"
};
```

Note that since there is no data, chart can't figure out what granularity of your data is, so you will have to specify it using `baseInterval`.

**Comment by igoriok1994** [comment]
Thank you for this suggestion :)
