### ISSUE TITLE
Adding icons to axis labels

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#359]
Hi,

How to add icons to axis labels

**Comment by notacouch** [comment]
Hello @Varshamathukumalli,

Would it be possible for you to provide an example that illustrates for us what you're looking to do? The more specific you are, the more clear it is to us what you're looking to achieve, the better we can help.

Thank you kindly.

**Comment by Varshamathukumalli** [comment]
@notacouch ,

In the code pen below, there are images as bullets fir each bar.
In the similar way, we wanted to add image as x-axis label instead of "Ross" or beside "Ross".
How to achieve that.

**Comment by notacouch** [comment]
@Varshamathukumalli 

Can you reply back here with the link to the codepen you were referring to?

Replacing the label with a bullet is very different from having a bullet next to the label's text.

Are you looking to do both or one of them?

**Comment by Varshamathukumalli** [comment]
Below is the url:
https://codepen.io/team/amcharts/pen/GdyEjM

no, i need the latter one of having a bullet next/previous to the text.
Instead of adding a bullet, is there any way to update the html directly, where we can add icons beside labels.

**Comment by notacouch** [comment]
Just wanted to let you know we have been working on a solution for this.

While `Label`s do have a [`html` property](https://www.amcharts.com/docs/v4/reference/label/#html_property) (which you can use instead of `text`), there are several reasons why it's not our first choice/recommendation. `Bullet`s can actually be used for what you're looking to do. We'll share the demo here once it's ready.

**Comment by notacouch** [comment]
So there isn't a way to simply modify the `AxisLabel` or add children to it to customize things whatever way we want.

What we'll do instead is use `Bullet`s to simulate `AxisLabel`s.

**There's an important caveat to this** however, the only way to accomplish this is:
your **Value Axis' minimum must be `0`** (`valueAxis.min = 0`). If that's okay, then check out the below, if it's not okay then I'm sorry to have gotten your hopes up, there is no alternative solution at this time.

Firstly we make the bullet, this serves as the template for other bullets:
```javascript
var bullet = series.bullets.push(new am4charts.Bullet());
```

To get the Bullets to appear where Axis Labels normally are, we set their `locationY` to `1` (this is why `valueAxis.min = 0` is necessary, without this, `locationY = 1` will not consistently place the Bullets to the bottom of the chart). Then we set the `dy` to shift the Bullets out of the chart, e.g. `bullet.dy = 16;`

Because a `Bullet` is a [`Container`](https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/), we can use it as a parent to lay out whatever chart Containers/Sprites we need.  We can set `bullet.layout = "horizontal";` so we can have an icon and label right next to each other horizontally. We can add a shape as a child and position that, we can also add a `Label` as a child and position it, too. Not to mention, the `label.text` can use placeholders and work like magic, e.g. `label.text = "{value}";` will work as expected!

Vertically centering the icon and label may take some tweaking so they're exactly the same across browsers (the SVG-related calculations seem to vary here very slightly). I had to fiddle with the `verticalCenter` properties of the icon and label so they looked just about the same in Chrome and Firefox.

Some other notes, we'll want to disable the actual Axis Labels, this is done via:
```javascript
categoryAxis.renderer.labels.template.disabled = "true";
```

With that, the Axis Renderer will be gone, so we want to fill up that space again for our Bullets to show up:
```javascript
chart.chartContainer.paddingBottom = 40;
```

Last but not least, the default behavior for charts is to mask or cut the Bullets out if they go passed their columns. To disable this behavior, set the following:
```javascript
chart.maskBullets = false;
```

If you've enabled the Chart Cursor, you may want to disable the X Axis' Chart Cursor tooltip so it doesn't overlay our Bullets:
```javascript
categoryAxis.cursorTooltipEnabled = false;
```

That said, here's a demo throwing all of that together:
https://codepen.io/team/amcharts/pen/bff429045682bfa08d43b02a0c8b8b1b

Screenshot:
![image](https://user-images.githubusercontent.com/2334143/46036334-44d14d00-c0d3-11e8-9b08-eda55588f38c.png)

Let us know if this is all making sense and if it works for you.

**Comment by Varshamathukumalli** [comment]
Hi,

That adds a lot to it. But the value axis min can't be 0 always, because there will be negative data also.
So that cant solve our problem.
Is there any other way, where we can simply add some html for each label directl.

**Comment by notacouch** [comment]
@Varshamathukumalli 

I'm sorry to say there's no other way at this time.

**Comment by abulyshkin** [comment]
workaround that I found
`const bullet = new am4charts.CircleBullet();
      bullet.circle.fill = am4core.color('#e0e0e0');
      bullet.circle.strokeWidth = 0;
      bullet.circle.radius = 4;
      bullet.circle.dx = 35;
      bullet.circle.dy = 20;
      valueAxis.renderer.labels.template.background = bullet;`

btw does anybody know is there a way to align that circles with 'align' props without using dx, dy?

**Comment by martynasma** [comment]
This is now possible with "axis range bullets":
https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Range_bullets
