### ISSUE TITLE
Make legendContainer use full height of the legend

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#360]
I'm using a legend in an external legendContainer. I would like the legendContainer to grow in height according to the height of the actual legends, so that items don't get cut off. 

An example can be seen here: https://codepen.io/chnoch/pen/aaRogw

It seems that setting the height of the `container` doesn't really have an effect, same with setting a numerical value on the `maxHeight`. Is there a way to enable the legend to use as much space as it needs?

**Comment by martynasma** [comment]
Technically you could dynamically measure height of all items in `legend.itemContainers` then explicitly set `style.height` of the legend div.

However, I suggest you wait until next version. It's going to introduce a property `contentHeight` / `contentWidth` which will return actual height/width of the container's contents, so you can use that to dynamically update height of the legend div on chart load.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.52](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.52).

## [4.0.0-beta.52] - 2018-09-21

### Added
- `CurvedColumnSeries` added. Allows having columns as curves or as triangles. Check `curved-column-chart` and `triangle-column-chart` in examples folder.
- `RadialGradientModifier` class added. Allows building more donut-like pie charts. Check `semi-circle-donut-chart` in examples.
- New chart type: `FunnelChart`, which can show regular FunnelSeries and PyramidSeries.
- New axis type: `DurationAxis`. Values on it are treated and formatted like time durations.
- `extraMin` and `extraMax` properties added to `ValueAxis`. Can be used to relatively adjust calculated minimum and maximum scale values.
- Two new read-only properties added to `Container`: `contentWidth` and `contentHeight`. Will hold width/height in pixels of the actual dimensions of elements in Container.

### Changed
- `DurationFormatter` now uses `TimeUnit` for its `baseUnit`, rather than arbitrary codes.
- `durationFormat` property was removed from `DurationFormatter`. Use [`getFormat()`](https://www.amcharts.com/docs/v4/reference/durationformatter/#getFormat_method) method to get correct format instead, then pass in to `format()`.
- Series will not show a tooltip (if one axis is `CategoryAxis`) if there is no value for this category (used to show tooltip if it had some extra text).

### Fixed
- Legend `valueLabel` values were not shown on chart initial render.
- 3D pie slices were not showing full stroke, only on the upper part of a slice.
- Sometimes `XYChart` did some additional animation even after all series finished animating, causing zoom-out flashing briefly.
- `XYChartScrollbar` was not showing series if data to the original series was added later (or changed).
- Chrome was not showing line series in `XYChartScrollbar` if all values were equal.
- Creating an empty line (without `multiGeoLine` set) was resulting in critical error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Chnoch** [comment]
Thanks for mentioning the new properties. `contentHeight` is pretty much what I need. Do you have an idea on which event (probably on the legend) I need to listen to, in order to have the legend fully rendered and the contentHeight of the legend properly calculated? I can't yet figure out a reliable way to consistently get the full contentHeight of the legend.

**Comment by martynasma** [comment]
Chart's `inited` event seems to be the right one.

That said, all events that set layout properties for legend items might fire after, but actual resizing happens in the next frame.

As a workaround, you might want to try wrapping your `inited` handler code into a 10ms `setTimeout()`.

That should ensure the `contentHeight` is calculated properly.

Let me know if this still does not work well for you.

**Comment by hkmoon** [comment]
@martynasma Thank you for the tip! I noticed the labels are misaligned sometimes like below.
Do you know how to deal with this? I use ```maxsizechanged``` for the legend container which is called when ```maxsizechanged``` is fired.
```javascript
      function resizeLegend() {
        const el: HTMLElement | null = document.getElementById('legenddiv');
        if (el) {
          // eslint-disable-next-line
          el.style.height = chart.legend.contentHeight + 'px';
        }
      }

      chart.legend.events.on('maxsizechanged', resizeLegend);
```

<img width="919" alt="gitlab_time_tracker" src="https://user-images.githubusercontent.com/3864647/51919571-fcf56600-23e3-11e9-852f-f8692c9634f2.png">


Could you let me know how to redraw Labels when it's necessary? Actually, I tried ```chart.invalidateLabels()```. However, it redraws one time and it updates some labels. Other labels become misaligned. Then, second call does not seem to work again.

**Comment by hkmoon** [comment]
@martynasma Thanks for the tip!

Recently, I have noticed some strange label display of pie chart legend in Windows.
In Windows,
<img width="947" alt="scicomp-pc-1" src="https://user-images.githubusercontent.com/3864647/51926337-5adc7a80-23f1-11e9-80ec-e33a8c9a217d.png">

In MacOS,
<img width="1279" alt="gitlab_time_tracker" src="https://user-images.githubusercontent.com/3864647/51926357-6af45a00-23f1-11e9-892a-07bede98b481.png">

I use ```legendContainer``` following one of your examples with resizing.
```js
      const legendContainer = am4core.create('legenddiv', am4core.Container);
      legendContainer.width = am4core.percent(100);
      legendContainer.height = am4core.percent(100);
      chart.legend.parent = legendContainer;

      function resizeLegend() {
        const el: HTMLElement | null = document.getElementById('legenddiv');
        if (el) {
          // eslint-disable-next-line
          el.style.height = chart.legend.contentHeight + 'px';
        }
      }

      chart.legend.events.on('sizechanged', resizeLegend);
```
Could you let me know how to deal with it?

Thanks a lot!

**Comment by hkmoon** [comment]
I resolved this problem with the below code.

```javascript
      function resizeLegend() {
        const el: HTMLElement | null = document.getElementById('legenddiv');
        if (el) {
          // eslint-disable-next-line
          const newHeight = chart.legend.contentHeight + 'px';
          if (el.style.height !== newHeight) {
            el.style.height = newHeight;
            setTimeout(() => {
              chart.legend.labels.template.width = am4core.percent(100);
            }, 100);
          }
        }
      }

      chart.legend.events.on('maxsizechanged', resizeLegend);
```

Any comments would be welcome!
