### ISSUE TITLE
Multiple containers with charts on the same page: only the charts for first container display cursor

### ISSUE THREAD

**Issue by artur-ott** [amcharts/amcharts4#362]
I try to display two containers of several charts in a react app. Unfortunately no cursor is displayed in the second container. 
An example: https://codepen.io/anon/pen/rZqBZe
If you place only one container, everything will be displayed correctly.

**Comment by martynasma** [comment]
Any chance of standalone demo (non-React), so that we can test?

**Comment by artur-ott** [comment]
I indeed did not test it without React. But as you can see in the example, it doesn't work without React either.
Without React: https://codepen.io/anon/pen/WgaVop
Furthermore, the code to synchronize the axes comes from an example I got from the Amcharts support.

**Comment by martynasma** [comment]
Easier example from #364:
https://codepen.io/aniov/pen/LJXygb?editors=0010

**Comment by martynasma** [comment]
Fixed in dev. Will be in the next release.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.54](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.54).

## [4.0.0-beta.54] - 2018-09-22

### Fixed
- Chart Cursor was working only for the first chart on the same page.
- `CSVParser` was not parsing `dateFields` and `numberFields` correctly.
- Issues with labels rendering in incorrect position fixed.
- `LinearGradientModifier` was not copying gradient properties to clones (since last version only).
- `FunnelSlice` sometimes rendered slice edges with no anti-aliasing.
- When calculating area of the Pyramid slices height of `sliceConnector` was not being taken into account.
- Reset `label.renderingFrequency` back to `1` to solve some unwanted label flickering.
- `MapImage` items were not showing if added via `series.data` (since last version only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
