### ISSUE TITLE
autoTextColor is not choosing the best contrast colour

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#363]
[autoTextColor](https://www.amcharts.com/docs/v4/reference/tooltip/#autoTextColor_property) may not define the best colour contrast when the background has light colours:

```javascript
var seriesTooltip = series.tooltip;
seriesTooltip.getFillFromObject = false;
seriesTooltip.getStrokeFromObject = false;
seriesTooltip.autoTextColor = true;
```

Please check the example here: https://codepen.io/team/amcharts/pen/e5600e442d8b4472f7a934070a0c5533/

**Comment by martynasma** [comment]
`autoTextColor ` is used only when `getFillFromObject = true`.

Otherwise it will be ignored, and you need to explicitly set `tooltip.label.fill` to set a color.

`autoTextColor` was designed for when the same tooltip is reused for multiple elements, often having different unpredictable colors.

If you explicitly set a color for background (or not set and leave it at default which is also predictable :) you can also set a suitable color for text.

I hope that makes sense.

I'll update documentation accordingly.
