### ISSUE TITLE
Is it possible to add multiple CSS classes via userClassName?

### ISSUE THREAD

**Issue by vigorouscoding** [amcharts/amcharts4#3634]
**Question**

I'm integrating amCharts 4 into a TailwindCSS app and would like to style the sprites using the TailwindCSS classes.
In my Pie Chart I am using `pieSeries.slices.template.propertyFields.userClassName = "myCustomClass"` to be able to specify a CSS class for each of my data slices.

What I would like to do is set (at least) **two** css classes (`fill-current` and  `text-red-500`). This would set the CSS style
`fill: currentColor; color: red` (simplified) but it is not possible as amCharts is expecting a single CSS class name as a string. For TailwindCSS (and any other such framework) it would be very nice to be able to specify an array of css classes.

Is there a way of doing this? If so, I'm sorry for the fuss I made!
Otherwise I think it would be a very nice addition.

Example CodePen: https://codepen.io/vigorouscoding/pen/rNmWeKE
Here I made it work by using exactly 1 class and adding a custom CSS rule to allow coloring the elements via CSS
```
g {
  fill: currentColor;
}
```

The CodePen example breaks when changing ` myCustomClass: 'text-red'` to ` myCustomClass: 'fill-current text-red'`.

**Environment (if applicable)**

**Additional context**

- amCharts version 4
- Any browser
- TailwindCSS

**Comment by martynasma** [comment]
It's currently not possible to add multiple classes using `userClassName`, but we'll implement it in the next version.

Will let you know here when it's out.

**Comment by martynasma** [comment]
Fixed in [4.10.21(https://github.com/amcharts/amcharts4/releases/tag/4.10.21).

## [4.10.21] - 2021-08-08

### Added
- Export: new setting in CSV options: `addBOM` (default `true`).

### Changed
- `userClassName` now supports multiple class names separated by space.
- Exporting CSV will now have add BOM code to exported file.
- Upgrading to `pdfmake 0.2.2` to work around security issues in older version.
- Upgrading to `xlsx 0.17.0` to work around security issues in older version.

### Fixed
- In some cases axis labels could be hidden across multiple data updates.
- Fixed issue with stacked/clustered negative values.
- `MapChart` now respects `home*` zoom/position with externally loaded geodata.
- Sizing/positioning of 3D charts with titles fixed.
- RangeSelector plugin: fixed zoom range resetting issues.
- Issue with inverted radial axis fixed.
- Axis with `snapToSeries` set was snapping to hidden series.
- Using timezone was causing `DateAxis` tooltips to show incorrect time in some cases.
- Issue with label text with a lot of in-line formatting not wrapping properly fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
