### ISSUE TITLE
2 Charts on same page - second chart doesn't have cursor

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#364]
With 4.0.0-beta.49 this was working ok. After changing to .51 this problem occurred.

See pen bellow:

https://codepen.io/aniov/pen/LJXygb?editors=0010

Same as [issue 362](https://github.com/amcharts/amcharts4/issues/362)

**Comment by martynasma** [comment]
OK, indeed looks like the same issue as #362

**Comment by martynasma** [comment]
Fixed in dev. Will be in the next release.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.54](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.54).

## [4.0.0-beta.54] - 2018-09-22

### Fixed
- Chart Cursor was working only for the first chart on the same page.
- `CSVParser` was not parsing `dateFields` and `numberFields` correctly.
- Issues with labels rendering in incorrect position fixed.
- `LinearGradientModifier` was not copying gradient properties to clones (since last version only).
- `FunnelSlice` sometimes rendered slice edges with no anti-aliasing.
- When calculating area of the Pyramid slices height of `sliceConnector` was not being taken into account.
- Reset `label.renderingFrequency` back to `1` to solve some unwanted label flickering.
- `MapImage` items were not showing if added via `series.data` (since last version only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
