### ISSUE TITLE
Snyk Vulnerability for xlsx

### ISSUE THREAD

**Issue by mmockelyn** [amcharts/amcharts4#3643]
Bug description
We're using @amcharts/amcharts4 and our Snyk testing shows an error for the version of xlsx that you have

See here for more details on the issue in particular: https://app.snyk.io/vuln/SNYK-JS-XLSX-1311137

The resolution is to update xlsx to a 0.17.0 version

**Comment by martynasma** [comment]
Thanks for the heads up. We're looking into it.

**Comment by SymbioticKilla** [comment]
@martynasma  Any ETA? We are blocked with releases due compliance rules.
Thank you!

**Comment by martynasma** [comment]
Not yet. Sorry.

**Comment by martynasma** [comment]
Quick update. We've successfully integrated xlsx@0.17.0 into amCharts 4, and are prepping new version as we speak.

Will post here once again when the new version is out. Most probably by the end of this week.

**Comment by martynasma** [comment]
Fixed in [4.10.21(https://github.com/amcharts/amcharts4/releases/tag/4.10.21).

## [4.10.21] - 2021-08-08

### Added
- Export: new setting in CSV options: `addBOM` (default `true`).

### Changed
- `userClassName` now supports multiple class names separated by space.
- Exporting CSV will now have add BOM code to exported file.
- Upgrading to `pdfmake 0.2.2` to work around security issues in older version.
- Upgrading to `xlsx 0.17.0` to work around security issues in older version.

### Fixed
- In some cases axis labels could be hidden across multiple data updates.
- Fixed issue with stacked/clustered negative values.
- `MapChart` now respects `home*` zoom/position with externally loaded geodata.
- Sizing/positioning of 3D charts with titles fixed.
- RangeSelector plugin: fixed zoom range resetting issues.
- Issue with inverted radial axis fixed.
- Axis with `snapToSeries` set was snapping to hidden series.
- Using timezone was causing `DateAxis` tooltips to show incorrect time in some cases.
- Issue with label text with a lot of in-line formatting not wrapping properly fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by iwantwin** [comment]
@martynasma in version 10.4.21 this is still an issue since `"xlsx": "^0.16.4"` is still referenced in the package.json. Please reopen.

**Comment by martynasma** [comment]
Sorry about that. Seems like ES2015 version of package.json was left out. We'll fix it with the next release and let you know.

**Comment by dasa** [comment]
> We'll fix it with the next release and let you know.

Any ETA on this?

**Comment by martynasma** [comment]
Fixed in [4.10.22](https://github.com/amcharts/amcharts4/releases/tag/4.10.22).

## [4.10.22] - 2021-08-20

### Changed
- `package.json` for ES2015 package was properly updated with new version dependencies.

### Fixed
- Another issue with label text with a lot of in-line formatting not wrapping properly fixed.
- ForceDirectedTree was not updating label `maxWidth` on zoom.
- Legend's `position = "absolute"` was not working.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by iwantwin** [comment]
Thanks, works perfectly!
