### ISSUE TITLE
`zoomToDates` doesn't give you the expected date range when used in conjunction with `axisBreaks`

### ISSUE THREAD

**Issue by MatthewAlner** [amcharts/amcharts4#3647]
**Bug description**

If you have an `axisBreak` and you use the `zoomToDates` function on the same axis then the chart will zoom but not to the range you asked for. The `selectionextremeschanged` event fires with the range that is displayed but this does not match the requested range. Interestingly if you set `.breakSize = 1;` this resolves the issue but obviously makes the axisBreak pointless.

Here is a minimal reproduction in code pen ➡️ https://codepen.io/MatthewAlner/pen/VwbzOZz

![broken_with_axis_break](https://user-images.githubusercontent.com/2782730/126482705-e805aeda-9e91-4c30-9be7-903db5110077.png)

![working_without_axis_break](https://user-images.githubusercontent.com/2782730/126482731-a946db67-af76-4805-81dd-1780899b0f48.png)

![working_with_breakSize_of_1](https://user-images.githubusercontent.com/2782730/126482740-ed17422e-ed94-4efc-bfdb-d6ec7993265a.png)

 
**Environment (if applicable)**

Provide details about your development environment where you think it might be useful. E.g.:

 - amCharts version: 4.10.20
 - Browser and its version: Google Chrome | 91.0.4472.164 (Official Build) (arm64)
 - Related frameworks and their versions: just "vanilla" js

**Comment by martynasma** [comment]
Fixed in [4.10.21(https://github.com/amcharts/amcharts4/releases/tag/4.10.21).

## [4.10.21] - 2021-08-08

### Added
- Export: new setting in CSV options: `addBOM` (default `true`).

### Changed
- `userClassName` now supports multiple class names separated by space.
- Exporting CSV will now have add BOM code to exported file.
- Upgrading to `pdfmake 0.2.2` to work around security issues in older version.
- Upgrading to `xlsx 0.17.0` to work around security issues in older version.

### Fixed
- In some cases axis labels could be hidden across multiple data updates.
- Fixed issue with stacked/clustered negative values.
- `MapChart` now respects `home*` zoom/position with externally loaded geodata.
- Sizing/positioning of 3D charts with titles fixed.
- RangeSelector plugin: fixed zoom range resetting issues.
- Issue with inverted radial axis fixed.
- Axis with `snapToSeries` set was snapping to hidden series.
- Using timezone was causing `DateAxis` tooltips to show incorrect time in some cases.
- Issue with label text with a lot of in-line formatting not wrapping properly fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
