### ISSUE TITLE
how to get single Start & end date time on zoom event.

### ISSUE THREAD

**Issue by chiraggirdhar** [amcharts/amcharts4#3657]
code: https://codepen.io/team/amcharts/pen/YMqOXy

multiple start and end date

**Comment by martynasma** [comment]
You seem to have already figured out how to get start and end dates after zoom, as per your CodePen.

Is the question how to avoid multiple triggers of the event?

If that is so, there's no way to enable just single firing of the event since zoom operation is animated. 

You will need to debounce the operation that is supposed to happen on zoom.

I.e. use `setTimeout()` on event trigger. If another event is triggered, previous timeout is cleared, and new timeout is created. This will ensure that only the last event will execute a function.

Hope that makes sense.

**Comment by chiraggirdhar** [comment]
I have already implemented this using setTimeout & clearTimeout.

Thank you for your help :)
