### ISSUE TITLE
Possible bug - Drawing chart series with mouse or touch do not work exporting data

### ISSUE THREAD

**Issue by ccamacho** [amcharts/amcharts4#3658]
When following the documentation and demos [[1]] it is possible to draw an extra set of data points by clicking the image.

The problem comes when you add the export menu [[2]] by adding `chart.exporting.menu = new am4core.ExportMenu();`.

In this case, you can export the image as pdf/png but you can not export the data in JSON or CSV.

In this jsfiddle [[3]] you can see the demo example with the export menu and you can see is not exporting the extra data set.

1 - https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/
2 - https://www.amcharts.com/docs/v4/concepts/exporting/
3 - https://jsfiddle.net/bs3d96kn/3/

[1]: https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/
[2]: https://www.amcharts.com/docs/v4/concepts/exporting/
[3]: https://jsfiddle.net/bs3d96kn/3/

**Comment by ccamacho** [comment]
I see there is a data adapter for the export: https://www.amcharts.com/docs/v4/reference/export/#data_adapter is there any hint you can give me to use it with https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/  ??

**Comment by martynasma** [comment]
There a tutorial/demo that makes use of "data" adapter on export:

https://www.amcharts.com/docs/v4/tutorials/combining-local-data-from-multiple-series-for-export/

You can use it as a reference point to modify exported data.

That demo is adding data directly to `newSeries.data`, so you will need to modify your "data" adapter to include that data, rather than chart's data.

Something like this:

```JavaScript
chart.exporting.adapter.add("data", function() {
  return newSeries.data;
});
```
