### ISSUE TITLE
 Problem with tensionX setting in staked LineSeries

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#366]
Example:
https://codepen.io/dmsmaxim/pen/mGQGPZ?editors=1010

The chart is not correctly drawn from point 5 to 7. Lines overlap each other:
![image](https://user-images.githubusercontent.com/15041200/45718297-35b74000-bba5-11e8-80f2-40769b11ea78.png)
But if you set `series.tensionX = 1`, everything is perfect:
![image](https://user-images.githubusercontent.com/15041200/45718436-a3636c00-bba5-11e8-86b9-31a9df893693.png)

**Comment by martynasma** [comment]
Well, it's tricky. Tension algo and line curvature depends data. The angle at which line comes in to a point depends on where it is headed next. On the angle depends how the line preceding it bends.

Since those two lines terminate sooner than the rest, their bending is affected differently, hence the visual glitch.

I'm going to chalk this up as a bug so we can look into it when we get a chance. Maybe there's a way to solve this. But I'm afraid, I can't provide any ETA on it, because it does not seems like a priority item. Too much of a niche case.

In the interim, you have two options:

1. Using tension 1 (smoothing disabled)
2. Having full data for the terminated lines, plus using AxisRange or `propertyFields` to update opacity of part of the line:

https://codepen.io/team/amcharts/pen/bb74b2a912ad68d1908dc28811ee7adf/

**Comment by zeroin** [comment]
Martynas is right, this is not fixable.

**Comment by martynasma** [comment]
Since we're not going to be fixing this, and there's a viable workaround, I'm going to go ahead and close this.

But feel free to post any follow up questions here, should you have any.
