### ISSUE TITLE
Axis cursor tooltip is not hidden when series is hidden

### ISSUE THREAD

**Issue by boerste** [amcharts/amcharts4#3665]
Hi there,

I am working with multiple axis on an XYChart and have **one** series attached to each axis. I started with the *Multiple Value Axes* demo found [here](https://www.amcharts.com/demos/multiple-value-axes/).

I added the following line of code on line 104: `chart.cursor.snapToSeries = chart.series.values;`. I created a CodePen with this change, here: https://codepen.io/jollyhour/pen/QWvryEL.

Everything works perfectly fine at first. Only the value of the series I hover my mouse over is shown, like below:
![479d8324-f503-4c3d-aa30-2ffafc019dfe](https://user-images.githubusercontent.com/50379203/127587650-30d9bca4-cbbf-4ccf-a742-ef3446925c21.png)

**However**, when I click one of the series in the legend to hide it, the cursor tooltip on its respective axis remains and follows my mouse. For example, in the image below, I clicked the "Visits" series in the legend, which then hides that series on the chart. Then, I hover over purple "Views" series. On the right, the correct value for the "Views" axis is shown, but the axis value of the hidden "Visits" series on the left is also visible.
![bb5db9b4-8ffb-4fc8-8c1f-4f7ba2cc8ae1](https://user-images.githubusercontent.com/50379203/127587954-9ca5e6f0-432c-4cf4-8d35-4af09e1452e7.png)

 Instead, I would like it so that when the series is hidden, the cursor tooltip is hidden also.

**Comment by martynasma** [comment]
Fixed in [4.10.21(https://github.com/amcharts/amcharts4/releases/tag/4.10.21).

## [4.10.21] - 2021-08-08

### Added
- Export: new setting in CSV options: `addBOM` (default `true`).

### Changed
- `userClassName` now supports multiple class names separated by space.
- Exporting CSV will now have add BOM code to exported file.
- Upgrading to `pdfmake 0.2.2` to work around security issues in older version.
- Upgrading to `xlsx 0.17.0` to work around security issues in older version.

### Fixed
- In some cases axis labels could be hidden across multiple data updates.
- Fixed issue with stacked/clustered negative values.
- `MapChart` now respects `home*` zoom/position with externally loaded geodata.
- Sizing/positioning of 3D charts with titles fixed.
- RangeSelector plugin: fixed zoom range resetting issues.
- Issue with inverted radial axis fixed.
- Axis with `snapToSeries` set was snapping to hidden series.
- Using timezone was causing `DateAxis` tooltips to show incorrect time in some cases.
- Issue with label text with a lot of in-line formatting not wrapping properly fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
