### ISSUE TITLE
Example of automatic label truncation with zoomable ForceDirectedTree?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts4#3682]
Hi again,

I'm trying to implement automatic label truncation for a zoomable ForceDirectedTree, where the label will place its ellipsis as appropriate based on the size of its containing node. I've looked at the docs as carefully as I could and played around with a number of parameters but they don't seem to do what I want them to. Any ideas please?

Thank you!

**Comment by martynasma** [comment]
There's currently no way to do that.

We'll investigate if maybe we can implement some workaround.

Will keep you posted.

**Comment by jonofoz** [comment]
@martynasma Sorry for the late reply. Thank you for the answer and for looking into possible solutions! And yes, please keep me in the loop. Cheers!

**Comment by martynasma** [comment]
Fixed in [4.10.22](https://github.com/amcharts/amcharts4/releases/tag/4.10.22).

## [4.10.22] - 2021-08-20

### Changed
- `package.json` for ES2015 package was properly updated with new version dependencies.

### Fixed
- Another issue with label text with a lot of in-line formatting not wrapping properly fixed.
- ForceDirectedTree was not updating label `maxWidth` on zoom.
- Legend's `position = "absolute"` was not working.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
