### ISSUE TITLE
Stacked columns tooltips are always centralized

### ISSUE THREAD

**Issue by darlesson** [amcharts/amcharts4#369]
When the XYCursor is not set and you hover on the difference series, the tooltip always shows on the middle of the chart.

https://codepen.io/team/amcharts/pen/KxJpKv?editors=0110

**Comment by martynasma** [comment]
There's a caveat: setting `tooltipText` directly on Series works only when you have `XYCursor` enabled.

Otherwise, you need to set `tooltipText` directly on items of the series, such as `series.columns.template.tooltipText`.

I know it's not very intuitive, and we might do something about it, but at this point it is how it is.
