### ISSUE TITLE
TimeLine

### ISSUE THREAD

**Issue by liaozhongxun** [amcharts/amcharts4#3712]
Bent Gantt chart 12 o'clock to 1 o'clock time setting is invalid

**Comment by xorspark** [comment]
Can you provide a codepen or jsfiddle that reproduces your problem? I don't see any issues in our current timeline examples.

**Comment by liaozhongxun** [comment]
Please set the start time in the example to between 12:00 and 13:00 noon. You can see that the line will be drawn from 0:00 a.m. All start times in the example are not in this time period.

**Comment by liaozhongxun** [comment]
> Can you provide a codepen or jsfiddle that reproduces your problem? I don't see any issues in our current timeline examples.

Please set the start time in the example to between 12:00 and 13:00 noon. You can see that the line will be drawn from 0:00 a.m. All start times in the example are not in this time period.

**Comment by xorspark** [comment]
That's an issue with the demo, but not the timeline addon itself. You have to change the `inputDateFormat` to use `HH` instead of `hh`; `HH` allows for 0-23 hour values, whereas `hh` only supports 1-12. We'll update the demo accordingly.

https://www.amcharts.com/docs/v4/concepts/formatters/formatting-date-time/#Format_codes
