### ISSUE TITLE
Pie remains the same size when legend.disabled is set to true

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#373]
Example:
https://codepen.io/dmsmaxim/pen/pOYPBV

1) initially `chart.legend.disabled = true;`
Pie fills the whole area -- correct. Legend is not shown - correct.
2) after 5 s `chart.legend.disabled = true;`
Pie reduced in size -- correct. Legend is shown -- correct
3) after 10 s `chart.legend.disabled = true;`
Pie remains the same size -- **not correct**. Legend is not shown - correct.

**Comment by martynasma** [comment]
Thanks for bringing this to our attention!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.83](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.83).

## [4.0.0-beta.83] - 2018-11-15

### Added
- [`hideOverflow`](https://www.amcharts.com/docs/v4/reference/svgcontainer/#hideOverflow_property) added to `SVGContainer` class. If set to `true` it will apply `overflow: hidden` to chart container so that all chart elements are contained within. Default is `false`, except on `MapChart`, which has it at `true`.

### Fixed
- Some adjustments and fixes to animations associated with `hide()`/`show()` functions.
- If a legend was initially disabled, it was not appearing when enabled later.
- `chart.addData()` was not adding data to `XYChart` scrollbar series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
