### ISSUE TITLE
Cannot set property '__disabled' of undefined

### ISSUE THREAD

**Issue by mahmoudyehia2020** [amcharts/amcharts4#3730]
During chart data render initialisation (data loading) of a XYChart, fail with this error:

Uncaught TypeError: Cannot set property '__disabled' of undefined
at queueHandler (Instance.js:264)
at Instance.js:226
at Object.dispatch (EventDispatcher.js:425)
at EventDispatcher.js:265
at Module.each (Array.js:74)
at EventDispatcher._eachListener (EventDispatcher.js:238)
at EventDispatcher.dispatchImmediately (EventDispatcher.js:263)
at Registry.dispatchImmediately (Registry.js:242)
at System.update (System.js:288)
at System.js:324

Environment

amCharts: 4.10.17
Browser: Chrome 92.0.4515.159
NextJs: 11.1.0

Additional context

This not occur on initial page load, and not always, very random but only after chart is re-initialised, to show new data set from useEffect. Difficult to reproduce always, but occur regularly.
 - amCharts version
 - Browser and its version
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.]
-->

**Additional context**

**Comment by oliverlj** [comment]
I reproduce this issue as well when activating amcore.options.queue = true; and quickly dispose and recreating chart because of a theme change kelly/dark

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
