### ISSUE TITLE
Bullets are not removed when zooming out with minBulletDistance

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#376]
I'm using `minBulletDistance` to minimize the number of bullets on screen when zoomed out in [this codepen](https://codepen.io/team/amcharts/pen/9e357057fdab91d7f3d5038faaf582f2?editors=0010), however when you zoom out, the bullets are still on screen in their original location

![floating bullets](https://user-images.githubusercontent.com/2679427/45901535-3e7c6180-bdb1-11e8-8465-839e9e150be1.gif)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.65](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.65).

## [4.0.0-beta.65] - 2018-10-28

### Changed
- `tooltip.hiddenState.transtionDuration` and `tooltip.defaultState.transitionDuration` are now set to 1 (on non-animated theme) to avoid some tooltip flickering.
- Individual legend items (label, value label, and marker) now have their  `interactionsEnabled = false` set by default to avoid double events. If you need to add events to these particular elements (as opposed to the whole legend item), you will need to set `interactionsEnabled = true` on that element.

### Fixed
- Calling `show()` on a `MapSeries` object was resulting in an error.
- 3D columns were not visible if their value was zero.
- Bullets are now hidden if `minBulletDistance` is set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
