### ISSUE TITLE
Tooltip range error when resizing map

### ISSUE THREAD

**Issue by DoheeMoon** [amcharts/amcharts4#3761]
![오류](https://user-images.githubusercontent.com/88127589/132827745-561ef44c-2258-49c1-9804-b55f7cbca2e5.gif)

The size of the demo chart on the website was resized.
After that, a tooltip position error occurred.

The same error occurs in my code.
Is there a way to fix it?

**Comment by martynasma** [comment]
I'm afraid I'm having issues reproducing this. Can you describe the steps in order to reproduce this?

I'm assuming you are using this demo:
https://www.amcharts.com/demos/map-dynamic-pie-charts/

**Comment by DoheeMoon** [comment]
At first, adjust the demo screen small and refresh it.
Then, drag according to the screen size.
Then it becomes like that.

**Comment by martynasma** [comment]
Thank you. I was able to reproduce this.

Will let you know when the fix is available.

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
