### ISSUE TITLE
does amcharts needs to run the function that builds the chart outside of ngZone when using Angular?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3762]
env:
 - amCharts 4.10.3
 - Chrome
 - Angular8

Following the docs for angular integration is showed the code below:
```
browserOnly(f: () => void) {
    if (isPlatformBrowser(this.platformId)) {
      this.zone.runOutsideAngular(() => {
        f();
      });
    }
  }
```

So the function that buillds the chart will be running outside ngZone, this function has a Angular EventEmitter witch is emitted at the end of the function. This emitter should trigger a change detection but I figured out that it doesnt  happens because of`this.zone.runOutsideAngular`

I removed `this.zone.runOutsideAngular` and everything looks fine. is it necessary for amcharts?

**Comment by Pauan** [comment]
Yes, all amCharts code (including update code) must run outside of Angular's zone.

This is necessary because Angular hijacks a lot of things (such as timers), which will then cause ***massive*** performance issues with amCharts.

If you want to do Angular stuff inside of the amCharts code, you can use [`this.zone.run`](https://angular.io/api/core/NgZone#run) to run your code *inside* of Angular's zone:

```ts
this.browserOnly(() => {
    // amCharts code here...

    this.zone.run(() => {
        // Angular code here...
    });
});
```

It's very important for performance reasons that you keep your amCharts and Angular code separate (using `this.zone.runOutsideAngular` and `this.zone.run` as appropriate).
