### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'touch')

### ISSUE THREAD

**Issue by flortsch** [amcharts/amcharts4#3775]
**Bug description**

On mobile, after programatically zooming on a map chart to a country and enabling its hover effect, tapping somewhere different on the map produces an uncaught type error.

```
Interaction.js:661 Uncaught TypeError: Cannot read properties of undefined (reading 'touch')
    at Interaction.handleOut (Interaction.js:661)
    at eval (Interaction.js:835)
    at eval (Iterator.js:65)
    at eval (List.js:66)
    at Object.each (Iterator.js:64)
    at Interaction.cancelAllHovers (Interaction.js:832)
    at Interaction.processDragStart (Interaction.js:1114)
    at Interaction.handleDown (Interaction.js:731)
    at Interaction.handlePointerDown (Interaction.js:533)
    at SVGGElement.eval (Interaction.js:308)
Interaction.handleOut @ Interaction.js:661
eval @ Interaction.js:835
eval @ Iterator.js:65
eval @ List.js:66
each @ Iterator.js:64
Interaction.cancelAllHovers @ Interaction.js:832
Interaction.processDragStart @ Interaction.js:1114
Interaction.handleDown @ Interaction.js:731
Interaction.handlePointerDown @ Interaction.js:533
eval @ Interaction.js:308
```

Reproducer: https://codesandbox.io/s/nostalgic-chatterjee-lmdi7

**Environment**
Touch devices.
amCharts version: 4.10.22

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
