### ISSUE TITLE
legend.contentHeight is not properly calculated for multi-line legend items

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#382]
I'm using a legend that has multiple lines per item and would like to dynamically set the height of the legend container based on the new property `contentHeight` of the legend, in order to not waste space or clip content or having to scroll.
However as can be seen in the following Codepen the `contentHeight` of the legend is not properly calculated when initializing the chart. When resizing the window triggers the `resize` event, amcharts will at some point correctly calculate the actual height of the legend content.

Codepen: https://codepen.io/chnoch/pen/eLamKp

**Comment by zeroin** [comment]
Our solution would be to set initial height of legend div to some bigger than expected size, like 300px. Then the legend will be drawn properly and contentHeight properly calculated. With div size 0 `contentHeight` might be incorrectly calculated because div size affects `maxHeight` and this also affects `contentHeight`.
