### ISSUE TITLE
Global trigger on div:hover for Export Menu

### ISSUE THREAD

**Issue by Jergron** [amcharts/amcharts4#3820]
**Bug description**
The Export Menu changes opacity on any div element that my mouse pointer hovers over. 

Wrapping a parent ` <div>`  element around the targeted chart id will trigger the issue. 

Demo: https://codepen.io/Jergron/pen/dyzbKmE

**Environment (if applicable)**
Development env.
amCharts version: 4.10.10
Browser and its version: Chrome version 94.0.4606.71
Related frameworks and their versions: VueJS version 2.6.11

**Additional context**
Our team found that the issue on [line 70 in the ExportCSS.ts file](https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/export/ExportCSS.ts#L70)

There is a space between 'div:hover' and the preFix class name. Once we removed the space, then the export menu worked as expected and only changed its opacity within the chart container.
![image](https://user-images.githubusercontent.com/10701505/136608753-e4a0be0e-ccc2-470b-8002-0f02a29b54a7.png)

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
