### ISSUE TITLE
'over' and 'out' events are toggled too often on legend item

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#383]
I have a multi-line legend item with event listeners on the `over` and `out` events. When I hover over the first line and then move the mouse to hover over the second line an `out` event is triggered followed by a `over` event, since we're still hovering over the same item. My expected behavior would be that as long as we are moving over the same legend items the `out` event is not triggered.

You can reproduce the behavior in the following Codepen:
https://codepen.io/chnoch/pen/dqEGVR?editors=0010

However over any legend item and move the mouse between the first and second line of that item. In the console the events are then logged, and a flickering of the tooltip is also visible.

**Comment by martynasma** [comment]
I have a very simple solution for you: just disable all interactivity for legend's labels:

```
chart.legend.labels.template.interactionsEnabled = false;
```

Since labels will be inactive, it won't trigger over event over the label, and thus no out ovent from the item container.

We will also consider whether we may need to do that by default.

In the interim, the above solution will do the trick.

**Comment by Chnoch** [comment]
Thanks for your solution, this works well for my use case.

I'll leave the ticket open in case you want to do further enhancements based on this.

**Comment by martynasma** [comment]
Yes, thanks. We'll use this issue to get back to this.

**Comment by martynasma** [comment]
Starting with next version, the `inetractionsEnabled` of individual legend item elements (labels, markers) will be set to `false` so that they do not generate any events. Only the main item container will have events attached.

This means that if you want to add any interaction event to particular element of the legend item, you will need to explicitly enable `interactionsEnabled = true` on it.
