### ISSUE TITLE
Scrollbar tooltip not updated with chart data

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3830]
**Bug description**

Line-Chart with date axis and Scrollbar. The chart is periodically updated.
The dateAxis keeps the selection:
dateAxis.keepSelection = true; 

Zooming the chart and hovering over the selection in the scrollbar shows a system tooltip (everything OK so far).
![image](https://user-images.githubusercontent.com/58069494/137316865-9b6b1b2c-f843-446e-a62d-1e226d840b12.png)

Waiting a few minutes while the chart is updated a few times.
The zoomed selection stays the same (OK).
The chart is updated - the scollbar chart is updated as well (OK).

Now hovering again over the scrollbar displays the **old** tooltip - no longer matching to the real selection.
![image](https://user-images.githubusercontent.com/58069494/137316930-511c5dda-95ba-4cc1-b52b-26ec77126382.png)

The title element in the svg is not updated.
![image](https://user-images.githubusercontent.com/58069494/137316752-d7d6f03b-46b0-41d1-a18e-4a0c00e4f6c8.png)

**Environment (if applicable)**

 - amCharts version: 4.10.21
 - Browser and its version: all Browsers

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
