### ISSUE TITLE
Failure adding a tooltip adapter to display multiple series values in one tooltip

### ISSUE THREAD

**Issue by Acke57** [amcharts/amcharts4#3841]
**Bug description**
When trying to add several series were each JSON element have similar properties such as {x: new Date("2021-09-01"),y:6848}.
x and y are present several times and in several different data series.

I am trying to use the description on how to create an adapter but it only shows the y values from the first series, however the stroke and name of the series are displayed correctly.

See jsfiddle that display the problem: https://jsfiddle.net/o5therwp/

**Comment by xorspark** [comment]
The combined tooltip code assumes chart-level data since it uses named fields. You need to apply different logic when you have series-level data such that it pulls directly from the series' data array instead of using a named-field lookup. You'll also need to add additional logic to handle the lone series that uses chart-level data as well:

```
  series.adapter.add("tooltipText", function (text, target) {
    var text = "[bold]{dateX}[/]\n";
    var dataItemIndex = target.tooltipDataItem.index;
    chart.series.each(function (item) {
      if (!item.isHidden) {
        text +=
          "[" +
          item.stroke.hex +
          "]●[/] " +
          item.name +
          ": " +
          // check if there is series-level data before pulling from its array
          // or the chart data array
          (item.data.length ? item.data[dataItemIndex][item.dataFields.valueY] : chart.data[dataItemIndex][item.dataFields.valueY]) + 
          "\n";
      }
    });
    return text;
  });
```

[Updated fiddle](https://jsfiddle.net/5xw2da8y/)
