### ISSUE TITLE
Is there an option to show the tool-tip when loading a chart with existing annotations?

### ISSUE THREAD

**Issue by Javier1zq** [amcharts/amcharts4#3859]
**Description**

I encountered this issue while using the chart annotations in our solution, but i also realized it is present in the demo for [Annotating Charts](https://www.amcharts.com/demos/annotating-charts/)

When you first load the chart (Or activate annotations in the case of our implementation) if there are pre-existing annotations present and you hover over the chart you cannot see the tool-tip, but if you start annotating and then stop annotating you can see the tool-tip through the annotations.

**Expected behavior**

The expected behavior is for the tool-tip to be visible when you first load a chart with existing annotations. Currently this only happens if you start and stop annotating in a chart with existing annotations.

**Question**

Is there an option to enable this behavior?

**Environment**

It is present in the demo:
https://www.amcharts.com/demos/annotating-charts/

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
