### ISSUE TITLE
Legend Scrollbar behavior in Firefox

### ISSUE THREAD

**Issue by lmogwitz** [amcharts/amcharts4#3862]
**Bug description**

For the codepen-example shown in https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Scrollable_legend_via_settings scrolling via mousewheel in Firefox (93.0) scrolls all the way to the bottom. This breaks very long legends spanning multiple heights of the container.

This only occurs in Firefox (93.0). In Chrome and Edge it works fine.

**Environment**
 - amCharts version: 4.10.22
 - Firefox 93.0
 - Angular(10.1.1) aswell as the codepen example in the issue's description

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
