### ISSUE TITLE
venn.js relies on ansi-regex with a moderate CVE (not web exploitable)

### ISSUE THREAD

**Issue by devanubis** [amcharts/amcharts4#3867]
**Bug description**

`venn.js@^0.2.20` depends on a series of outdated or unmaintained packages, culminating in a dependency on `ansi-regex@^2.0.0`.

https://github.com/chalk/ansi-regex has had a CVE for versions between 2.1.1 and 5.0.0, and 2.1.1 is the latest 2.x release and they don't appear to intend to patch previous major versions for this.

https://github.com/advisories/GHSA-93q8-gq69-wqmw

I realise there probably isn't much amcharts can do about this, other than ask `ansi-regex` nicely to patch their 2.x branch, or fork `venn.js` yourselves and update its dependencies...

But I thought it was at least worth letting you know about this.

It it doesn't appear to be web-exploitable, it's rooted in the `chalk` CLI utility, which is used by the version of `rollup`.

Oh, and `yarn audit` / `npm audit` doesn't detect this in our repo using amcharts4, but a checkout of your repo's `main` branch does flag this up (and some other problems too...)

 - amCharts version: `4.10.22`

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
