### ISSUE TITLE
How to import the types when lazy loading AmCharts

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts4#3870]
**Question**

I am lazy loading the library in an Angular app using the following code:

```ts
    Promise.all([
      import('@amcharts/amcharts4/core'),
      import('@amcharts/amcharts4/charts'),
      import('@amcharts/amcharts4/themes/animated'),
      import('@amcharts/amcharts4/themes/material')
      // tslint:disable-next-line:variable-name no-shadowed-variable
    ]).then(([am4core, am4charts, am4themes_animated, am4themes_material]: any) => {

      // Set up chart themes
      am4core.useTheme(am4themes_material.default);
      am4core.useTheme(am4themes_animated.default);

      // Emit the libraries as ready to use
      this.ready.next({ am4core, am4charts });
    }).catch((e: Error) => {
      console.error('Error when creating chart', e);
    });
```

So now we don't use any import like 

```ts
import * as AmCharts from 'ts@amcharts/amcharts4/charts';
```

However, we are still required to import the types, I am using 

```ts
import type * as Am4Charts from '@amcharts/amcharts4/charts';
```

The problem that the whole package is still being compiled and causing slowdown in app builds (serious slow down x20 times at the least)

How can I import the types without causing the chart library to be included in my app scripts?

**Environment (if applicable)**

 - amCharts 4
 - Angular 12

![Screenshot 2021-11-03 at 14 06 30](https://user-images.githubusercontent.com/8130692/140065630-e20e3342-5e2d-4589-9000-e11afa2f2c6e.png)

**Comment by Pauan** [comment]
You can try doing something like this:

```ts
    type Am5 = typeof import('@amcharts/amcharts4/core');
    type Am5Charts = typeof import('@amcharts/amcharts4/charts');
    type Am5ThemesAnimated = typeof import('@amcharts/amcharts4/themes/animated');
    type Am5ThemesMaterial = typeof import('@amcharts/amcharts4/themes/material');

    Promise.all([
      import('@amcharts/amcharts4/core'),
      import('@amcharts/amcharts4/charts'),
      import('@amcharts/amcharts4/themes/animated'),
      import('@amcharts/amcharts4/themes/material')
      // tslint:disable-next-line:variable-name no-shadowed-variable
    ]).then(([am4core, am4charts, am4themes_animated, am4themes_material]: [Am5, Am5Charts, Am5ThemesAnimated, Am5ThemesMaterial]) => {

      // Set up chart themes
      am4core.useTheme(am4themes_material.default);
      am4core.useTheme(am4themes_animated.default);

      // Emit the libraries as ready to use
      this.ready.next({ am4core, am4charts });
    }).catch((e: Error) => {
      console.error('Error when creating chart', e);
    });
```

Though I suspect it will still have slow build times, because it has to load all the types. That's unavoidable, since it's just how TypeScript works.

You can try using `--build` and `incremental` and `composite` and `assumeChangesOnlyAffectDirectDependencies`, they might improve your build times:

https://www.typescriptlang.org/docs/handbook/project-references.html

https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#incremental-file-watching-for-composite-projects-in---build---watch

https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#faster-subsequent-builds-with-the---incremental-flag

https://www.typescriptlang.org/tsconfig#composite

https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#fast-and-loose-incremental-checking

**Comment by MurhafSousli** [comment]
Thanks a lot, I will try!
