### ISSUE TITLE
Amchart default zooming is not working after setting queue/onlyShowOnViewport

### ISSUE THREAD

**Issue by rickxu0423** [amcharts/amcharts4#3875]
**Bug description**
If multiple charts need to be rendered and implement below settings to improve performance:
1. am4core.options.queue = true;
2. am4core.options.onlyShowOnViewport = true;

Then the default zooming functionality is breaking for:
1. All charts except the first one
2. All charts that are not on viewport

**Codepen/jsFiddle/Codesandbox (required)**
1. https://codepen.io/Rickxu0423/pen/ZEJoPpr
2. https://codepen.io/Rickxu0423/pen/WNEJWWm

**To Reproduce**
1. Go to the Codepen links above
2. Let the charts complete loading
3. Click on legend 'Series1' of the first chart, default zooming is working
3. Scroll down to the bottom and click on legend 'Series1' of the **LAST** chart (two charts total in the first link and three charts total in the second link), default zooming is breaking

**Expected behavior**
Default zooming functionality should still work after setting queue/onlyShowOnViewport

**Environment (if applicable)**
amChart version: 4.10.22
Browser: Chrome 95.0.4638.69

**Comment by martynasma** [comment]
Fixed in [4.10.23](https://github.com/amcharts/amcharts4/releases/tag/4.10.23).

## [4.10.23] - 2021-11-25

### Added
- New `NumberFormatter` setting: `forceLTR`. If set to `true` will force all numbers to be formatted as LTR, even if RTL is enabled.

### Changed
- Using minified version of `xlsx` library for XLSX exports.

### Fixed
- If chart queuing was enabled and chart was disposed quickly before it had a chance to initialize, it was resulting in a critical error.
- In some cases (after programmatic hover) tapping on a touch device could produce an error in `MapChart`.
- JSON config: in some cases items in `children` were not being created.
- Mouse wheel zooming was not working properly in recent versions of Firefox.
- Fixing security vulnerability ([`CVE-2021-3807`](https://nvd.nist.gov/vuln/detail/CVE-2021-3807)) with `venn.js` dependency.
- Tweaking hover styles for `ExportMenu` CSS so they do not get invoked unless hovered on chart's container.
- Reader labels were not being updated on Scrollbar elements when data in chart was updated.
- `Annotation` plugin will now not go into edit mode after `data` is set.
- In some cases wrapped and center-aligned axis labels could get a bit offset.
- In some cases toggling series on and off was not updating related value axis scale on lazy-loaded charts.

[Download options](https://www.amcharts.com/download-v4/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
