### ISSUE TITLE
move watermark

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#390]
Hello,

it's possible to move watermark INSIDE the chart (top left eventually, but better if configurable) to "reclaim" the space that the logo use but leaving it there for proper copyright informations?

**Comment by martynasma** [comment]
Well, normally the logo does not claim the space. So even if it is disabled, the chart will and its elements will be the same. You'll still need to modify chart properties, like `paddingBottom`, to control margins.

That said, I can totally understand that in some cases it would make sense to move the logo to some place else.

We'll think of some ways to make that doable.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.55](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.55).

## [4.0.0-beta.55] - 2018-09-26

### Added
- New series type suitable for `SlicedChart`: `PictorialStackedSeries`. (check `pictorial-stacked-chart` and `pictorial-stacked-chart-horizontal` demos)
- New themes: "dataviz", "moorisekingdom", "frozen", "spiritedaway".
- New Chart property: `logo`. If you are using amCharts with a free license, it holds reference to amCharts logo. Use it to position logo with `align` and `valign` properties.
- New `FunnelTick` properties: `locationX` and `locationY`. Allow specifying a relative location within target element where tick is pointing to.

### Changed
- `FunnelChart` was renamed to `SlicedChart`. The previous name did not correctly represent capabilities of the chart type that can display not only funnel series, but also pyramids and stacked pictorial series. `FunnelSeries` remains as it was before.

### Fixed
- Mouse wheel zoom was extremely slow in FireFox.
- Sometimes colors duplicate colors were generated by `ColorSet`.
- HTML-based labels were not accounting for "pixel ratio" on Retina displays, making tooltips larger then they are supposed to be.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
You can now move the logo to any other corner. For example to move to upper-right:

```
chart.logo.align = "right";
chart.logo.valign = "top";
```

**Comment by jimmykane** [comment]
@martynasma  can we add this to the docs ?
