### ISSUE TITLE
Pie chart slice tooltips stay forever

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#3911]
**Bug description**

Pie Chart with html slice tooltips adapter and periodically updated data.
If data is updated while the tooltip is shown the old tooltip stays and a new one is created.

![image](https://user-images.githubusercontent.com/58069494/143591070-b8e5c6f1-cc33-4217-a1aa-ea015c193a66.png)

Pen: https://codepen.io/chrisadler/pen/eYEwawd?editors=0010

**Environment (if applicable)**

 - amCharts version: 4.10.23 (and earlier)
 - Browser and its version: all Browsers

**Comment by zeroin** [comment]
Is there a reason you want to create a separate tooltip for each slice?

if you need and adapter for tooltipHTML you can simply add it, instead of creating a separate tooltip:
https://codepen.io/team/amcharts/pen/1a954dc3dd2c19bcb6d405a7dda063ea?editors=0010

If for some reason you need them, then before setting new data you should loop through all the slices and dispose the tooltip of each of them.

**Comment by lticadler** [comment]
Thank you very much - I found the reason. I misunderstood something.

The reason for that was to change the tooltip layout. And I thought it has to be changed on the slice's template.
```
let sliceTooltip = sliceTemplate.tooltip;
   if (!sliceTooltip) {
      sliceTooltip = new am4core.Tooltip();
      sliceTemplate.tooltip = sliceTooltip;
    }
sliceTooltip.background.strokeWidth = 0; // set tootltip layout
sliceTooltip.background.cornerRadius = 0;

sliceTemplate.adapter.add('tooltipHTML', ...
```

In this tutorial is the solution:
https://www.amcharts.com/docs/v4/tutorials/overriding-series-tooltip-fill-color/
the series already has the tooltip which is used for all slices.
Updated the pen - and it works as expected.
