### ISSUE TITLE
TooltipHTML background appearing double the size

### ISSUE THREAD

**Issue by pouretrebelle** [amcharts/amcharts4#394]
![image](https://user-images.githubusercontent.com/1901935/46020209-c3c78500-c0d5-11e8-9341-74e079c6e630.png)

No matter the content the background for HTML tooltips is appearing double its size. I'm on a 2x screen so thinking it's just that width/height needs to be divided by the pixel density at some dimension calculation...

**Comment by martynasma** [comment]
Thanks for the heads up. Confirmed bug.

Here's a very simple example, for our own use:
https://codepen.io/team/amcharts/pen/d3c611624e66da746bc81d97e16dfa8e

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.55](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.55).

## [4.0.0-beta.55] - 2018-09-26

### Added
- New series type suitable for `SlicedChart`: `PictorialStackedSeries`. (check `pictorial-stacked-chart` and `pictorial-stacked-chart-horizontal` demos)
- New themes: "dataviz", "moorisekingdom", "frozen", "spiritedaway".
- New Chart property: `logo`. If you are using amCharts with a free license, it holds reference to amCharts logo. Use it to position logo with `align` and `valign` properties.
- New `FunnelTick` properties: `locationX` and `locationY`. Allow specifying a relative location within target element where tick is pointing to.

### Changed
- `FunnelChart` was renamed to `SlicedChart`. The previous name did not correctly represent capabilities of the chart type that can display not only funnel series, but also pyramids and stacked pictorial series. `FunnelSeries` remains as it was before.

### Fixed
- Mouse wheel zoom was extremely slow in FireFox.
- Sometimes colors duplicate colors were generated by `ColorSet`.
- HTML-based labels were not accounting for "pixel ratio" on Retina displays, making tooltips larger then they are supposed to be.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
