### ISSUE TITLE
Range tooltip position

### ISSUE THREAD

**Issue by DimaGavrushko** [amcharts/amcharts4#3948]
"@amcharts/amcharts4": "^4.10.23",

In the chart I have ranges with tooltip. Sometimes tooltip renders not in the right place. It usually happens after updating the data.

https://user-images.githubusercontent.com/22750804/147755264-cd521951-8282-450b-ad21-43ec6af47430.mov

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by DimaGavrushko** [comment]
@martynasma It is very difficult to write exactly the same but I think I can reproduce the general idea.

https://codepen.io/dimagavrushko/pen/RwLomWR

https://user-images.githubusercontent.com/22750804/147975730-ffa93c7b-f813-444b-a5a0-8fa4be92e52a.mov

**Comment by DimaGavrushko** [comment]
@martynasma any updates there?

**Comment by martynasma** [comment]
Could you try setting `isHover = false` on all ranges before removing them and replacing with other ranges?

**Comment by DimaGavrushko** [comment]
@martynasma I updated the code in the same codepen and still can reproduce the issue

**Comment by martynasma** [comment]
Unfortunately, I don't have any more suggestions.

If you have a commercial license or paid support subscription, please contact us directly at contact@amcharts.com to see if we maybe can work something out.

Other than that, the issue is too niche and amCharts 4 is nearing EOL, so can't dedicate too much time to it, I'm afraid.

**Comment by DimaGavrushko** [comment]
@martynasma , got you, thanks
