### ISSUE TITLE
How to have static range in the category axis.

### ISSUE THREAD

**Issue by srvsourabh** [amcharts/amcharts4#3949]
Hi All, 

I need to have a category axis which shows just four labels as shown below.
<img width="399" alt="Screenshot 2022-01-04 at 9 07 17 AM" src="https://user-images.githubusercontent.com/44115389/148006420-9a8ee96d-fe0e-4ff2-aa5c-726f04425ef8.png">

I  have achieved this using below code.

```
const categoryAxis = lineChart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = 'week';

var series = lineChart.series.push(new am4charts.LineSeries());
series.dataFields.valueY = 'total_user';
series.dataFields.categoryX = ‘week’;

categoryAxis.renderer.minGridDistance = 150; 
categoryAxis.startLocation = 0;
categoryAxis.endLocation = 1.5;
```

the minGridDistance which is set to 150 helps me to achieve this issue but the problem is that it is responsive and changes to two labels on xAxis as the screen size changes.

<img width="397" alt="Screenshot 2022-01-04 at 9 18 52 AM" src="https://user-images.githubusercontent.com/44115389/148007146-d1526342-4797-4f76-ba78-d8f545d634b6.png">

Can someone please help me which suggestion so that we can have a category axis which shows just four labels.

**Comment by xorspark** [comment]
In order to have a static grid, you need to use [axis ranges](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges) to draw your grid and labels instead of using the auto-generated ones. We have an example for value axes here: https://www.amcharts.com/docs/v4/tutorials/custom-valueaxis-grid-using-ranges/. The same concepts can be applied to a category axis, but  note the caveat in [this section](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Guide_labels_on_category_axis) on setting labels.
