### ISSUE TITLE
tick function for tooltip

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#397]
I haven't understand how to display the tooltip on a serie for every value that i had on that dataset.

doing 

        series.tooltipText = "{valueY}";

will display the tooltip, but not for every value on the dataset, it just display "some" of them, based on something that i don't get

**Comment by martynasma** [comment]
Not sure what you mean. Say you have a ColumnSeries with 50 columns. Do you want to display 50 tooltips on every column?

**Comment by ramarro123** [comment]
XYChart, x = DateAxis various ValueAxis.

i expect that tooltip on ValueAxis line are one for every point in x, but i can move on x without seeing the tooltip, so i presume that the tooltip only happen every certain "tick" or something like that.

**Comment by martynasma** [comment]
Can you post your chart code and data?

I must be slow today, I can't for the life of me, understand what you're saying :)

**Comment by ramarro123** [comment]
sure, it's my english that's a bit rusty 🗡 

https://codepen.io/anon/pen/PyYRbg?editors=0010

if i set the loop with 10, i can see all the tooltip.
if i set 200 some of them are missing in action, i see 128, and 130 but not 129
if i set 1000, no tooltip are displayed

**Comment by martynasma** [comment]
Thanks, it's super clear now :)

Let me describe the issue.

When you don't hover exactly on a data point, the cursor is looking for a closest data item to show tooltip for.

The thing is, to not waste resources, it does not look through all of the data. It just looks for some of the closer ones.

Since your test data is a bit odd: it starts with milliseconds, then increases in geometrical progression, so the more items you have the bigger distance between them.

Hence cursor able to find closest data items at the beginning of the graph, where density is bigger, and not being able to do so at the end where distances are huge compared to granularity of data.

Is this your realistic data? My guess is that it's not. This issue should not be visible with real data.

**Comment by ramarro123** [comment]
of course it's realistic :)
maybe not in the sample that i give, but i use amchart to draw a nice chart of a powerhead (an aquarium pump) that simulate wave connected to arduino.

i need to see it in 24/12/6 hrs breakdown (to see moon and 'maree' -not sure how to translate it-) changes.

so, 6hrs of data, for a pump that do "things" every 2-3 secs, generate a lot of points, and all of them are near :)

even zooming out doesn't help.

also, since i used amchart3, i didn't have this issue with the same amt of data

**Comment by martynasma** [comment]
What I'm saying is that your sample data is not realistic. It does not come in every 2-3 seconds, the gap between every data point increases exponentially.

Because every distance is ^3 of `i`.

So the first data point is at time 0. The second 1 millisecond later. The third is 2x2x2=8ms later, fourth 3x3x3=27ms, fifith 4x4x4=64ms, 125ms, 216ms, 343ms, ....

By the time you reach 100th data point you have a million milliseconds which is like 17 hours.

So if you had data item every 2-3 seconds, by the 100th data point you'd be at 200-300 seconds, not 17 hours.

Does that make sense?

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
