### ISSUE TITLE
addData with partial data

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#405]
https://codepen.io/anon/pen/RebMYO?editors=0010

if addData contains an (ordered) array BUT the array overlap the starting array, chart isn't displayed as expected.

i have to use data ={} and all the chart get repainted, that's inefficient with > 20000 data i get a lot of lag just to add 2-3 elements. any solution?

server send incremental data batch, without any specific order, addData it's not able to insert them in order into the dataset

**Comment by ptorrent** [comment]
Hello, I don't know if this will help you but for me I set data directyl to serie.

serie.addData 

With this, I'm sure that data is ordered correctly

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.70](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.70).

## [4.0.0-beta.70] - 2018-10-31

### Fixed
- Keyboard dragging of elements such as scrollbar grips was not working.
- "hoverable" elements were not staying "hovered" after tap in Mobile Safari.
- `addData()` with more than one data item added was not working well.
- Zoomout button was visible on initial animation.
- Dynamically changing `Legend.position` was not updating its layout properly.
- Vertical axis tick position with rotated labels was incorrect.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
