### ISSUE TITLE
How to Squish Category Axis labels instead of hiding them on zoom-in and zoom-out

### ISSUE THREAD

**Issue by azharakbar** [amcharts/amcharts4#4062]
**Question**
I have a category axis in the chart whose visibility can be controlled using a scrollbar
But, the problem I am facing is, the labels on the category axis are getting hidden when we zoom out

This is not the desired behaviour

Is there a way to decrease the font size of the labels dynamically and make them display all in the axis depending on the zoom level ?

<img width="531" alt="image" src="https://user-images.githubusercontent.com/10185101/167400795-c1f02cc7-859e-4968-910e-5f8ee40d63e2.png">

In the above image, you can see that in the red boxes, there is no labels displayed, since its getting hidden 

Requirement:
Don’t skip/hide Trade labels on x-axis when expanding the number of trades to show. Just have them squish.

Please provide a solution for this

Thanks

**Comment by martynasma** [comment]
There's no option to "auto-squish" categories to fit them, I'm afraid.

There's a number of options for you to consider:

1) Using rotated labels.
2) Reducing font size.

To control how and when labels/grid is removed due to chart size, please read here:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Controlling_spacing

**Comment by denkquer** [comment]
You can also use axisRanges to render them yourself.

**Comment by azharakbar** [comment]
@denkquer 
Thanks, can you please give me an example for that in amcharts demo ?
