### ISSUE TITLE
Tooltip's exportable (and other elements) set to false still appears in export but only in specific circumstances 

### ISSUE THREAD

**Issue by jswelsh** [amcharts/amcharts4#4090]
Took a while to figure out how to replicate.

experiencing a bug that I feel tricks exportable property to not be honoured.

having elements exportable set to false, such as
```
let axisTooltip = yAxis.tooltip;
axisTooltip.exportable = false;
```
**happy path**
clicking the native export menu button
selecting any of the formats
don't move mouse cursor anywhere on graph until an export prompt appears
![disabledExportWorking](https://user-images.githubusercontent.com/51499117/172742967-2d6182ea-da35-49f2-b505-a8fe1772b48a.png)

**sad path**
clicking the native export menu button
selecting any of the formats
move cursor onto graph, sometimes across multiple points (doesn't trigger depending on how quickly the export processes occurs)
![exportDisableNotWorking](https://user-images.githubusercontent.com/51499117/172743018-97fa6319-88da-4b99-83c2-16f0d57dad20.png)

I suspect this is a limitation of the exportable = false property. But maybe a bug

**Comment by xorspark** [comment]
The charts operate asynchronously and the elements marked as non-exportable are removed at the beginning of the process. Since the cursor can still trigger the tooltip and add them back in while the export is in progress, you'll want to disable cursor interactivity during the export process and re-enable it afterward to prevent the cursors from appearing in this scenario:

```
chart.exporting.events.on("exportstarted", () => {
  chart.cursor.interactionsEnabled = false;
})

chart.exporting.events.on("exportfinished", () => {
  chart.cursor.interactionsEnabled = true;
})
```

**Comment by jswelsh** [comment]
Awesome, @xorspark that works perfectly.
