### ISSUE TITLE
Zooming in on the map in IE 11 causes scrollbars to appear

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#411]
When you zoom into a map in v4, scrollbars appear in the page in IE 11. This does not occur with other browsers.

[Debug codepen link](https://s.codepen.io/team/amcharts/debug/7b81c4622c2252be13c667702940ec05)
[Codepen with source](https://codepen.io/team/amcharts/pen/7b81c4622c2252be13c667702940ec05)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.83](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.83).

## [4.0.0-beta.83] - 2018-11-15

### Added
- [`hideOverflow`](https://www.amcharts.com/docs/v4/reference/svgcontainer/#hideOverflow_property) added to `SVGContainer` class. If set to `true` it will apply `overflow: hidden` to chart container so that all chart elements are contained within. Default is `false`, except on `MapChart`, which has it at `true`.

### Fixed
- Some adjustments and fixes to animations associated with `hide()`/`show()` functions.
- If a legend was initially disabled, it was not appearing when enabled later.
- `chart.addData()` was not adding data to `XYChart` scrollbar series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
