### ISSUE TITLE
AM/PM timestamps are not parsed correctly

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#412]
Date-based data with 12 hour am/pm timestamps are not parsed correctly when using `h` and `a` formats in `inputDateFormat`. In the [linked codepen](https://codepen.io/team/amcharts/pen/20c540048b1ebdd13e80548387e34fac?editors=0010) I have datetime strings in the format of `M/d/yyyy h:mm:ss a` from 1 am to 2:45 pm but the columns are placed in the wrong location and times after 10:45 am have a huge gap, whereas the [24 hour version](https://codepen.io/team/amcharts/pen/3384f184d80749c9ce0e61898c6adc36?editors=0010) renders correctly using the `M/d/yyyy H:mm:ss` format. Note that the data and axis also start in the wrong place (midnight in the 12 hour version, 1 am in the 24 hour version).

**Comment by martynasma** [comment]
Fixed in dev. Will release soon.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.56](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.56).

## [4.0.0-beta.56] - 2018-10-12

### Added
- New `Sprite` adapter: `"populateString"`. Applied to strings after `Sprite` replaces data binders with real values, but before any formatting by `Label` kicks in.
- New `Label` property: [`ignoreFormatting`](https://www.amcharts.com/docs/v4/reference/label/#ignoreFormatting_property). If set to `true` will treat formatting blocks in square brackes (e.g. `"[red bold]"`) as regular text and will display them as such.

### Changed
- Default big, small, and byte suffixes in `NumberFormatter` are now translatable via locale files.
- The suffix for thousands "kilo", was changed to lowercase "k", as per [standards](https://en.wikipedia.org/wiki/International_System_of_Units#Prefixes).
- On `XYChart`, default for [`mouseWheelBehavior`](https://www.amcharts.com/docs/v4/reference/xychart/#mouseWheelBehavior_property) changed to `"none"` (was `"zoomX"`).

### Fixed
- Improved performance! All charts types are now noticably, some drastically are faster. Some memory leakages fixed as well.
- Now `MapPolygonSeries` will not inherit chart's global `geodata` if it has own `geodataSource` set.
- `DateFormatter` was not parsing all AM/PM string dates correctly.
- `DateFormatter` was not parsing `MMM` (short month names like "Jan", "Feb") propertly.
- In-line date formatter was not working correctly in some cases, e.g. `"{dateX.formatDate()}"`.
- Setting `chart.mouseWheelBehavior = "none"` did not release wheel scrolling of the web page when hovering over chart.
- `DataSource`'s' `"done"` event was being called if parsing of loaded data failed. Not anymore. `"done"` is called only on successful load. To catch any load (including one that ended in http or parse error) use `"ended"`.
- `DataSource`'s' `reloadFrequency` was broken if error occurred during one of the loads. This has been fixed. Even if error occurrs, loader will try to reload data in the next reload slot.
- JSON: `heatRules` did not work properly with their target set to a list template, e.g. `mapPolygons.template`.
- Auto-calculated `DateAxis.baseInterval` was not being carried over to the `XYChartScrollbar`.
- `DurationAxis` scale sometimes was dropping to negative values, even there were no negative values in data.
- `PieChart` and `Legend` were not working properly with `chart.zoom()` or `legend.zoom()` methods.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
