### ISSUE TITLE
How to click a chart bar with react testing library without accessing implementation details?

### ISSUE THREAD

**Issue by Rokuem** [amcharts/amcharts4#4120]
I have a bar chart that selects an item when a bar is clicked. I wanted to make a test that would select the item and check if its details were displayed in another component, but I can't find a way to effectively trigger the "hit" event without going into implementation details.

I tried:
```
const option = screen.getByRole("menuitem");

fireEvent(
  option,
  new PointerEvent("pointerup", {
    bubbles: true,
  })
);
```

but that doesn't seem to work. I also tried the other events listed here:
![image](https://user-images.githubusercontent.com/26756006/182205604-1ae454dc-f3c4-4fdb-b3f7-ea10095e47a8.png)

This is the list of events firefox detected on the bar element. I tried a few things in the browser itself, but also didn't manage to manually trigger the "hit" event.

An alternative would be to mount things with mocked state, but I wonder if there is a good way to interact with the chart inside tests.

**Comment by martynasma** [comment]
Due to how interactions in amCharts 4 work, you will need a combination of two events to simulate a click on an element:

1. Simulate "pointerdown" event on the element itself.
2. Simulate "pointerup" event on `document`.

Here's an example:
https://codepen.io/team/amcharts/pen/bGvLBBN/67d1701b1b922ec4eec4f948018d3af4?editors=0010

**Comment by Rokuem** [comment]
![image](https://user-images.githubusercontent.com/26756006/182396106-5d8b494a-26b6-4f74-86a7-b47c81d4b55f.png)
This seems to work :D. Thanks @martynasma !
