### ISSUE TITLE
middle node's link(middleLine) is not showing when chart data has odd number of items.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [amcharts/amcharts4#4134]
**Bug description**

Same as title.
https://codepen.io/algorist/pen/eYMaVxz

**Environment (if applicable)**
amCharts 4
Chrome 104.0.5112.102

**Additional context**

**Comment by martynasma** [comment]
Fixed in 4.10.28.

## [4.10.28] - 2022-09-19

### Added
- `"p"` number formatting modifier added. Works the same way as `"%"` except it treats numbers as absolute values and does not multiply them by 100.

### Changed
- `"%"` number formatting modifier will now consider locale when choosing whether percent sign goes before or after the number. At this moment only `tr_TR` (Turkish) locale is placing percent sign before number.

### Fixed
- Pressing ENTER while `PieSeries` was focused would not toggle it.
- `SankeyLink` middle line was not drawn in it was a straight line.
- Legend's scrollbar was not adjusting thumb size if the div of a chart changed its height.
