### ISSUE TITLE
While using an adapter on Label, the target._dataItem is always undefined

### ISSUE THREAD

**Issue by ShahdaSayed** [amcharts/amcharts4#4155]
I am using @amcharts/amcharts4@4.10.25 and I have a logic where I have to access the dataItem of the target.

```
const labelBullet = series.bullets.push(new am4charts.LabelBullet());
labelBullet.label.adapter.add("html", (_html, target) => {
	let labelValue;
	if (target.dataItem) {
		labelValue = target.dataItem.values.value.value;
	}
	if (labelValue === undefined) {
		return `<span style="background-color: ${target.dataItem['column'].fill.hex};">{value.workingValue.formatNumber('#.')}</span>`
	}
	return `<span style="background-color: ${target.dataItem['column'].fill.hex};>{value.workingValue.formatNumber('#.')}%</span>`;
})
```

From @amcharts/amcharts@4.10.26, `target.dataItem` is always undefined.
This is breaking our existing implementation.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
The change was introduced fixing another issue.

When `fill` is set on a Label, it checks if `html` is set to, so that it can update color of the HTML content.

Since fill is often set before data item is initialized, this results in your adapter kicking in before data item, hence `undefined`.

That said, further updates (including when data item is set), cause adapter to re-run.

It should be sufficient to add check if data item is present. It's a good sense to do that in any case, rather than relying it to always being there.

Here's how your code might look:

```
const labelBullet = series.bullets.push(new am4charts.LabelBullet());
labelBullet.label.adapter.add("html", (html, target) => {
  if (target.dataItem === undefined) {
    return html;
  }
  let labelValue = target.dataItem.values.value.value;
  if (labelValue === undefined) {
    return `<span style="background-color: ${target.dataItem['column'].fill.hex};">{value.workingValue.formatNumber('#.')}</span>`
  }
  return `<span style="background-color: ${target.dataItem['column'].fill.hex};>{value.workingValue.formatNumber('#.')}%</span>`;
})
```

**Comment by ShahdaSayed** [comment]
Thanks for the clarification.
