### ISSUE TITLE
update xlsx module due to dependant module printj has EOL

### ISSUE THREAD

**Issue by pradnyavpatil** [amcharts/amcharts4#4157]
**Bug description**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Fixed in 4.10.30.

## [4.10.30] - 2022-11-14

### Changed
- Upgraded `xlsx` package to version 0.18.5.

### Fixed
- Stacked series were not being displayed correctly if it was hidden during data update.

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
