### ISSUE TITLE
Multiple tooltips in ColumSeries and dateAxis

### ISSUE THREAD

**Issue by murilo-kendjy** [amcharts/amcharts4#4166]
I'm using ColumsSeries and dateAxis to plot 3 data sets (serie1, serie2 and serie3), serie1 and serie 2 does not overlap in my dateTime axis, but my serie3 is something like an event and can occur in any dateTime thus overlaping with both serie1 or serie2.

I'm able to plot the 3 series together, the only problem is that when the event (serie3) occurs the tooltip only shows for one of the series.

Using this [codePen](https://codepen.io/m_kendjy/pen/mdKrPxv?editors=0010), is possible to see that on times: 20:30, 20:45 and 22:30 when the serie3 occurs only one tooltip is shown.

So my question is, is it possible using this method to show both tooltips?

Not sure if it helps, but all my series has an interval of 15min on each data. I tried shifting my serie3 some seconds so it won't overlap, but it breaks the whole X axis scale.

**Comment by martynasma** [comment]
When using a DateAxis, data needs to be ordered in ascending order, whereas yours isn't.

This can lead to other more anomalies, not just the tooltip issue.

In this particular setup, I recommend setting data directly to series that's relative to that series only, rather than chart:

```
series1.data = data1;
series2.data = data2;
```

https://www.amcharts.com/docs/v4/concepts/data/#Series_specific_data

**Comment by murilo-kendjy** [comment]
@martynasma My data was in fact a ordered JS Date Object, I just changed to "time" to simplify. Anyway changing my data from chart to the series itself solved the tooltip issue, thanks.
