### ISSUE TITLE
Amcharts 4: Is there an exapmple for using Vue3 with Composition API and dynamic data?

### ISSUE THREAD

**Issue by TangoPJ** [amcharts/amcharts4#4189]
I have a problem with my Vue.js 3 Composition API when I trying to render dynamic data I'm getting an error "Maximum call stack size exceeded"
When the incoming data is updated I set this data to a chart.value.data ref variable, then this error appears

As an example the script looks like this:
```
const createChart = () => {
      chart.value = am4core.create(chartdiv.value, am4charts.XYChart);
      const categoryAxis = chart.value.xAxes.push(new am4charts.CategoryAxis());
      categoryAxis.dataFields.category = 'date';
      chart.value.data = [
        { count: 5, date: '2022-12-01' },
        { count: 2, date: '2022-12-02' },
        { count: 6, date: '2022-12-03' },
      ];
      chart.value.yAxes.push(new am4charts.ValueAxis());
      const series = chart.value.series.push(new am4charts.ColumnSeries());
      series.dataFields.valueY = 'count';
      series.dataFields.categoryX = 'date';
};

```
In this example I set the static data, but in my project it's dynamic, that I get from the db.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/64611024/209642115-b73d4796-28e2-4445-bb96-471c49cbeb91.png">

**Comment by martynasma** [comment]
Perhaps this will help:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-vue-js/#Important_note

**Comment by TangoPJ** [comment]
@martynasma Can you open the online code editor - https://codesandbox.io/s/nameless-firefly-orf69p?file=/src/components/HelloWorld.vue
And if you change the size of the screen you should see an error (Maximum call stack size exceeded or Cannot read properties of undefined (reading 'positionInvalid')) What am I doing wrong?
Thank you

**Comment by xorspark** [comment]
As noted in @martynasma's link, Vue's reactivity system conflicts with amCharts objects since amCharts makes its own changes as needed. `ref` is having the same effect since it watches over every change on the object so Vue is trying to apply its own updates while amCharts is updating itself. 

You can try using `shallowRef` instead since it doesn't make the object deeply reactive and only triggers on `.value`, allowing both libraries to coexist. 

Ideally you should just limit your reactivity to the data itself and copy updates over to the chart, while keeping amCharts objects as standalone non-ref'd variables (note my [v5 example keeps the root object as standalone](https://stackblitz.com/edit/vitejs-vite-yfb14k?file=src%2Fcomponents%2FHelloWorld.vue)).
