### ISSUE TITLE
How to sort and filter data with createFromConfig

### ISSUE THREAD

**Issue by mazhar-kv** [amcharts/amcharts4#4202]
**Stack**

- React Typescript
- AmCharts4

[**CodeSandbox**
](https://codesandbox.io/s/beautiful-pine-zs1re0?file=/src/pages/Bar.tsx)

Can anyone help me how i can sort and filter data for a chart thats created with createFromConfig instead of sorting data manually. 

Also is there any way to update the JSON config of the chart without calling createFromConfig all over again?

**Comment by mazhar-kv** [comment]
@martynasma , 

Can you help me out here, sorry for pinging you here, Urgent requirement.

**Comment by martynasma** [comment]
You can add an event to the `beforedatavalidated` event to the chart.

The following tutorial goes in-depth examples (including for JSON config) of using this event to pre-process the data before it is parsed by chart:
https://www.amcharts.com/docs/v4/tutorials/manipulating-chart-data/

Please consider posting a separate issue for your additional question, since it is not related to the original question.
