### ISSUE TITLE
Date axis collapsed if groupData is used

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts4#4233]
Hi! I noticed, that my chart behaves incorrectly with dateAxes.groupData setted to true.
This is how it is supposed to display: 
![image](https://user-images.githubusercontent.com/18229211/225535100-fb07d6ef-7349-4746-9121-079245638a4f.png)

And if i turn on groupData:
![image](https://user-images.githubusercontent.com/18229211/225535314-e3a24754-2c61-42e6-88f4-e32e7ca3c674.png)

Any clues, why this can happen?
[Example](https://codepen.io/12rita/pen/Vwdzzey)

**Comment by martynasma** [comment]
Fixed in 4.10.35.

## [4.10.35] - 2023-03-21

### Fixed
- RTL text was not being truncated correctly.
- Removed chart producing an error on longpress on touch devices in some cases.
- In some cases, when a series was removed from a Serial chart, it was not disposing one of the listeners and could remain in the memory.
