### ISSUE TITLE
SerialChart: series disposer added to _disposers not removed when series is removed

### ISSUE THREAD

**Issue by hesselmeulenbeld** [amcharts/amcharts4#4238]
The ```registry.events.once("exitframe", () => { ...```  listener added to this._disposers in SerialChart::handleSeriesAdded2 is not removed when the series is removed in SerialChart::handleSeriesRemoved.
This listener keeps the series object alive which causes memory problems when adding and removing a lot of series from the chart.

**Comment by hesselmeulenbeld** [comment]
Does this fix also work when adding multiple series / removing one serie? 
The _exitDP only contains the disposer of the last added series.

The following sequence will not work:

1. Add series A
2. Add series B
3. Add series C
4. Remove series B
5. Remove series A
6. Remove series C

Only the listener for series C will be disposed, the other listeners will still be active?

**Comment by martynasma** [comment]
Sorry about that. Looks like we'll need another update.

**Comment by martynasma** [comment]
Fixed in 4.10.36.

## [4.10.36] - 2023-05-18

### Added
- New locale: Faroese (fo_FO). Thanks Martin Puge.

### Changed
- A link object that was created with `linkWith` for `ForceDirectedNode` is pushed to the child node's data items `childLinks` array and also `node.linksWith` list.
- Removed `xlsx` package (with vulnerability) from dependencies in favor of a bundled hard copy (version 0.19.3) due to their decision not to publish to NPM. ([Issue 4261](https://github.com/amcharts/amcharts4/issues/4261)).

### Fixed
- In some cases, when a series was removed from a `SerialChart` it was not disposing one of the listeners and could remain in the memory.
- Grip rollover labels of a vertical `Scrollbar` were showing opposite values.
