### ISSUE TITLE
Adding fo_FO.ts (Faroe island language) to supported languages

### ISSUE THREAD

**Issue by Puge96** [amcharts/amcharts4#4247]
Hi team

We are using amcharts4 and have a client that is requesting faroe island translation (fo_FO.ts). It's not supported as-is but we can provide the correct file if it can be included in the project.

Is this something you can add if we provide the file?

Best regards,
Martin

**Comment by Puge96** [comment]
@martynasma I've added a pull request to add faroese language.
https://github.com/amcharts/amcharts4/pull/4248

**Comment by martynasma** [comment]
Thanks for this. We'll include in the next release.

At this point we do not know when that will happen, but we'll let you know here when it's out.

**Comment by martynasma** [comment]
Added in 4.10.36.

## [4.10.36] - 2023-05-18

### Added
- New locale: Faroese (fo_FO). Thanks Martin Puge.

### Changed
- A link object that was created with `linkWith` for `ForceDirectedNode` is pushed to the child node's data items `childLinks` array and also `node.linksWith` list.
- Removed `xlsx` package (with vulnerability) from dependencies in favor of a bundled hard copy (version 0.19.3) due to their decision not to publish to NPM. ([Issue 4261](https://github.com/amcharts/amcharts4/issues/4261)).

### Fixed
- In some cases, when a series was removed from a `SerialChart` it was not disposing one of the listeners and could remain in the memory.
- Grip rollover labels of a vertical `Scrollbar` were showing opposite values.
