### ISSUE TITLE
Rendering a chart on an email

### ISSUE THREAD

**Issue by soumyaa1804** [amcharts/amcharts4#4280]
**Question**
I am using Amcharts in my project and I have created some charts using it. Now I want to have a functionality to be able to share the charts over email. I am wondering if it is possible to render a chart on email with the user being able to hover over the charts to get tooltip.

Currently, I have idea to render the chart as image and use Image map of HTML to get the hover effect. Not sure how feasible it is.

Can someone please help me how I can go about it? Would it be possible to render an interactable chart on an email? 

**Environment (if applicable)**
Considering all the latest versions 

**Additional context**

**Comment by xorspark** [comment]
> Would it be possible to render an interactive chart on an email?

I'm afraid not. The chart only exports as static images and there's no hook for an image map as part of the output. Even if you had an image map, your next obstacle would be email client support for rendering any hover over popover effects since CSS support in email is fairly limited.

Why not just have the static image of the chart link to an interactive version instead?

**Comment by soumyaa1804** [comment]
Okay, yeah this helps. Thanks for the input.
