### ISSUE TITLE
XYChartScrollbar not displaying any content

### ISSUE THREAD

**Issue by VT-hash** [amcharts/amcharts4#4288]
Does the content shown in the `XYChartScrollbar` depend on `chart.data` in some way? Once I set the `chart.data` to the values I would like to have exported, the content from `XYChartScrollbar` disappears (The scroll bar is still present, but the middle section where it used to show the chart is now blank).

![image](https://github.com/amcharts/amcharts4/assets/82308558/a38ed1d6-34af-44ce-b412-fe69d0fa3d6f)

If the `XYChartScrollbar` does depend on `chart.data`, is there a way for me to format the export data but still have the `XYChartScrollbar` show the original content from the chart?

The scrollbar is setup as:
```javascript
chart.scrollbarX = new am4charts.XYChartScrollbar();
chart.scrollbarX.parent = chart.bottomAxesContainer;

...

for (...)
    chart.scrollbarX.series.push(series);

...

chart.data = [list_of_custom_formated_data]
```

***

Additionally, I observed that the variable `chart.data` is an empty array. When `chart.data` remains unchanged, the `XYChartScrollbar` accurately displays the chart content. However, once any value is assigned to `chart.data`, even if it's an empty array (the same as its original value), the `XYChartScrollbar` ceases to show the chart.

- Working example:
```javascript
chart.scrollbarX = new am4charts.XYChartScrollbar();
chart.scrollbarX.parent = chart.bottomAxesContainer;

...

for (...)
    chart.scrollbarX.series.push(series);

...

console.log(chart.data)
>>> []
```

- Not working example:
```javascript
chart.scrollbarX = new am4charts.XYChartScrollbar();
chart.scrollbarX.parent = chart.bottomAxesContainer;

...

for (...)
    chart.scrollbarX.series.push(series);

...

console.log(chart.data)
>>> []

chart.data = [];
```

**Comment by xorspark** [comment]
The underlying scrollbar chart will look at the data value if set after the fact; since the values in `chart.data` likely don't correspond to your series' value fields, the resulting output will be empty in the scrollbar.

As mentioned in my [prior response](https://github.com/amcharts/amcharts4/issues/4283#issuecomment-1584904770) you can use the `data` adapter on the exporting object to set up your data for export with your desired formatted values, given that you have only series-level data. This will avoid this issue entirely.

If you *must* set `chart.data`, you'll need to use a timeout or listen to the `datavalidated` event to reset the scrollbar chart's series data, for example:

```
chart.events.on('datavalidated', () => {
    chart.scrollbarX.scrollbarChart.series.getIndex(0).data = chart.series.getIndex(0).data
})
```

The adapter method mentioned in your other ticket is the cleaner approach, however.
