### ISSUE TITLE
Multiple Y-axes tick alignment

### ISSUE THREAD

**Issue by pouretrebelle** [amcharts/amcharts4#433]
I've got two data series corresponding to multiple axes like this:

![image](https://user-images.githubusercontent.com/1901935/46484741-46e18d00-c7f2-11e8-8fea-6cd772370044.png)

Is there any way to have the ticks and lines on each axis match without calculating + rounding the domains of each data set?

This is what I'm trying to achieve:

![image](https://user-images.githubusercontent.com/1901935/46484761-4d700480-c7f2-11e8-84f0-561b59d129a9.png)

It starts to look really messy if I don't set the min on each axis to 0 😕 

![image](https://user-images.githubusercontent.com/1901935/46485094-ea32a200-c7f2-11e8-9cb5-592ad4a21c1f.png)

Thank you

**Comment by definitelycarter** [comment]
I believe this to be a bug since this behavior was introduce with this new version.

In version 3, it appears to calculate the max value at a different proportion.
**Version 3**
<img width="777" alt="image" src="https://user-images.githubusercontent.com/6287039/52486751-fad09b80-2b89-11e9-81ac-60731efb8949.png">

However, in version 4, the max for the left side was calculated to be 70 instead of 80.
**Version 4**
<img width="780" alt="image" src="https://user-images.githubusercontent.com/6287039/52486711-db397300-2b89-11e9-9728-63d9e0ae9bfc.png">

Also, in this scenario, it looks weird that the value 69 would tick higher than 71 on the bar chart.

**Comment by BrkCoder** [comment]
Hey I am having this issue too, please provide a simple workaround until this feature of sync yaxis alignment will be out.

**Comment by runfaj** [comment]
Putting in a "me too" to add another vote. My example for the duplicate issue was referenced above. (https://github.com/amcharts/amcharts4/issues/1606)

**Comment by runfaj** [comment]
Definitely unacceptable, especially when negative values are involved. At the absolute very least, the 0 axis should line up, but even that is off.

![image](https://user-images.githubusercontent.com/3292053/65259213-8f589000-dac1-11e9-8c3c-802b0929f49c.png)

The settings for adjusting these axis values only provide granularity as strictMinMax, min, max, extraMin, and extraMax. While you can potentially use these to get the start/end values on the second axis to match to the first axis, there is no way to adjust step count, so it's impossible to manually get these to match without drastically skewing the graphs.

**Comment by martynasma** [comment]
Hi everyone.

Grid syncing is now available (since verison `4.8.1`) via `syncWithAxis` setting.

More details:
https://www.amcharts.com/docs/v4/concepts/axes/value-axis/#Synchronizing_grid
