### ISSUE TITLE
Axis tooltip is trimmed when renderer.inside = true

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#441]
Example:
https://codepen.io/dmsmaxim/pen/pxEzjM
If you hover the last point, you can see that tooltip is trimmed:
![image](https://user-images.githubusercontent.com/15041200/46550374-8b962280-c8dd-11e8-9ca2-4c881488fcc9.png)
However if you remove `categoryAxis.renderer.inside = true;`, everything works perfect. Tooltip just moves left.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.58](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.58).

## [4.0.0-beta.58] - 2018-10-17

### Added
- `ExportMenu`'s "custom" items can now have `"callback"` which is a function to call when clicked on such custom item.

### Changed
- Slice labels on a `PieChart` now move with the slice (if `alignLables = false`).

### Fixed
- `requestAnimationFrame` now is called only when needed. This reduces idle CPU usage.
- Fixed `m4core.color()` result caching issue.
- Charts were broken in IEs since beta.57.
- `Tooltip` on `LineSeries` was not updating color if segment changed color.
- `MapChart` without any series was displaying an error in console.
- Axis tooltip was trimmed when `renderer.inside = true`.
- `StepLineSeries` `startLocation`/`endLocation` bug fixed.
- `"hover"` state was not being applied to series' bullet if it did not hav `tooltipText` set.
- `bulletLocation` for horizontal `ColumnSeries` fixed.
- Value labels of `Legend` were not in correct positions if `Legend` was positioned at the top or bottom (too close to legend label).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
