### ISSUE TITLE
 Clarification on Future Support and Recommendations for amCharts 4 vs. amCharts 5

### ISSUE THREAD

**Issue by bnarasimhamca10** [amcharts/amcharts4#4424]
Hi Team,

We are currently using amCharts 4 for our data visualization needs and noticed that amCharts 5 is now available. We would like to understand the following:

1. What is the roadmap for amCharts 4? Will it continue to be supported and receive updates in the future?
2. Are there any known compatibility issues or advantages to upgrading to amCharts 5?
3. Is there an official recommendation on whether users should upgrade to amCharts 5, especially for long-term projects?

Looking forward to your guidance on this.

**Comment by martynasma** [comment]
> What is the roadmap for amCharts 4? Will it continue to be supported and receive updates in the future?

Support for amCharts 4 has already reached EOL. We do not make updates, nor officially provide support for it. The updates are only issued for critical issues.

> Are there any known compatibility issues or advantages to upgrading to amCharts 5?

The main change is that instead of SVG V5 uses canvas rendering. This makes it much faster but might be an issue if you are relying on output being an SVG. E.g. for DOM testing, or export to SVG.

v5 also does not have 3D charts.

Other than that, the two versions are comparable, feature-wise.

The code is not interchangeable, though.

> Is there an official recommendation on whether users should upgrade to amCharts 5, especially for long-term projects?

Just common sense. V4 is deprecated. V5 is now being actively supported and developed. Might make sense to use V5 for long-term projects.

Also, V5 is much much faster, if performance is any issue with your V4 setups.
