### ISSUE TITLE
Map errors if there are no MapPolygonSeries or they do not have data set

### ISSUE THREAD

**Issue by bengallienne** [amcharts/amcharts4#445]
Hi,

I'm having an issue where while loading a map chart in to a Vue component, which uses the ES import method to get the modules it needs, I get an error when trying to create a chart, regardless of how I do it.

The error reads 'Cannot read property 'longitude' of undefined', and an example of a component where it happens can be found here;

https://codesandbox.io/s/rlynkkqkno

Am I doing something wrong? Are you able to let me know if I need to change my setup or if this is a bug please?

Thanks!

**Comment by martynasma** [comment]
It seems like your map code have no series defined.

So it's not a Vue issue but rather issue of map erroring out instead of just displaying nothing silently.

A map without any series does not make a lot of sense, hence it not being accounted for such situation. That said, it should not error out either since series might be added later.

Here's an simple isolated case without Vue:
https://codepen.io/team/amcharts/pen/ae30dea70b71f70c259fe736a73ab10d

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.58](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.58).

## [4.0.0-beta.58] - 2018-10-17

### Added
- `ExportMenu`'s "custom" items can now have `"callback"` which is a function to call when clicked on such custom item.

### Changed
- Slice labels on a `PieChart` now move with the slice (if `alignLables = false`).

### Fixed
- `requestAnimationFrame` now is called only when needed. This reduces idle CPU usage.
- Fixed `m4core.color()` result caching issue.
- Charts were broken in IEs since beta.57.
- `Tooltip` on `LineSeries` was not updating color if segment changed color.
- `MapChart` without any series was displaying an error in console.
- Axis tooltip was trimmed when `renderer.inside = true`.
- `StepLineSeries` `startLocation`/`endLocation` bug fixed.
- `"hover"` state was not being applied to series' bullet if it did not hav `tooltipText` set.
- `bulletLocation` for horizontal `ColumnSeries` fixed.
- Value labels of `Legend` were not in correct positions if `Legend` was positioned at the top or bottom (too close to legend label).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
