### ISSUE TITLE
Cant animate marker on MapImageSeries template

### ISSUE THREAD

**Issue by sonnh58** [amcharts/amcharts4#448]
I try to animate marker template but it is not working.
Can anyone show me how. I want it work like bulletAlertCircle in [this example](https://codepen.io/team/amcharts/pen/geEzxL/)

Reproduce
https://codepen.io/nguyn-hng-sn/pen/GYrzyv

**Comment by notacouch** [comment]
At first look it does look like your markers should animate.

Upon closer inspection I noticed in our demo that `honolulu` is not a `template`, but an actual marker already placed on the map. With that in mind I tried seeing if we run animations on your markers once they're created, and that seems to have done the trick.

I take your animation line...

```javascript
var bulletAlertAnimation = bulletAlertCircle.animate([{ property: "radius", to: 50 }, { property: "strokeOpacity", to: 0, from: 1 }], 600).loop();
```

...place it in an event listener for when the series' `mapImages` would be ready, and instead of using the `template`'s `Circle` `animate` method, I run it on each of the `mapImages` `Circle`s.

```javascript
imageSeries.events.once("inited", function() {
  imageSeries.mapImages.each(function(mapImage) {
    var bulletAlertAnimation = mapImage.children
      .getIndex(0)
      .animate(
        [
          { property: "radius", to: 50 },
          { property: "strokeOpacity", to: 0, from: 1 }
        ],
        600
      )
      .loop();
  });
});
```

Here's a fork of your reproduction:
https://codepen.io/team/amcharts/pen/a37d59b5d83256162ae08674e2bac192/

**Comment by sonnh58** [comment]
@notacouch Thank you so much

**Comment by notacouch** [comment]
@sonnh58 you're welcome, glad this was able to help you!
