### ISSUE TITLE
Bundle error with React v15

### ISSUE THREAD

**Issue by igoriok1994** [amcharts/amcharts4#450]
Hi,

After import have bundle (build) error (Uncaught SyntaxError: Unexpected token export)

`import * as am4core from "@amcharts/amcharts4/core";`
`import * as am4charts from "@amcharts/amcharts4/charts";`
`import am4themes_animated from "@amcharts/amcharts4/themes/animated";`

![image](https://user-images.githubusercontent.com/37294916/46730862-d9ba7580-cc91-11e8-92c1-ef1f0e86665a.png)

How to deal with it?

React v15.4
Webpack v1.13
Babel-polyfill v6.26
etc...

**Comment by notacouch** [comment]
It's not a React thing, e.g. here's a sample of amCharts working w/ React 16:
https://stackblitz.com/edit/39135-react-v16

It looks like when it comes to transpiling, it's not interpreting ES2015 modules (esm), though it's not clear if that's in general or specific to packages (in /node_modules/). I haven't used babel-polyfill and we don't know what your setup is like, but just in case it's not doing that job, have you tried any babel es2015 presets or esm-related loaders, or [esm loader](https://github.com/standard-things/esm)? 

You may have to specify to include the amcharts package as one of the things to transpile, which may look something like:

```javascript
{
  // ....
  module: {
    loaders: [
      {
         test: '\.js',
         include: ['/node_modules/@amcharts'],
      }
    ]
  }
}
```

Let us know if that helps, or if you can set something up on [StackBlitz](http://stackblitz.com/) or [CodeSandbox](http://codesandbox.io/) for us to look at so we can help.

**Comment by igoriok1994** [comment]
Looks like than. But in this project we are using ES2015 presets (es2015 exports and imports works fine).
Cant upload an example, because it's a big project. But I can show package.json and webpack.config.js files, I think problem might be there. 

Btw babel-polyfill includes core-js.

By the way, amCharts 3 works fine, so will try to use this version, until amCharts v4 will be released. Also have in plans to update out webpack version (maybe this will be a solution for out propblem).

So, package.json looks like this:
```javascript
{
  "name": "Some people working",
  "version": "1.0.0",
  "description": "Some people working on this app",
  "main": "''",
  "scripts": {
    "build": "webpack --config webpack.production.config.js --progress --profile --colors",
    "start": "webpack-dev-server --progress --profile --colors",
    "lint": "eslint --ext js --ext jsx src || exit 0",
    "docs": "node docmaker.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/alicoding/react-webpack-babel"
  },
  "author": "",
  "license": "",
  "homepage": "",
  "dependencies": {
    "@amcharts/amcharts3-react": "^3.1.0",
    "@amcharts/amcharts4": "^4.0.0-beta.55",
    "amcharts3": "github:amcharts/amcharts3",
    "anchorme": "^1.1.2",
    "autoprefixer": "^6.7.7",
    "axios": "^0.16.2",
    "babel-polyfill": "^6.26.0",
    "brace": "^0.10.0",
    "classnames": "^2.2.6",
    "cleave.js": "^1.4.4",
    "docgen-loader": "^1.3.4",
    "interact.js": "^1.2.8",
    "js-file-download": "^0.4.4",
    "json-loader": "^0.5.7",
    "jsonwebtoken": "^7.4.3",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "node-sass": "^3.13.1",
    "react": "15.4.2",
    "react-ace": "^6.2.0",
    "react-addons-perf": "^15.4.2",
    "react-color": "^2.14.0",
    "react-data-grid": "^4.0.8",
    "react-data-grid-addons": "^4.0.7",
    "react-day-picker": "^7.2.4",
    "react-docgen": "^2.21.0",
    "react-dom": "15.4.2",
    "react-redux": "^4.4.9",
    "react-router": "^3.2.1",
    "react-select": "^1.3.0",
    "react-split-pane": "^0.1.84",
    "react-tooltip": "3.3.0",
    "react-transition-group": "^2.5.0",
    "react-virtualized": "9.9.0",
    "redux": "^3.7.2",
    "redux-thunk": "^2.3.0",
    "sass-loader": "^4.1.1",
    "shortid": "^2.2.13",
    "split.js": "^1.5.2",
    "swiper": "^3.4.2",
    "validator": "^6.3.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.16.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "css-loader": "0.25.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "0.9.0",
    "html-webpack-plugin": "^2.30.1",
    "postcss-loader": "^1.3.3",
    "react-addons-perf": "^15.4.2",
    "react-hot-loader": "^3.1.3",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "1.13.2",
    "webpack-cleanup-plugin": "^0.4.2",
    "webpack-dev-server": "1.16.2"
  }
}
```

And this is how our webpack.config looks like:

```javascript
"use strict";
var webpack = require('webpack');
var path = require('path');
var loaders = require('./webpack.loaders');
var HtmlWebpackPlugin = require('html-webpack-plugin');

// const HOST = process.env.HOST || "192.168.0.68";
const HOST = process.env.HOST || "192.168.168.103";
const PORT = process.env.PORT || "3001";

const NODE_ENV = process.env.NODE_ENV || 'dev';

// global css
loaders.push({
	test: /\.css$/,
	exclude: /[\/\\]src[\/\\]/,
	loaders: [
		'style?sourceMap',
		'css'
	]
});

// local scss modules
loaders.push({
	test: /\.scss$/,
	exclude: /[\/\\](node_modules|bower_components|public)[\/\\]/,
	loaders: [
		'style?sourceMap',
		'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
		'postcss',
		'sass'
	]
});

// local css modules
loaders.push({
	test: /\.css$/,
	exclude: /[\/\\](node_modules|bower_components|public)[\/\\]/,
	loaders: [
		'style?sourceMap',
		'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]'
	]
});

module.exports = {
	entry: [
		'react-hot-loader/patch',
		'./src/index.jsx' // your app's entry point
	],
	// devtool: process.env.WEBPACK_DEVTOOL || 'cheap-module-source-map',
	devtool: NODE_ENV == 'dev' ? 'cheap-module-source-map' : null,
	output: {
		path: path.join(__dirname, 'public'),
		filename: 'bundle.js'
	},
	resolve: {
		extensions: ['', '.js', '.jsx']
	},
	module: {
		loaders
	},
	devServer: {
		contentBase: "./public",
		// do not print bundle build stats
		noInfo: true,
		// enable HMR
		hot: true,
		// embed the webpack-dev-server runtime into the bundle
		inline: true,
		// serve index.html in place of 404 responses to allow HTML5 history
		historyApiFallback: true,
		port: PORT,
		host: HOST
	},
	plugins: [
		new webpack.DefinePlugin({
			NODE_ENV: JSON.stringify(NODE_ENV)
		}),
		new webpack.NoErrorsPlugin(),
		new webpack.HotModuleReplacementPlugin(),
		new HtmlWebpackPlugin({
			template: './src/template.html'
		}),
	]
};
```
And webpack loaders:
```javascript
module.exports = [
	{
		test: /\.jsx?$/,
		exclude: /(node_modules|bower_components|public)/,
		loader: "babel"
	},
	{
		test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
		exclude: /(node_modules|bower_components)/,
		loader: "file"
	},
	{
		test: /\.(woff|woff2)$/,
		exclude: /(node_modules|bower_components)/,
		loader: "url?prefix=font/&limit=5000"
	},
	{
		test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
		exclude: /(node_modules|bower_components)/,
		loader: "url?limit=10000&mimetype=application/octet-stream"
	},
	{
		test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
		exclude: /(node_modules|bower_components)/,
		loader: "url?limit=10000&mimetype=image/svg+xml"
	},
	{
		test: /\.gif/,
		exclude: /(node_modules|bower_components)/,
		loader: "url-loader?limit=10000&mimetype=image/gif"
	},
	{
		test: /\.jpg/,
		exclude: /(node_modules|bower_components)/,
		loader: "url-loader?limit=10000&mimetype=image/jpg"
	},
	{
		test: /\.png/,
		exclude: /(node_modules|bower_components)/,
		loader: "url-loader?limit=10000&mimetype=image/png"
	}
];
```

**Comment by notacouch** [comment]
Thanks for providing those files, with that I was able to get amCharts 4 to transpile, basically just had to exclude it from the exclusions.

The next issue after that was dealing with dynamic imports (`import()`), which we use mainly for Export-related features.

I've thrown together what's working for those files (and 2 demo files) for me in a gist:
https://gist.github.com/notacouch/8745d78bd88a67c387669da405857837

First thing's first is excluding amCharts 4 package from exclusions in your loaders file:
https://gist.github.com/notacouch/8745d78bd88a67c387669da405857837#file-webpack-loaders-js-L4

```javascript
  {
    test: /\.jsx?$/,
    exclude: function(modulePath) {
      // use function notation for readability and cross-platform (path) compatibility
      return (
        (/node_modules/.test(modulePath) && !/amcharts4/.test(modulePath)) || // Don't transpile npm packages unless it's amcharts4
        /bower_components/.test(modulePath) ||
        /public/.test(modulePath)
      );
    },
    loader: "babel-loader",
    query: {
      presets: ["react", "es2015"], // needed for JSX and ES6
      plugins: ["dynamic-import-webpack"] // needed for converting dynamic `import()`s to `require.ensure` for Webpack 1.
    }
  },
```

I use the function notation for `exclude` so it's easier to tell what's going on there, basically exclude all npm packages except for `amcharts4`. 

The next difference is it's better to use `"babel-loader"` instead of `"babel"` so the proper files are loaded, it looks like it's an official change as of Webpack 2. There's no difference in this case, just giving a heads up.

Next is I had to provide the environment presets for both react and es6, otherwise it would snag on es modules and JSX. (I'm not really sure where `babel-polyfill` was supposed to do anything if at all.)

Last but not least, notice the addition of a plugin. In Webpack 1 it doesn't really know what to do when it comes across `import(...)`. Airbnb made some plugins to interpret that for node environment as well as for webpack:
https://github.com/airbnb/babel-plugin-dynamic-import-webpack

Install it via:
```shell
npm install babel-plugin-dynamic-import-webpack --save-dev
```

This will now convert `import()` calls to `require.ensure()` calls for Webpack. Webpack 1 will then create multiple #.bundle.js files to be pulled in dynamically as-needed. However, a path needs to be provided to construct an URL for these, otherwise the request for these files may be incorrectly constructed e.g. requesting them in the root or current depth of navigation. 

To fix that, in webpack.config.js, we add a `publicPath` property:
https://gist.github.com/notacouch/8745d78bd88a67c387669da405857837#file-webpack-config-js-L51

```javascript
  output: {
    path: path.join(__dirname, "public"),
    publicPath: "./public/", // adjust this, affects the URL to find #.bundle.js files in lieu of dynamic `import()`
    filename: "bundle.js"
  },
```

Now in my local demo it grabs the right file, in the right place, at the right time.

I definitely recommend upgrading Webpack when you have the opportunity. When it comes to handling dynamic `import()`, each version's documentation on Code Splitting will mention compatibility and strategies. E.g. v1:
https://devdocs.io/webpack~1/code-splitting

and v4:
https://webpack.js.org/guides/code-splitting/

v4 has various features for dynamic imports, e.g. we provide webpack chunk names, so you won't be left with #.bundle.js files, but named files instead.

If you decide to give amCharts 4 a shot again (it's pretty prime time ready), let us know if the above makes sense.

**Comment by igoriok1994** [comment]
Thank you for so fast response. 
I'll try to fix all these issues and definitely will test amCharts4.
About upgrading Webpack, yes it will be updated later (now just don't have possibility to do it).
By the way does amCharts4 have export plugin? Or some tools (like amCharts3, eg. autoOffsetAxis)

**Comment by notacouch** [comment]
You're welcome!

Yeah I figure upgrading Webpack is something that may take some time and testing, you'd wanna do it right afterall. At least we got things working for version 1.

Yes, there's an export plugin in amCharts4! Well, instead of plugin, v4 supports it out-of-the-box!

You can enable the full export menu by simply adding this to your code:
```javascript
chart.exporting.menu = new am4core.ExportMenu();
```

By default it appears in the top right of the chart:
![image](https://user-images.githubusercontent.com/2334143/46892949-34440500-ce3d-11e8-811d-1ee5a855b105.png)

Here's the guide on Exporting in v4, it also shows how to customize the layout, menu options, styles, etc. and even how to export via API:
https://www.amcharts.com/docs/v4/concepts/exporting/

By the way, [I made sure to test dynamic `import` support](https://gist.github.com/notacouch/8745d78bd88a67c387669da405857837#file-index_in_src_directory-jsx-L40) in my sample by making a chart with an export button, then exporting to PDF (can see in devtools' network tab it downloads more #.bundle.js files). So at least locally for me I was able to confirm everything working properly.

As for tools, there are not any at this time, as you can see with the example of Export, v4 is very powerful and you may not find a need for tools. With v4, multiple axes do not overlap and arrange themselves accordingly even with their own title, check out this quick demo I whipped up:
https://codepen.io/team/amcharts/pen/2818ad465e3dfd1b02c97f0f1e8a3948

Screenshot:
![image](https://user-images.githubusercontent.com/2334143/46895350-fdbeb800-ce45-11e8-864d-922296b3a661.png)

**Comment by igoriok1994** [comment]
That's pretty cool. New version supports a lot of features out of the box.
Thank you for help :))

**Comment by notacouch** [comment]
Yeah to think v4 is still in public preview! Which means there's more to come =D 
You're welcome!
