### ISSUE TITLE
Vertical clustered ColumnSeries' bullets are centered within category, not the bar/column

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#455]
Hello,

The label bullets positioning is not proper in the following pen:

https://codepen.io/vaish1906/pen/QZvVrN?editors=0010

**Comment by martynasma** [comment]
Thanks for the heads up. We'll be fixing it.

![image](https://user-images.githubusercontent.com/1458520/46868750-0c02d900-ce32-11e8-9a92-8cb5d1498085.png)

Simplified demo for dev purposes:
https://codepen.io/team/amcharts/pen/f7395641de9a47e966cc18a356652696/

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.58](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.58).

## [4.0.0-beta.58] - 2018-10-17

### Added
- `ExportMenu`'s "custom" items can now have `"callback"` which is a function to call when clicked on such custom item.

### Changed
- Slice labels on a `PieChart` now move with the slice (if `alignLables = false`).

### Fixed
- `requestAnimationFrame` now is called only when needed. This reduces idle CPU usage.
- Fixed `m4core.color()` result caching issue.
- Charts were broken in IEs since beta.57.
- `Tooltip` on `LineSeries` was not updating color if segment changed color.
- `MapChart` without any series was displaying an error in console.
- Axis tooltip was trimmed when `renderer.inside = true`.
- `StepLineSeries` `startLocation`/`endLocation` bug fixed.
- `"hover"` state was not being applied to series' bullet if it did not hav `tooltipText` set.
- `bulletLocation` for horizontal `ColumnSeries` fixed.
- Value labels of `Legend` were not in correct positions if `Legend` was positioned at the top or bottom (too close to legend label).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
