### ISSUE TITLE
Clear all data

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#458]
Hello,

Is there a way to clear all data in a chart ?

```javascript

chart.data = []

```
https://codepen.io/ptorrent/pen/JmyQJg

When you press previous  then next, old data are still there.

Thanks for support

**Comment by martynasma** [comment]
Is there a reason why you want to reset data, then add individual data points one by one using `addData()` rather than adding them to an array and setting `data` in one go?

**Comment by ptorrent** [comment]
I've a date picker and I receive data in asynchronous way. 

So when user change start/end date, I've to redefine min/max of dateAxis. Then I've to add data asynchronously to serie (but before it, I've to reset data of the serie). 

Does it make sense?

**Comment by martynasma** [comment]
It does. Thanks for the explanation.

OK, yeah I can see now. Looks like setting `data` to `[]` does not fully reset the data.

Marking this as a bug. Thanks!

**Comment by martynasma** [comment]
Our copy which shows the issue more prominently:
https://codepen.io/team/amcharts/pen/bmobRd?editors=0010

**Comment by ptorrent** [comment]
Thanks !

**Comment by zeroin** [comment]
This issue was fixed in v 64 beta.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.64](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.64).

## [4.0.0-beta.64] - 2018-10-27

### Added
- `shouldClone` flag added to `EventDispatcher`'s `on` and `once` methods. Can be used to restrict cloning of events when object itself is cloned.
- [`showOnInit`](https://www.amcharts.com/docs/v4/reference/sprite/#showOnInit_property) property added to `Sprite`. If this is set to `true`, the `Sprite`, when inited will be instantly hidden ("hidden" state applied) and then shown (animate properties form "hidden" state to "default" state). Animation will take `defaultState.transitionDuration`. `Series`, `Chart` classes has this set to `true`, so that they would perform initial animations. If you want a sprite (chart, series) not to be shown initially, you can set Sprite's [`hidden`](https://www.amcharts.com/docs/v4/reference/sprite/#hidden_property) to `true`. (`setting sprite.visible = true` won't work as expected anymore).

### Changed
- If chart rendering takes too long, it now is split into chunks, which makes the browser/page remain responsive even if you have a lot of charts to build.
- Changed how pre-hiding Series works. If you want series to be initially hidden, use `series.hidden = true` instead of `series.visible = false`.
- Removed `"hold"` and `"rotate"` interaction events and releated options and functionality, since they weren't used anywhere.
- Removed `"delayFirstHit"` option from `Sprite.hitOptions`.
- `chart.defaultState.transitionDuration` is set to `1`. This allows the chart to appear one frame after init and helps to avoid various flickers that happen while chart is building. Animated theme has this value set to `2000`.

### Fixed
- Performance enhancements.
- Non-draggable/trackable but otherwise interactive elements of the chart no longer prevent scrolling and other gestures on touch screens.
- `PieSeries` labels sometimes were positioned incorrectly (using non-default start/end angles).
- Slices (also columns of `RadarChart`) were not drawn if `radius <= 0` (even if `innerRadius > 0`). This resulted in radar columns not rendered in some cases.
- `MapChart` was not resizing properly when div size changed.
- `PictorialStackedSeries`, while `containerdiv` was resized did flicker a lot.
- If a Tooltip is visible while its Sprite changes size/position, it updates its position as well.
- Setting `chart.data = []` was not clearing data properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
