### ISSUE TITLE
PieChart overwrite legend 

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#474]
Hello,

Depending on the dimensions of the container. The graph will not have the good dimensions and will overwrite the legend (Appears only on the first call, if you resize the container the rendering will be ok)

https://codepen.io/ptorrent/pen/bmMZLZ

To solve the problem : 

```javascript
setTimeout(function(){
  document.getElementById('chartdiv').style.width = '200px'
},2000)
```

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.63](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.63).

## [4.0.0-beta.63] - 2018-10-20

### Fixed
- In some cases a `PieChart` could overlap its legend.
- `PieChart` flicker after `invalidateData` fixed.
- An error was occurring when data was updated on chart with series with bullet while hovering it with cursor.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
