### ISSUE TITLE
Dynamically changing Legend.position does not update its layout

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#477]
I am changing the position of legends, depending on the user input.
It is not updating properly, below is the url:
https://codepen.io/varshamathukumalli/pen/aRjVog?editors=1010

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.65](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.65).

## [4.0.0-beta.65] - 2018-10-28

### Changed
- `tooltip.hiddenState.transtionDuration` and `tooltip.defaultState.transitionDuration` are now set to 1 (on non-animated theme) to avoid some tooltip flickering.
- Individual legend items (label, value label, and marker) now have their  `interactionsEnabled = false` set by default to avoid double events. If you need to add events to these particular elements (as opposed to the whole legend item), you will need to set `interactionsEnabled = true` on that element.

### Fixed
- Calling `show()` on a `MapSeries` object was resulting in an error.
- 3D columns were not visible if their value was zero.
- Bullets are now hidden if `minBulletDistance` is set.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
OK, so it looks like the change now happens correctly, however layout of the legend is not updated accordingly.

Reopening this.

When moving legend to the side, it should go from horizontal to vertical layout, but it seems it doesn't.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.70](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.70).

## [4.0.0-beta.70] - 2018-10-31

### Fixed
- Keyboard dragging of elements such as scrollbar grips was not working.
- "hoverable" elements were not staying "hovered" after tap in Mobile Safari.
- `addData()` with more than one data item added was not working well.
- Zoomout button was visible on initial animation.
- Dynamically changing `Legend.position` was not updating its layout properly.
- Vertical axis tick position with rotated labels was incorrect.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
