### ISSUE TITLE
Error on js if chart element disappear on page

### ISSUE THREAD

**Issue by evazzadeh** [amcharts/amcharts4#48]
We use js pushState for navigate on our service pages and after migrate to v4 have error if chart element is removed from page. We don't have this error with v3. It's weird, because sometimes occur 14, sometimes 143 times!
`Error: <path> attribute d: Expected number, "MNaN,0 LNaN,0 LNa…".`

```

t.attr | @ | amcharts4.min.js:20
  | e.draw | @ | amcharts4.min.js:20
  | e.validate | @ | amcharts4.min.js:20
  | t.update | @ | amcharts4.min.js:20
  | (anonymous) | @ | amcharts4.min.js:20
  | requestAnimationFrame (async) |   |  
  | l | @ | amcharts4.min.js:20
  | t.update | @ | amcharts4.min.js:20
  | (anonymous) | @ | amcharts4.min.js:20
  | requestAnimationFrame (async) |   |  
  | l | @ | amcharts4.min.js:20
  | t.update | @ | amcharts4.min.js:20
  | (anonymous) | @ | amcharts4.min.js:20
  | requestAnimationFrame (async) |   |  
  | l | @ | amcharts4.min.js:20
  | t.update | @ | amcharts4.min.js:20
  | (anonymous) | @ | amcharts4.min.js:20
  | requestAnimationFrame (async) |  
...

```

Also we think render time of chart drawing increased too much!

**Comment by arm1n** [comment]
This is due to not calling `dispose()` before removing the element, whereas calling it leads to #17 and #65, so this is a big issue.

**Comment by Pauan** [comment]
@evazzadeh Have you tried calling `chart.dispose()` when the chart is removed from the page?

As @arm1n mentioned, there were some bugs that caused `chart.dispose()` to not work, but they have been fixed in the latest version.

**Comment by evazzadeh** [comment]
> @evazzadeh Have you tried calling chart.dispose() when the chart is removed from the page?

simply return on top level of chart render codes will fix this problem and work fine like v3. sometimes because of condition it's difficult to dispose old chart.

i update to beta30 and now have problem to get chart object to dispose it! how can i get chart from dom element(without global variable)?

**Comment by Pauan** [comment]
@evazzadeh With v3 you are also required to call `chart.clear()` (similar to how v4 requires you to call `chart.dispose()`). This is necessary because both v3 and v4 must remove event listeners, animation loops, etc.

I don't know what kind of routing system you are using (it sounds like a custom ad-hoc system), so it's difficult to give help. If you give more information then I can help more.

It is not possible to get the chart object from the DOM element, you must store it somewhere in JavaScript.

If you're using vanilla JavaScript then storing the chart in a global variable or some sort of state object is probably your best option.

If you're using ES6 or TypeScript then you can use a top-level variable in a module, like this:

```js
let chart = null;

export function disposeChart() {
    if (chart != null) {
        chart.dispose();
        chart = null;
    }
}

export function makeChart() {
    disposeChart();

    chart = am4core.create("chartdiv", am4charts.XYChart);

    ...
}
```

The `chart` variable isn't global, it can only be accessed inside of that module.

If you're using a framework (such as Angular, React, etc.) they provide a way to call some code when a component is disposed.

Your routing system might also let you call some code when the page is changed.

If your routing system doesn't allow you to cleanup old state (and it doesn't allow you to be notified when a page changes), then I highly suggest you fix that, since that's a basic requirement of all routing systems.

**Comment by Pauan** [comment]
Oh, I had completely forgotten: it is actually possible to avoid global variables in vanilla JavaScript:

```js
(function () {
    "use strict";

    var chart = null;

    function disposeChart() {
        if (chart != null) {
            chart.dispose();
            chart = null;
        }
    }

    function makeChart() {
        disposeChart();

        chart = am4core.create("chartdiv", am4charts.XYChart);

        ...
    }

    function onPageChange() {
        if (location.href === "/chart") {
            makeChart();

        } else {
            disposeChart();
        }
    }

    window.onpopstate = onPageChange;

    onPageChange();
})();
```

This puts all of the code inside of `(function () {})` (which is then immediately called).

This means that all variables defined inside of the function are **not** global.

Since it sounds like this issue has been resolved, I'm going to close it. If you're still having any problems, let me know and I'll reopen it.

**Comment by peluprvi** [comment]
@Pauan any news about https://github.com/amcharts/amcharts4/issues/65#issuecomment-403152111 ?
I'm asking it here because I think it's more related to this issue.
Also, to better follow the issue, is it better reopen this one or create a new one?

**Comment by peluprvi** [comment]
Since I can't use `this.chart` with this memory issue, to dispose the chart in Vue I created this workaround: https://github.com/peluprvi/vue-amcharts4-teste/commit/23a09ef6b7dc14c499b75971e72da55c04cbf859

**Comment by b49015** [comment]
Hi @peluprvi , I'm still facing the same issue. Can you please share your workaround? I think the link is broken.

**Comment by peluprvi** [comment]
@b49015 Sure! Link updated! ;)
