### ISSUE TITLE
Unexpected PieChart label placement for first/last slice

### ISSUE THREAD

**Issue by taylorehat-cs** [amcharts/amcharts4#486]
<img width="809" alt="screenshot_56" src="https://user-images.githubusercontent.com/44442112/47445051-2c595e80-d775-11e8-948e-b45e236c7233.png">

When the first or last slice in a pie series has a value of 0. The label is being placed unexpectedly at the bottom of the opposite side of the chart. In the case of the pictured sample, I would expect it to be the first label at aligned labels on the left of the chart.

If I adjust the startAngle/endAngle by -1 (-91/269) the first slice's label is placed at the bottom of the labels on the left of the chart.

<img width="807" alt="screenshot_57" src="https://user-images.githubusercontent.com/44442112/47445891-3a0fe380-d777-11e8-8f14-be8459b4b7c7.png">

Here is the working codepen: https://codepen.io/taylor-cs/pen/aREXLB

A side question would be is there a way to simply hide labels for 0 value slices?

**Comment by martynasma** [comment]
Indeed weird :)

Thanks for the heads up. We'll see what we can do about it.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.64](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.64).

## [4.0.0-beta.64] - 2018-10-27

### Added
- `shouldClone` flag added to `EventDispatcher`'s `on` and `once` methods. Can be used to restrict cloning of events when object itself is cloned.
- [`showOnInit`](https://www.amcharts.com/docs/v4/reference/sprite/#showOnInit_property) property added to `Sprite`. If this is set to `true`, the `Sprite`, when inited will be instantly hidden ("hidden" state applied) and then shown (animate properties form "hidden" state to "default" state). Animation will take `defaultState.transitionDuration`. `Series`, `Chart` classes has this set to `true`, so that they would perform initial animations. If you want a sprite (chart, series) not to be shown initially, you can set Sprite's [`hidden`](https://www.amcharts.com/docs/v4/reference/sprite/#hidden_property) to `true`. (`setting sprite.visible = true` won't work as expected anymore).

### Changed
- If chart rendering takes too long, it now is split into chunks, which makes the browser/page remain responsive even if you have a lot of charts to build.
- Changed how pre-hiding Series works. If you want series to be initially hidden, use `series.hidden = true` instead of `series.visible = false`.
- Removed `"hold"` and `"rotate"` interaction events and releated options and functionality, since they weren't used anywhere.
- Removed `"delayFirstHit"` option from `Sprite.hitOptions`.
- `chart.defaultState.transitionDuration` is set to `1`. This allows the chart to appear one frame after init and helps to avoid various flickers that happen while chart is building. Animated theme has this value set to `2000`.

### Fixed
- Performance enhancements.
- Non-draggable/trackable but otherwise interactive elements of the chart no longer prevent scrolling and other gestures on touch screens.
- `PieSeries` labels sometimes were positioned incorrectly (using non-default start/end angles).
- Slices (also columns of `RadarChart`) were not drawn if `radius <= 0` (even if `innerRadius > 0`). This resulted in radar columns not rendered in some cases.
- `MapChart` was not resizing properly when div size changed.
- `PictorialStackedSeries`, while `containerdiv` was resized did flicker a lot.
- If a Tooltip is visible while its Sprite changes size/position, it updates its position as well.
- Setting `chart.data = []` was not clearing data properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Regarding pre-hiding zero slices. There's currently no such feature.

You can set your chart slices to pre-hide using data:

https://www.amcharts.com/docs/v4/tutorials/pre-hiding-pie-chart-slices/

I suppose you can do that automatically via `"data"` adapter as well. Let me know if you need help with that.
