### ISSUE TITLE
Heat Map with DateAxis

### ISSUE THREAD

**Issue by pouretrebelle** [amcharts/amcharts4#488]
Hello, I'm building a heat map but want to format the axis differently (I get the y-axis data as '12:34:00' when I want it to say '12pm'). Changing to `DateAxis` from `CategoryAxis` make the axis label format correctly but the data in the `ColumnSeries` is messed up. [Here's a Codepen demo](https://codepen.io/pouretrebelle/pen/ad288f9c98913aafd80e51a404ddecd7/?editors=0010) that shows the problem.

Do I have to change it to a `LineSeries` and use bullets to show the data? Or is there a way to use the date formatter on a `CategoryAxis`?

**Comment by xorspark** [comment]
If you're using a date axis instead of a category axis for your segments, you might want to take the same approach as our [Gantt chart](https://codepen.io/team/amcharts/pen/qxzvxe) and specify an `openDateY` (cell start date) in addition to a `dateY` for each cell in your heat map and adjust your data accordingly to make it work, for example:

```
yAxis.dataFields.openDateY = "fromHour"; //cell starts from this timestamp
yAxis.dataFields.dateY = "hour";  //ends at this timestamp
yAxis.baseInterval = {count: 1, timeUnit: "hour"};
// ...
series.dataFields.openDateY = "fromHour";
// ...
chart.data = [
  { hour: "12AM", weekday: "Sun", value: 2990, fromHour: "11PM" },
  { hour: "1AM", weekday: "Sun", value: 2520, fromHour: "12AM" },
  // ... etc
];
```

[Updated codepen](https://codepen.io/team/amcharts/pen/7d06fee289b499cdacb87b9511489fe0/?editors=0010).

**Comment by pouretrebelle** [comment]
Thank you!
