### ISSUE TITLE
Tooltip issue when Hovering bullets on Bullet Chart

### ISSUE THREAD

**Issue by wandss** [amcharts/amcharts4#498]
Hello everyone, 

First of all congratulations on the amazing job with amcharts4. 
I've implemented a Bubble chart, exactly like the sample at codepen here: https://codepen.io/team/amcharts/pen/rvzKLE

Just like the sample above, when hovering bullets, the tooltip appears for a fraction of second.
Is this happening only with me?

Best regards,

**Comment by martynasma** [comment]
Thanks for the heads up.

Looks like the issue was introduced in the most recent version.

We'll let you know when the fix is available.

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify here when that happens.

**Comment by wandss** [comment]
> This issue was fixed in dev version, and will be released soon.
> 
> We'll notify here when that happens.
Great!
Please let me know if I can help testing or something.

Regards,

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.67](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.67).

## [4.0.0-beta.67] - 2018-10-29

### Fixed
- Chart `Cursor` was preventing hovers on series' elements like columns or bullets.
- Mouse cursor's down styles (like on scrollbar) were not being reset back properly in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
