### ISSUE TITLE
Category Axis Start / End Issues

### ISSUE THREAD

**Issue by kylekarpack** [amcharts/amcharts4#500]
If a category axis has a start index that is higher than the length of a new data set, the series processValues function exhibits error behavior when the chart is setting new data.

Example here: https://codepen.io/anon/pen/oaOPYa

The only way around this that I have found is to directly modify the _workingStartIndex and _workingEndIndex of each series on the chart before setting new data

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.69](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.69).

## [4.0.0-beta.69] - 2018-10-30

### Fixed
- Some charts were not properly displayed if initialized in a hidden (`display: none`) container, then revealed (`display: block`).
- Last slice of the `PyramidSeries` was not visible for certain widths.
- Adding `Legend` to a chart that had series with bullets using heatrules was causing an error.
- Label rotation was being ignored on `SlicedChart`.
- Labels of `PyramidSeries` were not centered (when `alignLabels = false`).
- Animation of labels for horizontal `PictorialSeries` was very jumpy.
- `position` and `rotation` of labels in `PyramidSeries` was not working properly.
- An error was occurring if chart's with a category axis data was updated and it contained less data points than before.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
