### ISSUE TITLE
Position and Rotation of Labels in Pyramid Series not working

### ISSUE THREAD

**Issue by VaishnaviAppannagari** [amcharts/amcharts4#501]
Hello,

I am trying to position my labels inside the slices in the pyramid series. But I am unable to achieve this by setting alingnLabels to false and providing radius. I could achieve the same in Pie Chart whereas it is not working in the Sliced Chart.

Also, the label type is Label, whereas we are expecting AxisLabelCircular with radius property.

Also, I am unable to rotate the labels.

Can you please look into this?

CodePen:
https://codepen.io/vaish1906/pen/pxmbaz?editors=0010

**Comment by martynasma** [comment]
This might be related to #505. We're going to resolve this.

You should not need to use radius to position the labels. Pyramid chart is not circular, hence no `AxisLabelCircular`.

Not sure why the rotation of labels does not work, either. We'll need to investigate.

Here's another issue for that: #506

Also, for the future. It's extremely difficult to manage multiple, unreleated issues in a single GitHub issue, hence me posting them as separate ones, instead of using what you posted.

Please make sure you subscribe to those other issues, to be informed about the progress.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.69](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.69).

## [4.0.0-beta.69] - 2018-10-30

### Fixed
- Some charts were not properly displayed if initialized in a hidden (`display: none`) container, then revealed (`display: block`).
- Last slice of the `PyramidSeries` was not visible for certain widths.
- Adding `Legend` to a chart that had series with bullets using heatrules was causing an error.
- Label rotation was being ignored on `SlicedChart`.
- Labels of `PyramidSeries` were not centered (when `alignLabels = false`).
- Animation of labels for horizontal `PictorialSeries` was very jumpy.
- `position` and `rotation` of labels in `PyramidSeries` was not working properly.
- An error was occurring if chart's with a category axis data was updated and it contained less data points than before.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
