### ISSUE TITLE
Adding Legend to bubble chart causes error

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#507]
Example: 
https://codepen.io/dmsmaxim/pen/YJbYmm

This is example from your documentation (https://codepen.io/team/amcharts/pen/rvzKLE).
I just added `chart.legend = new am4charts.Legend();`, and here it is:
![image](https://user-images.githubusercontent.com/15041200/47718548-6208b680-dc51-11e8-84ae-fef298e19258.png)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.69](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.69).

## [4.0.0-beta.69] - 2018-10-30

### Fixed
- Some charts were not properly displayed if initialized in a hidden (`display: none`) container, then revealed (`display: block`).
- Last slice of the `PyramidSeries` was not visible for certain widths.
- Adding `Legend` to a chart that had series with bullets using heatrules was causing an error.
- Label rotation was being ignored on `SlicedChart`.
- Labels of `PyramidSeries` were not centered (when `alignLabels = false`).
- Animation of labels for horizontal `PictorialSeries` was very jumpy.
- `position` and `rotation` of labels in `PyramidSeries` was not working properly.
- An error was occurring if chart's with a category axis data was updated and it contained less data points than before.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
