### ISSUE TITLE
Tooltips not working with LineSeries

### ISSUE THREAD

**Issue by Ekliptor** [amcharts/amcharts4#51]
Version: AmCharts 4.0.0-beta.24 from NPM

I am using the same line chart code as in my previous bug report: https://github.com/amcharts/amcharts4/issues/38

I added tooltips by adding 2 lines at the end:
```
        series2.columns.template.tooltipText = "Series: {name}\nFoo some more...";
        series2.columns.template.fill = am4core.color("#104547"); // fill
```

This gives me the following error:
```
amcharts.js:114 Uncaught TypeError: Cannot read property 'template' of undefined
    at AmHelperClass.plotLineChart (amcharts.js:114)
    at index.js:11
```

The same error occurs with beta25.
(Also your Codepen sample in the other bug report is not working anymore, but I assume that's because you are working on it.)

**Comment by martynasma** [comment]
The example is not working because there was a lose Axis object being created `let x = new am4charts.CategoryAxis();`, not entirely sure why that could cause breakdown, but nevertheless my example is back up when I remove that line.

As for your question, you're not using it right. `LineSeries`, does not have `columns` property, only `ColumnSeries` does. (and other series that extends it)

If you need any meaningful hover tooltips on a `LineSeries`, you probably need to use bullets, then set `tooltipText` on those bullets.

Take a look at this article:
https://www.amcharts.com/docs/v4/concepts/bullets/

Another alternative is to enable chart Cursor, so you can set `tooltipText` directly on series, and have it displayed when you are gliding over chart with a cursor, even without directly hovering over bullet/line:

https://www.amcharts.com/docs/v4/concepts/chart-cursor/

Hope that all makes sense.

**Comment by martynasma** [comment]
P.S. fixed the "stray" axis error in dev version. Will be rolled into the next official beta.

**Comment by Ekliptor** [comment]
Thx for the clarification. Chart Cursors sounds like an interesting concept. I will look into it.

**Comment by setiawans** [comment]
@martynasma can we make individual hover for each lineSeries? the cursor is hovering for all lineSeries so the tooltips is showing together. i want a hover then only one tooltip can be show.

with implement these
https://www.amcharts.com/docs/v4/concepts/bullets/
https://www.amcharts.com/docs/v4/concepts/chart-cursor/

please help me
