### ISSUE TITLE
Bar Chart Label Bullet Elipses Get Stuck

### ISSUE THREAD

**Issue by kylekarpack** [amcharts/amcharts4#510]
When zooming a chart with a scrollbar, label bullets are using elipses even when no longer needed:

![image](https://user-images.githubusercontent.com/2429580/47807074-6e941a00-dcf8-11e8-82bb-4a9a20f38792.png)

Example:

https://codepen.io/anon/pen/NOZQKo

(Drag the scrollbarX to zoom the chart a little after it initializes)

**Comment by martynasma** [comment]
Thanks for the headsup!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.82](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.82).

## [4.0.0-beta.82] - 2018-11-14

### Added
- JSON: `forceCreate` property added. If found in an item of an array, it will force creation of the new object, even if object with same index already exists in target `List`.
- French locale.

### Changed
- Adjusted animation durations in "animated" theme.

### Fixed
- JSON: String-based percent and color values were not being parsed correctly in some cases.
- JSON: `HeatLegend` was erroring if its `series` property was referencing to Series by id.
- Disposing an item with a custom `id` set was not clearing it from id map properly resulting in errors if item with the same id was being added later.
- `SankeyDiagram` was not taking chart's padding into account when sizing itself.
- Axis ticks were not being positioned properly after data update.
- Map using `deltaLongitude` was being positioned incorrectly.
- 3D columns z-indexing was sometimes incorrect.
- `PieChart` label placement with custom `startAngle`/`endAngle` was sometimes off.
- Label bullets on columns were not being restored from truncated state when width of the columns was increasing.
- Series `show()`/`hide()` were using `interpolationDuration` setting instead of `defaultState`/`hiddenState` transition duration when showing/hiding.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
