### ISSUE TITLE
TreeMap dispose() error

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#511]
Example: 
https://codepen.io/dmsmaxim/pen/XxvJRj

After 3s I call `chart.dispose();`.
Error in the console:
![image](https://user-images.githubusercontent.com/15041200/47812689-c01cc300-dd51-11e8-9b27-900609cd0bf3.png)

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.71](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.71).

## [4.0.0-beta.71] - 2018-11-01

- Calling `dispose()` on a `TreeMap` was causing an error.
- Legend items were being duplicated every time its disabled property was reset back to `false`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
