### ISSUE TITLE
Series combines own `data` with chart's `data`

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#517]
After changing from beta.63 I saw that having 2 LineSeries with dataFields.valueY (dataFields.dateX) with same "name" will overlap those series output.

See code pen bellow.
https://codepen.io/aniov/pen/NEKveV?editors=0010

**Comment by martynasma** [comment]
Yes, it seems that series with own `data` set still draws data from chart's `data`.

Marking this as a bug.

Thanks for the heads up!

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.73](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.73).

## [4.0.0-beta.73] - 2018-11-07

### Changed
- `axisFills.template.interactionsEnabled` is now set to `false` by default. If you need to attach events on an axis fill, you will need to set it to `true`.

### Added
- `autoDispose` property added to `Series` and `Axis` classes with default value `true`. This means that series/axis will be automatically disposed when removed from chart's `series`, `xAxes`, or `yAxes` lists.
- It is now possible to have 3D stacked columns (by setting `clustered = false` on series).

### Fixed
- If chart container was moved in DOM tree, it stopped sensing resize and was not updating its size anymore.
- Sometimes `ValueAxis` could show zero label with a minus sign.
- Arrows on `MapLine` were not drawn.
- It was not possible to change the text color of the tooltip on `TreeMap` diagram.
- `axis.tooltipPosition = "pointer"` was not working as it should - always follow the mouse/pointer.
- If series had `data` set directly, it was still using chart's global `data`, resulting in combined datasets and potentially visual anomalies.
- Setting `cellStartLocation` did not have any effect on an already inited chart.
- Line series could be cut off in the beginning (when zoomed-in closely).
- Vertical axis ticks were not being positioned properly if axis had a title.
- 3D columns were not using chart's `depth`/`angle`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
