### ISSUE TITLE
Clear is not working

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#519]
Hi,

i am changing the chart whenever the data format is changed.
Instead of instantiating the chart again, i want to use the existing object by clearing all the previously created axes and series as below and creating them again.
chart.yAxes.clear();
chart.xAxes.clear();
chart.series.clear();

But the axes are creating multiple times as in the below codepen
https://codepen.io/varshamathukumalli/pen/qQWxwL?editors=1010

**Comment by martynasma** [comment]
Thanks for the heads up!

**Comment by Varshamathukumalli** [comment]
This is failing when multiple axes are available. Below is the code pen, click on recreate button, in the console you will get duplicate id error
https://codepen.io/varshamathukumalli/pen/KrMpMv?editors=0010

**Comment by Varshamathukumalli** [comment]
Guys, is there any update on this?

**Comment by martynasma** [comment]
This has just been fixed in dev and will be released later today or tomorrow.

There is one issue with your code as well, though.

You are clearing value axes, but not your `valueAxes` array. When series are re-created they are assigned old disposed value axes from that array, causing errors.

You should reset that array when clearing axes as well:

```
valueAxes = [];
```

I'll ping you once more when the version with a fix is released.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.82](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.82).

## [4.0.0-beta.82] - 2018-11-14

### Added
- JSON: `forceCreate` property added. If found in an item of an array, it will force creation of the new object, even if object with same index already exists in target `List`.
- French locale.

### Changed
- Adjusted animation durations in "animated" theme.

### Fixed
- JSON: String-based percent and color values were not being parsed correctly in some cases.
- JSON: `HeatLegend` was erroring if its `series` property was referencing to Series by id.
- Disposing an item with a custom `id` set was not clearing it from id map properly resulting in errors if item with the same id was being added later.
- `SankeyDiagram` was not taking chart's padding into account when sizing itself.
- Axis ticks were not being positioned properly after data update.
- Map using `deltaLongitude` was being positioned incorrectly.
- 3D columns z-indexing was sometimes incorrect.
- `PieChart` label placement with custom `startAngle`/`endAngle` was sometimes off.
- Label bullets on columns were not being restored from truncated state when width of the columns was increasing.
- Series `show()`/`hide()` were using `interpolationDuration` setting instead of `defaultState`/`hiddenState` transition duration when showing/hiding.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
