### ISSUE TITLE
treemap tooltip percetage value?

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#544]
Hi,

I am trying to customize the tooltipText of treeMap, I am able to change the text by using tooltipText, however it only accepts {name} {value}, I cannot use {value.percents} to show the percentage value of each item. Is it possible to accomplish this without adding percentage value to the original dataset?
Thanks,

Lucas

**Comment by martynasma** [comment]
Next release will support `{percent}` tag in `tooltipText`.

We'll ping you once more when the new version is out.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.75](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.75).

## [4.0.0-beta.75] - 2018-11-10

### Added
- You can now use `"{percent}"` placeholder in `tooltipText` of `HeatMapSeries` items.

### Fixed
- Draggable/trackable areas of the chart were intercepting all mouse buttons, including right and back/forward.
- Fixed `MapChart` issue with dragging map by touch on hybrid devices.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
