### ISSUE TITLE
Rendering arrows when the source and destination is the same results in an error

### ISSUE THREAD

**Issue by garunski** [amcharts/amcharts4#553]
[example](https://codepen.io/anon/pen/LXbmXj)

In the `lineSeries.data` array there is a multiGeoLine that has the same starting and ending point. When adding the Arrow rendering code, there is a `Cannot read property 'x' of undefined` error that is displayed. Without rendering the Arrow, the map works as expected.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.80](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.80).

## [4.0.0-beta.80] - 2018-11-13

### Fixed
- Legend in external container was resulting in infinite loop.
- Rendering an arrow on a `MapLine` with same source and destination point was resulting in error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
