### ISSUE TITLE
Recent change to Pie Chart legend?

### ISSUE THREAD

**Issue by taylorehat-cs** [amcharts/amcharts4#554]
We have a test pie chart with a legend in a separate container using this method (https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/)

It seems to causing an infinite loop.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.80](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.80).

## [4.0.0-beta.80] - 2018-11-13

### Fixed
- Legend in external container was resulting in infinite loop.
- Rendering an arrow on a `MapLine` with same source and destination point was resulting in error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
