### ISSUE TITLE
Max height is not respected for vertical chart x-axis

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#564]
Hi,

Maxheight for x-axis is not respecting. Below is the codepen url:
https://codepen.io/varshamathukumalli/pen/KrmaLv?editors=0010

**Comment by martynasma** [comment]
I did try changing `maxHeight` setting in your chart. It does take. Can you double check if it's indeed still the issue on your end?

![image](https://user-images.githubusercontent.com/1458520/48573044-cd21e080-e913-11e8-8eeb-c84e1703681c.png)

![image](https://user-images.githubusercontent.com/1458520/48573063-d9a63900-e913-11e8-87aa-b7e13aea1b55.png)

![image](https://user-images.githubusercontent.com/1458520/48573084-e7f45500-e913-11e8-9ca2-684bc4833d20.png)

**Comment by martynasma** [comment]
Gotcha.

OK, so I know what's going on. Labels truncate based on `maxWidth`. Since you set `maxHeight` for the axis, it translates to `maxHeight` on labels as well, which does not influence truncation.

Save for us trying to implement some kind of fuzzy logic for truncation which would take both `maxWidth` and `maxHeight` into account, the easy workaround is to set `maxWidth` for the labels to the same number as for the axis:

```
  categoryAxis.renderer.maxHeight = 50;
  categoryAxis.renderer.labels.template.truncate = true;
  categoryAxis.renderer.labels.template.rotation = 90;
  categoryAxis.renderer.labels.template.maxWidth = categoryAxis.renderer.maxHeight;
```

This should do the trick.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
