### ISSUE TITLE
Dynamic update of chart properties is not working for some chart properties

### ISSUE THREAD

**Issue by ysreddy99** [amcharts/amcharts4#570]
Hello,

Some of the chart properties are not working while updating them dynamically. Could you please look into it.

Please find the attached codepen for the details.
https://codepen.io/ysreddy/pen/WYRezr?editors=1010

**Comment by martynasma** [comment]
OK, so out of your button list I found that these do not work:

1) Left-aligning category axis title;
2) Moving X axis labels back outside.

The first one won't work because axis titles are automatically centered.

If you would like to put a label aligned left to the chart, you might need to add it as a regular label, not as axis title.

https://www.amcharts.com/docs/v4/tutorials/adding-chart-titles-and-bottom-text/
https://www.amcharts.com/docs/v4/tutorials/placing-labels-anywhere-on-the-chart/

The second one, not sure why it happens. Must be a bug.

Did I miss anything else?

**Comment by ysreddy99** [comment]
Why first one is not a bug?. It is working fine when we directly use it while rendering the chart , Issue comes only when we try to update the property dynamically.

What about the remaining issues like background colour issue and axis labels position issue?

**Comment by martynasma** [comment]
Yes, my bad. I suppose setting `align` on chart title should work at any time.

We're going to look into these and other issues.

Thanks.

**Comment by martynasma** [comment]
Fixed in [4.0.4](https://github.com/amcharts/amcharts4/releases/tag/4.0.4).

## [4.0.4] - 2018-12-03

### Added
- `zoomLevel` and `zoomGeoPoint` properties added to `MapSeriesDataItem` and `IMapSeriesDataFields`. If set, these settings instead of automatically-calculated will be used when `zoomToMapObject()` method is invoked.

### Changed
- `verticalCenter` and `horizontalCenter` is no longer applied to rotated axis labels. If you are setting `rotation` on axis labels, make sure to adjust these settings as well as per your requirement.

### Fixed
- Setting `axis.renderer.inside` was ignored if set after chart was already initialized.
- Changing `align` of the a sprite was ignored if set after it was already initialized.
- Top level `TreeMap` segment tooltip was positioned incorrectly after drilling down and back up.
- `min`/`max` of `ValueAxis` was not being updated after `invalidateRawData()` call, and series were stacked.
- Tooltip sometimes was pointing outside chart container.
- `ChordLink` bullets were not properly positioned on init.
- `DateAxis` was not working well if `baseInterval.count > 1`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
