### ISSUE TITLE
Label "fullWords" is just for "truncate", is there a way to do the same thing with "wrap"?

### ISSUE THREAD

**Issue by elderalves** [amcharts/amcharts4#576]
I have this chart.
<img width="662" alt="screen shot 2018-11-19 at 1 26 02 pm" src="https://user-images.githubusercontent.com/4759623/48716636-e6ba7500-ebfe-11e8-99aa-e8b41df915c3.png">

the texts have a crazy break like. In the documentation the property `fullWords` helps using `truncate`.
How to break a line for a full word using `wrap`?

Documentation for `fullWords` says:
`If truncate is enabled, should Label try to break only on full words (true), or whenever needed, including middle of the word. (false)`

**Comment by martynasma** [comment]
Um, that does not seem right. It should not break words when breaking lines. It's a bug.

Will let you know when a fix is available.

Thanks for the heads up!

Example for testing:
https://codepen.io/team/amcharts/pen/136765571f269974a96a9b34c331cb00?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.85](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.85).

## [4.0.0-beta.85] - 2018-11-20

### Added
- `"ready"` event added to `Sprite`. Sprite fires it right after `"init"` event. `Container` fires it when all of its children are ready.
- `system.isPaused` property added. Setting it to `true` will effectively pause any chart activity, making them completely static.
- `ErrorBullet` class added. Allows drawing error charts. (Check `error-chart` and `xy-error-chart` examples for code samples)
- JSON: String-based `cursorOverStyle` and `cursorDownStyle` are not supported.

### Fixed
- JSON: Setting `ColorSet` properties `baseColor` or `list`  was not working properly.
- Accessibility: Legend item was not properly referring to a Series via `labelled-by`.
- `Label.wrap` was breaking lines mid-word even if there where words that would fit into alotted space.
- Memory leak fixed.
- Sometimes `Animation` was not firing `"animationended"` event (when elastic easing was used).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
