### ISSUE TITLE
How to change the background height

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#586]
Hi,

For every element, a rectangle is added for background-fill and it is having some height.
How to modify that height. I have tried background.height, background.maxHeight but in vain.
Is there any way to modify that

**Comment by RobbiesCode** [comment]
Hi,

I don't believe you can change the background fill height unless you change the height of the element itself. I would not recommend doing so (unless the element itself is insignificant).

You could perhaps adjust the fill of the element using a gradient/`fillModifier` so that it looks like the background is smaller than the actual container.

Here's how to set the background fill "height" to 80px inside a 100px tall `Rectangle` container:

```
// Create a container child
var rect = container.createChild(am4core.Rectangle);
rect.width = 100;
rect.height = 100;

rect.fill = am4core.color("red");

// set fill height to 80%
var fillModifier = new am4core.LinearGradientModifier();
fillModifier.opacities = [0, 0, 1];
fillModifier.offsets = [0, 0.199, 0.2];
fillModifier.gradient.rotation = 90;
rect.fillModifier = fillModifier;
```

Codepen demo: https://codepen.io/team/amcharts/pen/9750dcd1ec73d51da724969d88b704c2/?editors=0010.

Docs: 
https://www.amcharts.com/docs/v4/concepts/svg-engine/containers/
https://www.amcharts.com/docs/v4/concepts/colors/

Hope this helps!

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
