### ISSUE TITLE
Chart doesn't apply config with some sets of data

### ISSUE THREAD

**Issue by maurycyg** [amcharts/amcharts4#592]
You can see here:
https://codepen.io/maurycyg/pen/PxRrez?editors=0010 
that the chart is rendered properly with the config provided while here: https://codepen.io/maurycyg/pen/OaQMPZ?editors=0010 
the values from config are not applied (width of the bars), chart renders with half of bar outside of view

the only difference between them is 2nd element in array where month has changed

---
not working
```
chart.data = [
  { count: 5, date: "2018-10-22T00:00:00+0000" },
  { count: 2, date: "2018-11-18T00:00:00+0000" },
  { count: null, date: "2018-12-19T00:00:00+0000" }
];
```
---
working
```
chart.data = [
  { count: 5, date: "2018-10-22T00:00:00+0000" },
  { count: 2, date: "2018-12-18T00:00:00+0000" }, 
  { count: null, date: "2018-12-19T00:00:00+0000" }
];
```

**Comment by martynasma** [comment]
Let me explain why that happens.

When you have a `DateAxis` the chart tries to intelligently guess the granularity of your data.

In first set of data, you have one data item per month, making chart assume that your chart has data granularity of 1 month.

In second set you have a two data items in the same month, which kicks the chart into "daily" mode.

DateAxis does not try to show full period, but rather actual span from the timestamp of the first data point to the timestamp of the last one.

Your first data point is on day 22 - towrads the end of the month - hence it only showing part of that months and only partial column visible.

There are a few things you can do.

If you really want month mode (one column per month), you need to ensure that your dates come at day 1, so "2018-10-01" instead of ""2018-10-22".

Or, if your data has a daily granularity, like on the second data set, but just very occasional data items, you can force particular granularity using axis' `baseInterval` property.

```
categoryAxis.baseInterval = {
  timeUnit: "day",
  count: 1
};
```

Here's more information about data granularity:
https://www.amcharts.com/docs/v4/concepts/axes/#Data_granularity

At some point in the future, we might introduce some sort of setting to always expand to full period, regardless of the timestamp of edge data items. But for now, the above two options can be used, depending on your actual requirements.

I hope this all makes sense.

**Comment by maurycyg** [comment]
That kinda makes sense, but why would it ignore settings like column width?

**Comment by martynasma** [comment]
Do you mean it's ignoring `columnWidth`? That should not be happening. Do you have an example code which shows how this particular setting is ignored?

**Comment by maurycyg** [comment]
That was my misconfiguration, closing
