### ISSUE TITLE
Support for Global Chart Language

### ISSUE THREAD

**Issue by kevin-i3** [amcharts/amcharts4#603]
Is there a way to set the Global Language Locale of a chart.

Currently we need to set the chart individually using ``` xyChart.language.locale : ... ```

Is there an api for this already or currently not?

Thanks,
Kevin

**Comment by martynasma** [comment]
Excellent question. No there's currently no way to do that.

However, we've just implemented it in dev version and will include in next version we release.

You will be able to do it like this:

```
am4core.options.defaultLocale = am4lang_LT_lt;
```

This will eliminate the need to set language for each individual chart.

Will ping you here once more when the version is released in the coming days.

**Comment by kevzlou7979** [comment]
Thanks, I will be looking forward for this feature.

**Comment by martynasma** [comment]
Fixed in [4.0.3](https://github.com/amcharts/amcharts4/releases/tag/4.0.3).

## [4.0.3] - 2018-11-30

### Added
- Ability to set default locale via `am4core.options.defaultLocale`. When set, all new charts will automatically assume that locale, freeing you from setting locale for each chart individually.
- `reverseOrder` added to `Container`. Allows reversing order of its `children`.

### Changed
- Moved `Legend` of a `MapChart` from `chartAndLegendContainer` to `chartContainer`. In order to position legend on map chart, use `legend.align` / `legend.valign` properties.
- Default value of `showOnInit` on any `Series` is now `false`. Except if you are using "animated" theme, which sets it to `true` by default.

### Fixed
- JSON: Using `type: "Sprite"` in JSON config was not creating elements properly.
- Initial chart rendering optimized Charts should build faster.
- Some more performance optimizations.
- Setting `hiddenInLegend` on `Series` after chart was already built had no effect.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by kevzlou7979** [comment]
Working as expected :) Thanks for the quick release
