### ISSUE TITLE
PieChart slice color change doesn't have animation

### ISSUE THREAD

**Issue by rocos-david** [amcharts/amcharts4#605]
I am changing the color of a slice in a PieChart dynamically when the value of a data item gets over a specific value.  The dataset is being updated on the fly and calling invalidateRawData(). The animation works automatically for the size of the slice  but it doesn't automatically interpolate the color from the one color to the other.

I am changing the slice fill colour using pieSeries.slices.values[0].fill    

The animation does work however if I explicitly call animate on the specific slice for the property 'fill' and provide it a 'to' color.  It just doesn't work automatically with the default animation theme.  Is there a setting perhaps I can set for this? Or is this as designed?

**Comment by zeroin** [comment]
It's by design, we only animate values. It would be quite costly to check all the properties. So you'll have to manually animate color from one to another in your case. You can also create some additional custom state like "high", set fill property on this state to desired color and then just set this state if value is bigger than this specific value. But anyway, you'll have to do this on your side of a script.

**Comment by rocos-david** [comment]
Thanks for confirming and appreciate the tip to use the state option.
