### ISSUE TITLE
Sprite + path not working in JSON based configs

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#606]
In a JSON based setup, I am trying to get a Sprite + path to work (as a Map Image child).

Here's the Codepen demo: https://codepen.io/team/amcharts/pen/5ce1e059237cd1f0466fcfd29355754f?editors=1010.

Sprite + path seem to work fine for non JSON based config, as shown in the official example: https://www.amcharts.com/demos/map-with-curved-lines/.

I can only get the images to work when I convert the SVG path to a Data URI, but this process is kind of cumbersome & I lose the ability to change colors on the fly. Here's what the map looks like when I use Image + href (this is what the end result should look like): https://codepen.io/team/amcharts/pen/7bd92bffb332d2893e94f167ad5ecbc7?editors=1010.

How do I get the same result using Sprite + path in a JSON based config?

**Comment by martynasma** [comment]
It's a bug. Thanks!

We just fixed it in dev and will include in the next release version.

Will notify here when it happens.

**Comment by martynasma** [comment]
Fixed in [4.0.3](https://github.com/amcharts/amcharts4/releases/tag/4.0.3).

## [4.0.3] - 2018-11-30

### Added
- Ability to set default locale via `am4core.options.defaultLocale`. When set, all new charts will automatically assume that locale, freeing you from setting locale for each chart individually.
- `reverseOrder` added to `Container`. Allows reversing order of its `children`.

### Changed
- Moved `Legend` of a `MapChart` from `chartAndLegendContainer` to `chartContainer`. In order to position legend on map chart, use `legend.align` / `legend.valign` properties.
- Default value of `showOnInit` on any `Series` is now `false`. Except if you are using "animated" theme, which sets it to `true` by default.

### Fixed
- JSON: Using `type: "Sprite"` in JSON config was not creating elements properly.
- Initial chart rendering optimized Charts should build faster.
- Some more performance optimizations.
- Setting `hiddenInLegend` on `Series` after chart was already built had no effect.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
