### ISSUE TITLE
Reverse the Order of Legend Items?

### ISSUE THREAD

**Issue by taylorehat-cs** [amcharts/amcharts4#609]
Below is copy of the question I asked support that describes the issue with legend items feeling counter-intuitive to a LTR reader, they suggested leaving a feature request to add back in the `reversedOrder` property for legend items that existed in V3.

They responded with a solution to build a custom legend in the meantime.

> Is there a way to stack the series in a XY chart independently of the order the series is rendered in the legend? Or set a custom order in the legend or reverse the legend order?
> 
> I have found that the order you initialize the series' is the order they stack from bottom to top, which is fine, and then the legend is ordered from left to right.
> 
> The legend order feels backward, it is more apparent if you position the legend on the left or right of the chart, the legend stacks opposite the order the chart series stacks in the 
> chart.
> 
> <img width="586" alt="screenshot_67" src="https://user-images.githubusercontent.com/44442112/49162653-8d320480-f2e8-11e8-8c2a-1789f6edec4a.png">
> 
> Even if you position the chart on the bottom, the order of the legend seems counter intuitive since—at least my target audience—reads top to bottom, left to right. But in this case, the legend reads right to left.
> 
> <img width="985" alt="screenshot_68" src="https://user-images.githubusercontent.com/44442112/49162607-78557100-f2e8-11e8-98f7-125ae809e706.png">

Thanks,
Taylor

**Comment by martynasma** [comment]
Fixed in [4.0.3](https://github.com/amcharts/amcharts4/releases/tag/4.0.3).

## [4.0.3] - 2018-11-30

### Added
- Ability to set default locale via `am4core.options.defaultLocale`. When set, all new charts will automatically assume that locale, freeing you from setting locale for each chart individually.
- `reverseOrder` added to `Container`. Allows reversing order of its `children`.

### Changed
- Moved `Legend` of a `MapChart` from `chartAndLegendContainer` to `chartContainer`. In order to position legend on map chart, use `legend.align` / `legend.valign` properties.
- Default value of `showOnInit` on any `Series` is now `false`. Except if you are using "animated" theme, which sets it to `true` by default.

### Fixed
- JSON: Using `type: "Sprite"` in JSON config was not creating elements properly.
- Initial chart rendering optimized Charts should build faster.
- Some more performance optimizations.
- Setting `hiddenInLegend` on `Series` after chart was already built had no effect.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Use like this:

```
chart.legend.reverseOrder = true;
```
