### ISSUE TITLE
Label not rendered with set dateFormat

### ISSUE THREAD

**Issue by maurycyg** [amcharts/amcharts4#614]
I've set up a global date format for chart, the tooltip shows correct format but label and cursor label does not. I've tried to change the dateFormatter on axis, series and whole chart without success for label
codepen with issue
https://codepen.io/maurycyg/pen/WYYzqW?editors=0010

**Comment by martynasma** [comment]
Setting format for the `DateAxis` is not as straightforward as setting `dateFormat`. This axis type have multiple levels of granularity, so you need to set for your target one. In your case it's a day.

```
categoryAxis.dateFormats.setKey("day", "dd MMM");
categoryAxis.periodChangeDateFormats.setKey("day", "dd MMM");
```

More info:
https://www.amcharts.com/docs/v4/reference/dateaxis/#dateFormats_property
https://www.amcharts.com/docs/v4/reference/dateaxis/#periodChangeDateFormats_property

**Comment by maurycyg** [comment]
adding date formats produce something like this, where first and last label are not formatted
<img width="629" alt="screen shot 2018-12-03 at 10 33 24" src="https://user-images.githubusercontent.com/701197/49368545-dd450880-f6e6-11e8-9443-9675ab7c94bc.png">

**Comment by martynasma** [comment]
Did you add both `dateFormats` and `periodChangeDateFormats`?

**Comment by maurycyg** [comment]
So the DateAxis do NOT use the date format provided for the whole chart and it has not one but two properties to style the format of labels? That means I have now the date format repeated 3 times in the chart config. Seems a bit excessive

**Comment by martynasma** [comment]
Yes, that is correct. I understand it's an inconvenience, albeit necessary one.

Let me explain. Suppose you have a daily data for 10 years. When the map is completely zoomed out, you don't want a label for each of the 3650 days. That would be a mess.

So the chart reverts to bigger granularity for displaying labels - a year.

Now, you don't want those years to be formatted using daily format, like 2000-01-01, 2001-01-01, etc. That would be sloppy as well.

So the chart needs to use "year" format, so it looks nice, 2000, 2001, etc.

When you start zooming in, so the granularity of labels change. It might first revert to months, say 2000 Jan, 2000 Feb, etc. This will require "month" format.

So that is logic for DateAxis requiring whole bunch of formats rather than just bluntly relying on one format.

The `periodChangeDateFormats` is used when the bigger period starts. So say your axis spans two years. Starts with Jan 2000 and ends with Dec 2001.

Whenever label of the first month of the year is formatted, we use period change format to indicate start of the year differently from the rest of the labels.

So instead of 2000 Jan, 2000 Feb, 2000 Mar... we get nice 2000 Jan, Feb, Mar, ...., 2001 Jan, Feb, Mar.

You can disable this by setting [`markUnitChange`](https://www.amcharts.com/docs/v4/reference/dateaxis/#markUnitChange_property) to `false` on your date axis. This will make it use just `dateFormats` so you don't have to set it three times, just two.

I hope that makes sense, and sounds reasonable.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by NPC** [comment]
@martynasma Is there a list of all properties of DateAxis.dateFormats (e.g., the time units). I assume it's year, month, week, day, but think it's good to include it in the docs.

(probably have to set them all to the same value for dynamic charts; perhaps it would make sense to include an option to override all these formats with chart's date formatter)

**Comment by martynasma** [comment]
No, there's no such list, yet. I've been meaning to write a comprehensive dateFormats guide in docs, but... you know how it goes :)

Let me just plop the list here for now:

- `"millisecond"`
- `"second"`
- `"minute"`
- `"hour"`
- `"day"`
- `"week"`
- `"month"`
- `"year"`

Same for `dateFormats` and `periodChangeDateFormats`.

**Comment by martynasma** [comment]
Heads up, posted this:

https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Formatting_date_and_time
