### ISSUE TITLE
Top level treemap segment tooltip off center after drill-up

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#617]
In [this codepen](https://codepen.io/team/amcharts/pen/ba506814bb3ac533ebd6e560b27c9317?editors=1010), when you click on Parent 23 to drill down and and zoom back up, the tooltips for the top-level segments no longer line up with their corresponding segments.

GIF for reference

![github-617-treemap-tooltip2](https://user-images.githubusercontent.com/2679427/49314593-f0729100-f4b8-11e8-9e8b-8791cf0f444b.gif)

**Comment by martynasma** [comment]
Fixed in [4.0.4](https://github.com/amcharts/amcharts4/releases/tag/4.0.4).

## [4.0.4] - 2018-12-03

### Added
- `zoomLevel` and `zoomGeoPoint` properties added to `MapSeriesDataItem` and `IMapSeriesDataFields`. If set, these settings instead of automatically-calculated will be used when `zoomToMapObject()` method is invoked.

### Changed
- `verticalCenter` and `horizontalCenter` is no longer applied to rotated axis labels. If you are setting `rotation` on axis labels, make sure to adjust these settings as well as per your requirement.

### Fixed
- Setting `axis.renderer.inside` was ignored if set after chart was already initialized.
- Changing `align` of the a sprite was ignored if set after it was already initialized.
- Top level `TreeMap` segment tooltip was positioned incorrectly after drilling down and back up.
- `min`/`max` of `ValueAxis` was not being updated after `invalidateRawData()` call, and series were stacked.
- Tooltip sometimes was pointing outside chart container.
- `ChordLink` bullets were not properly positioned on init.
- `DateAxis` was not working well if `baseInterval.count > 1`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
