### ISSUE TITLE
Can't stack series on DateAxis

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#621]
When I try to stack my series which have individual data points, I get the error "Cannot read property 'hasValue' of undefined". When I set stacked to false, the chart renders.

You can recreate the issue with the following pen by changing stacked from true to false:

Pen: https://codepen.io/lucianholt/pen/PxVRpb?editors=1010

**Comment by zeroin** [comment]
This happens because some of your series has data at certain dates and others not. With our current design we can only properly stack series if all of them has the same amount of data. So I would suggest either create one data provider for the chart and combine all the data into this data (this would also be faster than setting data individually to series) or add all the dates (even if they don't have values) for all the datas of the series.

**Comment by martynasma** [comment]
@lucianholt97 At this point we do not have plans to implement support for stacking series with non-matching data. Too much fuzzy logic to consider all possible scenarios and contingencies.

As for your other questions, performance differences might manifest themselves if you have large data sets, as thousands of data points.

For charts with not a lot of data points, performance difference between chart.data and series.data is negligible.
