### ISSUE TITLE
invalidateRawData does not resize axis

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#622]
When updating a single value of the data array, calling chart.invalidateRawData() or series.invalidateRawData() should be sufficient to update the chart. In my case (pen attached) the value is changed, but the axis does not resize so that you can't actually see the new data and there is neither an option to resize manually.

Try clicking on "change data"
https://codepen.io/lucianholt/pen/qQgoxB?editors=0011

**Comment by martynasma** [comment]
Fixed in [4.0.4](https://github.com/amcharts/amcharts4/releases/tag/4.0.4).

## [4.0.4] - 2018-12-03

### Added
- `zoomLevel` and `zoomGeoPoint` properties added to `MapSeriesDataItem` and `IMapSeriesDataFields`. If set, these settings instead of automatically-calculated will be used when `zoomToMapObject()` method is invoked.

### Changed
- `verticalCenter` and `horizontalCenter` is no longer applied to rotated axis labels. If you are setting `rotation` on axis labels, make sure to adjust these settings as well as per your requirement.

### Fixed
- Setting `axis.renderer.inside` was ignored if set after chart was already initialized.
- Changing `align` of the a sprite was ignored if set after it was already initialized.
- Top level `TreeMap` segment tooltip was positioned incorrectly after drilling down and back up.
- `min`/`max` of `ValueAxis` was not being updated after `invalidateRawData()` call, and series were stacked.
- Tooltip sometimes was pointing outside chart container.
- `ChordLink` bullets were not properly positioned on init.
- `DateAxis` was not working well if `baseInterval.count > 1`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
