### ISSUE TITLE
Question: Continent map problem on Asia map

### ISSUE THREAD

**Issue by violeng** [amcharts/amcharts4#625]
Hi I am trying to using this demo https://www.amcharts.com/demos/drill-down-map/ for my project but I found there is a problem on the Asia map that is a small part go to the left side (North America) so when I click on Asia it could not have the correct zoom behavior. My question is there any way to replace this map style? It seems like on the Map version 3 it looks fine.

**Comment by RobbiesCode** [comment]
Hi,

In amCharts v4 you can change the `deltaLongitude` of the map. Basically this defines the center of the map.

You can easily change it to your desired center like this:

```
chart.deltaLongitude = -10;
```

Possible values are -180 until +180.

Here's a Codepen example: https://codepen.io/team/amcharts/pen/3ec13ecc2f3bdb185ff1c9597100e120?editors=1010

Hope this helps!

**Comment by violeng** [comment]
Hi @RobbiesCode Thank for your response. I have tried this but it leads to another problem on the North America because a small path of it go to the right side next to Asia. I think I might implement a work around to check both continents on click event before zoom the map.

**Comment by martynasma** [comment]
@violeng You're right, `deltaLongitude` might shift the map, but it will not influence zoom.

At this point there's currently no way to make the chart zoom just to "part" of the area.

Starting with the next version we will release shortly, you will be able to set zoom settings for each area individually. You'll just need to add that data to your series data.

I'll provide further details and a demo once the new version is out.

**Comment by martynasma** [comment]
Fixed in [4.0.4](https://github.com/amcharts/amcharts4/releases/tag/4.0.4).

## [4.0.4] - 2018-12-03

### Added
- `zoomLevel` and `zoomGeoPoint` properties added to `MapSeriesDataItem` and `IMapSeriesDataFields`. If set, these settings instead of automatically-calculated will be used when `zoomToMapObject()` method is invoked.

### Changed
- `verticalCenter` and `horizontalCenter` is no longer applied to rotated axis labels. If you are setting `rotation` on axis labels, make sure to adjust these settings as well as per your requirement.

### Fixed
- Setting `axis.renderer.inside` was ignored if set after chart was already initialized.
- Changing `align` of the a sprite was ignored if set after it was already initialized.
- Top level `TreeMap` segment tooltip was positioned incorrectly after drilling down and back up.
- `min`/`max` of `ValueAxis` was not being updated after `invalidateRawData()` call, and series were stacked.
- Tooltip sometimes was pointing outside chart container.
- `ChordLink` bullets were not properly positioned on init.
- `DateAxis` was not working well if `baseInterval.count > 1`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Here's an example:
https://codepen.io/team/amcharts/pen/a598babf2793f8c8ca25d6df8f0cce56

For Asia we now have custom zoom values set in data as well as relative dataFields for series.

```
continentsSeries.dataFields.zoomLevel = "zoomLevel";
continentsSeries.dataFields.zoomGeoPoint = "zoomGeoPoint";

continentsSeries.data = [ {
  "id": "Africa",
  "color": chart.colors.getIndex(0)
}, {
  "id": "Asia",
  "color": chart.colors.getIndex(1),
  "zoomLevel": 2,
  "zoomGeoPoint": {
    "latitude": 46,
    "longitude": 89
  }
}, {
  "id": "Australia and Oceania",
  "color": chart.colors.getIndex(2)
}, {
  "id": "Europe",
  "color": chart.colors.getIndex(3)
}, {
  "id": "North America",
  "color": chart.colors.getIndex(4)
}, {
  "id": "South America",
  "color": chart.colors.getIndex(5)
}];
```

Make sure you upgrade for the above to work.

**Comment by violeng** [comment]
Hi @martynasma 
Thanks for your support. I will try it out.
