### ISSUE TITLE
Cursor shows strange dates and is not snapping to all data points

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#639]
In v4.0.2 the cursor shows sometimes strange dates (at least, when dates are missing). In the following Example, the first data point has no value, only a date on 2018-11-03, followed by a data point with a value on 2018-11-05. When trying to hover the first date on 2018-11-03, the cursor snaps not to the data point, somewhere between 2018-11-03 and 2018-11-05 and shows "Nov 06" (a date after 2018-11-05).
https://codesandbox.io/s/k314v8568r

The second example is the same, but uses v4.0.5, and the cursor has an even stranger behaviour: When it snaps to the date 2018-11-03, it shows "Nov 02". For 2018-11-05 it shows "Nov 04".  It ignores snapping to the data point on 2018-11-23. It works correctly for the data point on 2018-11-26, but shows a day earlyer again, for the following data points. Besides the cursor problem, also the grid layout do not fit anymore.
https://codesandbox.io/s/mqx4x8k2pp

**Comment by zeroin** [comment]
Try setting: `xAxis.baseInterval = {timeUnit:"day", count:1}`
Previously we always set the count to 1, but it caused other problems, so we try to dected the propert count automatically. But as your data is at a very irregular intervals, the chart calculates count which is > 1 and this causes these problems.

**Comment by CipSoft-Components** [comment]
After further tests, it looks like, this problem appears, if the data point is exactly 2 dates before. I hope, this helps you to find the problem.

**Comment by martynasma** [comment]
@CipSoft-Components We have released a new version 4.0.6 just now.

It changes some logic behind axis tooltips and base interval detection algo.

The chart now behaves fine for me with the new version. Can you confirm if it does for you as well?

**Comment by CipSoft-Components** [comment]
I tried the new version, but it still behaves the same, like in v4.0.2. Thank you for the further and fast investigation!

**Comment by martynasma** [comment]
Thanks for additional details.

OK, so since 4.0.7 the tooltip on axis will try to snap to whatever closest data item is.

You can disable this behavior using:

```
dateAxis.snapTooltip = false;
```

It will now display tooltip for each day on the axis.

Let me know if this makes tooltips behave the way you want them to.

**Comment by CipSoft-Components** [comment]
Thank you, but nothing changed in my case with version 4.0.7. Here is a codepen with the adjusted gap demo from the amCharts website:
[https://codepen.io/anon/pen/dwywej?&editable=true](https://codepen.io/anon/pen/dwywej?&editable=true)
It looks like, if there is a data point with only the date and no value, 2 units before a normal data point, and a gap in between, it calculates the nearest data point wrong. In the example above, it jumps to 1977. In my personal case it snaps between the date only data point and the data point with value, and it shows some date in the future (which one, depends on how many data points are shown at all).
In the adjusted codepen demo, the date it snaps to also changes, if you remove unrelated dates from the end of the data. e.g. if I removed everything after 1980, it snaps between 1974 and 1975 and shows 1974.

**Comment by martynasma** [comment]
Fixed in [4.0.8](https://github.com/amcharts/amcharts4/releases/tag/4.0.8).

## [4.0.8] - 2018-12-11

### Added
- `currentStep` added to `ColorSet`. Allows setting current position of the color iterator.
- Adapters added for `Sprite` properties: `inertiaOptions`, `hitOptions`, `hoverOptions`, `swipeOptions`, `keyboardOptions`, `cursorOptions`.

### Changed
- `nonScaling` of `AxisLabel` is no longer set to `true` by default, to improve performance.

### Fixed
- `ValueAxis` was not updating its scale if series was hidden and animated theme was not enabled.
- Zooming an `XYChart` with all values equal was broken.
- Series in an `XYChartScrollbar` sometimes was not visible initially.
- `ColumnSeries` was drawing 1px line for `null` value data items.
- `DateAxis`' `snapTooltip = true` was working incorrectly with `skipEmptyPeriods = true`.
- Logarithmic `ValueAxis` with axis breaks was resulting in stack overflows.
- JSON: Chaining multiple adapters in an array (e.g. `adapter: [{...}, {...}]`), was not working.
- JSON: Adding elements to `children` via array syntax was not working properly.
- JSON: `Container` elements can now be created via JSON config.
- Setting `dataFields` in `Export` was only affecting column names. Values for all data fields were still being included in export.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by CipSoft-Components** [comment]
Thank you for your quick fix of my issue, now everything works as expected!
