### ISSUE TITLE
Tooltip stays when data updates (TreeMap)

### ISSUE THREAD

**Issue by leralgarmuz** [amcharts/amcharts4#64]
Hi there, I think this is a bug.

I'm updating the TreeMap data either by replacing the data set
https://www.amcharts.com/docs/v4/concepts/data/#Replacing_whole_data_set

Or by manipulating the data.
https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points

and the tooltip freezes when that update happens.
![image](https://user-images.githubusercontent.com/35471812/41172038-2929796c-6b18-11e8-882f-f120ea52740d.png)

I'm still able to move/use the tooltip, but an instance of that previous tooltip stays in place.

Thanks in advanced.

**Comment by martynasma** [comment]
Thanks for the heads up. We're on it.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
