### ISSUE TITLE
LineSeries stoke fill is not changing the color

### ISSUE THREAD

**Issue by tjones0808** [amcharts/amcharts4#642]
const series = chart.series.push(new am4charts.LineSeries());
    series.stroke.fill = am4core.color(this.props.color);

where color = "rgb(238,102,147)"

**Comment by martynasma** [comment]
I'm not entirely sure what you are trying to do there.

If you want to set color of the line, you set `stroke`:

```
series.stroke = am4core.color(this.props.color);
```

If you need to set fill, making it an area series, you set `fill` and `fillOpacity`: (setting `fillOpacity` is important since it's zero (transparent) by default)

```
series.fill = am4core.color(this.props.color);
series.fillOpacity = 0.2;
```

But there's no fill property of the stroke, like in your snippet.

I hope this makes sense and helps.

**Comment by tjones0808** [comment]
ugghhh wow thank you!! doh!!
