### ISSUE TITLE
Hiding items on the chart via the legend don't rearrange them in some cases

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#643]
When you "deactivate" some item on the chart via the legend marker all remains the same without rearranging, except that deactivated item becomes invisible.
For example TreeMap (https://codepen.io/team/amcharts/pen/zLVKLm):
![image](https://user-images.githubusercontent.com/15041200/49600536-19e55e00-f98c-11e8-9316-932b905b009d.png).
Or the column chart (https://codepen.io/team/amcharts/pen/wjyJQw):
![image](https://user-images.githubusercontent.com/15041200/49600790-b3147480-f98c-11e8-8e4c-63f3d6306fd5.png)

But all works perfectly for the pie chart (https://codepen.io/team/amcharts/pen/aKMaXQ):
![image](https://user-images.githubusercontent.com/15041200/49600622-4b5e2980-f98c-11e8-8eb1-993ac8d5535a.png)
After deactivating most of the items the pie rearranges so the circle is fully filled.

**Comment by martynasma** [comment]
I agree that it should re-arrange on a TreeMap. After all the whole point of toggling off a series is to make remaining ones clearer.

Not sure if re-arranging columns is a good approach, though. We'll discuss it.

Will keep you posted.

Thanks!

**Comment by martynasma** [comment]
Fixed in [4.0.7](https://github.com/amcharts/amcharts4/releases/tag/4.0.7).

## [4.0.7] - 2018-12-07

### Added
- `snapTooltip` with default value `true` added to `DateAxis`. Cursor will snap to the nearest date at which series has values.

### Changed
- Default value of `showOnInit` set to `false` for `TreeMapSeries`.

### Fixed
- Solved tooltip overlapping bug.
- In `TreeMap`, when series is toggled off, remaining series will be resized to take up freed space.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
Sorry, I made a typo in my last comment. TreeMap will NOW re-arrange. (not "not re-arrange")
