### ISSUE TITLE
Question: How can I tell a chart to skip colors from the beginning of the colorSet?

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#652]
I wondered whether it is possible to tell a chart to skip the first x colors of the default colorSet. I have multiple PieCharts arranged next to each other and would like to differentiate them by color.
I didn't find a solution in the docs, yet.
Thank you in advance!

**Comment by martynasma** [comment]
Hm, I suppose calling `next()` for X times should do the trick:

```
for(var i = 0; i < 10; i++) {
  chart.colors.next();
}
```

**Comment by martynasma** [comment]
OK, just added a `currentStep` property to `ColorSet`. It will be rolled into the next version we are going to release at some point next week.

**Comment by martynasma** [comment]
Fixed in [4.0.8](https://github.com/amcharts/amcharts4/releases/tag/4.0.8).

## [4.0.8] - 2018-12-11

### Added
- `currentStep` added to `ColorSet`. Allows setting current position of the color iterator.
- Adapters added for `Sprite` properties: `inertiaOptions`, `hitOptions`, `hoverOptions`, `swipeOptions`, `keyboardOptions`, `cursorOptions`.

### Changed
- `nonScaling` of `AxisLabel` is no longer set to `true` by default, to improve performance.

### Fixed
- `ValueAxis` was not updating its scale if series was hidden and animated theme was not enabled.
- Zooming an `XYChart` with all values equal was broken.
- Series in an `XYChartScrollbar` sometimes was not visible initially.
- `ColumnSeries` was drawing 1px line for `null` value data items.
- `DateAxis`' `snapTooltip = true` was working incorrectly with `skipEmptyPeriods = true`.
- Logarithmic `ValueAxis` with axis breaks was resulting in stack overflows.
- JSON: Chaining multiple adapters in an array (e.g. `adapter: [{...}, {...}]`), was not working.
- JSON: Adding elements to `children` via array syntax was not working properly.
- JSON: `Container` elements can now be created via JSON config.
- Setting `dataFields` in `Export` was only affecting column names. Values for all data fields were still being included in export.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by lucianholt97** [comment]
@martynasma it seems like this feature is not working for `PieCharts`, yet.
Setting `chart.colors.currentStep = 3` on a `XYChart` works as expected.
According to the docs I need to set the `ColorSet` on a `PieChart` for each series. But `pieSeries.colors.currentStep = 3` does not have any effect. Neither does `pieChart.colors.currentStep = 3`.

Also see: https://codepen.io/lucianholt/pen/eoVbve?=true

Please let me know if I am missing anything.
Thanks in advance!
