### ISSUE TITLE
Region map of Poland

### ISSUE THREAD

**Issue by piernik** [amcharts/amcharts4#654]
In v 3 there is a region map of Poland. Is there a chance for the same in v 4?

**Comment by martynasma** [comment]
Yes, we're re-adding maps one-by-one. V3 used SVG, V4 uses GeoJSON - different format, so we have to remake all of them.

I'll bump up Poland so it is implemented sooner. Will let you know when it's ready.

**Comment by piernik** [comment]
Great - thank You.
One more thing.
What about map of Europe? In such Russia should be split into Europ and Asia part.

**Comment by martynasma** [comment]
Yep, those maps are being prepared for the release as we speak. Should be released in the coming 1-2 days.

Not sure if Poland will make into this next release or not, tho. Even if it's not, I expect it to be ready by the end of this week.

**Comment by piernik** [comment]
Great news and great job.

**Comment by martynasma** [comment]
BTW, you mentioned map of Europe with Russia split in two. Normally our map of Europe contains only Russian European part, for obvious aesthetic/logical reasons.

Do you mean you need a map that has Russia's Asian part as well? (we haven't been planning such map)

That said, we were planning a World map with Russia split in two parts, so that could be repurposed easily for your requirement as well.

**Comment by piernik** [comment]
No. I need only European part.

**Comment by piernik** [comment]
Works - thanks
