### ISSUE TITLE
Axis Breaks do not work on Logarithmic Axis

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#655]
When trying to add an axis break to my logaritmic value axis, nothing renders. The page is stuck.

Steps:

I am taking this official example of a column chart with an axis break: https://www.amcharts.com/demos/column-chart-with-axis-break/.

I convert the regular value axis to a logarithmic value axis. I even remove the min and max settings. I do keep the axis break. Page gets stuck.

Code:

```
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.renderer.minGridDistance = 30;
valueAxis.logarithmic = true;

// axis break
var axisBreak = valueAxis.axisBreaks.create();
axisBreak.startValue = 2100;
axisBreak.endValue = 22900;
axisBreak.breakSize = 0.005;
```

Demo: https://codepen.io/team/amcharts/pen/87da9303777fa58b6afe93eef9f6dbe8?editors=0010.

Note that in the demo I have placed the axis break lines in between comments. Uncomment these lines to see what I mean.

**Comment by martynasma** [comment]
Fixed in [4.0.8](https://github.com/amcharts/amcharts4/releases/tag/4.0.8).

## [4.0.8] - 2018-12-11

### Added
- `currentStep` added to `ColorSet`. Allows setting current position of the color iterator.
- Adapters added for `Sprite` properties: `inertiaOptions`, `hitOptions`, `hoverOptions`, `swipeOptions`, `keyboardOptions`, `cursorOptions`.

### Changed
- `nonScaling` of `AxisLabel` is no longer set to `true` by default, to improve performance.

### Fixed
- `ValueAxis` was not updating its scale if series was hidden and animated theme was not enabled.
- Zooming an `XYChart` with all values equal was broken.
- Series in an `XYChartScrollbar` sometimes was not visible initially.
- `ColumnSeries` was drawing 1px line for `null` value data items.
- `DateAxis`' `snapTooltip = true` was working incorrectly with `skipEmptyPeriods = true`.
- Logarithmic `ValueAxis` with axis breaks was resulting in stack overflows.
- JSON: Chaining multiple adapters in an array (e.g. `adapter: [{...}, {...}]`), was not working.
- JSON: Adding elements to `children` via array syntax was not working properly.
- JSON: `Container` elements can now be created via JSON config.
- Setting `dataFields` in `Export` was only affecting column names. Values for all data fields were still being included in export.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
