### ISSUE TITLE
XYChart zooming is broken with data values of all zeroes.

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#660]
[https://codepen.io/anon/pen/RENyZJ](https://codepen.io/anon/pen/RENyZJ)

This CodePen is a copy of [this amChart demo](http://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/), with one modification:
1) Line 69: Changed "visits" to always be 0 (where, series.dataFields.valueY = "visits"). 

After the CodePen loads, try to perform a zoom or just click the "Zoom Out" button in the top right (though, hitting "Zoom Out" again will work as expected). After any zoom, the Y-axis limits change to only show -1.0 to -1.001.

I'm not sure if the data values all being zero is the actual cause of the issue, but that is how I noticed it.

**Comment by martynasma** [comment]
Fixed in [4.0.8](https://github.com/amcharts/amcharts4/releases/tag/4.0.8).

## [4.0.8] - 2018-12-11

### Added
- `currentStep` added to `ColorSet`. Allows setting current position of the color iterator.
- Adapters added for `Sprite` properties: `inertiaOptions`, `hitOptions`, `hoverOptions`, `swipeOptions`, `keyboardOptions`, `cursorOptions`.

### Changed
- `nonScaling` of `AxisLabel` is no longer set to `true` by default, to improve performance.

### Fixed
- `ValueAxis` was not updating its scale if series was hidden and animated theme was not enabled.
- Zooming an `XYChart` with all values equal was broken.
- Series in an `XYChartScrollbar` sometimes was not visible initially.
- `ColumnSeries` was drawing 1px line for `null` value data items.
- `DateAxis`' `snapTooltip = true` was working incorrectly with `skipEmptyPeriods = true`.
- Logarithmic `ValueAxis` with axis breaks was resulting in stack overflows.
- JSON: Chaining multiple adapters in an array (e.g. `adapter: [{...}, {...}]`), was not working.
- JSON: Adding elements to `children` via array syntax was not working properly.
- JSON: `Container` elements can now be created via JSON config.
- Setting `dataFields` in `Export` was only affecting column names. Values for all data fields were still being included in export.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
