### ISSUE TITLE
target.dataItem for **cursorOptions** adapters is always undefined

### ISSUE THREAD

**Issue by dmsmaxim** [amcharts/amcharts4#662]
Example:
https://codepen.io/dmsmaxim/pen/JwdRbb

```
pieSeries.slices.template.adapter.add('cursorOptions', (value, target) => {
  console.assert(target.dataItem === undefined); // is always right
...
```

**Comment by martynasma** [comment]
Looks like adapter is assigned once when Slice is created, and before it is populated with data.

We'll need to figure out how to solve this.

Thanks for the heads up!

**Comment by bahadirali** [comment]
Any update?

**Comment by martynasma** [comment]
I'm afraid we won't be able to fix this due how it is structured internally. Cursor options need to be set initially via styles. It's not something we change explicitly every time element is interacted with. So it turns out that it happens before data is fully initialized for slices, and thus dataItem is not available. Sorry.
