### ISSUE TITLE
XYChart: Odd tooltip behavior

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#663]
Not sure how to title this one. I have noticed a variety of issues with this simple, two data-point, [CodePen example](https://codepen.io/anon/pen/BvNpqJ).

1) With my cursor at [this location](https://i.imgur.com/92jlmTg.png), why is the right datapoint getting the tooltip and not the left, for which the cursor is most closest?
2) In that same screenshot above, why is the cursor x-axis label showing "16:21:30" when the timestamp for the datapoint has hours, minutes, seconds of "21:21:42"? (I understand the 16 instead of 21 for the hours is due to timezone difference [converting to EDT], but why are the seconds different?)

Now, in the chart.data array, change the timestamp of the second datapoint to 
`new Date('2018-12-10T21:21:43.000Z')`
(so, adding one second to the previous value)
The first datapoint now never gets the tooltip, and the tooltip on the second datapoint starts freaking out moving left to right as you move your cursor around the chart. Also, putting your cursor on top of the second datapoint shows no tooltip at all.

**Comment by martynasma** [comment]
Fixed in [4.0.11](https://github.com/amcharts/amcharts4/releases/tag/4.0.11).

## [4.0.11] - 2018-12-24

### Added
- `"disabled"` and `"enabled"` events added to `Sprite`.
- `cursorTooltipEnabled` added to `XYSeries`  If set to `false` cursor will not trigger bullet/item tooltips on series.

### Changed
- IMPORTANT (CODE-BREAKING CHANGES) For performance reasons we no longer create axis elements if they are disabled. For the same reasons we disabled by `axis.ticks` and `axis.axisFills` by default. Previously to enable them you had to set their `strokeOpacity` and/or `fillOpacity` to non-zero. This no longer will work. You will need to set `disabled` to `false` instead.
- `axisRanges` now take their default values from `dateAxis.axisRanges.template` items (`axisFill`, `grid`, `tick`, `label`). Previously they were using the defaults from `dateAxis.renderer.label` etc. This was not comfortable and counter-intuitive.

### Fixed
- `XYChartScrollbar`'s value axis was calculating `min`/`max` with a very big step.
- Ember plugin was throwing console errors.
- Fixed occasional zoom-in issue on Mobile Safari.
- `MapChart` mouse wheel zoom direction was inverted on some browsers.
- Cursor was not snapping correctly to `DateAxis` items.
- Multiple floating columns on the same category were disappearing when scrolling the chart.
- Date range fills were off when zooming on Gantt Chart.
- Overlapping tooltips problem solved.
- When `snapToSeries` was set for a tooltip, it was flickering a lot on slower browsers.
- `alignLabels = false` on a `PieSeries3D` was causing labels to be positioned incorrectly.
- `PieSeries.dataFields.radiusValue` was not accounting for `chart.innerRadius`.
- Dynamically updating `alignLabels` for `PieSeries` did not work correctly.
- Legend: `itemValueText` only worked if `valueText` was set.
- `ValueAxis` setting `maxZoomFactor = 1` was not working as expected.
- Changing values for all data items sometimes was resulting in `ValueAxis` scale going into negative.
- Some more tooltip and cursor related issues fixed.
- Axis Fill did not properly fill the whole span when axis was scaled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
