### ISSUE TITLE
Adapter for series tooltipText/tooltipHTML

### ISSUE THREAD

**Issue by arm1n** [amcharts/amcharts4#67]
This is rather a question than an issue. I would like to customize `tooltipText` as shown in [adapters documentation](https://www.amcharts.com/docs/v4/concepts/adapters/#Adding_adapters) to display other values from bound data item. I'm using type `LineSeries` and want to customize as follows:

```typescript
// data source for chart's `data` property
let data: Array<object> = [
  {
    category: 'Car',  // = categoryX
    price: 5000,      // = valueY
    time: 1528786360  // = some other data
  },
  ...
];

// adapter for `tooltipText` from line series
lineSeries.adapter.add('tooltipText', (text, target: LineSeriesDataItem) => {
  let data = target.tooltip.dataItem.dataContext; // = undefined
  let data = target.dataItem.dataContext; // = undefined

  let data = ... // how to access `time` from data source here?

  return `Price: ${data.price}\nTime: ${data.time}`;
});
```

Besides, also `text` parameter is constantly providing `undefined` in callback. Could you please tell me how to access the bound data item properly to show different values from data source? Thanks!

**Comment by arm1n** [comment]
Small addition: Same occurs when trying to setup an adapter for axis `getTooltipText` like so:

```javascript
this._xAxis.adapter.add('getTooltipText', (text: string, target: am4charts.CategoryAxis): string => {
  let dataItem: CategoryAxisDataItem = target.dataItem; // undefined
  
  return text; // defined
});
```

So in this case `dataItem` isn't even defined, whereas `text` parameter provides default `{categoryX}` as without using an adapter.

**Comment by martynasma** [comment]
OK, so there are two separate questions: tooltip for the Series and tooltip for the Axis.

To complicate things further, tooltip for the Series has also a dual-usage. The `series.tooltipText` is used only when you also have `Cursor` enabled on he chart. It's ignored if you don't have a Cursor. In that case `tooltipText` is used from individual hoverable items, like a bullet.

Which is it in your case?

As for Category axis, I suppose you could access a `CategoryAxisDataItem` using axis' `dataItemsByCategory` property, which is a dictionary:

```
this._xAxis.adapter.add('getTooltipText', (text: string, target: am4charts.CategoryAxis): string => {
  let dataItem: CategoryAxisDataItem = target.dataItemsByCategory.getKey(text);
  
  return text; // defined
});
```

This property is not documented, though. I'll add a note to surface this property to class ref, as I can see how it can be useful.

**Comment by arm1n** [comment]
Thanks for your response - just tried your suggestion for the (category) axis tooltip, which works fine, great! Considering the `tooltipText` of (line) series. In my setup I'm only using combined with `XYCursor`. Would be great to access original data here in a similar way for showing other properties from input data. Thanks for taking a public API for this things into consideration, it increases flexibility tremendously 👍

**Comment by martynasma** [comment]
You're right. There's currently no way to access related data item in tooltipText adapter.

We'll need to think about this.

One solution would be to pass in an object into adapter, which would hold both formatted text and data item reference. However, I don't like that because it would break consistency with regular Sprite's tooltipText.

I'll get back to you :)

**Comment by arm1n** [comment]
I tried this but the property `dataContext` stays `undefined`.

**Comment by martynasma** [comment]
Sorry, your reply slipped through the cracks somehow.

It turns out that sometimes adapter is called without specific data item. This is solvable by adding checks:

```JavaScript
series.adapter.add('tooltipText', (text, target) => {
  let data = target.tooltipDataItem.dataContext;
  if (target.tooltipDataItem.dataContext) {
    return `Price: ${data.price}\nTime: ${data.time}`;
  }
  else {
    return text;
  }
});
```

https://codepen.io/team/amcharts/pen/cad24deff91048118ad69b33df8e2c8f

**Comment by martynasma** [comment]
@johnalotoski The reference `data.price` refers to actual data. Do you have "price" in your data? The error might occur if there are no such fields in data. If you could produce an actual chart including data as a codepen, that would help us a lot in figuring this out.

**Comment by johnalotoski** [comment]
Hi @martynasma, thanks for the feedback.  Here is a codepen example which is essentially your codepen above, modified by adding several extra data digits past the decimal point to the price value field and then trying to insert a number formatter to the adapter's data.price return value so that, for example, only a few digits past zero will be shown in the tooltip text and not all of them: [https://codepen.io/jlotoski/pen/dgNWev](https://codepen.io/jlotoski/pen/dgNWev).

The error thrown in the console inspection is data.price.formatNumber is not a function, so maybe there's a simple syntax problem I have.

**Comment by martynasma** [comment]
Thanks for the codepen.

There are two issues with the code:

1) You have enclosed the `tooltipText` value in backticks which makes the string "template literals". ([more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)).

This makes stuff in curly brackets to be treated as actual JS code, hence the error, because, naturally, no `formatNumber` function in your data context.

This is easily fixable by replacing backticks with a doublequotes.

2) Another issue is that you are referring to `data.price`. The "data." part is excessive since you have your data in chart, not in series as it was the case in previous examples on this issue.

So the fixed (working) code would be like this:

```
series.adapter.add('tooltipText', (text, target) => {
  let data = target.tooltipDataItem.dataContext;
  if (target.tooltipDataItem.dataContext) {
    return "Price: ${price.formatNumber('#.##')}\nTime: ${time}";
  }
  else {
    return text;
  }
});
```

**Comment by johnalotoski** [comment]
Thank you for the explanation @martynasma -- I understand now!
