### ISSUE TITLE
Vertical Bar Chart with two Value Axes

### ISSUE THREAD

**Issue by pouretrebelle** [amcharts/amcharts4#673]
Hello,

I'm trying to make a chart that looks like this:

![image](https://user-images.githubusercontent.com/1901935/49886806-8354e900-fe32-11e8-92f4-0be4c6cc4d2b.png)

AFAIK the vertical column chart examples work by assuming the direction of the column should match the `ValueAxis`, but is there any way to use value axes in both directions? I want to have `valueY` and `openValueY` for columns of various widths and heights.

`series.stacked` also stacks the series the wrong way around..

**Comment by martynasma** [comment]
This looks like a job for a `StepLineSeries` and two value axes.

This is a very crude prototype:
https://codepen.io/team/amcharts/pen/7da43c3e02b31cf57b632647193b0ee9

Do you think something like that could work for you?

**Comment by pouretrebelle** [comment]
The `StepLineSeries` works with the values but I'm having trouble with 2 things:

[https://codepen.io/pouretrebelle/pen/1f359e55526937054f9eb10109dcc43d](https://codepen.io/pouretrebelle/pen/1f359e55526937054f9eb10109dcc43d?editors=0010)

I want each row to have a stroke as well, I figured Axis Ranges would work to divide the graph but I'm struggling to have them appear on top of the chart content, z-index doesn't seem to be working, any ideas?

Secondly, I want to have either labels or tooltips for the content. I haven't managed to get tooltips to appear on the series at all with horizontal step lines (even [this demo](https://www.amcharts.com/demos/step-line-without-risers/)'s tooltips disappear if you flip the axes), and labels aren't responding to the `locationY` property.. I've been thinking this could be faked with a dy adapter but not sure how to go about it.

Any help would be appreciated,
Thank you

**Comment by martynasma** [comment]
```
chart.seriesContainer.zIndex = -1;
```

The above will send all series right behind grid/ranges.

As for the tooltip, you're right - there's currently no way to enable tooltips on a vertically-positioned Line/Step series.

`locationY` won't work either, because on a Line/Step series, there is no "width" like you have in Column series. Each item is represented by a single point, hence `locationY` being ignored.

Bottom line, there's no way to position labels in the middle of each step.

As an ugly workaround (for both labels and tooltips) we might add a "ghost" `ColumnSeries`. Completely transparent fill. It would reuse same X value, and provide tooltip and label positioning.

Something like this:
https://codepen.io/team/amcharts/pen/34f301efa1a78e116298f92f5bc22628?editors=0010

**Comment by pouretrebelle** [comment]
Ah an easy fix for the z-index.

I like the idea of using a `ColumnSeries` for the labels, but as I wanted to use them on both sides I made a second x-axis which is reversed to put the second series and its column series / label on, so I didn't have to stack them.

Solution [here](https://codepen.io/pouretrebelle/pen/125ef78d1fc68d9dd11dd2df01015d22?editors=0010) for posterity. Thank you so much for your help on this, I know it's a bit esoteric 🙂

**Comment by martynasma** [comment]
That chart looks awesome! Great work.
