### ISSUE TITLE
Performance of AmCharts 4 is very poor

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#682]
Disclaimer: Maybe (and hopefully) I am doing something wrong 

So on a XY chart with 1 series of dates and number values for 7200 lets say elements it takes ~30s - 60s  in order to load load on a modern Macbook and Chrome warns about memory leaks. 

Here is an example with random numbers https://codepen.io/anon/pen/JwGbYW

I do notice though that if I use linear numbers it is a bit faster but way slower than AmCharts3 

Here is an example with linear numbers https://codepen.io/anon/pen/JwGbYW

related #68

**Comment by martynasma** [comment]
OK, let's bisect your chart :)

1) Bullets. Do you really need bullets on a chart with such dense data? That's 7K extra elements for the chart to draw. Disabling bullets alone, will give your chart a dramatic boost in performance.

2) Smoothed line. Again. Smoothing effect looks nice on a line series with a few data points, but is completely useless on lines with so many segments. It also drains performance. So, disabling `tension` settings will speed up your chart even further, without having any noticeable affect on appearance.

3) Animations. Goes without saying, than animation is a resource-intensive operation. You might consider disabling "animated" theme, so that you chart appears faster.

One other thing to consider.

You can display bullets dynamically using series [`minBulletDistance`](https://www.amcharts.com/docs/v4/reference/xyseries/#minBulletDistance_property) property.

It allows hiding bullets if there are too many data points crammed together but display them when you zoom in enough.

**Comment by jimmykane** [comment]
Good to know, I ll try to adjust the example to a similar case with mine to hear some more optimizations.
