### ISSUE TITLE
Time ignored if date is string in JSON

### ISSUE THREAD

**Issue by Britford** [amcharts/amcharts4#695]
When JSON data returns dates in a string, the time is assumed to be 00:00 so all data points for a given date are stacked instead of spread over the timeline.  When dates are converted to Javascript dates, chart displays as expected.

Example: https://codepen.io/AlienTechnology/pen/ZVWpER  (based on an amCharts pen)

**Comment by Achilles1515** [comment]
Add

`chart.dateFormatter.inputDateFormat = "yyyy-MM-ddTHH:mm:ss.SSSZ";`

**Comment by Britford** [comment]
My apologies.  That worked perfectly.

**Comment by xorspark** [comment]
Even shorter - `"i"` is equivalent to `"yyyy-MM-ddTHH:mm:ss.SSSZ"`

**Comment by Achilles1515** [comment]
> Even shorter - `"i"` is equivalent to `"yyyy-MM-ddTHH:mm:ss.SSSZ"`

This is actually not true, despite the docs making it seem so.
Use...
`chart.dateFormatter.inputDateFormat = "yyyy-MM-ddTHH:mm:ss.SSSZ";`
and then replace it with...
`chart.dateFormatter.inputDateFormat = "i";`
...and you will get two different charts (offset by local time zone difference from UTC).

Using...
`chart.dateFormatter.inputDateFormat = "yyyy-MM-ddTHH:mm:ss.SSS"; // no time zone specified`
...will give you the same chart as "i".

So, `"i"` is equivalent to `"yyyy-MM-ddTHH:mm:ss.SSS"` (without the time zone specifier --> making it parse as local time instead).

Though, this seems like a bug to me, especially considering the regex used in the "i" formatter expects a 'Z':
(/src/.internal/core/formatters/DateFormatter.ts)
![image](https://user-images.githubusercontent.com/23387905/50038689-7d593680-fff1-11e8-9700-7584fca3248a.png)

With the 'Z' standing for Zulu/UTC, I feel like this code in the same file...

![image](https://user-images.githubusercontent.com/23387905/50038696-b98c9700-fff1-11e8-8fc7-a5e232ab63da.png)

...should be... 

`res = new Date(Date.UTC(...))`

@martynasma Can you confirm the current behavior of the date formatter, that is NOT producing a UTC Date despite specifying UTC time zone in the string, is expected?

**Comment by martynasma** [comment]
> @martynasma Can you confirm the current behavior of the date formatter, that is NOT producing a UTC Date despite specifying UTC time zone in the string, is expected?

You're right. "Z" should indicate UTC, while lack of should be treated as local time zone. Whereas our current parsing algo seems to treat everything as local.

Making a note to fix this. Will ping you here.

**Comment by martynasma** [comment]
That tooltip issue seems unrelated. Posted it separately here: #700.

Please subscribe/comment there.

**Comment by martynasma** [comment]
"i" parsing in UTC was fixed in dev version and will be released soon.

Will notify here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.0.9](https://github.com/amcharts/amcharts4/releases/tag/4.0.9).

## [4.0.9] - 2018-12-19

### Added
- `snapToSeries` added to `XYCursor`. Allows setting series to which cursor lines should be snapped. Works if one of the axis of the series is `DateAxis` or `CategoryAxis`. Won't work if both axes are `ValueAxis`.
- New example: Pie charts in Columns using JSON config.
- Export: `emptyAs` added to both CSV and Excel export options. If set, missing values will be replaced with this value (default is empty string).
- New event `"beforedisposed"` added to `Sprite`. Kicks in right before the element starts to dismantle itself.
- Italian translation.

### Changed
- Export: if no `dataFields` specify it will now look for fields in all of the data, not just the first line.
- When creating a new state on an object, it will not automatically propagate itself on object's clones if `applyOnClones = true`.
- Setting `Container`'s `setStateOnChildren` will now propage to the new value to its existing clones if `applyOnClones = true`.
- In case `deepInvalidate()` is called on `Container`, it forces labels to redraw.
- `filters` on `SpriteState` is now `List` (was `ListTemplate`). It's better for performance which does not require creating Filter template object.

### Fixed
- Clicking a hoverable/clickable object was resultin in "over" and "out" events generated next to "hit".
- JSON: properties to existing `List` items were not being applied properly.
- Using geodata in Ember app was causing errors (Issue 672).
- Export to CSV/Excel was following first line of data values. It now respects `dataFields` setting, and will replace missing values with `emptyAs` (new options setting).
- Wheel-scrolling in MacOS Safari was very slow.
- HTML-based tooltips were too small to fit the actual contents on MaCOS Safari.
- `DateFormatter` was not parsing `"i"` format as local timezone, rather than UTC.
- Sometimes bullets with `Rectangle` element in them were not positioned properly.
- If category was named `"undefined"`, it was messing up label positions on `CategoryAxis`.
- State's property value was not being applied if current value of the property was `undefined`.
- Performance of `PieChart` and `RadarChart` improved dramatically under IEs.
- In some cases `"ready"` event was not being fired.
- `FunnelSeries` with 0 (zero) value slices was not rendered correctly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
