### ISSUE TITLE
Adding resize listener to the chart breaks zoom

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#697]
Just add: 

```
chart.events.on('resize', (ev) => {
          
        });
```

to a chart that has a zoom capability 

Then try to zoom on chrome 

https://codepen.io/anon/pen/XodxzX?=true

**Comment by martynasma** [comment]
"resize" event is not what you should use if you want to detect organic changes to chart container size.

You should use "sizechanged" instead.

For the record "resize" event is used for when `resizable` element is resized via human interaction. I'm not entirely sure why the anomaly happens, though. Let's leave it for now. Let us know if "sizechanged" event works for you.

**Comment by martynasma** [comment]
Well, there's a little bit of fuzzy logic with "resize" and some other interactions-related events.

Adding a "resize" handler, automatically sets `resizable = true` on an object. Because why would you add a resize event on a non-resizable event, right?

Now, if `resizable = true` a whole new logic kicks in. This means that object, in this case chart, listens for drag actions and tries to resize itself. Hence the effect you are seeing.

Since element is not draggable, inetractions are designed to resize element with just one pointer, like mouse or one finger.

Similarly, if you would add "drag" event, you'd automatically set `draggable = true` and would be able to drag whole chart instead, and at the same time resize it using two fingers on a touch display.

While it may look whacky when used on the whole chart, not some particular elements, it's actually by design :)
