### ISSUE TITLE
Regression: Axis Fill doesn't propery fill elements when axis is scaled

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#707]
When using the `axisFills` properties on an axis that dynamically scales (e.g. only rendering every second or third month), the axis no longer applies the properties to the whole section, only to a certain part of it. The issue can be seen in https://codepen.io/chnoch/pen/JwKedJ In the codepen I'd expect the section Feb-Apr, Jun-Aug and Oct-Dec to be colored.
This used to work properly in previous versions (at least with 4.0.2), thus I tagged it as a regression.

**Comment by Chnoch** [comment]
Quick update: The codepen only shows the issue in certain screen sizes. To reproduce it make sure that e.g. the months are visible as scale (Mar, Jun, Sep, etc.) but not every month is rendered, so that some months are not visible in the scale. The issue can be seen (statically) in the following image:
![image](https://user-images.githubusercontent.com/247564/50284041-0a6c1780-0458-11e9-81c2-10999ef92de3.png)

**Comment by martynasma** [comment]
Thanks for the heads up! Will let you know when the fix is available.

**Comment by martynasma** [comment]
Heads up, we're about to release a new version. While it fixes the axis fill issue, it also introduces a behavior-breaking change.

`axisFills.template` and `ticks.template` now will be `disabled = true` by default.

So, to enable them you need to set `disabled = true`.

It's a performance-related necessary change. Sorry for the inconvenience.

**Comment by martynasma** [comment]
Fixed in [4.0.11](https://github.com/amcharts/amcharts4/releases/tag/4.0.11).

## [4.0.11] - 2018-12-24

### Added
- `"disabled"` and `"enabled"` events added to `Sprite`.
- `cursorTooltipEnabled` added to `XYSeries`  If set to `false` cursor will not trigger bullet/item tooltips on series.

### Changed
- IMPORTANT (CODE-BREAKING CHANGES) For performance reasons we no longer create axis elements if they are disabled. For the same reasons we disabled by `axis.ticks` and `axis.axisFills` by default. Previously to enable them you had to set their `strokeOpacity` and/or `fillOpacity` to non-zero. This no longer will work. You will need to set `disabled` to `false` instead.
- `axisRanges` now take their default values from `dateAxis.axisRanges.template` items (`axisFill`, `grid`, `tick`, `label`). Previously they were using the defaults from `dateAxis.renderer.label` etc. This was not comfortable and counter-intuitive.

### Fixed
- `XYChartScrollbar`'s value axis was calculating `min`/`max` with a very big step.
- Ember plugin was throwing console errors.
- Fixed occasional zoom-in issue on Mobile Safari.
- `MapChart` mouse wheel zoom direction was inverted on some browsers.
- Cursor was not snapping correctly to `DateAxis` items.
- Multiple floating columns on the same category were disappearing when scrolling the chart.
- Date range fills were off when zooming on Gantt Chart.
- Overlapping tooltips problem solved.
- When `snapToSeries` was set for a tooltip, it was flickering a lot on slower browsers.
- `alignLabels = false` on a `PieSeries3D` was causing labels to be positioned incorrectly.
- `PieSeries.dataFields.radiusValue` was not accounting for `chart.innerRadius`.
- Dynamically updating `alignLabels` for `PieSeries` did not work correctly.
- Legend: `itemValueText` only worked if `valueText` was set.
- `ValueAxis` setting `maxZoomFactor = 1` was not working as expected.
- Changing values for all data items sometimes was resulting in `ValueAxis` scale going into negative.
- Some more tooltip and cursor related issues fixed.
- Axis Fill did not properly fill the whole span when axis was scaled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Chnoch** [comment]
Thanks for the release, the axis fill now fills the whole span properly again.
However I've discovered a similar issue with the axis labels when scaling the axis. The issue is also reproducable in https://codepen.io/chnoch/pen/JwKedJ 
If the axis spans multiple days/months/years the label is not positioned according to the value defined in `dateAxis.renderer.labels.template.location = 0.5` for the whole span, but again only for the month itself (e.g. if three months are spanned, the label is centered in the first third of the span).
Do I need to set another setting as well or is this an additional bug? Do you want me to open a new ticket for this?

**Comment by martynasma** [comment]
@Chnoch Yes, could you please open a new issue?

I'm not yet sure whether it's a bug, or not :) I can see the reasoning for both kinds of placement.

For example, let's say we have a period spanning three months from Jan to Mar. That period is represented by Jan. If we place it in the middle, e.g. where Feb is, that will be very idoerienting, since "Jan" label will be directly under February data points.

If you still think that's not right, please do open a new issue, so we have a reference point to continue this discussion.

**Comment by Chnoch** [comment]
True, both approaches can be valid. 
I've created a follow-up ticket #809 in order to have a discussion point. I'd say if we can make it configurable it would be great. In my point of view the labels just look out of place with the current default behavior. But anyway, let's discuss in #809
