### ISSUE TITLE
"ready" event does not always fire (PieChart)

### ISSUE THREAD

**Issue by Eldair** [amcharts/amcharts4#709]
Hi,

I've noticed there are many inconsistencies regarding chart (tested with PieChart, XYChart) `ready` event. Sometimes it fires correctly and sometimes only after I've hovered over some data (tooltip shown).
Could you please explain it a bit more? When should it be attached (after series are added or before)?
Is it 'restarted' when data has changed or when series are removed/added?

**Comment by martynasma** [comment]
It's not restarted after data has changed. And is supposed to fire only once, when all of its descendants are "ready".

If you can reproduce a chart setup which makes the chart's "ready" event not fire, please do share it, as we'd like to fix it :)

**Comment by Eldair** [comment]
Here you go (it is a fork from PieChart example)
https://codepen.io/Eldair/pen/ebzobP

Event gets fired only after hovering on any pie slice (I suppose it is connected to tooltips somehow)

**Comment by Eldair** [comment]
Also, if ready event is not 'restarted', how can we know when chart is ready again after removing all series and adding them (or some new ones) again? Is it faster to discard and recreate entire chart object again?

**Comment by martynasma** [comment]
Obviously a bug. Thanks!

Restarting or no restarting "ready" is a philosophical question. I can see arguments for both.

We'll discuss this as well.

**Comment by martynasma** [comment]
Fixed in [4.0.9](https://github.com/amcharts/amcharts4/releases/tag/4.0.9).

## [4.0.9] - 2018-12-19

### Added
- `snapToSeries` added to `XYCursor`. Allows setting series to which cursor lines should be snapped. Works if one of the axis of the series is `DateAxis` or `CategoryAxis`. Won't work if both axes are `ValueAxis`.
- New example: Pie charts in Columns using JSON config.
- Export: `emptyAs` added to both CSV and Excel export options. If set, missing values will be replaced with this value (default is empty string).
- New event `"beforedisposed"` added to `Sprite`. Kicks in right before the element starts to dismantle itself.
- Italian translation.

### Changed
- Export: if no `dataFields` specify it will now look for fields in all of the data, not just the first line.
- When creating a new state on an object, it will not automatically propagate itself on object's clones if `applyOnClones = true`.
- Setting `Container`'s `setStateOnChildren` will now propage to the new value to its existing clones if `applyOnClones = true`.
- In case `deepInvalidate()` is called on `Container`, it forces labels to redraw.
- `filters` on `SpriteState` is now `List` (was `ListTemplate`). It's better for performance which does not require creating Filter template object.

### Fixed
- Clicking a hoverable/clickable object was resultin in "over" and "out" events generated next to "hit".
- JSON: properties to existing `List` items were not being applied properly.
- Using geodata in Ember app was causing errors (Issue 672).
- Export to CSV/Excel was following first line of data values. It now respects `dataFields` setting, and will replace missing values with `emptyAs` (new options setting).
- Wheel-scrolling in MacOS Safari was very slow.
- HTML-based tooltips were too small to fit the actual contents on MaCOS Safari.
- `DateFormatter` was not parsing `"i"` format as local timezone, rather than UTC.
- Sometimes bullets with `Rectangle` element in them were not positioned properly.
- If category was named `"undefined"`, it was messing up label positions on `CategoryAxis`.
- State's property value was not being applied if current value of the property was `undefined`.
- Performance of `PieChart` and `RadarChart` improved dramatically under IEs.
- In some cases `"ready"` event was not being fired.
- `FunnelSeries` with 0 (zero) value slices was not rendered correctly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
