### ISSUE TITLE
How to make Chart div grow depending on legend height

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#71]
Hi, 

I have the following problem: 

- I create the chart with height 100vh and width 100vh 

However, as I dynamically add labels to the chart's legent the chart starts to shrink as more labels are added. 

How can I overcome this problem 

Here is a screen shot of the result 

<img width="965" alt="screen shot 2018-06-13 at 13 36 04" src="https://user-images.githubusercontent.com/1268723/41349005-c5cb0764-6f0e-11e8-9627-b523c6371dd9.png">

And how perhaps it looks when the legend has less labels

<img width="966" alt="screen shot 2018-06-13 at 13 36 44" src="https://user-images.githubusercontent.com/1268723/41349029-d6662202-6f0e-11e8-88cb-7d34dcc2db9b.png">

**Comment by martynasma** [comment]
I'm not going to help you, because I'm jealous. You're using 9 while I'm stuck with Spartan Ultra! ;)

Seriously now, we think that it would be very intrusive for the chart to start manipulating dimensions of its own container. That's a line we're not willing to cross.

However, it should be pretty easy for you to implement some sort of code to dynamically manipulate chart container height, based on how many series there are. Something along the lines:

```
chart.events.on("inited", function(ev) {
  ev.target.svgContainer.style.height = 500 + ev.target.series.length * 50;
});
```

This will set chart height at 500px plus 50px for each series the chart has.

I know it's a bit crude, but you can probably work out a better logic for your particular needs.

**Comment by jimmykane** [comment]
Lol @martynasma actually the above code/tool we use it for testing. 

I belong to the external field testers for Suunto and I made this tool for them to compare stats etc. (nothing official though)  

And guess what charting engine I ve used ;-) 

If you want to take a look at the current live version or github https://github.com/jimmykane/quantified-self 

Btw pm/mail me for any question about the s9 or needs etc.

**Comment by martynasma** [comment]
Nice!

So, do you think the above workaround could work for you?

P.S. Jokes aside, I'm perfectly happy with my ultra :)

**Comment by jimmykane** [comment]
@martynasma  I think yes because in the prev version of Amcharts(3) I literally hacked it and I was not happy about it. 

I ll try that and get back/update the issue. Time time time is needed.
