### ISSUE TITLE
Responsive: useDefault can't be set to false

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#717]
I tried to use the responsive feature and set my own rules. I did this with the JSON configuration. Because I I the default responsive rules didn't fit to my case, I tried to deactivate them with `Chart.responsive.useDefault = false`.
First I tried to set it in the JSON configuration, but the default rules applied.
Then I tried to set them after creation of the chart, but first I got a strange "Value doesn't exist". By debugging, I found out, that it expects my own rules to have an id attribute set.
But with the id attribute set, I didn't get the exception any longer, but the default rules get applied.
Then I looked into the code:
```
	public set useDefault(value: boolean) {
		if (this._useDefault != value) {
			this._useDefault = true;

			// Run `applyRules` so that any currently applied rules can be reset
			this.applyRules();
		}
	}
```
This means, if it is set to `true`, nothing changes, neither setting the private attribute to `true` or `false`.
If it is set to `false`, the private attribute is always set to `true`!!!
There is no way to set it to false.

**Comment by martynasma** [comment]
Responsive sub-system in amCharts 4 is not yet ready for prime time. That's why we don't advertise or recommend using it.

Rudimentary functionality is there, but it's buggy and not tested thoroughly. It might show up in documentation because some of it is generated from code, so it might seem like a full-fledged feature. But, unfortunately, it's not the case.

Sorry.
