### ISSUE TITLE
LineSeries throws errors when data points all contain zero values

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#73]
There appears to be a weird NaN issue with line chart when all of the data points have a zero value. Here's an example page that shows the problem:

https://codepen.io/anon/pen/JZJeZo

In Chrome I'm getting the following error:

> Error: <path> attribute d: Expected number, " M94.5,NaN  L94.5,NaN  …".
> t.attr @ core.js:1
> e.drawSegment @ charts.js:1
> e.drawSegment @ charts.js:1
> e.closeSegment @ charts.js:1
> e.openSegment @ charts.js:1
> e.validate @ charts.js:1
> t.update @ core.js:1
> (anonymous) @ core.js:1
> e @ core.js:1

In Microsoft Edge, I'm seeing:

> SVG4601: SVG Path data has incorrect format and could not be completely parsed.

Firefox does not seem to appear.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
Good work! It appears to be working correctly now.
