### ISSUE TITLE
Sankey diagram invalidate data flash

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#732]
Hello,

If there is 2-3 charts on the same page and I try to upgrade sankey chart data the display flash as you can see here : 

https://codepen.io/ptorrent/pen/bQWNwr?editors=0010

```javascript
setInterval(function(){
  chart.data.forEach(function(c,ii){
      c.value = 10
  })
  chart.invalidateData()
},1000)
```

This happens even if the value does not change (here I always set 10)

![flash](https://user-images.githubusercontent.com/6083644/50382718-2ebd3380-06a6-11e9-9cd9-f5ba9436c23d.gif)

**Comment by martynasma** [comment]
OK, so the flashing comes from all charts trying to update themselves at the same time, every often.

amCharts 4 supports incremental chart build, meaning that if build takes longer then X milliseconds, it takes a break, or the page would become unresponsive.

With just one chart it's usually fine. With multiple charts the queue gets longer, with last charts having to wait for their turn longer.

Since they already cleared themselves preparing for updated data, but have to wait for their brothers to finish drawing, there's a split second period where chart is empty, hence the flashing issue.

We are currently figuring out a way to avoid that.

Meanwhile you can ask yourself these questions:

1) Do you need to update charts that often?
2) Can you space out updates so they don't come at the same time?

**Comment by ptorrent** [comment]
In my case, I've something like 6 column charts without live update and one pie chart.

Sankey chart is the only chart that I update every 10 sec. is it possible that this problem appears without data update on other chart ?

**Comment by Kibsgaard** [comment]
@martynasma Is there any way to disable the "take a break if something takes a long time"? 

I would rather have the webpage stall until everything is ready as we are rendering the graphs inside another application and the flashing is problematic.

**Comment by martynasma** [comment]
This doesn't seem like an issue anymore. Closing.

https://codepen.io/team/amcharts/pen/4b7a9696134aeb0ef4dbae1c21eb81af?editors=0010

**Comment by Kibsgaard** [comment]
@martynasma It seems to still be an issue when there is more data in a graph.

I made an example:
[https://codepen.io/Kibsgaard/pen/abNoZrm](url)

It would still be great with an option to disable partial frame renders. Our application updates several charts whenever the user makes a change in another application and the flashing of the charts is very distracting for the users. We are still on AMCharts 3 because of this issue and we hope you could take another look at it.
