### ISSUE TITLE
export to csv showing timestamp value rather than formatted date shown in chart

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#733]
Using the export option I am seeing timestamp values rather than the formatted date as is displayed in the chart itself.  Instead of Mon, Dec 17 I am getting the timestamp such as 1545022800000.  This is happening for csv and json.  I created a fiddle showing this at [https://jsfiddle.net/0s2zok6u/6/](https://jsfiddle.net/0s2zok6u/6/).

Am I missing a date format option on the chart itself or is there something I need to do with the export options?

**Comment by martynasma** [comment]
Normally, export will try to determine date columns from values. However, since timestamps are essentially numbers, it cannot determine whether it's a number or a timestamp.

For that we have export setting [`dateFields`](https://www.amcharts.com/docs/v4/reference/export/#dateFields_property).

To make export treat a field in data as date just `push()` its name into the list:

```
chart.exporting.dateFields.push("timestamp");
```

**Comment by martynasma** [comment]
`chart.exporting.dateFormat` is a property, not a method. It should be set using `=`:

```
chart.exporting.dateFormat = "EEE, MMM dd";
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
