### ISSUE TITLE
Ember - World map doesn't render even after upgrading to 4.0.12

### ISSUE THREAD

**Issue by nhemanth007** [amcharts/amcharts4#736]
Related to #713 

World maps doesn't render in ember app even after upgrading `amcharts4-ember` to 4.0.12

I also tried replacing world related files in node modules folder of amcharts-ember from repo https://github.com/amcharts/amcharts4-geodata. Same issue persists.

![screen shot 2018-12-26 at 10 40 39 am](https://user-images.githubusercontent.com/14033372/50433300-725daa80-08fd-11e9-9fdc-129e736027c6.png)

Console error:
<img width="306" alt="screen shot 2018-12-26 at 10 54 47 am" src="https://user-images.githubusercontent.com/14033372/50433304-7984b880-08fd-11e9-891b-9c503fa95b06.png">

Is it possible that this error is resulting from issue in core.js/maps.js?

**Comment by Pauan** [comment]
@nhemanth007 Thanks to your code, I was able to find the problem and fix it.

We'll let you know when we release a new version.

**Comment by martynasma** [comment]
Fixed in [4.0.14](https://github.com/amcharts/amcharts4/releases/tag/4.0.14).

## [4.0.14] - 2019-01-02

### Added
- New setting `zoomStep` added to `MapChart`. Allows controlling zoom in/out speed.

### Fixed
- `Series.hidden` did not work as expected.
- World map did not work in Ember.
- Eliminated multiple warnings in recent version of Chrome regarding wheel events being active.
- Fixed mousewheel zoom in IEs.
- Draggable/resizable items were not working properly on some Android browsers.
- Setting `height` to a relative value for a horizontal `ColumnSeries` column template was not working propertly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
