### ISSUE TITLE
Series.hidden does not work

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#740]
Here is a codepen example. 

https://codepen.io/anon/pen/EGXBOM 

Both series are set to hidden but this has no effect

**Comment by martynasma** [comment]
Fixed in [4.0.14](https://github.com/amcharts/amcharts4/releases/tag/4.0.14).

## [4.0.14] - 2019-01-02

### Added
- New setting `zoomStep` added to `MapChart`. Allows controlling zoom in/out speed.

### Fixed
- `Series.hidden` did not work as expected.
- World map did not work in Ember.
- Eliminated multiple warnings in recent version of Chrome regarding wheel events being active.
- Fixed mousewheel zoom in IEs.
- Draggable/resizable items were not working properly on some Android browsers.
- Setting `height` to a relative value for a horizontal `ColumnSeries` column template was not working propertly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
