### ISSUE TITLE
Custom export option for exporting multiple charts to single PDF

### ISSUE THREAD

**Issue by krishnareddyML** [amcharts/amcharts4#743]
How we would export all charts in a page to single PDF file

**Comment by RobbiesCode** [comment]
Here we go :-)

amCharts v4, like v3, uses **pdfmake** as a dependency for PDF exports. This means that you can use pdfmake's API to generate PDF documents with multiple images in them (or text, or tables). First you'll have to export your charts to base-64 image data using v4's `getImage` method.

I have created a Codepen demo to show you how to accomplish this. You'll find it here: https://codepen.io/team/amcharts/pen/7156dd8b760c8c2c04db901eb4ae2884?editors=1010.

When you click the **Export to PDF** button, the `exportToPDF` function is called. This function will loop over all charts on the web page to get their PNG base 64 image data:

```
  // chart ids
  var ids = ["chart", "chart2"];
  var chartsRemaining = ids.length;

  // loop over all charts
  ids.forEach(function(id, index){

    window[id].exporting.getImage("png", exportOptions).then(function(imgData) {

      // save image data to chart itself for later reference
      window[id].exportedImage = imgData;

      // one more chart complete :-)
      chartsRemaining--;

      // Check if we got all of the charts
      if (chartsRemaining == 0) {
        // Yup, we got all of them
        // Let's proceed to putting PDF together
        generatePDF();
      }

    });

  });
```

When all charts have been exported to image data, you can start the actual PDF generation. This code is inside the generatePDF function. Here you'll mainly make use of pdfmake's API instead of amChart's API.

```
    // begin PDF layout
    var layout = {
      "content": []
    };

    // add chart 1
    layout.content.push({
      "image": chart.exportedImage,
      "fit": [ 523, 300 ]
    });

    // finally, download our PDF
    chart.exporting.pdfmake.then(function(pdfMake) {
      pdfMake.createPdf(layout).download("amcharts4.pdf");
    });
```

The demo is based on a tutorial that was written for v3. That tutorial has some other helpful tips in it (about working with pdfmake). https://www.amcharts.com/kbase/exporting-pdf-with-multiple-charts-and-related-info/.

Other helpful pages include:

pdfmake docs
http://pdfmake.org/#/gettingstarted

IExportImageOptions (v4)
https://www.amcharts.com/docs/v4/reference/iexportimageoptions/

Exporting charts tutorial (v4)
https://www.amcharts.com/docs/v4/concepts/exporting/#Getting_raw_data

Please have a thorough look at the Codepen demo to see how everything works. Hope this helps!

**Comment by krishnareddyML** [comment]
Thank you so much, it is working perfectly at my end. I tried with V3 code earlier but unable to understand how to convert that to V4.  Happy new Year!!  :-)
