### ISSUE TITLE
XYChart live demo date axis label opacity issue

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#745]
Regarding the [live data demo](https://www.amcharts.com/demos/live-data/), where chart data is both added and removed once per second.

If you sit and watch the demo for a minute or two, you will notice some odd behavior of the x-axis label opacity and can eventually see something like this:

![untitled2](https://user-images.githubusercontent.com/23387905/50518953-85e84d00-0a86-11e9-812d-2a46e51b06c7.png)

Correct me if I am wrong, but I am pretty certain the demo is intended to ALWAYS have the opacity go from lowest (left) to highest (right), and not have weird breaks like the screenshot above.

Label opacity is being set in the demo in the
`dateAxis.events.on("datarangechanged", ...)` method.

I edited the demo to log how much time has elapsed between these `datarangechanged` events and the results are quite erratic:

![untitled](https://user-images.githubusercontent.com/23387905/50519103-52f28900-0a87-11e9-9aaf-a7d6c36a2b17.png)

...where large time differences become the cause for the opacity issue in the screenshot of the demo above.

Is there a different dateAxis event that the opacity logic should be hooked into? I guess I'm confused by the amCharts documentation of the `datarangechanged `event:

> datarangechanged: Invoked when range of the currently selected data is validated.

Why is the `datarangechanged `event not getting executed every time a datapoint is added/removed from the series? What triggers a "range" validation and why are the timing results from above so erratic even though data is added/removed on a consistent basis with new data always having new date values?

**Comment by zeroin** [comment]
Thanks for the heads up, we indeed changed how `datarangechanged` event to save cpu and now it is not fired as often as it used to be. So in this case it would be safest to use `validated` event. And it would be really complicated to answer the question about `datarangechanged` event, theoretically range should not change at all on this particular example, as it fires only when startIndex/endIndex change, but because of some rounding it is still fired. So I would not suggest to use it at all here. We will update our demos as well.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
