### ISSUE TITLE
`legendSettings` is ignored initially if legend is in external container

### ISSUE THREAD

**Issue by keikoskat** [amcharts/amcharts4#750]
In the following example, the legend displays hovered values or sums for the selected range. It works as expected until the legend is placed in an external container.

It does not seem to work when you uncommment the lines below to place the legend in div boxLeg:

```
chart.legend = new am4charts.Legend();

/*
var legendContainer = am4core.create("boxLeg", am4core.Container);
legendContainer.width = am4core.percent(100);
legendContainer.height = am4core.percent(100);
chart.legend.parent = legendContainer;
*/
```

https://codepen.io/team/amcharts/pen/55bcca900dad737247ab795ab5904bf8/?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.0.15](https://github.com/amcharts/amcharts4/releases/tag/4.0.15).

## [4.0.15] - 2019-01-04

### Added
- `color` property added to `LegendDataItem`. Can be used for coloring `label` or `valueLabel` text like `text = "[{color}] {name}"`.
- `minZoomCount` added to `Component`.
- Export now allows formatting numberic values as durations. Use newly added `durationFields` and `durationFormat` settings.

### Changed
- Export: When exporting date to XLSX, date fields will now export as true date fields in Excel (which in turn will format them according to regional settings), unless `useLocal` is set to `false`.

### Fixed
- Charts were not working properly in FireFox Extended Support Release.
- Some computer setups were not properly registering mouse movement.
- `legendSettings` was being ignored initially if legend was in external container.
- "Week year" (format code `"YYYY"`) was not being properly calculated.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
