### ISSUE TITLE
Q: Separate XYCursor zoom from baseInterval of dateAxis

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#753]
Having a chart with a DateAxis with baseInterval setted to `{count: 1, timeUnit: 'millisecond'}` for example, the XYCursor also zooms to this level. 
My Question: can I limit the zoom to only zoom to 1 minute or something?

I need a millisecond precision on the dateAxis so my series is drawn correctly. This is also in combination with range which is drawn on millisecond precision.

(Also zooming in to milliseconds will cause Chrome to throw an error: `Error: <g> attribute transform: Expected number, "translate(-Infinity,165)".`

**Comment by martynasma** [comment]
There's currently no such feature. However, we are going to implement one. Please subscribe to issue #759.

As for the error, can you provide an example chart? I could reproduce it right away.

**Comment by FrankMerema** [comment]
Sure here is an example based on the Gantt With Dates example of the demos:

https://codepen.io/anon/pen/ropMGK?editors=1111

**Comment by martynasma** [comment]
Fixed in [4.0.15](https://github.com/amcharts/amcharts4/releases/tag/4.0.15).

## [4.0.15] - 2019-01-04

### Added
- `color` property added to `LegendDataItem`. Can be used for coloring `label` or `valueLabel` text like `text = "[{color}] {name}"`.
- `minZoomCount` added to `Component`.
- Export now allows formatting numberic values as durations. Use newly added `durationFields` and `durationFormat` settings.

### Changed
- Export: When exporting date to XLSX, date fields will now export as true date fields in Excel (which in turn will format them according to regional settings), unless `useLocal` is set to `false`.

### Fixed
- Charts were not working properly in FireFox Extended Support Release.
- Some computer setups were not properly registering mouse movement.
- `legendSettings` was being ignored initially if legend was in external container.
- "Week year" (format code `"YYYY"`) was not being properly calculated.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
