### ISSUE TITLE
Legend marker per-series

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#762]
Is it possible to specify a custom legend marker per series in V4, similar to markerType property in V3? I tried to look at series.legendSettings, but it seems to only allow label text modifications, not marker shape.

I use JSON for chart configuration.

**Comment by NPC** [comment]
Thanks, @martynasma, but I am still trying to figure it out. The examples use JS, but I need it to work with JSON, and I can't get the examples to work.

Here's one from https://www.amcharts.com/docs/v4/concepts/legend/#Creating_new_markers, codepen https://codepen.io/npc42/pen/LMQdyy it shows exception “N.validatePosition is not a function”. Perhaps using legend.children is incorrect?

If I change to legend.markers.children, it no longer fails, but doesn't do anything either: https://codepen.io/npc42/pen/VqQXMr; obviously, I am accessing wrong object properties to affect it.

The above is the simplest, attempting to modify legend markers via JSON. Once I figure this out, perhaps I'll know how to apply your new example for individual custom markers.

One more question (once I get there), can I use adapters to set marker's type instead of href? I'd like to use standard triangle/rectangle, if possible.

PS V3's graph.markerType was nice and simple, sigh.

**Comment by martynasma** [comment]
You're right, the JSON example is wrong. Thanks for the heads up!

I'll need to test another solution, and update the docs.

Will ping you when that happens.

**Comment by martynasma** [comment]
Sorry, took a while.

Docs updated.

Also had to do some updates to core engine. (JSON processor was not setting empty variables like `dummyData`)

Updated code in docs is correct, but will not work until new version is released. Will ping you here when it happens.

**Comment by NPC** [comment]
No worries, thanks for looking into it.

**Comment by martynasma** [comment]
Fixed in [4.0.18](https://github.com/amcharts/amcharts4/releases/tag/4.0.18).

## [4.0.18] - 2019-01-10

### Added
- JSON: Better id checking and error reporting.

### Fixed
- Export menu no longer shows DATA menu for `MapChart` (and other charts if data is empty).
- JSON: Some empty properties like `dummyData` were not being set properly.
- Disposing a chart or series when `Legend` was enbled was resulting in error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by NPC** [comment]
@martynasma I finally got around to checking it, thanks again for your assistance. The documentation still needs useDefaultMarker adding (set to true, confusingly), then it starts displaying non-default markers.

Then I tried to use your adapter suggestion (from 2nd comment on this issue), yet struggle to make it work with standard geometry types. Can you please quickly look at the [codepen](https://codepen.io/npc42/pen/LMQdyy?editors=0010). I try to set type, direction and width (it will differ between squares and triangles), and only the “direction” adapter is called; “type” and “width” are ignored.

I only need simple triangles and squares, colored by the series' fill, so going with pre-rendered images will make it inconvenient (I'll have to generate and include individually colored image for every serie).

Btw, I also tried the array with { key: ..., callback: ... } for adapters, with the same outcome.

**Comment by martynasma** [comment]
@NPC 

OK, so there's no adapter for "type". It's a directive for JSON processor, and not part of the engine, so it won't work. And even if it was, there's absolutely no way to change the class of the object once it has been instantiated.

As for the "width" it's an accessor, which allows setting width in pixels or percent. Sort of a shortcut for the users. Actual renderer does not ever use it, it uses either `pixelWidth` or `percentWidth`, so you need to add an adapter for whichever suits your requirements: do you want to set pixel width or relative width?

That said, I would probably go the other way completely.

Since there's no way to change object's type using adapter in JSON anyway, I would rather use a callback function, which would create necessary children for the marker.

https://www.amcharts.com/docs/v4/concepts/json-config/#Callbacks

Hope that makes sense.

**Comment by NPC** [comment]
@martynasma I think I have it now, using your original suggestion, but creating several markers, and controlling which ones are disabled per series via adapters. Thank you for your feedback, your last comment that I could just create several children made me think in this direction, and of course the adapter example helped.

Here's the [codepen](https://codepen.io/npc42/pen/LMQdyy?editors=0010), if anyone is interested.

**Comment by NPC** [comment]
@martynasma hmmm, if I try to hide/show series clicking on legend items in my [codepen](https://codepen.io/npc42/pen/LMQdyy?editors=0010), the markers stay in “disabled” grey colour. Could this be a bug?

**Comment by zola-25** [comment]
I have this problem too

**Comment by runfaj** [comment]
> As for the "width" it's an accessor, which allows setting width in pixels or percent. Sort of a shortcut for the users. Actual renderer does not ever use it, it uses either `pixelWidth` or `percentWidth`, so you need to add an adapter for whichever suits your requirements:

@martynasma Regarding this comment, can you add this to the docs, both in the article, but also the class reference docs?
