### ISSUE TITLE
XYCursor Showing Incorrect Date

### ISSUE THREAD

**Issue by davidmcooper** [amcharts/amcharts4#763]
Using @amcharts/amcharts4 v4.0.14 with React to display an XYChart with a DateAxis on the x-axis.  My data has a maximum date of 2019-01-02, and my graph is plotting my data correctly, but the bubble shown in the X-Axis shows an invalid date for any datapoints which fall after the new year.  Instead of 2019-01-02, the axis label is showing 2020-01-02.  If I add an additional datapoint for 2019-01-03, the axis bubble shows 2020-01-03.

The date shown in the tooltip for the series is accurate.  This appears to only affect the axis label bubble shown for the XYCursor.

![image](https://user-images.githubusercontent.com/867436/50652155-8d5e9900-0f53-11e9-9845-67465bf8cbd2.png)

**Comment by davidmcooper** [comment]
Date comes in as Jan 02, 2019 and comes out as Jan 02, 2020.  This is in DateAxis.js

![image](https://user-images.githubusercontent.com/867436/50653937-31970e80-0f59-11e9-9dcd-e898b3af64e7.png)

**Comment by zeroin** [comment]
It appears there is a bug with YYYY date format, YYYY stands for "week year" and should not be used unless you really need it, you should instead use "yyyy". We will fix "YYYY" issue shortly.

**Comment by martynasma** [comment]
Fixed in [4.0.15](https://github.com/amcharts/amcharts4/releases/tag/4.0.15).

## [4.0.15] - 2019-01-04

### Added
- `color` property added to `LegendDataItem`. Can be used for coloring `label` or `valueLabel` text like `text = "[{color}] {name}"`.
- `minZoomCount` added to `Component`.
- Export now allows formatting numberic values as durations. Use newly added `durationFields` and `durationFormat` settings.

### Changed
- Export: When exporting date to XLSX, date fields will now export as true date fields in Excel (which in turn will format them according to regional settings), unless `useLocal` is set to `false`.

### Fixed
- Charts were not working properly in FireFox Extended Support Release.
- Some computer setups were not properly registering mouse movement.
- `legendSettings` was being ignored initially if legend was in external container.
- "Week year" (format code `"YYYY"`) was not being properly calculated.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by davidmcooper** [comment]
YYYY still produces an invalid date.  Now it shows Jan 03, 2018 when the datapoints are Jan 03, 2019.

![image](https://user-images.githubusercontent.com/867436/50698891-41bff400-1014-11e9-8ec5-d748cac8149b.png)

yyyy works correctly.

**Comment by martynasma** [comment]
That is correct. `"YYYY"` is a week year.

The week that Jan 3, 2019 is in started in 2018, which means that it's week year is 2018.

To show exact date's year use `"yyyy"` instead.

**Comment by davidmcooper** [comment]
Ah, I see.  Thanks for the clarification and the fix.

**Comment by Daniel-Prescience** [comment]
Is the logic behind this correct?

Given the date "Monday dec. 31st 2018" - that should resolve to week 1 of 2019, because that monday belongs to the first week of 2019.

If you want the year of the first day of the week (the current logic for amchart `dateFormat("YYYY")`), you would just do: `date.firstDayOfWeek.year`.
