### ISSUE TITLE
Cannot interact with charts in Safari

### ISSUE THREAD

**Issue by blin4444** [amcharts/amcharts4#769]
Seems to be a regression. Charts display, but cannot click and drag to zoom in on chart nor ChartScrollbar. Example is supposed to have an XYCursor with tooltip.

https://codepen.io/blin4444/pen/MZarPg

Also, this example is completely blank in Chrome.

Safari Version 12.0 (14606.1.36.1.9) on macOS 10.14 (18A391)

**Comment by martynasma** [comment]
Indeed, something's off. We'll be looking into why interactions do not work well on Safari.

The chart appears fine on Chrome, though. Can you try clearing your browser cache and confirming whether Chrome is still coming up blank for you?

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.0.16](https://github.com/amcharts/amcharts4/releases/tag/4.0.16).

## [4.0.16] - 2019-01-05

### Added
- New locales: Norwegian Bokmål (np_NO), Danish (da_DK).

### Changed
- Renamed Swedish locale to `sv_SE`.

### Fixed
- Interactions on MacOS Safari was broken sincle last update.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by blin4444** [comment]
Thanks. I just tried in Chrome and it didn't work initially, but did after I cleared its cache, as you suggested.
