### ISSUE TITLE
Request for robust ID checking

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#771]
Can you please add more reliable ID checking? When linking to an item ID it should be possible to output error saying ”ID so-and-so is missing”, which will help with debugging large charts.

Here's an example of current error message when cursor refers to wrong axis ID: https://codepen.io/npc42/pen/xmWggZ. It says “Cannot read property 'events' of undefined”, and at least console shows that it somehow relates to xAxis, but still took a while to narrow it down to cursor config.

**Comment by martynasma** [comment]
I see your point, and agree that it might be helpful to provide better error messages.

That said, it's more complicated than it might seem.

I'm adding as a feature suggestion and will investigate if something like that can be implemented.

Thanks for the suggestion!

**Comment by NPC** [comment]
@martynasma No worries, I know internal things can complicate this, but I know you guys are yourself interested in better error reporting / debugging process :)

**Comment by martynasma** [comment]
Fixed in [4.0.18](https://github.com/amcharts/amcharts4/releases/tag/4.0.18).

## [4.0.18] - 2019-01-10

### Added
- JSON: Better id checking and error reporting.

### Fixed
- Export menu no longer shows DATA menu for `MapChart` (and other charts if data is empty).
- JSON: Some empty properties like `dummyData` were not being set properly.
- Disposing a chart or series when `Legend` was enbled was resulting in error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by NPC** [comment]
@martynasma excellent, thank you!
