### ISSUE TITLE
No dataContext on ColumnSeries hit

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#776]
Hello,

Hit handler works for ColumnSeries, but always returns undefined dataContext (I need to know the clicked date). It does work correctly for LineSeries bullets.

Codepen: https://codepen.io/npc42/pen/wRPxZK, using JSON for chart config.

**Comment by martynasma** [comment]
This is happening because you are setting "hit" handler on the whole series. Since Series is a valid Sprite, hit event works, but as a whole, hence no particular dataItem or dataContext.

If you need to get data context on column click, you need to set the hit handler on a column template:

```
series.columns.template.events.on("hit", ....);
```

Or, in JSON config:

```
series: [{
  // ...
  columns: {
    // ...
    events: {
      hit: ....
    }
  }
}]
```

**Comment by NPC** [comment]
@martynasma That makes perfect sense, and works. Thank you!

PS Are there any suggestions to approximate X position when clicking a line segment? Should I raise a separate issue for this?

**Comment by martynasma** [comment]
X position is probably better to derive from the position of the cursor.

When click happens, check `chart.cursor.xPosition`.

More details:
https://www.amcharts.com/docs/v4/tutorials/tracking-cursors-position-via-api/

That is if you are using `XYCursor`.
