### ISSUE TITLE
Legend: Values column arrangement

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#786]
How is it possible to have column arrangement for the legend values, like in the documentation [https://www.amcharts.com/docs/v4/concepts/legend/#Value_labels](https://www.amcharts.com/docs/v4/concepts/legend/#Value_labels)?
There is no example for that. I want to achieve, that it looks like on the left image, where the values align to the right, and all label/value entries have the same width in its column.

**Comment by notacouch** [comment]
Well to start with, as the guide mentions you'll have to utilize the `valueLabel`s


Here's a demo:
https://codepen.io/team/amcharts/pen/b43a2e6dba1dec63d6964bb31ba3cc9e

**Comment by notacouch** [comment]
Thanks for the feedback. You're right, there isn't a demo to match that image, our apologies about that.

We'll use the guide as a starting point, at least. Both the legend's regular label and its [`valueLabel`s](https://www.amcharts.com/docs/v4/reference/legend/#valueLabels_property) must be used so we can have distinct columns.

This can be set on a per series basis, e.g.:
```javascript
series1.legendSettings.labelText = "Series: [bold {color}]{name}[/]";
series1.legendSettings.valueText = "{valueY.close}";
```

To change the orientation of the legend so it's top-down instead of left-to-right:

```javascript
chart.legend.layout = "vertical";
```
Your labels, both the text-based and `valueLabel`s, will probably auto-size based on their content. You can hardcode some widths to ensure both same-width columns and alignment, e.g.

```javascript
chart.legend.labels.template.width = 150;
chart.legend.valueLabels.template.width = 40;
```

The `valueLabels` template by default already has settings to ensure they are aligned and text-aligned to the right. So with the tabular structure in place via hardcoded widths, you'll find they ought to align sensibly.

Here's a demo:
https://codepen.io/team/amcharts/pen/b43a2e6dba1dec63d6964bb31ba3cc9e

**Comment by CipSoft-Components** [comment]
@notacouch thank you for the hint. I now use something like the following, to have it more dynamic and not hard coded:
```
function adjustLegend() {
  var maxLabelWidth = 0;
  for (var i in chart.legend.labels.values) {
    var label = chart.legend.labels.values[i];
    if (label.measuredWidth > maxLabelWidth) {
      maxLabelWidth = label.measuredWidth;
    }
  }
  chart.legend.labels.template.minWidth = maxLabelWidth;

  var maxValueLabelWidth = 0;
  for (var i in chart.legend.valueLabels.values) {
    var label = chart.legend.valueLabels.values[i];
    if (label.measuredWidth > maxValueLabelWidth) {
      maxValueLabelWidth = label.measuredWidth;
    }
  }
  chart.legend.valueLabels.template.minWidth = maxValueLabelWidth;

  chart.legend.invalidate();
}

chart.legend.events.off('ready', adjustLegend, this);
```
This will adjust the min values every time the legend is redrawn, and get the min value from the measured values from amCharts.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
