### ISSUE TITLE
Data export in map charts support?

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#793]
When enabling export in the map chart type, the data option is available but all of the data formats return empty files because the data property is typically set at the series level, but setting it at the chart's top level data property will make it work. 

I'm not quite sure if that's a fluke, especially since v3 didn't support data export in maps. Is this the official way to allow data export in maps? If so, we should probably add a call-out for it. If it isn't meant to be supported, we should probably hide the option.

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.0.18](https://github.com/amcharts/amcharts4/releases/tag/4.0.18).

## [4.0.18] - 2019-01-10

### Added
- JSON: Better id checking and error reporting.

### Fixed
- Export menu no longer shows DATA menu for `MapChart` (and other charts if data is empty).
- JSON: Some empty properties like `dummyData` were not being set properly.
- Disposing a chart or series when `Legend` was enbled was resulting in error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
