### ISSUE TITLE
Question: Can a Series share with another Series the same value Axis? 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#797]
Hi, 

I trying to achieve the following: 

- I have a set of series that represent a type , eg `Altitude`, `Cadence`, `Power`, `Cadence #2`. 
- I plot the series on the chart with their own value Axis. 
- However, for those of the same type, having an extra yAxis to represent the same "type" is a bit redundant. 

So in the above I would like the `Cadence` and `Cadence #2` series to share the same yAxis. 

If the created series do not have a yAxis they share the one that is attached to the Chart. 

So how can I achieve: 

- Some series sharing the same yAxis, while others having their own?

**Comment by jimmykane** [comment]
What I did try is to create one yAxis for both and assign it to both with 0 luck (it errored)

**Comment by Achilles1515** [comment]
Here is an example. The series "Hits" and "Fourth" are on the same y-axis.

https://codepen.io/anon/pen/aPjeVv

I just modified [this demo](https://www.amcharts.com/demos/multiple-value-axes/) and added another series, "Fourth", and then added a conditional statement to use the previously created y-axis for the "Fourth" data set instead of making a new one.

It sounds like what you were doing is correct, though, with the main thing being setting `series.yAxis` for multiple series to the same y-axis instance.

**Comment by martynasma** [comment]
I agree with @Achilles1515 

You create one ValueAxis instance, then assign that instance to `yAxis` on both Cadence and Cadence #2 series.

**Comment by jimmykane** [comment]
Yup. Thanks guys it worked like a charm.
