### ISSUE TITLE
XYChart cursor's X-axis tooltip not showing hours

### ISSUE THREAD

**Issue by blin4444** [amcharts/amcharts4#819]
In my data, I have a dummy datum to artificially expand the viewport. It seems this datum causes the tooltip to not show hours. The datum's date has nonzero milliseconds, while the rest of the data's dates' milliseconds are zero.

![screen shot 2019-01-14 at 5 31 21 pm](https://user-images.githubusercontent.com/2326556/51152799-43fb2d00-1822-11e9-910f-eee2b041345f.png)

Minimal example: https://codepen.io/blin4444/pen/roPpVm

**Comment by martynasma** [comment]
This is happening because your you have time span of several minutes. So the date axis is in "seconds" mode. Which means that each label/increment on the axis is a second, hence no milliseconds.

If you zoom in really close, where span is less than a second, you will notice the axis switches to milliseconds mode and milliseconds will start to appear.

You could also set `dateAxis.snapTooltip = false;` but that would mean you would be losing the series tooltip, at least with your current data, where data points are very far apart in terms of milliseconds.

That should not be a problem, though, if your real data comes pretty close every few milliseconds.

**Comment by blin4444** [comment]
I see. Is it normal for the hour to not show up in the tooltip though, given that the data spans several minutes? The tooltip just says, for example, "54:05 0", instead of "14:54:05 0" currently.

**Comment by martynasma** [comment]
Yes, because the tooltip uses date format for the chart's data granularity.

Though, you can force a specific date format for the tooltip using axis' [`tooltipDateFormat`](https://www.amcharts.com/docs/v4/reference/dateaxis/#tooltipDateFormat_property).

**Comment by blin4444** [comment]
The problem is that if I remove the dummy data point, or if I change its value slightly, then the behavior I described is not exhibited, and the hours are shown: https://codepen.io/blin4444/pen/magLEK.

**Comment by martynasma** [comment]
By adding dummy data points at less than second intervals, you trick your chart to think it is in "millisecond" mode, and use millisecond format for tooltips.

In your second codepen data points come at more than a second intervals, so it is in "second" mode, hence second format is used in tooltip.

In your dummy data version you can use  `tooltipDateFormat` to force specific format for tooltips, or force your date axis into second mode using `baseInterval`:

```
dateAxis.baseInterval = {
  timeUnit: "second",
  count: 1
}
```

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
