### ISSUE TITLE
Question: Tooltip which updates by cursor move

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#821]
How can I set a mouse following tooltip (for axis range or plot area), which updates (e.g. with adapter on tooltipText) on cursor move?
I tried different ways, but the tooltip always only updates if I hit a grid line or something else. So it often do not update at all, because the cursor do not hit anything (even if I cross a grid line, because it was too fast, or because the grid line is dashed).

**Comment by CipSoft-Components** [comment]
@martynasma thank you for the hint. I tied this, but no matter which redraw method I call on the tooltip, it is not calling the adapter I defined for `tooltipText`. The adapter itself works, it only not works when calling `invalidate` or similar on the `axisFill`s tooltip. I don't know how to force the tooltip, to update its content.

**Comment by martynasma** [comment]
Can you produce a CodePen chart with your setup? I'll see what I can do.

**Comment by CipSoft-Components** [comment]
@martynasma I modified the example from the issue #842 to show what the problem is:
https://codepen.io/anon/pen/bzGWXy
In the code, there are some invalidate methods I called, but the tooltip is not updating. Here it shows the current timestamp if the mouse moves over the axis range. In my real project, it shows a combined tooltip of overlapping axis ranges. But the working solution I found with `showTooltip`, produces errors, when a new chart is redrawn into the same `div`.

**Comment by martynasma** [comment]
OK, so we've been able to identify the bug. We're going to release a new version today or tomorrow, which should fix the issue you are having after chart redraw.

Thank you for your patience! :)

**Comment by martynasma** [comment]
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
