### ISSUE TITLE
createFromConfig removes axisRanges attribute from xAxes configuration

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#824]
When creating a chart with `createFromConfig`, the attribute `axisRanges` is removed from the axis objects of the `xAxes` configuration of the original configuration object.
Is this by design? If so, why?

**Comment by martynasma** [comment]
Yes. It's due to internal organizational reasons.

Important thing to understand is that JSON object passed into `createFromConfig` might and probably will be mutated, so you should not rely on it to coming out of it intact.

If you absolutely need to reuse the same object, you need to clone the config object beforehand.

I noticed we don't have this warning in our docs, which is an oversight. Sorry. I'm making a note to correct that.

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.
