### ISSUE TITLE
Question: When exporting a chart how can we include the legend if it's on an outside container?

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#835]
When I export a chart to PNG for example the legend is not in the produced imaged. 

Is there a tip/ way to include that?

**Comment by martynasma** [comment]
Excellent question. You get a medal :)

There's currently no (easy) way to do that. It would require producing canvas snapshots of chart and the legend separately, then combining it into a single canvas, then producing it for download.

```
chart.exporting.getImage( "PNG" ).then( ( data ) => {
  var = data;
} );
```

This is way too complicated. However if you're game, you might take a stab at implementing it.

I'm making a note to produce either a detailed tutorial or implement this feature into Export.

Can't promise any particular timeline, though.

**Comment by NPC** [comment]
Oof, this hurts, considering that legend scrolling is only possible in a separate container (looking at [this](https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Making_legend_scrollable))…

**Comment by martynasma** [comment]
@NPC No pressure, huh? :)

**Comment by NPC** [comment]
Well, dealing with legend on dynamically-generated charts (users have control over which series they add etc) is painful on V4, I'm sorry to say. I hope you get around to improving it (if scrolling can be done without an external container, then I'm fine with this export issue, tbh, but from other discussions it seems like you don't even plan to do it — or should I raise an enhancement request?).

**Comment by martynasma** [comment]
We've implemented this in dev.

Will post more details when released.

**Comment by jimmykane** [comment]
Woop woop!

**Comment by martynasma** [comment]
Fixed in [4.2.0](https://github.com/amcharts/amcharts4/releases/tag/4.2.0).

## [4.2.0] - 2019-03-06

### Added
- Added read-only property of `CategoryAxis`: `frequency`. Indicates every X label is shown.
- Added JSON example of Candle stick chart (json/candlestick-series).
- New `Export` property: `extraSprites`. May contain a list of references to other `Sprites` (e.g. external legend or even other chart) to attach to exported image. [More info](https://www.amcharts.com/docs/v4/concepts/exporting/#Including_external_elements).
- Experimental responsive features and default rules are now active. [More info](https://www.amcharts.com/docs/v4/concepts/responsive/).

### Changed
- Accessibility: Default role of the Legend's item containers was changed to "switch".

### Fixed
- Accessibility: Legend's containers when toggling items were setting value of `aria-checked` incorrectly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by martynasma** [comment]
More info related to external legend:
https://www.amcharts.com/docs/v4/tutorials/chart-legend-in-an-external-container/#Including_external_legend_in_export

**Comment by buni-buni** [comment]
when I am trying to add external legend my chart image expoer  **chart.exporting.extraSprites**  is coming undefined. :(
unable to understand y chart.exporting doesnt has this extraSprites . :(
