### ISSUE TITLE
ChartScrollbar grip and graph positioning

### ISSUE THREAD

**Issue by blin4444** [amcharts/amcharts4#845]
I'm trying to use multiple standalone XYChartScrollbars for data from different date ranges for one merged dataset. I'm having trouble getting the grips of the different XYChartScrollbars to align.

Is it possible to remove the gap in between the plotted data and the left/right edges of the XYChartScrollbar? And, is it possible to precisely set the grip position to a datum's date?

In [this example](https://codepen.io/blin4444/pen/WLBVwY), I'm trying to set the grips' positions to the start/end of the data inside the main chart + external XYChartScrollbar when the button is clicked, but there's a bit of an offset, and I'm not sure how to compute the offset. I tried disabling the Y-axis on the XYChartScrollbar but there's still an offset.

**Comment by blin4444** [comment]
Yes, those gaps are what I'm referring to. I just tried setting the startLocation/endLocation options on both the main chart's and the XYChartScrollbar's X-axes, but after clicking the button to set the grips to the data point's locations, I get -0.03333333333333333 and 0.95 for the first and second data point's locations, respectively, from calling DateAxis.dateToPosition.

https://codepen.io/blin4444/pen/WLBVwY

**Comment by martynasma** [comment]
Well, this is happening because data point timestamp refers to the particular point in time.

However, the actual point is shown in the middle of a DateAxis cell. In your case it's a 30 second period.

So when you use data point's timestamp to position grips, you don't get actual zoom scope of the upper chart.

What you should probably do, is check upper charts' date axis and its `start` / `end` properties, that will hold positions of the actual zoom.

```
  externalChartScrollbar.start = dateAxis.start;
  externalChartScrollbar.end = dateAxis.end;
```
