### ISSUE TITLE
Map legend position is ignored

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#872]
For me it displays on top, though I set it to "bottom": https://codepen.io/npc42/pen/exmmjL?editors=0010

This happens even in the manual example: https://www.amcharts.com/docs/v4/chart-types/map/#Multiple_polygon_series, yet there is it set to "right", but shown on the left.

**Comment by martynasma** [comment]
This is due to a (fairly) recent change in how MapChart is layouted.

The Legend is not placed into a separate container anymore but rather into `chartContainer` which does not have a strict layout, hence `postion` being ignored.

Use legend's `valign` to bottom-align it:

```
chart.legend.valign = "bottom";
```

Thanks for the tip about docs. Sometimes those lag behind. Fixed now.
