### ISSUE TITLE
karma es6-transform test error with dynamic import

### ISSUE THREAD

**Issue by anotherapj** [amcharts/amcharts4#875]
I'm using Karma test runner for my Anguar 4 project. After installing the amcharts4, when I run the test-headless, the es6-transform is unable to understand the dynamic import and it is throwing error.
Karma.conf.js
`karmaTypescriptConfig: {
          bundlerOptions: {
            entrypoints: /\.spec\.ts$/,
            transforms: [
              require('karma-typescript-angular2-transform'),
              require('karma-typescript-es6-transform')()
            ]
          },
          compilerOptions: {
            lib: ['ES2015', 'DOM']
          }
        }`

error when running the test-headless
```
23 01 2019 05:02:41.833:ERROR [source-reader.karma-typescript]: Error parsing code: Unexpected token (2675:49)
in /<project>/node_modules/@amcharts/amcharts4/.internal/core/export/Export.js
at line 2675, column 49:

 ...import(/* webpackChunkName: "canvg" */ "canvg")];
```

I have tried upgrading the typescript to 2.8 from an older version, but the error still exists. Any help is appreciated.

**Comment by Pauan** [comment]
I believe this is related to #868, so hopefully fixing that will fix this too.

**Comment by Pauan** [comment]
@anotherapj I did some research, and it seems like Karma doesn't support dynamic `import()` natively, but you can [use karma-webpack to get dynamic `import()` working](https://medium.com/lacolaco-blog/setting-up-angular-2-testing-environment-with-karma-and-webpack-e9b833befd99).

In addition, make sure you're using Webpack version 4.28.4, since the latest Webpack has issues with `import()`.

Because this isn't an issue with amCharts, I'm going to close this.
