### ISSUE TITLE
Duration as xAxis leaves empty space at the end 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#876]
Hi when using a durationAxis for xAxis on the chart I get this strange behavior: 

<img width="1042" alt="screenshot 2019-01-23 at 14 45 00" src="https://user-images.githubusercontent.com/1268723/51610620-7a6d3200-1f1d-11e9-9076-975538d7643c.png">

As you can see there is an empty portion on the chart to the right. 

This is reproducable here : 

https://codepen.io/anon/pen/GzgLWK?=true

And here is a screenshot of the above codepen. 

<img width="1435" alt="screenshot 2019-01-23 at 14 46 06" src="https://user-images.githubusercontent.com/1268723/51610686-a25c9580-1f1d-11e9-81cb-fb0ce917f57c.png">

I am not sure if this is a bug but worth to mention or hear advice how to proceed.

**Comment by martynasma** [comment]
This is because DurationAxis, just like ValueAxis will "round" the scale to a full time period, say an hour, or 10 minutes like in your codepen.

Probably easiest way around it is to set `max` explicitly:

```
categoryAxis.max = 500;
categoryAxis.strictMinMax = true;
```

That said, I can totally see how it would be useful to cap the scale at the highest value.

Since this is related to any `ValueAxis`-based axis, I have opened a new enhancement issue for it: #878
