### ISSUE TITLE
Legend's default State breaks when using relative sizes and responsive features

### ISSUE THREAD

**Issue by federicomoretti** [amcharts/amcharts4#879]
Hello, I'm using a simple Map with a Legend on the bottom right corner. Once I enable the `responsive` feature and resize the screen, the legend is incorrectly positioned.

I created a very simple case to reproduce it: https://codepen.io/federicomoretti/pen/OdVVBQ
In this example, when the screen width is less than 400px, I move the Legend to the top left corner.

I noticed that this seems to only happen when the Map/Chart has relative sizes (in this case `height: 100%`). But I'm not sure if that's the only case.

**Comment by martynasma** [comment]
Oh man, you found responsive, huh? :)

That functionality is there, but is not yet ready for prime time, hence us not promming it anywhere.

I'll mark it as a bug, but can't provide any ETA or immediate solution right now.

Will get back to it once we finalize that part of the package.

**Comment by martynasma** [comment]
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
