### ISSUE TITLE
Why doesn't ColumnSeries have segments like a LineSeries?

### ISSUE THREAD

**Issue by taylorehat-cs** [amcharts/amcharts4#880]

**Comment by notacouch** [comment]
I'm not sure I understand the question. They're different series that don't inherit from one another. Both the [LineSeries](https://www.amcharts.com/docs/v4/reference/lineseries/#Inheritance) and [ColumnSeries](https://www.amcharts.com/docs/v4/reference/columnseries/#Inheritance) extend XYSeries. You'll find that [LineSeries' `segments`](https://www.amcharts.com/docs/v4/reference/lineseries/#segments_property) list template is not inherited, rather it's unique starting at LineSeries. Instead of having [line] segments, a ColumnSeries has a [`columns`](https://www.amcharts.com/docs/v4/reference/columnseries/#columns_property) list template.

Similarly, a PieChart's PieSeries has a slices list template, a MapChart's MapPolygonSeries has a mapPolygons list template, and so on.

Can you elaborate what the issue is?

**Comment by taylorehat-cs** [comment]
In a line series, we can setup interactions that will allow a user to interact across a category using the `segments`:
https://codepen.io/taylor-cs/pen/qQyreE?editors=1010

The code is almost entirely interchangeable by just changing `am4charts.LineSeries()` to `am4charts.ColumnSeries()` except a Column Series doesn't have the same concept as being able to interact with all columns of a series as a group rather than as individual columns. Is there to do that currently?

Columns example where interactions are only limited to individual columns:
https://codepen.io/taylor-cs/pen/OdyRvJ?editors=1010

**Comment by notacouch** [comment]
If you want to hover over all columns in a series, you can do so via states, i.e. when hovering over the parent, all the children can get the same state (if both have said state key), e.g.

```javascript
    series.columnsContainer.states.create("hover");
    series.columnsContainer.setStateOnChildren = true;
```

Here's a demo:
https://codepen.io/team/amcharts/pen/ac07b777f32fbaad1577fef88e08c182
