### ISSUE TITLE
4.0.23  breaks legend markers 

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#891]
Hi with 4.0.23  all markers (also in docs ) are broken (dont change style) 

ref https://www.amcharts.com/docs/v4/tutorials/using-adapters-to-modify-legend-item-appearance/#Modifying_individual_markers

**Comment by martynasma** [comment]
Fixed in [4.0.24](https://github.com/amcharts/amcharts4/releases/tag/4.0.24).

## [4.0.24] - 2019-01-25

### Fixed
- `nonScalingStroke` (broken in 4.0.23) fixed.
- Legend custom adapters problem (broken in 4.0.23) fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
