### ISSUE TITLE
MapLineSeries nonScalingStroke different in v4.0.23

### ISSUE THREAD

**Issue by NPC** [amcharts/amcharts4#893]
Not sure if that was your intention, but line/arrow size now scales with zoom, you can see in your own [demo](https://www.amcharts.com/demos/map-with-curved-lines/), thickness of lines and size of arrows increases as you zoom in. It actually doesn't look bad (at least it is consistent — the arrow used to become smaller on zoom, I mentioned it as a side note in #873), but that's not how it worked before.

**Comment by martynasma** [comment]
Fixed in [4.0.24](https://github.com/amcharts/amcharts4/releases/tag/4.0.24).

## [4.0.24] - 2019-01-25

### Fixed
- `nonScalingStroke` (broken in 4.0.23) fixed.
- Legend custom adapters problem (broken in 4.0.23) fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
