### ISSUE TITLE
Issue : Type mismatching in am4core.create function

### ISSUE THREAD

**Issue by etranchi** [amcharts/amcharts4#90]
Hello,

I'm using amcharts with Typescript : 
- amcharts version : 4.0.0-beta.29
- typescript version : 2.9.2

I was doing the tutorial about the XYChart, then on creating the instance of the chart : 
```
this.chart = am4core.create('chartdiv', am4charts.XYChart);
```
i get this type mismatch : `typeof XYChart not assignable to new () => Sprite`

What is the right way to create a XYChart with correct typings ?
Otherwise the chart seems to work fine.

**Comment by martynasma** [comment]
Fixed in [4.0.22](https://github.com/amcharts/amcharts4/releases/tag/4.0.22).

## [4.0.22] - 2019-01-23

### Added
- 23 new locales: Arabic, Bosnian, Catalan, Czech, Greek, Estonian, Finnish, Hebrew, Hindi, Croatian, Hungarian, Indonesian, Japanese, Korean, Latvian, Polish, Romanian, Serbian, Thai, Turkish, Vietnamese, Chinese (simplified and traditional versions). Thanks Bjorn Svensson!

### Fixed
- It is no longer necessary to use `"strictFunctionTypes": false`, [thanks to goloveychuk for their help](https://github.com/amcharts/amcharts4/pull/645).
- Broken images were causing export to fail.
- Setting Series' `name` to a number with percent sign was resulting in breakage of the whole chart.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
