### ISSUE TITLE
Export error with image watermark

### ISSUE THREAD

**Issue by Dongjin-Dongdor** [amcharts/amcharts4#902]
Hello. 
When I use watermark with image, export function makes empty file. 
Even though I can check image file on my local, the image show anything. Only SVG file is working. 
Please check this error

I used explorer version 11 and chrome.
Thank you :)

**Comment by RobbiesCode** [comment]
Due to security measures, implemented in all modern browsers, export won't work when loaded locally, via `file://`.

In order for export to work properly, the web page needs to be loaded via web server, even if it's `http://localhost/`.

Refer to the "Common Pitfalls" section of our Exporting Charts article: https://www.amcharts.com/docs/v4/concepts/exporting/#Common_pitfalls.

Hope this helps!
