### ISSUE TITLE
Daylight saving time creates unexpected chart

### ISSUE THREAD

**Issue by bmampaey** [amcharts/amcharts4#903]
When plotting an XYChart whith a DateAxis for X and a ValueAxis for Y, using UTC times, the chart makes a unexpected Z when Daylight saving time occurs (for example 28th of October 2018)

![daylight saving time](https://user-images.githubusercontent.com/3693702/51902133-94918f00-23b9-11e9-98f0-2bcaf8cb54b5.png)

I made a codepen to show the strange behavior :
https://codepen.io/Benjamin-Mampaey/pen/PVGGgB

Edit:
I noticed that if instead of using "inputDateFormat" : "i", I use "inputDateFormat": "yyyy-MM-DDTHH:mm:ss", then the result is as expected
https://codepen.io/Benjamin-Mampaey/pen/YBpePQ

**Comment by martynasma** [comment]
Just an update: we're still trying to figure out the best way to work with DST switches.

Meanwhile, let me comment about your setup. The ISO "i" date format calls for milliseconds, but yours does not have any: "2018-10-28T00:00:00Z". While adding milliseconds will not solve the immediate issue, just wanted you to know.

As for `"yyyy-MM-DDTHH:mm:ss"` working, I don't know why it works :) but it's definitely not right. Uppercase `"DD"` means "year day" as in "day from the start of the year", so in terms of full date it's definitely not right.

Will keep you posted about the further progress.

**Comment by bmampaey** [comment]
Thank you for your remarks.
 
Indeed the uppercase D makes it that the dates are shifted to January when there is no DST, and that is why the problem did not appear. Changing the D to lowercase ("yyyy-MM-ddTHH:mm:ss"), dates are correctly parsed, and the problem with DST shows again.

**Comment by martynasma** [comment]
Heads up, this will be fixed in the next version to be released within the next few days.

**Comment by martynasma** [comment]
Fixed in [4.1.6](https://github.com/amcharts/amcharts4/releases/tag/4.1.6).

## [4.1.6] - 2019-02-12

### Added
- New plugin chart type: [`Sunburst`](https://www.amcharts.com/docs/v4/chart-types/sunburst/)!
- New `Sprite` adapter: `criticalError`. Takes `Error` object as an argument. Modify it's `message` property.

### Fixed
- Export was somewhat broken in Angular apps or pages with `<base>` since 4.1.5.
- `DateAxis` was not positioning elements properly when spanning switch to/from daylight savings time.
- `valign` property of the horizontal axis labels now work properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
