### ISSUE TITLE
How is the "start" and "stop" positions of a linear gradient defined?

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#905]
I would like to create a linear gradient such that no matter the shape of the chart, the same value on the y axis leads to the same color at that height.

Here's what I tried so far.
https://codepen.io/andili99/pen/xMEaMO

If you zoom into one of the yellow peaks (but not the highest peak), it will change colour and the peak becomes red. My goal is to have values at the top of the chart be pure red, and values at the bottom to be green. It would be great to be able to manually define the start and stop positions to be the top and bottom of the chart.

**Comment by RobbiesCode** [comment]
At this moment there is no built-in setting to "glue" the gradient start & end positions to certain min & max values on the value axis.

However, you can create an extra series that holds a "fixed" gradient, then use your actual line series as a mask to your gradient line series. Here's how that works:

Add a `minValue` and `maxValue` field to all your data items. This will define the "value span" of your gradient. 

```
  var minValue = 0;
  var maxValue = 35;

  data.push({
    date: new Date().setSeconds(i - 100),
    value: visits,
    minValue: minValue,
    maxValue: maxValue
  });
```

Then, define your gradient:

```
var gradient = new am4core.LinearGradient();
gradient.addColor(am4core.color("green"));
gradient.addColor(am4core.color("blue"));
gradient.addColor(am4core.color("yellow"));
gradient.addColor(am4core.color("red"));
gradient.rotation = 270;
```

Now you're ready to add a gradient line series. Make sure the gradient series comes before your actual line series:

```
// add gradient series for min until max (full gradient)
var gseries = chart.series.push(new am4charts.LineSeries());
gseries.dataFields.valueY = "maxValue";
gseries.dataFields.openValueY = "minValue";
gseries.dataFields.dateX = "date";
gseries.fillOpacity = 0.5;
gseries.strokeWidth = 0;
gseries.fill = gradient;
gseries.ignoreMinMax = true;
```

Set this series' fill to your `gradient` and set `ignoreMinMax` to **true** so this line series will not affect your value axis extremes while zooming.

Last thing to do is mask your gradient series `segments` with your actual line series segments:

```
series.events.on("inited", () => {
  // loop through all
  for (var i = 0; i < gseries.segments.length; i++) {
    gseries.segments.getIndex(i).mask = series.segments
      .getIndex(i)
      .children.getIndex(0);
  }
});
```

Here's the final Codepen: https://codepen.io/team/amcharts/pen/omYZyx?editors=1010.

You can also use this technique for Column Series. Instead of applying the mask on `segments`, you apply the mask on `column`. Column Series demo: https://codepen.io/team/amcharts/pen/ZwBLxv?editors=0010.

Hope this helps!

**Comment by AndiLi99** [comment]
Wow, this is exactly what I was looking for. Thank you so much!

**Comment by AndiLi99** [comment]
Hi again, I've modified the code to produce 1000 points and the masking seems to break. Is this intended?

**Comment by AndiLi99** [comment]
Modifying the event to be "ready" instead of "inited" seems to solve the problem.

**Comment by martynasma** [comment]
There currently is no "official" chain of events list, I'm afraid.

There are a lot of stuff going on in charts when something happens, with a lot of events being fired on various elements, so it would be too difficult to produce one, at least not in the meaningful sense.

These types of chains are best implemented by observation.
