### ISSUE TITLE
Chart tooltips not always positioned in the viewport

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#91]
Tooltips are not always positioned in the viewport. This happens when you use the `tooltip.label.maxWidth` property to allow a tooltip to expand larger than it's parent container. We need to set the `maxWidth` because we're showing some pie charts in a very small space and if we don't set the `maxWidth`, the tooltips do not render properly (or very readable).

In IE11, this has the unfortunate side effect of adding an X scrollbar to the body element that never goes away (because the tooltip remains in the DOM taking up space, it's just hidden).

Here's an example that shows the problem:

https://codepen.io/anon/pen/gKvyPY

![amcharts_tooltip_viewport_issue](https://user-images.githubusercontent.com/900497/41658377-2d116e04-7464-11e8-8677-f22f090a1332.gif)

If you mouse over the light blue slice, you can see the tooltip causes an overflow on the body element. In IE11, the scrollbar doesn't go way.

Tooltips should always be positioned inside the viewport.

**Comment by martynasma** [comment]
This might be complicated, because we'd need to not only check whether it fits into chart container (because that influences its behavior), but also whether it fits into viewport, which adds another costly measuring operation.

That said, I agree that hidden tooltip should not have any effect on document size.

We will investigate wheater this can be resolved intelligently somehow.

Meanwhile, have you considered applying some kind of restriction, like `overflow: hidden` to your document body?

**Comment by martynasma** [comment]
Gotcha. Just wanted it on the table in case you haven't considered it.

I'll keep this open until we have had a chance to figure something out.

Thanks!

**Comment by martynasma** [comment]
Hey, we've just noticed this was still open, even though it was fixed a while ago.

I'm gonna go ahead and close this, but feel free to reopen should you still experience the issue.

**Comment by dswitzer** [comment]
@martynasma 

While it does indeed stay in the viewport, in IE you still get the X scrollbar to the body element that never goes away (because the tooltip remains in the DOM taking up space, it's just hidden).

(See the last part of the issue description for more details.)

**Comment by martynasma** [comment]
Oh OK, missed that one. Sorry.

We'll see if we can do something about it.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.45](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.45).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

## [4.0.0-beta.45] - 2018-08-17

### Added
- New hardcoded `Sprite` state name added `"hoverActive"` which (if defined) is applied on active elements on hover. This state is applied last in the chain.
- New property on `DataSource`: `keepCount`. If set to `true` incremental updates will remove data items from the beginning of the current dataset, when adding the newly-loaded ones.
- New property on `DataSource`: `incrementalParams`. It's an object whose key/value pairs will be added to URL as parameters when DataSource is making an incremental load request.
- `Popup` (and `Modal`) now have an event dispatcher (`events`) with two events: `"opened"` and `"closed"`. ([more info](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Event_handlers))

### Changed
- Legend now respects `itemContainers.template.togglable = false`, which disables default functionality of toggling items when clicked in legend, allowing users to attach their own funcitonality to legend item clicks.
- Toggling of items in Legend can now be disabled by setting `chart.legend.itemContainers.template.togglable = false`.
- In `XYChart` with a `DateAxis`, cursor and data at irregular intervals will now display a Tooltip for nearest available series' data item.
- `zoomToCategories` method of `CategoryAxis` now zooms to the end of the "to" category.
- Default `urlTarget` of amCharts logo is now `"_blank"`.

### Fixed
- In `DataSource` the formatters `inputDateFormat` was ignored.
- Incremental data load via `DataSource` was not working.
- Tooltip used to flicker ar 0,0 position in some cases when hovering over elements.
- Fixed issue which caused chart to gradually shrink to invisibility under some conditions.
- Fixed rendering errors for charts that were initialized in hidden containers.
- `XYCursor` lines and axis tooltips were not shown if chart did not have any data (data was set directly on axis/series).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

**Comment by dswitzer** [comment]
FYI - Still broken in beta 48.

**Comment by dswitzer** [comment]
@martynasma 

The fact that the tooltips in Edge/IE end up adding the horizontal scrollbar (X coordinate) was causing us issues yesterday with a fixed position element.

In looking into the issue, the problem appears to be caused by the use of transform. I found a couple of links which indicate that transforming an element can lead to overflow issues:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15645603/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13475965/

I played around with seeing if any CSS rules would fix the issue. I could use:

```css
g[role='tooltip'][visibility='hidden'] {
	display: none;
}
```

And that gets rid of the scrollbars when the tooltip isn't shown, but it causes issues calculating the size of the tooltip bubble.

This sort of works, but wasn't always getting ready of the scrollbar:

```css
g[role='tooltip'][visibility='hidden'] {
	transform: none;
}
```

However, neither of these hacks prevent the scrollbar from appearing at all.

Would it be possible to get rid of the use of transformations altogether and just place the tooltips using raw coordinates?

**Comment by dswitzer** [comment]
@martynasma,

Setting the overflow doesn't work for us, because the parent container of the chart is too small and the tooltips get cropped.

What about removing the transformations on the elements and just placing the positions based on simple X/Y coordinates?

That would appear to resolve the issue.

While not ideal, something that would at least sort of improve things is if the tooltips were actually removed from taking up DOM space when hidden. Right now, since only their visibility is hidden, the elements still take up DOM space. If the elements were removed from the DOM (display: none) or perhaps parked way to the left, it would at least remove the scrollbars when not mousing over an element. It's still not ideal that the scrollbars would appear when a tooltip is visible, but it's better.

**Comment by zeroin** [comment]
I don't think that will work - for example, when the map is zoomed, it is scaled and is bigger than the div. We can't remove part of the map. In charts we often have objects which are indeed bigger than div size and cutting them at the place where the div ends would require a lot of additional calculations which would affect performance. So I don't think we will go for this solution.

**Comment by dswitzer** [comment]
@zeroin  @martynasma 

From what I'm seeing, it looks like charts (or at least Pie charts) have a DOM hierarchy that looks something like:

```
<svg>
	<desc>...</desc>
	<defs>...</defs>
	<g> --> this is the main container
		<g></g> --> this is the background
		<g>
			<g role="region"></g> --> this is the background
			<g></g> --> this is holds the tooltips
		</g>
	</g>
</svg>
```

What if the "region" hide the overflow or used clip to reduce the element to only appear within the container. The container could still have elements that expands outside the main container.

Then the tooltips were positioned without using transform, but actual x/y coordinates.

I think that would solve the scrollbar issue. Since the charting could still be larger than the parent container, but it's content would be hidden. Since the tooltips aren't using transformations for position, it should avoid triggering the IE bug.

I'd also think avoiding transforming the tooltips would improve performance, but I could be wrong about that.

**Comment by martynasma** [comment]
@dswitzer My two cents.

SVG elements do not nest. Technically, it's possible to include another SVG as an `<image>` tag. However that brings whole other issues, such as we won't be able to target individual elements of the nested SVG, and even if we can, it introduces whole new level of complexity, because chart elements go levels deep.

Not to mention losing style inheritance such as `stroke` and `fill`.

**Comment by dswitzer** [comment]
You can indeed nest SVG elements:

https://www.sarasoueidan.com/blog/mimic-relative-positioning-in-svg/

You would lose inheritance, but seems like the tooltips have mostly their
own styles.

**Comment by martynasma** [comment]
Thanks for the links.

We're going to make a note to experiment with this at some point. As you can imagine it's not a straightforward change. Would need to test browser support, performance implications, etc.

At this point, I'm can't provide any specific time estimate for this.

**Comment by dswitzer** [comment]
Sure. I understand.

I wonder if it wouldn’t make more sense to move the tooltips into its own
SVG container and use a single tooltip for all charts. I’m sure that would
be a huge change and obviously affects styling, so it may be a difficult
change. However, it would reduce the SVG nodes being created, which could
help with multi-chart performance.

**Comment by martynasma** [comment]
Tooltip objects are already being reused whenever possible. So we probably would not gain much in terms of performance by "exiling" them into a separate SVG.

That would create a lot of additional logistical details, as you correctly pointed out.

Somehow going to great lengths and introducing additional code complexity just to work around a bug in a browser does not feel right. If you know what I mean.

We will keep this on our radar, though. Thank you for all the suggestions!

**Comment by BdDragos** [comment]
This issue is still there it seems, since when I have a configuration for a series = new am4charts.ColumnSeries() and a tooltip like this one:

    series.columns.template.tooltip = new Tooltip();
    series.columns.template.tooltipHTML = ' ';
    series.columns.template.tooltip.label.adapter.add('htmlOutput', function(text, target) {}

the tooltip still goes out of the chart bounds, and the <g> where the tooltips are situated is way bigger than the chart container.

Setting the tooltip pointerOrientation didn't help, neither for vertical or horizontal, since the center wasn't calculated like it is specified in the documentation (Options"horizontal" or "vertical" are location-aware, meaning they will change position of the Tooltip based on the target point's position in relation to chart center.)

![Annotation 2019-10-02 143329](https://user-images.githubusercontent.com/26300460/66041070-9fd92380-e521-11e9-8a41-3819480e3e9c.png)

**Comment by cangSDARM** [comment]
why this error didn't solved yet?

**Comment by cangSDARM** [comment]
This is initial chart looks like:
![截屏2020-05-09 14 19 33](https://user-images.githubusercontent.com/20441896/81465898-1e0c4f80-9200-11ea-959b-7be4a3262a73.png)

When I zoom in:
![截屏2020-05-09 14 20 36](https://user-images.githubusercontent.com/20441896/81465922-43995900-9200-11ea-94db-82c4a9f8e0cd.png)

**Comment by martynasma** [comment]
Just doing some spring cleaning. This seems to be fixed:

![image](https://user-images.githubusercontent.com/1458520/83778624-9fd28a00-a693-11ea-854d-69cbd92a39da.png)

@cangSDARM Yours is totally different issue. Axis tooltips follow totally different logic. If you want to pursue this, you can open a separate issue.

**Comment by abdurrehman-alphasquad** [comment]
Please can anyone help me how to give series tooltip height and overflow-x in react.js. I use maxHeight and height and also using css class with it but its not working.
