### ISSUE TITLE
Map SVG export creates invalid file in IE/Edge when map contains unicode/high ascii characters

### ISSUE THREAD

**Issue by xorspark** [amcharts/amcharts4#911]
When exporting [this map](https://s.codepen.io/team/amcharts/debug/012b2d3adfa4f308076826bef1b76dee) in IE or Edge as an SVG file, an invalid SVG file is created due to the non-escaped characters in the output file. Opening the resulting SVG file in any browser gives you the following error:

XML5617: Illegal XML character.
File: amCharts.svg, Line: 1, Column: 254601

This corresponds to the node containing Piteå. This issue doesn't occur when exporting with Firefox or Chrome.

**Comment by martynasma** [comment]
Looks like it is related to Unicode symbols, like "Piteå".

I'm chalking it as a bug. Will see if we can somehow escape on SVG export.

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by martynasma** [comment]
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
