### ISSUE TITLE
Series with bullets do not show tooltips

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#913]
I updated my amCharts v4.0.21 to v4.1.0 to fix overlapping tooltips of series, when hovering with the cursor. But now, I have no tooltips at all for the series. If I remove the bullets, the tooltips work, but with bullets, they do not work any longer.
https://codepen.io/anon/pen/wREbmb

**Comment by zeroin** [comment]
Try setting `chart.dateFormatter.inputDateFormat = "yyyy";` it should fix this issue. Then you have single digits as your dates in data, chart doesn't properly parse them as it doesn't actually know what kind of date is this. And this causes to some weird problems like the one with tooltip.

**Comment by martynasma** [comment]
This is now a workaround. You provided a demo which has dates set as year strings, hence setting propert `inputDateFormat` is a perfectly valid action.

If you say you have different data, can you please provide a CodePen that is closer to your setup, so that we can take a look ant provide a relative solution, or determine it's a bug?

**Comment by martynasma** [comment]
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
