### ISSUE TITLE
Y CategoryAxis and missing values

### ISSUE THREAD

**Issue by bmampaey** [amcharts/amcharts4#914]
This problem could be related to issue #889

When plotting a XYChart with a CategoryAxis on the Y axis, the first values or last values may be missing depending on the order of the values.

I made a codepen as an example: https://codepen.io/Benjamin-Mampaey/pen/gqgBWo

With the following data : 

    var data = [
    {'date': '2010-01-01T00:00:00Z', 'value': 'Red'},
    {'date': '2010-01-01T00:30:00Z', 'value': 'Red'},
    {'date': '2010-01-01T01:00:00Z', 'value': 'Blue'},
    {'date': '2010-01-01T01:30:00Z', 'value': 'Blue'},
    {'date': '2010-01-01T02:00:00Z', 'value': 'Red'},
    {'date': '2010-01-01T02:30:00Z', 'value': 'Red'},
    {'date': '2010-01-01T03:00:00Z', 'value': 'Blue'},
    {'date': '2010-01-01T03:30:00Z', 'value': 'Blue'},
    {'date': '2010-01-01T04:00:00Z', 'value': 'Red'},
    {'date': '2010-01-01T04:30:00Z', 'value': 'Red'},
    ];

If I define the Y axis like below, the last values (Red) are not plotted.
![red - green - blue](https://user-images.githubusercontent.com/3693702/52062345-a6696280-2570-11e9-9528-8990cd3822a7.png)

	"yAxes": [{
		"type": "CategoryAxis",
		"data": [
			{"value": 'Red'},
			{"value": 'Green'},
			{"value": 'Blue'},
		],
		"dataFields": {
			"category": "value"
		},
	}],

If I define the Y axis like below, the first values (Red) are not plotted.
![blue - green - red](https://user-images.githubusercontent.com/3693702/52062330-a1a4ae80-2570-11e9-849c-bc59b27031ab.png)

	"yAxes": [{
		"type": "CategoryAxis",
		"data": [
      {"value": 'Blue'},
			{"value": 'Green'},
      {"value": 'Red'},
		],
		"dataFields": {
			"category": "value"
		},
	}],

**Comment by martynasma** [comment]
Yup, looks like identical bug with #889.

I'm going to mark this as a duplicate for now. Make sure you subscribe to #889 as well so you can check if this fixes your issue as well, when it is fixed.

Cool?

**Comment by martynasma** [comment]
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
