### ISSUE TITLE
LineSeries dateX/Y tooltip does not match axis label

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#95]
When you have a LineSeries based on a date category, the `{dateX}` and `{dateY}` values you use in a tooltip do not match the label drawn on the axis.

If you look at the example below, when you mouse over the data points the value of the `{dateX}` is going to be a year-month-day, but the xAxis shows a time.

https://codepen.io/anon/pen/oyqmJL

It seems like the `{dateX}` and `{dateY}` value should match the format of the axis, so the users sees a label which matches what they're already seeing on the screen.

It would be great if the `dataItem` property of the target of a hit event, would include this label as well—or at least have a way to translate the value to the same formatting rules as the axis is currently using.

**Comment by martynasma** [comment]
We have had a lot of discussions about this topic. The verdict that it should work as it is now. Let me explain.

DateAxis is an intelligent being, which chooses granularity of labels based on the distance between them and scope of time.

Even if you have hourly data and therefore a label each hour on the X axis, your cursor may be positioned anywhere in-between. It would make much less sense to show 1PM while hovering anywhere between 1PM and 2PM, then to show exact minute of the position.

Similarly, on a ValueAxis (which DateAxis inherits from) it would not make sense to show static values between actual labels. I.e. if we have labels at 100, 200, 300 when you move cursor along the axis you would get axis tooltips with intermediate values.

That said, it's totally up to you to set the format for your axis tooltip using axis' [`tooltipDateFormat`](https://www.amcharts.com/docs/v4/reference/dateaxis/#tooltipDateFormat_property).

Some info [here](https://www.amcharts.com/docs/v4/concepts/axes/axis-tooltips/#Tooltip_value_format) as well.

P.S. which hit event are you referring to?

P.P.S. I'm going to close this so that dev team is not sidetracked by issues. But feel free to reply to this thread in case you have any further questions, or think that what I wrote above does not make sense.
