### ISSUE TITLE
4.1.5 breaks PNG export with Axis fill dropping over legend

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#955]
related to fixing #841  now the PNG export on other browsers fails (Angular + Webpack) 
![amcharts 14](https://user-images.githubusercontent.com/1268723/52586650-51fb9800-2e38-11e9-90e6-265138729d59.png)

**Comment by martynasma** [comment]
Thanks. Yes, the fix in 4.1.5 broke export.

Fixed in dev. Will release today/tomorrow.

**Comment by martynasma** [comment]
Fixed in [4.1.6](https://github.com/amcharts/amcharts4/releases/tag/4.1.6).

## [4.1.6] - 2019-02-12

### Added
- New plugin chart type: [`Sunburst`](https://www.amcharts.com/docs/v4/chart-types/sunburst/)!
- New `Sprite` adapter: `criticalError`. Takes `Error` object as an argument. Modify it's `message` property.

### Fixed
- Export was somewhat broken in Angular apps or pages with `<base>` since 4.1.5.
- `DateAxis` was not positioning elements properly when spanning switch to/from daylight savings time.
- `valign` property of the horizontal axis labels now work properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
