### ISSUE TITLE
How can truncate rotated label on categoryAxis ?

### ISSUE THREAD

**Issue by rkovalyov** [amcharts/amcharts4#964]
**See example**
- https://codepen.io/anon/pen/aXjGLE?&editable=true
```
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.truncate = true;
categoryAxis.renderer.labels.height = 50;
categoryAxis.height = 50;
```

**Comment by rkovalyov** [comment]
And I noticed that adapter doest invoke on resize event

```
const updateLabel = () => {
    categoryAxis.renderer.labels.template.adapter.add(
    'text',
    (label) => {
       console.log(label); // doesnt works, I try to truncate labels manualy
       return label;
    },
  );
}
const cb = debounce(updateLabel, 300, { leading: true });
categoryAxis.events.on('validated', cb);
```

**Comment by martynasma** [comment]
First of all, your code contains error. You're setting `truncate` and `height` on labels list, not on a template.

Second, you should still set `width` or `maxWidth` since only width controls label truncation, even if its rotated:

```
categoryAxis.renderer.labels.template.truncate = true;
categoryAxis.renderer.labels.template.width = 50;
```

Adapters on label's `text` are invoked only when label is redrawn. If the chart deems it unnecessary to redraw it, e.g. it displays label for the same timestamp, even if different place, it does not redraw it.
