### ISSUE TITLE
Error: '.../ResizeSensor.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by alexandru-tomescu** [amcharts/amcharts4#977]
Hi. We are trying to check if amcharts suits our needs in our project, but when trying to use it with ES6 module we are getting the following error:

`app.js:242 Uncaught (in promise) SyntaxError: The requested module '../../../../../../../css-element-queries/src/ResizeSensor.js' does not provide an export named 'default'`

PS: We tried install to npm and load items in the code both from npm package and github repo:

```
import * as am4core from '@amcharts/amcharts4/dist/es2015/core.js';
import * as am4charts from '@amcharts/amcharts4/dist/es2015/charts.js';
import am4themes_animated from '@amcharts/amcharts4/dist/es2015/themes/animated.js';
```

**Comment by Pauan** [comment]
You shouldn't be loading from `/dist`, just importing `@amcharts/amcharts4/core.js` should work.

Also, it sounds like you're not using a bundler like Webpack. You really should be using Webpack:

https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/

The reason is because ES6 modules are not supported natively in older browsers, and also there are many JavaScript libraries which depend upon Webpack to work (such as `css-element-queries`).

Having said that, I'll see if we can workaround that specific error.

**Comment by Pauan** [comment]
@alexandru-tomescu By the way, can you share your code with us? That will make it easier for us to debug and fix this problem.

**Comment by Pauan** [comment]
If you're not comfortable sharing your code publicly, you can send it in a `.zip` file to my e-mail (pcxunlimited@gmail.com)

Of course I will keep it completely secret, only using it to help fix this issue.

**Comment by alexandru-tomescu** [comment]
@Pauan i also imported from `@amcharts/amcharts4/core.js` but still the same error (i mentioned it). Basically we are trying to use amcharts in a Polymer based project (polymer cli + lit element) which i think doesn't compile anything when serving via development web server (`polymer serve`). I pretty sure polymer cli uses webpack to compile, but when build the project. Right now amcharts are working only if importing the source via index.html, but we want to use it with es6 modules.

Importing it from the npm package we receive the same error
```
import * as am4core from '@amcharts/amcharts4/core.js';
import * as am4charts from '@amcharts/amcharts4/charts.js';

**Comment by alexandru-tomescu** [comment]
Can you solve this guys ? Thank you :)

**Comment by Pauan** [comment]
@alexandru-tomescu It's very odd that Polymer would run Webpack in build mode but not dev mode.

Most npm packages use CommonJS, not ES6 modules, and therefore they *require* Webpack.

I looked into it, but unfortunately I don't think there's much we can do. The issue isn't with amCharts.

The fundamental issue is that the `css-element-queries` npm package is using CommonJS, and therefore you must use Webpack (or another bundler, like Parcel, Rollup, etc.).

Polymer doesn't use Webpack, and therefore most npm packages are broken with Polymer.

So I recommend filing a bug report with Polymer. If their goal is to reduce compile times, they should use Webpack's dev + watch mode, which is usually quite fast.

**Comment by Pauan** [comment]
I found an existing bug report, here is their response:

https://github.com/Polymer/polymer/issues/5342#issuecomment-415458851

Perhaps if enough developers politely ask, they will add in support for CommonJS.

Since CommonJS is so extremely common with npm packages, I'm surprised that they are specifically not supporting it.

In any case, this is clearly Polymer's responsibility, not amCharts.

**Comment by alexandru-tomescu** [comment]
@Pauan thank you for the response and your time. I will open an issue to Polymer CLI.
