### ISSUE TITLE
DateAxis cursor tooltip shows incorrect year if timeUnit is year

### ISSUE THREAD

**Issue by donnysim** [amcharts/amcharts4#986]
https://codepen.io/anon/pen/pGGEbZ

It keeps showing incorrect tooltip date on the x axis, the date is 2018, but tooltip shows 2017.
If you set `utc = true` then the dates become 1 year less no matter what you set it to, so 2018-01-01 becomes 2017-12-31, even 2018-12-31 is still kept as 2017-12-31.

**Comment by martynasma** [comment]
Thanks for the heads up.

![2019-02-19_15-59-24](https://user-images.githubusercontent.com/1458520/53020335-5ab72400-345f-11e9-8e03-071b6253db65.gif)

Simplified example:
https://codepen.io/team/amcharts/pen/1fe43f4a3bf5e6a608d37d31a09e5527?editors=0010

**Comment by martynasma** [comment]
Fixed in [4.1.9](https://github.com/amcharts/amcharts4/releases/tag/4.1.9).

## [4.1.9] - 2019-02-20

### Added
- New `Sprite` property: `baseSprite`. On objects, even deep in hierarchy it will contain a reference to the main chart object.

### Changed
- Axis `min`/`max` calculation algorightm updated.

### Fixed
- On a chart with `DateAxis` and multiple series with same-date data items, bullets could sometimes disappear while scrolling the chart.
- On `DateAxis` with yearly granularity could sometimes show wrong year.
- Updating chart `data` with less data points was sometimes resulting in JavaScript error.
- `DateAxis` labels/ticks/grid was not placed in the correct position if `baseInterval.count > 1` and `location > 0`.
- Dynamically changing `ZoomControl` value of `layout` was not working correctly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
