### ISSUE TITLE
valueY doesn't work in legendSettings.itemLabelText

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#994]
I can display `valueY` in `itemValueText` like this:

```
series4.legendSettings.valueText = "{valueY.close}";
series4.legendSettings.itemValueText = "[bold]{valueY}[/bold]";
```

But I cannot display `valueY` in `itemLabelText`:

```
series4.legendSettings.labelText = "{name}: {valueY.close}";
series4.legendSettings.itemLabelText = "{name}: [bold]{valueY}[/bold]"; // valueY is empty
```

I have disabled `valueLabels` as I want to remove the gap between the two columns (label and value):

```
chart.legend.valueLabels.template.disabled = true;
```

Codepen demo: https://codepen.io/team/amcharts/pen/JeeRaZ?editors=0010.

Hover over any column and see the `valueY` between parentheses is missing.

**Comment by martynasma** [comment]
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
