### ISSUE TITLE
Question: amcharts 4 state abbreviations as labels over US map

### ISSUE THREAD

**Issue by ljubo2015** [amcharts/amcharts4#995]
Hello all,
I am having issue adding states labels on map. Small states are not really visible and i would like to put labels.
![usamap](https://user-images.githubusercontent.com/15197215/53055083-c5d81900-34a6-11e9-9e09-c2b665b54177.png)

Something similar was done with version 3 but so far i was not successful translating this to version 4 : https://www.amcharts.com/docs/v3/tutorials/display-state-abbreviations-as-labels-over-us-map/

here is my code so far:
                    // Themes begin
                    am4core.useTheme(am4themes_animated);

                    // Create map instance
                    chart = am4core.create("chartdiv", am4maps.MapChart);

                    // Set map definition
                    chart.geodata = am4geodata_usaTerritoriesHigh;

                    // Set projection
                    chart.projection = new am4maps.projections.Miller();

                    // Create map polygon series
                    polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());

                    //Set min/max fill color for each area
                    polygonSeries.heatRules.push({
                        property: "fill",
                        target: polygonSeries.mapPolygons.template,
                        min: chart.colors.getIndex(1).brighten(1),
                        max: chart.colors.getIndex(1).brighten(-0.3)
                    });

                    let mapbg = polygonSeries.mapPolygons.template;
                    mapbg.fill = am4core.color("#d8dee7");

                    // Make map load polygon data (state shapes and names) from GeoJSON
                    polygonSeries.exclude = ["US-AS","US-VI","US-GU","US-MP"];
                    polygonSeries.useGeodata = true;
                    polygonSeries.propertyFields.fill = "name";
                    // Set heatmap values for each state

                    // Set up heat legend
                    let heatLegend = chart.createChild(am4maps.HeatLegend);
                    heatLegend.series = polygonSeries;
                    heatLegend.align = "right";
                    heatLegend.width = am4core.percent(25);
                    heatLegend.marginRight = am4core.percent(4);
                    heatLegend.minValue = 0;
                    heatLegend.maxValue = 300;

                    polygonSeries.mapPolygons.template.events.on("over", function(ev) {
                        if (!isNaN(ev.target.dataItem.value)) {
                            heatLegend.valueAxis.showTooltipAt(ev.target.dataItem.value)
                            //console.log(ev.target.dataItem.dataContext.modalUrl);
                        } else {
                            heatLegend.valueAxis.hideTooltip();
                        }
                    });
                    polygonSeries.mapPolygons.template.events.on("hit", function(ev) {
                        if (!isNaN(ev.target.dataItem.value)) {
                            window.open(ev.target.dataItem.dataContext.modalUrl, '_self');
                        } else {
                            heatLegend.valueAxis.hideTooltip();
                        }
                    });
                    polygonSeries.mapPolygons.template.events.on("out", function(ev) {
                        heatLegend.valueAxis.hideTooltip();
                    });
                    // Set up custom heat map legend labels using axis ranges
                    var minRange = heatLegend.valueAxis.axisRanges.create();
                    minRange.value = heatLegend.minValue;
                    minRange.label.text = "Little";
                    var maxRange = heatLegend.valueAxis.axisRanges.create();
                    maxRange.value = heatLegend.maxValue;
                    maxRange.label.text = "A lot!";

                    // Blank out internal heat legend value axis labels
                    heatLegend.valueAxis.renderer.labels.template.adapter.add("text", function(labelText) {
                        return "";
                    });
                    // Configure series tooltip
                    polygonTemplate = polygonSeries.mapPolygons.template;

                    // Create hover state and set alternative fill color
                    var hs = polygonTemplate.states.create("hover");
                    hs.properties.fill = am4core.color("#26539b");
                    // Add zoom control
                    chart.zoomControl = new am4maps.ZoomControl();
                    chart.zoomControl.align = "left";
                    //Create button zoom in zoom out and go home
                    var button = chart.chartContainer.createChild(am4core.Button);
                    button.padding(5, 5, 5, 5);
                    button.width = 20;
                    button.align = "left";
                    button.marginRight = 10;
                    button.events.on("hit", function() {
                        chart.goHome();
                    });
                    button.icon = new am4core.Sprite();
                    button.icon.path = "M16,8 L14,8 L14,16 L10,16 L10,10 L6,10 L6,16 L2,16 L2,8 L0,8 L8,0 L16,8 Z M16,8";

I am really appreciate any tip or help.

**Comment by ljubo2015** [comment]
Hello all,
Anyone had experience with this, i am stuck on this for 2 days ..without any luck :(

**Comment by notacouch** [comment]
Hello @ljubo2015 , I know we don't have an open example for putting labels on maps. I'm sure we will work on having a demo or guide for that eventually, no ETA on that, though.

To add labels to a `MapChart`, you'll need to make a `MapImageSeries`. `MapImage`s are `Container`s that can take geographic coordinates, think of them as invisible pins on the map whose children (non-map-related children, like a `Label`!) (via `series.mapImages.template.createChild(...)`) will show up where you want on the map.

Labels can be set up like so:

```javascript
var imageSeries = chart.series.push(new am4maps.MapImageSeries());
var mapImageTemplate = imageSeries.mapImages.template;
mapImageTemplate.propertyFields.latitude = "latitude";
mapImageTemplate.propertyFields.longitude = "longitude";

var labelTemplate = mapImageTemplate.createChild(am4core.Label);
labelTemplate.text = "{id}";
labelTemplate.horizontalCenter = "middle";
labelTemplate.verticalCenter = "middle";
labelTemplate.textAlign = "middle";
labelTemplate.interactionsEnabled = false; // let hover pass through, this way a country's hover effect is maintained
```

Now we just need data for our `mapImages` that must have `latitude`, `longitude`, and a 2-letter `id`. If you have those, you can provide it via `mapImageSeries.data = [...];`, otherwise, we can rely on the `polygonSeries`. Once the `mapPolygons` have loaded, their center coordinates will be calculated and stored in their `latitude` and `longitude` properties. 

```javascript
polygonSeries.events.once("datavalidated", function(){
  var imageData = [];
  polygonSeries.mapPolygons.each(function(polygon) {
    var stateData = polygon.dataItem.dataContext;
    var stateLabelData = {
      latitude: polygon.latitude,
      longitude: polygon.longitude,
      id: stateData.id.substr(3) // stateData.id.replace(/US-/, '')
    }
    imageData.push(stateLabelData);
  });
  imageSeries.data = imageData;
});
```

Demo:
https://codepen.io/team/amcharts/pen/5ae84826c9e2ab4772c9ef85021835c7

Bear in mind the center coordinates are based roughly on a rectangular area, therefore there's a good chance for that calculation to not represent the actual "visual" center of the map polygon or U.S.A. State in this case. You'll have to provide your own coordinates to fix that.

Also in the demo I've provided v4 ways of things you're trying to do.

To show a tooltip, all you need is `tooltipText` to be non-empty. So to hide a tooltip, you can use an [adapter](https://www.amcharts.com/docs/v4/concepts/adapters/) to reset the value so it's empty, e.g.:

```javascript
polygonTemplate.adapter.add("tooltipText", function(tooltipText, polygon) {
  if (isNaN(polygon.dataItem.dataContext.value)) {
    return "";
  }
  return tooltipText;
});
```

If you want to hide a tooltip on clicking a polygon it helps to know some things. The tooltip for the `mapPolygons` is like a singleton instance, the actual tooltip object is on the `polygonSeries` itself, shared between the `mapPolygons`. So the business logic of checking if there's a numeric value no longer applies, b/c with the adapter in place the tooltip will not have arisen in the first place. So we can just focus on hiding the tooltip regardless. There are multiple ways of doing that within the `"hit"` event:

```javascript
polygonTemplate.events.on("hit", function(event) {
  // polygonSeries.tooltip.hide(); // not preferred, but does the job
  // polygonSeries.hideTooltip();
  event.target.hideTooltip();
});
```

As for opening an url on hit, many of our Objects have an [`url` property](https://www.amcharts.com/docs/v4/reference/mappolygon/#url_property), it can be set via property binding:

```javascript
polygonTemplate.propertyFields.url = "modalUrl";
polygonTemplate.urlTarget = "_self";
```

And reset via an adapter in light of business logic:
```javascript
polygonTemplate.adapter.add("url", function(url, polygon) {
  // if data isn't ready, or value isn't a number, kill the url if it has one
  if (! polygon.dataItem || !polygon.dataItem.dataContext || isNaN(polygon.dataItem.dataContext.value)) {
    return "";
  }
  return url;
});
```

Once an `url` is applied, the hover cursor is changed to pointer. Since the adapter is triggered on click, i.e. after hover, we need to reset this sooner, here's one possibility:

```javascript
polygonSeries.events.on("datavalidated", function() {
  polygonSeries.mapPolygons.each(function(polygon) {
    // Since we only set url via property binding, if it has an url
    // already, then it definitely has the dataItem.dataContext,
    // but maybe not a value.
    if (polygon.properties.url && isNaN(polygon.dataItem.dataContext.value)) {
      polygon.cursorOverStyle = am4core.MouseCursorStyle.default;
    }
  });
})
```

Hope this helps!

**Comment by martynasma** [comment]
OK, so life just got a little bit easier :)

More details here:
https://www.amcharts.com/docs/v4/tutorials/automatic-labels-over-map-polygons/
